### ISSUE TITLE
[NTR]enteroendocrine cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1000]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enteroendocrine cell of appendix

**Synonyms**
enteroendocrine cell of vermiform appendix
enteroendocrine cell of appendix vermiformis

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enteroendocrine cell that is located in the vermiform appendix. Enteroendocrine cells are scattered throughout the epithelial layer of the gut wall and produce gut hormones. Enteroendocrine cells are in a continuous state of cell turnover, being replaced by a cycle of local stem cell division that gives rise to all the epithelial cell types, including enterocytes, mucus-producing goblet cells, enteroendocrine cells, tuft cells and Paneth cells. Intestinal enteroendocrine cells are embedded within a polarized absorptive epithelium and have an apical membrane facing directly into the gut lumen and a basolateral surface facing the interstitial space, giving rise to the term ‘open-type’ enteroendocrine cell. PMID: 30760847

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal enteroendocrine cell http://purl.obolibrary.org/obo/CL_1001516

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009030 (enteroendocrine cell of appendix)
