### ISSUE TITLE
[NTR]: medullary lymphocyte

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#1001]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
medullary lymphocyte

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A lymphocyte which is temporarily residing in the medulla of the lymph node.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
lymphocyte: http://purl.obolibrary.org/obo/CL_0000542

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node: http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**
As discussed with @paolaroncaglia this is a located in term for the SCA anatomograms.

**Comment by addiehl** [comment]
Are you sure you can't be more precise about whether the lymphocyte is a T cell or B cell?  It really is not helpful just to identify cells as lymphocytes.  Do you have any marker or functional information?

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
We discussed this request on today's CL and Uberon editors' call. I presented the anatomograms use case, and SCA's need for grouping terms based on anatomical location. While it's easier to justify the creation of several other CL and Uberon terms you and @sfexova requested recently, @addiehl is more concerned about lymphocite and lymph node-related classes. Ideally, given the amount of literature and evidence for these areas, we'd want to provide more detail than what you have currently. It'd be a better service to the community including your users. I understand that it may not be possible to modify most of teh anatomograms that you already have, but for lymphocite and lymph node-related requests alone, could you please review them and see if you could use more granular terms? E.g. as Alex suggested
 
> Are you sure you can't be more precise about whether the lymphocyte is a T cell or B cell? It really is not helpful just to identify cells as lymphocytes. Do you have any marker or functional information?

Here we could also create two classes (medullary T cell + medullary B cell) if you can use/locate them in your anatomograms.

Note for self:
- [ ] Mention use case more explicitly in new term(s), e.g. "do not use for annotation" if the term is generic and one could use a more specific term, and/or indicate that the term will be used in an anatomogram.

**Comment by addiehl** [comment]
Also, I would like to point out that there are medulla in other organs, such as the thymus or the brain (medulla oblongata), and therefore new classes in the CL for T cells and B cells of the lymph node medulla should be called some like 'T cell of the lymph node medulla' and 'B cell of the lymph node medulla' so that the anatomical location of these cells is not ambiguous.

**Comment by ngeorgeebi** [comment]
Thanks @addiehl and @paolaroncaglia for the feedback here! This is unfortunately a really generalised term but I would actually assume a mix of B and T lymphocytes located in the medullary sinus of the lymph node. These would be a range of activated lymphocytes on their way back out of the lymph node via the efferent vesicles - but i can definitely see where you guys are coming from! I was mostly wondering what would be the best way to represent this term. Also as in discussion with @paolaroncaglia, the issue came up that we are trying to find stationary terms for non-stationary entities, which is very difficult. Our aim for the anatomograms is to represent this cells in the most versatile way so users can a. find the cell type in the anatomograms and b. use this to anotate their terms when providing inferred cell type. If as I am assuming would be the best way forward is to sidestep the term lympocyte entirely and create the two terms: B cell of medullary sinus of lymph node and T cell of medullary sinus of lymph node then this would be a good compromise for us if it works for you as well :)

**Comment by addiehl** [comment]
I would be happy with 'B cell of medullary sinus of lymph node' and 'T cell of medullary sinus of lymph node'.

**Comment by ngeorgeebi** [comment]
Thank you @addiehl and @paolaroncaglia I think that should work well :) . Should I make the two new term requests?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

> Should I make the two new term requests?

No need to, I'll take it from here ;-)
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
As agreed above, I added 
CL_0009045 (B cell of medullary sinus of lymph node)
and
CL_0009046 (T cell of medullary sinus of lymph node).
