### ISSUE TITLE
[NTR]: medullary sinus macrophage

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#1002]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
medullary sinus macrophage

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A macrophage that is temporarily residing the medullary sinus of the lymph node.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
macrophage: http://purl.obolibrary.org/obo/CL_0000235

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node: http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
CL_0009047 (macrophage of medullary sinus of lymph node)
