### ISSUE TITLE
[NTR] T cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1018]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
T cell of appendix

**Synonyms**
T cell of appendix vermiformis
T cell of vermiform appendix

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
T cell that is located in the appendix vermiformis. T cell is a type of lymphocyte whose defining characteristic is the expression of a T cell receptor complex. PMID: 24292902

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
http://purl.obolibrary.org/obo/CL_0000084

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009031 (T cell of appendix)

Here's the current hierarchy in Protege. (I haven't expanded all terms, but you may view them in OLS). As you can see, the new term is a bit of an outlier. If you think it's possible to specify anything more about the T cells in question, please open a new ticket and I'll be happy to modify the term (not the ID, so you can use CL_0009031 as soon as you need to). Thanks.
![Screen Shot 2021-04-22 at 18 36 17](https://user-images.githubusercontent.com/4982516/115751720-bbbd4800-a399-11eb-8055-d4b4671f371c.png)
