### ISSUE TITLE
[NTR] B cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1019]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
B cell of appendix

**Synonyms**
B cell of vermiform appendix
B cell of appendix vermiformis

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
B cell that is located in the appendix vermiformis. B cells are at the centre of the adaptive humoral immune system and are responsible for mediating the production of antigen-specific immunoglobulin (Ig). PMID: 31002794

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
B cell http://purl.obolibrary.org/obo/CL_0000236

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009032 (B cell of appendix)

Please open a new ticket if we can make the term more specific:
![Screen Shot 2021-04-22 at 18 42 22](https://user-images.githubusercontent.com/4982516/115752985-f2479280-a39a-11eb-9b85-3417e48f43ca.png)
