### ISSUE TITLE
[NTR] plasma cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1020]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
plasma cell of appendix

**Synonyms**
plasma cell of vermiform appendix
plasma cell of appendix vermiformis

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Plasma cell that is located in the appendix vermiformis. Plasma cell is a terminally differentiated, post-mitotic, antibody secreting cell of the B cell lineage. Plasma cells are oval or round with extensive rough endoplasmic reticulum, a well-developed Golgi apparatus, and a round nucleus having a characteristic cartwheel heterochromatin pattern and are devoted to producing large amounts of immunoglobulin. PMID: 25698678

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
plasma cell http://purl.obolibrary.org/obo/CL_0000786

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009033 (plasma cell of appendix)

![Screen Shot 2021-04-22 at 18 47 00](https://user-images.githubusercontent.com/4982516/115753146-27ec7b80-a39b-11eb-8af6-72b5eed0038d.png)
