### ISSUE TITLE
[NTR] Immature Enterocyte

### ISSUE THREAD

**Issue by chenlingantelope** [obophenotype/cell-ontology#1028]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)** PMID: 33290721

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**CL:0000584 enterocyte; CL:0002563 ! intestinal epithelial cell

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**intestineUBERON:0000160

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-9610-7627

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Note to self: 'lysosome-rich enterocyte' = "...In mammals they are found in the ileum pre-weaning and later are replaced by mature enterocytes." => check if 'lysosome-rich enterocyte' is the same thing that the requested "immature enterocyte" refers to.
