### ISSUE TITLE
[NTR] Mature Enterocyte

### ISSUE THREAD

**Issue by chenlingantelope** [obophenotype/cell-ontology#1029]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

Preferred term label:Mature Enterocyte

Synonyms

Definition (free text, please give PubMed ID in format PMID:XXXXXX) PMID: 33290721

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**CL:0000584 enterocyte; CL:0002563  intestinal epithelial cell

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**intestine UBERON:0000160

Your nano-attribution (ORCID)
https://orcid.org/0000-0001-9610-7627

**Comment by paolaroncaglia** [comment]
Notes to self: the reference provided PMID:33290721 mentions mature/differentiated enterocytes. In the absence of feedback from the submitter, 
- [ ] I'll add "mature enterocyte" and differentiated enterocyte" as narrow synonyms of CL:0000584 'enterocyte', with AP dbxref PMID:33290721.
