### ISSUE TITLE
[NTR]alveolar fibroblast

### ISSUE THREAD

**Issue by chenlingantelope** [obophenotype/cell-ontology#1030]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**alveolar fibroblast

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**Classical fibroblast markers (BSG and COL1A2) that  localized to alveoli with additional markers (SPINT2+FGFR4+GPC3+) PMID: 33208946 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):** CL:0002553, fibroblast of lung

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**lungUBERON:0002048

**Your nano-attribution (ORCID)**https://orcid.org/0000-0001-9610-7627

**Any additional notes or concerns**

**Comment by JoshuaFortriede** [comment]
This new term has been added as "alveolar type 1 fibroblast cell" and has an ID of CL:4028004. The term "alveolar fibroblast" has been added as a synonym.

**Comment by brianpenghe** [comment]
Type 1 alveolar cell (AT1) is a totally different cell type. Is it possible to use "Alveolar fibroblast (type) 1" or something?

**Comment by bvarner-ebi** [comment]
@JoshuaFortriede, checking in on this ticket.
Can this be closed or does it require additional work?
I see [the comment above](https://github.com/obophenotype/cell-ontology/issues/1030#issuecomment-1157081072), which may have triggered the ticket to be reopened, but it is unclear to me how it relates to this ticket.

**Comment by bvarner-ebi** [comment]
Closing this ticket as it appears done and there has been no recent follow up.
