### ISSUE TITLE
[NTR]capillary aerocyte

### ISSUE THREAD

**Issue by chenlingantelope** [obophenotype/cell-ontology#1031]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**capillary aerocyte

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)** A subtype of capillary cell in lung. PMID: 33208946 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):** CL:0000115 ! endothelial cell

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**lungUBERON:0002048

**Your nano-attribution (ORCID)**https://orcid.org/0000-0001-9610-7627

**Any additional notes or concerns**

**Comment by JoshuaFortriede** [comment]
This term has been added as "alveolar capillary type 2 endothelial cell" and has an ID of CL:4028003
