### ISSUE TITLE
[NTR] telocyte

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1048]
**Preferred term label:**
telocyte

**Synonyms**
interstitial Cajal-like cell; ICLC; interstitial Cajal cell-like cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A cell with a small, oval-shaped body with around 10 micrometers of diameter present in the interstitium. It has one to five long cytoplasmic protrusions (telopodes) extending from tens to hudreds of micrometers and mostly below 0.2 microns of caliber. PMID:20367664

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0000630 (supportive cell) is one possibility. 

Maybe a parent new term "interstitial cell" could be interesting.  

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

Found in a number of different organs, including kidney, heart, pancreas, placenta and more. I am not sure which to add. In addition, telocytes in different tissues might have different markers and execute different functions. 

**Your nano-attribution (ORCID)**
0000-0003-2473-2313

**Any additional notes or concerns**

Has a few possible crossrefs: 

**Wikipedia**: https://en.wikipedia.org/wiki/Telocyte
**MeSH**: https://meshb.nlm.nih.gov/record/ui?ui=D000067170
**Wikidata**: https://www.wikidata.org/wiki/Q7697784

**Comment by lubianat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import GitHub issues assigned to me](https://trello.com/c/sLWt8New/4-import-github-issues-assigned-to-me)

**Comment by lubianat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Proceed with Telocyte integration](https://trello.com/c/1xEKPnNj/5-proceed-with-telocyte-integration)

**Comment by paolaroncaglia** [comment]
@lubianat commenting to prevent closure - there's a PR for this term but it's stalled.
