### ISSUE TITLE
Alveolar Fibroblast 1 [NTR]

### ISSUE THREAD

**Issue by AnnekarinaPerl** [obophenotype/cell-ontology#1053]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Alveolar Fibroblast 1

**Synonyms**
Lipofibroblast, Matrix Fibroblast 1

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Fibroblast like morphology, contains lipid vesicles in early murine lung development.
Key source of FGF7 and FGF10.
Marker genes : TCF21 and WNT2
Marker Proteins: PLIN/ADRP
proliferative in response to injury
PMID:29489752 
PMID:33707239
PMID:30675802
PMID:
[Alveolar Fibroblast 1.docx](https://github.com/obophenotype/cell-ontology/files/6385290/Alveolar.Fibroblast.1.docx)
33624948

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
pulmonary interstitial fibroblast CL0002241

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
alveolus

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-8445-4565

**Any additional notes or concerns**
@addiehl

**Comment by paolaroncaglia** [comment]
Duplicate of #1030 and/or #1280 ?

**Comment by dosumis** [comment]
CC @JoshuaFortriede

**Comment by JoshuaFortriede** [comment]
This new term has been added as "alveolar type 1 fibroblast cell" and has an ID of CL:4028004. The requested term name has been added as a synonym, along with the synonyms "Lipofibroblast" and "Matrix Fibroblast 1". PMIDs have been added as well. The marker genes were not added yet as the best method of this is still being determined.
