### ISSUE TITLE
Alveolar Fibroblast 2 [NTR]

### ISSUE THREAD

**Issue by AnnekarinaPerl** [obophenotype/cell-ontology#1054]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Alveolar Fibroblast 2

**Synonyms**
Matrix Fibroblast 2, Mesenchymal alveolar niche cell, Type-2 associated stromal cell (TASC)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Fibroblast like morphology
Source of Signals: FGF7, FSTL1, WNT5A, IL6
Support AT2 cell proliferation and differentiation during postnatal maturation, homeostasis and regeneration
Source of extra cellular matrix proteins
Marker Genes: MFAP5, SCARA5
PMID:26706109
PMID:28886382
PMID:30675802
PMID:29752282
PMID:33624948

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
pulmonary interstitial fibroblast CL0002241

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
alveolus

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-8445-4565

**Any additional notes or concerns**
@addiehl 

[Alveolar Fibroblast 2.docx](https://github.com/obophenotype/cell-ontology/files/6385293/Alveolar.Fibroblast.2.docx)

**Comment by bvarner-ebi** [comment]
@JoshuaFortriede, checking in on the status of this ticket. 
Is this the same term requested in this ticket:  ['alveolar type 2 fibroblast cell'](http://purl.obolibrary.org/obo/CL_4028006) ? If so, would you kindly close this ticket?

**Comment by bvarner-ebi** [comment]
Closing this ticket as it appears done and there has been no recent follow up.
