### ISSUE TITLE
Mucous Cell [NTR]

### ISSUE THREAD

**Issue by AnnekarinaPerl** [obophenotype/cell-ontology#1057]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Mucous cell

**Synonyms**
none

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Mucous secreting cell in the submucosal gland of the lung
[Mucous cells.docx](https://github.com/obophenotype/cell-ontology/files/6385596/Mucous.cells.docx)
Marker Genes: MUC5B, SPEDEF
PMID:19759516
PMID:26336032

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
mucous gland of lung 

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
Submucosal glands (SMG) line the mucous tubules that are located between the collecting ducts and the serous acini

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-8445-4565

**Any additional notes or concerns**

@addiehl

**Comment by bvarner-ebi** [comment]
CL:403303 'mucus secreting cell of tracheobronchial tree submucosal gland' appears to satisfy this request. Feel free to reopen this issue if necessary.
FYI, @aleixpuigb.
