### ISSUE TITLE
Pulmonary Submucosal Gland [NTR]

### ISSUE THREAD

**Issue by AnnekarinaPerl** [obophenotype/cell-ontology#1059]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Pulmonary Submucosal Gland

**Synonyms**
Pulmonary SMG

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
PMID: 26336032

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
Submucosal gland UBERON:0011148

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
SMGs are present within the connective tissues lining the cartelagious airways and are a major source of the protective mucus layer critical to normal innate defense.
the gland contains the following cells:
terminal ciliated duct basal cells
Myoepithelial cells
Mucous cells
Serous Cells

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-8445-4565

**Any additional notes or concerns**
@addiehl

**Comment by AnnekarinaPerl** [comment]
The SMG also contains the Ionocyte, goblet cells , cilliated cells, within the terminal ciliated duct.

**Comment by addiehl** [comment]
Hi Anna Karina,

This looks like a request that ought to be directed to Uberon rather than the Cell Ontology, as Uberon is an ontology for anatomical structures larger than cells.
[https://github.com/obophenotype/uberon/issues](https://github.com/obophenotype/uberon/issues)

-- Alex

**Comment by addiehl** [comment]
See [http://purl.obolibrary.org/obo/UBERON_0011148](http://purl.obolibrary.org/obo/UBERON_0011148) for a small hierarchy of submucosal glands already in Uberon.

**Comment by AnnekarinaPerl** [comment]
I agree thank you for pointing it out. I will stick with the cell terms

Anne-Karina Perl, PhD
Associate Professor
Cincinnati Children's Hospital
Division of Pulmonary Biology
3333 Burnet Avenue, MLC 7029, Cincinnati, OH 45229
office: 513 636 6084
lab: 513 636 9799
fax: 513 803 4891
url: http://www.cincinnatichildrens.org/perl
[tps://www.cincinnatichildrens.org/-/media/295b830c6eb94ee2b662c61a2945e5e6.ashx?h=67&w=200]<https://www.cincinnatichildrens.org/>



From: Alexander Diehl ***@***.***>
Reply-To: obophenotype/cell-ontology ***@***.***>
Date: Tuesday, April 27, 2021 at 12:34 PM
To: obophenotype/cell-ontology ***@***.***>
Cc: Anne Perl ***@***.***>, Author ***@***.***>
Subject: Re: [obophenotype/cell-ontology] Pulmonary Submucosal Gland [NTR] (#1059)


***This email originated from an EXTERNAL sender to CCHMC. Proceed with caution when replying, opening attachments, or clicking links in this message.***



Hi Anna Karina,

This looks like a request that ought to be directed to Uberon rather than the Cell Ontology, as Uberon is an ontology for anatomical structures larger than cells.
https://github.com/obophenotype/uberon/issues

-- Alex
