### ISSUE TITLE
[NTR] macrophage of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1062]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
macrophage of appendix

**Synonyms**
macrophage of appendix vermiformis
macrophage of vermiform appendix

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Macrophage that is located in the appendix vermiformis.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
macrophage http://purl.obolibrary.org/obo/CL_0000235

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
The new term is CL_0009036 (appendix macrophage).
Again, the naming is consistent with other existing terms, and I kept all of your suggestions as synonyms.
Thanks,
Paola
