### ISSUE TITLE
[NTR] cnidocyte

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1065]
(Background: I’m attending an EMBO symposium on cell types)
GO:0042151 ‘nematocyst’ is defined as “An organelle found in cnidoblast (nematoblast) cells. When matured, these stinging organelles store toxins and can deliver them when the cnidocil (a short extension of the cnidocyst) is stimulated by a prey or another stimulus. [ GOC:jl http://dx.doi.org/10.1139/z02-135 ] ”
but there is no CL term for cnidoblast or nematoblast (or cnidocyte). Should we add one based on https://en.wikipedia.org/wiki/Cnidocyte:

**Preferred term label:**
cnidocyte

**Synonyms**
cnidoblast, nematocyte

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A cnidocyte (also known as a cnidoblast or nematocyte) is an explosive cell containing one giant secretory organelle called a cnidocyst (also known as a cnida (plural cnidae) or nematocyst) that contains a toxin responsible for the stings delivered by a cnidarian to other organisms. Cnidae are used to capture prey and as a defense against predators. The presence of cnidocytes defines the phylum Cnidaria (corals, sea anemones, hydrae, jellyfish, etc.).
def dbxref: https://en.wikipedia.org/w/index.php?title=Cnidocyte&oldid=1019979214 [can’t remember the correct format now]

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
subclass_of secretory cell
has_part GO:0042151 nematocyst
taxon constraint: only in Cnidaria 

**Your nano-attribution (ORCID)**
0000-0002-2825-0621

We could add an xref to 
cnidoblast BTO:0001706
http://purl.obolibrary.org/obo/BTO_0001706
A cell in the epidermis of coelenterates in which a nematocyst is developed.

I also just noticed that this term exists in the Clytia hemisphaerica Development and Anatomy Ontology (CLYH), so we should xref to it to: 
nematocyte CLYH:1000107
http://purl.obolibrary.org/obo/CLYH_1000107
Specialized cell containing one giant explosive secretory organelle called nematocyst used for prey capture and defense from predators.

Or - should we not create a CL term if CLYH is the appropriate domain ontology, and suggest a link is created between the respective GO and CLYH terms?

Thanks.
Paola

**Comment by nicolevasilevsky** [comment]
I just created this new term, then read your comment about whether this term is more appropriate for CLYH, haha! Please feel free to close the PR if we don't want this in CL.

**Comment by paolaroncaglia** [comment]
> I just created this new term, then read your comment about whether this term is more appropriate for CLYH, haha! Please feel free to close the PR if we don't want this in CL.

Yes apologies I should have edited the ticket to put that bit at the start!
The question is more for GO, I guess (would they rather link to CL or to the domain-specific CLYH ontology - or does it not really matter that a link is created). @cmungall @dosumis please?
Thank you all,
Paola

**Comment by cmungall** [comment]
CLYH is too narrow. This term is applicable across cnidaria, including anenomies, coral

We do need a plan for CL/Uberon mapping to CLYH and inclusion in composite-metazoa

**Comment by nicolevasilevsky** [comment]
Hi @paolaroncaglia I'll address the open action items from Nico on the PR.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky thanks!
