### ISSUE TITLE
Labels of 2 x-secreting cell types

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1066]
Minor notes:

Should CL:0007021 'alarm substance cell' (subclass of ‘secretory cell’) be renamed 'alarm substance secreting cell' for consistency with its x-secreting siblings in the same branch? ’alarm substance cell' could stay as a synonym.
Update: 'alarm substance cell' is what's used in lit, so leave it as is but 
- [ ] add exact synonym 'alarm substance secreting cell'

Should CL:0000315 'tears secreting cell' be renamed 'tear secreting cell' for consistency with the use of singular rather than plural? 'tears secreting cell' could stay as a synonym.
Update: none of the two labels seems used as such, so yes go ahead and
- [ ] rename as 'tear secreting cell'
- [ ] add exact synonym 'tears secreting cell'

**Comment by bvarner-ebi** [comment]
Hi @paolaroncaglia, I noticed the definition for CL:0007021 'alarm substance cell' has the title of the reference in brackets at the end even though the ISBN is included in the annotation. 
Is the title in the definition redundant and should it be removed from the definition string?
