### ISSUE TITLE
[Merge] CL:0000111 'peripheral neuron'

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1069]
**CL term (ID and Label)**
CL:0000111 'peripheral neuron'

**Reason for deprecation**
Is this the same as CL:2000032 'peripheral nervous system neuron'?
If so, its (only) child 'peripheral sensory neuron' should be rehoused (and 'sensory neuron of spinal nerve' should probably become its child)

**Term to be merged with (ID and Label)**
CL:2000032 'peripheral nervous system neuron'

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@shawntanzk 
Hi. Not urgent (Uberon release first! ;-) ), but when you have a chance, could you please comment on whether 
CL:0000111 'peripheral neuron'
and
CL:2000032 'peripheral nervous system neuron'
look the same to you too?
Thanks.

**Comment by shawntanzk** [comment]
they look the same to me - will merge them

**Comment by shawntanzk** [comment]
> and 'sensory neuron of spinal nerve' should probably become its child

I'm not too sure about this - this should be inferred somehow and asserting it as a child seems to be bad modelling imo

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> > and 'sensory neuron of spinal nerve' should probably become its child
> 
> I'm not too sure about this - this should be inferred somehow and asserting it as a child seems to be bad modelling IMO. (I'm guessing it already is/will be)

Yes, that's what I meant, I was unclear. Thank you for taking this ticket!

**Comment by shawntanzk** [comment]
@paolaroncaglia - brought up a bigger problem (https://github.com/obophenotype/cell-ontology/issues/1537) have assigned it to you too in case you want to be involved in the discussion of that :)

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> @paolaroncaglia - brought up a bigger problem (#1537) have assigned it to you too in case you want to be involved in the discussion of that :)

Telepathy, I was just commenting on that ;-) Thanks!
