### ISSUE TITLE
[Obsolete] CL:0010022 'cardiac neuron'

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1074]
**CL term**
CL:0010022 'cardiac neuron'

**Reason for deprecation**
Similar to https://github.com/obophenotype/cell-ontology/issues/1067, but with no annotation other than the label. It is
equivalent to 'neuron' and ('part of' some heart)
Is the term legit (if so it'd benefit from more info) or should it be obsoleted?

**Suggested replacement to consider**
No suggestion, as I'm not sure what the term was meant to represent.

**Comment by nicolevasilevsky** [comment]
I'm okay with obsoleting.

**Comment by paolaroncaglia** [comment]
Note to self, this is in progress.

**Comment by paolaroncaglia** [comment]
@shawntanzk 
Again, not urgent (it's my CL tickets week, so I'm following up on pending ones). I will remove my assignment from this one and add you instead, because once David approves https://github.com/obophenotype/cell-ontology/pull/1501, this ticket is good to close. Thank you for your work on this.
