### ISSUE TITLE
[Class hierarchy] CL:0002278 'GIP cell', missing link to small intestine

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1076]
**CL term**
CL:0002278 'GIP cell'
"An enteroendocrine cell of duodenum and jejunum that produces gastric inhibitory peptide."

**Suggested revision and reasons**
Could be improved by adding part_of 'small intestine' (where duodenum and jejunum are both located).

Thanks,
Paola

**Comment by rays22** [comment]
@paolaroncaglia ,
It looks like the `GIP cell` is already

    'part of' some 'small intestine'

in the current CL release.
Can I close this ticket?

**Comment by paolaroncaglia** [comment]
Thanks @rays22 , I'll close.
