### ISSUE TITLE
Improve CL:0000118 'basket cell'

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1077]
(Listening to Ed Lein's talk at EMBO symposium)
I'm aware that neuronal cell type terms are the object of specific projects at the moment, however beyond the specificity and richness of recently created terms for those projects, I noticed that the older term CL:0000118 'basket cell' has no annotation and is a subclass of generic 'CNS neuron (sensu Vertebrata)'. The term could be quickly improved based on the relevant Wikipedia entry (https://en.wikipedia.org/w/index.php?title=Basket_cell&oldid=951703880):

- [ ] Add def: "Basket cells are inhibitory GABAergic interneurons of the brain. In general, dendrites of basket cells are free branching and contain smooth spines. Axons are highly branched. The branched axonal arborizations give rise to the name as they appear as baskets surrounding the soma of the target cell. Basket cells form axo-somatic synapses, meaning their synapses target somas of other cells."
def dbxref https://en.wikipedia.org/w/index.php?title=Basket_cell&oldid=951703880 (in correct format), plus my ORCID if you wish

- [ ] Replace current superclass with more granular CL:0011005 'GABAergic interneuron' 

Thanks,
Paola

**Comment by dosumis** [comment]
@shawntanzk is working on defining terms like this using morphology terms defined in PATO.   PATO route might be overkill for this term. Not sure if this one is on the list to target right now, but I think we should be broadening Brain Data Standards efforts to include commonly defined neuron types.

**Comment by shawntanzk** [comment]
See this PR for Basket cell morphology: https://github.com/pato-ontology/pato/pull/387 
I've not annotated anything outside Brain Data Standards stuff, but have been thinking if I should for things like Basket Cell, Pyramidal Neuron, and Bipolar Neuron - happy to do so if you think it would be appropriate

**Comment by patrick-lloyd-ray** [comment]
@dosumis: I agree that BDS efforts should include updating these types. 

@shawntanzk: if you are going to take the lead, I can help where needed. Feel free to reach out for what you need.

**Comment by dosumis** [comment]
The PATO version doesn't account for the basket name as the text from wikipedia does.
