### ISSUE TITLE
[NTR] intestinal crypt stem cell of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1083]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
intestinal crypt stem cell of anal canal

**Synonyms**
anal canal intestinal crypt stem cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Intestinal crypt stem cell that is located in the anal canal

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal crypt stem cell http://purl.obolibrary.org/obo/CL_0002250

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'intestinal crypt stem cell of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
Waiting for Godot, ehm, Uberon.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009061 (intestinal crypt stem cell of anorectum)
