### ISSUE TITLE
[NTR] enteroendocrine cell of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1084]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enteroendocrine cell of anal canal

**Synonyms**
anal canal enteroendocrine cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enteroendocrine cell that is located in the anal canal.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal enteroendocrine cell http://purl.obolibrary.org/obo/CL_1001516

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'enteroendocrine cell of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
Waiting for Uberon

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009063 (enteroendocrine cell of anorectum)
