### ISSUE TITLE
[NTR] transit amplifying cell of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1088]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
transit amplifying cell of anal canal

**Synonyms**
anal canal transit amplifying cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Transit amplifying cell that is located in the anal canal

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
transit amplifying cell http://purl.obolibrary.org/obo/CL_0009010

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'transit amplifying cell of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
...and this one too... waiting for Uberon

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009056 (transit amplifying cell of anorectum)
