### ISSUE TITLE
[NTR] paneth cell of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1089]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
paneth cell of anal canal

**Synonyms**
anal canal paneth cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Paneth cell that is located in the anal canal

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
http://purl.obolibrary.org/obo/CL_0000510

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'paneth cell of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
Note to self: waiting for Uberon 'anorectum' to be released.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009055 (paneth cell of anorectum)
