### ISSUE TITLE
[NTR] microfold cell of epithelium proper of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1090]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
microfold cell of epithelium proper of anal canal

**Synonyms**
M cell of anal canal

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Microfold cell (M cell) that is part of the anal canal

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
microfold cell of epithelium proper of large intestine http://purl.obolibrary.org/obo/CL_1000360

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'microfold cell of epithelium proper of anorectum' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
This requests also needs the updated Uberon version.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009054 (microfold cell of epithelium proper of anorectum)
