### ISSUE TITLE
[NTR] stromal cell of anal canal lamina propria

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1091]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
stromal cell of anal canal lamina propria

**Synonyms**
anal canal stromal cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A stromal cell found in the lamina propria of the anal canal.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
stromal cell http://purl.obolibrary.org/obo/CL_0000499

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'stromal cell of anorectum lamina propria' and make it a child term of anorectum - UBERON:8410050 anorectum

**Comment by paolaroncaglia** [comment]
Need to wait for Uberon release.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009053 (stromal cell of anorectum lamina propria)
