### ISSUE TITLE
[NTR] stratified squamous epithelial cell of anal canal

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1092]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
stratified squamous epithelial cell of anal canal

**Synonyms**
anal canal stratified squamous epithelial cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Stratified squamous epithelial cell that is part of the anal canal

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
stratified squamous epithelial cell http://purl.obolibrary.org/obo/CL_0000240

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anal canal http://purl.obolibrary.org/obo/UBERON_0000159

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Is this term request still for part_of 'anal canal', or should it be revised to part_of 'anorectum'?
Thanks,
Paola

**Comment by sfexova** [comment]
Hi @paolaroncaglia, thanks - it is still needed, yes. This type of cell only appears in the anal canal, not in the rest of the large intestine, so it can stay as stratified squamous epithelial cell of anal canal without breaking anything I believe

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009066 (stratified squamous epithelial cell of anal canal)
