### ISSUE TITLE
[NTR]monocyte-derived_dendritic_cell

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1104]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
monocyte-derived dendritic cell

**Synonyms**
MDDC cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
BTO:0002900

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

**Comment by nicolevasilevsky** [comment]
@kalpanaps is this still needed?

**Comment by kalpanaps** [comment]
It is needed, as we could not map this term to any ontology. This is one of host organism where protein-protein interaction has been detected and we need ontology support.

Let me know if any further information is needed.

Best regards,

Kalpana
----------------------------------------------
Kalpana Panneerselvam

IntAct-Senior Scientific Database Curator
European Molecular Biology Laboratory
European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
Tel: +44 1223 494 468
email: ***@***.***
