### ISSUE TITLE
[NTR]dermal microvascular endothelium cell

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1105]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
dermal microvascular endothelium cell

**Synonyms**
DMEC cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Has brenda id BTO:0004574

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

**Comment by nicolevasilevsky** [comment]
@kalpanaps is this still needed?

**Comment by kalpanaps** [comment]
Yes, we need this term to be mapped to cell ontology for us to map PPIs onto this cell.

Best regards,

Kalpana
----------------------------------------------
Kalpana Panneerselvam

IntAct-Senior Scientific Database Curator
European Molecular Biology Laboratory
European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
Tel: +44 1223 494 468
email: ***@***.***
