### ISSUE TITLE
UUID IRI used in six axioms

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#1112]
There is a term `http://purl.obolibrary.org/obo/D96882F1-8709-49AB-BCA9-772A67EA6C33` with no label or any other annotations which is used in six axioms for 'immature basophil', 'immature eosinophil', and 'immature neutrophil'.

These are all meant to have some unknown thing as a part.

**Comment by balhoff** [comment]
I transferred the issue from Uberon to CL.

**Comment by balhoff** [comment]
This unusual IRI is in CL, but does have a label there, 'alobate nucleus'.

**Comment by addiehl** [comment]
This may have been a GO term once: [https://sourceforge.net/p/obo/phenotypic-quality-pato-requests/551/](https://sourceforge.net/p/obo/phenotypic-quality-pato-requests/551/).

The CL has several similar "CP:" terms related to types of nuclei. I should probably replace them all with something better (this has been brought up multiple times).

**Comment by cmungall** [comment]
I think we can close as a dupe of #857. 

However, I wasn't aware that these fake GO classes are actually in two namespaces:

 * CP
 * namespaceless UUIDs

I think we should get rid of the CPs, I don't know whether we first want to turn the UUIDs into CPs

**Comment by paolaroncaglia** [comment]
Hi @matentzn ,
Tagging you as you linked a pull request recently: I think that this issue could be closed as a duplicate and because you're already working on a solution, but please confirm in case any loose end needs to be documented somewhere. Thanks.

**Comment by matentzn** [comment]
Thanks for pointing. @dosumis needs to decide what to do with #1311 - I think it should be merged.
