### ISSUE TITLE
[NTR] T cell of anorectum

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1115]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
T cell of anorectum

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
T cell that is located in the anorectum. T cell is a type of lymphocyte whose defining characteristic is the expression of a T cell receptor complex. PMID: 24292902

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
T cell http://purl.obolibrary.org/obo/CL_0000084

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:8410050 anorectum

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Can't create as desired until Uberon releases 'anorectum'.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009051 (T cell of anorectum)
