### ISSUE TITLE
[NTR] B cell of anorectum

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1116]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
B cell of anorectum

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
B cell that is located in the anorectum. B cells are at the centre of the adaptive humoral immune system and are responsible for mediating the production of antigen-specific immunoglobulin (Ig). PMID: 31002794

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
B cell http://purl.obolibrary.org/obo/CL_0000236

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:8410050 anorectum

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Can't create as desired until Uberon releases 'anorectum'.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009050 (B cell of anorectum)
