### ISSUE TITLE
[NTR] intestinal crypt stem cell of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1117]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
intestinal crypt stem cell of colon

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Intestinal crypt stem cell that is located in the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal crypt stem cell http://purl.obolibrary.org/obo/CL_0002250

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
- [ ] 'intestinal crypt stem cell of appendix' shouldn't reason under 'intestinal crypt stem cell of colon'

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009043 (intestinal crypt stem cell of colon)
