### ISSUE TITLE
[NTR] enteroendocrine cell of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1118]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enteroendocrine cell of colon

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enteroendocrine cell that is located in the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal enteroendocrine cell http://purl.obolibrary.org/obo/CL_1001516

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
- [ ] 'enteroendocrine cell of appendix' should no longer reason under 'enteroendocrine cell of colon' after Uberon release and ingest

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009042 (enteroendocrine cell of colon)
