### ISSUE TITLE
[NTR] tuft cell of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1119]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
tuft cell of colon

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Tuft cell that is a part of the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal tuft cell http://purl.obolibrary.org/obo/CL_0019032

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Note to self,
- [ ] 'tuft cell of appendix' should no longer reason under 'tuft cell of colon' after Uberon release and ingest

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009041 (tuft cell of colon)
