### ISSUE TITLE
[NTR] stromal cell of lamina propria of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1121]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
stromal cell of lamina propria of colon

**Synonyms**
stromal cell of colon lamina propria

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A stromal cell found in the lamina propria of the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
stromal cell http://purl.obolibrary.org/obo/CL_0000499

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009040 (stromal cell of lamina propria of colon)
