### ISSUE TITLE
[NTR] goblet cell of colon

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1122]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
goblet cell of colon

**Synonyms**
colon goblet cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Goblet cell that is located in the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
large intestine goblet cell http://purl.obolibrary.org/obo/CL_1000320

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
FYI, the new term will be labelled 'colon goblet cell' (with 'goblet cell of colon' as an exact synonym) for consistency with its many pre-existing siblings under 'goblet cell'.

**Comment by paolaroncaglia** [comment]
Note to self: 'appendix goblet cell' currently reasons under 'colon goblet cell'
- [ ] Double-check that it doesn't after Uberon release

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009039 (colon goblet cell)
(leaving ticket open to address https://github.com/obophenotype/cell-ontology/issues/1122#issuecomment-873983475)
