### ISSUE TITLE
[NTR] colon macrophage

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1123]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
colon macrophage

**Synonyms**
macrophage of colon

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Macrophage that is located in the colon.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
macrophage http://purl.obolibrary.org/obo/CL_0000235

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
colon http://purl.obolibrary.org/obo/UBERON_0001155

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Note to self: 'appendix macrophage' currently reasons under 'colon macrophage', because CL hasn't ingested the Uberon change by which appendix is no longer part_of colon (because Uberon hasn't released yet).
- [ ] Double-check after Uberon release.

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009038 (colon macrophage)
(leaving ticket open until https://github.com/obophenotype/cell-ontology/issues/1123#issuecomment-873976856 is addressed)
