### ISSUE TITLE
[NTR] anorectum macrophage

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1124]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
anorectum macrophage

**Synonyms**
macrophage of anorectum

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Macrophage that is located in the anorectum.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
macrophage http://purl.obolibrary.org/obo/CL_0000235

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
anorectum UBERON:8410050

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Note to self: can't create this term as desired until Uberon releases 'anorectum'. Should be any day now (David said possibly today).

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009048 (anorectum macrophage)
