### ISSUE TITLE
[Class hierarchy] small, large and nest basket cells might be under neocortex basket cell

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1128]
From the description of small, large and nest basket cells, they sound like they could possibly be cortex specific. 
If so, these terms should be under neocortex basket cell.
Would like some input on this @tgbugs, thanks.

Related to #1127

**Comment by dosumis** [comment]
'large basket cell' def is clearly cortex specific: "A basket cell that is large, and typically ascends to give rise to many long horizontally and vertically projecting axon collaterals that traverse neighboring columns and can extend through all cortical layers."

Mention of layer here sounds cortex specific: "A basket cell with axonal arbors composed of frequent, short, curvy axonal branches that tend to be near their somata and within the same layer."

Wikipedia (& reference therein) has these 3 types as cortex specific: https://en.wikipedia.org/wiki/Basket_cell#Cortex


@tgbugs - this is consistent with Wikipedia https://en.wikipedia.org/wiki/Basket_cell#Cortex

**Comment by tgbugs** [comment]
Sorry, just seeing this. The one area where the neocortex axioms would be problematic is that there are basket cells in hippocampus, so basket cell usually applies neocortex and hippocampus, whereas neocortex basket cell is the differentiated form for neocortex only. That said, all of these types are coming from neocortex only, and Rat area S1 specifically. So the change to include the part of neocortex axiom is ok.
