### ISSUE TITLE
sensory neurons and hair cells

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#113]
```
Hi all,

These comments on sensory neurons and hair cells were motivated by issues we've 
had in marking up the text of PMID:12585968 with CL.

First, 'auditory hair cell' is an indirect subclass of both 'neuron' and 
'epithelial cell'--is this intended? 

Also, 'sensory hair cell' is an indirect subclass of 'neuron' but not of 
'sensory neuron'.  It seems it should be, but  my reading of this article 
suggests that sensory neurons and hair cells are indeed different (disjoint?), 
e.g., the Table 1 caption.  So, is it the case that sensory neurons and sensory 
hair cells are either disjoint or overlapping, but the former doesn't subsume 
the latter, as is currently modeled?  If so, then why are sensory hair cells, 
which are neurons, not sensory neurons?  If this is the case, it seems mentions 
of sensory neurons might be referring to either.  On the other hand, 
categorizing sensory hair cells as sensory neurons doesn't seem to jive with 
this article to me, so I'm stuck.  And would the mentions of vestibular and 
cochlear sensory neurons in the article refer to vestibular and cochlear hair 
cells already represented in CL?

Mind you, I'm not an expert in this at all, so I'd be curious to hear opinions.

Thanks!
Mike
```

Original issue reported on code.google.com by `mikeb...@gmail.com` on 14 Mar 2014 at 4:07

**Comment by shawntanzk** [comment]
> First, 'auditory hair cell' is an indirect subclass of both 'neuron' and 
'epithelial cell'--is this intended? 

I think this is correct, hair cells – are highly specialized epithelial cells located within the inner ear. [PMID:23545368]

> It seems it should be, but  my reading of this article 
> suggests that sensory neurons and hair cells are indeed different (disjoint?), 
> e.g., the Table 1 caption.

I think what this means is that it seems that hair cells and sensory neurons seem to refer to different things in the article? It seems that this is specific to the article and I'm not 100% sure if they meant hair cells as a subset or neurons. Noting their methods, they only did IHC for hair cells and used cresyl violet to count neurons (which seems to include hair cell) - it is a bit confusing here

> If so, then why are sensory hair cells, 
> which are neurons, not sensory neurons?

They actually are, see screenshot:
![Screenshot 2021-08-25 at 10 03 23](https://user-images.githubusercontent.com/76212760/130761812-ca2d3937-743f-45d1-a02c-5fb5ee0a7231.png)

Will close this ticket for now, please do open again if there are other concerns (cc @nicolevasilevsky as your email is in this thread, not sure who `mikeb...@gmail` is)
