### ISSUE TITLE
[NTR] Club cell of the urethra epithelium

### ISSUE THREAD

**Issue by GHAStVHenry** [obophenotype/cell-ontology#1133]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Club cell of the urethra epithelium

**Synonyms**
Club-like cell of the urethra epithelium
Club-like cell of the prostatic urethra epithelium

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
* PMID:31390564
* PMID:32497356

Unique epithelial cell type identified in the prostatic urethra, identified by it's transcriptional similarity to lung club cells
PMID:30069044
PMID:33208946
PMID:33442032

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:1000296

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:0002325

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-7772-9578

**Any additional notes or concerns**

**Comment by emquardokus** [comment]
@stranddw

**Comment by paolaroncaglia** [comment]
Note to CL editors:
I removed the automated assignments as this ticket hasn't been actually picked up;
There are 4 NTRs by the same submitter, so it'd make sense to address them all at the same time: #1133 (urethra), #1134 (urethra), #1135 (prostate) and #1171 (bronchiole).
