### ISSUE TITLE
[NTR] Hillock cell of the urethra epithelium

### ISSUE THREAD

**Issue by GHAStVHenry** [obophenotype/cell-ontology#1134]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Hillock  cell of the urethra epithelium

**Synonyms**
Hillock-like cell of the urethra epithelia
Hillock-like cell of the prostatic urethra epithelium

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
* PMID:31390564
* PMID:32497356

Unique epithelial cell type identified in the prostatic urethra, identified by it's transcriptional similarity to lung hilllock cells
PMID:30069044
PMID:32726565
PMID:33208946
PMID:33442032

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:1000296

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:0002325

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-7772-9578

**Any additional notes or concerns**
Lung hillock cells are not currently annotated in Cell Ontology

**Comment by lubianat** [comment]
@GHAStVHenry Can you make a ticket for lung hillock cells? It would be good to have that term before we proceed with this one.

**Comment by GHAStVHenry** [comment]
I can do, that, I'm don't research lung... so all I really have is the reference to the one paper that initially ID'd the cell type...

**Comment by GHAStVHenry** [comment]
I guess that's not true... I quoted 4 above...

**Comment by GHAStVHenry** [comment]
@lubianat see #1171

**Comment by paolaroncaglia** [comment]
Note to CL editors:
I removed the automated assignments as this ticket hasn't been actually picked up, though there have been comments by @lubianat and @emquardokus ;
There are 4 NTRs by the same submitter, so it'd make sense to address them all at the same time: https://github.com/obophenotype/cell-ontology/issues/1133 (urethra), https://github.com/obophenotype/cell-ontology/issues/1134 (urethra), https://github.com/obophenotype/cell-ontology/issues/1135 (prostate) and https://github.com/obophenotype/cell-ontology/issues/1171 (bronchiole).

**Comment by paolaroncaglia** [comment]
@lubianat scratch that, I see you made a PR but it seems there was a conflict? The term isn't in CL yet. I'll assign to you. Thanks!

**Comment by lubianat** [comment]
merged via #1624

**Comment by anitacaron** [comment]
In PR #1624, only add hillock cell and respiratory hillock cell. Still missing Hillock cell of the urethra epithelium.

**Comment by bvarner-ebi** [comment]
Hi, @lubianat, are you planning to add this new term? If not, feel free to assign the ticket to me or assign me as a reviewer if you make a PR.

**Comment by lubianat** [comment]
Sorry for the mess, everyone. I'll add the hillock cell of the urethra now.

**Comment by bvarner-ebi** [comment]
@GHAStVHenry,
Thank you for the contribution.

The following terms have been added to CL and will be available in the next release:

CL:0017010 ‘hillock cell of urethral epithelium’
CL:0017011 ‘hillock cell of prostatic urethral epithelium’
