### ISSUE TITLE
[NTR] Neuroendocrine cell of prostate epithelium

### ISSUE THREAD

**Issue by GHAStVHenry** [obophenotype/cell-ontology#1135]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Neuroendocrine cell of prostate epithelium

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Neuroendocrine cell (CL:0000165) in the prostate
* PMID:33842835
* PMID:31390564
* PMID:32497356

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0002231

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:0000428

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-7772-9578

**Any additional notes or concerns**

**Comment by lubianat** [comment]
@GHAStVHenry PMID:31390564 (https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC6710009/)  does not seem to mential neuroendocrine cells. Am I missing anything?

**Comment by GHAStVHenry** [comment]
Prostate neuroendocrine are rare and sometimes difficult to identify unless you are specifically looking for them. That paper did not identify them as it wasn't important for proving their hypothesis. They are usually referred to in publications in reference to prostate cancer, which can trans-differentiate into neuroendocrine-like prostate cancer... but they are present in the normal prostate and is very well accepted in the urologic field as being present.

The review @ @[pmc8023015](https://www.ncbi.nlm.nih.gov/labs/pmc/articles/pmc8023015/) describes them as:
```
NE cells are scattered among the more abundant luminal and basal cells, representing only ∼1% of the epithelial population.11, 13, 21 Because of their rarity in benign prostate and most prostate tumors, they cannot be appreciated on standard H&E stained sections. However, through the use of electron microscopy, they can be identified and differentiated from luminal and basal cells by their elongated cell bodies and intracytoplasmic dense core secretory granules.21 Furthermore, electron microscopy can differentiate between two morphologic subtypes of NE cells: open-type and closed-type.24 Open-type cells possess long microvilli which reach the lumen and can detect changes in pH as well as respond to other chemical stimuli in luminal secretions. Closed-type cells possess dendritic-like processes and receive stimuli from nerve endings, blood vessels, and smooth muscle cells. A more practical way to highlight NE cells in the prostatic epithelium involves the use of immunohistochemistry (IHC) (Fig. 1) and commonly used markers include chromogranin A (CgA),11, 13, 21 synaptophysin (SYP),11, 13, 21 neuron-specific enolase (NSE),11, 13, 21 neural cell adhesion molecule (NCAM or CD56),11, 13, 21 forkhead-box A2 (FOXA2),25 and CXC chemokine receptor 2 (CXCR2).26 In addition to being negative for AR and PSA, they are also negative for Ki67 because they are non-proliferative, post-mitotic cells.11, 13, 21, 26
```

...as a matter of fact, it even describes two types (open-type and closed-type) which I have never heard about.

**Comment by lubianat** [comment]
@GHAStVHenry  thanks! I am working on this ticket, but it has been a while since my last CL edit, the review might take a while, but it should be moving forward.

**Comment by GHAStVHenry** [comment]
That's awesome, thanks @lubianat, while this is important...

I'm really would love to have terms #1133 #1134... I have some curation processes that could use terms for them... are you working on those tickets too?

**Comment by lubianat** [comment]
I've seen them, I plan is to pick up on those two after this one is complete (unless someone happens to work on them first)

**Comment by GHAStVHenry** [comment]
sounds good... this is the "easiest" one as it is an "old" cell type... the other 2 are "new" so there are fewer references

**Comment by paolaroncaglia** [comment]
@lubianat assigning to you as I see you made a PR. Thanks.
As a reminder, I removed the automated assignments;
There are 4 NTRs by the same submitter, so it'd make sense to address them all at the same time: https://github.com/obophenotype/cell-ontology/issues/1133 (urethra), https://github.com/obophenotype/cell-ontology/issues/1134 (urethra), https://github.com/obophenotype/cell-ontology/issues/1135 (prostate) and https://github.com/obophenotype/cell-ontology/issues/1171 (bronchiole).
