### ISSUE TITLE
'flatworm hypodermal cell' xref to C. elegans 'hypodermal cell'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#1137]
Recently a taxon constraint to Platyhelminthes was added to 'flatworm hypodermal cell' (#1070). This is causing the GO pipeline to fail, because there is an xref from this CL term to C. elegans [hypodermal cell](http://purl.obolibrary.org/obo/WBbt_0007846). Uberon provides a bridge ontology based on these xrefs which has equivalent class axioms like:

[hypodermal cell](http://purl.obolibrary.org/obo/WBbt_0007846) EquivalentTo [flatworm hypodermal cell](http://purl.obolibrary.org/obo/CL_0000411) and [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [Caenorhabditis](http://purl.obolibrary.org/obo/NCBITaxon_6237).

I think either the xref should be removed, or the CL term should be broadened, or we need to change the Uberon pipeline using the xrefs (perhaps we need new properties like "taxon-specific version" instead of generic xref).

**Comment by dosumis** [comment]
For now - fix to roundworm (check this is right taxon!)

**Comment by lubianat** [comment]
can we be sure it is safe to change the definition of the class? I know no one needs more work, but wouldn't it be cleaner to create a new class for Nematoda/roundworms with the WormBase/Worm Atlas xrefs?

**Comment by cmungall** [comment]
I am changing the name for now to reflect the intent but I am good with obsoleting this altogether

**Comment by cmungall** [comment]
The PR changes the name to Caenorhabditis which is more specific than roundworm but I think reflects a safer level of generalization

**Comment by cmungall** [comment]
Making a new release now,
