### ISSUE TITLE
Names of classes added for BDS need shortening

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1138]
Remove redundancy

e.g. 
medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
-> 
medulla-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)

**Comment by shawntanzk** [comment]
corticothalamic VAL/VM projecting glutamatergic neuron of the primary motor cortex (Mus musculus) -> technically can remove corticothalamic, but i find it useful as VAL/VM is not very informative without "thalamic" in there
