### ISSUE TITLE
new term proposal catecholaminergic neuron

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#114]
```

Need term catecholaminergic neuron
Def: Neurons that produce dopamine, norephinephrine or adrenaline.  CA 
synthesis involves four enzymes: tyrosine hydroxylase (TH), aromatic amino acid 
decarboxylase (AADC), dopamine b-hydroxylase (DbH), and 
phenylethanolamine-N-methyl transferase (PNMT) PMID:10191060 ISBN:
9780521442510     

Notes: Frequently used when describing the developing nervous system in 
zebrafish.  Cells express th or th2 genes.  
PMID: 12128258   

```

Original issue reported on code.google.com by `cer...@gmail.com` on 20 Mar 2014 at 5:54

**Comment by addiehl** [comment]
Seems like a valid term.  Is this still needed @cerivs?

**Comment by bvarner-ebi** [comment]
Some comments:

The proposed text def is:
"Neurons that produce dopamine, norephinephrine or adrenaline.  CA 
synthesis involves four enzymes: tyrosine hydroxylase (TH), aromatic amino acid 
decarboxylase (AADC), dopamine b-hydroxylase (DbH), and 
phenylethanolamine-N-methyl transferase (PNMT)"

- "Neurons" should be in singular form.

- The term epinephrine vs adrenaline should be used consistently:

A neuron that produces dopamine, norephinephrine or epinephrine.
OR
A neuron that produces dopamine, noradrenaline or adrenaline.

- The gloss may be too broad for the term 'catecholaminergic neuron'.

- The following GO terms already exist:

 GO:0061527 'dopamine secretion, neurotransmission'
 GO:0061533 'norepinephrine secretion, neurotransmission'
 GO:0061529 'epinephrine secretion, neurotransmission'
 
 Given that, should a new term 'catecholamine secretion, neurotransmission' be created in GO?
 
 FYI @shawntanzk

**Comment by shawntanzk** [comment]
Ideally having a new term 'catecholamine secretion, neurotransmission' that has all the catecholamine secretion under it would be ideal. I'll create a ticket there. However, if there is any issue, we can also manually assert given its only 3. Give this ticket is from 2015 I don't think there is any rush. Will wait to see what GO says about the new term

**Comment by anitacaron** [comment]
@bvarner-ebi @shawntanzk, do you think this term can be the same as [the one on row 37](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit?pli=1#gid=1225604837)?

**Comment by shawntanzk** [comment]
from definition, yes, though my assumption is that the spleen is innervated by catecholaminergic neuron, and not has them? That being said given its a MIRACL sheet, I assume its just for term addition, in which case, yes, that is the same term.

**Comment by aleixpuigb** [comment]
Hi @cerivs, thank you for your request. Would you still want to include the following comment in the term?
> Frequently used when describing the developing nervous system in zebrafish.  Cells express th or th2 genes.  (PMID: 12128258)

If so, could you provide your ORCID number to add, please?

**Comment by cerivs** [comment]
Hi,
Thank you.  The note is still applicable.  My ORCID is 0000-0002-2244-7917

**Comment by aleixpuigb** [comment]
Thank you, @cerivs. This class has been created and will be available in the new released scheduled for today.
