### ISSUE TITLE
somatic cell classification is massively incomplete

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#1150]
these are all the non-redundant descendants of native cell that are not classified under somatic cell. YES means I think they should be moved under somatic cell. NO means keep. ? means decisions should be made on a subclass basis. I was too lazy to expand these

|move?|id|name
|---|---|---|
|NO|CL:0000039|germ line cell
|?|CL:0000080|circulating cell
|YES|CL:0000183|contractile cell
|YES|CL:0000197|sensory receptor cell
|YES|CL:0000211|electrically active cell
|YES|CL:0000212|absorptive cell
|YES|CL:0000215|barrier cell
|?|CL:0000219|motile cell
|YES|CL:0000325|stuff accumulating cell
|YES|CL:0000329|oxygen accumulating cell
|?|CL:0000412|polyploid cell
|NO|CL:0000413|haploid cell
|?|CL:0000415|diploid cell
|YES|CL:0000445|apoptosis fated cell
|?|CL:0000520|prokaryotic cell
|?|CL:0000627|transporting cell
|YES|CL:0000628|photosynthetic cell
|YES|CL:0000663|valve cell
|YES|CL:0000725|nitrogen fixing cell
|YES|CL:0000891|foam cell
|?|CL:0002242|nucleate cell
|YES|CL:0007001|skeletogenic cell
|YES|CL:0007005|notochordal cell
|YES|CL:0007023|flask cell
|YES|CL:0009010|transit amplifying cell
|YES|CL:0010007|His-Purkinje system cell
|NO|CL:0010017|zygote
|?|CL:0011115|precursor cell
|YES|CL:2000004|pituitary gland cell
|YES|CL:2000020|inner cell mass cell
|YES|CL:2000021|sebaceous gland cell
|YES|CL:2000022|cardiac septum cell
|YES|CL:2000030|hypothalamus cell
|YES|CL:0000293|structural cell
|YES|CL:0000473|defensive cell
|?|CL:0000255|eukaryotic cell
|YES|CL:0000151|secretory cell
|?|CL:0000225|anucleate cell
|?|CL:0000064|ciliated cell
|YES|CL:0000422|mitogenic signaling cell
|YES|CL:0000630|supportive cell

alternatively we could try and auto-classify these.

**Comment by cmungall** [comment]
I think if we keep terms in CL we need to do a good job of ensuring **reasonable completeness**. If we can't commit to doing this for somatic cell let's get rid of it, it's confusing as it is now as it is so incomplete

**Comment by dosumis** [comment]
Notes from CL call:
  - No one gave an especially strong argument for keeping the term so we suggest obsoletion.  However, before obsoletion we should check completely for any usage in other ontologies (follow links to usage context here: http://www.ontobee.org/ontology/CL?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002371 )  and provide a community announcement.

**Comment by paolaroncaglia** [comment]
Also see https://github.com/obophenotype/cell-ontology/issues/530

**Comment by cmungall** [comment]
[let's keep this one active]

sounds like we are agreed on obsoletion

**Comment by bvarner-ebi** [comment]
Checking in on this ticket.

@cmungall, in addition to obsoleting 'native cell' and 'animal cell' in https://github.com/obophenotype/cell-ontology/issues/2124, are you proposing to also obsolete 'somatic cell'?

If yes, an announcement for planned obsoletion will be made on Slack #cl-editors and the term will be marked for obsoletion.
If no, kindly clarify action item or close ticket.

**Comment by cmungall** [comment]
While the issues have similarities (unsustainable and confusing groupings) I think they can be decoupled (though we may want to time this so we do it all at once)

But yes, that is the decision that we seem to have reached here, obsolete somatic cell
