### ISSUE TITLE
[NTR] enteroendocrine cell of small intestine

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#1156]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enteroendocrine cell of small intestine

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enteroendocrine cell that is located in the small intestine.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal enteroendocrine cell http://purl.obolibrary.org/obo/CL_1001516

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
small intestine http://purl.obolibrary.org/obo/UBERON_0002108

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
The new term is CL_0009006 (enteroendocrine cell of small intestine). 
Not sure when the next CL release will be, as there was one last week, but they are fairly frequent now. If not, I'll ask to run one when I've committed more of your term requests.
Best,
Paola
