### ISSUE TITLE
Make anatomograms use case explicit

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1165]
As discussed at a CL editors meeting and summarized [here](https://github.com/obophenotype/cell-ontology/issues/1001#issuecomment-804309266), "Mention use case more explicitly in new term(s) [created for the Single Cell Expression Atlas], e.g. "do not use for annotation" if the term is generic and one could use a more specific term, and/or indicate that the term will be used in an anatomogram.". One way to do this could be to wait for all anatomogram requests to be addressed, then search for the subset tag "location grouping", and, if appropriate/necessary, add a comment "This term was created for use in the EMBL-EBI Single Cell Expression Atlas anatomograms. Other users may wish to choose more specific cell type terms if applicable.".
- [x] Run the suggested phrasing by CL editors
- [x] Resolve on what annotation property to use: editor note IAO:0000116, or editor_note, or ...?

**Comment by dosumis** [comment]
I like the advisory comment.  It's good to encourage use of more precise terms, but don't want to give the impression that the term should not be used.

Perhaps:

"This is a general grouping term created for use in the EMBL-EBI Single Cell Expression Atlas anatomograms.  Please use a more specific cell type term for annotation if this is possible, given the information available to you."

?

**Comment by paolaroncaglia** [comment]
Thanks @dosumis , very helpful. 

Note to self, here's the plan then:
when all NTRs for SCA anatomogram are addressed, search for terms with the subset tag "location grouping", and, if appropriate/necessary, 
- [ ] add an rdfs:comment to each "This is a general grouping term created for use in the EMBL-EBI Single Cell Expression Atlas anatomograms. Please use a more specific cell type term for annotation if possible, given the information available to you."

**Comment by paolaroncaglia** [comment]
Note to self: the plan above can be implemented now, I'll do it.

**Comment by paolaroncaglia** [comment]
Note to self: I'm _not_ adding the rdfs:comment ("This is a general grouping term created for use in the EMBL-EBI Single Cell Expression Atlas anatomograms. Please use a more specific cell type term for annotation if possible, given the information available to you.") if

- there aren't currently any more specific terms to use for annotation (i.e. the parent term doesn't have any existing child with specification/differentia other than location)
- there are already pre-existing location-based "siblings" of the term.

So far, I _have_ added the comment to SCEA terms that are subclasses of

- lymphocyte 
- B cell
- T cell
- plasma cell
- stratified squamous epithelial cell.
