### ISSUE TITLE
[NTR] Hillock Cell

### ISSUE THREAD

**Issue by GHAStVHenry** [obophenotype/cell-ontology#1171]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Hillock Cell

**Synonyms**
hillock cell of bronchiole

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Krt13+ epithelial cells found in the respiratory tract
PMID:30069044
PMID:32726565
PMID:33208946
PMID:33442032

See review PMID:33442032: entire paragraph on Hillock cells...

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0002328

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:0000065

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-7772-9578

**Any additional notes or concerns**
Used it ID similar cell type in urethra #1134

**Comment by paolaroncaglia** [comment]
Note to CL editors:
I removed the automated assignments as this ticket hasn't been actually picked up (though @emquardokus commented);
There are 4 NTRs by the same submitter: https://github.com/obophenotype/cell-ontology/issues/1133 (urethra), https://github.com/obophenotype/cell-ontology/issues/1134 (urethra), https://github.com/obophenotype/cell-ontology/issues/1135 (prostate) and https://github.com/obophenotype/cell-ontology/issues/1171 (bronchiole).

**Comment by cakirb** [comment]
Hello,

What is the current status of this term? Thanks!

**Comment by dosumis** [comment]
@bvarner-ebi can we make this a high priority. Thanks!

**Comment by bvarner-ebi** [comment]
@GHAStVHenry, thank you for the new cell request.

For your requested synonym, do you have a reference to attach to that? After scanning your supplied references, it seems these cells are discussed in context of the trachea and airway epithelium. I haven't found a reference specifically to a 'hillock cell of bronchiole'. 

Similarly, should the parent cell type be CL:0002368 'respiratory epithelial cell' as I did not see this being restricted to the bronchioles? We could also consider adding parent cell type CL:0000307 'tracheal epithelial cell'.

fyi @emquardokus.

**Comment by GHAStVHenry** [comment]
> @GHAStVHenry, thank you for the new cell request.
> 
> For your requested synonym, do you have a reference to attach to that? After scanning your supplied references, it seems these cells are discussed in context of the trachea and airway epithelium. I haven't found a reference specifically to a 'hillock cell of bronchiole'.
> 
> Similarly, should the parent cell type be CL:0002368 'respiratory epithelial cell' as I did not see this being restricted to the bronchioles? We could also consider adding parent cell type CL:0000307 'tracheal epithelial cell'.
> 
> fyi @emquardokus.

Lung isn't my expertise, but your suggestions make sense. I only put in this request because the lung hillock signature is how we identified the related cell in the urethra (#1134).

**Comment by bvarner-ebi** [comment]
@GHAStVHenry, thanks for the feedback.
There is a PR ready for review: https://github.com/obophenotype/cell-ontology/pull/1624.

**Comment by emquardokus** [comment]
@bvarner-ebi

**Comment by emquardokus** [comment]
@bvarner-ebi I commented on PR---I do not think based on literature hillock cell is restricted to respiratory system. See comment on PR.

**Comment by bvarner-ebi** [comment]
Agreed. Does it make sense to you to label this term as 'hillock cell of respiratory epithelium'?
We could make a separate parent term for 'hillock cell' and place this term and one requested in #1134 under it.

**Comment by stranddw** [comment]
This should be labeled as hillock cell of urethral epithelium.

**Comment by GHAStVHenry** [comment]
@stranddw @emquardokus this is the submission for lung hillock, not urethra
