### ISSUE TITLE
Trying to solve serialisation/diff issues

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#1175]
@lubianat  @paolaroncaglia  @dosumis (tag any other CL Editors that have edited CL in the last 3 months). Please provide, in a comment here, three pieces of information (please dont update anything, just share the information as is):

1. A screenshot of your Protege->About information, see attached.
1. The exact version of your operating system
1. The output of `docker images obolibrary/odkfull` on your terminal (if you have docker installed, if not, say so)
1. The output of `robot --version` if you have ROBOT installed, if not, say so

![image](https://user-images.githubusercontent.com/7070631/126125739-44b81517-d176-410f-8cc0-9e2f402b0b79.png)

I have some mid-term strategy moving forward, but it will take a moment to put it in place (in involves updated the OWLAPI version in Protege without actually updating Protege).

- #1176 @shawntanzk Normalisation PR

**Comment by dosumis** [comment]
![image](https://user-images.githubusercontent.com/112839/126126833-2d3336e5-64d0-44f7-bedd-89eeb24411a4.png)
![image](https://user-images.githubusercontent.com/112839/126126900-0ed22ec5-68f1-484e-8fb0-2b2f1ef97fb1.png)

obolibrary/odkfull   latest    cb723cf17266   2 months ago    2.18GB
obolibrary/odkfull   <none>    6e43317fb08d   5 months ago    2.09GB

ROBOT version 1.8.1

**Comment by matentzn** [comment]
@dosumis your `docker image` output does not indicate the version tag? Mine says, for example:

```
~ $ docker images obolibrary/odkfull
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
obolibrary/odkfull   latest    3950a2ef3f73   3 weeks ago     2.38GB
obolibrary/odkfull   v1.2.30   3950a2ef3f73   3 weeks ago     2.38GB
obolibrary/odkfull   v1.2.29   702666a4e0c0   3 weeks ago     2.38GB
obolibrary/odkfull   v1.2.28   bd19f2ddd82a   2 months ago    2.22GB
```

**Comment by paolaroncaglia** [comment]
> @lubianat @paolaroncaglia @dosumis (tag any other CL Editors that have edited CL in the last 3 months). 

Tagging @shawntanzk, @cmungall , @nicolevasilevsky , @addiehl , and @lubianat for his information.

> Please provide, in a comment here, three pieces of information (please dont update anything, just share the information as is):
> 
>     1. A screenshot of your Protege->About information, see attached.
> 
>     2. The exact version of your operating system
> 
>     3. The output of `docker images obolibrary/odkfull` on your terminal (if you have docker installed, if not, say so)
> 
>     4. The output of `robot --version` if you have ROBOT installed, if not, say so
> 
> 
> ![image](https://user-images.githubusercontent.com/7070631/126125739-44b81517-d176-410f-8cc0-9e2f402b0b79.png)
> 
> I have some mid-term strategy moving forward, but it will take a moment to put it in place (in involves updated the OWLAPI version in Protege without actually updating Protege).

**Comment by dosumis** [comment]
Seems not 

```
$ docker images obolibrary/odkfull
REPOSITORY           TAG       IMAGE ID       CREATED         SIZE
obolibrary/odkfull   latest    cb723cf17266   2 months ago    2.18GB
obolibrary/odkfull   <none>    6e43317fb08d   5 months ago    2.09GB
```

**Comment by paolaroncaglia** [comment]
1. ![Screen Shot 2021-07-19 at 10 42 18](https://user-images.githubusercontent.com/4982516/126130594-04d1d687-d66a-451d-9012-afd09eb98dcd.png)

2. ![Screen Shot 2021-07-19 at 10 43 38](https://user-images.githubusercontent.com/4982516/126130768-37e35c82-0ba1-40e4-aa44-54003b9b54df.png)

3. I don't have docker installed

4. I don't have ROBOT installed

Thanks @matentzn !

**Comment by shawntanzk** [comment]
1. 
![Screenshot 2021-07-19 at 09 45 26](https://user-images.githubusercontent.com/76212760/126131401-741dee7f-97dc-4534-9388-1de710f97319.png)
2. 
![Screenshot 2021-07-19 at 09 48 56](https://user-images.githubusercontent.com/76212760/126131662-72e405be-8c6a-466c-903a-ce311ef0733d.png)
3. 
```
shawntan@C02DW26DML87 ontology % docker images obolibrary/odkfull
REPOSITORY           TAG       IMAGE ID       CREATED        SIZE
obolibrary/odkfull   latest    742aa3c8a1a2   5 weeks ago    2.35GB
obolibrary/odkfull   <none>    cb723cf17266   2 months ago   2.18GB
obolibrary/odkfull   <none>    d9f55e6b6404   3 months ago   2.17GB
```
4.
```
shawntan@C02DW26DML87 ontology % sh run.sh robot --version
ROBOT version 1.8.1
```

**Comment by lubianat** [comment]
1.
![image](https://user-images.githubusercontent.com/7917951/126160226-e68781a9-ef2f-4aff-b8df-0c76fe707b99.png)

2.
![image](https://user-images.githubusercontent.com/7917951/126160751-386d3c6c-211a-42e7-9cb3-47f1ab86e50c.png)

3. 
```
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
obolibrary/odkfull   latest              742aa3c8a1a2        5 weeks ago         2.35GB
```
4. ROBOT is not installed

**Comment by nicolevasilevsky** [comment]
![image](https://user-images.githubusercontent.com/6722114/126182364-f7215d2f-0224-4cbd-86b8-427680a0e1fe.png)

![image](https://user-images.githubusercontent.com/6722114/126182407-4752959d-8710-45e4-82b2-8c57db08024d.png)

![image](https://user-images.githubusercontent.com/6722114/126182740-9cc99705-e50f-45d1-a2cc-27642f279683.png)

I guess I don't have ROBOT installed on this new computer:
nicolevasilevsky@CHAI-M-C02FK38 ~ % robot --version
zsh: command not found: robot
nicolevasilevsky@CHAI-M-C02FK38 ~ %

**Comment by matentzn** [comment]
Sorry to bug you all again. Can you please:
1. Open CL (Edit file)
2. Save as RDFXML somewhere
3. share here the last two lines of that file (e.g. `tail -2 ~/cl.owl`)

Example:

```
matentzn@mbp:~ $ tail -2 ~/cl.owl
<!-- Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi -->

```

**Comment by shawntanzk** [comment]
I have the same as yours @matentzn 

`<!-- Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi -->`

**Comment by paolaroncaglia** [comment]
Me too @matentzn :

**Comment by lubianat** [comment]
@matentzn did the same here, same result too: 
`<!-- Generated by the OWL API (version 4.5.9.2019-02-01T07:24:44Z) https://github.com/owlcs/owlapi -->`

**Comment by matentzn** [comment]
For now, we use this strategy:
https://obophenotype.github.io/cell-ontology/Fixing_xsdstring_diffs.html

Expect some hiccups for a few weeks while pull requests are being merged which are not yet normalised. 

The longer term solution is to ensure
- [ ] https://github.com/owlcs/owlapi/issues/1004 gets fixed
- [ ] We get a new Protege release
- [ ] We update ROBOT with the new serialisers

For now, this wont fix - so I will close it - the discussion will resume on the OWLAPI trakcer.

**Comment by matentzn** [comment]
@cmungall 

See here a diff that @gouttegd got when editing an OBO file with the newest OWL API. Can you check its all in order?

[fbbt-edit.obo.txt](https://github.com/obophenotype/cell-ontology/files/6869788/fbbt-edit.obo.txt)

**Comment by cmungall** [comment]
so `+` is the newer version?

this doesn't look good:

```
-property_value: IAO:0006011 FBbt:00000464 {xref="FlyBase:FBrf0076757", xref="FlyBase:FBrf0228644", xref="FlyBase:FBrf0228646"}
+property_value: IAO:0006011 "FBbt:00000464" {xref="FlyBase:FBrf0076757", xref="FlyBase:FBrf0228644", xref="FlyBase:FBrf0228646"}
```

some differences wrt escaping, neither right nor wrong as the spec has always been underspecified here

```
-comment: Pre-synaptic terminals were assessed by labelling with a UAS-Synaptotagmin reporter (P\{UAS-HA-syt}) [FBtp0015803]. The neurotransmitter was assessed by labelling cells with an anti-ChAT antibody (Hasegawa et al., 2011). The morphology of the terminals was judged from figures in Fischbach and Dittrich (1989) as assessed by FlyBrain Neuron DB. Connectivity and morphology in the medulla were assessed by electron microscopy reconstruction from 7 columns (Takemura et al., 2013).
+comment: Pre-synaptic terminals were assessed by labelling with a UAS-Synaptotagmin reporter (P\{UAS-HA-syt\}) [FBtp0015803]. The neurotransmitter was assessed by labelling cells with an anti-ChAT antibody (Hasegawa et al., 2011). The morphology of the terminals was judged from figures in Fischbach and Dittrich (1989) as assessed by FlyBrain Neuron DB. Connectivity and morphology in the medulla were assessed by electron microscopy reconstruction from 7 columns (Takemura et al., 2013).
```

we need to test on more than fbbt. Is there a robot jar I could test?

**Comment by matentzn** [comment]
https://www.dropbox.com/s/3wr8lcuz3pkopoo/robot.jar?dl=0
