### ISSUE TITLE
NTR: brain vascular pericyte

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#118]
```
Label: brain vascular pericyte

Synonyms:

Text definition:

Definition source: CL:0000184 "pericyte"

Genus/parent:

Differentiae:

Other relationships:
part_of UBERON:0005284


```

Original issue reported on code.google.com by `vmall...@stanford.edu` on 2 Apr 2014 at 5:32

**Comment by shawntanzk** [comment]
we already have brain pericyte (CL:2000043) which from my understand (I might be wrong) is brain vascular pericyte (given pericytes are present in capillaries and all) - will close this for now, please open up again if I'm wrong and there needs to be a separate term
