### ISSUE TITLE
[Typo/Bug]. Incorrect classifications under epithelial cell

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1183]
epithelial cell
EquivalentTo: 'animal cell' and ('part of' some epithelium)

=> various misclassifications

e.g. 

![image](https://user-images.githubusercontent.com/112839/126355113-804c0010-54ad-4674-9cba-3f3608b0fd76.png)

Relaxing the EquivalentClass axiom to subClassOf fixes this and reduces subclasses  from 664 to 643.  

I think this is probably the right approach to fixing, but it is worth surveying the cells lost to this classification for anything that should be manually asserted.

**Comment by shawntanzk** [comment]
These are the direct subclasses that get removed when switching from equiv to subclass

amnioserosal cell <- this currently doesn't have description etc. on CL, might need to ask a fly person to help add those in? but I think it is an epithelial cell according to https://www.pnas.org/content/105/1/234 (happy to assert it) 

> "Higher cyclorrhaphan flies including Drosophila develop a single extraembryonic epithelium (amnioserosa), which closes the germband dorsally."

reticular layer of dermis fibroblast <- this was the weird one that you were mentioning above I'm guessing

yolk sac hematopoietic stem cell <- seems appropriate to be removed
