### ISSUE TITLE
[Typo/Bug] are mesothelial fibroblasts mesothelial cells

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1184]
**CL term**

rdfs:label "mesothelial fibroblast"
definition "A mesothelial cell that has undergone mesothelial-to-mesenchymal transition (MMT) to become a fibroblast cell."
subClassOf:
'mesothelial cell'
fibroblast

**Description of typo, bug or error**

From the definition it sounds like these should be fibroblasts that develop_from some 'mesothelial cell'- not mesothelial cells themselves (which are epithelial).

**Comment by shawntanzk** [comment]
From my understanding (from reading the paper cited at least), develop_from some 'mesothelial cell' should be correct, but I'm not 100% sure on this. Wonder if there is anyone more familiar with this we can bring in to this discussion? I'll change this for now in a PR, but would like a second opinion ideally.
