### ISSUE TITLE
Close all stalled issues?

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#1234]
From the CL meeting on August 18th, 2021:

Shall we automatically close existing issues that have not been updated in the past 3 years, as we have recently done for Uberon?

If so:
- [ ] Shall an editor do a pass on those issues before we trigger the closing script, to protect some worthy issues from auto-closing (again similar to what we have done for Uberon)?
- [ ] Should we use the same age threshold as for Uberon (3 years)?

For information, as of today there are 182 issues that have not seen any update in the last 3 years.

CL editors who were not present in the August 18th meeting are invited to weigh in.

**Comment by shawntanzk** [comment]
Think 3 years is a good amount of time :)

**Comment by paolaroncaglia** [comment]
> Shall we automatically close existing issues that have not been updated in the past 3 years, as we have recently done for Uberon?
> 
> If so:
> 
>     * [ ]  Shall an editor do a pass on those issues before we trigger the closing script, to protect some worthy issues from auto-closing (again similar to what we have done for Uberon)?
> 
>     * [ ]  Should we use the same age threshold as for Uberon (3 years)?
> 
> For information, as of today there are 182 issues that have not seen any update in the last 3 years.

I had a quick glance at some of those 182 tickets. At least some of them look worthy of consideration before auto-closing en masse. E.g., several tickets look neuron-related, so may be in scope for specific funded projects. Other may be in scope for the Human Cell Atlas. Others still may have been addressed, or out of date, or ok to close anyway. If we're willing/able to put in a bit of our time, we could split say the 100 oldest tickets among as many of us as possible and take a quick look? Even 5-10 minutes per ticket would make a difference, even if we can't fully address all requests. Then apply Damien's workflow on what's left. And repeat once per quarter?

**Comment by shawntanzk** [comment]
Happy to do so :) 
I've seen some of the neuro ones and think they can probably be closed (or maybe some discussion continuing that imo is secondary) - havent done so just cause if we are going to implement the above, it might be better use the automated thing to ping the people assigned on them to see if they have anything else to add/change. Happy to split tickets and go through instead :)

**Comment by gouttegd** [comment]
We are now at 117 issues that would be closed with a threshold set at 3 years.

I propose to give us one more month to check some more of those issues (and either fix them directly or at least tag them or comment on them — anything to mark them as "active"), and then by the end of October I unleash the auto-closing script.

Would everyone be happy with that?

**Comment by gouttegd** [comment]
For reference, here are the issues that would be closed as of today:

| Issue | Author | Team? | Assignee(s) |
| ----- | ------ | ----- | ----------- |
| [Define strategy for handling new proposed cell types derived from clustering transcriptomic and other data](https://github.com/obophenotype/cell-ontology/issues/520) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Single cell transcriptome profiling of retinal ganglion cells identifies cellular subtypes](https://github.com/obophenotype/cell-ontology/issues/519) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [suppressor macrophage](https://github.com/obophenotype/cell-ontology/issues/518) | @[cmungall](https://github.com/cmungall) | Yes | @[addiehl](https://github.com/addiehl) |
| [fibrocyte](https://github.com/obophenotype/cell-ontology/issues/517) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [kidney interstitial cell subtypes](https://github.com/obophenotype/cell-ontology/issues/516) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [glomerular mesangial cell](https://github.com/obophenotype/cell-ontology/issues/515) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [renal interstitial pericyte](https://github.com/obophenotype/cell-ontology/issues/514) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [KCD renal intercalated cell](https://github.com/obophenotype/cell-ontology/issues/513) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Proposal: obsolete meso/metanephros subtypes for many kidney cell types](https://github.com/obophenotype/cell-ontology/issues/512) | @[cmungall](https://github.com/cmungall) | Yes |  |
| ["juxtaglomerular complex cell" is an unintuitive group](https://github.com/obophenotype/cell-ontology/issues/511) | @[cmungall](https://github.com/cmungall) | Yes | @[addiehl](https://github.com/addiehl) |
| [Add is_a edge between CL:0000451 and CL:0000145](https://github.com/obophenotype/cell-ontology/issues/507) | @[mbernste](https://github.com/mbernste) | No |  |
| [Add icon images from Reactome](https://github.com/obophenotype/cell-ontology/issues/504) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Add synonym 'Treg' for term CL:0000815](https://github.com/obophenotype/cell-ontology/issues/503) | @[mbernste](https://github.com/mbernste) | No |  |
| [Add edge CL:0008001 is_a CL:0011115 ](https://github.com/obophenotype/cell-ontology/issues/502) | @[mbernste](https://github.com/mbernste) | No |  |
| [Bad ZFA mappings](https://github.com/obophenotype/cell-ontology/issues/501) | @[balhoff](https://github.com/balhoff) | Yes |  |
| [Fibro/adipogenic progenitors](https://github.com/obophenotype/cell-ontology/issues/500) | @[Alessandro-Palma](https://github.com/Alessandro-Palma) | No |  |
| [peripheral blood](https://github.com/obophenotype/cell-ontology/issues/499) | @[tuli](https://github.com/tuli) | No |  |
| [Faulty term ID in obo file for 'alobate nucleus'](https://github.com/obophenotype/cell-ontology/issues/498) | @[cmpich](https://github.com/cmpich) | No |  |
| [Two term stanza do not have a name tag in the obo file](https://github.com/obophenotype/cell-ontology/issues/497) | @[cmpich](https://github.com/cmpich) | No |  |
| [No default-namespace in obo file header](https://github.com/obophenotype/cell-ontology/issues/496) | @[cmpich](https://github.com/cmpich) | No |  |
| [Distribute nif_import.owl in RDF/XML?](https://github.com/obophenotype/cell-ontology/issues/495) | @[jonathanbona](https://github.com/jonathanbona) | No |  |
| [lacks part relation](https://github.com/obophenotype/cell-ontology/issues/483) | @[lgcowell](https://github.com/lgcowell) | No |  |
| [create mapping of CL to NCIt cell classes](https://github.com/obophenotype/cell-ontology/issues/481) | @[nicolevasilevsky](https://github.com/nicolevasilevsky) | Yes | @[cmungall](https://github.com/cmungall) |
| [adipocyte (white/brown/beige) classification, definitions and axioms](https://github.com/obophenotype/cell-ontology/issues/479) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [NTR: annulus fibrosus cell](https://github.com/obophenotype/cell-ontology/issues/478) | @[jahilton](https://github.com/jahilton) | Yes |  |
| [NTR: HFF-Myc](https://github.com/obophenotype/cell-ontology/issues/477) | @[jahilton](https://github.com/jahilton) | Yes |  |
| [Definition update for CL_0000178](https://github.com/obophenotype/cell-ontology/issues/471) | @[cerivs](https://github.com/cerivs) | Yes |  |
| [Fix import generation](https://github.com/obophenotype/cell-ontology/issues/470) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Ensure correct annotation properties are always used](https://github.com/obophenotype/cell-ontology/issues/467) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| ['female germ cell' not capable of oogenesis relationship](https://github.com/obophenotype/cell-ontology/issues/457) | @[dosumis](https://github.com/dosumis) | Yes |  |
| [Update CL xrefs to species-specific AOs](https://github.com/obophenotype/cell-ontology/issues/452) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [vestibular afferent neuron](https://github.com/obophenotype/cell-ontology/issues/451) | @[dosumis](https://github.com/dosumis) | Yes |  |
| [Cede fungal cell types to FAO](https://github.com/obophenotype/cell-ontology/issues/447) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Are APUD (amine precursor uptake and decarboxylation) cells always NC-derived?](https://github.com/obophenotype/cell-ontology/issues/446) | @[cmungall](https://github.com/cmungall) | Yes | @[cerivs](https://github.com/cerivs), @[ybradford](https://github.com/ybradford) |
| [NTRs](https://github.com/obophenotype/cell-ontology/issues/445) | @[jahilton](https://github.com/jahilton) | Yes | @[addiehl](https://github.com/addiehl) |
| [neutrophil CL:0000775 logical definition](https://github.com/obophenotype/cell-ontology/issues/443) | @[cerivs](https://github.com/cerivs) | Yes |  |
| [linking CL terms to UBERON terms](https://github.com/obophenotype/cell-ontology/issues/430) | @[jahilton](https://github.com/jahilton) | Yes |  |
| [NTR:  keratinized cell of hair follicle](https://github.com/obophenotype/cell-ontology/issues/417) | @[YasminAF](https://github.com/YasminAF) | No | @[dosumis](https://github.com/dosumis) |
| [Use a consistent obo-namespace tag in obo format exports](https://github.com/obophenotype/cell-ontology/issues/413) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [temporal relation used in CL](https://github.com/obophenotype/cell-ontology/issues/181) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [CL_0008023 is a replaced term](https://github.com/obophenotype/cell-ontology/issues/179) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [missing classifications under "animal cell" and "eukaryotic cell"](https://github.com/obophenotype/cell-ontology/issues/178) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Classification under 'somatic cell'](https://github.com/obophenotype/cell-ontology/issues/177) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Failed to parse cl.obo due to a loop in the term relationships: StackOverflowError](https://github.com/obophenotype/cell-ontology/issues/174) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Fix def of granulosa cell](https://github.com/obophenotype/cell-ontology/issues/173) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTRs for 'adult Leydig cell' and for 'fetal Leydig cell', possibly split or relabel existing CL:0000178](https://github.com/obophenotype/cell-ontology/issues/172) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [cholangiocte improvements](https://github.com/obophenotype/cell-ontology/issues/171) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: otic epithelial cell](https://github.com/obophenotype/cell-ontology/issues/169) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: anterior visceral endoderm cell ](https://github.com/obophenotype/cell-ontology/issues/168) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [olfactory epithelium cells](https://github.com/obophenotype/cell-ontology/issues/167) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Hepatic pit cell](https://github.com/obophenotype/cell-ontology/issues/165) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [intraepithelial cells](https://github.com/obophenotype/cell-ontology/issues/164) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: ](https://github.com/obophenotype/cell-ontology/issues/159) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| ['visual pigment cell' needs definition](https://github.com/obophenotype/cell-ontology/issues/158) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [melanocyte should not be a subclass of neurecto-epithelial cell](https://github.com/obophenotype/cell-ontology/issues/157) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Add part_of axioms for horizontal cel](https://github.com/obophenotype/cell-ontology/issues/155) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR:  Segmented neutrophil in Bone marrow](https://github.com/obophenotype/cell-ontology/issues/152) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Review precursor B-Cell and its subclasses, proposing parallel minimal commitment EC axioms](https://github.com/obophenotype/cell-ontology/issues/151) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: CD8/CD4 positive T cell](https://github.com/obophenotype/cell-ontology/issues/149) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [cl-plus-fbbt is incoherent](https://github.com/obophenotype/cell-ontology/issues/147) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Add MESH xrefs](https://github.com/obophenotype/cell-ontology/issues/146) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Project: Review all cases where cell types have multiple develops_from relatiionships](https://github.com/obophenotype/cell-ontology/issues/145) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Project: separate out developmental precursor cells from stem cell heirarchy](https://github.com/obophenotype/cell-ontology/issues/144) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Proposal for segregating marker axioms in CL](https://github.com/obophenotype/cell-ontology/issues/143) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [mesenchymal cell / mesenchymal stem cell (CL_0000134)](https://github.com/obophenotype/cell-ontology/issues/142) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [cardioblast has no relationship to 'cardiac muscle myoblast'](https://github.com/obophenotype/cell-ontology/issues/140) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Consider adding axiom: glandular epithelial cells are columnar/cuboidal](https://github.com/obophenotype/cell-ontology/issues/139) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: mature dendritic cell](https://github.com/obophenotype/cell-ontology/issues/135) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [add part_of relation in CL:0000066 and in CL:0000586](https://github.com/obophenotype/cell-ontology/issues/134) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Should a "naive regulatory T cell" be is_a "regulatory T cell"?](https://github.com/obophenotype/cell-ontology/issues/133) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) CD11c in "myeloid dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/132) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “C-X-C chemokine receptor type 3” missing in "Tc17 cell"](https://github.com/obophenotype/cell-ontology/issues/129) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “low affinity immunoglobulin gamma Fc region receptor III” missing in "myeloid dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/128) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “CD14 molecule” missing in "myeloid dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/127) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “low affinity immunoglobulin gamma Fc region receptor III” missing in "plasmacytoid dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/126) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “CD14 molecule” missing in "plasmacytoid dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/125) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “low affinity immunoglobulin gamma Fc region receptor III” missing in "dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/124) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [(flowCL project) Lacks pmp “CD14 molecule” missing in "dendritic cell, human"](https://github.com/obophenotype/cell-ontology/issues/123) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: 3 new terms](https://github.com/obophenotype/cell-ontology/issues/121) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Ensure FBbt xrefs are up to date](https://github.com/obophenotype/cell-ontology/issues/115) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [new term proposal catecholaminergic neuron](https://github.com/obophenotype/cell-ontology/issues/114) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Create importer that brings plant and animal cells into same ontology](https://github.com/obophenotype/cell-ontology/issues/106) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Create strategy for maintaining axioms connecting ssAOs to CL](https://github.com/obophenotype/cell-ontology/issues/105) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [merge egg (cell) and female gamete](https://github.com/obophenotype/cell-ontology/issues/100) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [New neuron grouping term/cell types.](https://github.com/obophenotype/cell-ontology/issues/99) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [rename 'skeletal muscle cell' to 'cell of skeletal muscle' ??](https://github.com/obophenotype/cell-ontology/issues/95) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: intestinal stem cell](https://github.com/obophenotype/cell-ontology/issues/79) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| ["lacks" relations as object properties (between individuals) are not meaningful:](https://github.com/obophenotype/cell-ontology/issues/77) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [relabel 'phenotype' classes](https://github.com/obophenotype/cell-ontology/issues/76) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [remove in appropriate Schwann cell syns](https://github.com/obophenotype/cell-ontology/issues/75) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Review request: basic muscle cell hierarchy](https://github.com/obophenotype/cell-ontology/issues/72) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: undifferentiated osteoblast](https://github.com/obophenotype/cell-ontology/issues/62) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Update label for CL:0002000](https://github.com/obophenotype/cell-ontology/issues/45) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: antigen-presenting cell](https://github.com/obophenotype/cell-ontology/issues/37) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [use IAO replaced_by property for obsoletes](https://github.com/obophenotype/cell-ontology/issues/35) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [adding support for evidence codes to CL](https://github.com/obophenotype/cell-ontology/issues/34) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [peripheral ganglia should have neruon that they are part of](https://github.com/obophenotype/cell-ontology/issues/32) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Align thymocyte / DN T Cell with MP](https://github.com/obophenotype/cell-ontology/issues/31) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [axioms of pancreas related cell types](https://github.com/obophenotype/cell-ontology/issues/29) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: electrocyte](https://github.com/obophenotype/cell-ontology/issues/24) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [CL:1000409 'myocyte of sinoatrial node' vs CL:1000477 'cardiac pacemaker cell of sinoatrial node' ](https://github.com/obophenotype/cell-ontology/issues/23) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [CL:0002339 'prostate stem cell' vs CL:0002341 'basal cell of prostate epithelium' ](https://github.com/obophenotype/cell-ontology/issues/22) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [merge CL:1000416 'myoepithelial cell of lactiferous gland' into CL:0002324 'myoepithelial cell of mammary gland' ](https://github.com/obophenotype/cell-ontology/issues/21) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Adopt common naming conventions for compositional terms](https://github.com/obophenotype/cell-ontology/issues/20) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTRs: subclasses of blastoderm cell](https://github.com/obophenotype/cell-ontology/issues/18) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [NTR: Koniocellular cell](https://github.com/obophenotype/cell-ontology/issues/17) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [mesenchymal cell](https://github.com/obophenotype/cell-ontology/issues/16) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [Cell type terms required by GO](https://github.com/obophenotype/cell-ontology/issues/15) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [PATO differentium for non-terminallly differentiated cell](https://github.com/obophenotype/cell-ontology/issues/8) | @[GoogleCodeExporter](https://github.com/GoogleCodeExporter) | No |  |
| [displaced (inverted) amacrine cell](https://github.com/obophenotype/cell-ontology/issues/380) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [lacks_part and lacks_plasma_membrane_part](https://github.com/obophenotype/cell-ontology/issues/379) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [CL:0000432 ! reticular cell - definition](https://github.com/obophenotype/cell-ontology/issues/369) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [CL:0002520 ! nephrocyte](https://github.com/obophenotype/cell-ontology/issues/366) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [CL:0000746 ! A myocyte located in the heart. The contractile](https://github.com/obophenotype/cell-ontology/issues/351) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [NTR: endothelial progenitor cell](https://github.com/obophenotype/cell-ontology/issues/348) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [CL to AO part_of links](https://github.com/obophenotype/cell-ontology/issues/271) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |
| [sensu terms](https://github.com/obophenotype/cell-ontology/issues/190) | @[cmungall](https://github.com/cmungall) | Yes | @[cmungall](https://github.com/cmungall) |

**Comment by addiehl** [comment]
Is adding a new label enough to spare from closing?  There are multiple kidney related items that should be addressed as part of the KPMP and HuBMAP project work.  I am adding the 'KPMP' label to these.

**Comment by gouttegd** [comment]
Yes, adding a label counts as an "activity" from the point of view of the auto-closing script, so it's enough to prevent auto-closing.

**Comment by gouttegd** [comment]
44 old issues have now been closed. They are [all tagged](https://github.com/obophenotype/cell-ontology/issues?q=is%3Aissue+label%3Aautoclosed-unfixed+is%3Aclosed) with the `autoclosed-unfixed` label.

Thanks to those who contributed to cut down the number of inactive issues by 75% (down from 182 issues when this ticket was opened) in the last two months!

Now that we have an automated procedure to _regularly_ flag and close stale issues, there will be no more need for mass closures like this one.
