### ISSUE TITLE
Import UBERON:8410065 and UBERON:8410066

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1252]
@matentzn @shawntanzk please:

I need to import two Uberon terms in CL (needed for SCA anatomograms):

UBERON:8410065 'lymph node follicle marginal zone'
for https://github.com/obophenotype/cell-ontology/issues/975

UBERON:8410066 lymph node paracortex
for https://github.com/obophenotype/cell-ontology/issues/988

I don't have ODK or ROBOT tools on my machine. Shall I follow the instruction in "Protege-based declaration" [here](https://obophenotype.github.io/cell-ontology/odk-workflows/UpdateImports.html#protege-based-declaration), and then ask one of you to refresh the Uberon import please? Or are there still issues with that?
Thanks in advance!

Paola

**Comment by matentzn** [comment]
There is no pure protege based solution I am afraid, as you do have to refresh the import no matter what with ROBOT. We will do it for you until you have your new machine up and running, then we train you to do it yourself :)

**Comment by shawntanzk** [comment]
Uberon import is pretty broken at the moment due to a obsolete term :( 
@matentzn will this be fixed soon? If not I can go add these terms (and one I need) and hack at the import file for now

**Comment by paolaroncaglia** [comment]
@matentzn @shawntanzk 
Thank you both very much. I'll wait for updates then.

**Comment by matentzn** [comment]
@shawntanzk I have lost overview of the uberon broken import situation - what do you need me to do?

**Comment by shawntanzk** [comment]
@matentzn currently we cannot implement ('part of' some cell) in uberon as CL:0 axiom is not legal OBO or nesting is not OBO compatible (not 100% sure, taking wordings from https://github.com/obophenotype/uberon/pull/2037) and would need a decision from @dosumis 
For the moment, I can fix uberon_import by changing it to ('part of' some cell) given that uberon_import is owl, but of course this is a short term fix.

**Comment by dosumis** [comment]
> For the moment, I can fix uberon_import by changing it to ('part of' some cell) given that uberon_import is owl, but of course this is a short term fix.

Is this just down to reciprocal imports between CL and Uberon => outdated uberon import of CL comes with 'cell part'?  or is there a more general issue with the 'cell part' -> "'part of' some cell" solution?

**Comment by matentzn** [comment]
-> This is a temporary hack as long as Uberon is not re-released - the moment we have a new Uberon release @shawntanzk changes will be overwritten here..

**Comment by matentzn** [comment]
(its all about fixing the use of obsolete classes in axioms - so in this case just the "getting rid of cell part" issue.

**Comment by dosumis** [comment]
> (its all about fixing the use of obsolete classes in axioms - so in this case just the "getting rid of cell part" issue.

That bit I understand.  But 'cell part' -> "'(part of' some cell)" will be long term fix in edit files.  Correct?

**Comment by shawntanzk** [comment]
> That bit I understand. But 'cell part' -> "'(part of' some cell)" will be long term fix in edit files. Correct?

I think that comes down to this ticket https://github.com/obophenotype/uberon/issues/2046 - how we fix it in uberon itself
