### ISSUE TITLE
Typo in definition of CL_0000119

### ISSUE THREAD

**Issue by Alain-Gateau** [obophenotype/cell-ontology#1254]
...The axon of the Golgi cell **enters** ramifies densely in the granule layer and enters into a complex arrangement with mossy fiber terminals and...
The first occurence of 'enters' is grammatically wrong, please remove

**Comment by paolaroncaglia** [comment]
Hi @Alain-Gateau ,
Thank you for pointing that out, we'll fix it.
Best wishes,
Paola

**Comment by paolaroncaglia** [comment]
Hi @Alain-Gateau ,
The typo above has been fixed. The change will be visible in the next CL release, planned for today.
Thanks,
Paola
