### ISSUE TITLE
[NTR] pulmonary lipofibroblast

### ISSUE THREAD

**Issue by zimmwe** [obophenotype/cell-ontology#1280]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
pulmonary lipofibroblast

**Synonyms**
lipid interstitial cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Lipid droplet containing fibroblast of the alveolar interstitium.

PMID: 33624948
PMID: 9074756
PMID: 22268140

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
fibroblast  CL:0000057

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lung  UBERON:0002048

**Your nano-attribution (ORCID)**
0000-0002-1425-877X

**Any additional notes or concerns**

**Comment by zimmwe** [comment]
Thank you Paola

Best,

Wendy

**Comment by JoshuaFortriede** [comment]
This new term has been added as "alveolar type 1 fibroblast cell" and has an ID of CL:4028004. The requested term name has been added as a synonym, along with the synonym "lipid interstitial cell". PMIDs have been added as well.

**Comment by zimmwe** [comment]
Thank you!
