### ISSUE TITLE
[NTR] Ureteric bud cell

### ISSUE THREAD

**Issue by zimmwe** [obophenotype/cell-ontology#1281]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Ureteric bud cell

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Epithelial cells of the uretic bud.

PMID: 9374839
PMID: 24183650
PMID: 17133361

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
kidney epithelial cell  CL:0002518

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
ureteric bud  UBERON:0000084

**Your nano-attribution (ORCID)**
0000-0002-1425-877X

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Dear @zimmwe ,

Thank you for your request.

Similarly to your other ticket, may I please ask what project or group is this for? So we can assign the task appropriately.

Also, could you please confirm if the proposed definition 
"Epithelial cells of the uretic bud."
should read
"Epithelial cells of the _ureteric_ bud."
instead?

Thanks.

**Comment by bvarner-ebi** [comment]
@emquardokus, checking in on this ticket.
Is this a cell type you still plan to add? If so, I suggest to remove the "stale" label. The original request is from 2021.

**Comment by emquardokus** [comment]
@bvarner-ebi removed "stale" label; Paola had been working on this; I think we figured it had KPMP potential as an expert group. Created and added NIBR. This is not part of a HuBMAP ASCT+B table as it's kidney development.

**Comment by bvarner-ebi** [comment]
@zimmwe, @emquardokus,
Apologies for the extended delay on this ticket. 
After reviewing the references above, below are the proposed edits.
It would be appreciated if a subject matter expert will confirm that what is noted in the definitions are broadly applicable and not overly specific to particular taxa.

--

**Preferred term label:**
ureteric bud cell

**Synonym**
UB cell (related, abbreviation, PMID:24183650)

**Text Definition**
An epithelial cell that is part of a ureteric bud. A ureteric bud cell has the potential to induce metanephric mesenchymal cells to proliferate and convert to epithelia that form renal tubules via: (1) the secretion of multiple diffusible growth factors that rescue renal progenitors from apoptosis and (2) contact-dependent mechanisms that induce mesenchymal-epithelial conversion.
PMID:9374839 ; PMID:24183650 ; PMID:17133361


**Logical definition:**
‘epithelial cell’ and ‘part of’ some ‘ureteric bud’

Your nano-attribution (ORCID)
0000-0002-1425-877X

**Comment by bvarner-ebi** [comment]
@zimmwe, thank you for the new term request. The following term has been added to CL and will be available in the next release.

CL:4030066 'ureteric bud cell'

Additional details can be reviewed in [the linked PR](https://github.com/obophenotype/cell-ontology/pull/2185).
