### ISSUE TITLE
[NTR] Hepatic portal fibroblast

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#1282]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
hepatic portal fibroblast

**Synonyms**
portal fibroblast

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Portal fibroblast are a non-parenchymal cell population located adjacent to bile duct epithelia  in liver and are distinct from stellate cells. They differentiate into fibrogenic myofibroblasts during chronic injury states producing high levels of collagen.
PMID: 24814904
PMID: 20209607

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
fibroblast

hepatic portal fibroblast subclass of fibroblast of liver

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
ADD fibroblast of liver

**Your nano-attribution (ORCID)**
0000-0001-7655-4833

**Any additional notes or concerns**
Term request part of HuBMAP ASCT+B liver table from Anna Maria Masci

**Comment by emquardokus** [comment]
@paolaroncaglia yes please can you add this term as suggested? Thank-you

**Comment by paolaroncaglia** [comment]
@emquardokus the new term is CL_0009100 (hepatic portal fibroblast).
