### ISSUE TITLE
Improve documentation for ODK imports 

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1287]
As per @matentzn's suggestion at: 
- #1232

**Comment by lubianat** [comment]
It is not clear to me which systems dependency are required at: https://obophenotype.github.io/cell-ontology/odk-workflows/UpdateImports#refresh-imports

Perhaps that could use some additional documentation

**Comment by matentzn** [comment]
What do you mean by systems dependency again? :) thanks @lubianat

**Comment by lubianat** [comment]
@matentzn  I guess just "Make sure docker is installed" would suffice :)

**Comment by matentzn** [comment]
This will be fixed as part of https://github.com/INCATools/ontology-development-kit/pull/496

Closing it here as it should be in the ODK repo. Thank you @lubianat
