### ISSUE TITLE
(flowCL project) Synonyms of IgA, IgD, IgE, IgG and IgM in immunoglobulin complexes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#131]
```
Synonym of "IgA" missing in "IgA immunoglobulin complex"
Synonym of "IgD" missing in "IgD immunoglobulin complex"
Synonym of "IgE" missing in "IgE immunoglobulin complex"
Synonym of "IgG" missing in "IgG immunoglobulin complex"
Synonym of "IgM" missing in "IgM immunoglobulin complex"

```

Original issue reported on code.google.com by `justinme...@gmail.com` on 30 May 2014 at 6:43

**Comment by addiehl** [comment]
This is an issue for GO and PRO, really.  Search using IgA, etc. is not affected by these missing synonyms, because they are a component of the longer term label. Only exact matches would be affected.
