### ISSUE TITLE
[Typo/Bug] Typo in labels of 'Fraction' cell types

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1314]
Hi @addiehl ,

**CL term**
http://purl.obolibrary.org/obo/CL_0002045 | Fraction A pre-pro B cell
http://purl.obolibrary.org/obo/CL_0002047 | Fraction B precursor B cell
http://purl.obolibrary.org/obo/CL_0002400 | Fraction B/C precursor B cell
http://purl.obolibrary.org/obo/CL_0002049 | Fraction C precursor B cell
http://purl.obolibrary.org/obo/CL_0002050 | Fraction C' precursor B cell
http://purl.obolibrary.org/obo/CL_0002052 | Fraction D precursor B cell
http://purl.obolibrary.org/obo/CL_0002054 | Fraction E immature B cell
http://purl.obolibrary.org/obo/CL_0002056 | Fraction F mature B cell

**Description of typo, bug or error**
As per standard naming guidelines, the labels should read 'fraction...' instead of 'Fraction'.
Minor point: some synonyms of the terms above also have incorrect capitalisation.
Also, some of the terms above have a comment indicating that those markers are commonly associated with mouse cells. 
Are the terms broadly applicable, or should the mouse specificity be indicated in labels and/or taxon annotations? 

Thanks,
Paola

**Comment by addiehl** [comment]
I believe the names were capitalized because they were based on classic fractionation methods for B cells in mice that were capitalized in the original papers, but I need to go back to check.  Probably they should be taxon restricted as well.  I will get back to you.

**Comment by paolaroncaglia** [comment]
I fixed the capitalisation, and made some exact synonyms broad instead. The taxon specificity is in rdfs:comments already, so I'll go ahead and close.
