### ISSUE TITLE
Typo in label of CL:0002181 mucus neck cell of gastric gland

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1324]
**CL term**
CL:0002181 mucus neck cell of gastric gland

**Description of typo, bug or error**
The label should read 'mucous' not 'mucus' (the former is the adjective for the latter). This suggestion is also supported by the parent's label 'mucous neck cell', and by usage in literature. 'mucus neck cell of gastric gland' could stay as a synonym, even an exact one. Thanks.

**Comment by nicolevasilevsky** [comment]
I'll fix this
