### ISSUE TITLE
Revise synonym of CL:0000192 smooth muscle cell

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1326]
**CL term**
CL:0000192 smooth muscle cell 

**Description of typo, bug or error**
Defined as "A non-striated, elongated, spindle-shaped cell found lining the digestive tract, uterus, and blood vessels..."
and subclass of 'non-striated muscle cell'
but has _narrow_ synonym "non-striated muscle cell" => should be broad please. Thanks.

**Comment by nicolevasilevsky** [comment]
I'll fix this.
