### ISSUE TITLE
Revise label of CL:0000630 supportive cell?

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1329]
**CL term**
CL:0000630 supportive cell

**Description of typo, bug or error**
"A cell whose primary function is to support other cell types."
As a non-native English speaker, this is one of my favourite CL terms. But shouldn't the primary label be 'supporting cell', with 'supportive cell' as a synonym? The current label seems very little used in literature. Even the BTO term that it xrefs to is named 'supporting cell', and all subtypes in CL are labelled 'supporting' or 'support', e.g. 'supporting cell of carotid body'.
Note that if we rename the grouping class, we should also revise definitions containing "supportive cell". Thanks.

**Comment by nicolevasilevsky** [comment]
this sounds good to me, I'll create a PR
