### ISSUE TITLE
[Typo/Bug] error in annotation of CL:1000398 'endothelial cell of hepatic sinusoid'

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1353]
**CL term**
CL:1000398 'endothelial cell of hepatic sinusoid'

**Description of typo, bug or error**
has exact synonym LSEC, with AP _has exact synonym_ PMID:x
Replace with dbxref.
(I'm happy to do the edit, but I'll leave it as is for now in case it can be used for automated checks, see below.)

@matentzn @dosumis 
Are there checks in place to flag when a PMID is associated with anything other than dbxref, please? The reverse isn't true, but presumably annotations starting with PMID: should only ever be dbxrefs? Thanks.

**Comment by matentzn** [comment]
In such cases, always tag @shawntanzk and @anitacaron rather than me because they do the triaging of the tech call issues! :)  Thanks for the issue!

**Comment by shawntanzk** [comment]
Created a ticket for this :) thanks
