### ISSUE TITLE
[Merge] CL:0000717 'fusimotor neuron' into CL:0008037 'gamma motor neuron'

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1364]
@dosumis (cc @shawntanzk )

**CL term (ID and Label)**
CL:0000717 'fusimotor neuron'

**Reason for deprecation**
Currently, CL:0000717 'fusimotor neuron' and CL:0008037 'gamma motor neuron' are siblings.
The former is defined as "A subset of motor neurons that innervates intrafusal muscle fibers and has small diameter axons.".
The latter as "A lower motor neuron that innervates only intrafusal muscle fibers. (...)".
[Wikipedia says](https://en.wikipedia.org/wiki/Gamma_motor_neuron) "A gamma motor neuron (γ motor neuron), also called gamma motoneuron, or fusimotor neuron...".
They really sound the same, so please consider merging CL:0000717 'fusimotor neuron' into CL:0008037 'gamma motor neuron' (the latter has children and is better axiomatised).

**Term to be merged with (ID and Label)**
CL:0008037 'gamma motor neuron'

Thanks!
Paola

**Comment by shawntanzk** [comment]
I'll handle this :) thanks for spotting this @paola-scibite and sorry for adding gamma motor neuron without checking properly first >.<
