### ISSUE TITLE
Typo in def of CL:0000359 vascular associated smooth muscle cell

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1368]
**CL term**
CL:0000359 vascular associated smooth muscle cell

**Description of typo, bug or error**
"A smooth muscle cell _assocatiated_ with the vasculature."
=> please correct to associated.

**Comment by bvarner-ebi** [comment]
@paolaroncaglia , @dosumis, after opening cl-edit.owl and running the reasoner (before making any changes), I see the following disjoint appear on all the classes:

![Screenshot 2021-12-16 at 05 13 38](https://user-images.githubusercontent.com/95643797/146352817-029ae897-ef8b-4437-b5a5-a1df9447f977.png)

owl:Nothing is also red in the class hierarchy.

Is this expected?

**Comment by dosumis** [comment]
@shawntanzk  - is this the inconsistency coming in from GO which is only visible with ELK 0.5 ?  Should we be recommending that everyone switch back to [elk 0.43](https://github.com/liveontologies/elk-reasoner/releases) until this is fixed?

**Comment by shawntanzk** [comment]
Yeah it is
Leaving this link so that this ticket gets linked there to it https://github.com/geneontology/go-ontology/issues/16524

**Comment by paolaroncaglia** [comment]
As per discussion on cl-editors Slack: 
Please could all editors make sure they have ELK 0.4.3 installed for Protege (https://github.com/liveontologies/elk-reasoner/releases), and use this for editing CL until further notice. Thanks!

**Comment by dosumis** [comment]
Sorry all - I got a slap on the wrist from @matentzn  for suggesting this.  He prefers fixes upstream that stop this and related issues from bleeding through.

**Comment by bvarner-ebi** [comment]
@dosumis, would it be prudent to pause future pull requests until this is resolved?

**Comment by matentzn** [comment]
Its resolved #1377 

dont stop yourself @bvarner-ebi

**Comment by shawntanzk** [comment]
#1377 has been merged to master - once you update it, it should not show any unsats anymore :)
