### ISSUE TITLE
Reinstating range constraints on 'has characteristic' and 'regulates'

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1376]
Currently to fix import issues that create unsat classes, we need to remove range constraints on 'has characteristic' and 'regulates'
This ticket is a reminder to remove this hack when the issues in GO are resolved

related to https://github.com/geneontology/go-ontology/issues/16524

@rays22 (or @dosumis) not sure if the above is the only ticket for this? or if there are tickets in GO to fix “has participant” and “has characteristic” range issues? - if so could you link them here please?

**Comment by rays22** [comment]
> @rays22 (or @dosumis) not sure if the above is the only ticket for this? or if there are tickets in GO to fix “has participant” and “has characteristic” range issues? - if so could you link them here please?

I did a quick search, but I could not find any other related issue in GO.

**Comment by shawntanzk** [comment]
for the GO terms - next release should fix it (see https://github.com/geneontology/go-ontology/issues/22587)

**Comment by shawntanzk** [comment]
checked with refreshed GO, issue still there

**Comment by shawntanzk** [comment]
Ok, issue is still there, not sure why it didnt get picked up when i tried last, but basically still a problem
