### ISSUE TITLE
Reinstate normal CLO mirror

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#1379]
CLO does not have a base, so we have to drop some classes from the mirror in CL. This will probably never fix, so I wont put it on the board. If someone is eager go make a https://github.com/CLO-ontology/CLO issue, but there are multiple problems, not just the use of an obsolete class.

```
mirror/clo.owl: mirror/clo.trigger
	echo "WARNING OVERWRITING CLO MIRROR BECAUSE OF EQUIVALENT TERM"
	if [ $(MIR) = true ] && [ $(IMP) = true ]; then curl -L $(URIBASE)/clo.owl --create-dirs -o mirror/clo.owl --retry 4 --max-time 200 && $(ROBOT) convert -i mirror/clo.owl -o $@.tmp.owl && \
		$(ROBOT) remove -i $@.tmp.owl --base-iri $(URIBASE)/CLO --axioms external --preserve-structure false --trim false \
			remove --term "CLO:0000021" --axioms logical --preserve-structure false \
			remove --term "CL:0000243" --preserve-structure false \
			remove --term "CLO:0000031" --term "CLO:0000001" --term "rdfs:comment" --term "IAO:0000115" --signature true --trim false -o $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: mirror/clo.owl
```

**Comment by matentzn** [comment]
We do not need CLO import:

CLO terms are only used in replaced_by as replacements for three terms:
<obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/CLO_0000019"/>
<obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/CLO_0000001"/>
<obo:IAO_0100001 rdf:resource="http://purl.obolibrary.org/obo/CLO_0000018"/>

**Comment by matentzn** [comment]
- [ ] @shawntanzk will drop the dependency as part of the ODK 1.3.0 migration

**Comment by shawntanzk** [comment]
removed CLO import
