### ISSUE TITLE
glomerular visceral epithelial cell should be part of glomerular visceral epithelium

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1399]
it is currently 

subClassOf part of some visceral layer of glomerular capsule

This should be changed to 

EquivalentTo 'epithelial cell'  and 'part of' some 'glomerular visceral epithelium'

Closely related ticket: https://github.com/obophenotype/uberon/issues/2230

**Comment by bvarner-ebi** [comment]
@dosumis, I'd like to help with this, but I could not find 'glomerular visceral epithelium' in cell-ontology.

I also tried to find the uberon-edit.owl file that is mentioned in the [Uberon readme for editors](https://github.com/obophenotype/uberon/blob/master/src/ontology/README-editors.md), but I get a 404 error after clicking the 'uberon-edit.owl' hyperlink in the readme. The closest I found in the repository is [uberon-edit.obo.](https://github.com/obophenotype/uberon/blob/master/src/ontology/uberon-edit.obo)

Could you provide additional instruction?
