### ISSUE TITLE
renal beta-intercalated cell should be part of collecting duct of renal tubule

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1400]
Poss supporting refs (from ASCT+B table version 1.1)
PMID: 31249312. PMCID: PMC6597610	DOI: 10.1038/s41467-019-10861-2		PMID: 31689386	DOI: 10.1016/j.devcel.2019.10.005

**Comment by bvarner-ebi** [comment]
@dosumis, would you want to also include 'part of' connecting tubule? I think type B = beta.

PMID: 29285423:
"Type B and non-A, non-B intercalated cells are found within the **connecting tubule** and the cortical collecting duct."

Not sure if the following text  only refers to beta-intercalated, but to consider:
PMID: 25632105:
"[Intercalated] cells appear in the **late distal convoluted tubule or in the connecting segment**, depending on the species. They are most abundant in the collecting duct... "

Also found typos in the definition for CL:0002201 renal beta-intercalated cell:
"A renal intercalated cell that secretes base and reabsorbs acid in the **coritcal** collecting duct to **mantain** acid/base balance."
--> cortical, maintain; respectively
