### ISSUE TITLE
Documentation on importing classes to CL

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1404]
Hi @shawntanzk, as discussed offline, kindly review, edit where necessary, and add the following to central docs...

# How to add (import) a class to the Cell Ontology (CL) from another ontology

## 1. Follow steps 1 - 5 under the heading [Protege-based declaration.](https://obophenotype.github.io/cell-ontology/odk-workflows/UpdateImports/#protege-based-declaration)

_NB: Even though the instructions state that this workflow is to be avoided, the other solutions in the current documentation are out of date._

_Example_
**Request:**
Update the equivalence axiom for a term in CL to:

`'epithelial cell' and ('part of' some 'glomerular visceral epithelium’)`

**Problem:**
glomerular visceral epithelium (UBERON:0006852) does not yet exist in CL. It needs to be imported from the UBERON ontology to the CL ontology.
**Solution:**
The editor would create a new class in CL for UBERON:0006852 by following steps 1 - 5 from the link above and proceed with one of the options below.

## 2. The editor then has several options (a or b or c):

**(a)** Construct logical axioms using the newly declared ID, create a 
    pull request, merge the changes and check back after the imports have 
    been refreshed (@shawntanzk: do refreshes happen on a regular basis or just ad hoc?).
    If viewing the ontology in Protégé, in addition to seeing the newly 
    imported class with all associated metadata, the label should replace 
    the ID in axioms if the view is set to “Render by label (rdfs:label)”.

_Example_
Write the equivalence axiom as:

`'epithelial cell' and ('part of' some UBERON:0006852)`

Proceed with a pull request and merge.
Once the imports have been refreshed, the equivalence axiom should appear as:

`'epithelial cell' and ('part of' some 'glomerular visceral epithelium’)`

___
**(b)** Ask a developer _(@shawntanzk: how to identify devs? Is there a directory?)_ to refresh the imports. Once refreshed, return to Protégé, add the logical axioms and create a pull request per standard procedure.

_Example_
After the developer confirms the refresh has been completed, return to Protégé and write the equivalence axiom as:

`‘epithelial cell' and ('part of' some 'glomerular visceral epithelium’)`

___
**(c)** Refresh the imports, return to Protégé, add the logical axioms and create a pull request per standard procedure. Note that refreshing the imports requires Docker and sufficient computational power (> 8GB RAM). To refresh the imports, open Docker so it is running in the background. Then open Terminal, navigate to src/ontology directory in the cell-ontology repository and run:

`sh run.sh make imports/merged_import.owl`

Contact a developer if there is an issue with the refresh. Once refreshed, return to Protégé, add the logical axioms and create a pull request per standard procedure. _Note that the import refresh process seems to be quite laborious/computationally expensive as-is, and a centralised database approach may be an improved longterm solution._

**Comment by shawntanzk** [comment]
yes! found it! it's here https://github.com/INCATools/ontology-development-kit/edit/master/template/_dynamic_files.jinja2 - let me go through the above, edit it, and see if you can give a go on editing that file -> that should distribute it to all ontologies

**Comment by shawntanzk** [comment]
actually I'm looking at it now, and it might take a bit of reworking to get it in the main docs. For now, if you want, you can add it to CL internal docs: https://github.com/obophenotype/cell-ontology/tree/master/docs

**Comment by shawntanzk** [comment]
Comments on docs: 

>  Example
> Request:
> Update the equivalence axiom for a term in CL to:
> 
> 'epithelial cell' and ('part of' some 'glomerular visceral epithelium’)
> 
> Problem:
> glomerular visceral epithelium (UBERON:0006852) does not yet exist in CL. It needs to be imported from the UBERON ontology to the CL ontology.
> Solution:
> The editor would create a new class in CL for UBERON:0006852 by following steps 1 - 5 from the link above and proceed with one of the options below.
> 

The above section is not really needed imo 

>  Construct logical axioms using the newly declared ID, create a
> pull request, merge the changes and check back after the imports have
> been refreshed

This is dangerous as unsatisfiable axioms might happen and break if merge is done before imports - I would remove this as an option in docs

I think it should be just try to run imports, if you run into error (write something about requiring quite a bit of memory on your local machine), create a ticket that requests for a certain term to be imported and someone will pick it up and do it for you. That would probably be the best :)
