### ISSUE TITLE
[NTR] Endothelial colony forming cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1410]
**Preferred term label:** Endothelial colony forming cell

**Synonyms**: -

**Definition**: Endothelial colony forming cells are adult endothelial progenitor cells capable of differentiating to regenerate endothelial cell populations. They are residents of adult vasculature and are also thought to migrate to areas of injury as one form of circulating endothelial cell. They are thought to play a critical role in vascular healing after injury as well as developmental angiogenesis. [PMID: 33419165]

**Parent cell type term:** adult endothelial progenitor cell (CL:0002619)

**What is the anatomical structure that the cell is a part of?**: vasculature (UBERON:0002049)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**:  Wikipedia page could be cited: https://en.wikipedia.org/wiki/Endothelial_colony_forming_cell

**Comment by paolaroncaglia** [comment]
Notes to self:
The suggested parent 'adult endothelial progenitor cell' (CL:0002619) was created in 2011 and has def "An adult angioblastic cell released from the bone marrow, capable of blood circulation and participation in angiogenesis by differentiating into blood vessel endothelial cells. _Their existence is controversial._". Also, the requested new term would be the only child of CL:0002619, always a bad smell as Chris M. would say. Based on the Wikipedia entries for parent and child, we could probably add 2 more children, _focusing on what's known about their characteristics in vivo_  to clarify differentia from parent, and revise def and add Wikipedia ref for parent. I won't go deeper into the literature at this point.

**Comment by paolaroncaglia** [comment]
@paulacalipho your new term is CL_0009090 (endothelial colony forming cell).
Best,
Paola

**Comment by paulacalipho** [comment]
@paolaroncaglia Many thanks
