### ISSUE TITLE
[NTR] Fibroblast-like synoviocyte

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1411]
**Preferred term label:** Fibroblast-like synoviocyte

**Synonyms**: Synovial fibroblasts

**Definition**: Fibroblast-like synoviocytes are the resident stromal cells of the joints responsible for the production of immune-related cytokines and chemokines. These cells play a key role in the pathogenesis of rheumatoid arthritis and are essential for the maintenance of normal joint functions. Fibroblast-like synoviocytes from different joints have different properties, which may contribute to the characteristic pattern of joint involvement in different types of arthritis [PMID: 34433485; PMID: 34772990]

**Parent cell type term:** 
synovial cell (CL:0000214)
stromal cell (CL:0000499)

**What is the anatomical structure that the cell is a part of?**: synovial joint (UBERON:0002217)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**: thanks

**Comment by bvarner-ebi** [comment]
Hi, @paulacalipho, upon investigation we found that 'fibroblast-like synoviocyte' is a synonym for CL:0002301 'type B synovial cell'. We updated that term and some related terms accordingly as detailed in PR #1427.

**Comment by paulacalipho** [comment]
@bvarner-ebi OK, many thanks
