### ISSUE TITLE
[NTR] Kisspeptin neuron

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1412]
**Preferred term label:** Kisspeptin neuron

**Synonyms**: -

**Definition**: Kisspeptin is a neuropeptide with a critical role in the function of the hypothalamic–pituitary–gonadal axis. Kisspeptin is produced by two major populations of neurons located in the hypothalamus, the rostral periventricular region of the third ventricle (RP3V) and the arcuate nucleus (ARC). These neurons project to and activate gonadotrophin-releasing hormone neurons (acting via the kisspeptin receptor) in the hypothalamus and stimulate the secretion of gonadotrophin-releasing hormone. Gonadal sex steroids stimulate kisspeptin neurons in the RP3V, but inhibit kisspeptin neurons in the ARC. [PMID: 30042117]

**Parent cell type term:** neuron of the forebrain (CL:0012001)

**What is the anatomical structure that the cell is a part of?**: arcuate nucleus of hypothalamus (UBERON:0001932)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**: this cell type is also part_of "rostral periventricular region of the third ventricle". I did not find this term in UBERON

**Comment by shawntanzk** [comment]
Notes: 

Kisspeptin is most notably expressed in the hypothalamus, but is also found in other areas of the brain including the hippocampal dentate gyrus. (https://en.wikipedia.org/wiki/Kisspeptin) -> therefore Kisspeptin neuron should not be constrained to hypothalamus if the definition for it is a neuron that expresses Kisspeptin

**Comment by paulacalipho** [comment]
Thanks Shawn for your suggestions. We should modify the definition for “Kisspeptin neuron” as follows?

Definition: Kisspeptin is a neuropeptide mostly expressed in the hypothalamus, but also found in other areas of the brain including the hippocampal dentate gyrus. In particular, it has a critical role in the function of the hypothalamic–pituitary–gonadal axis. In the hypothalamus, kisspeptin is produced by two major populations of neurons located in the rostral periventricular region of the third ventricle (RP3V) and the arcuate nucleus (ARC). These neurons project to and activate gonadotrophin-releasing hormone neurons (acting via the kisspeptin receptor) in the hypothalamus and stimulate the secretion of gonadotrophin-releasing hormone. Gonadal sex steroids stimulate kisspeptin neurons in the RP3V, but inhibit kisspeptin neurons in the ARC. [PMID: 30042117]

**Comment by shawntanzk** [comment]
Hi @paulacalipho I've made a pull request with the textual definition I wrote based on what you provided (there are some conventions in ontological definitions that we should follow). You can view it here https://github.com/obophenotype/cell-ontology/pull/1424/files - any feedback would be amazing. I've also made a hierarchical structure based on what I read and would like feedback on that too. For ease, I've attached a screenshot of it here: 
![Screenshot 2022-01-21 at 07 28 07](https://user-images.githubusercontent.com/76212760/150484679-0aeba307-83dd-4aed-b55d-bf563f6aa43c.png)

**Comment by paulacalipho** [comment]
@shawntanzk: many thanks!!
