### ISSUE TITLE
[NTR] KNDy neuron

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1413]
**Preferred term label:** KNDy neuron

**Synonyms**: -

**Definition**: KNDy neurons in the hypothalamus coexpress kisspeptin, neurokinin B and dynorphin. They are involved in the negative feedback of gonadotropin-releasing hormone release in the hypothalamic–pituitary–gonadal axis. Sex steroids released from the gonads act on KNDy neurons as inhibitors of kisspeptin release. This inhibition provides negative feedback control on the hypothalamic–pituitary–gonadal axis. Other roles of KNDy neurons include influences on prolactin production; puberty; stress' effects on reproduction; and the control of thermoregulation.

**Parent cell type term**: neuron of the forebrain (CL:0012001)

**What is the anatomical structure that the cell is a part of?**: arcuate nucleus of hypothalamus (UBERON:0001932)

**Your nano-attribution (ORCID)**: 0000-0002-0819-0473

**Any additional notes or concerns**
1) is it possible to cite Wikipedia as reference in the definition? [https://en.wikipedia.org/wiki/KNDy_neuron]
2) this cell type is also part_of "rostral periventricular region of the third ventricle". I did not find this term in UBERON

**Comment by shawntanzk** [comment]
Notes to self:

expresses some PR:000009344 (kisspeptin)

Neurokinin b (NKB), is encoded by the TAC3 gene in humans and Tac2 in rodent species. -> PR:000016004

Dynorphin -> NCBIgene:5173 -> PDNY -> PR:000012526

> is it possible to cite Wikipedia as reference in the definition? [https://en.wikipedia.org/wiki/KNDy_neuron]

yes - will cite it accordingly :) 

> this cell type is also part_of "rostral periventricular region of the third ventricle". I did not find this term in UBERON

"rostral periventricular region of the third ventricle" - In rats and mice, the anteroventral periventricular nucleus (UBERON:0002690) plus the periventricular nucleus (UBERON:0002322) make up the rostral periventricular region of the third ventricle (RP3V). [https://en.wikipedia.org/wiki/Anteroventral_periventricular_nucleus] - I think we can do 'has soma location' some (UBERON:0002690 and UBERON:0002322) if need be. 

@paulacalipho is there a need to go into more details in logical axiom for the RP3V and arcuate nucleus of hypothalamus? - we can so a general hypothalamus class, then subclasses of for the 2 structures if so, but if there isn't a need, happy to just put it in the text definition.

**Comment by shawntanzk** [comment]
> @paulacalipho is there a need to go into more details in logical axiom for the RP3V and arcuate nucleus of hypothalamus? - we can so a general hypothalamus class, then subclasses of for the 2 structures if so, but if there isn't a need, happy to just put it in the text definition.

Ok just saw the other request and saw the PMID and understand why there is a need for this.

**Comment by shawntanzk** [comment]
>  I think we can do 'has soma location' some (UBERON:0002690 and UBERON:0002322) if need be.

just realised that this means the soma has to be in both >.< might need a new term for this in uberon
