### ISSUE TITLE
[Synonym] add synonyms to "light melanocyte"

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1417]
**CL term**: light melanocyte CL:0002567

**Synonym to be added**:
"amelanotic melanocyte"
"amelanotic melanophore" 

**broad/exact/narrow/related ?** exact [PMID: 10985850]

**Comment by bvarner-ebi** [comment]
Thank you for the request, @paulacalipho. The synonyms were added (PR #1426).
