### ISSUE TITLE
[Synonym] add synonym to "epithelial fate stem cell"

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1419]
**CL term**: epithelial fate stem cell (CL:0000036)

**Synonym to be added**: 
"epithelial stem cell"

**broad/exact/narrow/related ?** exact

**Comment by bvarner-ebi** [comment]
Hi, @paulacalipho. This synonym was added in PR #1437.

**Comment by paulacalipho** [comment]
Many thanks
