### ISSUE TITLE
[Synonym] add synonyms to "mammary alveolar cell"

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1420]
**CL term**: mammary alveolar cell (CL:0002325)

**Synonym to be added**:
"mammary alveolar epithelial cell"
"mammary gland alveolar epithelial cell"

**broad/exact/narrow/related ?** exact

**Comment by bvarner-ebi** [comment]
Hi, @paulacalipho. These synonyms were added in PR #1436.

**Comment by paulacalipho** [comment]
Many thanks
