### ISSUE TITLE
Can't seem to get PR import to work

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1421]
I'm trying to import these PR terms:
PR:000009344
PR:000016004
PR:000012526
But I've tried adding them to pr_terms.txt -> refreshing imports/pr_import.owl -> refreshing merged, tried declaring them in -edit then refreshing merged, tried with mirror on, but it does seem to get imported in. 
Tried the same thing on UBERON and it seems to work properly. (unless those terms were already in CL and I got lucky - trying now with a new term)
Will add to tech call.

**Comment by matentzn** [comment]
Are you sure merged refreshed? That's all that matters.. we don't care about pr_import anymore. 

Note: remember we have a PRO slim now. You need to be sure the new PRO terms are in there.

**Comment by shawntanzk** [comment]
> Are you sure merged refreshed? That's all that matters.. we don't care about pr_import anymore.
> 
> Note: remember we have a PRO slim now. You need to be sure the new PRO terms are in there.

yes, refreshed the merged and all. Ah will check PRO slim, might be that. I've only checked them on OLS atm

**Comment by shawntanzk** [comment]
@matentzn lol ok yeah, its not in the PRo slim >.< is there a way to get it in?

**Comment by matentzn** [comment]
Sure! Clone the PRO slim, add the PRO terms to the seed.txt and run the Makefile.. Make a PR and its done. Should be less then 10 minutes if you do it for the first time!

**Comment by shawntanzk** [comment]
@matentzn stupid question, but how do i run the makefile lol

**Comment by matentzn** [comment]
Actually use this opportunity to add a README.md and some instructions how to add new terms to the slim..

**Comment by shawntanzk** [comment]
> Try reading it! convention is: `sh odk.sh make all`..

oh right, lol i was trying to do `run.sh` >.< 

> Actually use this opportunity to add a README.md and some instructions how to add new terms to the slim..

Will do

**Comment by matentzn** [comment]
There is also this:
https://github.com/obophenotype/pro_obo_slim/blob/master/.github/workflows/build.yaml

Not sure if it works though.. You could try that as well (in Actions tab, run workflow)

**Comment by shawntanzk** [comment]
@matentzn - i dont have write request on PR slim unfortunately, could you give that me please? thanks :)

**Comment by matentzn** [comment]
Done https://github.com/orgs/obophenotype/teams/uberon-cl-curators/repositories
