### ISSUE TITLE
[NTR] TEMRA: terminally differentiated effector memory cells re-expressing CD45RA

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1435]
@addiehl please
Currently in CL "TEMRA" is a broad synonym for both
CL:0001062 effector memory CD8-positive, alpha-beta T cell, terminally differentiated
and
CL:0001087 effector memory CD4-positive, alpha-beta T cell, terminally differentiated
As far as I can see, there isn't a broader term in CL to represent TEMRA cells.
Based on usage in literature, would you consider adding one please? 
If the specs below are correct, I can add it myself.

**Preferred term label:**
effector memory CD45RA-positive, alpha-beta T cell, terminally differentiated

**Synonyms**
terminally differentiated effector memory cells re-expressing CD45RA (exact) (https://en.wikipedia.org/wiki/T_cell#Memory_T_cells)
terminally differentiated effector memory CD45RA+ T cells (exact) (PMID:25104859)
TEMRA cell (exact) (PMID:25104859)
effector memory RA T cell (broad? if not exact) (PMID:16237082)
TEMRA (broad or related, with has_synonym_type=abbreviation) (PMID:16237082)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
An alpha beta memory T cell with the phenotype CD45RA-positive.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0000791 mature alpha-beta T cell

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

**Any additional notes or concerns**
To become parent of 
CL:0001062 effector memory CD8-positive, alpha-beta T cell, terminally differentiated
and
CL:0001087 effector memory CD4-positive, alpha-beta T cell, terminally differentiated

Thank you.
Paola

**Comment by addiehl** [comment]
I don't mind if you add this term.  Is there a specific request for it?

We haven't provided general classes such as 'alpha-beta memory T cell, CD45RO-positive', 'central memory alpha-beta T cell', 'effector memory alpha-beta T cell', either, in case you want to fill out the full lattice of possibilities.

**Comment by paolaroncaglia** [comment]
@addiehl 

> I don't mind if you add this term. Is there a specific request for it?

It's found in text mining, and TEMRA is in CL as a synonym for 2 sibling classes, which suggests that a parent may be useful.

> We haven't provided general classes such as 'alpha-beta memory T cell, CD45RO-positive', 'central memory alpha-beta T cell', 'effector memory alpha-beta T cell', either, in case you want to fill out the full lattice of possibilities.

Thanks, I might request/add those on an ad-hoc basis.
Paola
