### ISSUE TITLE
Create synonym_type_property 'abbreviation' for CL

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1441]
UBERON has the Annotation property 'abbreviation' (Superproperty 'synonym_type_property'). http://purl.obolibrary.org/obo/uberon/core#ABBREVIATION

So editors can also leverage this property in CL, I request for Annotation property 'abbreviation' to be imported from UBERON into CL.

PR that inspired this request: PR #1440

**Comment by shawntanzk** [comment]
would be a bit weird to add a uberon specific AP to CL. I've previously used exact synonym in CL but do understand that there might be use cases for that - thoughts on this @dosumis?

**Comment by paolaroncaglia** [comment]
@shawntanzk (cc @bvarner-ebi )

> would be a bit weird to add a uberon specific AP to CL. I've previously used exact synonym in CL but do understand that there might be use cases for that - thoughts on this @dosumis?

While OBO members may not all agree on how strict we should be with the "exact" synonym scope, I do think that in CL there are plenty of use cases for the "abbreviation" annotation property. E.g. ESC, Treg, TAC... Abbreviations and acronyms are also discussed in the OBOOK [here](https://oboacademy.github.io/obook/reference/synonyms-obo/#synonym-types), so we wouldn't be going against consensus practice if we imported that AP. (Uberon has way more APs than CL and I think we've imported at least one before - location grouping - but I can't find mention of it.)

**Comment by shawntanzk** [comment]
100% agree that abbreivation AP would be useful in CL, but I guess my question then is should we be adding a specific AP to CL? should this live in a more general location given its usefulness? If so where? This seems to vary and was wondering what the best way to handle this would be. 

Some notes on this:
MONDO seems to have their own [AP for abbreviation](https://www.ebi.ac.uk/ols/ontologies/mondo/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fmondo%23ABBREVIATION)
Like things like hasexactsynonym has a GO iri (http://www.geneontology.org/formats/oboInOwl#hasExactSynonym)

**Comment by paolaroncaglia** [comment]
> This seems to vary

Yes, it seems that synonym policy/SOP aren't applied homogeneously throughout OBO. Understandably, reaching a consensus may not be a high priority. Would be great to have feedback from others. Perhaps @nicolevasilevsky , who wrote the Mondo synonyms guide, might comment please. :-)

**Comment by nicolevasilevsky** [comment]
Yes, we have our own AP in Mondo. HPO uses a similar AP too, that is their own as well: http://purl.obolibrary.org/obo/hp#abbreviation

**Comment by dosumis** [comment]
I'd favour adding abbreviation as a synonym type to CL ASAP.  Could re-use the Uberon one or add to CL following similar pattern.  However, I think this should move to OMO or IAO ASAP.   It will be a pain to query in integrated resources (e.g. Ubergraph) if every ontology has their own version. 

Note - there may be some OBO format compatibility issues

**Comment by bvarner-ebi** [comment]
> I'd favour adding abbreviation as a synonym type to CL ASAP. Could re-use the Uberon one or add to CL following similar pattern. However, I think this should move to OMO or IAO ASAP.

@dosumis, regarding order of operations, do you recommend opening a ticket in OMO to incorporate Uberon's abbreviation AP and then pulling that into CL?

**Comment by shawntanzk** [comment]
See https://github.com/information-artifact-ontology/ontology-metadata/issues/70
