### ISSUE TITLE
[NTR] tumor-associated endothelial cell

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#1471]
Hello Cell Ontology Team,

I had a discussion with Alex about the term-request 'tumor-associated endothelial cell' into Disease Ontology, please see here:
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1016

**Preferred term label: tumor-associated endothelial cell**

**Synonyms:  tumor endothelial cell  /    TEC**

WP definition:
https://en.wikipedia.org/wiki/Tumor-associated_endothelial_cell

**Definition (derived from PMID:32588325, PMID:29695087)**
draft definition:  Cells that line tumor blood vessels and are part of the tumor microenvironment (TME) that plays a central role in cancer development and progression. While the tumor blood vessels show clear morphological and functional abnormalities,  the cellular origin of vessel network in tumors is less known.

**Parent cell type term: CL:0001061 abnormal cell**

**Cell part_of UBERON:0001986 endothelium (or part_of the anatomical cluster UBERON:0002049 vasculature)**

**nano-attribution (ORCID): https://orcid.org/0000-0003-3308-6245**

Many thanks in advance for your help

Anne

Anne Niknejad

Senior biocurator
https://bgee.org/
SIB | Swiss Institute of Bioinformatics
Unil, Department of Ecology and Evolution - Quartier Sorge, bâtiment Biophore - 1015 Lausanne
t: +41 21 692 42 21 - f: +41 21 692 41 65
[Anne.Niknejad@sib.swiss](mailto:Anne.Niknejad@sib.swiss) - [https://www.sib.swiss](http://www.sib.swiss/)

**Comment by paolaroncaglia** [comment]
For quick reference, @addiehl 's favourable comment to having 'tumor-associated endothelial cell' in CL is [here](https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/1016#issuecomment-1047071038)

**Comment by bvarner-ebi** [comment]
Hello, @ANiknejad, thank you for the new term request and accompanying information.

I propose the following **definition**: 
An endothelial cell that lines a tumor blood vessel and is part of the tumor microenvironment that plays a central role in cancer development and progression.

and setting the following as a **comment**:
While tumor blood vessels show clear morphological and functional abnormalities, the cellular origin of a vessel network in tumors is less known.

Does the above seem reasonable to you?
Also, I am unable to access the full text for PMID:32588325. Could you confirm that paper supports the **comment** statement above?

**Comment by bvarner-ebi** [comment]
Hi, @ANiknejad, checking in to see if you had thoughts on the comment above.

**Comment by dosumis** [comment]
@dosumis - I'm uncomfortable about this because:
   
    1.  Potentially out of scope
    2. Classification - right now under abnormal cell.   But potentially wrong to classify pathological/disease associated cells under normal CL branches.
    3. Need to automated classification but patterns we should use are unclear.

From slack:
@matentzn  Basic approach should be as usual - new involved parties should not be rejected outright, but the “tumor-associated” has a very bad smell attached; basically anything that could copy the whole CL hierarchy with “X cell type” should be avoided. On the other side, you can show them how to use post composition to say “endothelial cell” and “associated with pathological entity” some “tumor”.  If there is just 20 such cell types, you can also precompose them

@cmungall:
agreed, massive ragged lattice red flags here. But it is worth looking at the NCIT abnormal cell hierarchy here

**Comment by bvarner-ebi** [comment]
@dosumis, @ANiknejad, given the comments above, would closing this ticket for now be appropriate?

**Comment by bvarner-ebi** [comment]
Closing this ticket due to comments above and no recent follow-up comments.
