### ISSUE TITLE
[NTR] Add new lymph node CL terms for ASCT+B

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1472]
Based on https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=457494842.
Tagging @emquardokus FYI.
Note to self, the related Uberon ticket is https://github.com/obophenotype/uberon/issues/2320.

**Comment by paolaroncaglia** [comment]
@emquardokus 
The [lymph node spreadsheet](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=457494842) requests, among other things, 
'Fibroblastic Reticular Cell' (FRC for brevity)
("Specialized cells of mesenchymal origin that express several markers common to myofibroblasts (desmin, vimentin, CD73, CD90, α-smooth muscle actin (αSMA) and can be differentiated from endothelial cells by their lack of CD31 expression. These cells are critical for the overall organization and function of the lymph node. Within the lymph node, fibroblastic reticular cells (FRCs) can be further classified based on their location, function, and unique marker expression.")
as a subclass of Myofibroblast (CL:0000186)
and part of Lymph Node (UBERON:0000029).
This alone raises the question "are FRCs only ever found in lymph nodes". A quick PubMed search confirms that FRCs are found elsewhere in lymphoid organs.
While investigating, I noticed that the existing CL term 'reticular cell' is defined as "Large, stellate fibroblast found along the network of collagen fibers of the reticulum of the spleen; synthesize the matrix components of the reticulum." (but it's not part_of spleen) and has this Wikipedia entry as def dbxref (https://en.wikipedia.org/wiki/Reticular_cell). It says:
"A reticular cell is a type of fibroblast that synthesizes collagen alpha-1(III) and uses it to produce reticular fibers. The cell surrounds the fibers with its cytoplasm, isolating them from other tissue components and cells.[1] Reticular cells provide structural support, since they produce and maintain the thin networks of fibers that are a framework for most lymphoid organs.
Reticular cells are found in many organs, including the spleen, lymph nodes and kidneys. They are also found within tissues, such as lymph nodules. There are different types of reticular cells, including epithelial, mesenchymal, and fibroblastic reticular cells. Fibroblastic reticular cells are involved in directing B cells and T cells to specific regions within the tissue whereas epithelial and mesenchymal reticular cells are associated with certain areas of the brain."
Based on these considerations, I plan to

- [ ] Broaden the applicability of 'reticular cell' by changing the definition to "A fibroblast that synthesizes collagen and uses it to produce reticular fibers, thus providing structural support. Reticular cells are found in many organs, including the spleen, lymph nodes and kidneys. Subtypes of reticular cells include epithelial, mesenchymal, and fibroblastic reticular cells. Fibroblastic reticular cells are involved in directing B cells and T cells to specific regions within a tissue, whereas epithelial and mesenchymal reticular cells are associated with certain areas of the brain."
- [ ] Create a tissue-agnostic term 'fibroblastic reticular cell' as a subclass of 'myofibroblast cell' (CL:0000186) and 'reticular cell'
- [ ] Create 'lymph node fibroblastic reticular cell' as a subclass of 'fibroblastic reticular cell', with broad synonym 'fibroblastic reticular cell' if desired (when literature mentions FRCs, is it mostly in lymph nodes?). 

Please let me know if you have any objection to this plan, otherwise I'll proceed soon. Thank you.

**Comment by emquardokus** [comment]
@paolaroncaglia I'm running this by the experts right now to make sure there is nothing we've missed.  Yes, I had looked into this as well and had pointed out "reticular cell" to the experts and investigated that as a possible term to use, but was not. I should hear back a bit later today. Thank-you!

**Comment by paolaroncaglia** [comment]
@emquardokus thank you, I'll wait to hear from you then.

**Comment by emquardokus** [comment]
@paolaroncaglia here's the reply below from Andrea Radtke our Lymph node expert in **bold.**

From: "Radtke, Andrea (NIH/NIAID) [E]" <andrea.radtke@nih.gov>
Subject: RE: Please review: [obophenotype/cell-ontology] [NTR] Add new lymph node CL terms for ASCT+B (Issue #1472)
Date: March 15, 2022 at 9:46:50 PM EDT
To: "Quardokus, Ellen M" <ellenmq@iu.edu>

Hi Ellen,
 
This is all great! I was “LN” focused when I wrote the entries, but these cells are critical to all tissues. Good grab.
  
Take care,
A
 
 
See my comments below.
[ ] Broaden the applicability of 'reticular cell' by changing the definition to "A fibroblast that synthesizes collagen and uses it to produce reticular fibers, thus providing structural support. Reticular cells are found in many organs, including the spleen, lymph nodes and kidneys. Subtypes of reticular cells include epithelial, mesenchymal, and fibroblastic reticular cells. Fibroblastic reticular cells are involved in directing B cells and T cells to specific regions within a tissue, whereas epithelial and mesenchymal reticular cells are associated with certain areas of the brain."
 **Great. Agree.**
[ ] Create a tissue-agnostic term 'fibroblastic reticular cell' as a subclass of 'myofibroblast cell' (CL:0000186) and 'reticular cell' 
**Great. Agree.**
[ ] Create 'lymph node fibroblastic reticular cell' as a subclass of 'fibroblastic reticular cell', with broad synonym. 
**Agree. The LN FRCs are so diverse and change with disease. Use this definition for 'lymph node fibroblastic reticular cell': Specialized cells of mesenchymal origin that express several markers common to myofibroblasts (desmin, vimentin, CD73, CD90, α-smooth muscle actin (αSMA) and can be differentiated from endothelial cells by their lack of CD31 expression. These cells are critical for the overall organization and function of the lymph node. Within the lymph node, fibroblastic reticular cells (FRCs) can be further classified based on their location, function, and unique marker expression**

**Comment by paolaroncaglia** [comment]
@emquardokus FYI I did the edits listed in https://github.com/obophenotype/cell-ontology/issues/1472#issuecomment-1067876254. 
The new terms are
CL_0009101 (fibroblastic reticular cell)
and 
CL_0009102 (lymph node fibroblastic reticular cell)
I'll add the ID of the latter in the [lymph node spreadsheet](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=457494842).

**Comment by paolaroncaglia** [comment]
Note to self: addition of B Cell Zone Reticular Cell depends on https://github.com/obophenotype/cell-ontology/issues/1513

**Comment by paolaroncaglia** [comment]
Note to self: the [latest PR](https://github.com/obophenotype/cell-ontology/pull/1519) is blocked bcs "GitHub Actions is experiencing degraded performance", so I'll check back tomorrow.

**Comment by paolaroncaglia** [comment]
@emquardokus 
I have a question about 'medullary reticular cell' please. 
For ease of reference, here's the info that was provided in the [lymph node spreadsheet](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=457494842):

Medullary Reticular Cell 
Stromal cell present in the lymph node medulla. 
[superclass] Fibroblast (CL:0000057) 
Homo sapiens 
[part of] Medulla (UBERON:0002007) 
DOI: 10.1016/j.ajpath.2010.12.039, DOI: 10.3389/fimmu.2011.00035, DOI: 10.1016/j.jcyt.2017.01.010, DOI: 10.1038/nri3846, DOI: 10.1016/j.it.2021.06.006, DOI: 10.1016/j.immuni.2018.04.006 
[Additional info] Origin and phenotype is less well understood in humans than in mice

(I added this as CL:0009106 'medullary reticular cell', committed to the editors' file but not publicly released yet)

Should 'medullary reticular cell' be a subclass of 'reticular cell' rather than the broader suggested 'fibroblast'? I saw the comment about the origin being unclear in human, but given that the label contains "reticular", if we don't want 'medullary reticular cell' to be a subclass of 'reticular cell' it'd be better to make this more explicit in a comment to prevent the same question in the future. Also, the suggested definition is "Stromal cell present in the lymph node medulla.", so should it be a child of 'stromal cell' instead? If the available knowledge is insufficient to clarify, we could make 'medullary reticular cell' a subclass of 'connective tissue cell' (parent of both fibroblast and stromal cell), but that may be a bit extreme (also considering that stromal cells and tissues are not greatly defined).

Thank you,
Paola

**Comment by emquardokus** [comment]
@paolaroncaglia 
Spoke with Andrea Radtke 4-21-2022 about her definition for Medullary Reticular Cell of lymph node and lineage of cell type. 
Pointed out description as "stromal cell present in the lymph node medulla" vs where stromal cell vs reticular cell and fibroblast relationships in CL. Worth pointing out that updates to stromal cell may need revision to catch up with current knowledge.
Obtained better DOIs describing human medullary reticular cells (MedRCs) and comparison to mouse: DOI:https://doi.org/10.1016/j.it.2021.06.006.  This paper discusses stromal cells in relationship to Medullary reticular cells https://doi.org/10.1038/s41586-021-03549-5 "The cords are populated by medullary reticular cells (MedRCs), macrophages, and plasma cells. MedRCs highly express CXCL12 ([Hargreaves et al., 2001](https://www.sciencedirect.com/science/article/pii/S1074761318301432?via%3Dihub#bib30)), but little else is known about them."

**Propose modifying description of MedRC to "specialized fibroblast found in the medulla of lymph node"**
**Put Medullary reticular cell under Reticular cell in CL**
Thank-you

**Comment by paolaroncaglia** [comment]
@emquardokus Will do! Thank you for following up.

**Comment by paolaroncaglia** [comment]
- [ ] To do: "stromal cell may need revision to catch up with current knowledge" as per ASCT+B's suggestion

**Comment by paolaroncaglia** [comment]
@emquardokus 

> "Worth pointing out that updates to stromal cell may need revision to catch up with current knowledge" 

as per your latest comment - if you have specific suggestions, including references, could you please open a new ticket?
Thank you.

**Comment by paolaroncaglia** [comment]
@dosumis @emquardokus 
All cell type requests in this ticket have been addressed, terms created and information incorporated based on the [lymph node spreadsheet](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=457494842). IDs and labels of new terms are in the right-most column in the spreadsheet. If you'd like, you could load the latest version of cl-edit.owl in Protege, take a look at the new terms, and let me know if you have any concern. Based on the definitions that were provided, I think that we could change subclasses to equivalent axioms for the following terms, but I've erred on the side of caution and kept subclasses for now:

CL_0009103 (lymph node marginal reticular cell)
CL_0009104 (B cell zone reticular cell)
CL_0009105 (T cell zone reticular cell)
CL_0009107 (lymphatic endothelial cell of subcapsular sinus ceiling)
CL_0009108 (lymphatic endothelial cell of subcapsular sinus floor)
CL_0009109 (lymphatic endothelial cell of trabecula)
CL_0009111 (centrocyte)
CL_0009112 (centroblast)

Let me know if you'd like me to change the subclasses to EAs.

**Comment by emquardokus** [comment]
@paolaroncaglia @dosumis 
Looked at cl-edit.owl and based on literature, I'm wondering why medullary reticular cell is not in the under 'lymph node fibroblastic reticular cell? 
All of these seem correct based on same literature to be under 'lymph node fibroblastic reticular cell:
CL_0009103 (lymph node marginal reticular cell)
CL_0009104 (B cell zone reticular cell)
CL_0009105 (T cell zone reticular cell)
<img width="362" alt="Screen Shot 2022-04-28 at 10 52 55 AM" src="https://user-images.githubusercontent.com/47257000/165781699-5c653fbe-d996-4b9d-89a5-14e9b340674e.png">

For these, would it make sense to have "lymph node lymphatic vessel endothelial cell" with these cell types under it?: 
CL_0009107 (lymphatic endothelial cell of subcapsular sinus ceiling)
CL_0009108 (lymphatic endothelial cell of subcapsular sinus floor)
CL_0009109 (lymphatic endothelial cell of trabecula)
<img width="455" alt="Screen Shot 2022-04-28 at 11 02 24 AM" src="https://user-images.githubusercontent.com/47257000/165783094-d64b0625-3b28-4227-ac8e-8c0d4f575211.png">

**Comment by paolaroncaglia** [comment]
@emquardokus @dosumis 

> @paolaroncaglia @dosumis Looked at cl-edit.owl and based on literature, I'm wondering why medullary reticular cell is not in the under 'lymph node fibroblastic reticular cell? 

I made 'medullary reticular cell' a subclass of 'reticular cell' and 'part of' some 'medulla of lymph node', rather than equivalent to, because the information provided for 'medullary reticular cell' didn't give me the confidence to say that any and all reticular cells found in lymph node medulla are the same type of specialised fibroblast that the expert referred to, as per your previous comment [here](https://github.com/obophenotype/cell-ontology/issues/1472#issuecomment-1109465649). I do agree that 'medullary reticular cell' should be a child of 'lymph node fibroblastic reticular cell'. @dosumis , please advice on whether I should assert the subclass or add the equivalence.

> For these, would it make sense to have "lymph node lymphatic vessel endothelial cell" with these cell types under it?: CL_0009107 (lymphatic endothelial cell of subcapsular sinus ceiling) CL_0009108 (lymphatic endothelial cell of subcapsular sinus floor) CL_0009109 (lymphatic endothelial cell of trabecula) <img alt="Screen Shot 2022-04-28 at 11 02 24 AM" width="455" src="https://user-images.githubusercontent.com/47257000/165783094-d64b0625-3b28-4227-ac8e-8c0d4f575211.png">

It's preferable to avoid inflating the ontology with grouping terms based solely on their location, unless they're strictly needed (see the anatomograms use case) and/or can be defined based on shared functional characteristics or markers etc. This said, I might be missing the use case :-) and of course I can add the term if you both think that it would help. Thanks!

**Comment by dosumis** [comment]
> I made 'medullary reticular cell' a subclass of 'reticular cell' and 'part of' some 'medulla of lymph node', rather than equivalent to, because the information provided for 'medullary reticular cell' didn't give me the confidence to say that any and all reticular cells found in lymph node medulla are the same type of specialised fibroblast that the expert referred to, as per your previous comment https://github.com/obophenotype/cell-ontology/issues/1472#issuecomment-1109465649. I do agree that 'medullary reticular cell' should be a child of 'lymph node fibroblastic reticular cell'. @dosumis , please advice on whether I should assert the subclass or add the equivalence.

subClassOf makes sense.  Agree that Equivalence could be dangerous given current state of knowledge.

For 'lymph node lymphatic vessel endothelial cell' I think a general term could be useful.  Maybe try running the DL query first to see if you get everything you expect under it.
