### ISSUE TITLE
Random unresolvable CARO term in CL hierarchy

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#1473]
http://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CARO_0000006

<img width="610" alt="image" src="https://user-images.githubusercontent.com/50745/155177870-5873b1cb-f51f-4c5d-8d9a-83d0a8391ec1.png">

http://purl.obolibrary.org/obo/CARO_0000006 is itself unresolvable

**Comment by shawntanzk** [comment]
related to https://github.com/obophenotype/cell-ontology/issues/1306

**Comment by shawntanzk** [comment]
will try to import in CARO after https://github.com/obophenotype/cell-ontology/pull/1461 and see if there are any clashes
