### ISSUE TITLE
[NTR] nonparenchymal liver cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1476]
**Preferred term label:**
nonparenchymal liver cell

**Synonyms**
nonparenchymal cell
non-parenchymal cell 
non-parenchymal liver cell
hepatic non-parenchymal cell

**Definition**
Hepatocytes constitute about 80% of the mass of the liver. The remaining tissue is made up of nonparenchymal liver cells such as Kupffer cells, stellate cells and liver sinusoidal endothelial cells. These cells play an important role in liver regeneration and recovery from inflammatory liver injury. [PMID: 8743919]

**Parent cell type term:**
CL:0000000 (cell)

**What is the anatomical structure that the cell is a part of?**
UBERON:0002107 (liver)

**Your nano-attribution (ORCID)**
0000-0002-0819-0473

**Any additional notes or concerns**
This is not a distinct entity but all liver cells that are not hepatocytes. 
Not clear to which term must be related to in CL.
This term can be mapped to BTO:0005265

**Comment by bvarner-ebi** [comment]
Thank you for the new term request, @paulacalipho.

I propose we make the parent cell type **CL:0002371 'somatic cell'**.

For synonyms, do you agree with the following types?
nonparenchymal cell **(broad)**
non-parenchymal cell **(broad)**
non-parenchymal liver cell **(exact)**
hepatic non-parenchymal cell **(exact)**

**Comment by paulacalipho** [comment]
@bvarner-ebi Yes, many thanks

**Comment by dosumis** [comment]
Couple of potential issues here:

1. We also don't typically make terms with negative definitions.  I think in this case we may be able to as may be able to list all subclasses cleanly.  However, I'd like to discuss further on the upcoming CL call. 

2. Parenchyma is a rather broad/vague term.  As a result, the parenchyma terms in Uberon are poorly populated with tissues and so classification in CL based on part relationships to parenchyma terms is unreliable.  There is demand for these terms though, especially from clinical users.  We need to discuss a strategy for supporting these terms.  Let's also add this to the CL meeting agenda.

In the meantime,  please put this request on hold.

Thanks, David

**Comment by bvarner-ebi** [comment]
This term was discussed in today's CL meeting.

@addiehl and @paolaroncaglia shared thoughts. There is concern that this term is problematic due to it being too general and based on a negative ('everything else') definition, which is not good practice for ontologies. There are also many cell types outside the scope of the term that are involved in liver regeneration.

@paulacalipho, consensus is that we will not proceed with creating this term at the moment. We would like to understand your use case better so that we could offer other potential solutions. Is it to map cell types in Cellosaurus to CL?

**Comment by paulacalipho** [comment]
@bvarner-ebi, thanks for reviewing this term. I understand your concern. 
It is to map the cell line NPC2-hTERT (synonym: NPC-hTERT) described in PubMed=20456367. Derived from sampling site: Fetal liver. Cell type=Non-parenchymal cell. This cell line will be release today in Cellosaurus. The paper is not really helpful, it only states "NPC2, non-parenchymal cells"

**Comment by paolaroncaglia** [comment]
@paulacalipho cc @bvarner-ebi 

> It is to map the cell line NPC2-hTERT (synonym: NPC-hTERT) described in PubMed=20456367. Derived from sampling site: Fetal liver. Cell type=Non-parenchymal cell. This cell line will be release today in Cellosaurus. The paper is not really helpful, it only states "NPC2, non-parenchymal cells"

The abstract of the paper you cite says "Here, we established two new cell lines, telomerase immortalized human fetal hepatocytes, Hc3716-hTERT, and telomerase immortalized hepatic stellate cells, NPC-hTERT." so why not use CL:0000632 'hepatic stellate cell'?
Note (for Bradley), the "mapping" here really means "derived from".

**Comment by paulacalipho** [comment]
Thanks @paolaroncaglia for your input. Indeed in the abstract is indicated this cell type. Material and methods indicate non-parenchymal cells and further analysis indicates has stellate cell markers. We will analyze to what this term will be mapped. Many thanks again, Paula
