### ISSUE TITLE
Proposal to obsolete CL:0000000 cell

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#148]
```
replaced_by GO:0005623 ! cell

Note this is an obsoletion, not a merge, as this proposal involves changing the 
definition of cell to include encapsulating structures (if present) (as defined 
in GO, and consistent with PO).

CL:0000003 ! native cell  would become a subclass of GO:0005623 ! cell


GO:0005623 ! cell
may have an additional synonym "cell plus encapsulating structures"

We could optionally have an additional class in GO that is part_of GO:cell 
called something like "cell minus encapsulating structures (if present)" - but 
it's not clear what the use case is
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 24 Jul 2014 at 4:02

**Comment by cmungall** [comment]
GO:0005623 will be obsoleted. Announcement from @pgaudet coming soon

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to replace `GO:0005623 cell` with `CL:0000000 cell` from the Cell Type ontology. 

There are currently no more terms in the ontology using `GO:0005623 cell`. We plan to implement this change in two weeks, on April 17, 2020. Please let us know if you need more time to adjust your parsers or tools.  Comments can be made on the GO tracker: https://github.com/geneontology/go-ontology/issues/19036


Thanks, Pascale
