### ISSUE TITLE
[NTR] Add CL terms for kidney ASCT+B table

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1482]
cc @dosumis and @emquardokus

Per our ASCT+B harmonisation meetings, I’ll be adding CL terms needed for the kidney [ASCT+B table](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=1063693910).

I have entered preliminary information for @emquardokus and her SMEs to review, add to, and approve [on the kidney table](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=1063693910).
This is a placeholder / tracking ticket for the forthcoming new term requests / edits related to this work.

**Comment by emquardokus** [comment]
@bvarner-ebi @dosumis I met with Sanjay Jain (KPMP and HuBMAP) on Friday April 30; he reviewed and updated the new term request table on May 2, 2022.  He asked about adding 2 additional cell types Descending Thin Limb Cell Type 2 and Descending Thin Limb Cell Type 3 and I've added those to the table and asked if he could provide the rest of the information for those.
He has updated those 2 new cell types for their descriptions and citations as of May 2, 2022 10:30 am EASTERN
This should all be ready to go now. 
Please let me know if you are still having any questions; I believe they've all been addressed now?

**Comment by bvarner-ebi** [comment]
Per @emquardokus, these new kidney-related terms ideally will be added by end of May 2022.

**Comment by bvarner-ebi** [comment]
@emquardokus, now that all terms from [the kidney table](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=1063693910) have been added to CL, I will close this ticket. Future requests can be submitted via "New Term Request" tickets.
Thanks for your contributions!
