### ISSUE TITLE
[Typo/Bug] Typo in synonym of CL:0002169

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1489]
**CL term**
CL:0002169 basal cell of olfactory epithelium

**Description of typo, bug or error**
has broad synonym "horizontal basal _call_", please correct to "...cell". Thanks.

**Comment by paola-scibite** [comment]
Note, [Typo/Bug] template issues are automatically assigned to David, Nicole and Alex, we should change this (I can't from this account)

**Comment by paolaroncaglia** [comment]
@bvarner-ebi before you close this, could you please address https://github.com/obophenotype/cell-ontology/issues/1489#issuecomment-1062805344? If you don't have privileges to edit the issue templates, let us know. Thanks!

**Comment by paolaroncaglia** [comment]
P.S. That's why I use "addresses" or similar in PRs instead of "fixes/closes" - I know the latter is ok most of the time, but going back to the originating issue before closing it ensures that all tasks are looked into. :-) Thank you for taking care of this!

**Comment by dosumis** [comment]
> @dosumis, @shawntanzk, do you have the ability to edit how tickets are auto-assigned from templates?

Taking a look now.

**Comment by paolaroncaglia** [comment]
I'm on it https://github.com/obophenotype/cell-ontology/pull/1494

**Comment by paolaroncaglia** [comment]
@dosumis shall I remove automated assignments from all issue templates while I'm there?
I think we reached that consensus on a recent call.

**Comment by paolaroncaglia** [comment]
(I won't ask you to review them all :-D )

**Comment by bvarner-ebi** [comment]
> I'm on it #1494

Thank you, @paolaroncaglia! I now see this was described in the latter of the instructions page.

**Comment by bvarner-ebi** [comment]
> @dosumis shall I remove automated assignments from all issue templates while I'm there?
> I think we reached that consensus on a recent call.

I could also do this now that you showed me how :)

**Comment by bvarner-ebi** [comment]
> [Typo/Bug] template issues are automatically assigned to David, Nicole and Alex, we should change this (I can't from this account)

Note: issues generated from templates are no longer automatically assigned to users (resolved via PR #1495).
