### ISSUE TITLE
Strip labels of 'pericyte cell' and 'perirenal adipocyte cell' of the redundant "cell"

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1503]
The suffix -cyte means cell, so 'pericyte cell' and 'perirenal adipocyte cell' should be labeled 'pericyte' and 'perirenal adipocyte' for logic and consistency with all other -cyte terms in CL (e.g. leukocyte, lymphocyte). The current labels should be kept as exact synonyms. 
(Note, 'pericyte cell' has an exact synonym of pericyte, which should be removed. At a quick glance, 'pericyte' is what literature calls them. But - update/note to self - I asked Bradley for his opinion as he's more aware of the literature.)
(Also, update/note to self, I've looked at 'perirenal adipocyte cell' again and I don't see any reason not to change that label.)

**Comment by paolaroncaglia** [comment]
If no objections are voiced, I will assume that you all agree to these changes. Thanks.

**Comment by paolaroncaglia** [comment]
@lubianat 

> I think this is safe. It might be, though, a good "low hanging fruit" for people getting to know about CL? Something to familiarize with the PR workflow and the like

I labeled this ticket as "Good first task", and I agree that it would be a good one to address for training purposes, but as far as I know, there aren't any plans to hire new CL editors soon... that's why I assigned it to me (as I opened it), but it's not a priority.

**Comment by paolaroncaglia** [comment]
@bvarner-ebi 
Tagging you as you've worked on pericyte terms recently. Not urgent, but I'd appreciate your feedback on renaming 'pericyte cell' as 'pericyte', to resolve the implicit redundancy ("cyte" means "cell") and to make labels more consistent across the whole branch, see below. Thanks.

![Screenshot 2022-04-22 at 15 00 19](https://user-images.githubusercontent.com/4982516/164719645-dda00d96-a1b1-48dd-9fed-31fb63a56e1c.png)

**Comment by bvarner-ebi** [comment]
@paolaroncaglia, thank you for reminding me of this ticket. I agree with your comments and will make these edits.
