### ISSUE TITLE
Cortical interneuron equivalent axiom uses cortex instead of cerebral cortex

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1507]
equiv axiom for CL:0008031 is:
```
interneuron
 and ('has soma location' some cortex)
```
Cortex here refers to "Outermost layer of an organ"
Instead cortical interneurons are understood to mean cerebral cortex. 
This has implications on classification.

**Comment by dosumis** [comment]
Oops!
