### ISSUE TITLE
Please import 3 lymph node Uberon terms 

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#1523]
@shawntanzk could you please import the following Uberon classes in CL? 
Last ones needed to complete #1472.
Overnight is fine, thank you very much in advance!

UBERON:8410052 lymph node germinal center light zone (already released)
UBERON:8410071 subcapsular sinus ceiling (committed but not yet released as of today 24/3/22)
UBERON:8410072 subcapsular sinus floor (committed but not yet released as of today 24/3/22)

**Comment by shawntanzk** [comment]
@paolaroncaglia this might have to wait for new uberon release for me to pull them into CL. I can do the first one first, but if they are all needed I'd rather wait for a release and do them altogether. I can run an uberon release if needed, fingers crossed nothing breaks this time lol. Let me know :)

**Comment by paolaroncaglia** [comment]
@shawntanzk I agree it'd be optimal to import all 3 at once. They're all needed to complete the lymph node ASCT+B work, and the last release of Uberon was done on Feb 21, so hopefully there are no objections to running a new release? But I know it's a bit of a pain, so I'm ok with waiting if you prefer, and/or if others have Uberon PRs that they'd like to go in. Thank you.

**Comment by shawntanzk** [comment]
@paolaroncaglia I think the only worry would be space - uberon is pretty big an ontology and all. I will make a call out in uberon slack, if all good, ill run a release and once that is pulled, will make the imports altogether

**Comment by matentzn** [comment]
No, forgot to reroute the non-standard releases in the PURL config. 10 min.

**Comment by matentzn** [comment]
Ok all good now.

**Comment by shawntanzk** [comment]
thanks @matentzn :)
