### ISSUE TITLE
CL had SuperProperty Of (Chain) on develops from that is now removed 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1532]
CL used to have these axioms that were imported into uberon that did some heavy lifting
In the new test release (https://github.com/obophenotype/uberon/pull/2376), when we updated CL, these were missing causing a massive loss of inferred axioms. 
Are these correct and should be added back? If so should we add them back in RO instead of CL? 
![Screenshot 2022-04-04 at 14 56 46](https://user-images.githubusercontent.com/76212760/161559764-61f0f46d-26b0-4fdb-9ab7-40dedb6e2ddf.png)

**Comment by balhoff** [comment]
They should not be added back: https://github.com/obophenotype/uberon/pull/1808
