### ISSUE TITLE
Excitatory neuron currently only has retinal bipolar neuron under it

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1540]
![Screenshot 2022-04-07 at 15 19 58](https://user-images.githubusercontent.com/76212760/162221037-2ac0652e-7b1d-41a9-a872-1ecbf8885f88.png)

This is definitely not right as most glutamatergic neurons are excitatory - problem being not ALL glutamatergic neurons are excitatory, and not all excitatory neurons are glutamatergic neurons (I can't give an example off my head, but im 100% sure I've learnt that developmental period GABA/Glut Inhibitatory/excitatory is not as straightforward a dichotomy 

Will need to think about how to handle this

**Comment by shawntanzk** [comment]
CL call decision:
obsolete excitatory and inhibitory, as these are too difficult to populate 
HOWEVER - check if any downstream is affected first

**Comment by jenjou** [comment]
Hello,

The "excitatory neuron" term was used to annotate some datasets submitted for the ENCODE project prior to the term's deprecation: https://www.encodeproject.org/search/?type=Experiment&biosample_ontology.term_name=excitatory+neuron

Does CL have any further information about the decision to remove this term? We spoke briefly with some of the labs involved and are concerned that the suggested replacement "glutamatergic neuron" is overly specific for our use case, whereas the superclass "neuron" would be overly general. Any additional info would help us decide how to resolve our use of the obsolete term.

Thank you in advance!

**Comment by shawntanzk** [comment]
Hi @jenjou - our concern with excitatory neuron is that we need to manually populate these (for the same reason why glutamatergic neuron is overly specific for your use case. If we have excitatory neuron, we are not confident in properly populating it completely, which would be problematic for the ontology. I do however understand that it might be required for annotation, and I wonder if there is a possibility of more specific terms, the obvious one being glutamatergic neurons where appropriate. 
I'm happy to bring this up in the next CL call (which happens to be tmr), but perhaps you can help us by letting us know the use case for the term, or rather a case where you need excitatory neurons but glutamatergic neurons is too specific. I see mostly RNA-seq based experiments in the link you gave, in which case, from my understand, excitatory mainly means glutamatergic no? (ie RNA sequencing doesn't tell you the excitatory or inhibitory nature of a cell, but instead tells you biomarkers of cell types that, for example, express glutamate). I'm not sure if there are some techniques that I am unaware of that filters out excitatory neurons specifically, in which case that's a good argument for having something like excitatory neurons. 
Thanks

**Comment by jenjou** [comment]
Thanks for the explanation! We'll need to reach out to the labs to get more detailed information about these samples -- I'm not sure we'll have a follow up by tomorrow, but I will reach out again if we have more specifics on the methods used.

**Comment by cmungall** [comment]
@dosumis and I think it was a mistake to obsolete these.

Rather than re-open this ticket, I made a new one https://github.com/obophenotype/cell-ontology/issues/2083 with some additional observations in it
