### ISSUE TITLE
Fix MeSH cross-references

### ISSUE THREAD

**Issue by bgyori** [obophenotype/cell-ontology#1557]
Similar to UBERON (see https://github.com/obophenotype/uberon/issues/698), CL contains a number of cross-references to MESH that are represented as tree numbers rather than IDs. These should ideally be replaced where possible and I will open a PR to do so.

However, as also pointed out in https://github.com/obophenotype/cell-ontology/issues/146, many CL terms do not actually refer to a corresponding MESH term as a usual xref, but rather refer to it as part of the definition. Here is an example with CL:0000034 in OWL and OBO, respectively:
```
# Class: obo:CL_0000034 (stem cell)

AnnotationAssertion(Annotation(oboInOwl:hasDbXref "GOC:tfm"^^xsd:string) Annotation(oboInOwl:hasDbXref "MESH:A11.872"^^xsd:string) obo:IAO_0000115 obo:CL_0000034 "A relatively undifferentiated cell that retains the ability to divide and proliferate throughout life to provide progenitor cells that can differentiate into specialized cells."^^xsd:string)
AnnotationAssertion(oboInOwl:hasDbXref obo:CL_0000034 "CALOHA:TS-2086"^^xsd:string)
AnnotationAssertion(oboInOwl:hasDbXref obo:CL_0000034 "FMA:63368"^^xsd:string)
...
```

```
[Term]
id: CL:0000034
name: stem cell
namespace: cell
def: "A relatively undifferentiated cell that retains the ability to divide and proliferate throughout life to provide progenitor cells that can differentiate into specialized cells." [GOC:tfm, MESH:A11.872]
comment: This term applies to metazoan. For plant stem cells, consider using PO:0004011 ‘initial cell’ or its parent PO:0004010 ‘meristematic cell’.
xref: CALOHA:TS-2086
xref: FMA:63368
...
```

Is there some rationale behind putting references to MESH in the definition rather than the xref list? I would assume that most downstream code that aims to find xrefs would overlook these.

**Comment by cthoyt** [comment]
It might be more specifically denoting that the text was borrowed from the MeSH record, but I agree, in this case it would be nice to have the xref also on the node level since these two places for xrefs can be interpreted differently.

**Comment by dosumis** [comment]
> It might be more specifically denoting that the text was borrowed from the MeSH record

Correct.


>  but I agree, in this case it would be nice to have the xref also on the node level since these two places for xrefs can be interpreted differently.

+1.

Maybe it would be useful to have some script in place to auto-propagate these from  Def xref to xref on the term?

**Comment by shawntanzk** [comment]
looks like this is done here https://github.com/obophenotype/cell-ontology/pull/1558, please reopen if there are any issues?
