### ISSUE TITLE
[Merge] foreskin melanocyte and melanocyte of foreskin

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1562]
**CL term (ID and Label)**
CL_2000045 foreskin melanocyte

**Reason for deprecation**
Both terms are fairly similar; I don't know if there are non-skin foreskin melanocytes. In any case, at least the labels should be changed for clarity. 

**Term to be merged with (ID and Label)**
https://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_2000045 foreskin melanocyte
https://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_2000082 melanocyte of foreskin

**Comment by lubianat** [comment]
can someone else comment on this issue? maybe @bvarner-ebi ? 

I am not really sure how merging works in CL

**Comment by lubianat** [comment]
docs: https://oboacademy.github.io/obook/howto/merge-terms/

**Comment by bvarner-ebi** [comment]
Hi @lubianat, thanks for the updated comment.
This was not on my radar since I saw it was assigned to you.

@shawntanzk reported that he forwarded you the documentation on how to merge. If you like, can you give it a go and provide feedback on whether or not the documentation was easy to follow? Of course, reach out if you run into issues along the way.

**Comment by lubianat** [comment]
Sure, thanks @bvarner-ebi ! Won't be able to do it today, though; but it is on my to do list for the next CL slot on my agenda

**Comment by bvarner-ebi** [comment]
Hi, @lubianat, checking in on this ticket.
Kindly advise if you would like help with this merge.

**Comment by lubianat** [comment]
@bvarner-ebi thanks; 
I won't be doing this merge in the near future. I cannot accurately estimate the time I'll take and how hard it will be 

I might do it in the next semester, when some of my current commitments will be over

**Comment by aleixpuigb** [comment]
Hi @lubianat, I am checking old open tickets. Is it still in your plans to do the merge or would you like me to assign myself or another CL editor?

**Comment by lubianat** [comment]
@aleixpuigb thanks for the ping again. I guess I fell into some rabbit hole on that and could not really complete the merge. Feel free to assign someone else (not sure if I'll be able to do it)

**Comment by aleixpuigb** [comment]
No problem, it will be good practice for new editors to merge terms.
