### ISSUE TITLE
melanocyte should not be a subclass of neurecto-epithelial cell

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#157]
```
neurecto-epithelial cell is a subclass of epithelial cell and this is causing 
the inference that melanocyte is equivalent to epithelial melanocyte, which is 
incorrect.
```

Original issue reported on code.google.com by `vasil...@ohsu.edu` on 2 Dec 2014 at 10:52

**Comment by addiehl** [comment]
This seems to have been fixed a long time ago per the comments from Melissa and what I can see in CL using Protege.
