### ISSUE TITLE
Microglial does not derive from OPCs nor glioblast

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1571]
see https://cshperspectives.cshlp.org/content/7/8/a020537.full

Currently microglial has the subclass axiom
`'develops from' some 'oligodendrocyte precursor cell'`
which seems wrong

They arise from hematopoietic stem cells in the yolk sac during early embryogenesis that populate the central nervous system -> derived from embryonic mesoderm and are not from neuroectoderm where glioblast develops from

glial cell therefore also cannot have the axiom `'develops from' some glioblast` - this needs to be pushed down to all child that actually do.

This might also have implications on FBbt:00005145 glial cell definition:  "Cell that divides to give rise to glial cells."

**Comment by shawntanzk** [comment]
Related to https://github.com/obophenotype/cell-ontology/issues/573#issuecomment-1112584551

**Comment by gouttegd** [comment]
> glial cell therefore also cannot have the axiom 'develops from' some glioblast - this needs to be pushed down to all child that actually do.

I _think_ that in vertebrates all _macroglia_ do derive from glioblasts, though I would like to find confirmation of that.

> This might also have implications on FBbt:00005145 glial cell definition: "Cell that divides to give rise to glial cells."

For FBbt this is fine. In _Drosophila_ all glial cells do derive from glioblasts, and there is no microglia.

**Comment by shawntanzk** [comment]
> Drosophila all glial cells do derive from glioblasts, and there is no microglia.

The world of Drosophila is wild man :p

**Comment by gouttegd** [comment]
I’d like to argue that it’s the world outside of _Drosophila_ that is wild, but I’ll admit I could be _slightly_ biased. :D
