### ISSUE TITLE
[NTR] [ASCT+B table] descending thin limb epithelial cell (3 types)

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1579]
This is part of the ASCT+B harmonisation initiative. New terms are being spawned from [the kidney table](https://docs.google.com/spreadsheets/d/1BihrOU9vWrsA_wYjcbdPUr42_Sb22CO3gkBDieiYQPs/edit#gid=1063693910).

Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
descending thin limb epithelial cell type 1
descending thin limb epithelial cell type 2
descending thin limb epithelial cell type 3

**Synonyms**
currently none

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
respectively:
Epithelial cell of the descending thin limb of the short loop (cortical) nephron limited to the outer medulla (mainly inner stripe) that may be enriched in the urea transporter SLC14A2.

Epithelial cell of the descending thin limb of the long loop (juxtamedullary) nephron that spans the outer medulla (inner stripe) and expresses AQP1, SLC4A11 and SLC9A3.

Epithelial cell of the descending thin limb of the long loop (juxtamedullary) nephron that spans the inner medulla and may express AQP1 and SLC4A11.  The urea transporter SLC14A2, especially in the segments reaching the papillary tip, may also be expressed.
PMID:33769951
 **@dosumis, @emquardokus should these definitions include the notes on gene expression? Glancing at the references provided in the kidney sheet, perhaps there is too much heterogeneity to justify noting specific genes in the definitions.**

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:1001111 'kidney loop of Henle thin descending limb epithelial cell'

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
UBERON:0005096 'descending thin limb'

**Your nano-attribution (ORCID)**
 https://orcid.org/0000-0002-1773-2692 
[@emquardokus](https://github.com/emquardokus), kindly advise if other attributions should be added to these terms

**Any additional notes or concerns** 
"parent GitHub ticket": [#1482](https://github.com/obophenotype/cell-ontology/issues/1482)

**Comment by bvarner-ebi** [comment]
Note: I don't see a justification to label these as cell type 1, cell type 2, etc.
Although long, these are the updated labels that I believe clearly convey the cell types:

epithelial cell of the short descending limb of the loop of Henle
epithelial cell of the outer medulla of the long descending limb of the loop of Henle 
epithelial cell of the inner medulla of the long descending limb of the loop of Henle

Additionally, I plan to remove references to biomarkers from the definitions.

**Comment by bvarner-ebi** [comment]
Removed "(inner stripe)" from definition for 'epithelial cell of the outer medulla of the long descending limb of the loop of Henle'... did not see this specification in reference. Will add back if reference found.

**Comment by emquardokus** [comment]
@bvarner-ebi the descriptions that Sanjay Jain provided should be used as is.  PMID: 33769951 provides the differential gene expression evidence for the particular genes that are hallmarks for these regions and cell types.
The concise cell names are more succinct and it's hard to justify the multiple "of this of that" phrasing--is this necessary?
Inner and Outer stripe are well documented terms in kidney literature and should be provided in description.

**Comment by bvarner-ebi** [comment]
Thank you for the review and feedback, @emquardokus!
My feedback is below, and I look forward to your replies.

> the descriptions that Sanjay Jain provided should be used as is. PMID: 33769951 provides the differential gene expression evidence for the particular genes that are hallmarks for these regions and cell types.

Looking at PMID: 3376995, I see the following for segment-specific genes:

"DTL1 selectively expresses the serine protease Corin, the homeobox TF Uncx, and the urea channel Slc14a2. The long descending limb of the loop of Henle in the outer medulla selectively expresses the secreted activin-antagonist protein follistatin (Fst), the GPI-linked adhesion protein Cdh13, and the protein kinase Stk32a. The long descending limb of the loop of Henle in the inner medulla selectively expresses the nuclear receptor Nr2e3, the Ig κ chain Igkc, and the secreted protein dermokine (Dmkn)."

For DLT1, for example, I'm trying to connect the proposed definition with the paper. Why was Slc14a2 only mentioned in the proposed definition and not all of the following: "the serine protease Corin, the homeobox TF Uncx, and the urea channel Slc14a2"?
I also think the wording of "may be enriched" and "may also be expressed" can be problematic for ontology definitions. If they are defining characteristics, I would remove phrasing with "may". If they are not always defining characteristics, I suggest placing in a comment rather than a definition. We also do not tend to use "negative definitions", so "not the urea transporter SLC14A2" would probably not be appropriate for the definition. 

> The concise cell names are more succinct and it's hard to justify the multiple "of this of that" phrasing--is this necessary?

Please see related discussion here:
https://github.com/obophenotype/cell-ontology/pull/1578#discussion_r872096897

I agree we should follow the format of the parent and go with:

'kidney loop of Henle short descending limb epithelial cell'
'kidney loop of Henle long descending limb outer medulla epithelial cell'
'kidney loop of Henle long descending limb inner medulla epithelial cell'

We could put the longer form of the labels as exact synonyms. Does this sound reasonable?

>Inner and Outer stripe are well documented terms in kidney literature and should be provided in description See PMID: [26290371](https://www.ncbi.nlm.nih.gov/pubmed/26290371); this also provides further historical evidence of long standing markers for those regions.

I am familiar with these terms, but did not see the original reference specify the inner/outer stripe location. Thank you for the additional reference. 
Can you highlight where 'kidney loop of Henle long descending limb outer medulla epithelial cell' is said to be restricted to the "**inner stripe** of the outer medulla"? I also do not see SLC4A11 or SLC9A3 mentioned in this reference.

>Sanjay Jain 0000-0003-2804-127X
Thank you!

I'm also happy to jump on a zoom meeting or Slack thread to discuss if that will be more expedient.

**Comment by bvarner-ebi** [comment]
The following terms have been added:

CL:4030012 'kidney loop of Henle short descending thin limb epithelial cell'
CL:4030013 'kidney loop of Henle long descending thin limb outer medulla epithelial cell'
CL:4030014 'kidney loop of Henle long descending thin limb inner medulla epithelial cell'
