### ISSUE TITLE
Hepatic progenitor cell

### ISSUE THREAD

**Issue by masciam** [obophenotype/cell-ontology#1594]
Hi as finishing my work on the ASCT table for Liver I would like to request to add the hepatic progenitor cell as human adult counterpart of the oval cell that are bipotential progenitors capable of forming hepatocytes or cholangiocytes in rodent adult liver. The equivalent bipotential progenitors in adult human liver are called hepatic progenitor cells.  
There is a difference between hepatic stem cell and hepatic progenitor because the last one can only became hepatocyte or cholangiocyte and nothing else. It may be added  as synonym of the oval cell. My only concern in doing this is that in CL there is oval stem cell and this could create a problem of consistency if stem cell is multi potent

**Comment by bvarner-ebi** [comment]
Hi @masciam, thank you for suggesting this new cell type.
Could you [create an "Add term" issue,](https://github.com/obophenotype/cell-ontology/issues/new/choose) and provide the requested information?
For examples of other "new term requests', you could view closed issues with the "new term request" tag or reach out to me for additional support.

**Comment by bvarner-ebi** [comment]
Closing this issue as it has been replaced by #1604.
