### ISSUE TITLE
hepatic progenitor cell 

### ISSUE THREAD

**Issue by masciam** [obophenotype/cell-ontology#1604]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
hepatic progenitor cell 

**Synonyms**
adult hepatic progenitor cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
It is a progenitor cell that is part of the adult human liver and is capable of differentiating only in hepatocyte or cholangiocyte 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
progenitor cell

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
adult liver

**Your nano-attribution (ORCID)**
0000-0003-1940-6740

**Any additional notes or concerns**

**Comment by bvarner-ebi** [comment]
Thank you for this ticket, @masciam. Would you kindly add the reference (PMID, DOI, etc) to support adding this cell type?

**Comment by emquardokus** [comment]
@bvarner-ebi @masciam 
Here are several DOI to support adding cell type; needed urgently for HuBMAP
https://doi.org/10.1038/s12276-020-0483-0
https://doi.org/10.7554/eLife.47313
https://doi.org/10.1016/B978-0-12-385233-5.00008-8
http://dx.doi.org/10.1136/gut.2007.143321
Thanks

**Comment by bvarner-ebi** [comment]
This cell type appears to be the same as CL:0002196 'hepatic oval stem cell'.

In https://doi.org/10.1038/s12276-020-0483-0 it states: "... [biliary epithelial cells] are able to dedifferentiate into liver progenitor cells (LPCs), also known as oval cells.'

In [PMID:17901986](https://pubmed.ncbi.nlm.nih.gov/17901986) it states: "Hepatic stem/progenitor cells also known as “oval cells” in rodents have been implicated in liver tissue repair, ..."

The [comment here](https://github.com/obophenotype/cell-ontology/issues/1594#issue-1241737084) proposes adding this term as a synonym to 'hepatic oval stem cell'. There is a concern regarding the multipotent categorisation of stem cell, but based on the literature and in line with the definition of 'hepatic oval stem cell', this progenitor cell can differentiate into more than one cell.

Proposal:
- [ ] add exact synonyms 'hepatic progenitor cell', 'hepatic stem/progenitor cell' and 'liver progenitor cell' to CL:0002196 'hepatic oval stem cell' with appropriate dbxrefs

**Comment by masciam** [comment]
I am fine with having the hepatic progenitor cell as synonym of the Oval cell. My only concern is that the hepatic progenitor cell are only present in adult human can only differentiate in 2 specific cell types and they are different from hepatic stem cell that derived from bone marrow.  I will not change '_hepatic oval cell_' with '_haptic oval stem cell_' this will create more confusion.  I have some concerns on the fact that in CL _progenitor cell_ are parent of _stem cell_ instead to be the reverse. Stem cell can differentiate in many cell types and are reserve cells that have the ability to change into many different types of cells and grow indefinitely. They have the potential to create many new different cells that can help replace dying and/or damaged cells. .Progenitor cell can only hey are already more specific than stem cells and can only be pushed to differentiate into its "target" cell.

**Comment by bvarner-ebi** [comment]
Thanks for the feedback, @masciam.

>My only concern is that the hepatic progenitor cell term is only use in adult human terminology and refer to a rodent counter part (oval cell) that can only differentiate in 2 specific cell types and they are different from hepatic stem cell that derived from bone marrow.

These terms are not species restricted in the ontology, so I don't expect it should cause an issue. The few papers I scanned suggest only bipotency of hepatic progenitor cell, so that seems in line with oval cell. We won't call it 'hepatic stem cell', but I have seen 'hepatic stem/progenitor cell' used to seemingly refer to the progenitor cell.

>I have some concerns on the fact that in CL progenitor cell are parent of stem cell instead to be the reverse.

I don't see the relationship you noted above. Do you have a screen shot?
The equivalence axiom for 'progenitor cell' is:
```
'precursor cell'
 and ('develops from' some 'stem cell')
```

**Comment by masciam** [comment]
> Thanks for the feedback, @masciam.
> 
> > My only concern is that the hepatic progenitor cell term is only use in adult human terminology and refer to a rodent counter part (oval cell) that can only differentiate in 2 specific cell types and they are different from hepatic stem cell that derived from bone marrow.
> 
> These terms are not species restricted in the ontology, so I don't expect it should cause an issue. The few papers I scanned suggest only bipotency of hepatic progenitor cell, so that seems in line with oval cell. We won't call it 'hepatic stem cell', but I have seen 'hepatic stem/progenitor cell' used to seemingly refer to the progenitor cell.
> 
> > I have some concerns on the fact that in CL progenitor cell are parent of stem cell instead to be the reverse.
> 
> I don't see the relationship you noted above. Do you have a screen shot? The equivalence axiom for 'progenitor cell' is:
> 
> ```
> 'precursor cell'
>  and ('develops from' some 'stem cell')
> ``you are right  stem cell is not a child of progenitor, my mistake.  But hepatic oval cell is a child of stem cell not progenitor how we deal with that?  should the oval cell moved under progenitor cell? From the practical point the hepatic progenitor cell are the corresponding adult human of rodent oval cell so this should make the terms clearly synonyms . My first concern when I started this request is about the consistency with the hierarchy but if you do not se
e the issue here I am fine with having the synonym .

**Comment by bvarner-ebi** [comment]
@masciam, I think confusion may stem from (pun intended) how it has been referred to in papers, using both progenitor and stem in the terminology (see below).
In CL I see several classes with 'stem' in the label as sublclasses of 'progenitor cell', so we could consider moving 'hepatic oval stem cell' to a subclass under 'progenitor cell'. @dosumis, what do you think?

For reference, the text definition of 'hepatic oval stem cell' in CL is:
"A transient hepatic stem cell observed after liver injury with a high nuclear to cytoplasm ratio that can differentiate into mature hepatocytes and bile duct cells. Arises from more than one tissue."

CL definition of 'stem cell':
A relatively undifferentiated cell that retains the ability to divide and proliferate throughout life to provide progenitor cells that can differentiate into specialized cells.

CL definition of 'progenitor cell':
A precursor cell that has a tendency to differentiate into a specific type of cell. They are descendants of stem cells, only they are more constrained in their differentiation potential or capacity for self-renewal, and are often more limited in both senses.


In [PMID:17901986](https://pubmed.ncbi.nlm.nih.gov/17901986): "Hepatic **stem/progenitor** cells also known as "oval cells" in rodents have been implicated in liver tissue repair, ..."

In PMID:12468240 :"Bone marrow stem cells have recently been shown to be a potential source of the hepatic oval cells..."

In PMID:12468240, they put 'stem' inside quotes. 
Title of paper: **Hepatic oval 'stem' cell in liver regeneration** 
Text from paper: "Hepatic oval cells display a distinct phenotype and have been shown to be a bipotential progenitor of two types of epithelial cells found in the liver, hepatocytes and bile ductular cells."

**Comment by emquardokus** [comment]
1) The difference in terminology between adult hepatic progenitor cell and hepatic oval cell seems to be human vs rat.  From PMID: [28135758](https://pubmed.ncbi.nlm.nih.gov/28135758):
"In this scenario, adult hepatic stem/progenitor cells, termed hepatic progenitor cells (HPCs) in humans[4](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5534384/#R4) and oval cells in rodents,[5](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5534384/#R5) emerge and become activated.[6](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5534384/#R6),[7](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5534384/#R7)"
2) Stem cell vs progenitor cell are blurred into "stem/progenitor cell" in many source papers because they are talking about the transitional state from one to the other.

**Comment by masciam** [comment]
> @masciam, I think confusion may stem from (pun intended) how it has been referred to in papers, using both progenitor and stem in the terminology (see below). In CL I see several classes with 'stem' in the label as sublclasses of 'progenitor cell', so we could consider moving 'hepatic oval stem cell' to a subclass under 'progenitor cell'. @dosumis, what do you think? My question is- if we do that, would the parent class 'hepatic stem cell' also be moved under 'progenitor cell'?
> 
> For reference, the text definition of 'hepatic oval stem cell' in CL is: "A transient hepatic stem cell observed after liver injury with a high nuclear to cytoplasm ratio that can differentiate into mature hepatocytes and bile duct cells. Arises from more than one tissue."
> 
> CL definition of 'stem cell': "A relatively undifferentiated cell that retains the ability to divide and proliferate throughout life to provide progenitor cells that can differentiate into specialized cells."
> 
> CL definition of 'progenitor cell': "A precursor cell that has a tendency to differentiate into a specific type of cell. They are descendants of stem cells, only they are more constrained in their differentiation potential or capacity for self-renewal, and are often more limited in both senses."
> **_After looking at the different definitions that  Hepatic oval cell are progenitors. A different thing are the hepatic stem cell those can differentiate in several cell types as well as the Human liver stem cells (HLSC) that are different from the hepatic cell progenitor (the the human counterpart of oval cell in rat). https://pubmed.ncbi.nlm.nih.gov/33981703/_** 

-***_*_I agree on  
- move the hepatic oval cell under progenitor cell 
- make the hepatic progenitor cell a synonym of hepatic oval cell
- leave the hepatic stem cell under stem cell_** 

> From OLS:
> 
> ![Screenshot 2022-06-07 at 10 35 29](https://user-images.githubusercontent.com/95643797/172348244-57a6ebc1-2b88-4e1e-840e-ccff169bce3f.png)
> 
> In [PMID:17901986](https://pubmed.ncbi.nlm.nih.gov/17901986): "Hepatic **stem/progenitor** cells also known as "oval cells" in rodents have been implicated in liver tissue repair, ..."
> 
> In PMID:12468240 :"Bone marrow stem cells have recently been shown to be a potential source of the hepatic oval cells..."
> 
> In PMID:12468240, they put 'stem' inside quotes. Title of paper: **Hepatic oval 'stem' cell in liver regeneration** Text from paper: "Hepatic oval cells display a distinct phenotype and have been shown to be a bipotential progenitor of two types of epithelial cells found in the liver, hepatocytes and bile ductular cells."

**Comment by bvarner-ebi** [comment]
Proposal:

[ ] change the parent of CL:0002196 'hepatic oval stem cell' from 'hepatic stem cell' to 'progenitor cell'
[ ] add 'hepatic progenitor cell' as an exact synonym to 'hepatic oval stem cell'
[ ] do not edit 'hepatic stem cell'

**Comment by bvarner-ebi** [comment]
@masciam, the changes discussed above have been merged via PR #1625 and will be reflected in the next CL release.
Thank you for your contribution!

**Comment by masciam** [comment]
Thank you :)
