### ISSUE TITLE
Import kidney Uberon terms to CL to support new HubMAP CL terms

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1605]
As discussed in PR #1586, please:

- [ ] import the following Uberon terms to  CL:
 - UBERON:0005099 'short descending thin limb'
 - UBERON:0005100 'long descending thin limb'

- [ ] add the following subclass axioms in CL:
 - CL:4030012 EA: 'epithelial cell' and 'part of' some 'short descending thin limb' - CL:4030013 part_of some UBERON:0005100
 - CL:4030014 part_of some UBERON:0005100

**Comment by bvarner-ebi** [comment]
@shawntanzk, could you help with the import part of this request?

**Comment by shawntanzk** [comment]
@bvarner-ebi you should be able to do it with your new machine now :) why don't you try doing it and if you run into any issues, let me know
