### ISSUE TITLE
Retina paper as source for new CL terms

### ISSUE THREAD

**Issue by Wkt8** [obophenotype/cell-ontology#1606]
This is a paper being wrangled from the HCA Data Portal to CellxGene. The paper consists of retina tissues. The paper and it's gene expression matrices contain a number of free-text matrices which have no specific mapping in CL. 

Doi: [10.1016/j.cell.2020.08.013](https://doi.org/10.1016/j.cell.2020.08.013)
Spreadsheet containing mapping of free-text matrices to closest CL term: [Retina_cell_types.xlsx](https://github.com/obophenotype/cell-ontology/files/8796843/Retina_cell_types.xlsx)
Link to collection in cellxgene: [cellxgene](https://cellxgene.cziscience.com/collections/2f4c738f-e2f3-4553-9db2-0582a38ea4dc)

Tagging @bvarner-ebi

**Comment by bvarner-ebi** [comment]
@Wkt8, thank you for sharing your file on retina cell types.
I added it to the [New cell type triage workbook](https://docs.google.com/spreadsheets/d/1WTs7AFd4outzbr_w-ct6Us1F4owYUKzTG0C-nzh-0jQ/edit#gid=494641507). Please feel free to edit it.

If there are any particular high priority new cell types you would like to add to CL, please create new term requests.

**Comment by dosumis** [comment]
Some papers relevant to defining at lease some of these cell types coming from HubMap:  https://github.com/hubmapconsortium/ccf-validation-tools/blob/master/logs/new_cl_terms_Eye.tsv

@shawntanzk - Can you take a look at the paper (DOI in first comment)?  Some cell types in this paper may be too provisional for CL, but there also seems to be quite a lot of mapping to types identified in earlier papers that we don't yet have.

**Comment by shawntanzk** [comment]
Looks like theres a whole bunch of transcriptomics types mapped to known types but hidden: 

> In the adult retina, we detected all known neuronal cell classes as well as many subclasses and distinct cell types, such as rods, L/M (red/green) cones and S (blue) cones, two types of horizontal cells, ten types of bipolar cells in three major groups (rod bipolar, ON cone bipolar, and OFF cone bipolar), 17 types of amacrine cells including [glycinergic](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/glycinergic) types (e.g., AII amacrine cells, GJD2) and GABAergic types (e.g., starburst amacrine cells, SLC18A3), and five types of ganglion cells ([Figures 5](https://www.sciencedirect.com/science/article/pii/S0092867420310047?via%3Dihub#fig5)E, 5H, and [S3](https://www.sciencedirect.com/science/article/pii/S0092867420310047?via%3Dihub#figs3); [Table S2](https://www.sciencedirect.com/science/article/pii/S0092867420310047?via%3D

In this case I know that they have mapped a GABAergic amacrine type to starbust amacrine, but its not easily findable (table S2 doesn't have this information). Happy to download their data from cellxgene and see what annotations they have. 

For now, I would suggest that we just ensure that we have the cell types in fig 5G/the named cell types: 
![Screenshot 2022-09-29 at 11 33 49](https://user-images.githubusercontent.com/76212760/193009216-0f9074d4-95bb-4048-8975-54c5cf674109.png)

I see that @Wkt8 has basically listed these down in the excel sheet attached above - I think at least these cell types are "categorical" and safe to add to CL

**Comment by shawntanzk** [comment]
action items: 

- [ ] Add cell types from this list that aren't in CL - @bvarner-ebi 

AC_B - Amacrine cell,   GABAergic
AC_Y - Amacrine cell, Glycinergic
Ast - Astrocyte
CM - Choroidal melanocyte
CdBC - Cone ON bipolar cell   (depolarizing)
ChBC - Cone OFF bipolar cell   (hyperpolarizing)
END - Enothelial cell
FB - Fibroblast
GC - Ganglion cell
HC - Horizontal cell
MAST - Mast cell
MC - Mueller cell
MO - Monocyte
NK - Natural killer cell
PER - Pericyte
RBC - Rod bipolar cell
RPE - Retinal pigment epithelium
uG - Microglia

- [ ] Go through h5ad file to see if there's any other annotations for cell types that need to be added - @shawntanzk

**Comment by shawntanzk** [comment]
h5ad fill author_cell_type:

Fovea:
B cell
Mueller cell
OFF-bipolar cell
T cell
amacrine cell
astrocyte
cell_type
endothelial cell of vascular tree
fibroblast
microglial cell
monocyte
natural killer cell
pericyte cell
retina horizontal cell
retinal cone cell
retinal ganglion cell
retinal pigment epithelial cell
retinal rod cell
rod bipolar cell

Periphery:
Mueller cell
OFF-bipolar cell
ON-bipolar cell
T cell
amacrine cell
astrocyte
cell_type
endothelial cell of vascular tree
fibroblast
mast cell
melanocyte
microglial cell
monocyte
natural killer cell
pericyte cell
retina horizontal cell
retinal cone cell
retinal ganglion cell
retinal pigment epithelial cell
retinal rod cell
rod bipolar cell

**Comment by dosumis** [comment]
> In this case I know that they have mapped a GABAergic amacrine type to starbust amacrine, but its not easily findable 

Yeh - I had a quick look and couldn't track that down either.  Probably worth opening a second ticket to add these types.  Looks like there are some good general refs for retinal cell types in the intro.  Also found these by looking for Starburst in my library: 
![image](https://user-images.githubusercontent.com/112839/193030779-39314fef-fcaa-45f6-8461-96aa0fb8ffcb.png)

**Comment by addiehl** [comment]
Many of those cell types have been in CL for years, even since the beginning.

**Comment by bvarner-ebi** [comment]
@shawntanzk, thank you for extracting the terms. 

I consolidated the terms into the table below. None are exact matches to priority cell types from [the triaging worksheet](https://docs.google.com/spreadsheets/d/1WTs7AFd4outzbr_w-ct6Us1F4owYUKzTG0C-nzh-0jQ/edit#gid=0).

**If any of the terms below warrant a new class to be added to CL, kindly provide feedback.**

Cell Type from paper | closest CL IRI | CL label | Notes
-- | -- | -- | --
amacrine cell (fovea) | CL:0000561 | amacrine cell | CL term not specific to fovea or periphery
amacrine cell (periphery) | CL:0000561 | amacrine cell | CL term not specific to fovea or periphery
amacrine cell, GABAergic | CL:0000561 | amacrine cell | CL term not specific to neurotrasmitter
amacrine cell, glycinergic | CL:0000561 | amacrine cell | CL term not specific to neurotrasmitter
astrocyte | CL:0000127 | astrocyte |  
astrocyte (fovea) | CL:0000127 | astrocyte | CL term not specific to fovea or periphery
astrocyte (periphery) | CL:0000127 | astrocyte | CL term not specific to fovea or periphery
B cell (fovea) | CL:0000236 | B cell | CL term not specific to fovea or periphery
choroidal melanocyte | CL:4030000 | choroidal melanocyte | CL term defined to be part of some uvea
cone OFF bipolar cell (hyperpolarizing) | CL:0000750;CL:0000752 | OFF-bipolar cell;cone retinal bipolar cell |  
cone ON bipolar cell (depolarizing) | CL:0000749;CL:0000752 | ON-bipolar cell;cone retinal bipolar cell |  
endothelial cell of vascular tree (fovea) | CL:0002139 | endothelial cell of vascular tree | CL term not specific to fovea or periphery
endothelial cell of vascular tree (periphery) | CL:0002139 | endothelial cell of vascular tree | CL term not specific to fovea or periphery
endothelial cell | CL:0000115;CL:0002585 | endothelial cell;retinal blood vessel endothelial cell |  
fibroblast | CL:0000057 | fibroblast | CL term not specific to fovea or periphery
fibroblast (fovea) | CL:0000057 | fibroblast | CL term not specific to fovea or periphery
fibroblast (periphery) | CL:0000057 | fibroblast | CL term not specific to fovea or periphery
ganglion cell | CL:0000740 | retinal ganglion cell |  
horizontal cell | CL:0000745 | retina horizontal cell |  
mast cell | CL:0000097 | mast cell | absent in retina: https://www.sciencedirect.com/science/article/pii/S0002944015002606
mast cell (periphery) | CL:0000097 | mast cell | absent in retina: https://www.sciencedirect.com/science/article/pii/S0002944015002606
melanocyte (periphery) | CL:0000148 | melanocyte | CL term not specific to fovea or periphery
microglial cell | CL:0000129 | microglial cell | CL term not specific to fovea or periphery
microglial cell (fovea) | CL:0000129 | microglial cell | CL term not specific to fovea or periphery
microglial cell (periphery) | CL:0000129 | microglial cell | CL term not specific to fovea or periphery
monocyte | CL:0000576 | monocyte | CL term not specific to fovea or periphery
monocyte (fovea) | CL:0000576 | monocyte | CL term not specific to fovea or periphery
monocyte (periphery) | CL:0000576 | monocyte | CL term not specific to fovea or periphery
Mueller cell | CL:0000636 | Mueller cell | CL term not specific to fovea or periphery
Mueller cell (fovea) | CL:0000636 | Mueller cell | CL term not specific to fovea or periphery
Mueller cell (periphery) | CL:0000636 | Mueller cell | CL term not specific to fovea or periphery
natural killer cell | CL:0000623 | natural killer cell | CL term not specific to fovea or periphery
natural killer cell (fovea) | CL:0000623 | natural killer cell | CL term not specific to fovea or periphery
natural killer cell (periphery) | CL:0000623 | natural killer cell | CL term not specific to fovea or periphery
OFF-bipolar cell (fovea) | CL:0000750 | OFF-bipolar cell | CL term not specific to fovea or periphery
OFF-bipolar cell (periphery) | CL:0000750 | OFF-bipolar cell | CL term not specific to fovea or periphery
ON-bipolar cell (periphery) | CL:0000749 | CL:0000749 | CL term not specific to fovea or periphery
pericyte | CL:0000669;CL:0002575 | pericyte;central nervous system pericyte | CL term not specific to fovea or periphery
pericyte cell (fovea) | CL:0000669;CL:0002575 | pericyte;central nervous system pericyte | CL term not specific to fovea or periphery
pericyte cell (periphery) | CL:0000669;CL:0002575 | pericyte;central nervous system pericyte | CL term not specific to fovea or periphery
retina horizontal cell (fovea) | CL:0000745 | retina horizontal cell | CL term not specific to fovea or periphery
retina horizontal cell (periphery) | CL:0000745 | retina horizontal cell | CL term not specific to fovea or periphery
retinal cone cell (fovea) | CL:0000573 | retinal cone cell | CL term not specific to fovea or periphery
retinal cone cell (periphery) | CL:0000573 | retinal cone cell | CL term not specific to fovea or periphery
retinal ganglion cell (fovea) | CL:0000740 | retinal ganglion cell | CL term not specific to fovea or periphery
retinal ganglion cell (periphery) | CL:0000740 | retinal ganglion cell | CL term not specific to fovea or periphery
retinal pigment epithelial cell (fovea) | CL:0002586 | retinal pigment epithelial cell | CL term not specific to fovea or periphery
retinal pigment epithelial cell (periphery) | CL:0002586 | retinal pigment epithelial cell | CL term not specific to fovea or periphery
retinal pigment epithelium | UBERON:0001782 | pigmented layer of retina |  
retinal rod cell (fovea) | CL:0000604 | retinal rod cell | CL term not specific to fovea or periphery
retinal rod cell (periphery) | CL:0000604 | retinal rod cell | CL term not specific to fovea or periphery
rod bipolar cell | CL:0000751 | rod bipolar cell | CL term not specific to fovea or periphery
rod bipolar cell (fovea) | CL:0000751 | rod bipolar cell | CL term not specific to fovea or periphery
rod bipolar cell (periphery) | CL:0000751 | rod bipolar cell | CL term not specific to fovea or periphery
T cell (fovea) | CL:0000084 | T cell | CL term not specific to fovea or periphery
T cell (periphery) | CL:0000084 | T cell | CL term not specific to fovea or periphery

**Comment by lubianat** [comment]
By the way, organizing the new CL cell types in a MIRACL sheet seems a nice way of moving this forward. 
https://arxiv.org/abs/2204.09673

Example MIRACL sheet: 
https://docs.google.com/spreadsheets/d/1FBbarq3aCM3CUGd9oIOuYY5Sljzt2Pegl-sdx8OwbfI/edit

**Comment by lubianat** [comment]
And I'd argue while the terms might not be priority, I think all of them could be included.

**Comment by lubianat** [comment]
Also, as a note, I've curated many of those terms on Wikidata, and will likely include others in the list too. 

Here are all retinal cells on Wikidata: https://w.wiki/5p4a

**Comment by dosumis** [comment]
> Also, as a note, I've curated many of those terms on Wikidata, and will likely include others in the list too.
> Here are all retinal cells on Wikidata: https://w.wiki/5p4a

Cool.  Can we co-ordinate xrefs?

**Comment by bvarner-ebi** [comment]
Next step is to identify which of [these terms](https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1265503887) constitute new cell types. If there is no need to differentiate these cell types based on location (peripheral retina vs fovea), I do not see many/any new terms here.

**Comment by dosumis** [comment]
Should definitely add amacrine neurons by NT.

**Comment by dosumis** [comment]
I think also worth going back to older papers referenced here to find if we can defined things like 'starburst amacrine cells'

**Comment by dosumis** [comment]
@addiehl  - wasn't there also work in your group ages ago on defining types of retinal ganglion cell that never made it into CL.  Maybe worth a look?

**Comment by addiehl** [comment]
The retinal CL (RCL) file is attached
[RCL1v7_ds_test.owl.txt](https://github.com/obophenotype/cell-ontology/files/9789562/RCL1v7_ds_test.owl.txt)

This work was performed primarily by Terry Meehan and Patrick Ray @patrick-lloyd-ray under my direction when I had moved to the University at Buffalo, with some contributions from a couple of summer students who worked with me at the Jackson Laboratory.  This file contains 51 classes in the range CL:0003XXX for ganglion cells and 57 classes in the range CL:0004XXX for amacrine, bipolar, ganglion, and additional cell types.  33 of these cell types are based on BAMS. (these IDs have never been used in CL).

There are a number of UBERON terms referenced in logical definitions as well as 53 of the dreaded "CP" cellular phenotype terms.  I think there is a lot of good work in this file but it probably needs some revision/reengineering if parts of it were to be imported into CL.  I think a lot of the cell types are based on mouse, but Patrick probably knows better than me.

There are 29 types of amacrine cell, including:
'starburst amacrine cell' : "An amacrine cell with a flat dendritic arbor and a medium dendritic field. Starburst amacrine cells have post-synaptic terminals in S2."
Logical definition
'retinal amacrine cell'
 and (has_quality some 'medium dendritic field')
 and (has_post_synaptic_terminals_in some 'sublaminar layer S2')
 and (lacks_post_synaptic_terminals_in some 'sublaminar layer S1')
 and (lacks_post_synaptic_terminals_in some 'sublaminar layer S3')
 and (lacks_post_synaptic_terminals_in some 'sublaminar layer S4')
 and (lacks_post_synaptic_terminals_in some 'sublaminar layer S5')

There are 61 types of retinal ganglion cell in the file.

I don't have the time and knowledge myself to do more with this work right now, but someone with training in neuroscience who works on CL might be interested in seeing what can be used.
-- Alex

**Comment by dosumis** [comment]
I somehow didn't realise this was Patrick's work!  Makes sense for @shawntanzk and @patrick-lloyd-ray to work on folding this into CL.  From the above example, I think simplifying definitions would be worthwhile, e.g. I think we need to lose the negative assertions and probably relax the definition to just use subClassOf.

**Comment by shawntanzk** [comment]
Happy to look into it, just for coordination, I will start by extracting the CL:0004XXX terms in the file and merging it with cl-edit into an PR, and we can work on that branch till we are satisfied before merging to master :)

**Comment by shawntanzk** [comment]
ok take it back, its pretty messy when merging - for review sake, it would probably end up better to just manually add these in. Will take a closer look and see whats the best way to do that (template or individually)

**Comment by dosumis** [comment]
Where does the messiness of the merge come from? If IDs and imports, can this be cleaned up first?

**Comment by shawntanzk** [comment]
no idea, robot merge does some weird stuff. Anyway decided to convert to ofn and copy and paste the stuff in manually to edit, changing some of the relations as needed. Works well, will make a commit to branch and we can edit from there

**Comment by bvarner-ebi** [comment]
The following classes have been added to CL:

CL:4030027 ‘GABAergic amacrine cell’
CL:4030028 'glycinergic amacrine cell'

@shawntanzk, it does not look like either of these classes appear in #1713. I do not see an outlined list of the new cell types for that source. I can work on extracting the labels so it is clearly outlined for that PR.

To tidy up this ticket, I propose we focus discussion here on [this list](https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1265503887) and shift discussion about [the file](https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1279416308) @addiehl provided in a separate ticket.

@dosumis, are there any other cell types from [this list](https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1265503887) you believe warrant new classes? If not, I propose we close this ticket.

**Comment by shawntanzk** [comment]
> @shawntanzk, it does not look like either of these classes appear in https://github.com/obophenotype/cell-ontology/pull/1713. I do not see an outlined list of the new cell types for that source. I can work on extracting the labels so it is clearly outlined for that PR.

That is from the file from @addiehl so there isn't a list. Don't worry too much about generating a list for now, but if you need one, you can adapt the sparql query I added to that PR - the new terms are in fixed spaces so should be easy. 

>To tidy up this ticket, I propose we focus discussion here on https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1265503887 and shift discussion about https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1279416308 @addiehl provided in a separate ticket.

I agree, I just wanted to make sure no duplicates happen, more coordination between the two efforts than anything :)

**Comment by bvarner-ebi** [comment]
Closing this ticket as the obvious new cell types have been created.

@Wkt8, if you believe any other of [the extracted cell types](https://github.com/obophenotype/cell-ontology/issues/1606#issuecomment-1265503887) should be added, feel free to reopen or submit a new ticket.

Thanks, all, for the contributions.
