### ISSUE TITLE
endoderm/hepatic progenitor

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1610]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**hepatic progenitor

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**:Hepatic progenitor cells serve as the major component of the hepatic parenchyma in early stages of liver organogenesis [[8]](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2714184/#pone.0006468-Zaret1). Studies of mouse and human embryonic development indicate that they are common progenitors of mature hepatocytes and biliary epithelial cells, the lineage commitments of which are determined around the mid-gestation stage PMID: [19649295](https://pubmed.ncbi.nlm.nih.gov/19649295)

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**:embryonic stem cell - CL:0002322

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by bvarner-ebi** [comment]
@kalpanaps, thank you for the new term request.
Could you confirm that this is not a request for the same cell type as this:
https://github.com/obophenotype/cell-ontology/issues/1604

**Comment by kalpanaps** [comment]
@bvarner-ebi, my apologies - looks like both are the same type of cell; maybe the description what I added is more accurate

Thank you

**Comment by bvarner-ebi** [comment]
Thanks for checking, @kalpanaps. Kindly advise if you think the definition warrants an update or kindly close the ticket.
