### ISSUE TITLE
nurse cell

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1611]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Cells accessory to egg and/or sperm formation in a wide variety of organisms. Usually thought to synthesize special substances and to export these to the developing gamete (BTO:0000953)

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by dosumis** [comment]
@gouttegd can you look into relationship to FBbt nurse cell.  I think the key question is whether these are always germ cells.

**Comment by gouttegd** [comment]
@dosumis In FBbt, `nurse cell` is a subClassOf `female germline cell` and is defined as “one of a group of 15 germ cells that lie anterior to the oocyte within the egg chamber.” These cells are, indeed, always germ cells.

Of note, in CL we already have `invertebrate nurse cell` (CL:0000026), which is also a subClassOf `germ line cell` and is defined as “a germline cell that contributes to the development of the oocyte by transferring cytoplasm directly to oocyte“. That term is cross-referenced to FBbt’s `nurse cell`.

Do all “nurse cells” derive from the germline throughout species? Apparently not.

On one hand, germline-derived nurse cells have been described in insects (obviously), in nematodes, in hydra ([Alexandrova et al., 2005](https://doi.org/10.1016/j.ydbio.2005.02.015)); in mouse, non-oocyte-forming germline-derived cyst cells have been shown to transfer organelles to the oocyte, leading to them being called “nurselike germ cells“ ([Lei and Spradling, 2016](https://doi.org/10.1126/science.aad2156)).

On the other hand, reptiles, birds, and amphibians have “pyriform cells”, described by [del Pino (2021)](https://doi.org/10.1016/bs.ctdb.2020.10.008) as “nurse cells of somatic origin” which “enrich the oocyte with transcripts, proteins and organelles”.

Also in mammals, Sertoli cells are sometimes described as “nurse cells”, though most authors seem to use precautionary quotes (e.g., [França et al., 2016](https://doi.org/10.1111/andr.12165)) or talk of them as “cells that nurse the spermatogonia” or similar (e.g. [Petersen and Söder, 2006](https://doi.org/10.1159/000094142); [Wong and Kahn, 2021](https://www.ncbi.nlm.nih.gov/books/NBK560631/)) without calling them proper “nurse cells”.

Overall I am not sure there is a consensus in the literature as to which cells should be called “nurse cells”. Some authors seem to imply that “nurse cells” refers strictly to germline-derived cells (non-somatic cells with a similar function being called “nurse-like cells” or similar), while others have no qualms calling any cell that provides anything to a developing gamete a “nurse cell”, regardless of its origin.

Shall we have three terms:

* one for “any cell that supports the the development of a gamete by providing it any kind of substance”, regardless of origin;
  * one subterm for germline-derived cells (under which we could classify the existing `invertebrate nurse cell`);
  * one subterm for somatic cells (under which we could classify mammalian Sertoli cells and amphibian pyriform cells)

?

**Comment by dosumis** [comment]
> * one for “any cell that supports the the development of a gamete by providing it any kind of substance”, regardless of origin;
>    * one subterm for germline-derived cells (under which we could classify the existing invertebrate nurse cell);
>    * one subterm for somatic cells (under which we could classify mammalian Sertoli cells and amphibian pyriform cells)

I think that would be reasonable.  Perhaps you want some wiggle room with defining the parent class.  I'm sure there are a very large number of cell types that provide some substances to oocytes (e.g. circulating metabolites).  Could we perhaps have some restriction on the mode or directness of transport, or on the amount or type of material provided?

**Comment by gouttegd** [comment]
> Could we perhaps have some restriction on the mode or directness of transport, or on the amount or type of material provided?

I think what would make the most sense is to include in the definition the notion of transfert of cytoplasmic material (including organelles) by direct cross-membrane channels. This seems to be the common point across insect-type nurse cells proper, pyriform cells in birds/reptiles/frogs, and “nurselike cells” in mouse.

This would exclude cells that provide substances by a paracrine-like mechanism (e.g., secreting growth factors in the extracellular medium, that are then picked up by the gametes).

Not sure yet where Sertoli cells would fit. _A priori_ I think they would be excluded by such a definition, because my current understanding is that they “nurse” the spermatogonia solely by paracrine secretion and _not_ by direct cytoplasmic transfert. But I may be wrong on that count, I’ll have a closer look.
