### ISSUE TITLE
coelomocyte

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1612]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**:coelomocyte

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**:1: Corpuscles (usually amoebocytes) in the coelomic or pseudocoelomic fluids of invertebrates. 2:(Annelida) amoebocytes and elaeocytes. 3: (Echinodermata) The spindle-shaped cells, phagocytes, and crystal cells. 4: (Nematoda) The mesenchymatous cells in the body cavity - BTO:0002856.

Coelomocytes are a heterogeneous cell population that inhabit the coelomic cavity, or coelom, the main body cavity that radiates from each arm of a starfish. The coelomic cavity and organs located in it are lined with a ciliated epithelium (coelomic epithelium (CE)), which also extends into the lining of the dermal papulae:PMID: 33237478

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by emquardokus** [comment]
@kalpanaps exact match term already exists: [CL:0000421](http://purl.obolibrary.org/obo/CL_0000421)
