### ISSUE TITLE
synaptosome

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1613]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**:From cryopreserved human brain tissues, it is possible to isolate detached-and-resealed synaptic terminals termed synaptosomes, which remain metabolically and enzymatically active. PMID: 28733958(https://pubmed.ncbi.nlm.nih.gov/28733958)

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by emquardokus** [comment]
@kalpanaps these are cells though... they are a cell fraction of isolated synapses.

**Comment by dosumis** [comment]
Agree is useful term, but out of scope for CL.  Maybe try OBI?

**Comment by bvarner-ebi** [comment]
@kalpanaps, following the comments above, I think it is appropriate to close this issue for CL. Since the entity you want to represent is not a cell type, it is not a class that belongs in CL.
