### ISSUE TITLE
hemocyte

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1615]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:** hemocyte

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**:PMID:33995363 - The innate immune system of insects is divided into humoral defenses that include the production of soluble effector molecules (like antimicrobial peptides) and cellular defenses like phagocytosis and encapsulation that are mediated by hemocytes 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by bvarner-ebi** [comment]
@kalpanaps, thank you for the new term request.
Would this be a new, unique cell type, different from CL:0000387 'hemocyte (sensu Arthropoda)?

**Comment by kalpanaps** [comment]
Yes, they are not different. My apologies for creating new request

**Comment by bvarner-ebi** [comment]
Thank you for confirming, @kalpanaps. 
I will close this ticket.
