### ISSUE TITLE
arterial endothelial cell

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1616]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**arterial endothelial cell

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**:PMID:30412436 - Visit 2 occurred within 7 days of visit 1. A 20-gauge, 5-cm catheter (model RA-04020; Arrow, Reading, PA) was inserted into the radial artery of the right arm under aseptic conditions. Immediately after catheter insertion, a blood pressure cuff was placed to occlude the brachial artery and thus radial artery blood flow. 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**: 0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by emquardokus** [comment]
@kalpanaps this is exact synonym for endothelial cell of artery http://purl.obolibrary.org/obo/CL_1000413

**Comment by dosumis** [comment]
Please use term linked by @emquardokus
