### ISSUE TITLE
embryonic fibroblast

### ISSUE THREAD

**Issue by kalpanaps** [obophenotype/cell-ontology#1617]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**embryonic fibroblast

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Has a BTO X'ref - BTO:0004725

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**:0000-0003-2534-198X

**Any additional notes or concerns**

**Comment by emquardokus** [comment]
@kalpanaps term already exists: embryonic fibroblast http://purl.obolibrary.org/obo/CL_2000042
