### ISSUE TITLE
Create new GitHub issue template for new term requests coming in via cellxgene

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1627]
As discussed in recent cellxgene meeting, a template for new CL term requests coming in via cellxgene will be created. 

This template should contain the standard information for a CL new term request plus additional fields specific to cellxgene (@dosumis, can you confirm fields?) and a GitHub label for 'cellxgene'.

**Comment by dosumis** [comment]
I think minimal would be to just add the cellXGene label - maybe should also assign to you by default.  We could also add a bit about suggesting markers that uniquely identify the cell type (noting species).
