### ISSUE TITLE
Feedback on new CL home page

### ISSUE THREAD

**Issue by nlharris** [obophenotype/cell-ontology#1629]
As requested, here is my feedback on https://cell-ontology.github.io/. (I also emailed this to @dosumis on 2022-06-07.)

Overall, the page looks nice and clean. I like that it has minimal text. It could use more hyperlinks to make it easier to get to other information — see below for some specific suggestions.

The blue “Query” button goes to https://yasgui.triply.cc/#; I don’t understand what to do there, and didn’t see a link for instructions.

The icon bar (below) appears hyperlinked but doesn’t actually go anywhere.
<img width="657" alt="Screen Shot 2022-06-07 at 4 37 43 PM" src="https://user-images.githubusercontent.com/348704/173685500-b8f5ea37-d229-4d10-bf5b-d86aeb3a0823.png">

> The Cell Ontology is built on FAIR principles and interoperates well with other ontologies. It works in concert with the multi-species anatomy ontology UBERON, and is used as the reference ontology for cell types in the Gene Ontology (GO).

this could use hyperlinks for “FAIR principles” “UBERON” (shouldn’t that be Uberon?) and GO.

> The Cell Ontology actively engages the community, editors from multiple projects embeded in the team, active and responsive discussions in the issue tracker, and constant improvements both in content and technical development of the ontology.

…community, with editors…
(the addition of “with” will help the sentence make more sense).
embeded -> embedded

> The Cell Ontology is also integrated into tools used by the community such as Ubergraph and the Ontology Access Kit (OAK), and is uploaded into popular ontology browsers such as the Ontology Lookup Service (OLS) and Ontobee.

add links to uber graph, oak, ols, ontobee

> The Cell Ontology is released in multiple standard formats to be compatible with releases done in owl (RDF/XML), obo, and json format. 

I don’t really understand “releases done in owl” etc. I may have this wrong but could this sentence be simplified to
"The Cell Ontology is released in multiple standard formats including owl (RDF/XML), obo, and json." or "Releases are available in standard formats including owl (RDF/XML), obo, and json." ?

> It also comes in multiple variants including full (all imports merged in, and classified using a reasoner), base (only axioms belonging to the ontology), and simple (a subset of the ontology useful for tool development), all of which are openly accessible in our GitHub page.

I would change “openly accessible in our GitHub page” to “accessible from GitHub” with GitHub hyperlinked.

> We'd love to hear from You

You -> you

> You can also directly contact an editor from the list below

I mean, not really, since all that’s listed in that linked list (which says Uberon at the top) is handles (@) for some but not all editors. The handles are not hyperlinked, and it’s unclear whether they are GitHub or Slack handles.

Overall, nice work!

**Comment by shawntanzk** [comment]
moved to https://github.com/cell-ontology/cell-ontology.github.io/issues/12
