### ISSUE TITLE
Is CL:0002148 'dental pulp cell' a stem cell?

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#1635]
Dear CL editors,
I was going to request a new subclass (or descendant) of CL:0000034 'stem cell', namely 'dental pulp stem cell', based on this biomedically-relevant fact and potential usefulness for human-focused studies: "Human dental pulp stem cells (hDPSCs) are some of the most promising stem cell types for regenerative therapies given their ability to grow in the absence of serum and their realistic possibility to be used in autologous grafts." (PMID: 33805573)

However, is this the same as the existing term CL:0002148 'dental pulp cell', based on its definition ref PMID: 11087820 saying "Postnatal human dental pulp _stem_ cells (DPSCs) in vitro and in vivo"? If yes, please consider editing the existing term accordingly. The xref'd FMA term doesn't mention stem explicitly. The BTO xref is a tissue, not a cell type, so not sure if it's strictly ok as dbxref/mapping.

If CL:0002148 'dental pulp cell' does not refer to a stem cell instead, would you please consider creating 'dental pulp stem cell'?
With synonym "DPSC" [exact, with AP 'abbreviation']
part_of some 'dental pulp'
https://orcid.org/0000-0002-2825-0621

Thank you,
Paola

**Comment by dosumis** [comment]
Hi @bvarner-ebi  - do you want to tackle this.  The existing term looks a mess.

**Comment by paola-scibite** [comment]
@bvarner-ebi @dosumis thank you both.

**Comment by bvarner-ebi** [comment]
Hi, @paola-scibite, and FYI to @wdduncan (who is working on tooth-related terms in Uberon),

Kindly see my proposal below. I will appreciate your feedback.

Regarding [CL:0002148 ‘dental pulp cell’](http://purl.obolibrary.org/obo/CL_0002148):

[ ] keep CL:0002148 ‘dental pulp cell’ as a general category for the heterogeneous cell populations located in the dental pulp: odontoblasts, fibroblasts, mesenchymal cells, etc. 
[ ] remove the BTO cross reference as this refers to tissue, not a cell type
[ ] cannot find CALOHA reference **(remove or keep this reference?)**
[ ] replace current PMID reference with [PMID:36267574](https://pubmed.ncbi.nlm.nih.gov/36267574)
[ ] restrict to human? 

[ ] create new class ‘dental pulp stem cell’ as follows

**Preferred term label**
‘dental pulp stem cell’

**Synonyms** (add reference(s), please)
DPSC (exact, abbreviation, [PMID:11087820](https://pubmed.ncbi.nlm.nih.gov/11087820/), [PMID:11087820](https://pubmed.ncbi.nlm.nih.gov/11087820))

**Definition**
A dental pulp cell that possesses stem-cell-like qualities, including self-renewal capability and multi-lineage differentiation.
DOI:[10.1177/154405910208100806](http://dx.doi.org/10.1177/154405910208100806)

**Parent cell type term**
CL:0002148 ‘dental pulp cell’
CL:0000034 ‘stem cell’

**What is the anatomical structure that the cell is a part of?**
part_of some 'dental pulp'

**Your ORCID**
https://orcid.org/0000-0002-2825-0621

**Comment by paola-scibite** [comment]
Hi @bvarner-ebi,

Thank you for looking into this. I'm on leave this week, but I have a reminder so I won't forget. 

Happy New Year!

**Comment by paola-scibite** [comment]
@bvarner-ebi
Hi again. Your proposal sounds good to me. 
Re. "cannot find CALOHA reference (remove or keep this reference?)": the CALOHA xref work was carried out by Chris Mungall a long time ago, so the historical knowledge is with him. I'd keep the reference. 
Re. "restrict to human?": I'll leave that to you and/or @wdduncan.
Thanks!

**Comment by wdduncan** [comment]
At the present moment, I don't see a need for human specific classes of dental pulp. Dental procedures that involve dental pulp (e.g., root canal treatments) reference the tooth that contained the dental pulp, and not some specific type of dental pulp. In the future, perhaps I may encounter translational research in which it is important to distinguish dental pulp in a rat from dental pulp in a human. But, let's cross that bridge if/when we get there ...

**Comment by bvarner-ebi** [comment]
@paola-scibite, thank you for this ticket. 

The edits mentioned above have been made (see associated ticket and PR), including the addition of the new term:

CL:4030035 'dental pulp stem cell'

@wdduncan, if you have additional suggestions for edits, please message me and/or create a CL ticket. 

Thank you both for the feedback.

**Comment by paola-scibite** [comment]
@bvarner-ebi thank you for your work!
