### ISSUE TITLE
[Typo/Bug] 'gall bladder' should be 'gallbladder'

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1658]
**CL term**
Several, see below.

**Description of typo, bug or error**
As noted [here](https://github.com/obophenotype/uberon/pull/2570#pullrequestreview-1037362968), 'gall bladder' (two words) appears in several ontology terms. It inconsistently appears in the ontologies as one and two words. For CL, examples are:

CL:1001592 'gall bladder glandular cell'
CL:200069 'gallbladder fibroblast'

There are no common resources that I found that support the usage of the term split into two words, suggesting 'gall bladder' is a typo.

As a fix:
- [x] Update all CL refs:labels to 'gallbladder' where 'gall bladder' is present
- [x] Add 'gall bladder' as as an exact synonym (gall bladder is a synonym in FMA- see below)
- [x] Add to next CL/UBERON meeting agenda to discuss how to handle historical typos such as this. Should a term that includes a typo appear as a synonym?
- [x] @shawntanzk to fix instances in UBERON https://github.com/obophenotype/uberon/pull/2570
- [x] Create a GO ticket to recommend they update GO terms accordingly
DONE: https://github.com/geneontology/go-ontology/issues/23695

**Comment by raymond91125** [comment]
FMA http://purl.org/sig/ont/fma/fma7202 "Gall bladder" is a synonym.

**Comment by raymond91125** [comment]
All mentioning of "gall bladder" has been changed to "gallbladder" in GO, except in logical def (UBERON term). Thanks for the heads up.

**Comment by shawntanzk** [comment]
> FMA http://purl.org/sig/ont/fma/fma7202 "Gall bladder" is a synonym.

@bvarner-ebi - if FMA uses it as a synonym, we should defs add/leave it in the ontology

**Comment by bvarner-ebi** [comment]
> FMA http://purl.org/sig/ont/fma/fma7202 "Gall bladder" is a synonym.

Thank you for pointing this out. Is FMA actively maintained?

**Comment by bvarner-ebi** [comment]
Note that the source of using 'gall bladder' is reportedly Stedman's Electronic Medical Dictionary v5.0 2000 (http://fma.si.washington.edu/browser/#/?iri=http%3A%2F%2Fpurl.org%2Fsig%2Font%2Ffma%2Ffma7202).
Trying to get access to this text to confirm.
