### ISSUE TITLE
[Typo/Bug] circularity in cl.obo data-version: releases/2022-06-18 CHEBI:36080 and PR:000000001

### ISSUE THREAD

**Issue by vjcitn** [obophenotype/cell-ontology#1672]
**CL term**

CHEBI:36080, PR:000000001 are `is_a` to each other in cl.obo of 2022-06-18

**Description of typo, bug or error**

line 7408 of cl.obo
```
[Term]
id: CHEBI:36080
name: protein
namespace: chebi_ontology
alt_id: CHEBI:13677
alt_id: CHEBI:14911
def: "A biological macromolecule minimally consisting of one polypeptide chain synthesized at the ribosome." [] 
subset: 3_STAR 
synonym: "proteins" EXACT IUPAC_NAME [IUPAC]
is_a: PR:000000001 ! protein
equivalent_to: PR:000000001 ! protein
```

at line 156886 we have stanza for
```
id: PR:000000001
```
that includes at line 156893
```
is_a: CHEBI:36080 ! protein
```
Observed by Daniel Greene author of the ontologyX packages on CRAN.  This circularity defeats `get_OBO` in ontologyIndex.  @stankiewicz565

**Comment by cmungall** [comment]
Hi Vince,

While this is indeed strange and unintuitive, it is valid. Equivalence is the same as mutual subsumption. Ideally CHEBI and PRO would come to some agreement about who owns the concept of protein but they have not done this in >10 years so this is where we are.

We have a profile of OBO Format intended for tools like ontologyX called obo-basic

Documentation:
https://owlcollab.github.io/oboformat/doc/obo-syntax.html#6.2

cl-basic release:

http://purl.obolibrary.org/obo/cl/cl-basic.obo

If you consume this, then ontologyX should work. However, you will not get part-ofs to uberon or other inter-ontology links

There is an open issue about what to do with equivalence/reciprocal is-as here:
https://github.com/ontodev/robot/issues/956

I am interested in having a discussion with the ontologyX developers to get it such that the full obo format spec is supported. You may be interested in adopting patterns from OAK: https://incatools.github.io/ontology-access-kit

**Comment by bvarner-ebi** [comment]
Closing this ticket given @cmungall's comment above.
@vjcitn, feel free to add follow-up comments if needed.
