### ISSUE TITLE
[Synonym] add M1, M2 macrophage as synonym

### ISSUE THREAD

**Issue by LiNiMGI** [obophenotype/cell-ontology#1680]
**CL term**
 alternatively activated macrophage CL:0000890

**Synonym to be added**
  M2 macrophage

**broad/exact/narrow/related ?**
 exact

**CL term**
     inflammatory macrophage CL:0000863

**Synonym to be added**
  M1 macrophage

**broad/exact/narrow/related ?**
 exact

**Comment by bvarner-ebi** [comment]
@LiNiMGI, thank you the contribution to CL.

Could you kindly add references that support adding these terms as exact synonyms?

**Comment by addiehl** [comment]
You can use this review article as a reference:
"M1 Means Kill; M2 Means Heal"  J. Immunol. 2017 Oct 1;199(7):2191-2193.  doi:10.4049/jimmunol.1701135. [PMID:28923980](https://pubmed.ncbi.nlm.nih.gov/28923980/)

**Comment by bvarner-ebi** [comment]
Thank you, @addiehl.

Based on this line in the reference, should these be "related" synonyms, and not "exact" or new cell types altogether?

[PMID:28923980](https://pubmed.ncbi.nlm.nih.gov/28923980/):
"Today, M1 is often used for classically activated macrophages ([16](https://www.jimmunol.org/content/199/7/2191.long#ref-16)) and M2 for alternatively activated macrophages ([17](https://www.jimmunol.org/content/199/7/2191.long#ref-17)). Although there are similarities in phenotype, this use of the M1/M2 nomenclature is incorrect: unlike classically activated macrophages, M1 polarization does not require IFN-γ, and unlike alternatively activated macrophages, M2 polarization does not require IL-4."

"Although there are similarities between M2 macrophages and alternatively activated (by IL-4) macrophages ([31](https://www.jimmunol.org/content/199/7/2191.long#ref-31)), they are not the same. No IL-4 is found in healing wounds ([32](https://www.jimmunol.org/content/199/7/2191.long#ref-32)). Similarly, it is well known that LPS is sufficient to induce an M1 phenotype, and T cell–derived IFN-γ, the hallmark of classical macrophage activation ([16](https://www.jimmunol.org/content/199/7/2191.long#ref-16)), is not required. Thus, classically activated macrophages are an amplified (by IFN-γ) version of M1 macrophages, but in the primary immune response, macrophages instruct T cells."

**Comment by addiehl** [comment]
I think related synonyms might be sufficient for now. We clearly need to either read more or get advice from a macrophage expert.

**Comment by bvarner-ebi** [comment]
@Thank you, @addiehl. 
The terms are already related synonyms for these terms. I'll add the reference as an annotation to them.

**Comment by bvarner-ebi** [comment]
@LiNiMGI, these terms have been kept as **related** synonyms.
I added dbxref annotations to them.
Kindly open a new ticket if you would like to request additional changes.

**Comment by ANiknejad** [comment]
https://pubmed.ncbi.nlm.nih.gov/37530555/
