### ISSUE TITLE
vocload synonyms encased in apostrophes[

### ISSUE THREAD

**Issue by hdrabkin** [obophenotype/cell-ontology#1690]
These synonyms have an extra apostrophe which are giving grief to our loader at MGI.

Can you please fix? Thanks
 
synonym: "Langerhans' cell" EXACT []
synonym: "Langhans' cell" EXACT []
synonym: "Bm2' B lymphocyte" EXACT []
synonym: "Bm2' B-cell" EXACT []
synonym: "Fr. C'" BROAD []
synonym: "'T-shaped' Martinotti neuron" EXACT []
synonym: "'fanning-out' Martinotti neuron" EXACT []
synonym: "'CAP1'" BROAD []
synonym: "'capillary 1 cell'" BROAD []
synonym: "'gCAP'" BROAD [PMID:33057196]
synonym: "'general capillary cell'" BROAD [PMID:33057196]

**Comment by bvarner-ebi** [comment]
Thank you for this ticket, @hdrabkin.
My proposed edits are below.

synonym: "Langerhans' cell" EXACT []
[ ] Remove apostrophe. Use of the apostrophe is not correct. I only have found it used here: https://www.gosh.nhs.uk/conditions-and-treatments/conditions-we-treat/langerhans-cell-histiocytosis/

synonym: "Langhans' cell" EXACT []
[ ] Remove synonym. Improper use of the apostrophe aside, I do not think this term refers to the cell type described in the definition.

See also https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(03)14323-1/fulltext regarding the first two cells.

synonym: "Bm2' B lymphocyte" EXACT []
synonym: "Bm2' B-cell" EXACT []
[ ] Keep apostrophe. These appear to be valid uses of the apostrophe (to represent "prime").
https://link.springer.com/article/10.1007/s12016-007-8000-y

synonym: "Fr. C'" BROAD []
[ ] Keep apostrophe. Although I don’t see this form of the synonym (with apostrophe) used in the dbxref of the term, an apostrophe is sometimes used to stand for “prime”.

synonym: "'T-shaped' Martinotti neuron" EXACT []
synonym: "'fanning-out' Martinotti neuron" EXACT []
[ ] Remove apostrophes. These seem redundant and presence or absence would not impact the meaning of the term.
Thoughts @shawntanzk ?

synonym: "'CAP1'" BROAD []
synonym: "'capillary 1 cell'" BROAD []
synonym: "'gCAP'" BROAD [PMID:33057196]
synonym: "'general capillary cell'" BROAD [PMID:33057196]
[ ] Remove apostrophes. These seem redundant and presence or absence would not impact the meaning of the term.

**Comment by shawntanzk** [comment]
I'm ok with having my terms apostrophes removed - added them as it was probably how the paper used it, don't think removal would affect much on our side. Thanks

**Comment by dosumis** [comment]
Commenting late, but looks good.  @hdrabkin  - we can't promise to always keep apostrophes out of synonyms where these are valid/important.  I think MGI needs to look at fixing their loader.

**Comment by hdrabkin** [comment]
@dosumis, I think it was the double quotes around the synonym that is the problem.
