### ISSUE TITLE
NTR: Koniocellular cell

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#17]
```
See:

http://en.wikipedia.org/wiki/Koniocellular_cells
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 12 Feb 2013 at 1:08

**Comment by addiehl** [comment]
Still not in CL.  per the neuron folks, is this needed? @dosumis

**Comment by bvarner-ebi** [comment]
fyi @shawntanzk

**Comment by shawntanzk** [comment]
I'll handle it, thanks

**Comment by dosumis** [comment]
Wow - that's an old one!  Might be worth folding into discussion of import from existing resources (BAMS; NPO).  Should at least check whether they have these.

**Comment by shawntanzk** [comment]
Term not in BAMS
but here in NPO https://github.com/SciCrunch/NIF-Ontology/blob/fb72fda56484f1c9443416ee7da6477331b68145/ttl/NIF-Cell.ttl#L297
I will add the term and add a dbxref to NIFEXT:44

**Comment by dosumis** [comment]
(Broader context - worth mentioning in discussion with @tgbugs about mapping from NPO.  Is this a CUT - & if not should we be mapping more broadly.  Also need a strategy for developing SSSOM mapping & some thought about how we might use these in construction of unified knowledge bases).

**Comment by tgbugs** [comment]
Just an FYI. NIF-Cell only partially overlaps with NPO, it is couple if iterations older, but we do reuse the ids in a number of cases.
