### ISSUE TITLE
Clean upper level in cl.owl (release) a bit

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#1707]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/7070631/191458675-a08bf27e-a794-4760-909e-def5799af5d2.png">

We should probably add these to the list of excluded ID spaces in cl-odk.yaml.

**Comment by anitacaron** [comment]
This was done in [this commit](https://github.com/obophenotype/cell-ontology/commit/824ae7d9d7f6c2325936bdfdd763e1412a7c80ca).
