### ISSUE TITLE
[NTR]perineurial cell

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#1726]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label**
perineurial cell

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A cell that belongs to the supporting tissue surrounding a nerve fiber bundle. It has thin long bipolar cytoplasmic processes, pinocytotic vesicles, fragments of external lamina and/or external lamina-like material, attachment plaques, and desmosome-like junctions. [ NCI ] 

NCIT:C41442 http://purl.obolibrary.org/obo/NCIT_C41442

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
perineural cell http://purl.obolibrary.org/obo/CL_0002576
based on placement in NCIT perineural cell http://purl.obolibrary.org/obo/NCIT_C41416

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
perineurium 

**Your ORCID**
0000-0001-7655-4833

**Additional notes or concerns**
HuBMAP Skin ASCT+B table term

**Comment by bvarner-ebi** [comment]
@emquardokus provided review article [PMID:36244793](https://pubmed.ncbi.nlm.nih.gov/36244793/), which states:

"Previous studies—including this one— largely accept the idea that the perineurial cell is a modified fibroblast with myofibroblastic features (Bunge et al. 1989; Vega et al. 1996; Du Plessis et al. 1997)."

I do not think this justifies the EA:

```
 'myofibroblast cell'
 and ('part of' some perineurium)
```
Looking forward to additional input on this and the proposed next steps above.

**Comment by bvarner-ebi** [comment]
Hi @emquardokus, @dosumis, any additional thoughts on the proposed next steps above?

**Comment by bvarner-ebi** [comment]
@emquardokus, thank you for this term request.

As commented above, the class CL:0002576 'perineurial cell' has been updated.
