### ISSUE TITLE
[NTR]retinal ganglion specific cell type: midget ganglion cell of retina

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#1728]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label**
midget ganglion cell of retina

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
PMID: 32533915, PMCID: PMC7442669, Soto, Florentina, Jen-Chun Hsiang, Rithwick Rajagopal, Kisha Piggott, George J. Harocopos, Steven M. Couch, Philip Custer, Josh L. Morgan, and Daniel Kerschensteiner. “Efficient Coding by Midget and Parasol Ganglion Cells in the Human Retina.” Neuron 107, no. 4 (August 19, 2020): 656-666.e5. https://doi.org/10.1016/j.neuron.2020.05.030.

https://en.wikipedia.org/wiki/Midget_cell

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
retinal ganglion cell http://purl.obolibrary.org/obo/CL_0000740

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
Retina UBERON:0000966

**Your ORCID**
0000-0001-7655-4833

**Additional notes or concerns**
Exists in FMA as Midget ganglion cell of retina , FMA:62360

NOTE: there are midget bipolar cells of retina and midget ganglion cells of retina and they are not the same: 
Midget bipolar cells (imb, fmb) have larger axon terminals at greater distances from the fovea (retinal eccentricity of 4.5mm as compared to 12 mm). Midget ganglion cells (MGC) have larger dendritic fields (here seen at 8 mm) as they increase in eccentricity.

Related closed issue in CL: https://github.com/obophenotype/cell-ontology/issues/1606

**Comment by shawntanzk** [comment]
Related to https://github.com/obophenotype/cell-ontology/pull/1713
