### ISSUE TITLE
[NTR] valve interstitial cell (heart)

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#1736]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label**
valve interstitial cell

**Synonyms** (add reference(s), please)
VIC
cardiac valve interstitial cell

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

Ayoub, Salma, Chung-Hao Lee, Kathryn H. Driesbaugh, Wanda Anselmo, Connor T. Hughes, Giovanni Ferrari, Robert C. Gorman, Joseph H. Gorman, and Michael S. Sacks. “Regulation of Valve Interstitial Cell Homeostasis by Mechanical Deformation: Implications for Heart Valve Disease and Surgical Repair.” Journal of The Royal Society Interface 14, no. 135 (October 31, 2017): 20170580. https://doi.org/10.1098/rsif.2017.0580. (Table 1. Key Studies With Original Methodology Revealing Important Properties of Isolated, Cultured VICs)

Liu, Amber C, Vineet R Joag, and Avrum I Gotlieb. “The Emerging Role of Valve Interstitial Cell Phenotypes in Regulating Heart Valve Pathobiology.” The American Journal of Pathology 171, no. 5 (November 2007): 1407–18. https://doi.org/10.2353/ajpath.2007.070251.

Rutkovskiy, Arkady, Anna Malashicheva, Gareth Sullivan, Maria Bogdanova, Anna Kostareva, Kåre‐Olav Stensløkken, Arnt Fiane, and Jarle Vaage. “Valve Interstitial Cells: The Key to Understanding the Pathophysiology of Heart Valve Calcification.” Journal of the American Heart Association 6, no. 9 (n.d.): e006339. https://doi.org/10.1161/JAHA.117.006339.

This paper refers to them as "fibroblast-like"
Xu, Kang, Shangbo Xie, Yuming Huang, Tingwen Zhou, Ming Liu, Peng Zhu, Chunli Wang, et al. “Cell-Type Transcriptome Atlas of Human Aortic Valves Reveal Cell Heterogeneity and Endothelial to Mesenchymal Transition Involved in Calcific Aortic Valve Disease.” Arteriosclerosis, Thrombosis, and Vascular Biology 40, no. 12 (December 1, 2020): 2910–21. https://doi.org/10.1161/ATVBAHA.120.314789.

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
It's unclear where this should live exactly.
There is no "interstitial cell" in CL; there are some types of interstitial cells specific to some organs under "columnar/cuboidal epithelial cell" CL:0000075 http://purl.obolibrary.org/obo/CL_0000075 ; however, I'm not certain of the histology yet for valve interstitial cell of heart.
See above reference "This paper https://doi.org/10.1161/ATVBAHA.120.314789 refers to them as "fibroblast-like"

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
aortic valve of heart

**Your ORCID**
https://orcid.org/0000-0001-7655-4833

**Additional notes or concerns**
Unsure of parent term in CL; cardiac valve interstitial cells referred to as "fibroblast-like"- CL does not have "interstitial cell" per se.

**Comment by dosumis** [comment]
> There is no "interstitial cell" in CL;

There probably should be.  I think 'mesenchymal cell' is often used for this.

> there are some types of interstitial cells specific to some organs under "columnar/cuboidal epithelial cell"

That sounds wrong to me.

**Comment by bvarner-ebi** [comment]
Proposed modelling, fyi @emquardokus ....

**Preferred term label** 
valve interstitial cell

**Synonyms**
 VIC [PMID:25311230](https://pubmed.ncbi.nlm.nih.gov/25311230), [PMID:30796046](https://pubmed.ncbi.nlm.nih.gov/30796046))
valvular interstitial cell ([PMID:25311230](https://pubmed.ncbi.nlm.nih.gov/25311230))
cardiac valve interstitial cell (PMID: 16456103)

**Definition**
A cardiac valve cell that resides in a valve leaflet.    Along with valve endothelial cells, a valve interstitial cell maintains tissue homeostasis for the function of cardiac valves through secreting biochemical signals, matrix proteins and matrix remodeling enzymes.
[PMID:25311230](https://pubmed.ncbi.nlm.nih.gov/25311230)
https://doi.org/10.1098/rsif.2017.0580
https://doi.org/10.2353/ajpath.2007.070251
https://doi.org/10.1161/JAHA.117.006339
https://doi.org/10.1161/ATVBAHA.120.314789

**Comment**
Activated valve interstitial cells undergo continual turn over into deactivated fibroblasts and other cell fates (such as apoptosis). [PMID:25311230](https://pubmed.ncbi.nlm.nih.gov/25311230)

**Parent cell type term** 
 CL:1000147 'cardiac valve cell'
CL:4030031 ‘interstitial cell’

**What is the anatomical structure that the cell is a part of?**
UBERON:0000946 'cardiac valve'

**Your ORCID** 
https://orcid.org/0000-0001-7655-4833

**Comment by dosumis** [comment]
Looks good.  I would infer classification under  CL:1000147 'cardiac valve cell' from logical definition of 'cardiac valve cell' (cell and part_of some cardiac valve)

Also consider adding capable_of some extracellular matrix constituent secretion (GO)

**Comment by bvarner-ebi** [comment]
@emquardokus, thank you again for the new term.

The following has been added to CL and will be available in the next release:

CL:4030032 'valve interstitial cell'
