### ISSUE TITLE
Update diff to use base plus with new ODK

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1737]
Reminder ticket to update automated diff to use base plus once that is ready with next ODK release

**Comment by anitacaron** [comment]
Base plus is still not available.

**Comment by gouttegd** [comment]
Unless I missed something, “base plus“ artefacts _are_ available now?

@matentzn (or anyone who followed the base-plus saga, really): Is the following correct?

1. Prior to ODK 1.4, the ODK only provided an artefact called `-base`, which was basically the `-edit` file, as in “the ontology as it is edited by its editors“ (with no imports and no reasoning).
2. The “base-plus” proposition was to add a new artefact that would contain all axioms that are “about” a term defined in the ontology (including inferred axioms); that is, no longer merely the contents of the `-edit` file, but the result of the fully processed ontology from which axioms about “foreign“ terms are forcibly removed.
3. In ODK 1.5, what was actually implemented was that the `-base` artefact is now what was envisioned as “base-plus” (https://github.com/INCATools/ontology-development-kit/pull/810), while a new artefact called “baselite” (optional, not generated by default) corresponds to what used to be “base” (that is, the `-edit` file without reasoning).

**Comment by matentzn** [comment]
Correct, unless cl.Makefile does not overwrite cl-base.owl, cl-base.owl is now what we referred to back in 2023 "base plus"
