### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1739]
Might be a good idea to have a PR template 
that way we can add instructions for actions that require trigger there too
Probably needs discussion with community - @bvarner-ebi could you make sure this gets discussed in next CL call please? Thanks

**Comment by bvarner-ebi** [comment]
Hi, @shawntanzk, you are welcome to add points of discussion to the CL agenda: https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit#
