### ISSUE TITLE
Add cell types from transcriptomic of adult human brain

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1743]
https://www.biorxiv.org/content/10.1101/2022.10.12.511898v1.full.pdf

We need to add the superclasses 
Some already are in CL 
Need to read to ensure that they can be added in CL rather than PCL too.

**Comment by shawntanzk** [comment]
```
Each was
manually annotated based on the literature and their
regional composition (Table S2) with one exception, a
supercluster that contained neurons from most brain
regions. In the tradition of naming neurons for their
shapes, we named them splatter neurons based on their
appearance on the two-dimensional embedding. Each
supercluster was separately reanalyzed, resulting in a final
set of 461 clusters. A dendrogram of these clusters mirrored
previous work in the mouse: neurons split separately from
non-neuronal cells and into two clades (Fig. 1C) (1). One
clade contained telencephalic excitatory neurons that
express glutamatergic genes like SLC17A6 and SLC17A7.
The other contained telencephalic inhibitory neurons
that express GABAergic genes like SLC32A1, as well as
all excitatory and inhibitory diencephalic, midbrain,
and hindbrain neurons. We additionally analyzed each
cluster separately to produce a more detailed but less
robust clustering that contained 3313 clusters, which we
subsequently refer to as “subclusters” (Fig. 1C).
```

**Comment by shawntanzk** [comment]
- [ ] Amygdala excitatory
- [ ] Astrocyte
- [ ] Bergmann glia
- [ ] CGE interneuron
- [ ] Cerebellar inhibitory
- [ ] Choroid plexus
- [ ] Committed oligodendrocyte precursor
- [ ] Deep-layer corticothalamic and 6b
- [ ] Deep-layer intratelencephalic
- [ ] Deep-layer near-projecting
- [ ] Eccentric medium spiny neuron
- [ ] Ependymal
- [ ] Fibroblast
- [ ] Hippocampal CA1-3
- [ ] Hippocampal CA4
- [ ] Hippocampal dentate gyrus
- [ ] LAMP5-LHX6 and Chandelier
- [ ] Lower rhombic lip
- [ ] MGE interneuron
- [ ] Mammillary body
- [ ] Medium spiny neuron
- [ ] Microglia
- [ ] Midbrain-derived inhibitory
- [ ] Miscellaneous
- [ ] Oligodendrocyte
- [ ] Oligodendrocyte precursor
- [ ] Splatter
- [ ] Supercluster
- [ ] Thalamic excitatory
- [ ] Upper rhombic lip
- [ ] Upper-layer intratelencephalic
- [ ] Vascular

**Comment by shawntanzk** [comment]
@dosumis - question: do we REALLY need http://purl.obolibrary.org/obo/CL_4023070 ('caudal ganglionic eminence derived GABAergic cortical interneuron') to be cortical specific? Currently there's a need to add CGE interneuron, and if I do, it CGE cortical interneuron will be the only child (unless I also created like hippocampus, amygdala etc. CGE interneuron. I don't see a huge use case for the proliferation of these terms as we tend to also annotate location of cell types (eg annotating cell type as "CGE interneuron" and location as "hippocampus"). Should we make a change for CGE and MGE to be wider brain applicable? If so should it be an obsolete and remake term (given we are changing the definition of the term)? Thanks

**Comment by shawntanzk** [comment]
Issue:
Choroid plexus and Ependymal are separate clusters, yet there are Ependymal cells in the Choroid plexus - not sure how these clusters are actually separated?

**Comment by dosumis** [comment]
* I'm in favour of making a general MGE interneuron term but also keeping subclasses by major region.  It's some proliferation of terms, but I think potentially v.useful.

* Is the choroid plexus cluster close to the ependymal cluster on the UMAP?  Presumably specialised ependymal cells that cluster separately.  Might be odd to have term for non-CP ependymal cells though, so any annotation of the ependymal cluster will have to be with a broader term.

**Comment by shawntanzk** [comment]
> Is the choroid plexus cluster close to the ependymal cluster on the UMAP?

They are a fully separate island, I'm guessing that Ependymal cluster doesn't include Ependymal in choroid plexus, light not details in writing about it. 

![Screenshot 2022-11-24 at 11 51 00](https://user-images.githubusercontent.com/76212760/203777710-4ac2da1f-5017-4143-91ed-30fd96546f82.png)

**Comment by shawntanzk** [comment]
Similar issue with 'Eccentric medium spiny neuron' and 'medium spiny neuron' which are separate clusters, but I assume 'medium spiny neurons' refers to “direct” (dSPN) and “indirect” (iSPN) spiny neurons only. 
![Screenshot 2022-11-24 at 14 26 06](https://user-images.githubusercontent.com/76212760/203807664-ed89bc1e-02c2-4b37-b937-ad644db7851e.png)
