### ISSUE TITLE
[Typo/Bug] typo in text definition for 'anterior horn motor neuron'

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1764]
**CL term**
[CL:2000048 'anterior horn motor neuron'](http://purl.obolibrary.org/obo/CL_2000048)

**Description of typo, bug or error**
Typo in text defintion:
"**An** lower motor neuron whose soma is located in one of the ventral horns of the spinal cord and innervates skeletal muscles of the trunk or head."

Change "An" to "A".

Side note and likely for a separate ticket: @shawntanzk, this text definition does not seem correct. This seems to leave out innervation of skeletal muscles in limbs and unsure what "head" muscles are innervated by this cell type. Appreciate your expertise on this.

**Comment by shawntanzk** [comment]
Given that this isn't a huge deal, I'd like to leave this ticket for new incoming curators - I see you have tagged good first task too :)

**Comment by shawntanzk** [comment]
Fixed it in #1812 (for some odd reason, this ticket seems duplicated or something and @bvarner-ebi & @aleixpuigb spotted that it was still opened after I fixed it). If all good, please do close it :)

**Comment by anitacaron** [comment]
There isn't a PR linked and merged to this issue to close it. But it's weird how they're duplicated.

**Comment by anitacaron** [comment]
Closing this issue in favour of https://github.com/obophenotype/cell-ontology/issues/1765

**Comment by bvarner-ebi** [comment]
> Fixed it in #1812 (for some odd reason, this ticket seems duplicated or something and @bvarner-ebi & @aleixpuigb spotted that it was still opened after I fixed it). If all good, please do close it :)

This ticket (#1764) was opened as a "good first task" to fix the typo in the definition. In response to:
> "Side note and likely for a separate ticket: ...",

@shawntanzk made that separate ticket (#1765). When @shawntanzk fixed #1765, the typo in this ticket was also fixed.
