### ISSUE TITLE
Massive amount of unsats in cl-edit

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#1782]
@bvarner-ebi spotted that there are a lot of unsats in cl-edit.owl in master branch
interestingly explain_unsat isn't picking this up which is probably why QC didnt pick up on it
Here's an example from @bvarner-ebi 
<img width="1088" alt="209308227-51e3ec28-f9e2-44d1-87c9-edcc751fbc0a" src="https://user-images.githubusercontent.com/95643797/209309433-d2a63ce6-eecf-411c-944a-de9bc7eb3bf6.png">

@bvarner-ebi suspects this PR in Ubeorn https://github.com/obophenotype/uberon/pull/2695 (tagging @gouttegd) 
Will try to look into this when I can, but any help is also welcomed

**Comment by gouttegd** [comment]
The (main? only? not sure yet) culprit seems to be _results in developmental progression of_ (RO:0002295), which has a range restricted to _connected anatomical structure_ (CARO:0000003) (which is itself `DisjointWith` _disconnected anatomical group_, CARO:0020000).

This restriction seems wrong. A developmental process can very well result in the development of an entity made of *disconnected* parts, not only of a connected structure. E.g., _endocrine system development_ results in the development of the _endocrine system_, which is a _non-connected functional system_ (it is made of endocrine glands dispersed throughout the body).

This range restriction should either be removed or at least replaced by a restriction to a higher class in the hierarchy, one that does not imply anything about “connectedness” (_anatomical entity_ would be correct, I think).

**Comment by bvarner-ebi** [comment]
Thank you for taking a look, @gouttegd.

Reviewing related tickets I found [this comment](https://github.com/obophenotype/uberon/issues/2682#issue-1420638803), where it was proposed that 'anatomical cluster' should be a 'disconnected anatomical group'. 
I'm not sure this is accurate, but unsure how "connected" is defined.

**Comment by gouttegd** [comment]
I note that the definition of RO:0002295 does state that the relation applies (or should apply) to anatomical structures:

> p results in the developmental progression of s iff p is a developmental process and s is an anatomical structure and p causes s to undergo a change in state at some point along its natural developmental cycle (this cycle starts with its formation, through the mature structure, and ends with its loss).

The range restriction is consistent with that definition, but then, if we follow that, the relation should _not_ be used to describe the development of anatomical entities that are _not_ anatomical structures. And again that seems wrong to me: I see no reason for limiting the use of that relation to the development of anatomical structures, especially since there are no equivalent relations to describe the development of disconnected anatomical entities.

**Comment by gouttegd** [comment]
> Reviewing related tickets I found https://github.com/obophenotype/uberon/issues/2682#issue-1420638803, where it was proposed that 'anatomical cluster' should be a 'disconnected anatomical group'.
I'm not sure this is accurate, but unsure how "connected" is defined.

I am not 100% sure either. As I wrote in that comment, it depends on how you interpret “adjacents” in the definition of _anatomical cluster_ (“anatomical group that has its parts adjacent to one another”). I took it as _not_ implying that the parts are _connected_, that is, they don’t have physical connection to each other.

(For reference, PATO defines _disconnected_ as “a structural quality inhering in the bearer by virtue of the bearer consisting of multiple structures lacking any physical connection to each other”.)

**Comment by bvarner-ebi** [comment]
>I took it as not implying that the parts are connected, that is, they don’t have physical connection to each other.

> (For reference, PATO defines disconnected as “a structural quality inhering in the bearer by virtue of the bearer consisting of multiple structures lacking any physical connection to each other”.)

If parts are adjacent (which I interpret as sharing a physical boundary), I would argue that they are physically connected.

**Comment by gouttegd** [comment]
I won’t argue with that, feel free to revert that change if you want. (Please do let me know if you do, because that term is mapped to FBbt’s _anatomical cluster_, which is clearly defined as disconnected; if you re-classify it as connected, I will need to remove the mapping.)

I actually question the usefulness of _anatomical cluster_ in Uberon, regardless of its definition, given the diversity of its subclasses: _muscle spindle_, _pineal complex_, _upper urinary tract_, _vasculature_ … Seems like a mess to me: under which definition would the _vasculature_ or the _urinary tract_ be _anatomical clusters_ ?

**Comment by dosumis** [comment]
Anatomical cluster in fbbt does useful work.  The uberon term inherits an
incoherent mess from FMA. Fully agree with Damien that this should be
cleaned up.  If align the def with fbbt and remove most subclasses.

Also makes sense to relax domain/range on the dev relation causing unsats.

**Comment by bvarner-ebi** [comment]
> I actually question the usefulness of anatomical cluster in Uberon, regardless of its definition, given the diversity of its subclasses: muscle spindle, pineal complex, upper urinary tract, vasculature … Seems like a mess to me: under which definition would the vasculature or the urinary tract be anatomical clusters ?

Agreed. I cannot justify why these terms are 'anatomical clusters'.

Of note, removing the range 'connected anatomical structure (CARO:0000003)' from 'developmental progression of (RO:0002295)' fixes all unsats but one (a GO term: 'calcium activated cation channel activity').

**Comment by bvarner-ebi** [comment]
> Also makes sense to relax domain/range on the dev relation causing unsats.

@dosumis, should this change and new CL release wait until the new year?

**Comment by gouttegd** [comment]
> all unsats but one (a GO term: 'calcium activated cation channel activity').

This one seems to be caused by _regulated by_ (RO:0002334), which has both a domain and a range restriction to _process_ (BFO:0000015) (so, a process is regulated by another process), where _process_ is an _occurrent_.

_calcium activated cation channel activity_ is defined as _gated channel activity_ (a process, OK) that is _regulated by_ some _calcium(2+)_ (**not** a process).

**Comment by shawntanzk** [comment]
> calcium activated cation channel activity is defined as gated channel activity (a process, OK) that is regulated by some calcium(2+) (not a process).

I think this might be a RO issue, again I think the range needs to be relaxed too, given a process can be regulated by things other than a process (probably also means we should change the domain of regulates given that regulates by is defined by regulates)

**Comment by gouttegd** [comment]
@shawntanzk Not sure about that. `regulated by` is a subclass of `causal relation between processes`, so the range and domain restrictions are clearly not accidental – the relation is explicitly intended to be about processes on both ends. There is another set of relations intended for causal relations between a process on one side and a material entity  on another side (RO:0002595 and its subclasses), the definition of _calcium activated cation channel activity_ should probably use one of those instead.

**Comment by dosumis** [comment]
> calcium activated cation channel activity is defined as gated channel activity (a process, OK) that is regulated by some calcium(2+)

@gouttegd is correct - this is a GO error.  GO should fix by changing to regulated by 'Ca2+ binding'.

**Comment by bvarner-ebi** [comment]
To revisit this issue, is the ideal approach as follows:

1: In CL, remove the range 'connected anatomical structure (CARO:0000003)' from 'developmental progression of (RO:0002295)'
2: Resolve https://github.com/geneontology/go-ontology/issues/24605
3: Refresh CL imports and make a new CL release

For step 1, does this change need to happen elsewhere / outside of CL?
For step 2, can someone recommend a GO editor to ping?

Thanks again for the help with this.

**Comment by gouttegd** [comment]
Step 1 should happen in [obo-relations](https://github.com/oborel/obo-relations). There’s already a PR for that (oborel/obo-relations#659), once it’s merged (only after a discussion about it at the next RO meeting apparently, whenever that meeting may be) the fix will be brought to CL by refreshing the RO import.

**Comment by shawntanzk** [comment]
> whenever that meeting may be

luckily it is today :) I'll attend and try to make sure this gets merged in (don't think its super controversial). Once that happens, I'll try to do a release (if merged in this evening, will probably get it done by tmr).

**Comment by gouttegd** [comment]
> don't think its super controversial

Famous last words… :D

**Comment by shawntanzk** [comment]
> For step 2, can someone recommend a GO editor to ping?

@raymond91125 was wondering if you could help with this (see https://github.com/geneontology/go-ontology/issues/24605) if not could you suggest someone that can help us with this please? thanks heaps :)

**Comment by shawntanzk** [comment]
GO issue should be solved in this PR https://github.com/geneontology/go-ontology/pull/24610 (see this ticket https://github.com/geneontology/go-ontology/issues/24605), will probably just have to refresh import after next GO release :)

**Comment by shawntanzk** [comment]
RO issue solved too :D will make a RO release tmr -> want to wait till after RO meeting today to let anyone get their stuff in and all

**Comment by bvarner-ebi** [comment]
With the new CL release, the only unsatisfiable class is now GO:0005227 'calcium activated cation channel activity'. The GO term update [appears to have been merged](https://github.com/geneontology/go-ontology/pull/24610). This last unsatisfiable class should be resolved once there is a new GO release and it is imported to CL.

**Comment by bvarner-ebi** [comment]
Now that GO has a new release release and [imports have been refreshed in CL](https://github.com/obophenotype/cell-ontology/pull/1890), there appear to be no more unsats in cl-edit.

Thanks to all for the help.
