### ISSUE TITLE
[Merge] 'neuroendocrine cell' and 'neurosecretory neuron'

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1784]
**CL terms**
CL:0000165 'neuroendocrine cell' 

to subsume:

CL:0000381  'neurosecretory neuron' (has 1 child class, no text definition)

**Reason for deprecation**
'neuroendocrine cell' (which has exact synonym "neurosecretory cell") and 'neurosecretory neuron' may all refer to the same cell type.
https://doi.org/10.1093/icb/7.1.161

**Comment by shawntanzk** [comment]
Given that the EA of neurosecretory neuron is
```
neuron
 and ('capable of' some 'hormone secretion')
```
I think this merge is sensible.
However, I think we need to be careful of the use of neurosecretory as basically all neurons "secretes" neurotransmitters right? and not all NTs are hormones. My suggestion would be to make neurosecretory neuron a related or broad synonym

**Comment by bvarner-ebi** [comment]
>However, I think we need to be careful of the use of neurosecretory as basically all neurons "secretes" neurotransmitters right? and not all NTs are hormones. My suggestion would be to make neurosecretory neuron a related or broad synonym

Thanks for the feedback.
After a cursory search, the term "neurosecretion" appears to have inconsistencies in how it is defined and used (the release of any substance from a neuron vs the release of hormones from a neuron.)

In addition to the reference in the original comment, these additional references suggest that this term is used specifically in association with hormone release rather than release of any substance (neurotransmitters, etc):

https://link.springer.com/chapter/10.1007/978-3-030-22989-4_1
https://www.sciencedirect.com/topics/neuroscience/neurosecretory-cell
https://encyclopedia2.thefreedictionary.com/Neurosecretion
https://www.britannica.com/science/neurosecretory-cell

**Comment by bvarner-ebi** [comment]
Given the "evolution" in meaning and potential ambiguity of the term, there are sources that treat it as a broader term and others that treat it as an exact synonym. With this in mind, I would annotate it as a related synonym. 

Consider adding a rdfs:comment or editor's note regarding "The modern definition of neurosecretion has evolved ..."

**Comment by aleixpuigb** [comment]
Thank you for your input.
