### ISSUE TITLE
[Logical def] Visceral muscle cell missing "part_of" statement

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#1793]
**CL term**

https://ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_0008007

**Suggested revision of logical definition**

Add equivalence axiom reflecting textual description.

**Comment by aleixpuigb** [comment]
Thank you, @lubianat. I will create a new UBERON term for 'visceral muscle' and then add the equivalence axiom that you propose.

**Comment by aleixpuigb** [comment]
Hi @lubianat, the term `visceral muscle` can now be found in the Uberon ontology and the logical definition of `visceral muscle cell` will be present in the next release scheduled for next Tuesday (21/03/23). Thank you.
