### ISSUE TITLE
Incorrect descendants 

### ISSUE THREAD

**Issue by noamiz5060** [obophenotype/cell-ontology#1802]
hey hey
There are cells that in the website have/dont have a descendants, while when you ask for their descendants in python, it returns several of them.
For example, 'Bm3-delta B cell' [CL_0000963 ] doesn't have anyone below him in the website, while in python it says he has 2 descendants, ['CL:0000967', 'CL:0000966'], which are 'Bm5 B cell' and 'Bm4 B cell'. 
I'm using cl-basic.obo file and the networkx.ancestors function in python.

If a cell does have descendants and for some reason they don't show up in the website, I'd love to know if there's any function that can return its descendants by the website (in my example, no descendants at all)

**Comment by bvarner-ebi** [comment]
Hi @noamiz5060, thank you for the comment.

In your example, it seems you are pulling in classes that are linked to the parent class 'Bm3-delta B cell' through the 'develops from' property. I believe OLS only displays 'subclass of'  and 'part of' relations.
Using http://purl.obolibrary.org/obo/cl/cl.obo, these relationships are visualised in Protégé. 

<img width="296" alt="Screenshot 2023-01-16 at 16 21 07" src="https://user-images.githubusercontent.com/95643797/212724575-50409d38-4ef0-456a-848d-d2bb8dfc8c0b.png">

@dosumis, @ubyndr, can you recommend a solution that would return the same results as OLS?

**Comment by dosumis** [comment]
@noamiz5060 - it is better to use a library that allows the edge (relation) types to be specified.  
That may be possible in NetworkX, but you could also consider [OAK](https://pypi.org/project/oaklib/). develops_from edges are not safe to use for most  content grouping or enrichment use-cases (e.g. if you want to group annotations of gene expression, you should avoid develops from - if cells of type X expresses gene Y and cells of type X develops from cells of type Z, you can't include that cells of type Z express gene Y).

**Comment by noamiz5060** [comment]
> @noamiz5060 - it is better to use a library that allows the edge (relation) types to be specified. That may be possible in NetworkX, but you could also consider [OAK](https://pypi.org/project/oaklib/). develops_from edges are not safe to use for most content grouping or enrichment use-cases (e.g. if you want to group annotations of gene expression, you should avoid develops from - if cells of type X expresses gene Y and cells of type X develops from cells of type Z, you can't include that cells of type Z express gene Y).

First of all, thank you both for replying, I really appreciate it.

Will oak be able to give me the same results of OLS? Right now I'm deep into my project and I probably can't let myself use the Protege version. Cells like Bm3 delta b cell give me this minor yet important problem, that will be easily solved if I could use the OLS version. I can't decide 'by myself' to delete Bm delta as it has no descendants, I need it to be in the ontology itself. I hope I don't sound too absurd

**Comment by dosumis** [comment]
HI @noamiz5060, 

there is no OLS version.  It's just a display issue - OLS tree-view is set to display only 2 edge types -  subClassOf and part_of.  [networkX descendants ](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.descendants.html) just uses all edge types (iIRC, networkX doesn't support edge labels/types).

OAK will allow you to specify edge types in queries for descendants, so you could choose subclassof(is_a) and part_of there if that is what you want.  What is your use-case?

**Comment by noamiz5060** [comment]
> s

Oh I get it now. So what edge type is the Bm3 b cell descendants in that case? and how can use OAK to not include it?

I need to get from the ontology cells but not all of them. It's hard to explain, but I try to aim for cells that aren't too specific like d79 alpha something natural killer cell yada yada yada, but on the other hand, I need it not to be TOO general, like getting 'lymphocytes' for example. I mostly managed to do that, but there are still few cells that are left, and the one that does the most damage is the Bm3 one. The solution I came up with, after looking at the OLS ver, is remove the cells with no descendants, and indeed most of them were the way-too-specific one, but unfortunately the Bm3 left, because he had these 'hidden' descendants. The catch is I cant delete specific cells by myself, I need to make a 'law'.

**Comment by bvarner-ebi** [comment]
> So what edge type is the Bm3 b cell descendants in that case? 

'develops from'

This is illustrated on the right side of the page in OLS.

<img width="903" alt="Screenshot 2023-01-17 at 09 27 43" src="https://user-images.githubusercontent.com/95643797/212860644-f30a6ff2-71cc-47ce-ac46-86e060582d28.png">

**Comment by bvarner-ebi** [comment]
@noamiz5060, feel free to reopen this issue if you have follow-up questions regarding the ontology.

**Comment by noamiz5060** [comment]
I thank you both very much

**Comment by dosumis** [comment]
> Oh I get it now. So what edge type is the Bm3 b cell descendants in that case? and how can use OAK to not include it?
> ...
> I try to aim for cells that aren't too specific like d79 alpha something natural killer cell yada yada yada, but on the other hand, I need it not to be TOO general

If you are interested in specific vs general cell types, you should probably just use subClassOf (IS_A) edges alone. 

For how to do this in OAK, check out the graph operations part of this notebook:
https://github.com/INCATools/ontology-access-kit/blob/main/notebooks/basic-demo.ipynb

**Comment by noamiz5060** [comment]
> > Oh I get it now. So what edge type is the Bm3 b cell descendants in that case? and how can use OAK to not include it?
> > ...
> > I try to aim for cells that aren't too specific like d79 alpha something natural killer cell yada yada yada, but on the other hand, I need it not to be TOO general
> 
> If you are interested in specific vs general cell types, you should probably just use subClassOf (IS_A) edges alone.
> 
> For how to do this in OAK, check out the graph operations part of this notebook: https://github.com/INCATools/ontology-access-kit/blob/main/notebooks/basic-demo.ipynb

Is there any way to get what I need with Networkx? I've tried to use OAK but I struggle with it a lot, I feel it's a bit unfriendly for the user experience and I just can't seem to use it properly and get what I need.  I just need to get rid of the develop_from and I could sleep calmly

**Comment by anitacaron** [comment]
Hi @noamiz5060, did you try something like this in OAK?

```python
from oaklib.implementations.pronto.pronto_implementation import ProntoImplementation
from oaklib.resource import OntologyResource
from oaklib.datamodels.vocabulary import IS_A, PART_OF

resource = OntologyResource(slug='cl-basic.obo', local=True)
oi = ProntoImplementation(resource)

desc = oi.ancestors('CL:0000963', predicates=[IS_A, PART_OF])
for anc in list(ancs):
    print(f'{anc} ! {oi.label(anc)}')
```

**Comment by noamiz5060** [comment]
> 

thank you very much for the reply.
I get an error 'KeyError: 'NCBITaxon:9606'' (BTW I replaced the 'ancs' in desc, imaging that's what you meant)
Not only that, more of the examples in the demo notebook above give me errors

if it matters, I also tried to use `oi = ProntoImplementation(OntologyResource(local=False, slug='cl-basic.obo'))` 
(also tried it with `"http://purl.obolibrary.org/obo/cl/cl-basic.obo"`, nothing works
