### ISSUE TITLE
[Typo/Bug] Location of cl.owl 

### ISSUE THREAD

**Issue by twhetzel** [obophenotype/cell-ontology#1807]
**Description of typo, bug or error**
Hi all - where can I find the latest version of the `cl.owl` file? I see an OBO file in the top-level directory of the repo, but not the OWL file. Checking https://cell-ontology.github.io/ the "Download OWL" button returns a 404.

**Comment by balhoff** [comment]
The website should link to the PURL rather than directly to GitHub: http://purl.obolibrary.org/obo/cl.owl

I think CL recently switched to using GitHub releases, and broke the link (good reason for using PURLs).

**Comment by bvarner-ebi** [comment]
Thank you for pointing this out, @twhetzel and @balhoff.
The link on the website now directs to the PURL.
