### ISSUE TITLE
temporal relation used in CL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#181]
```
Current CL is using BFO 2 temporal relation
http://purl.obolibrary.org/obo/BFO_0000056
participates in at some time

Does CL plan to replace it by RO relation
http://purl.obolibrary.org/obo/RO_0000056
participates in

```

Original issue reported on code.google.com by `zhengj2...@gmail.com` on 19 May 2015 at 10:14

**Comment by addiehl** [comment]
CL does use http://purl.obolibrary.org/obo/RO_0000056 'participates in' currently. and no longer uses 'bearer of at some time', so nothing left to fix.
