### ISSUE TITLE
Unresolvable IRIs

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1810]
There are several terms in CL with unresolvable IRIs. These appear to be relations in CL but not in RO and have an octothorpe in the IRI.

For example, http://purl.obolibrary.org/obo/cl#lacks_plasma_membrane_part

@shawntanzk provided a link to [this file](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/cl.yml), which may be key in addressing the issue.

FYI, @anitacaron

**Comment by shawntanzk** [comment]
As reference, http://purl.obolibrary.org/obo/cl#lacks_plasma_membrane_part should resolve to: 
https://ontobee.org/ontology/CL?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2Fcl%23lacks_plasma_membrane_part

**Comment by dosumis** [comment]
Agree should be fixed here: 
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/cl.yml

@anitacaron  - could you have a go at making a PR to fix?  Not Urgent.  (If you haven't edited these before, Huseyin can help)

**Comment by balhoff** [comment]
In my opinion instead of making these resolvable, they should all be replaced with numeric identifiers. I've been working toward this in various ontologies (didn't get to CL yet): https://github.com/INCATools/ubergraph/issues/102

These hash IRIs create massive confusion for users, and don't have any canonical CURIE form.

**Comment by balhoff** [comment]
> Also, there are many GitHub links referenced in the yaml file. Should those be updated to PURLs?

@bvarner-ebi that's the file that makes the PURLs work, so in this case you do need to point to GitHub.

**Comment by bvarner-ebi** [comment]
> > Also, there are many GitHub links referenced in the yaml file. Should those be updated to PURLs?
> 
> @bvarner-ebi that's the file that makes the PURLs work, so in this case you do need to point to GitHub.

Thank you for explaining!

**Comment by anitacaron** [comment]
I agree with @balhoff. It's better and easier to replace all properties with numeric identifiers.

**Comment by dosumis** [comment]
Proposal is to use CL IDs for these.  I think this is a reasonable solution.

**Comment by bvarner-ebi** [comment]
Below is a list of object properties in CL without numeric identifiers. The majority are imported from other ontologies. 
As an initial next step, I will reassign numeric identifiers to the properties in CL.

Object properties in CL without numeric identifiers
------------------------------------------------------
http://purl.obolibrary.org/obo/chebi#has_functional_parent
http://purl.obolibrary.org/obo/chebi#has_parent_hydride
http://purl.obolibrary.org/obo/chebi#is_conjugate_acid_of
http://purl.obolibrary.org/obo/chebi#is_conjugate_base_of
http://purl.obolibrary.org/obo/chebi#is_enantiomer_of
http://purl.obolibrary.org/obo/chebi#is_substituent_group_from
http://purl.obolibrary.org/obo/chebi#is_tautomer_of
**http://purl.obolibrary.org/obo/cl#has_not_completed
http://purl.obolibrary.org/obo/cl#lacks_part
http://purl.obolibrary.org/obo/cl#lacks_plasma_membrane_part**
http://purl.obolibrary.org/obo/pr#has_constituent_monomer
http://purl.obolibrary.org/obo/pr#lacks_part
http://purl.obolibrary.org/obo/uberon/core#posteriorly_connected_to
http://purl/obolibrary.org/obo/uberon/core#anteriorly_connected_to
http://purl/obolibrary.org/obo/uberon/core#channel_for
http://purl/obolibrary.org/obo/uberon/core#channels_from
http://purl/obolibrary.org/obo/uberon/core#channels_into
http://purl/obolibrary.org/obo/uberon/core#conduit_for
http://purl/obolibrary.org/obo/uberon/core#distally_connected_to
http://purl/obolibrary.org/obo/uberon/core#extends_fibers_into
http://purl/obolibrary.org/obo/uberon/core#filtered_through
http://purl/obolibrary.org/obo/uberon/core#indirectly_supplies
http://purl/obolibrary.org/obo/uberon/core#layer_part_of
http://purl/obolibrary.org/obo/uberon/core#posteriorly_connected_to
http://purl/obolibrary.org/obo/uberon/core#protects
http://purl/obolibrary.org/obo/uberon/core#proximally_connected_to
http://purl/obolibrary.org/obo/uberon/core#proximally_connected_to
http://purl/obolibrary.org/obo/uberon/core#sexually_homologous_to
http://purl/obolibrary.org/obo/uberon/core#site_of
http://purl/obolibrary.org/obo/uberon/core#subdivision_of
http://purl/obolibrary.org/obo/uberon/core#synapsed_by
http://purl/obolibrary.org/obo/uberon/core#transitively_anteriorly_connected_to
http://purl/obolibrary.org/obo/uberon/core#transitively_distally_connected_to
http://purl/obolibrary.org/obo/uberon/core#transitively_proximally_connected_to
http://purl/obolibrary.org/obo/uberon/core#trunk_part_of

**Comment by bvarner-ebi** [comment]
CL terms addressed in #1854.

Next steps:
[ ] Follow up with CHEBI on updating identifiers
[ ] Follow up with Uberon on updating identifiers (@anitacaron, is this something you were investigating?)
[ ] Investigate replacing instances of PR relation lacks_part with CL:4030045 lacks_part
[ ] Follow up with PR on updating identifier for has_constituent_monomer (and lacks_part if not replaced by CL lacks_part)

**Comment by dosumis** [comment]
Trying to fix everyone else's identifiers looks like unsustainable scope creep to me.  If this is prompted by validation fails then the validation checks should be updated to ensure they don't run on imports (I think this should be a general principle).

lacks_part should have a separate ticket for review of usage.  It is potentially dangerous to hide negation in a positive statement (see the example of lacks_part lobed nucleus => inference of anucleate described in #93 )

**Comment by balhoff** [comment]
@bvarner-ebi here is an issue linking several other issues to work on that: https://github.com/INCATools/ubergraph/issues/102

But none of the ones you mentioned have been addressed yet. I thought there was an Uberon issue, but I can't find it now.

**Comment by bvarner-ebi** [comment]
Covered in https://github.com/INCATools/ubergraph/issues/102:
[ ] Follow up with CHEBI on updating identifiers
[ ] Follow up with PR on updating identifiers

@balhoff- can you add Uberon to the scope of https://github.com/INCATools/ubergraph/issues/102?
[ ] Follow up with Uberon on updating identifiers (@anitacaron, is this something you were investigating?)

Covered in #1863:
[ ] Investigate replacing instances of PR relation lacks_part with CL:4030045 lacks_part

**Comment by anitacaron** [comment]
I'll create a general ticket in Uberon and link it to the Ubergraph ticket. I started fixing the two properties that are already available in RO.

**Comment by bvarner-ebi** [comment]
Closing this ticket as the local issue in CL has been addressed in #1854 and pending items will be covered in separate tickets.
