### ISSUE TITLE
[NTR] respiratory ciliated cell

### ISSUE THREAD

**Issue by s-carney** [obophenotype/cell-ontology#1811]
**Preferred term label**
respiratory ciliated cell

**Synonyms** (add reference(s), please)
ciliated cell of the respiratory tract

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A ciliated cell of the respiratory system. Ciliated cells are present in the airway epithelium from the nasal cavity, trachea, bronchi, to the bronchioles.

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
http://purl.obolibrary.org/obo/CL_0000064

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
http://purl.obolibrary.org/obo/UBERON_0001004

**Comment by bvarner-ebi** [comment]
Thank you for the new term request, @s-carney. 

Is this new term meant to be a parent term to:
[CL:0002332 'ciliated cell of the bronchus'](http://purl.obolibrary.org/obo/CL_0002332)
[CL:0002145 'ciliated columnar cell of tracheobronchial tree'](http://purl.obolibrary.org/obo/CL_0002145)
[CL:1000271 'lung ciliated cell'](http://purl.obolibrary.org/obo/CL_1000271)? 
Would these terms be sufficient for your use case or do you require this new grouping term?

If you need this new grouping term, kindly provide a reference to support the text definition (PMID, doi, etc) and your ORCID.

**Comment by s-carney** [comment]
I believe this could represent a grouping term as ciliated cells can also be found in the upper airways.

PMID: 21364219
PMID: 18757316

Unfortunately, I do not have an ORCID.

**Comment by bvarner-ebi** [comment]
[@s-carney](https://github.com/s-carney), thank you for the new terms.
The following have been added to CL and should appear in the next release:
CL:4030034 ‘respiratory ciliated cell’

Additional details can be found in [the linked PR](https://github.com/obophenotype/cell-ontology/pull/1819).
