### ISSUE TITLE
[NTR] suprabasal keratinocyte

### ISSUE THREAD

**Issue by s-carney** [obophenotype/cell-ontology#1813]
**Preferred term label**
suprabasal keratinocyte

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
Suprabasal keratinocytes are cells that lie directly above basal keratinocytes

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
http://purl.obolibrary.org/obo/CL_0000312

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
http://purl.obolibrary.org/obo/UBERON_0001003

**Comment by aleixpuigb** [comment]
Thank you for the new term request, @s-carney.

Given the definition that you provided, are you referring to keratinocytes that are in direct contact above the basal stratum or any keratinocyte found in the epithelial suprabasal layer? 

If you are referring to only the keratinocytes in contact with basal keratinocytes, could you provide a reference to support this text definition?

**Comment by s-carney** [comment]
Hello, 

I am referring to the latter: any keratinocyte found in the epithelial suprabasal layer.
Here is my reference: 
https://www.proteinatlas.org/humanproteome/single+cell+type/Squamous+epithelial+cells#suprabasalkeratinocytes

**Comment by aleixpuigb** [comment]
@s-carney, thank you for the new terms.

The following have been added to CL and should appear in the next release:

CL:4033013 suprabasal keratinocyte

Additional details can be found in the [associated PR](https://github.com/obophenotype/cell-ontology/pull/1826).
