### ISSUE TITLE
[Question] Are all animals part of Metazoa?

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#1816]
**Background**
The logical definition of the term CL:0000548 "animal cell" is the following:

'native cell'
 **and** ('only in taxon' **some** Metazoa)

By definition, Metazoan are multicellular animals, what suggests: a) There are unicellular animals that are not Metazoan, or b) all animals are multicellulars, and therefore Metazoan.

**Question**
Is there any animal that is not part of Metazoa?

**Comment by dosumis** [comment]
AFAIK, the tems Metazoa and Animalia are used interchangably.  We use NCBI taxonomy as a reference, which has  Animalia as a synonym for Metazoa: https://www.ebi.ac.uk/ols/ontologies/ncbitaxon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_33208&lang=en&viewMode=All&siblings=false

>  all animals are multicellulars, and therefore Metazoan.

all plants are multicelluar, but none are metazoan.

**Comment by dosumis** [comment]
(At least most are - depending on whether unicellular algae count as plants.  Argument still holds though)

**Comment by dosumis** [comment]
BTW - we don't need to worry about the logic of NCBI-Taxonomy.  It's just an agreed reference standard.  In the OBO interpretation, an instance of the class Metazoa = a single organism that belongs to the Metzoan taxon.  (e.g. you and I are both instances).  

The logic of the term "animal cell" defines it as any cell that is part_of (some) Metazoa(n) organism.

**Comment by bvarner-ebi** [comment]
> The logic of the term "animal cell" defines it as any cell that is part_of (some) Metazoa(n) organism.

Should "metazoan cell" then be an exact synonym to 'animal cell' or should the label be 'metazoa cell'?

I agree that using "multicellular animal" as an exact synonym to "Metazoa" implies that unicellular animals exist.

**Comment by dosumis** [comment]
>  A cursory online search reveals that there are different perspectives

True. But we defer to NCBI_taxonomy on this and they treat Animalia as synonymous.  I agree that the exact synonym 'metazoan cell' to be added.  I think "animal cell" is fine as the label as its more accessible.
