### ISSUE TITLE
[NTR] endometrial ciliated cell

### ISSUE THREAD

**Issue by s-carney** [obophenotype/cell-ontology#1817]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label**
endometrial ciliated cell

**Synonyms** (add reference(s), please)
ciliated cell of the endometrium
uterine ciliated cell
ciliated cell of the uterus

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A ciliated cell that lines the endometrium where the cilia help move mucus from the glandular tissue [PMID: 31290979]

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
http://purl.obolibrary.org/obo/CL_0000064

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
http://purl.obolibrary.org/obo/UBERON_0004811

**Comment by bvarner-ebi** [comment]
Thanks for the new term request, @s-carney.

In another ticket (#1760), it is planned to add 3 new terms (from https://www.nature.com/articles/s41591-020-1040-z):

‘endometrial ciliated epithelial cell’
with new child classes:
‘luminal endometrial ciliated epithelial cell’
‘glandular endometrial ciliated epithelial cell’

If you agree, I will merge the details from this request with creating the new term ‘endometrial ciliated epithelial cell’.

**Comment by s-carney** [comment]
Hello, thanks for your response. I agree the other tickets describes well the term suggested.

**Comment by bvarner-ebi** [comment]
Thanks for the reply, @s-carney. 
The reference provided also uses organoids in the study, which is outside the domain of CL. 
If you'd like to have your requested synonyms added to the new term, a non-organoid reference or your ORCID could be added to support their inclusion.

**Comment by s-carney** [comment]
My primary source was the Human Protein Atlas:
https://www.proteinatlas.org/humanproteome/single+cell+type/Glandular+epithelial+cells#endometrialciliatedcells
Perhaps if this is not sufficient, I can find another reference.

**Comment by bvarner-ebi** [comment]
@s-carney,

Thank you for this ticket. The following have been added to CL and should appear in the next release:

CL:4030040 ‘endometrial ciliated epithelial cell’
CL:4030041 ‘luminal endometrial ciliated epithelial cell’
CL:4030042 ‘glandular endometrial ciliated epithelial cell’

More details are available in [the linked PR](https://github.com/obophenotype/cell-ontology/pull/1843).
