### ISSUE TITLE
Remove chebi import

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#1837]
I saw that CL is still not using the Slim for CHEBI.

Replacing this will drastically reduce memory use for CL:

https://github.com/obophenotype/cell-ontology/blob/master/src/ontology/cl-odk.yaml#L61

**Comment by dosumis** [comment]
Wondering whether we need CHEBI imports at all.  Would be good to see what we use for.  We may be able to replace usage with GO processes that ref CHEBI.

**Comment by anitacaron** [comment]
The only use is in the [CL:0002060](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0002060)

```
# Class: obo:CL_0002060 (melanophage)

AnnotationAssertion(Annotation(oboInOwl:hasDbXref "GOC:tfm"^^xsd:string) Annotation(oboInOwl:hasDbXref "PMID:20479296"^^xsd:string) Annotation(oboInOwl:hasDbXref "PMID:2943821"^^xsd:string) obo:IAO_0000115 obo:CL_0002060 "A melanin-containing macrophage that obtains the pigment by phagocytosis of melanosomes."^^xsd:string)
AnnotationAssertion(<http://purl.org/dc/terms/contributor> obo:CL_0002060 <https://orcid.org/0000-0003-1980-3228>)
AnnotationAssertion(oboInOwl:creation_date obo:CL_0002060 "2010-06-22T10:46:12Z"^^xsd:string)
AnnotationAssertion(rdfs:label obo:CL_0002060 "melanophage"^^xsd:string)
EquivalentClasses(obo:CL_0002060 ObjectIntersectionOf(obo:CL_0000864 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0002097) ObjectSomeValuesFrom(obo:BFO_0000051 obo:CHEBI_25179)))
SubClassOf(Annotation(oboInOwl:is_inferred "true") obo:CL_0002060 obo:CL_0000864)
```

**Comment by anitacaron** [comment]
Can I replace it with [GO:0006582](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0006582)?

**Comment by matentzn** [comment]
Needs @dosumis I dont know

**Comment by dosumis** [comment]
I can't think of any other way to formalise.  Could just remove the EC axiom.  Wouldn't be too much of a loss I think.
