### ISSUE TITLE
[Typo/Bug] Tag release says 2022 instead of 2023

### ISSUE THREAD

**Issue by bherr2** [obophenotype/cell-ontology#1841]
**Description of typo, bug or error**

The latest release has is tagged as [v2022-01-09](https://github.com/obophenotype/cell-ontology/releases/tag/v2022-01-09) ... which really should be v2023-01-09, right?

**Comment by bvarner-ebi** [comment]
@bherr2, thank you for spotting this.
The tag on the latest release has been updated. Kindly advise if you find other inconsistencies.

**Comment by bherr2** [comment]
Thank you for the quick resolution! I think that does it :-)
