### ISSUE TITLE
Paneth cell lacks part_of relationship to crypt of Lierberkuhn

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1844]
The definition suggests that this part relationship should be present.
![image](https://user-images.githubusercontent.com/112839/218527131-2b7fa3cc-2101-4926-90c3-d7e74686f2fd.png)

**Comment by aleixpuigb** [comment]
Thank you for this ticket, @dosumis.

After doing some research on Paneth cells, I agree that Paneth cells are part of the crypt and I would add [an additional reference](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7145889/#:~:text=Paneth%20cells%20are%20highly%20specialized,composition%20of%20the%20intestinal%20flora.) to the text definition.
![Screenshot 2023-02-14 at 10 43 14](https://user-images.githubusercontent.com/94959119/218712941-7942c450-869a-45bf-8c62-5bd09e5563de.png)

In addition, Paneth cell has the following two grandchild in the CL ontology:

![Screenshot 2023-02-14 at 10 47 16](https://user-images.githubusercontent.com/94959119/218713582-6eaca36f-db34-46d3-bca0-c3e6720c66cb.png)

Both terms are paneth cells of the epithelium of the small intestine, however they induce to confusion as both might refer to the same cells, unless by epithelium proper they refer to the villus without including the crypt. As I have not found any reference of Paneth cells outside of the crypt or that epithelium proper refers to only the villus, in my opinion both terms are redundant and would be obsolete with the addition of the 'part of' to paneth cells.

I would suggest the following:

- [ ]  Add a Subclass Of 'part of' some 'crypt of lieberkuhn' (UBERON:0001983) for Paneth cells.

- [ ] Obsolete 'paneth cell of epithelium of crypt of Lieberkuhn of small intestine' and 'paneth cell of epithelium proper of small intestine'.

Finally, Paneth cells are [rarely found in the rectum or anus, and it is a hallmark of inflammatory bowel disease](https://www.sciencedirect.com/science/article/pii/S1074761320303174). However, in the ontology we can find the '[paneth cells of anorectum](http://purl.obolibrary.org/obo/CL_0009055)' term. While there are [crypts in the rectum](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3241542/) (not in UBERON), it doesn't look like it is the case of the anus and I have not find references stating of the presence of Paneth cells in the anus. Therefore, I propose two options:

- [ ] Obsoleting the term 'paneth cell of anorectum' as it is not find in homeostatic conditions.
or
- [ ] Creating an UBERON term for 'crypt of Lieberkuhn of rectum' and edit 'paneth cell of anorectum' to 'paneth cell of rectum'.
