### ISSUE TITLE
[NTR] 'CD24-positive, CD-133-positive, vimentin-positive proximal tubular cell'

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1856]
**Preferred term label**
CD24-positive, CD-133-positive, vimentin-positive proximal tubular cell

**Synonyms**
(broad): CD24-positive tubular cell [PMID:23124355](https://pubmed.ncbi.nlm.nih.gov/23124355)
(broad): CD24+CD133+ tubular cell [PMID:23124355](https://pubmed.ncbi.nlm.nih.gov/23124355)
(broad): CD133+CD24+CD106- tubular cell [https://doi.org/10.1002/stem.1130](https://doi.org/10.1002/stem.1130)
****Note- Consider creating separate classes for this cell type in distal convoluted tubule and connecting segment:
"However, CD133+CD24+ tubular cells were localized in the distal convoluted tubule and the connecting segment..." but compare to findings in [PMID:23124355](https://pubmed.ncbi.nlm.nih.gov/23124355)**

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A CD24-positive, CD-133-positive, vimentin-positive cell found scattered throughout a renal proximal tubule and that may participate in tubular regeneration. Compared to other proximal tubular cell types, this cell contains less cytoplasm, fewer mitochondria and no brush border.
[PMID:23124355](https://pubmed.ncbi.nlm.nih.gov/23124355)
[PMID:21281815](https://pubmed.ncbi.nlm.nih.gov/21281815)

**Parent cell type term**
CL:0002306 'epithelial cell of proximal tubule'
expresses some 'signal transducer CD24'
expresses some prominin-1
expresses some vimentin (needs imported after GO update: http://purl.obolibrary.org/obo/PR_000017298)

**What is the anatomical structure that the cell is a part of?**
‘part of’ some ‘proximal tubular epithelium’

**Additional notes or concerns**
Comment: After acute tubular injury, this cell type becomes more numerous. In healthy rat kidneys, this cell is not detectable, whereas after unilateral ureteral obstruction (renal injury), it may appear de novo, arguing against the notion that this cell type represents a pre-existing progenitor cell population. In at least one study, data indicate that this cell type represents transiently dedifferentiated tubular cells involved in regeneration.
[PMID:23124355](https://pubmed.ncbi.nlm.nih.gov/23124355)

**Comment by dosumis** [comment]
Are these rat markers?

**Comment by bvarner-ebi** [comment]
> Are these rat markers?

The papers mention human and rat subjects.
The PR terms refer to the human gene product or "1:1 orthodox thereof".

**Comment by bvarner-ebi** [comment]
Note: adding this term is paused until the new GO release is available.

**Comment by bvarner-ebi** [comment]
CL:4030038 'CD24-positive, CD-133-positive, vimentin-positive proximal tubular cell' has been to CL and should appear in the next release.
