### ISSUE TITLE
[NTR] Bipolar cells

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#1865]
Adding 12 new bipolar cell types. All the information is [described in the modified MIRACL table](https://docs.google.com/spreadsheets/d/1KVEXB29BdKqhewc1_UB8v8EFFP0T7ML2fA3J0ncrYFI/edit?usp=sharing).

**Your ORCID**
http://orcid.org/0000-0001-6677-8489

**Additional notes or concerns**

**Comment by aleixpuigb** [comment]
Some of these cells have mouse homologous terms in the CL:
<img width="329" alt="Screenshot 2023-03-03 at 09 51 55" src="https://user-images.githubusercontent.com/94959119/222689426-0292ae3f-444d-4133-9ab3-de9acb990da6.png">

Not all the homologies are correct and they should not be exact_synonym, as in the [dbxref you can read](https://onlinelibrary.wiley.com/doi/10.1002/cne.10985):

> DB1 cells of the primate retina appear to correspond to Type 1 cells, DB2 to Type 4 cells, and DB3 to Type 3 cells. 

@dosumis @bvarner-ebi Do you think that we should we create new terms human (and primate) specific, or should we work with the ones that already exist?

**Comment by dosumis** [comment]
Would be good to have grouping terms, but also possible that homology is controversial.  Grouping on properties might be more straightforward. Maybe add to agenda for CL@EBI?
