### ISSUE TITLE
[Typo/Bug] review and revise 'gonadotropin releasing neuron'

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1866]
**CL term**
CL:0011111 'gonadotropin releasing neuron'

**Description of typo, bug or error**
The concepts of "gonadotropin-releasing hormone" and "gonadotropin" seem to have been conflated when creating CL:0011111 'gonadotropin releasing neuron'. The label, dbxref, exact synonyms and EA do not describe the same cell type.

**Comment by aleixpuigb** [comment]
I propose the following actions to fix this issue:
- [ ] Update name to `gonadotropin-releasing hormone neuron`
- [ ] - [ ] Update text definition: 
   > A neuroendocrine cell that is born in the nasal placode during embryonic development and migrates through the nose and forebrain to the hypothalamus. This cell regulates reproduction by secreting gonadotropin-releasing hormone into the pituitary portal vessels to induce the release of gonadotropins into the general circulation.
- [ ] Remove equivalent axiom and add the two following subclasses: 'neuroendocrine cell' and 'capable of' some 'regulation of gonadotropin secretion'.

**Comment by bvarner-ebi** [comment]
Thanks for looking into this, @aleixpuigb.

Agree with the label change.

For text def, I recommend the first sentence to explicitly define the cell: A neuroendocrine cell that secretes gonadotropin-releasing hormone.

Regarding "'capable of' some 'regulation of gonadotropin secretion'"... 
 the gonadotropin-releasing hormone (GnRH) is the entity which regulates gonadotropin secretion. 
 'capable of' is not a transitive property. 
 Therefore, '[capable of regulating'](http://purl.obolibrary.org/obo/RO_0002596) some 'gonadotropin secretion' may be more accurate.

'capable of regulating' def:
Holds between c and p if and only if c is capable of some activity a, and a regulates p.

In the present example:
c = gonadotropin-releasing hormone neuron
a = GnRH secretion
p = gonadotropin secretion

**Comment by aleixpuigb** [comment]
thank you for your comments, @bvarner-ebi.

> Therefore, 'gonadotropin-releasing hormone neuron' '[capable of regulating'](http://purl.obolibrary.org/obo/RO_0002596) some 'gonadotropin secretion' may be more accurate.

Perfect! I wasn't very convinced either by it, so this option is great!
