### ISSUE TITLE
[Class hierarchy] (multiple terms) - remove direct subclass to material entity

### ISSUE THREAD

**Issue by nataled** [obophenotype/cell-ontology#1867]
The following terms have direct subclass assertions to BFO:000040 'material entity'. These appear to be superfluous, as they also have direct subclass assertions to a more specific CL term. I suspect these can (should?) be removed.

**CL term**

- [ ] CL:0000039
- [ ] CL:0000081
- [ ] CL:0000135
- [ ] CL:0000140
- [ ] CL:0000151
- [ ] CL:0000182
- [ ] CL:0000197
- [ ] CL:0000219
- [ ] CL:0000312
- [ ] CL:0000329
- [ ] CL:0000343
- [ ] CL:0000540
- [ ] CL:0000628
- [ ] CL:0000725
- [ ] CL:0000762
- [ ] CL:0002062
- [ ] CL:0002079
- [ ] CL:0002080
- [ ] CL:0002088
- [ ] CL:0002301
- [ ] CL:0002323
- [ ] CL:0002488
- [ ] CL:0005011
- [ ] CL:0009002
- [ ] CL:0009103
- [ ] CL:0011115
- [ ] CL:1000488

**Suggested revision and reasons**

Remove direct subclass assertion to 'material entity'

**Comment by bvarner-ebi** [comment]
@dosumis, @cmungall, any concerns with making the changes above?

**Comment by bvarner-ebi** [comment]
@nataled, can you advise where you are seeing these assertions? I checked the first 5 classes in your list and they appear to have SubClass Of 'material entity' inferred, not asserted.

As an example, here is CL:0000039 'germ line cell' before and after running a reasoner:

BEFORE reasoner ('material entity' not asserted):
<img width="510" alt="Screenshot 2023-03-02 at 16 07 42" src="https://user-images.githubusercontent.com/95643797/222484543-5c029246-9f77-4dca-8d29-ff46ee12b657.png">

AFTER reasoner ('material entity' inferred):
<img width="505" alt="Screenshot 2023-03-02 at 16 06 53" src="https://user-images.githubusercontent.com/95643797/222484744-93832559-ab90-4cbf-a791-e70dde7fdad7.png">

**Comment by nataled** [comment]
I downloaded http://purl.obolibrary.org/obo/cl.owl. Can see each of these without inference when looking at children of 'material entity'. I also see the direct source in the OWL file. Both screenshots attached. 
![cl_material_entity](https://user-images.githubusercontent.com/13770634/222503870-eac38c83-39eb-46de-bf52-e51dd63472ad.jpg)
![cl_subclass](https://user-images.githubusercontent.com/13770634/222503875-e7a1f96d-f0e7-462d-b903-df1ddf9873d0.jpg)

**Comment by nataled** [comment]
When looking at the base version, I still don't see what you see. After reasoning the 'material entity' subclass isn't there (I tried ELK, Hermit, and Pellet). Even if I was originally looking at a version that has already gone through reasoning, it strikes me as odd that only this small subset reasoned to 'material entity' and not many, many others.

**Comment by balhoff** [comment]
It's probably inferred from a property range. This would be fixed by asserting a superclass on [cell](http://purl.obolibrary.org/obo/CL_0000000) to link it up with BFO (I would suggest Uberon [material anatomical entity](http://purl.obolibrary.org/obo/UBERON_0000465) or [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)).

Related issue: https://github.com/INCATools/ubergraph/issues/105

**Comment by bvarner-ebi** [comment]
Thank you for the additional feedback, @nataled and @balhoff. My screenshots were from the cl editors' file.
Will touch base with @dosumis on how to proceed.

**Comment by dosumis** [comment]
@balhoff is correct.  I think this is coming from the domain of 'capable of'.  

@bvarner-ebi  please add the axiom [cell](http://purl.obolibrary.org/obo/CL_0000000) subClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) & check that the inferred superclass disappears in Protege.

(This is actually just adding back axiomatization from CARO).

**Comment by bvarner-ebi** [comment]
Thanks for the note, @dosumis. Unfortunately adding the axiom [cell](http://purl.obolibrary.org/obo/CL_0000000) subClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) does not remove the inferred 'material entity' superclass. 

Of note, 'cell' already does have the superclass 'connected anatomical structure'.

In the case of 'germ line cell', the inference does appear to come from 'capable of'.
<img width="974" alt="Screenshot 2023-03-03 at 11 07 14" src="https://user-images.githubusercontent.com/95643797/222705086-29820837-d752-446b-a331-dadeb2ebae26.png">

'located in' also seems to lead to this inference:
<img width="834" alt="Screenshot 2023-03-03 at 11 13 38" src="https://user-images.githubusercontent.com/95643797/222706336-d8f38817-6394-4d72-bd80-701dbcdb2b6f.png">

**Comment by dosumis** [comment]
Uberon may need the link to BFO material entity too.

(Alternative is to use COB, probably works for CL, but has serious problems for alignment with Uberon.)

**Comment by bvarner-ebi** [comment]
> Unfortunately adding the axiom [cell](http://purl.obolibrary.org/obo/CL_0000000) subClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) does not remove the inferred 'material entity' superclass.

> Of note, 'cell' already does have the superclass 'connected anatomical structure'.

Checking this again, I was looking at the wrong 'cell' class in CL. I was looking at CARO:0000013 'cell', which is the first term that appears when searching 'cell' in Protégé. 
Adding superclass 'material entity' to CL:0000000 'cell' appears to fix the issue in this ticket. Apologies for any confusion.
