### ISSUE TITLE
[Logical+Text def] Megakaryocyte

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#1879]
**CL term**
megakaryocyte CL:0000556

**Suggested revision of logical definition**
Remove 'part of' some 'bone marrow' both in the textual definition and in the logical definition, as there are megakaryocytes in the [fetal liver and in the fetal and adult lung](https://ashpublications.org/bloodadvances/article/4/24/6204/474606/Lung-megakaryocytes-display-distinct).

**Comment by addiehl** [comment]
Sounds good to me.
