### ISSUE TITLE
Cell types defined/named by biomarkers

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#1883]
CL ontology has many cell types named with the DE genes. This is specially true with cells from the immune system, but many new cell types from other tissues coming from scRNAseq datasets are subsets of a named cell, with different biomarkers. When these cells are properly named, there is the risk that a new term is created for the same cell type, causing duplications. Should we create cells based only on biomarkers?
Example: [Dermal Dendritic cell (Type 2)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6422157/) might be [langerin-negative dermal dendritic cell](http://purl.obolibrary.org/obo/CL_0002459) in CL.

Comment from @dosumis: "Non-immune:  Don’t make terms based only on scRNAseq -> markers.  We may end up making these as part of jamborees."

Should we establish a policy for immune cells? In the case that we use markers to name cell types:

- We should use in taxon
- Should we use bags of markers similarly to [CCF](https://www.ebi.ac.uk/ols4/ontologies/ccf/classes/https%253A%252F%252Fpurl.org%252Fccf%252FASCTB-TEMP_cd8-t-cell-effector-memory)?

Your input would be very appreciated, @addiehl.

**Comment by addiehl** [comment]
Shall we discuss this issue on the CL call tomorrow, March 15?
