### ISSUE TITLE
CL:0000487 oenocyte, name and definition to review?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#1901]
CL:0000487 oenocyte, name of the class and definition maybe to review ?

the current definition of CL:0000487 in composite-metazoan.obo is restricted to larval oenocyte (as far as I understand):
'def: "A large secretory cell found in clusters underlying the epidermis of the abdominal segments of **larval** abdominal segments." []

while CL:0000487 has a cross-reference to a broader definition:
xref: FBbt:00004995 (oenocyte: 'Large cell located in a cluster or row under the abdominal epidermis, to which it is as attached.')

And in composite-metazoan.obo, the relation
is_a: CL:0000487 ! oenocyte
is present in 2 classes, 

FBbt:00003185 name: adult oenocyte (Drosophila)
and
FBbt:00001694 name: embryonic/larval oenocyte (Drosophila)

I propose to open the definition to something like that:
'def: "A large insect secretory cell of ectodermal origin, found in clusters and segmentally arranged in connection with the fat bodies and tracheae of most insects and that may have important function in fatty acid and hydrocarbon metabolism'. [PMID: 24397521, https://www.merriam-webster.com/dictionary/oenocyte]

And in PMID: 24397521, 
https://pubmed.ncbi.nlm.nih.gov/24397521/
'Oenocytes have also been reported in arachnids and crustaceans ([110](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7613053/#R110), [122](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7613053/#R122)), but it is not yet known whether these are homologous to insect oenocytes and so are not discussed further.'

so maybe the name of CL:0000487 should be 'insect oenocyte' ?

Thank you for your advice.

Anne

**Comment by aleixpuigb** [comment]
Thank you for your request, @ANiknejad.

As you pointed out, the current definition of oenocyte is larval specific and should be revise. However, after a review of the literature, it seems that this cell type has a high variability in size, shape, number in clusters and localisation:


![image](https://user-images.githubusercontent.com/94959119/227175432-03163650-8851-4920-ae46-33b9968fa595.png) 
[PMID:24397521](https://pubmed.ncbi.nlm.nih.gov/24397521/)


![image](https://user-images.githubusercontent.com/94959119/227176960-e1fe08f5-d9d5-49db-aa58-ecda900b998e.png) 
[PMID:34208190](https://www.mdpi.com/2075-4450/12/6/547)


Regarding the taxon restriction, currently oenocyte is `'in taxon' some Arthopoda`. This includes arachnids and crustaceans.
In the case of arachnids, they named large cells oenocytes after a morphologic and functional study. 

![image](https://user-images.githubusercontent.com/94959119/227181490-617a58dd-27a1-4fcb-8ee1-cc0d016e6d8e.png)
https://link.springer.com/article/10.1007/BF00233631

For crustaceans, the authors are careful with the terminology:

![image](https://user-images.githubusercontent.com/94959119/227182316-8223a7bb-00f1-4352-9d0d-b5fdf775f4a6.png)
https://academic.oup.com/jcb/article/29/1/18/2548055

Therefore, I don't think there is a conflict maintaining the class name as oenocyte and keeping it Arthropod restricted.

I propose the following definition: "A secretory cell of ectodermal origin in connection with the fat bodies and tracheae. This cell may have important function in fatty acid and hydrocarbon metabolism'. [PMID:24397521, PMID:34208190, https://www.merriam-webster.com/dictionary/oenocyte]

And a comment: "An oenocyte is highly variable in shape and size across species. This cell typically forms clusters. In adults, oenocytes tend to be smaller but more numerous, while in larvae they are larger and form smaller clusters. [PMID:24397521, PMID:34208190]

Please, let me know if you find these edits satisfactory or if you have any comment. Thank you!

**Comment by aleixpuigb** [comment]
Hi @ANiknejad, I just wanted to check if you are happy with the proposed edits.

**Comment by aleixpuigb** [comment]
Hi @gouttegd, I would appreciate your expertise in the subject for [the edits I have proposed](https://github.com/obophenotype/cell-ontology/issues/1901#issuecomment-1481008113) on this term. Thank you!

**Comment by gouttegd** [comment]
This may need to wait until after the ISB meeting next week, but sure, I’ll have a look. :+1:

**Comment by gouttegd** [comment]
@aleixpuigb Your proposed edits look good to me. I agree with keeping the taxon restriction to arthropods instead of tightening it to only insects.

Maybe we could add a further sentence in the comment: “While oenocytes have been found in arachnids and crustaceans, they have been most abundantly described in insects.” ?

**Comment by aleixpuigb** [comment]
Thank you for the comments, @gouttegd. I agree with extending the comment.
