### ISSUE TITLE
Build general, upper-level slim

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1908]
The aim here is to tag a set of general cell types that would make sense to most biologists as grouping terms. Some judgement will be required in generating this - there is no perfect recipe, although we might gradually evolve some guidelines.

The terms chose should all be in the native cell (classification) branch, although the the immediate children of this term are mostly unsuitable (and any cells under here with no children after reasoning need review).  Example of folding down to a level that is more suitable - neuron and muscle cell look appropriate but their parents do not.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/112839/227902634-704f3930-81ef-49c6-9da9-a9c29fbfd60c.png">

 Some terms may cross metazoans (neuron, muscle cell, epithelial cell), whereas other will be vertebrate specific (leukocyte).    It may be useful to refer to text books on major vertebrate/mammalian cell types or use ChatGPT for inspiration

- [ ] Add upper_cell_type_slim* AP with short definition - subProperty of http://www.geneontology.org/formats/oboInOwl#SubsetProperty (*I'm open to better names!)
- [ ]  Tag a set of high level cell types (see discussion above)
- [ ]  Work with @ubyndr to test coverage under native cell - aiming for 80% coverage (excluding ancestors of slim terms)

**Comment by dosumis** [comment]
Chat GPT Experiment: 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/112839/227905489-6d1a9d46-e4d8-4c27-aad9-8b90ce9fdb1c.png">


Neurons - specialized cells that transmit nerve impulses.
Glial cells - support cells that provide structural and metabolic support for neurons.
Epithelial cells - form the linings of internal and external surfaces of the body.
Muscle cells - contractile cells responsible for movement.
Adipocytes - fat cells that store energy.
Hematopoietic stem cells - give rise to all types of blood cells.
Endothelial cells - line blood vessels and regulate the exchange of materials between the blood and tissues.
Fibroblasts - produce and maintain the extracellular matrix of connective tissue.
Osteoblasts - bone-forming cells.
Osteoclasts - bone-resorbing cells.
Chondrocytes - cartilage-forming cells.
Mast cells - release histamine and other substances in response to injury or inflammation.
Macrophages - phagocytic cells that engulf and destroy pathogens and cellular debris.
T cells - immune cells that coordinate the immune response.
B cells - immune cells that produce antibodies.
Natural killer cells - immune cells that kill infected or cancerous cells.
Dendritic cells - immune cells that present antigens to T cells.
Hepatocytes - liver cells that perform a variety of metabolic functions.
Pancreatic beta cells - produce insulin.
Pancreatic alpha cells - produce glucagon.
Kidney cells - perform a variety of functions related to waste removal and fluid balance.
Sertoli cells - support cells in the testes that help to produce sperm.
Leydig cells - produce testosterone in the testes.
Granulosa cells - support cells in the ovaries that help to produce eggs.
Theca cells - produce hormones in the ovaries.
Keratinocytes - produce the protein keratin, which forms the basis of hair, nails, and the outer layer of skin.
Melanocytes - produce the pigment melanin, which gives color to the skin, hair, and eyes.
Langerhans cells - immune cells in the skin that help to protect against infection.
Smooth muscle cells - contractile cells found in the walls of internal organs, blood vessels, and airways.
Cardiomyocytes - specialized muscle cells that make up the heart.

**Comment by addiehl** [comment]
Interesting result, but I wonder if 30 is too low to catch all the major cell types.  Nice representation of major immune cells in this list though.

**Comment by aleixpuigb** [comment]
Proposed definition for upper_cell_type_slim:
"a subset of general classes in the cell ontology."

-----

High level terms (some are very general (tagged with *) and will be assessed later):

neuron
glial cell
*epithelial cell
*secretory cell
*muscle cell
adipocyte
endothelial cell
fibroblast
osteoblast
osteoclast
chondrocyte
mast cell
macrophage
T cell
B cell
hematopoietic stem cell
natural killer cell
dendritic cell
hepatocyte
enteroendocrine cell
neuroendocrine cell
kidney cell
supporting cell
smooth muscle cell
cardiac muscle cell
skeletal muscle cell
striated muscle cell
male germ cell
female germ cell
seromucus secreting cell
pancreatic endocrine cell
keratinocyte
melanocyte
retinal cell
sensory receptor cell
extraembryonic cell
myeloid cell
glandular epithelial cell

**Comment by emquardokus** [comment]
@aleixpuigb @dosumis

**Comment by dosumis** [comment]
This seems reasonable as a starting point for coverage: 

cartilage 2) bone (osseus), 3) blood, 4) adipose (fat), 5) loose connective tissue 6) dense fibrous connectve tissue 7) elastic connective tissue
3 muscle tissue types:
striated = a) skeletal (voluntary) or b) cardiac) , c smooth muscle
+ eptihelial cell
+ immune cells
- but I'm sure this won't cover enough of the ontology - so maybe start here and extend with other grouping types until coverage is sufficient.

I wouldn't

**Comment by dosumis** [comment]
@bvarner-ebi @aleixpuigb - Can we make it a priority to get something released here.  Needed for Pandasaurus.  We can iterate on it to improve once an initial version is out.
