### ISSUE TITLE
Build immune slim, based on HCA PBMC hierarchy + AD prelim work.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1909]
- [ ] Add immune_slim AP with short definition - subProperty of http://www.geneontology.org/formats/oboInOwl#SubsetProperty
- [ ] Tag a set of high level cell types for immune system - aiming for non-overlapping classifications (if you are very confident they don't overlap - disjointness should be asserted) 
- [ ] Work with @ubyndr to test coverage of all immune cells - aiming for 80-90% coverage

Starting points:  
- HCA PBMC hierarchy from [amcujba](https://github.com/amcujba) 
https://docs.google.com/spreadsheets/d/1K-Z_IWVVEdCA6xo6ca_9aHc3WvYSFTf4-R-xYbINpn4/edit#gid=621727165
- Prior work on immune slims from @addiehl  (Alex - please upload somewhere and link here!)

**Comment by bvarner-ebi** [comment]
@dosumis, will you confirm that this slim is meant to capture both blood and immune cell types? For example, is [erythrocyte](http://purl.obolibrary.org/obo/CL_0000232) expected to appear in this slim?

**Comment by bvarner-ebi** [comment]
Preliminary list:

erythrocyte
megakaryocyte
platelet
erythroblast
‘erythroid progenitor cell’
proerythroblast
reticulocyte
‘nucleated thrombocyte’
‘plasmacytoid dendritic cell’
‘conventional dendritic cell’
‘blood lymphocyte’
‘innate lymphoid cell’
lymphoblast
‘B cell’
B-lymphoblast
‘natural helper lymphocyte’
‘alpha-beta T cell’
‘gamma-delta T cell’
‘immature T cell’
‘mononuclear cell’
basophil
eosinophil
neutrophil
macrophage
‘mast cell’
monocyte
‘multinucleated giant cell’
‘myeloid suppressor cell’
‘nongranular leukocyte’
‘professional antigen presenting cell’
‘hematopoietic lineage restricted progenitor cell’
‘hematopoietic multipotent progenitor cell’
‘hematopoietic oligopotent progenitor cell’
‘hematopoietic stem cell’

@dosumis, @addiehl, kindly share feedback on what terms should be more general or specific.

**Comment by dosumis** [comment]
> @dosumis, will you confirm that this slim is meant to capture both blood and immune cell types? For example, is [erythrocyte](http://purl.obolibrary.org/obo/CL_0000232) expected to appear in this slim?

Good point.  The bionetwork is coming to this with the perspective of supporting datasets based on where they were sampled (blood). But this inevitably covers immune cells elsewhere.  So maybe we should call it blood_immune_slim.

Next steps (besides review by @addiehl and any other experts we could find.

1. Turn this into a ROBOT template in https://github.com/obophenotype/cell-ontology/tree/master/src/templates. The template can follow the pattern used for the CAP organ slim.
2. Work with @ubyndr to test coverage.  For this we will need some way to define grouping classes that subsume everything in the slim.

**Comment by addiehl** [comment]
What is the target number of classes to include?  I started a list yesterday, but it's a bit larger than this.  Also, should we create two lists, one for immune cell types commonly found in blood, and another for the overall immune system?

**Comment by ubyndr** [comment]
I'm reviewing my previous work about coverage report, need to make it more generic, it was tailored for one of our project. As far as I understand, aim is to have 80-90 % coverage with the slim list.

**Comment by dosumis** [comment]
We need some way to define a reference scope for coverage.  In this case we need one or more classes that define this scope, e.g. we might decide that the scope is all cells under

hematopoietic cell *
![image](https://user-images.githubusercontent.com/112839/228648373-4e5358f7-a78b-48ab-960d-36d61e1dfcf0.png)

Coverage is defined as the percentage of cell type within this scope that are subsumed by terms in the slim - excluding superclasses of slim terms, e.g. if the slim contains T-Cell the leukocyte and lymphocyte are excluded from counts of coverage.

![image](https://user-images.githubusercontent.com/112839/228648815-2f54d454-2d13-4981-809d-80ff7ddbabd9.png)


\* maybe hematopoietic_slim would be a better name?

**Comment by dosumis** [comment]
It would also be useful to 

> What is the target number of classes to include?

Use your judgement.  The aim is to provide a useful summary.   Maybe 30-40 terms?  My gut feeling is that it should be  <50, but perhaps I'm wrong and more terms are needed to provide a useful summary with sufficient coverage.

> Also, should we create two lists, one for immune cell types commonly found in blood, and another for the overall immune system?

Won't their be lots of overlap in terms?

**Comment by bvarner-ebi** [comment]
- Seeking consensus on the "short definition" of the slim:

"a collection of cell types related to blood and the immune system, primarily of hematopoietic origin"

---- 

- Seeking consensus on the "name" of the slim:

blood&immune_slim
blood_immune_slim (caveat- may suggest slim scope is focused on immune cells in the blood)
hematopoietic_slim (caveat- may suggest slim scope is focused on hematopoiesis / hematopoietic process)

**Comment by bvarner-ebi** [comment]
> Suggest: blood_and_immune_upper_slim

Thank you for the feedback.
Thoughts on **blood_and_immune_upperslim** or **upperslim_blood_and_immune**?

Context for naming choices: CL currently has slims with names such as organ_slim, uberon_slim, goslim_mouse and goslim_plant.
