### ISSUE TITLE
Build eye slim

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1910]
- [x] Add eye_slim AP with short definition - subProperty of http://www.geneontology.org/formats/oboInOwl#SubsetProperty
- [x] Tag a set of high level cell types for eye asserting disjointness where justified, e.g.  for retina RGC, retinal bipolar neuron, rod, cone, amacrine
- [x] Work with @ubyndr to test coverage of all cell types that overlap the eye - aiming for 80-90% coverage

**Comment by dosumis** [comment]
Chat GPT experiment for inspiration": 

![image](https://user-images.githubusercontent.com/112839/227907560-e71ff4e1-915f-4b53-8b10-eb26dc0d3951.png)

**Comment by aleixpuigb** [comment]
This article can also be good as reference: https://www.sciencedirect.com/science/article/pii/S1350946220300161

**Comment by aleixpuigb** [comment]
Proposed definition for eye_slim:
A  subset of cell types that are found in the eye.

----------
High level terms (with IRI and ID in this file [1910_eye_SLIMS.xlsx](https://github.com/obophenotype/cell-ontology/files/11120078/1910_eye_SLIMS.xlsx))


retinal cell
photoreceptor cell
retinal bipolar neuron
retina horizontal cell
retinal ganglion cell
amacrine cell
corneal epithelial cell
corneal endothelial cell
vertebrate lens cell
scleral cell
iris pigment epithelial cell
choroidal cell of the eye
