### ISSUE TITLE
Review azimuth annotations for new cell types

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1911]

**Comment by bvarner-ebi** [comment]
https://azimuth.hubmapconsortium.org/references/

(comment in progress)


Human - PBMC
--
Annotation group | Note
|---|---|
celltype.l1 | All mapped.
celltype.l2 (default) | All mapped, but some details lost. <br> For example, "AXL+ Dendritic Cell" mapped to '[dendritic cell](http://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_0000451)'; "Proliferating Natural Killer" mapped to '[natural killer cell](http://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_0000623)'
celltype.l3 | All mapped, but several mapped terms are more general. <br> For example, all "gamma-delta T_%N" mapped to '[gamma-delta T cell](http://www.ontobee.org/ontology/CL?iri=http://purl.obolibrary.org/obo/CL_0000798)'

**Comment by emquardokus** [comment]
@dosumis this is the new pipeline being used for Azimuth cell annotations that the New York Genome Center (NYGC) team (Rahul Satija, Gesmira Molla and Austin Hartman) are using: https://github.com/hubmapconsortium/azimuth-annotate cells.

**Comment by dosumis** [comment]
@aleixpuigb  - moving over to you as we don't have any more CAP priority datasets here.  Job for remaining datasets is mostly to map labels to cell types and look for new cell types whilst doing it.

**Comment by aleixpuigb** [comment]
New mappings for the remaining datasets will be submitted in the [azimuth-mapping](https://github.com/hubmapconsortium/azimuth-mapping) repository:

- [ ] Human - PBMC
- [ ] Human - Motor Cortex
- [ ] Mouse - Motor Cortex
- [ ] Human - Pancreas
- [ ] Human - Fetal Development
- [ ] Human - Lung v1
- [ ] Human - Kidney
- [ ] Human - Bone Marrow
- [ ] [Human - Lung v2 (HLCA)](https://github.com/hubmapconsortium/azimuth-mapping)
- [ ] Human - Tonsil
- [ ] Human - Adipose
- [ ] Human - Heart
- [ ] Human - Liver

**Comment by emquardokus** [comment]
@aleixpuigb related issue: Review Specific Kidney cell type annotation mappings on Azimuth to find more detailed CL terms #1972 
https://github.com/obophenotype/cell-ontology/issues/1972

**Comment by aleixpuigb** [comment]
Since this has been moved to a different repo, all the mappings have been done, and the discussion is taking place in the google sheets, I will close this ticket as completed.
