### ISSUE TITLE
Validate HCA bionetwork draft PBMC heirarchy

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1912]
Aim here is to validate the [draft PBMC hierarchy](https://docs.google.com/spreadsheets/d/1K-Z_IWVVEdCA6xo6ca_9aHc3WvYSFTf4-R-xYbINpn4/edit#gid=621727165) generated by @amcujba for the blood cell type reconciliation effort of the HCA

To do this we need to convert the hierarchy into a standard validation table with IDs.  Validation can then be carried out using @anitacaron 's https://pypi.org/project/relation-validator/ lib.  The current hierarchy has only labels (although these should align with CL labels), so an initial mapping is needed (manual or semi-automated).  

Suggested division of work: 

- [x] @aleixpuigb to work with @amcujba on prep (with help from @anitacaron  if needed.  
- [x] @aleixpuigb to work with @anitacaron to use (and test) relation-validator on the prepared data and share results with (and demo validation workflow to  @amcujba.

**Comment by aleixpuigb** [comment]
I have generated a [CT table](https://docs.google.com/spreadsheets/d/1w4vy1tFYdsDSLsNIAhtcxhp3xYuKCUmror_xCrHhF5k/edit?usp=sharing) based on the PBMC hierarchy generated by @amcujba. All cells could be mapped except two:
- progenitor (parent term `innate lymphoid cell`). There is an `immature innate lymphoid cell`, but it is not a progenitor.
- IGA.IGL (parent term `plasma cell`)

@amcujba, are these two cells missing in CL ontology?
@anitacaron, can you use this table for validation? I have used the same format from ASCT+B tables, but let me know if you need a different format.

**Comment by anitacaron** [comment]
Thank you, @aleixpuigb! When using the python lib `relation-validator` we need a simpler table with the columns:



s | slabel | user_slabel | o | olabel | user_olabel
-- | -- | -- | -- | -- | --
the subject term ID | the label of the term in the column s | optional label for the term given by user | the object term ID | the label of the term in the column s | optional label for the term given by user

**Comment by aleixpuigb** [comment]
This is the output of the relation-validator:

|s         |slabel                                                                    |user_slabel                                   |o         |olabel                                                 |user_olabel                                           |
|----------|--------------------------------------------------------------------------|----------------------------------------------|----------|-------------------------------------------------------|------------------------------------------------------|
|CL:0000050|megakaryocyte-erythroid progenitor cell                                   |megakaryocyte-erythroid progenitor cell       |CL:0000556|megakaryocyte                                          |megakaryocyte                                         |
|CL:0000233|platelet                                                                  |platelet                                      |CL:0000556|megakaryocyte                                          |megakaryocyte                                         |
|CL:0000798|gamma-delta T cell                                                        |gamma-delta T cell                            |CL:0000789|alpha-beta T cell                                      |alpha-beta T cell                                     |
|CL:0000786|plasma cell                                                               |plasma cell                                   |CL:0000785|mature B cell                                          |mature B cell                                         |
|CL:0000813|memory T cell                                                             |memory alpha-beta T cell (memory T cell?)     |CL:0000791|mature alpha-beta T cell                               |mature alpha-beta T cell                              |
|CL:0000898|naive T cell                                                              |naive T cell                                  |CL:0000791|mature alpha-beta T cell                               |mature alpha-beta T cell                              |
|CL:0000815|regulatory T cell                                                         |regulatory T cell                             |CL:0000791|mature alpha-beta T cell                               |mature alpha-beta T cell                              |
|CL:0001062|effector memory CD8-positive, alpha-beta T cell, terminally differentiated|effector memory CD8-positive alpha-beta T cell|CL:0001203|CD8-positive, alpha-beta memory T cell, CD45RO-positive|CD8-positive alpha-beta memory T cell, CD45RO-positive|


### These are the proposed fixes for the relations:
- megakaryocyte --> megakaryocyte-erythroid progenitor cell
[megakaryocyte](http://purl.obolibrary.org/obo/CL_0000556) 'develops from' some [megakaryocyte progenitor cell](http://purl.obolibrary.org/obo/CL_0000553).

- megakaryocyte --> platelet
[platelet](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000233?lang=en) 'develops from' some [megakaryocyte](http://purl.obolibrary.org/obo/CL_0000556).

- alpha-beta T cell --> gamma-delta T cell
[gamma-delta T cell](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000798?lang=en) is a sibling of [alpha-beta T cell](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000789?lang=en).

- mature B cell --> plasma cell
(plasma cell)[http://purl.obolibrary.org/obo/CL_0000786] has no relation to [mature B cell](http://purl.obolibrary.org/obo/CL_0000785).

<img width="300" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/94959119/1b3e65d4-3a02-4579-8cc1-d57fa65efbf3">

- mature alpha-beta T cell --> memory T cell
[memory T cell](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000813?lang=en) is too general, it should be under the absent term [mature T cell](http://purl.obolibrary.org/obo/CL_0002419), which should go under [T cell](http://purl.obolibrary.org/obo/CL_0000084).

- mature alpha-beta T cell --> naive T cell
[naive T cell](http://purl.obolibrary.org/obo/CL_0000898) should go under  [mature T cell](http://purl.obolibrary.org/obo/CL_0002419).

- mature alpha-beta T cell --> regulatory T cell
[regulatory T cell](http://purl.obolibrary.org/obo/CL_0000815) should go under  [mature T cell](http://purl.obolibrary.org/obo/CL_0002419).

- CD8-positive, alpha-beta memory T cell, CD45RO-positive --> effector memory CD8-positive, alpha-beta T cell, terminally differentiated
[effector memory CD8-positive, alpha-beta T cell, terminally differentiated](http://purl.obolibrary.org/obo/CL_0001062) is a child of [CD8-positive, alpha-beta memory T cell](http://purl.obolibrary.org/obo/CL_0000909).

**Comment by amcujba** [comment]
Hi, thanks for this @aleixpuigb and @anitacaron. I can double check these changes with the immune bionetwork and get back to you. I believe David will be attending the meeting tomorrow at 2pm, so we can take it from there as well.

**Comment by aleixpuigb** [comment]
Hi @amcujba, based on the proposed changes to validate, I have generated [an updated hierarchy](https://docs.google.com/spreadsheets/d/1w4vy1tFYdsDSLsNIAhtcxhp3xYuKCUmror_xCrHhF5k/edit#gid=801101796). The green cells are the edits (cell has been moved or a term has been added). I am available if you would like to  discuss it in person or in a call.

**Comment by amcujba** [comment]
Hi @aleixpuigb. Please send me your email addresses and I will invite you to our immune bionetwork meeting, where you can share the hierarchy. I can also share it with them before the meeting, if that is okay with you. Thank you.

**Comment by aleixpuigb** [comment]
Hi @amcujba, no problem at all, you can share it. My email address is aleix@ebi.ac.uk. Thanks!

**Comment by aleixpuigb** [comment]
Hi @dosumis, can this ticket be closed as completed?

**Comment by amcujba** [comment]
I have cc'd you in the email to the immune bionetwork, Aleix, apologies for
the delay.

**Comment by aleixpuigb** [comment]
Hi @amcujba, can this ticket be closed as completed? Thank you.

**Comment by aleixpuigb** [comment]
Hi @amcujba, I will close this ticket as completed. Feel free to reopen it if there's something else needed. Thank you.

**Comment by amcujba** [comment]
Hello Aleix,

Could you please contact me via ***@***.***? I do not always check
this email, apologies for the late reply. What would you need me to
provide? more unmatching labels? thank you!
