### ISSUE TITLE
[NTR]glial restricted tripotential precursor cell; chorionic girdle cell; enteric glial cell

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#1913]
Term: glial restricted tripotential precursor cell
Synonyms:
exact: glial restricted precursor PMID:10719353
exact: tripotential glial-restricted precursor cell PMID:11921204
exact: GRP cell PMID:11756508
Definition: Glial restricted tripotential precursor cells are a type of glial precursor cells that can generate oligodendrocytes, type-1 astrocytes, and type-2 astrocytes. They express A2B5, nestin, FGFR-1, 2, and 3, PLP, and DM-20 antigens. They can be isolated from spinal cord at early stages of embryonic development. Unlike O-2A cells, the glial-restricted tripotential precursor cells do not initially express PDGFR-alpha and can differentiate into both A2B51/GFAP1 and A2B52/GFAP1 astrocytes. PMID:10719353
SubClass Of:
progenitor cell CL_0011026
neuron associated cell (sensu Vertebrata) CL_0000123
develops_from glioblast (sensu Vertebrata) CL_0000339 -> check if correct
https://orcid.org/0000-0002-0819-0473
 
Term: chorionic girdle cell
Definition: Chorionic girdle cells are horse-specific highly invasive trophoblast cells that invade the endometrium where they form endometrial cups. PMID:27280409, PMID:35328607
SubClass Of:
trophoblast cell CL_0000351
'part of' chorion membrane UBERON_0003124"
Notes: 
Pregnancy-specific glycoproteins (PSGs) are members of the carcinoembryonic antigen cell adhesion molecule (CEACAM) family that are secreted by trophoblast cells. PSGs are found in species that have a highly invasive (hemochorial) placentation including humans, mice, and rats. Horses, which has a non-invasive epitheliochorial placenta, except for the transient endometrial cup, express PSG-like CEACAMs. Phylogenetic analysis suggests that PSGs from humans and rodents and PSG-like from horses evolved independently. The microenvironment of invasive equine trophoblast cells has striking similarities to the microenvironment of trophoblast cells in hemochorial placentas, suggesting that equine PSG-like CEACAMs and rodent and primate PSGs have undergone convergent evolution. PMID:27280409
https://orcid.org/0000-0002-0819-0473
 
Term: enteric glial cell
Synonyms: 
exact: enteroglial cell PMID:11169131
exact: EGC PMID:3700564
Definition: The enteric glial cells are support for the enteric nervous system. In addition they are involved in enteric neurotransmission, they have an important role in maintaining the integrity of the mucosal barrier of the gut and may serve as a link between the nervous and immune systems of the gut. PMID:17483847 PMID:16336493
SubClass Of :
glial cell CL_0000125
https://orcid.org/0000-0002-0819-0473

**Comment by bvarner-ebi** [comment]
Three (3) new cell types have been added and will be available in the next CL release.

CL:4040000 ‘glial restricted tripotential precursor cell’
CL:4040001 ‘chorionic girdle cell’
CL:4040002 ‘enteroglial cell’
