### ISSUE TITLE
[Class hierarchy] chandelier cell - add GABAergic?

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1915]
**CL term**

chandelier cell CL:4023083 should be subClassOf GABAergic interneuron (may also all be cortical)

**Suggested revision and reasons**

General background reading supports classification as GABAergic.  Text def should be updated accordingly

Current text def records synaptic connectivity to pyramidal cells - might be worth formalising

**Comment by dosumis** [comment]
Would be good to get this fixed.  May require some research to check for supporting refs.

**Comment by bvarner-ebi** [comment]
Proposed edits:

- [ ] **Edit text definition:**
CURRENT: “An interneuron that selectively innervates the axon initial segment of pyramidal cells. Their local axonal clusters are formed by high-frequency branching at shallow angles, often ramifying around, above or below their somata with a high bouton density. The characteristic terminal portions of the axon form short vertical rows of boutons, resembling a chandelier. Chandelier cells can be multipolar or bitufted.”
PROPOSED: A **GABAergic** interneuron that selectively innervates the axon initial segment of pyramidal cells. Their local axonal clusters are formed by high-frequency branching at shallow angles, often ramifying around, above or below their somata with a high bouton density. The characteristic terminal portions of the axon form short vertical rows of boutons, resembling **the candlesticks and candles of** a chandelier. Chandelier cells can be multipolar or bitufted.”

- [ ] **Edit logical defintion:**
CURRENT: interneuron
 and ('has characteristic' some 'chandelier cell morphology')
PROPOSED: GABAergic interneuron
 and ('has characteristic' some 'chandelier cell morphology')
 
 - [ ] **Edit synonym "ChC" from exact --> related, abbreviation**

- [ ] **Add synonym:**
"axo-axonic cell" (broad, PMID:[27199673](https://pubmed.ncbi.nlm.nih.gov/27199673); PMID:[33862423](https://pubmed.ncbi.nlm.nih.gov/33862423))

**Comment by dosumis** [comment]
Looks good to me.
