### ISSUE TITLE
[Text def] Rosehip neuron

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1916]
**CL term**

rosehip neuron has no definition or reference
![image](https://user-images.githubusercontent.com/112839/228872498-1f750a7d-d122-4822-a71e-687bc88f614f.png)

**Suggested revision of textual definition**

This is the primary ref and should be suitable for coming up with a text def https://www.nature.com/articles/s41593-018-0205-2. -

**Comment by bvarner-ebi** [comment]
Thank you for the issue.
Of note, the equivalence axiom invokes mouse specific proteins, although the reference specifically mentions this cell type has not been seen in mouse cortex.

`interneuron and ('has soma location' some 'cortical layer I') and ('capable of' some 'gamma-aminobutyric acid secretion, neurotransmission') and (expresses some 'mast/stem cell growth factor receptor Kit (mouse)') and (expresses some 'netrin-G1 (mouse)') and (expresses some 'short transient receptor potential channel 3 (mouse)')`

"Using unbiased single-nucleus RNA sequencing, we identify ten GABAergic interneuron subtypes with combinatorial gene signatures in human cortical layer 1 and characterize **a group of human interneurons with anatomical features never described in rodents**, having large ‘rosehip’-like axonal boutons and compact arborization. These rosehip cells show an immunohistochemical profile (GAD1+CCK+, CNR1–SST–CALB2–PVALB–) matching a single transcriptomically defined **cell type whose specific molecular marker signature is not seen in mouse cortex**."

In addition to adding a text definition, should these PR terms be switched to human-specific or species-agnostic?

**Comment by dosumis** [comment]
Suggested changes look good. The mouse proteins were clearly a mistake.  Thanks for spotting.
