### ISSUE TITLE
[Typo/Bug] Fixes for abbreviations (narrow/broad)

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1925]
Context: https://github.com/obophenotype/uberon/issues/2363#issuecomment-1446928901

**CL terms**
CL:0000037
CL:0000038
CL:0000040
CL:0000049
CL:0000051
CL:0000134
CL:0000145
CL:0000557
CL:0000595
CL:0000611
CL:0000798
CL:0000936
CL:0001059
CL:0001066
CL:0002066
CL:0002195
CL:0002436
CL:0002453
CL:0002476
CL:0002664
CL:0004120
CL:0004138
CL:0005012
CL:0009106
CL:4023041
CL:4023097
CL:4023122
CL:4028002
CL:4028003
CL:4028004
CL:4028006

**Description of typo, bug or error**
In CL there are several synonyms that are (or include) abbreviations that are not annotated as "related" synonyms and / or are missing the 'abbreviation' annotation property tag. 
This ticket covers mostly synonyms currently annotated as narrow and broad. Given the volume of exact and related synonyms, a separate ticket will be planned.

**Fix**
Make synonyms that are abbreviations "related synonyms" and add 'abbreviation' synonym type.

**Comment by dosumis** [comment]
I guess I wasn't on the call where it was agreed to make all abbreviations 'RELATED'.    We have many examples in FBbt of abbreviations with EXACT scope, backed up by references. 

If we do go ahead with implementing this policy, we need to be careful about knock-on effects on search.  We need to ensure that CL config on OLS & on CAP allow search across RELATED synonyms in CL.

**Comment by bvarner-ebi** [comment]
> We need to ensure that CL config on OLS & on CAP allow search across RELATED synonyms in CL.

Thanks for this concern.

CAP will be fine per @ubyndr, "as we take related synonyms into account".
Per my brief testing, OLS3 returns expected results whether searching for exact or related synonyms. 
OLS4 does not seem to take synonyms into account when generating search results, which may be a bug.

**Comment by dosumis** [comment]
>  Whilst some abbreviations may have an exact meaning as the primary term definition within the context of a particular reference, it may not hold beyond that context or across other domains.

You can say that of almost any synonym.  Within specific references, the scope is clear. Outside of a specific references, scope can only be set by  getting a general impression of use in the literature, which often changes over time and may be domain specific.  Lots of examples from fly - optic lobe neuron  type names have changed in meaning/usage over the past 15 years.; many difference in meaning of the same terms between usage in Drosophila and more generally in insects.

**Comment by dosumis** [comment]
I agree with Shawn that, whatever the policy think we should have well-publicised, general advice on use of synonyms scopes & types in search (& NLP) for CL.    Some ontologies have a lot of very tangentially related terms in the RELATED scope (IIRC, GO is very liberal), whereas others use it more strictly.   This is a major reason that OLS allows configuration of synonym scopes.  If RELATED synonyms work in search for OLS3, this will be due to the custom config for CL in OLS, which we can control.
