### ISSUE TITLE
[Typo/Bug] Equivalence axiom of 'Schwann cell' too broad

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#1926]
**CL term**
CL:0002573 'Schwann cell'

**Description of typo, bug or error**
[Whilst reviewing a PR](https://github.com/obophenotype/cell-ontology/pull/1920#discussion_r1159492931), it was realised that the current equivalence axiom for '[Schwann cell](http://purl.obolibrary.org/obo/CL_0002573)' would incorrectly classify some glial cells as Schwann cells.

**CURRENT EQUIVALENCE AXIOM:**

`'glial cell' and ('part of' some 'peripheral nervous system')`

This causes an 'enteroglial cell' to be inferred as a 'Schwann cell', which seems to be inaccurate.

See also https://doi.org/10.1002/9781118402061.ch8:
There are four major types of glia in the PNS. They are myelinating and non-myelinating Schwann cells, satellite glial cells (SGCs), enteric glial cells (EGCs), and olfactory ensheathing cells (OECs). 

Based on the above, not all glial cells of the PNS are 'Schwann cells'.

**PROPOSED FIX:**
- Remove current equivalence axiom
- add subclass axioms:
   - 'glial cell'
   - 'part of' some 'peripheral nervous system'
- Fix grammar in text definition

**Comment by aleixpuigb** [comment]
@bvarner-ebi, can this issue be closed?
