### ISSUE TITLE
[Obsolete] subclasses of _visual pigment cell (sensu Nematoda and Protostomia)_

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#1930]
[visual pigment cell (sensu Nematoda and Protostomia)](http://purl.obolibrary.org/obo/CL_0001658) has three subclasses:

* [primary pigment cell](http://purl.obolibrary.org/obo/CL_0000727)
* [secondary pigment cell](http://purl.obolibrary.org/obo/CL_0000728)
* [tertiary pigment cell](http://purl.obolibrary.org/obo/CL_0000729)

They have no definitions and are not referenced from anywhere. Given that the parental term is already mapped to its _Drosophila_ counterpart ([FBbt:00004230](http://purl.obolibrary.org/obo/FBbt_00004230)), I don’t think there is a need in CL for those subclasses. People who need to refer to a precise subtype of pigment cell can use one of the FBbt terms (if they’re fly people), or equivalent terms in other nematode or arthropod ontologies.

**Comment by dosumis** [comment]
Agreed

**Comment by aleixpuigb** [comment]
Thank you for your request, @gouttegd.
