### ISSUE TITLE
Intended meaning of _primary neuron_ is unknown

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#1931]
We have the following terms under _neuron_:

* [primary neuron](http://purl.obolibrary.org/obo/CL_0000530)
  * [primary interneuron](http://purl.obolibrary.org/obo/CL_0000534)
  * [primary motor neuron](http://purl.obolibrary.org/obo/CL_0000533)
  * [primary sensory neuron](http://purl.obolibrary.org/obo/CL_0000531)
* [secondary neuron](http://purl.obolibrary.org/obo/CL_0000535)
  * [secondary motor neuron](http://purl.obolibrary.org/obo/CL_0000535)

Because none of them has a definition, it is unknown what is the intended meaning of _primary_ and _secondary_ here.

In FBbt, _primary neuron_ and _secondary neuron_ have a clear meaning: a primary neuron is a neuron that arises during the first wave of neurogenesis (at the embryonic stage), while a secondary neuron is a neuron that arises during the second wave of neurogenesis (at the larval stage).

The concept of “two-stages neurogenesis” is not specific to flies, so it makes sense for CL to have terms referring to neurons born during the “first neurogenesis” and neurons born during the “second neurogenesis” — _if_ that is indeed the meaning that was intended when the above terms were added in CL.

[primary motor neuron](http://purl.obolibrary.org/obo/CL_0000533) is a parent to [CAP motoneuron](http://purl.obolibrary.org/obo/CL_0000532), which again has no definition but is probably the [CaP motoneuron](https://zfin.org/action/ontology/term-detail/ZFA:0009243) of zebrafish (the FZA term has a cross-reference back to the CL term). In ZFA, [primary motor neurons](https://zfin.org/action/ontology/term-detail/ZFA:0009244) are neurons that arise during the first day of development, while [secondary motor neurons](https://zfin.org/action/ontology/term-detail/ZFA:0009247) are neurons that “develop several hours later than primary motor neurons”, which at first sight seems compatible with the general idea that “primary“ and “secondary” refer to the _time_ at which the neurons appear.

On the other hand, _primary motor neuron_ could also easily be understood (especially by people with a “vertebrate mindset”) as “a neuron of the primary motor cortex”, and likewise _secondary motor neuron_ could be “a neuron of the secondary motor areas”. Of note, both _primary motor neuron_ and _secondary motor neuron_ are mapped to equivalent FMA terms ([FMA:83619](http://purl.obolibrary.org/obo/FMA_83619) and [FMA:83620](http://purl.obolibrary.org/obo/FMA_83619), respectively), but since the FMA terms _also_ have no definitions (😩), that does not help a bit…

So:

Does anyone know or remember what was the intended meaning of _primary_ and _secondary_ in the label of the terms above? Was it about timing (where “primary” ≈ “early” and “secondary” ≈ “late”), as in flies and zebrafish?

**Comment by gouttegd** [comment]
Decision from the CL meeting of April 19th 2023: No agreement on what the meaning should be. Those terms should be obsoleted instead of being defined.

**Comment by cerivs** [comment]
Objection to obsoleting these cell terms.  They are the commonly studied neuron types in the developing zebrafish embryos.

**Comment by gouttegd** [comment]
The consensus of the meeting was that such terms do not belong in CL. People needing them can use the ZFA terms (for zebrafish) or the FBbt terms (for flies).

**Comment by cerivs** [comment]
The ZFA terms are the zebrafish instance of the CL term.   The first mention on Github of any problem with the term was only last week.  The meeting was one week later.  CL was originally unifying the cell components of the various species specific ontologies similar to how UBERON works for gross anatomy.    If CL is acting as the source for all cells then sufficient time should be given to allow the community to review proposals and come up with definitions.     One week notice is not sufficient for terms to be made obsolete.

**Comment by cerivs** [comment]
@balhoff Are any of the Phenoscape products that use primary neuron?

**Comment by balhoff** [comment]
> @balhoff Are any of the Phenoscape products that use primary neuron?

No, all clear I think.

**Comment by cerivs** [comment]
If we want to define the term we could use this.  
PMID:1842357 
Primary neurons develop shortly during early segmentation stages, before the neural tube is formed. Each neuron occurs in a stereotyped location along the neuraxis.   Axons from these cells grow via a growth cone  along a stereotyped pathway.  These axons form the pattern of the early nervous system.  

I still need to contact researchers from the medaka community.
