### ISSUE TITLE
Should 'follicle stem cell' be insect-specific?

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#1943]
[follicle stem cell](http://purl.obolibrary.org/obo/CL_0000441) has no definition. It is mapped to FBbt’s [follicle stem cell](http://purl.obolibrary.org/obo/FBbt_00004903).

I wonder if the term should be labelled and defined as being specific to insects. “Follicle cells” in insects (represented in CL as [follicle cell of egg chamber](http://purl.obolibrary.org/obo/CL_0000477) are quite different from “follicular cells” in other species (represented in CL as [follicular cell of ovary](http://purl.obolibrary.org/obo/CL_0002174)), and while in insects it it clear that all follicle cells derive from well-identified “follicle stem cells”, I am not sure it is the case for all follicular cells in other species. The mere existence of stem cells in ovaries seems debated (e.g. https://ovarianresearch.biomedcentral.com/articles/10.1186/s13048-020-00647-2).

I am inclined to rename CL:0000441 as “insect follicle stem cell”, add the appropriate taxon restriction and define it accordingly.

**Comment by addiehl** [comment]
There are also hair follicle stem cells to consider: [https://jbiomedsci.biomedcentral.com/articles/10.1186/s12929-020-0624-8](https://jbiomedsci.biomedcentral.com/articles/10.1186/s12929-020-0624-8)
