### ISSUE TITLE
'CNS interneuron' is loosely defined but tightly classified

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#1960]
[CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) is logically defined as [interneuron](http://purl.obolibrary.org/obo/CL_0000099) and [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017).

None of the terms of the logical definition are taxon-restricted (well, strictly speaking they are, but at a very high level: [Metazoa](http://purl.obolibrary.org/obo/NCBITaxon_33208) for [interneuron](http://purl.obolibrary.org/obo/CL_0000099) and [Bilateria](http://purl.obolibrary.org/obo/NCBITaxon_33213) for [central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017) – for the purpose of this ticket I will treat that as an absence of taxon restrictions), meaning that the logical definition casts a very wide net and will catch any interneuron that happens to have its cell body in a central nervous system in any species. Obviously this includes, for example, some _Drosophila melanogaster_ interneurons.

_But_ [CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) is _also_ classified as a [CNS neuron (sensu Vertebrata)](http://purl.obolibrary.org/obo/CL_0000117), which, as the label suggests, is restricted to vertebrates (through [neuroblast (sensu Vertebrata)](http://purl.obolibrary.org/obo/CL_0000031)).

This single term is therefore responsible for the unsatisfiability of ~3,400 fly interneurons when Uberon, CL, and FBbt are merged and taxon constraints are enforced.

Either [CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) is intended to be taxon-neutral (as its wide logical definition implies), in which case the SubClassOf [CNS neuron (sensu Vertebrata)](http://purl.obolibrary.org/obo/CL_0000117) should be removed, or it is intended to be vertebrate-specific, in which case the logical definition should be tightened.

I favour the first solution, as I see no reason why [CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) should be vertebrate-specific.

**Comment by lubianat** [comment]
+1 for the proposed solution
