### ISSUE TITLE
[NTR] intermediate cell of urothelium, umbrella cell of urothelium

### ISSUE THREAD

**Issue by jenjou** [obophenotype/cell-ontology#1975]
**Preferred term label**
intermediate cell of urothelium

**Synonyms** (add reference(s), please)
N/A

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A regenerative layer of cells directly above basal cells in the urothelium.

See PMID:36180582
Corresponds to FMA:84155 Intermediate cell of urothelium

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
CL:0000731  urothelial cell

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
UBERON:0000365 Urothelium

----
**Preferred term label**
umbrella cell of urothelium

**Synonyms** (add reference(s), please)
superficial cell of urothelium, facet cell of urothelium

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
Fully differentiated cells on the apical surface of the urothelium that function as a barrier.

See PMID:36180582
Corresponds to FMA:84149 Umbrella cell of urothelium

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl)
CL:0000731  urothelial cell

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
UBERON:0000365 Urothelium

----

**Your ORCID**
https://orcid.org/0000-0003-3065-9183

**Additional notes or concerns**
These two terms form a "set" with the 3rd cell type of the urothelium, CL:1000486 basal cell of urothelium.

**Comment by bvarner-ebi** [comment]
@jenjou, thank you for these new terms.
Below are some proposed updates.
Can you advise if you agree or what should be added/removed?

----

**Preferred term label** 
intermediate cell of urothelium

**Synonyms**
 urothelial intermediate cell
(exact, doi:10.1007/978-3-030-14366-4_8)

**Definition**
A urothelial cell that is part of the regenerative layer(s) of cells directly superficial to basal cells in urothelium. The layer of intermediate cells in the urothelium ranges from one to several layers thick depending on the species with intermediate cells attached to adjacent cell layers and one another via desmosomes.
doi:10.1038/s41385-022-00565-0

**dbxref** FMA:84155

**Parent cell type term**
 CL:0000731 'urothelial cell'
 
**What is the anatomical structure that the cell is a part of?**
 UBERON:0000365 urothelium
 
**Comment**
It has been noted in at least some mammalian species that the urothelial intermediate cell type is similar to basal cells by expressing CK17 and (unlike umbrella cells) p63 but is positive for uroplakins (UPK) and negative for CK5. Urothelial intermediate cells have also been noted to be larger in diameter than urothelial basal cells.
doi:10.1038/s41385-022-00565-0

Contributor: https://orcid.org/0000-0003-3065-9183
---

**Preferred term label** 
umbrella cell of urothelium

**Synonyms**
superficial cell of urothelium
facet cell of urothelium
(exact, doi:10.1038/s41385-022-00565-0)

**Definition**
A urothelial cell that is terminally differentiated and part of the urothelial apical surface that forms the high-resistance barrier of urothelium. Umbrella cells have been described as the largest of urothelial cell types, highly polarized, and, in some species, multinucleated. In the relaxed state, these cells form a dome-shaped structure at the apical pole and can also cover multiple underlying intermediate cells, leading to the name umbrella cells. In contrast, these cells flatten when the bladder is filled.
doi:10.1038/s41385-022-00565-0

**dbxref** FMA:84149 

**Parent cell type term**
 CL:0000731 'urothelial cell'

**What is the anatomical structure that the cell is a part of?**
UBERON:0000365 urothelium

**Comment:**
Umbrella cells are attached to sub-superficial cell layers via desmosomes, while tight junctions localized between superficial cells aid in forming a high-resistance barrier function. Another distinguishing feature of an umbrella cell type is the presence of subapical discoidal/fusiform-shaped vesicles contributing to the plasticity in urothelial cell surface area through a regulated process of endocytosis/exocytosis. It has been noted in at least some mammalian species that the urothelial umbrella cell type expresses UPK1A, UPK1B, UPK2 and UPK3A. Unlike intermediate and basal cells of the urothelium, CK17 is reported to be completely absent and p63 not expressed in umbrella cells.

Contributor: https://orcid.org/0000-0003-3065-9183

**Comment by bvarner-ebi** [comment]
@jenjou, thank you for the new term request.
The following have been added to CL and will be available in the next release:

CL:4030051 'intermediate cell of urothelium'
CL_4030052 'umbrella cell of urothelium'
