### ISSUE TITLE
Potential new cell types & mappings for whole human brain scRNAseq dataset

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1980]
Paper: https://doi.org/10.1101/2022.10.12.511898 Siletti et al., 2022 bioRxiv Transcriptomic diversity of cell types across the adult human brain
[supplementary-material](https://www.biorxiv.org/content/10.1101/2022.10.12.511898v1.supplementary-material)

Supplementary material table 2 has two columns that are potentially mappable to cell types:

`Supercluster` - Shawn worked on mapping and adding terms - see #1743 for details.  This work is mostly done but it might be worth following up the unchecked items on Shawn's list - particularly grouping of types derived from upper and lower rhombic lip.

`Subtype auto-annotation`:    Review contents of this column - referring back to text of paper to work out if we should add a new cell type to CL or whether we have an existing type that could be mapped to.

This is a uniq'd list of entries in `Subtype auto-annotation` column + some potential mappings.  But note - it can be useful to look at the context of the rest of the row in table 1 to work out what is being referred to.

Table entry | Mapping
-- | --  
ABC PIA | 
ARACH | 
ARTERIOLE ARTERY | 
ARTERIOLE CAP | 
CAP | 
CB-GRAN | cerebellar granule cell (CL:0001031)
CB-GranLayerInt | 
CB-MolLayerInt1 | 
CB-MolLayerInt1 CB-MolLayerInt2 | 
CB-MolLayerInt2 | 
CB-PURK | Purkinje cell (CL:0000121)
CB-PurkLayerInt | 
CHAND | chandelier cell (CL:4023083)
COP | 
DG-GRAN | TBA  dentate gyrus granule cell (have not found detail in paper)
FIBMYO | 
INT-LAMP5 | 
INT-LAMP5-LHX6 | 
INT-PVALB | 
INT-SST | 
INT-SST INT-SST-CHODL | 
INT-SST-CHODL | 
INT-VIP | 
L5-ET | L5 extratelencephalic projecting glutamatergic cortical neuron (CL:4023041)
L5-ET VonEcon |  TBA - von Economo neuron
MSN-D1 | 
MSN-D1 MSN-D2 MSN-ECC | 
MSN-D1 MSN-ECC |  
MSN-D2 | 
PIA | 
PIA PVF | 
UBC | 
VENOUS | 

- [x] #1990
- [ ] ...

**Comment by dosumis** [comment]
CC @hkir-dev

**Comment by dosumis** [comment]
Uniq'd list of entries in `Subtype auto-annotation` column + some potential mappings

Table entry | Mapping
-- | --  
ABC PIA | 
ARACH | 
ARTERIOLE ARTERY | 
ARTERIOLE CAP | 
CAP | 
CB-GRAN | cerebellar granule cell (CL:0001031)
CB-GranLayerInt | 
CB-MolLayerInt1 | 
CB-MolLayerInt1 CB-MolLayerInt2 | 
CB-MolLayerInt2 | 
CB-PURK | Purkinje cell (CL:0000121)
CB-PurkLayerInt | 
CHAND | 
COP | 
DG-GRAN | TBA - 
FIBMYO | 
INT-LAMP5 | 
INT-LAMP5-LHX6 | 
INT-PVALB | 
INT-SST | 
INT-SST INT-SST-CHODL | 
INT-SST-CHODL | 
INT-VIP | 
L5-ET | 
L5-ET VonEcon |  TBA - von Economo neuron
MSN-D1 | 
MSN-D1 MSN-D2 MSN-ECC | 
MSN-D1 MSN-ECC |  
MSN-D2 | 
PIA | 
PIA PVF | 
UBC | 
VENOUS | 


 - [ ] NTR - von Economo Neuron

**Comment by dosumis** [comment]
Next steps:
@bvarner-ebi  to work with @hkir-dev  to get these mappings into the while human brain PCL build.
@dosumis  to contact Siletti to suggest meeting to discuss further & ask if she is happy to provide answers to more questions.

**Comment by bvarner-ebi** [comment]
@hkir-dev, can you comment on [the mappings above](https://github.com/obophenotype/cell-ontology/issues/1980#issuecomment-1559625722) and if you need further input from me?

**Notes on mappings:**
Question marks (?) signify best guesses.
Hyphens (-) are next to aggregates of other entries - I don't have a recommendation on how those should be mapped.
Otherwise, if there is no question mark, those terms can be mapped to the dataset entries.

My understand is that @dosumis would like to move forward using the confident mappings (those with no "?").
