### ISSUE TITLE
[Logical def] platlet

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1986]
**CL term**

[platelet](http://purl.obolibrary.org/obo/CL_0000233) EquivalentTo:
['myeloid cell'](http://purl.obolibrary.org/obo/CL_0000763) *and* ['has characteristic'](http://purl.obolibrary.org/obo/RO_0000053) *some* [**anucleate**](http://purl.obolibrary.org/obo/PATO_0001405)) 
*and* (['has characteristic'](http://purl.obolibrary.org/obo/RO_0000053) *some* [discoid](http://purl.obolibrary.org/obo/PATO_0001874))
 *and* (['capable of'](http://purl.obolibrary.org/obo/RO_0002215) *some* ['blood coagulation'](http://purl.obolibrary.org/obo/GO_0007596)) 
*and* (['capable of'](http://purl.obolibrary.org/obo/RO_0002215) *some* ['blood circulation'](http://purl.obolibrary.org/obo/GO_0008015))

**Suggested revision of logical definition**

~The equivalence axiom does not appear to do any useful work in classification, so I think should be relaxed to subClassOf.

Two other corrections are needed:

1. 'capable of' to 'capable of part of'

(['capable of'](http://purl.obolibrary.org/obo/RO_0002215) *some* ['blood coagulation'](http://purl.obolibrary.org/obo/GO_0007596)) 
Is not correct.  Although platelets are critical to the process, other factors (outside of platelets) are involved.

2. '(['capable of'](http://purl.obolibrary.org/obo/RO_0002215) *some* ['blood circulation'](http://purl.obolibrary.org/obo/GO_0008015)) <-- this should just be dropped, here and anywhere else it is used. It seems to be used to mean capable of circulating in the blood, but the term is defined as: "The flow of blood through the body of an animal, enabling the transport of nutrients to the tissues and the removal of waste products." It's hard to imagine how a cell could be capable of that. If we really need a way to record blood cells as circulating we should use a different pattern.

**Comment by addiehl** [comment]
Works for me. Representation of an earlier period in CL development when we were trying to capture most characteristics in equivalence axioms rather than subclass axioms without regard as to whether they represent coherent necessary and sufficient conditions to define a cell type.
