### ISSUE TITLE
[NTR] lung resident memory CD8-positive CD103-positive, alpha-beta T cell

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#1994]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label**
lung resident memory CD8-positive, CD103-positive, alpha-beta T cell

**Synonyms** (add reference(s), please)
lung resident memory CD8-positive CD103-positive, alpha-beta T cell [PMID:27776108](https://www.nature.com/articles/ni.3589)
lung TRM CD8-positive CD103-positive cell  [PMID:27776108](https://www.nature.com/articles/ni.3589)
lung TRM CD8-positive integrin  alpha E-positive cell [PMID:27776108](https://www.nature.com/articles/ni.3589)

**Definition** 
A lung resident memory CD8-positive CD103-positive, alpha-beta T cell that is CD103-positive. [PMID:27776108](https://www.nature.com/articles/ni.3589)

**Parent cell type term** 
[lung resident memory CD8-positive, alpha-beta T cell](http://purl.obolibrary.org/obo/CL_4033039) and ('has plasma
membrane part' some [integrin alpha-E](http://purl.obolibrary.org/obo/PR_000001010))

**What is the anatomical structure that the cell is a part of?** (check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon)
lung (should be inferred)

**Your ORCID**
https://orcid.org/0000-0001-6677-8489
https://orcid.org/0000-0002-9185-3994

**Additional notes or concerns**

**Comment by aleixpuigb** [comment]
FYI @addiehl

**Comment by addiehl** [comment]
Looks good to me.
