### ISSUE TITLE
New medium spiny neuron subtypes + other striatal neuron types

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1996]
Potential new subtypes of medium spiny neuron to curate from this paper + synonyms for existing subtypes
https://pubmed.ncbi.nlm.nih.gov/34727523/.  Also some details on striatal interneurons.  

There is some multi-modal data here that might be sufficient to define new neuron types initially identifed by scRNAseq

**Comment by bvarner-ebi** [comment]
Note: paper focuses on primate striatum.
