### ISSUE TITLE
xrefs for papers should use PMID or DOI - not journal URLs

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#1997]
Found one example on rosehip neujron.  Here may be others.

<img width="873" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/7083c71d-59b3-4164-809b-d2c40244080a">

**Comment by bvarner-ebi** [comment]
[SPARQL query results here](https://api.triplydb.com/s/X2-aXnsKE).

After a cursory review of the results, the following dbxrefs are flagged to be fixed: 

source | property | dbXref | comment
-- | -- | -- | --
obo:CL_0000382 | obo:IAO_0000115 | "doi:https://doi.org/10.1016/B978-012369493-5.50012-2"^^<http://www.w3.org/2001/XMLSchema#string> | remove extra doi:
obo:CL_0000396 | obo:IAO_0000115 | "doi:https://doi.org/10.1016/B978-012369493-5.50008-0"^^<http://www.w3.org/2001/XMLSchema#string> | remove extra doi:
obo:CL_0002437 | obo:IAO_0000115 | "http:www.immgen.org/index_content.html"^^<http://www.w3.org/2001/XMLSchema#string> | add // after http:
obo:CL_0002506 | obo:IAO_0000115 | "http:http://www.immgen.org/index_content.html"^^<http://www.w3.org/2001/XMLSchema#string> | remove extra http:
obo:CL_4030003 | obo:IAO_0000115 | <https://www.nature.com/articles/s41467-020-20082-7> | replace with PMID or doi
obo:CL_0000158 | obo:IAO_0000115 | "DOI:https://doi.org/10.1378/chest.12-2762"^^<http://www.w3.org/2001/XMLSchema#string> | remove extra doi:
obo:CL_4030040 | obo:IAO_0000115 | "https://www.nature.com/articles/s41591-020-1040-z"^^<http://www.w3.org/2001/XMLSchema#string> | replace with PMID or doi
obo:CL_4030042 | obo:IAO_0000115 | "https://www.nature.com/articles/s41591-020-1040-z"^^<http://www.w3.org/2001/XMLSchema#string> | replace with PMID or doi
obo:CL_4030041 | obo:IAO_0000115 | "https://www.nature.com/articles/s41591-020-1040-z"^^<http://www.w3.org/2001/XMLSchema#string> | replace with PMID or doi
obo:CL_0002505 | obo:IAO_0000115 | "http:http://www.immgen.org/index_content.html"^^<http://www.w3.org/2001/XMLSchema#string> | remove extra http:
obo:CL_4030001 | obo:IAO_0000115 | <https://www.nature.com/articles/s41467-020-20082-7> | replace with PMID or doi
obo:CL_0000998 | obo:IAO_0000115 | "http:www.immgen.org/index_content.html"^^<http://www.w3.org/2001/XMLSchema#string> | add // after http:

Of note, several potential "broad" dbxrefs were noted that do not point to the specific page used for reference, e.g., "http://www.immgen.org/index_content.html", "http://www.cap.org".
