### ISSUE TITLE
NCIt Term Suggestions for Cross-Reference

### ISSUE THREAD

**Issue by ssyeds3** [obophenotype/cell-ontology#1999]
The NCI Cancer Research Data Commons (CRDC) Program (https://datacommons.cancer.gov/) is developing data standards for submitting data to the CRDC ecosystem. As part of this effort, the CRDC Data Standards Service (DSS) Team is identifying industry standards that can be leveraged for this harmonization and standardization effort. 

In the process of mapping valid values between various ontologies and NCIt we (the DSS Team) came across terms in the CL ontology that did not have a cross-reference to NCIt terms (please see below):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/syeds3/AppData/Local/Temp/1/msohtmlclip1/04/clip.htm">
<link rel=File-List
href="file:///C:/Users/syeds3/AppData/Local/Temp/1/msohtmlclip1/04/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

CL Term | CL ID | NCIt Term   Suggestion for Cross-Reference
-- | -- | --
bladder urothelial cell | CL:1001428 | Bladder   Urothelial Cell (C32210)
germ cell | CL:0000586 | Germ   Cell (C12597)
fibroblast | CL:0000057 | Fibroblast   (C12482)
leukocyte | CL:0000738 | Leukocyte   (C12529)

</body>

</html>

**Comment by bvarner-ebi** [comment]
@ssyeds3, thank you for these mappings.
They have been added to the CL terms noted above and will be present in the next CL release.
