### ISSUE TITLE
should epithelial cell and neuron be disjoint?  are epithelial cell and neuron disjoint?  

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#2]
```
I would have thought so, but 'taste receptor cell' is (indirectly) a neuron, 
but also a sensory epithelial cell and an endo-epithelial cell.
Complete list of classes:

'auditory hair cell'
'cochlear inner hair cell'
'macular hair cell'
'outer hair cell'
'taste receptor cell'
'type I taste bud cell'
'type II taste cell'
'type III taste bud cell'
'type IV taste receptor cell'
'type V taste receptor cell'

It may be that we need some overlap between these classes, but this should be 
discussed/investigated further.

```

Original issue reported on code.google.com by `dosu...@gmail.com` on 24 Feb 2012 at 1:58

**Comment by paolaroncaglia** [comment]
> ```
> I would have thought so, but 'taste receptor cell' is (indirectly) a neuron, 
> but also a sensory epithelial cell and an endo-epithelial cell.
> Complete list of classes:
> 
> 'auditory hair cell'
> 'cochlear inner hair cell'
> 'macular hair cell'
> 'outer hair cell'
> 'taste receptor cell'
> 'type I taste bud cell'
> 'type II taste cell'
> 'type III taste bud cell'
> 'type IV taste receptor cell'
> 'type V taste receptor cell'
> 
> It may be that we need some overlap between these classes, but this should be 
> discussed/investigated further.
> ```
> 
> Original issue reported on code.google.com by `dosu...@gmail.com` on 24 Feb 2012 at 1:58

'epithelial cell' and 'neuron' are not disjoint at present. Like @dosumis , I'm not sure if they should be, but I'm commenting to prevent staleness. Any opinions? Or ok to close?

**Comment by bvarner-ebi** [comment]
Hi, @shawntanzk, tagging you on this neuron-related. It seems it can be closed.

**Comment by shawntanzk** [comment]
I think it shouldnt be disjoint given the above, closing issue, please reopen if anyone objects
