### ISSUE TITLE
pre-type 2 pneumocyte

### ISSUE THREAD

**Issue by paulacalipho** [obophenotype/cell-ontology#2001]
**Preferred term label:** pre-type 2 pneumocyte

**Synonyms**
pre-type II alveolar epithelial cell PMID:12114192
alveolar pre-type II epithelial cell PMID:9624168

**Definition**
Precursor of type II pneumocyte that does not yet produce surfactant. These cells do not have lamellar bodies, which are a marker of type II pneumocyte maturity. PMID:1316350
Curator note: A central feature of the fetal respiratory distress syndrome seems to be the presence in the lung of abundant pre-type II alveolar epithelial cells. PMID:1316350

**Parent term**
pneumocyte CL:0000322

**ORCID**
https://orcid.org/0000-0002-0819-0473

**Comment by bvarner-ebi** [comment]
@paulacalipho, thank you for adding CL:4040003 'fetal pre-type II pneumocyte'.
It will appear in the next Cl release.

**Comment by paulacalipho** [comment]
@bvarner-ebi thanks for your input and help
