### ISSUE TITLE
[NTR] ventral striatum medium spiny neurons subtypes

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#2006]
**Preferred term label**
nucleus accumbens shell and olfactory tubercle D1 medium spiny neuron

**Synonyms**
NAc shell and OT D1 medium spiny neuron
(exact, doi:10.1016/j.cub.2021.10.015)
NAc shell and OT D1-MSN
D1Sh
(related, abbr, doi:10.1016/j.cub.2021.10.015)

**Definition**
A DRD1-expressing medium spiny neuron that is part of a nucleus accumbens shell or olfactory tubercle.
(doi:10.1016/j.cub.2021.10.015)

**Parent cell type term**
CL:1001474 'medium spiny neuron'

**What is the anatomical structure that the cell is a part of?**
UBERON:0005403 'ventral striatum'
note in text def:  UBERON:0012171 ‘shell of nucleus accumbens’, UBERON:0001883 ‘olfactory tubercle’

**Additional notes or concerns**
In Rhesus macaques, both nucleus accumbens shell and olfactory tubercle D1 and D2 medium spiny neuron cell types have been noted to have enriched gene expression of the following: GREB1L, ARHGAP6, and GRIA4.
(doi:10.1016/j.cub.2021.10.015)

----

**Preferred term label**
nucleus accumbens shell and olfactory tubercle D2 medium spiny neuron

**Synonyms**
NAc shell and OT D2 medium spiny neuron
(exact, doi:10.1016/j.cub.2021.10.015)
nucleus accumbens shell and olfactory tubercle D2-MSN
NAc shell and OT D2-MSN
D2Sh
(related, abbr, doi:10.1016/j.cub.2021.10.015)

**Definition**
A DRD2-expressing medium spiny neuron that is part of a nucleus accumbens shell or olfactory tubercle.
(doi:10.1016/j.cub.2021.10.015)

**Parent cell type term**
CL:1001474 'medium spiny neuron'

**What is the anatomical structure that the cell is a part of?**
UBERON:0005403 'ventral striatum'
note in text def:  UBERON:0012171 ‘shell of nucleus accumbens’, UBERON:0001883 ‘olfactory tubercle’

**Additional notes or concerns**
In Rhesus macaques, both nucleus accumbens shell and olfactory tubercle D1 and D2 medium spiny neuron cell types have been noted to have enriched gene expression of the following: GREB1L, ARHGAP6, and GRIA4.
(doi:10.1016/j.cub.2021.10.015)

----

**Preferred term label**
Island of Calleja granule cell

**Synonyms**
D1-ICj
(related, abbr, doi:10.1016/j.cub.2021.10.015)

**Definition**
A DRD1-expressing, medium spiny neuron-like granule cell that is part of an Island of Calleja.
(doi:10.1016/j.cub.2021.10.015)

**Parent cell type term**
CL:0000120 'granule cell'

**What is the anatomical structure that the cell is a part of?**
(‘island of Calleja’
  and ('part of' some 'ventral striatum'))

**Additional notes or concerns**
In Rhesus macaques, the Island of Calleja granule cell type has been noted to have enriched gene expression of CPNE4.
(doi:10.1016/j.cub.2021.10.015)

----

**Preferred term label**
RXFP1-positive interface island D1-medium spiny neuron

**Synonyms**
RXFP1-positive island D1-medium spiny neuron
(exact, doi:10.1016/j.cub.2021.10.015)
D1-NUDAP
(related, abbr, doi:10.1016/j.cub.2021.10.015)

**Definition**
A DRD1-expressing medium spiny neuron that is part of dense, RXFP1-positive cell islands throughout the nucleus accumbens, putamen, and near the adjacent septal nuclei.
(doi:10.1016/j.cub.2021.10.015)

**Parent cell type term**
CL:1001474 'medium spiny neuron'

**What is the anatomical structure that the cell is a part of?**
UBERON:0005403 'ventral striatum'
note in text def:  UBERON:0001882 'nucleus accumbens', UBERON:0001874 putamen, UBERON:0002663 'septal nuclear complex'

**Additional notes or concerns**
comment: Regarding the abbreviation D1-NUDAP, NUDAP stands for "neurochemically unique domains in the accumbens and putamen". In Rhesus macaques, the RXFP1-positive interface island D1-medium spiny neuron (D1-NUDAP) has been noted to have upregulation of _OPRM1_ compared to DRD1-expressing medium spiny neurons located outside of the D1-exclusive island and in Islands of Calleja. Kappa-opioid receptor gene (_OPRK1_) has been noted to be absent from D1-NUDAP cells. Many striosome-specific markers have been noted to be upregulated in D1-NUDAP cells, including _KCNIP1_, _KCNT1_, _KHDRBS3_, and _BACH2_. _PDYN_, an acknowledged D1-striosome marker gene, has also been noted to be expressed in D1-NUDAPs. D1-NUDAPs also express some genes found to be selectively expressed in the matrix, including _STXBP6_, _GDA_, and _SEMA3E_. Gene enrichment analysis has revealed that D1-NUDAP neurons express genes that have been implicated in drug addiction and many other functions.
(doi:10.1016/j.cub.2021.10.015)

**Comment by dosumis** [comment]
CC @jeremymiller  - do you have time to look over these?  Thanks!

**Comment by dosumis** [comment]
CC @UCDNJJ - would you be able to review these terms for us.  Thanks!
