### ISSUE TITLE
Make new issue template for epic tickets for new design patterns

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2027]
Use this as the basis for the new template: https://github.com/obophenotype/cell-ontology/issues/1884

@anitacaron  to look into whether we can spawn subtickets automagically.

**Comment by anitacaron** [comment]
If you create the template with the task list, you can quickly turn them into issues later.

![Screenshot 2023-06-23 at 10 36 38](https://github.com/obophenotype/cell-ontology/assets/2208124/6353658a-7516-4470-92bd-8acd3dd58018)
