### ISSUE TITLE
Update search widget on github.io site to use OLS4

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2039]
Still using OLS3: https://cell-ontology.github.io/index.html#ols_search

From James:  "No new widget yet. Best to use the existing widget just change the backend url to ols4"

Should work fine as new API is meant to be backwards compatible with OLS4.

**Comment by hkir-dev** [comment]
In the new OLS all single values are turned into list, so just changing to `ols4` didn't worked. 

https://www.ebi.ac.uk/ols/api/select?q=gaba&ontology=cl
https://www.ebi.ac.uk/ols4/api/select?q=gaba&ontology=cl

Updating and testing the widget script now.

**Comment by anitacaron** [comment]
@dosumis, the imports were just updated before the new release yesterday.

**Comment by hkir-dev** [comment]
The new API has many missing fields in the response `responseHeader` and this is blocking the adaptation of the widget script. 

@dosumis can we request OLS team to test the widget and apply required API and widget changes?

**Comment by hkir-dev** [comment]
Thanks to James widget is working now (https://github.com/EBISPOT/ols4/issues/401). 

https://cell-ontology.github.io/index.html#ols_search is using OLS4 now

**Comment by dosumis** [comment]
Wondering if it is possible to restrict to subClasses of cell (can't remember if we had this before).  Right now it also returns imported terms (e.g. from GO).

**Comment by hkir-dev** [comment]
Seems `local=true` param will do the job. Updated the OLS script accordingly.

https://www.ebi.ac.uk/ols/docs/api
https://www.ebi.ac.uk/ols4/api/select?q=gaba&ontology=cl&local=true
