### ISSUE TITLE
[Update] retina-related bionetwork terms updates

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#2044]
Context: #1974

The following edits are derived from review of the Retina bionetwork and cellXgene references:

CL label | Edit | dbxref
-- | -- | --
Mueller cell | Add "Muller cell" as exact syn with prop type MISSPELLING. | doi:10.21769/BioProtoc.4179
amacrine cell | Add "AC" as related syn, abbreviation.  Add "ACs" as related syn, abbreviation, plural. | doi:10.1038/s41598-020-66092-9
retinal bipolar neuron | Add "BC" as related syn, abbreviation. Add "BCs" as related syn, abbreviation, plural. | doi:10.1038/s41598-020-66092-9
retinal cone cell | Add "cone" as related syn. | doi:10.1038/s41598-020-66092-9
retina horizontal cell | Add "HC" as related, abbreviation. Add "HCs" as related, abbreviation, plural. | doi:10.1038/s41598-020-66092-9
macroglial cell | Add "macroglia" as related, plural. | doi:10.1152/physrev.2001.81.2.871
microglial cell | CL has as exact synonym. EDIT "microglia" as related, plural. | doi:10.1038/s41598-020-66092-9
retinal ganglion cell | CL has "RGC" as exact synonym. EDIT "RGC" as related, abbreviation. Add "RGCs" as related, abbreviation, plural. | doi:10.1038/s41598-020-66092-9
retinal rod cell | Add "rod" as related syn. | doi:10.1038/s41598-020-66092-9
H1 horizontal cell | Add "H1" as related syn, abbreviation. | doi:10.1038/s41598-020-66092-9
H2 horizontal cell | Add "H2" as related syn, abbreviation. | doi:10.1038/s41598-020-66092-9

**Comment by dosumis** [comment]
If we really need to refer to GEO  IDs  we should use https://bioregistry.io/registry/geo. => geo: GSE137537.  Unless we can reliably tie the annotations to those on GEO, I don't think we should use GEO as a reference in cases like this.  It would be better if we could use a standard CxG reference for the annotated matrix.  It may be possible to use the UUID of the dataset, but we need some statement of official policy on IDs from CxG.

But in this case, we have DOI for all except one so I think we should use DOI alone for all except this and just drop  the one with no DOI.
