### ISSUE TITLE
[Merge] 'choroid plexus cell' into 'choroid plexus epithelial cell'

### ISSUE THREAD

**Issue by bvarner-ebi** [obophenotype/cell-ontology#2079]
**CL term**
CL:4023073 '[choroid plexus cell](http://purl.obolibrary.org/obo/CL_4023073)'

**Suggested replacement (merge above term into the winning term below)**
CL:0000706 '[choroid plexus epithelial cell](http://purl.obolibrary.org/obo/CL_0000706)'

**Reason for deprecation**
See #2043.

**Comment by bvarner-ebi** [comment]
Pending Q: This class is in the human_reference_atlas subset.
Get confirmation if this obsoleted class should be removed from the subset and if 'choroid plexus epithelial cell' should be added to the subset.

@emquardokus, do you. work with the human_reference_atlas. If so, can you advise?

**Comment by anitacaron** [comment]
The human_reference_atlas subset is generated from the ASCT+B tables. The complete answer is in the [linked PR](https://github.com/obophenotype/cell-ontology/pull/2088#discussion_r1288224746).
