### ISSUE TITLE
clean up imports directory

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#2084]
There is an `/imports/` directory at the root of the repo. It looks like it's not being rebuild - presumably intentionally as it is not standard to merge imports.

The URLs no longer resolve:

http://purl.obolibrary.org/obo/cl/imports/chebi_import.owl

(perhaps they never did and they were always fetched by catalog?)

We should tidy up the repo and get rid of stale committed derived artefacts that have no PURL

**Comment by bvarner-ebi** [comment]
@anitacaron, was something missed in https://github.com/obophenotype/cell-ontology/pull/1903 and https://github.com/obophenotype/cell-ontology/pull/1846?

**Comment by anitacaron** [comment]
As Chris noticed, the `/imports/` directory at the repo's root is no longer updated after we changed the imports approach to have one merged file.

@cmungall, can I remove this directory, or is it being used?
