### ISSUE TITLE
Telocyte and Lymphoblast do not have explicit parents

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#2086]
Current telocyte (CL:0017004) and lymphoblast (CL:0017005) do not have explicit parentage.
The only subclass they have is 
lymphoblast:
![image](https://github.com/obophenotype/cell-ontology/assets/76212760/ab40d4f8-98ae-4b80-b5bc-d7178e7d5619)
telocyte:
![image](https://github.com/obophenotype/cell-ontology/assets/76212760/e8f94e4d-b4c3-4780-95af-0c2ee25ee11a)
I am guessing this is why they seem orphaned in the .obo files
Can we split these up into separate subClassOf restrictions? Is there any implications on this?

**Comment by addiehl** [comment]
Split them up.  The split up axioms are logically equivalent to the combined one, in that there is an implicit 'and' between subclass axioms, in any case, but obviously tools are confused.

**Comment by lubianat** [comment]
Oh, that is probably something I did! But somehow that slipped through review - sorry!
