### ISSUE TITLE
acid secreting cell - obsolete? change logical def? merge?

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2095]
Acid secreting cell has only one asserted child:  parietal cell. 

[Cell Guide ChatGPT generated def](https://cellxgene.cziscience.com/cellguide/CL_0000161) makes it synonymous with parietal cell.

The term has not text def and a stupidly broad logical def - any cell that secretes some acid.  This probably applies to almost any cell, although currently the only auto-classificastion that results is classification of GABAergic neurons under this term -  based on GABA being an acid:

<img width="323" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/41e827bf-8721-4897-bda0-6d7340690bb2">

Most of the datasets grouped under it on CxG are grouped on the basis of having GABAergic neuron annotations

<img width="895" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/dc9b8168-66bd-45ba-bddd-e247b537a804">

Suggested change:  Merge with parietal cell.

**Comment by bvarner-ebi** [comment]
Resolved by https://github.com/obophenotype/cell-ontology/pull/2098
