### ISSUE TITLE
Duplicated label to synonym

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2102]
Looking at the reports there are few terms that have the label also as an exact synonyms:

| Level | Rule Name               | Subject    | Property                 | Value                              |
|-------|-------------------------|------------|--------------------------|------------------------------------|
| WARN  | duplicate_label_synonym | CL:0000448 | oboInOwl:hasExactSynonym | white fat cell                     |
| WARN  | duplicate_label_synonym | CL:0000598 | oboInOwl:hasExactSynonym | pyramidal neuron                   |
| WARN  | duplicate_label_synonym | CL:0009077 | oboInOwl:hasExactSynonym | subcapsular thymic epithelial cell |
| WARN  | duplicate_label_synonym | CL:1000409 | oboInOwl:hasExactSynonym | myocyte of sinoatrial node         |
| WARN  | duplicate_label_synonym | CL:1001435 | oboInOwl:hasExactSynonym | periglomerular cell                |

Is there a reason to maintain these synonyms or can I proceed to remove the synonym?

**Comment by dosumis** [comment]
Fine to remove

**Comment by shawntanzk** [comment]
@dosumis @aleixpuigb wondering if its worth looking into why the terms have duplicate exact synonym. might hint at terms that are duplicated. Can probably run a sparql query to report all duplicates with exact and rdfs:label

**Comment by emquardokus** [comment]
@aleixpuigb @dosumis 
CL:0009077 subcapsular thymic epithelial cell was one Paola Roncaglia added on behalf of our HuBMAP work. Our we sure all synonyms are really synonyms?

**Comment by shawntanzk** [comment]
@emquardokus - would you mind taking a look at this ticket re CL:0009077 https://github.com/obophenotype/cell-ontology/issues/2101

Thanks :)

**Comment by aleixpuigb** [comment]
The 'subcapsular thymic epithelial cell' can be adressed in #2101, as it is the only term that the exact synonym is in a different class. For the others, I am not sure why it was included as an exact synonym. Maybe it was a synonym of another term that was merged?
![image](https://github.com/obophenotype/cell-ontology/assets/94959119/91333397-1a6d-402b-8fe5-dcbd336bf480)
