### ISSUE TITLE
obsolete native cell and animal cell, they are confusing and cause missing inferences

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#2124]
These seem to be used randomly in logical definitions.

* 'native cell' is genus in cellHasPlasmaMembranePartX
* 'cell' is used as genus in the others
* 'animal cell' is never a genus as far as DPs are concerned

However, animal cell is widely (but not consistently) used as a genus in practice.

This leads to oddities such as His-purkinje cell not being an animal cell:

<img width="1136" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/50745/35a12365-da38-4502-b190-796f72e75e65">

(weirdly the inference is added at release time - I assume some property chain to taxa is not being imported correctly in the edit file)

Others that are clearly animal cells are not classified as such:

<img width="256" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/50745/62f1e13f-5c15-472d-ac04-613b492254f4">

It's very easy to do this kind of analysis with OAK; here are all cells that are not animal cells:

`cl info .desc//p=i 'cell' .not .desc//p=i 'animal cell'`

it's not too bad - the majority of these are truly generic (and also useless/silly groupings but that's another issue)

However we are leaving ourselves open to many more missing classifications, this is not good

There are likely a large number of cryptic missing inferences in other ontologies when they use CL

# Proposal 1: Obsolete native cell and animal cell

These have no purpose other than to confuse. If you want to filter CL by species there are better ways.

Having both is especially confusing and terminologically inconsistent, because animal cell is already a native cell. if we care to subdivide at the top level why not further down?

Note I am not proposing we get rid of cancel cell line cell etc. They stay as subclasses of 'cell'

# Proposal 2: Obsolete animal cell and use native cell consistently in all DPs

# Proposal 3: Keep both but be very clear and consistent in DPs

**Comment by bvarner-ebi** [comment]
@cmungall, an obsoletion notice for '[native cell](http://purl.obolibrary.org/obo/CL_0000003)' and
'[animal cell](http://purl.obolibrary.org/obo/CL_0000548)' was made on  Slack #cl-editors on 31-08-23. So far there have been no objections.

In all instances of usage of these terms in the ontology, I will replace them with [cell](http://purl.obolibrary.org/obo/CL_0000000).

**Comment by dosumis** [comment]
**We should make sure that CxG are aware** They directly reference 'native cell' in their schema and it is used as a general annotation throughout annotations on CxG.  We need a clear migration strategy - I think native cell should have a replaced_by axioms to cell.

**Comment by dosumis** [comment]
CC @jahilton

**Comment by dosumis** [comment]
I think maybe this is a good opportunity to ensure that key users are listening on the channels where this is announced and to consider whether we should use additional channels.

**Comment by ubyndr** [comment]
> @ubyndr - note - this wlll also affect the CAP pipeline - where we use 'animal cell' as a restriction. This should now be updated to just 'cell'. We should aim for some renewed general effort on species tagging and filtering - working with @gouttegd.

Hi @dosumis. We had started to use Cell instead of Animal Cell with this [PR](https://github.com/cellannotation/cap-pipeline-config/pull/88)
