### ISSUE TITLE
Documentation TOC

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2127]
IIRC the doc on github.io used to include  some kind of side bar or frame that showed a table of contents of the currently viewed document.  This is no longer present making a [doc like this](https://obophenotype.github.io/cell-ontology/relations_guide/ ) hard to navigate  .  Can we revive this please?

**Comment by bvarner-ebi** [comment]
Thank you for the issue, @dosumis.
I am able to see a TOC on the right side of the page. Can you clarify what TOC you are expecting to see?

<img width="1301" alt="Screenshot 2023-08-25 at 11 34 00" src="https://github.com/obophenotype/cell-ontology/assets/95643797/d14009d6-7421-45d2-bd54-b94bc18b228b">

**Comment by dosumis** [comment]
That's what I expected to see. I'm getting this in chrome.  Maybe a browser issue.  ![image](https://github.com/obophenotype/cell-ontology/assets/112839/c1de9156-6aa8-4f2a-89b4-3eff7f395cc0)

**Comment by bvarner-ebi** [comment]
If the viewing window is not fully expanded or opened in a mobile device, some elements of the page become hidden.
Viewing with Safari on a desktop with the window maximised should reveal all page elements.

**Comment by anitacaron** [comment]
The TOC moved to the burger menu, at the top left on the page.
