### ISSUE TITLE
[Class hierarchy] CL:4023056 vascular leptomeningeal cell (Mmus), species specific cell?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#2128]
CL:4023056

I am wondering what is the meaning of this CL class? a species-specific CL class? while CL:4023051 ! vascular leptomeningeal cell, already exists.

[Term]
id: CL:4023056
name: vascular leptomeningeal cell (**Mmus)**
def: "A type of mouse mesothelial fibroblast that is derived from the neural crest, is localized on blood vessels, and is a key component of the pia and arachnoid membranes surrounding the brain." [PMID:30096314]
subset: BDS_subset
synonym: "VLMC (Mus musculus)" EXACT []
is_a: CL:4023051 ! **vascular leptomeningeal cell**
relationship: dc-contributor https://orcid.org/0000-0001-7258-9596
relationship: in_taxon NCBITaxon:10090 ! Mus musculus
relationship: RO:0002292 PR:P11087 {xref="PMID:30096314"} ! expresses collagen alpha-1(I) chain (mouse)
relationship: RO:0002292 PR:P26618 {xref="PMID:30096314"} ! expresses platelet-derived growth factor receptor alpha (mouse)
relationship: RO:0002292 PR:P51885 {xref="PMID:30096314"} ! expresses lumican (mouse)

**Comment by bvarner-ebi** [comment]
@ANiknejad, yes, [CL:4023056](http://purl.obolibrary.org/obo/CL_4023056) is a species-specific (for Mus musclus) class.  The [parent class](http://purl.obolibrary.org/obo/CL_4023051) is not restricted to a specific taxon. There are several examples of taxon-specific cell types in CL, similar to how there are general and species-specific classes of genes in GO.

If this above does not answer your question, feel free to reopen and comment on this issue.

**Comment by bvarner-ebi** [comment]
@ANiknejad, the species-agnostic classes in Uberon should invoke the species-agnostic CL classes in the axioms. Species-specific cell type classes are also required in CL where there are species-specific features of the cell type and/or specific use case requirements.

**Comment by bvarner-ebi** [comment]
To illustrate the point above, [UBERON:0005206 'choroid plexus stroma'](http://purl.obolibrary.org/obo/UBERON_0005206) has the axiom [has part](https://www.ebi.ac.uk/ols4/ontologies/uberon/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000051?lang=en) some [dendritic cell](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000451?lang=en), NOT ['dendritic cell, human'](http://purl.obolibrary.org/obo/CL_0001056). 

'dendritic cell, human' has a definition specific to Homo sapiens.

**Comment by ANiknejad** [comment]
But in the precise example of CL:4023056
name: vascular leptomeningeal cell (Mmus)
what could be the need to create this class?

**Comment by bvarner-ebi** [comment]
> But in the precise example of CL:4023056
> name: vascular leptomeningeal cell (Mmus)
> what could be the need to create this class?

After a review of the provenance of this term, it appears both the general and mouse-specific classes were created based on the conversation that follows from this comment: https://github.com/obophenotype/cell-ontology/pull/968#discussion_r611683838

**Comment by ANiknejad** [comment]
yes, but in this comment, they talk about VLMC-**like**, and CL:4023056
name: vascular leptomeningeal cell (Mmus) is not described as a like one, right

**Comment by ANiknejad** [comment]
oh sorry, I see the RO with markers!

**Comment by bvarner-ebi** [comment]
> yes, but in this comment, they talk about VLMC-**like**, and CL:4023056
> name: vascular leptomeningeal cell (Mmus) is not described as a like one, right? and none marker is reported in its definition

In the comment I see "We should have species neutral terms for VLMC and ABC."
Both neutral and mouse-specific classes were added in the PR noted above.

If you believe the mouse-specific class should be edited/obsoleted, you are welcome to propose changes and/or reach out to the editors involved on the PR to get more insight on their decisions for adding both.

**Comment by bvarner-ebi** [comment]
> oh sorry, I see the RO with markers!
> 
> > relationship: RO:0002292 PR:P11087 {xref="PMID:30096314"} ! expresses collagen alpha-1(I) chain (mouse)
> > relationship: RO:0002292 PR:P26618 {xref="PMID:30096314"} ! expresses platelet-derived growth factor receptor alpha (mouse)
> > relationship: RO:0002292 PR:P51885 {xref="PMID:30096314"} ! expresses lumican (mouse)

@ANiknejad, if you have any other concerns, kindly add them here. If your question has been answered, kindly close the ticket.
Thank you for your contributions.

**Comment by ANiknejad** [comment]
thank you for clarifications, Bradley, yes so far I close the issue
