### ISSUE TITLE
[Synonym] corpus luteum cell  --> luteal cell

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#2139]
**CL term**
luteal cell
http://purl.obolibrary.org/obo/CL_0000175

**Synonym to be added** (include synonym scope broad/exact/narrow/related and reference(s))

corpus luteum cell (exact match, PMID:[16790079](https://pubmed.ncbi.nlm.nih.gov/16790079))

related: corpus luteum endothelial cell   from ASCTB tables (https://www.ebi.ac.uk/ols4/ontologies/ccf/classes/https%253A%252F%252Fpurl.org%252Fccf%252FASCTB-TEMP_corpus-luteum-endothelial-cell)

**Comment by aleixpuigb** [comment]
Thank you for the synonym, @lubianat.
I will add the'corpus luteum cell' as an exact synonym.
corpus luteum endothelial cell is a different cell type, and should be included in a different ticket [PMID:14613535](https://pubmed.ncbi.nlm.nih.gov/14613535).
