### ISSUE TITLE
[NTR] TCR+ Macrophage

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#2140]
Hello CL Team,

In this very recent paper, 
https://pubmed.ncbi.nlm.nih.gov/37500727/
'Integrated single-cell chromatin and transcriptomic analyses of human scalp identify gene-regulatory programs and critical cell types for hair and skin diseases'

they identified a 'TCR+ Macrophage' cell type ('TCR.macs'), 

a cell type also cited in an older reference 
https://pubmed.ncbi.nlm.nih.gov/26074923/ 
'Much More than M1 and M2 Macrophages, There are also CD169+ and TCR+ Macrophages':

> Regarding macrophage cellular subpopulations, several publications have reported the presence of both humans and murine TCR+ macrophages. 

So far, none CL class seems available to map this cell type, as far as I can see.

**Preferred term label**. TCR+ Macrophage

**Synonyms** TCR.macs   (PMID: 37500727)

**Definition** A monocyte-derived macrophage subpopulation having expression of TCR on cellular surface (derived from PMID: 26074923)

**Parent cell type term** CL:0000235 (macrophage)

**Anatomical structure where the cell type is found** is_a: UBERON:0004120 ! mesoderm-derived structure
**Your ORCID** 0000-0003-3308-6245

**Comment by bvarner-ebi** [comment]
@addiehl, checking if you have any feedback on this request.

**Comment by bvarner-ebi** [comment]
@addiehl, thank you for the feedback.
@ANiknejad, do you agree with the proposals above?

**Comment by ANiknejad** [comment]
@bvarner-ebi 
thank you very much, yes I agree!

**Comment by bvarner-ebi** [comment]
**Preferred term label**
TCR-positive macrophage

**Synonyms**
T cell receptor positive macrophage (exact, PMID:26074923)
TCR+ macrophage (exact, PMID:26074923)
TCR.macs (related, abbreviation, PMID:37500727)

**Definition**
A macrophage that expresses the T cell receptor complex at the cell surface. 
PMID:26074923
https://orcid.org/0000-0001-9990-8331

**Parent cell type term / Logical definition**
macrophage and ('has plasma membrane part' some 'T cell receptor complex')


**Anatomical structure where the cell type is found**
N/A

**Your ORCID**
https://orcid.org/0000-0003-3308-6245

**Comment by bvarner-ebi** [comment]
@ANiknejad, the following class has been added to CL and will be publicly available in the next CL release:

CL:4030058 'TCR-positive macrophage'

Details can be reviewed in the linked PR (#2162).
Thank you again for your contribution.
