### ISSUE TITLE
Remove tissue region specificity from term label or else NTR

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#2148]
The children of [L2/3-6 intratelencephalic projecting glutamatergic cortical neuron](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_4023040) have the text " of primary motor cortex" at the end of the term label:

<img width="824" alt="Screenshot 2023-09-12 at 11 32 00 AM" src="https://github.com/obophenotype/cell-ontology/assets/52470876/acdaa0f2-1297-4a2c-9019-048718f9b59f">\

Is there a particular reason the region of the brain was added to the term names? The primary motor cortex is not referenced in the definition. And there isn't a term for just "L2/3 intratelencephalic projecting glutamatergic neuron". Can the children terms have either have " of primary motor cortex" removed from label, or can a new term be added without the specific brain tissue location? That way, cells annotated as, for example, **L2/3 IT** can be mapped to "L2/3 intratelencephalic projecting glutamatergic neuron" rather than have to default to the parent "L2/3-6 intratelencephalic projecting glutamatergic cortical neuron" since it is not definitively part of the primary motor cortex.

Example journals: 

- https://www.biorxiv.org/content/10.1101/2023.05.08.539485v2.full.pdf (https://cellxgene.cziscience.com/e/c2876b1b-06d8-4d96-a56b-5304f815b99a.cxg/)
- https://www.nature.com/articles/s41586-021-03500-8 (https://cellxgene.cziscience.com/e/35081d47-99bf-4507-9541-735428df9a9f.cxg/)

**Comment by bvarner-ebi** [comment]
Thank you for the questions, @jychien.

>Is there a particular reason the region of the brain was added to the term names?

The cross-references for classes L2/3 - L5 are specific to motor cortex. The cross-reference for the L6 class appears to be focussed on somatosensory cortex, so I cannot explain that one.

> The primary motor cortex is not referenced in the definition.

It is referenced in all logical definitions for these classes and in all text definitions except for 'L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex'. The text definition for this class can be updated to be aligned with the rest.

Thank you for the references. The second reference appears to be focussed on primary motor cortex, so those terms could be mapped to the already existing CL classes.
Generally, creating a class that would have only one child (e.g., something like "L2/3 intratelencephalic projecting glutamatergic cortical neuron") is discouraged unless you have a specific use case. If you'd like to submit a NTR issue for these cell types in other brain regions, please do so, and it will be added to the work queue.

**Comment by jychien** [comment]
Thank you, @bvarner-ebi, for the explanation and pointing out the definitions of the other children terms. And, I do agree that it's not ideal to create classes with only one child, and that is why I hadn't initially created a NTR ticket. 

The more general question I have is at what point does CL create new terms for cell types that are tissue location specific? Is there a requirement of specific cell markers? It seems to be the current general trend that authors that upload their data to CELLxGENE would rather not include the tissue location in the cell type annotation, as they are not sure if there is enough evidence to support cell type specificity based on location.

We've been able to use the more general term (such as 'fibroblast') for most cases. But for this case, if we use the parent term, there is information loss since the layers are collectively categorized as L2/3-6. And, when looking at the multiple brain datasets we have in CELLxGENE, only the cells that explicitly mention the primary motor cortex could have the specific layer. I would give a confusing user experience who, for example, want to look at different layers.

I don't really have a good solution, but getting a better understanding would help us guide the process of picking the appropriate CL term.

**Comment by bvarner-ebi** [comment]
Thank you for the follow up, @jychien.

> The more general question I have is at what point does CL create new terms for cell types that are tissue location specific? Is there a requirement of specific cell markers? Is there a requirement of specific cell markers?

If there exists clear differentia, which may include specific cell markers, that should satisfy the requirement to add a new class in CL. If the differentia is not immediately evident, the requestor should submit a compelling reason to add the new class.

>  It seems to be the current general trend that authors that upload their data to CELLxGENE would rather not include the tissue location in the cell type annotation, as they are not sure if there is enough evidence to support cell type specificity based on location.

I agree with the approach to not include anatomical location in a class label or definition unless there is compelling evidence that differentiates the cell type from the same general cell type in other anatomical locations, but other editors may have different perspectives. If you'd like, you could add this as a topic of discussion at one of the monthly CL meetings. 

>But for this case, if we use the parent term, there is information loss since the layers are collectively categorized as L2/3-6. And, when looking at the multiple brain datasets we have in CELLxGENE, only the cells that explicitly mention the primary motor cortex could have the specific layer. It would give a confusing user experience for people who, for example, want to look at different layers.
I don't really have a good solution, but getting a better understanding would help us guide the process of picking the appropriate CL term.

In this case, if you have a reference to support creating a new class of the form 'L{_N_} intratelencephalic projecting glutamatergic neuron of the {_anatomical location_}', such as 'L2/3 intratelencephalic projecting glutamatergic neuron of the somatosensory cortex', that could be added.

**Comment by dosumis** [comment]
This term came from the brain initiative atlas of the primary motor cortex. Because glutamatergic projection neurons do vary quite a lot between cortical regions, we were conservative (probably too conservative) adding region neutral terms for these.    The region restriction should be mentioned in the textual definition as well as the logical one, so the absence of this is an error. I am happy to support addition of a region neutral term.

**Comment by jychien** [comment]
Thank you @bvarner-ebi and @dosumis. It would be great if the region neutral terms could be added as children of [L2/3-6 intratelencephalic projecting glutamatergic cortical neuron](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_4023040). The corresponding terms with " of primary motor cortex" would then be children of these new terms. Please let me know if I should create a separate ticket.

> If you'd like, you could add this as a topic of discussion at one of the monthly CL meetings.

It would also be great to discuss this topic. If you could let me know how to get added to the meeting and/or access the meeting agenda, that would be great. Thanks!

**Comment by bvarner-ebi** [comment]
> Please let me know if I should create a separate ticket.

@jychien, yes, kindly create a NTR issue including  cross-references.

>  If you could let me know how to get added to the meeting and/or access the meeting agenda, that would be great.

CL meetings are every 3rd Wednesday of the month at 8am PT, with the next scheduled for 20/09. Agenda is [here](https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit?pli=1).

**Comment by bvarner-ebi** [comment]
@jychien, the linked PR has been merged and https://github.com/obophenotype/cell-ontology/issues/2154 has been opened. Is there anything else you would like addressed on this issue?

**Comment by bvarner-ebi** [comment]
Pending issues captured in #2154.
