### ISSUE TITLE
[NTR-cxg] Add region neutral children of L2/3-6 intratelencephalic projecting glutamatergic cortical neuron

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#2154]
**Related ticket**: https://github.com/obophenotype/cell-ontology/issues/2148

**Parent cell type term**
The children of [L2/3-6 intratelencephalic projecting glutamatergic cortical neuron](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_4023040) have the text " of primary motor cortex" at the end of the term labels. To ontologize layer specific neurons that are not definitively from the primary motor cortex, we are requesting that there be terms added that are region neutral.
Additionally, we are requesting that the region neutral grouping terms are added as parents to the layer specific terms:
- L2/3 intratelencephalic projecting glutamatergic neuron (L2/3 IT) is parent of L2 IT and L3 IT
- L4/5 intratelencephalic projecting glutamatergic neuron (L4/5 IT) is parent of L4 IT and L5 IT

**Preferred term label** (**Synonym(s)** in parenthesis):
- L2/3 intratelencephalic projecting glutamatergic neuron (L2/3 IT)
- L2 intratelencephalic projecting glutamatergic neuron (L2 IT)
- L3 intratelencephalic projecting glutamatergic neuron (L3 IT)
- L4/5 intratelencephalic projecting glutamatergic neuron (L4/5 IT)
- L4 intratelencephalic projecting glutamatergic neuron (L4 IT)
- L5 intratelencephalic projecting glutamatergic neuron (L5 IT)
- L6 intratelencephalic projecting glutamatergic neuron (L6 IT)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
- L2/3 intratelencephalic projecting glutamatergic neuron: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 2/3. (PMID:37292694, PMID:34004146)
- L2 intratelencephalic projecting glutamatergic neuron: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 2 (PMID:34004146)
- L3 intratelencephalic projecting glutamatergic neuron: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 3 (PMID:34004146)
- L4/5 intratelencephalic projecting glutamatergic neuron:  An intratelencephalic-projecting glutamatergic with a soma located in cortical layer 4/5. (PMID:34004146)
- L4 intratelencephalic projecting glutamatergic neuron: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 5 (PMID:37292694)
- L5 intratelencephalic projecting glutamatergic neuron: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 5. (PMID:37292694, PMID:37609206)
- L6 intratelencephalic projecting glutamatergic neuron: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 6 . (PMID:37292694, PMID:37609206)

**Publications**:
- https://doi.org/10.1101/2023.05.08.539485 (PMID:37292694) (https://cellxgene.cziscience.com/e/c2876b1b-06d8-4d96-a56b-5304f815b99a.cxg/)
- https://doi.org/10.1016/j.cell.2021.04.021 (PMID:34004146) (https://cellxgene.cziscience.com/e/d7291f04-fbbb-4d65-990a-f01fa44e915b.cxg/)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: 
Cerebral cortex: UBERON:0000956

**Your ORCID**
https://orcid.org/0000-0003-4389-9821

**Additional notes or concerns**
- The parents of the terms containing " of primary motor cortex" would then be the most layer specific of these new terms as possible. For example, "L4/5 IT M1" would be a child of "L4/5 IT" and "L5 IT M1" would be a child of "L5 IT".
- Was there a particular reason that L2/3 and L4/5 were considered together on not listed as individual layers?
- NOTE: It would make the most sense that "L5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex" is child of "L5 IT M1".
- I've made a diagram, since this was gettting so complicated:

<img width="450" alt="Screenshot 2023-10-11 at 2 41 41 PM" src="https://github.com/obophenotype/cell-ontology/assets/52470876/fc01aa69-ea9c-4cc2-a88b-8a645e800b4b">

**Comment by jychien** [comment]
We just received another dataset with the following cell annotations:
['L6-IT-Car3', 'Amy-Exc', 'L6b', 'L6-CT', 'L6-IT', 'L4-IT', 'L5-IT', 'L2/3-IT', 'L5/6-NP', 'L5-ET']

Is it possible to separate L4 with L5?

**Comment by bvarner-ebi** [comment]
Thank you for the additional information, @jychien.

The reference for '[L4/5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023048)', PMID:[33184512](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8113357/), has the following description:

"We were also able to identify a t-type, L4/5 IT_1, that was located on the boundary between L2/3 and L5 and probably corresponds to the quasi-L4 neurons described previously in motor cortex.[31](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8113357/#CR31)"

Given this lack of specificity, the aggregation for L4 and L5 in this case seems reasonable in this case. 

Are you proposing to **replace** L4/5 with L4 and L5 parent classes or to **keep** L4/5 and add L4 and L5?

**Comment by dosumis** [comment]
Any one paper with layer information is about a type is likely to focus on the peculiarities of the layer structure of the region being studied.  IIRC, the primary motor cortex lacks a clear layer 4 (unlike many other cortical regions), but some the the location of the soma of some the type being discussed in this paper fits with it being quasi-L4 in the PMC.  

It is clear that we need a set of region-neutral terms for IT & ET projecting glutamatergic neurons in the cortex.   To find out: for which layers can we justify adding ET, IT or both. @jychien - can you provide refs for the papers you're curating for these datasets (or are they pre-release?).

Please also note that we now have the option to add an official symbol  (e.g. L5 ET) and have done so for at least some terms.  I'd like to add these for well used symbols to enhance findability and to provide an option for display where long names are not appropriate.

Finally - I think it would be worth having a more general call with folks form the Allen who are working on these cell types to get their take on what's needed.  We can't avoid that these names are being used based on annotation transfer in cases were we don't have soma-location and projection info.  I can help organise through BICAN.  @jychien would you be interested to join??

**Comment by jychien** [comment]
Thank you @bvarner-ebi and @dosumis. 

To clarify, yes, I was suggesting to keep the L4/5 terms and to add the individual L4 and L5. And it does make a lot of sense to add them as children. 

Here are 2 of the preprints that I am working on with contributors:
- https://www.biorxiv.org/content/10.1101/2023.08.10.552874v1
- https://www.biorxiv.org/content/10.1101/2022.11.30.518285v1.full.pdf

We do have additional datasets that other wranglers on the Lattice team are working on, and other datasets that are being wrangled from public repositories where we have yet to engage with the authors.  It would be great if @jlzamanian and I could be invited to the conversation. Much appreciated! The authors that I am talking with are non-Allen, and it does sound like they have some feedback on the CL terms and is what started this thread. Would it be okay to extend the invitation to these authors, in the case they are interested in adding some feedback? 

In general, the datasets for brain that we are getting are large, and if we could get the CL terms in place, it would help alleviate some of the re-annotation work that we would need to do in the future. Thank you !

**Comment by jychien** [comment]
@bvarner-ebi I've tried to make it as least confusing as possible. Please let me know if something is inconsistent. Thanks!

**Comment by dosumis** [comment]
> We just received another dataset with the following cell annotations:
> ['L6-IT-Car3', 'Amy-Exc', 'L6b', 'L6-CT', 'L6-IT', 'L4-IT', 'L5-IT', 'L2/3-IT', 'L5/6-NP', 'L5-ET']

@jychien - is this one of the datasets being processed for loading?

Jorstad, Nikolas L., Jennie Close, Nelson Johansen, Anna Marie Yanny, Eliza R. Barkan, Kyle J. Travaglini, Darren Bertagnolli, et al. 2022. “Transcriptomic Cytoarchitecture Reveals Principles of Human Neocortex Organization.” bioRxiv. https://doi.org/10.1101/2022.11.06.515349.

This is a current priority for our Brain Initiative funding and may become a reference for human cortical types.  Looks v. relevant to decisions about cell types being added for this ticket.

**Comment by jychien** [comment]
@dosumis Yes, the list of cell annotations is from the [second](https://doi.org/10.1101/2022.11.30.518285) preprint listed above. 

Thank you for the link to the preprint. What does it mean for a publication to become a reference for a brain tissue region? Will there need to be any changes to this new terms requested in this ticket? We are looking through our brain datasets in CELLxGENE and do anticipate additional NTRs.

**Comment by dosumis** [comment]
>  What does it mean for a publication to become a reference for a brain tissue region?

It will be added to the list of annotated datasets used as a reference on https://portal.brain-map.org/explore/cell-type-references-and-algorithms.  This allows users to upload an h5ad file and get a set of predicted annotations.

**Comment by dosumis** [comment]
> > Please also note that we now have the option to add an official symbol (e.g. L5 ET) and have done so for at least some terms.

> That's great! Is this listed as an exact synonym, or are you saying that there is a new feature of an 'official symbol' that can be retrieved for these cell types with long names?

Both.  e.g. 

https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_4023041

has 

![image](https://github.com/obophenotype/cell-ontology/assets/112839/6ff29849-9f35-4418-b17e-8d9dbac63e92)

**Comment by bvarner-ebi** [comment]
@jychien, thank you for the detailed ticket.
*Note: using abbreviations instead of labels in comments below.

Regarding the placement of L2 IT and L3 IT as subclasses under L2/3 IT, I'm unsure of this modelling. 

My understanding is that '[cortical layer II/III](http://purl.obolibrary.org/obo/UBERON_8440000)' is used when there is no clear distinction between the boundaries of layers II and III as opposed to an arbitrary grouping of the two classes.
Uberon does not classify '[cortical layer II](http://purl.obolibrary.org/obo/UBERON_0005391)' and '[cortical layer III](http://purl.obolibrary.org/obo/UBERON_0005392)' as children of '[cortical layer II/III](http://purl.obolibrary.org/obo/UBERON_8440000)', and it is my inclination to preserve that separation with these new CL classes.

The r[eference provided](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8195859/) for new terms L2 IT and L3 IT also classifies these as different super types (emphasis added): "The ENT IT group ([Fig. 4B](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8195859/figure/F4/)–[D](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8195859/figure/F4/), [​,FF](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8195859/figure/F4/)–[H](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8195859/figure/F4/)) has 10 supertypes organized in a layer-selective manner, in the order of **L2, L2/3, L3**, L5 and L6, consistent with their correspondence with CTX L2/3-L6 IT types, and shows differential spatial distribution along the anterior-posterior axis..."

The reference also states: "Two supertypes, L2 IT ENTm Lef1 and L2 IT ENTl Chn2 (Grik1+), are located at the border between L1 and L2." 
Your proposed text definition for L2 IT has "...soma found in cortical layer 2". **Is this distinction in location worth reflecting in the definition (border vs layer)?**


With the above in mind, would it be appropriate to classify L2 IT, L3 IT, L4 IT and L5 IT as **direct descendants of L2/3-6 IT** instead of the hierarchy presently proposed in your request?

CC @patrick-lloyd-ray if you have insight to add.

**Comment by jychien** [comment]
@bvarner-ebi Thank you very much for catching that. I hadn't realized the nuanced difference. I've updated the diagram in the first comment accordingly.

**Comment by bvarner-ebi** [comment]
@jychien, thank you for confirming.

For your review, this is how the classes appear in the ontology editor inferred class hierarchy view:

<img width="789" alt="Screenshot 2023-10-12 at 15 53 14" src="https://github.com/obophenotype/cell-ontology/assets/95643797/6534436d-1a24-49a1-8f4d-09eb539b7a51">

Of note, assuming there was a copy error in the text def for L4 IT, I substituted "4" for "5".

**Comment by bvarner-ebi** [comment]
@jychien, thanks again for the new terms. The following classes have been added and will be available in the next CL release:

CL:4030059 'L2/3 intratelencephalic projecting glutamatergic neuron'
CL:4030060 'L2 intratelencephalic projecting glutamatergic neuron'
CL:4030061 'L3 intratelencephalic projecting glutamatergic neuron'
CL:4030062 'L4/5 intratelencephalic projecting glutamatergic neuron'
CL:4030063 'L4 intratelencephalic projecting glutamatergic neuron'
CL:4030064 'L5 intratelencephalic projecting glutamatergic neuron'
CL:4030065 'L6 intratelencephalic projecting glutamatergic neuron'

Additional details can be viewed in [the linked PR](https://github.com/obophenotype/cell-ontology/pull/2181).
