### ISSUE TITLE
[Class hierarchy]Hofbauer cell CL:0000235 is a tissue resident macrophage

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#2166]
**CL term**
Hofbauer cell CL:0000235

**Suggested revision of class hierarchy**
It should appear under tissue resident macrophage.

Thomas JR, Naidu P, Appios A, McGovern N. The Ontogeny and Function of Placental Macrophages. Front Immunol. 2021 Oct 21;12:771054. doi: 10.3389/fimmu.2021.771054. PMID: 34745147; PMCID: PMC8566952.
Quote from paper: "Hofbauer cells (HBC) are a population of tissue-resident macrophages found within human placental villi. These cells appear very early during development and have been identified at day [1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8566952/#B1)8 post-conception (1, [2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8566952/#B2)). HBC are the only significant immune cell population found within the normal healthy human placenta."

<img width="443" alt="Screenshot 2023-10-02 at 4 03 33 PM" src="https://github.com/obophenotype/cell-ontology/assets/47257000/54fa745d-6dec-4781-a1ca-608f4d5dc49f">

**Comment by aleixpuigb** [comment]
Thank you, @emquardokus. I agree that it should be a tissue-resident macrophage. Moreover, I think it should be 'part of' '[chorion membrane](http://purl.obolibrary.org/obo/UBERON_0003124)' (not chorionic villi, as it is a species unspecific term).

**Comment by aleixpuigb** [comment]
Hi @emquardokus,
This term has few issues. The definition provides from wikipedia, which is not referenced, and it is outdated and human specific. It also does not reflect the new axioms. Do you agree with the following edits?

Current definition:
> Oval eosinophilic histiocytes with granules and vacuoles found in placenta, which are of mesenchymal origin, in mesoderm of the chorionic villus, particularly numerous in early pregnancy.

Proposed definition
> A tissue-resident macrophage that is part of the placenta. A Hofbauer cell expresses high levels of growth factors and metalloproteinases that support vasculogenesis, angiogenesis, branching morphogenesis and tissue remodeling.

[PMID:34745147](https://doi.org/10.3389/fimmu.2021.771054)
[PMID:30498493](https://doi.org/10.3389/fimmu.2018.02628)
[PMID:35438172](https://pubmed.ncbi.nlm.nih.gov/35438172)

And add the following comment:
> Hofbauer cells are an heterogenic group of macrophages that resemble M2-like cells. Initially described in chorionic villi in humans, a Hofbauer cell is now often used to describe any fetal derived placental macrophage that resides within the placental villous core, amnion, and chorionic lavae.

[PMID:30498493](https://doi.org/10.3389/fimmu.2018.02628)

New synonym
EXACT ABBREVIATION HBC [PMID:34745147](https://doi.org/10.3389/fimmu.2021.771054)

**Comment by emquardokus** [comment]
@aleixpuigb

**Comment by aleixpuigb** [comment]
Thank you, I will include at the end of the definition: "A Hofbauer cell  has a fetal origin and is present through pregnancy."
