### ISSUE TITLE
[NTR-cxg] Add L6 IT Car3

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#2202]
**Preferred term label**
L6 IT Car3 glutamatergic neuron 
(referring to term label in PCL for "[L6 IT Car3 primary motor cortex glutamatergic neuron (Mmus)](https://www.ebi.ac.uk/ols4/ontologies/pcl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPCL_0011069?lang=en)")

**Synonym(s)**
L6 IT Car3

**Definition**
An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 6 that expresses Car3. 

**References**
- Jorstad et al., 2022 (“Transcriptomic cytoarchitecture reveals principles of human neocortex organization”, Homo sapiens, https://doi.org/10.1101/2022.11.06.515349): “L6 IT Car3 neurons were more diverse in MTG, A1, and AnG compared to other areas reflecting a balanced population of CUX2-expressing and non-expressing neurons specifically in these cortical areas that we reported as an evolutionary specialization of great apes compared to monkeys”
- Yao et al. 2021: (‘A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation’, Mus musculus, https://doi.org/10.1016/j.cell.2021.04.021): “The distinct subclass of Car3, which includes neurons from L6 of many lateral cortical areas, is included here as our recent study showed that these Car3+ L6 neurons, like cortical IT neurons, have extensive intracortical axon projections.” https://cellxgene.cziscience.com/collections/e3aa612b-0d7d-4d3f-bbea-b8972a74dd4b 
- Tien et al., 2022 (“Epigenomic complexity of the human brain revealed by single-cell DNA methylomes and 3D genome structures”, Homo sapiens, https://doi.org/10.1101/2022.11.30.518285): “Although they have similar DNA methylation patterns at the major type level, a recent study in mice showed that L6-IT-Car3 cells have divergent projection patterns”

**Parent cell type term** 
L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex ([CL:4023050](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_4023050?lang=en))

**Anatomical structure where the cell type is found** 
cortical layer VI ([UBERON:0005395](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0005395))

**Your ORCID**
https://orcid.org/0000-0003-4389-9821

**Additional notes or concerns** 
Would be great to have a reviewer add some more to the description, such as including description about projection type.

**Comment by bvarner-ebi** [comment]
@jychien, thank you for this request.

Regarding the parent term, you requested 'L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex'. 
Noted above from your reference: "The distinct subclass of Car3, which includes neurons from L6 of many lateral cortical areas... ". This suggests this cell type exists in more cortical areas than only the primary motor cortex.

With that said, would you agree the parent class of this new term can be '[L6 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030065)' and '[L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023050)' would instead be a **sibling** class?

**Comment by bvarner-ebi** [comment]
@jychien, thank you again for this new term request.
The following has been added to CL and will be available in the next release:

CL:4030068 'L6 intratelencephalic projecting Car3 glutamatergic neuron'

Additional synonyms were added. Details can be reviewed in the linked PR: https://github.com/obophenotype/cell-ontology/pull/2234
