### ISSUE TITLE
[NTR-cxg] Add region neutral L5/6 NP

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#2203]
**Preferred term label**
L5/6 near-projecting glutamatergic neuron

**Synonym(s)**
L5/6 NP

**Definition**
A near-projecting glutamatergic neuron with a soma  found in layer 5/6 

**References**
- Gabitto et al. 2023: (‘Integrated multimodal cell atlas of Alzheimer’s disease’, Homo sapiens, https://doi.org/10.1101/2023.05.08.539485 ), https://cellxgene.cziscience.com/collections/1ca90a2d-2943-483d-b678-b809bf464c30, PMID: [37292694](https://pubmed.ncbi.nlm.nih.gov/37292694)
- Yao et al. 2021 Cell: (“A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation”, Mus musculus) “, https://doi.org/10.1016/j.cell.2021.04.021, PMID: [34004146](https://pubmed.ncbi.nlm.nih.gov/34004146)

**Parent cell type term**
near-projecting glutamatergic cortical neuron ([CL:4023012](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_4023012?lang=en))

**Anatomical structure where the cell type is found**
cortical layer V/VI ([UBERON:8440002](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_8440002?lang=en))

**Your ORCID**
https://orcid.org/0000-0003-4389-9821

**Comment by bvarner-ebi** [comment]
@jychien, thank you for this new term request.
The following has been added to CL and will be available in the next CL release.

CL:4030067 'L5/6 near-projecting glutamatergic neuron'
