### ISSUE TITLE
Ontobot workflow failing with all new issues (not related to it)

### ISSUE THREAD

**Issue by anitacaron** [obophenotype/cell-ontology#2225]
Since last week, [all new issues](https://github.com/obophenotype/cell-ontology/actions/workflows/ontobot.yml) created in the repo are triggering the ontobot workflow is failing.

```bash
build (3.9, ubuntu-latest)The format of '<@users.noreply.github.com>' is not a valid email address with display name
```

This workflow should be triggered only when invocated with `Hey ontobot, apply:`.

**Comment by anitacaron** [comment]
I temporarily turned off this workflow.

**Comment by anitacaron** [comment]
It's still failing, for another reason

https://github.com/obophenotype/cell-ontology/actions/runs/6907370221

**Comment by hrshdhgd** [comment]
That's because the issue is empty. Usually not the case, regardless, I'll address it and make a new release.

**Comment by anitacaron** [comment]
Here, we can expect anything 😬

**Comment by hrshdhgd** [comment]
Haha fair enough!

**Comment by anitacaron** [comment]
But it would be good if it doesn't run in all new and edited issues. As I said, there are many cases.

**Comment by hrshdhgd** [comment]
Ok, it'll run a preliminary check on the issue body for the presence of `Hey ontobot`. If true only then will the workflow run.
