### ISSUE TITLE
[NTR] liver-resident natural killer cell

### ISSUE THREAD

**Issue by EMRutherford** [obophenotype/cell-ontology#2241]
**Preferred term label**
liver-resident natural killer cell

**Synonyms** 
liver NK cell, lrNK, lr-NK

**Definition** 
A natural killer cell resident to the liver, distinguished from circulating natural killer cells by CD49a or CD69 gene expression.  Also expresses CCR5, EOMES, KLRB1, GZMK, and CXCR6.

**Parent cell type term**
natural killer cell (CL:0000623)

**Anatomical structure where the cell type is found** 
liver (UBERON:0002107)

**References**

- Hudspeth et al. 2015 (“Human liver-resident CD56bright/CD16neg NK cells are retained within hepatic sinusoids via the engagement of CCR5 and CXCR6 pathways”, DOI: 10.1016/j.jaut.2015.08.011, PMID:26330348)

- Peng et al. 2016 (“Liver natural killer cells: subsets and roles in liver immunity”, DOI:  ​​https://doi.org/10.1038/cmi.2015.96, PMID:26639736)

- Highton et al. 2021 (“The role of natural killer cells in liver inflammation”, DOI:10.1007/s00281-021-00877-6, PMID:34230995)

- Zhao et al. 2020 (“Single-cell RNA sequencing reveals the heterogeneity of liver-resident immune cells in human”, DOI: 10.1038/s41421-020-0157-z, PMID: 32351704)

- Jameson et al. 2022 (“Human Hepatic CD56bright NK Cells Display a Tissue-Resident Transcriptional Profile and Enhanced Ability to Kill Allogenic CD8+ T Cells”, DOI: 10.3389/fimmu.2022.921212, PMID: 35865550)

- Cuff et al. 2016 (“Eomeshi NK Cells in Human Liver Are Long-Lived and Do Not Recirculate but Can Be Replenished from the Circulation”, DOI: 10.4049/jimmunol.1601424, PMID: 27798170)

**Your ORCID**
0000-0001-8134-3037

**Additional notes or concerns**
Relates to existing term “hepatic pit cell” (CL:2000054).  However, pit cells appear to be defined based on the microscopic appearance of these cells in rats, and a reference (Peng et al 2016) suggests that there is no exact equivalent in humans:  “In recent years, the author (E. W.) had the opportunity to investigate more than 200 wedge and needle biopsies of human livers using fixation methods adapted to obtain perfusion fixation quality tissue.52,53 After observing these specimens, the author concluded that no cells with rat pit cell morphology are present in the human liver. Very occasionally, a cell with a few granules could be found, but an EM comparison of rat and human livers led to the conclusion that human liver does not harbor a morphological equivalent of the rat pit cell.”  “Liver-resident natural killer cell” is a more appropriate term since it is not species-specific, and appears to be the term preferred in modern literature.

**Comment by dosumis** [comment]
@JABelfiore  can you make this high priority for this sprint? It's been hanging around too long. thanks.

**Comment by dosumis** [comment]
See also https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2019.00946/full

Human lr-NK cells were first described in 1976 and were originally called “pit cells.” Only later, they were defined as highly cytotoxic NK cells resident in the hepatic sinusoids (35, 43, 44). Differently from murine and their human counterparts in peripheral blood, CD56dim and CD56bright NK cells are present at similar frequencies in liver and the latter subset likely corresponds to the murine CD49apos/DX5neg lr-NK cells, as they both share the same transcriptional factor T-bet and are negative for Eomes (Table 1) (28).
