### ISSUE TITLE
[NTR] subtypes of tanycyte - alpha1,2; Beta 1,2

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2256]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**

alpha 1 tanycyte
alpha 2 tanycyte
beta 1 tanycyte
beta 2 tanycyte

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

Review here: DOI: 10.1016/S0074-7696(05)47003-5

Table II has a good summary of differences in location, morphology and gene expression.  Looks like location and morphology might be sufficient to distinguish.

<img width="1061" alt="image" src="https://github.com/obophenotype/cell-ontology/assets/112839/5977129f-f032-467f-971e-2be8b9401027">

May be worth looking back at some more classical papers - review references EM studies from the 70s.

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**

**Additional notes or concerns**

**Comment by dosumis** [comment]
Notes - needed for:
 -  whole mouse brain 
- ["HypoMap – a unified single cell gene expression atlas of the murine hypothalamus"] | ["https://cellxgene.cziscience.com/collections/d86517f0-fa7e-4266-b82e-a521350d6d36"] | ["https://doi.org/10.1038/s42255-022-00657-y"]

Additional refs:
https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2015.00387/full
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5323293/

See also:  
https://cellxgene.cziscience.com/cellguide/CL_0002085 - Can we use this for an extended description for the general term?

**Comment by AvolaAmg** [comment]
@dosumis thanks for your ticket. 
Would you like me to add the CxG [link]("https://cellxgene.cziscience.com/collections/d86517f0-fa7e-4266-b82e-a521350d6d36) as a **database_cross_reference** ? 

Here there is the work to do for these cell types

[tanycyte](http://purl.obolibrary.org/obo/CL_0002085)
-
A specialized elongated ventricular ependymal cell that has processes that extend to the outer, or pial, surface of the CNS. A tanycyte is found in the adult brain, specifically in the third ventricle, cerebral aqueduct, spinal canal, and floor of the fourth ventricle. This cell type is involved in hormonal regulation, gatekeeping molecules between the bloodstream and cerebrospinal fluid, metabolic sensing, and regulating food intake.

has_broad_synonym
radial glia-like cell
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/)


has_broad_synonym
residual radial glia cell
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/)

 has_related_synonym
stretched cells
[https://doi.org/10.1016/B978-0-12-820584-6.00016-7](https://doi.org/10.1016/B978-0-12-820584-6.00016-7 "Persistent link using digital object identifier")

**Comment by JABelfiore** [comment]
[tanycyte]
Definition is great, no amends. 
Database_cross_reference to be added once David confirms

has_broad_synonym
radial glia-like cell
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/)

Paper cited frequently uses “resemblance to radial glial cells”  which means the same as “radial glia-like cell”, but can't find the specific wording in the paper. 

has_broad_synonym
residual radial glia cell
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/)

“residual radial glia cell” does not exist in paper  

However, stretched cells exist in this paper. 

has_related_synonym
stretched cells
https://doi.org/10.1016/B978-0-12-820584-6.00016-7

Can’t access this document. Suggest replacing reference with [PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/)


α1-tanycyte
Definition: Looks great, no amends
database_cross_reference:
https://en.wikipedia.org/wiki/Tanycyte  confirms location in ventromedial nucleus and the dorsomedial nucleus
[PMID:26578855 confirms α-tanycyte processes lack blood vessel contact](https://pubmed.ncbi.nlm.nih.gov/26578855) and that  It expresses the glial marker S-100β. Confirms proximity to parenchymal neurons
[PMID:16344112](https://pubmed.ncbi.nlm.nih.gov/16344112/) confirms hypothalamic location
Extended definition looks good.
database_cross_reference:
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) confirms expression in rodents

has_exact_synonym:
VMH tanycyte
abbreviation
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/) Confirms synonym


has_exact_synonym:
DMH tanycyte
abbreviation
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/) Confirms synonym


has_exact_synonym:
alpha1 tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) Confirms synonym


has_broad_synonym
α-tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) Confirms synonym




Logical definition looks good


α2-tanycyte
Definition looks good, no amends.


database_cross_reference:
https://en.wikipedia.org/wiki/Tanycyte[confirms location in dmARH](https://pubmed.ncbi.nlm.nih.gov/29351662/)
[PMID:29351662 confirms location in dmARH](https://pubmed.ncbi.nlm.nih.gov/29351662/)
[PMID:26578855 confirms mono-ciliated](https://pubmed.ncbi.nlm.nih.gov/26578855)
[PMID:16344112](https://pubmed.ncbi.nlm.nih.gov/16344112/)  confirms protrusions


Additional_definition looks good

[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) confirms expression
has_related_synonym:
dmARH tanycyte
database_cross_reference:
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/) confirms synonym 
has_exact_synonym:
alpha2 tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) confirms synonym 
has_broad_synonym
α-tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) confirms synonym 
Logical definition looks good
β1-tanycyte
Definition looks good, no amends.
[https://en.wikipedia.org/wiki/Tanycyte confirms location in ](https://en.wikipedia.org/wiki/Tanycyte)median eminence
[PMID:29351662 confirms multiple microvilli extension into third ventricle ](https://pubmed.ncbi.nlm.nih.gov/29351662/)
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855) confirms expression
[PMID:16344112](https://pubmed.ncbi.nlm.nih.gov/16344112/) confirms proximity to GRH neurons
has_exact_synonym:
beta1 tanycyte
Database_cross_reference: 
[PMID:26578855 confirms](https://pubmed.ncbi.nlm.nih.gov/26578855) synonym
has_broad_synonym:
β-tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855)confirms synonym 
has_related_synonym:
vmARH tanycyte
database_cross_reference:
[PMID:29351662 confirms](https://pubmed.ncbi.nlm.nih.gov/29351662/) synonym 
logical definition: looks good
subclass of tanycyte, expresses [FGF-1](http://purl.obolibrary.org/obo/IMR_0100551) and [FGF-2](http://purl.obolibrary.org/obo/IMR_0100551), involved in secretion of [GnRH](http://purl.obolibrary.org/obo/IMR_0100095), soma location [infundibular recess in the brain](http://purl.obolibrary.org/obo/UBERON_0006250)
taxon: mice, humans
β2-tanycyte
Definition looks good. 
database_cross_reference:
https://en.wikipedia.org/wiki/Tanycyte confirms median eminence location 
[PMID:29351662 confirms FGF receptors](https://pubmed.ncbi.nlm.nih.gov/29351662/)
[PMID:26578855 confirms multiple villi](https://pubmed.ncbi.nlm.nih.gov/26578855)
[PMID:16344112](https://pubmed.ncbi.nlm.nih.gov/16344112/) confirms GnRH 
has_related_synonym:
ME tanycytes
database_cross_reference:
[PMID:29351662](https://pubmed.ncbi.nlm.nih.gov/29351662/) confirms synonym 
has_exact_synonym:
beta2 tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855)confirms synonym 
has_broad_synonym:
β-tanycyte
database_cross_reference
[PMID:26578855](https://pubmed.ncbi.nlm.nih.gov/26578855)confirms synonym 


Logical definition: looks good

**Comment by AvolaAmg** [comment]
thank you @JABelfiore ! will turn this into a PR!
