### ISSUE TITLE
website - broken link to main release file

### ISSUE THREAD

**Issue by krchristie** [obophenotype/cell-ontology#2260]
**Description of typo, bug or error**

On your home page (https://obophenotype.github.io/cell-ontology/), under the **Accessing CL** header, this link:

- The main release file can also be found [here](https://raw.githubusercontent.com/obophenotype/cell-ontology/master/cl.owl).

generated a 404 error (1/5/2004 5 pm Pacific time)

**Comment by dosumis** [comment]
Thanks Karen.  @anitacaron - I think link just needs to change to release prod link.
