### ISSUE TITLE
Obsolete terms have URL to Github issues that are not IRI

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2272]
When a term is obsoleted, the standard is to include a term_tracker_item with the URL to the Github issue as IRI. This ticket is to track and edit those that do not follow the standard:
- obsolete barrier epithelial cell
- obsolete seminal fluid secreting cell
- obsolete primary pigment cell
- obsolete secondary pigment cell
- obsolete tertiary pigment cell

**Comment by shawntanzk** [comment]
Was a bit sick of my work so was finding something to do that was more fun so here I am, hi :D 

Here's a sparql query I ran to detect all with the above issue:

```sparql
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT *
WHERE {

  ?term ?predicate ?iri .
  FILTER EXISTS { ?term owl:deprecated true }
  FILTER (STRSTARTS(str(?iri), "https://github.com/"))
  FILTER (?predicate != <http://purl.obolibrary.org/obo/IAO_0000233>)
}
```
Came up with the following results:

term | predicate | iri
-- | -- | --
http://purl.obolibrary.org/obo/CL_0000665 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/726
http://purl.obolibrary.org/obo/CL_0002371 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/1150
http://purl.obolibrary.org/obo/CL_0017501 | http://www.w3.org/2000/01/rdf-schema#seeAlso | https://github.com/obophenotype/cell-ontology/issues/734
http://purl.obolibrary.org/obo/CL_4023073 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/2043
http://purl.obolibrary.org/obo/CL_0000073 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/1149
http://purl.obolibrary.org/obo/CL_0000161 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/427
http://purl.obolibrary.org/obo/CL_0000124 | http://www.w3.org/2000/01/rdf-schema#seeAlso | https://github.com/obophenotype/cell-ontology/issues/715
http://purl.obolibrary.org/obo/CL_0000426 | http://www.w3.org/2000/01/rdf-schema#seeAlso | https://github.com/obophenotype/cell-ontology/issues/708
http://purl.obolibrary.org/obo/CL_0000181 | http://www.w3.org/2000/01/rdf-schema#seeAlso | https://github.com/obophenotype/cell-ontology/issues/720
http://purl.obolibrary.org/obo/CL_0000321 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/1149
http://purl.obolibrary.org/obo/CL_0000243 | http://www.w3.org/2000/01/rdf-schema#seeAlso | https://github.com/obophenotype/cell-ontology/issues/715
http://purl.obolibrary.org/obo/CL_1001566 | http://www.w3.org/2000/01/rdf-schema#seeAlso | https://github.com/obophenotype/cell-ontology/issues/1443
http://purl.obolibrary.org/obo/CL_0000003 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/2124
http://purl.obolibrary.org/obo/CL_0000663 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/726
http://purl.obolibrary.org/obo/CL_0000548 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/2124
http://purl.obolibrary.org/obo/CL_0000664 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/726
http://purl.obolibrary.org/obo/CL_0000381 | http://www.w3.org/2000/01/rdf-schema#comment | https://github.com/obophenotype/cell-ontology/issues/1784          'neuroendocrine cell' (which has exact synonym "neurosecretory   cell") and 'neurosecretory neuron' may all refer to the same cell type.

Personally I would manually edit http://purl.obolibrary.org/obo/CL_0000381 to not have extra text, then run the following sparql query to replace 

```sparql
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

DELETE{
  ?term ?predicate ?iri .
}
INSERT{
  ?term <http://purl.obolibrary.org/obo/IAO_0000233> ?iri .
}
WHERE {

  ?term ?predicate ?iri .
  FILTER EXISTS { ?term owl:deprecated true }
  FILTER (STRSTARTS(str(?iri), "https://github.com/"))
  FILTER (?predicate != <http://purl.obolibrary.org/obo/IAO_0000233>)
}


```

Hope that helps :) 
Ok back to less fun work lol

**Comment by aleixpuigb** [comment]
Thank you very much Shawn, that helps a lot!
