### ISSUE TITLE
[Text def] Cell types with missing definition

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2283]
The following terms are lacking a definition.

**CL term**
[kidney interstitial fibroblast](http://purl.obolibrary.org/obo/CL_1000692)
[omentum preadipocyte](http://purl.obolibrary.org/obo/CL_0002579)
[perirenal preadipocyte](http://purl.obolibrary.org/obo/CL_0002581)
[kidney medulla cell](http://purl.obolibrary.org/obo/CL_1000504)
[kidney cortex interstitial cell](http://purl.obolibrary.org/obo/CL_1000681)
[kidney medulla interstitial cell](http://purl.obolibrary.org/obo/CL_1000682)
[kidney inner medulla interstitial cell](http://purl.obolibrary.org/obo/CL_1000803)
[kidney outer medulla interstitial cell](http://purl.obolibrary.org/obo/CL_1000804)
[kidney resident dendritic cell](http://purl.obolibrary.org/obo/CL_1000699)
[kidney blood vessel cell](http://purl.obolibrary.org/obo/CL_1000854)
[vasa recta cell](http://purl.obolibrary.org/obo/CL_1001036)

**Comment by AvolaAmg** [comment]
CL term
[kidney interstitial fibroblast](http://purl.obolibrary.org/obo/CL_1000692)
A fibroblast that is located in the interstitial compartment of the kidney 
database_cross_reference
[PMID:10559635](https://pubmed.ncbi.nlm.nih.gov/10559635/)


[omentum preadipocyte](http://purl.obolibrary.org/obo/CL_0002579) 
a preadipocyte that is part of the omentum 
database_cross_reference
[PMID:21484051](https://pubmed.ncbi.nlm.nih.gov/21484051) 

[perirenal preadipocyte](http://purl.obolibrary.org/obo/CL_0002581)
a preadipocyte that is part of the perirenal fat tissue 
database_cross_reference
[PMID:31079959](https://pubmed.ncbi.nlm.nih.gov/31079959)

[kidney medulla cell](http://purl.obolibrary.org/obo/CL_1000504)
A cell that is part of the renal medulla
database_cross_reference 
[PMID:22343825](https://pubmed.ncbi.nlm.nih.gov/22343825)


[kidney cortex interstitial cell](http://purl.obolibrary.org/obo/CL_1000681)
A cell that is located in the interstitial compartment of the renal cortex 
database_cross_reference
[PMID:18575881](https://pubmed.ncbi.nlm.nih.gov/18575881)

[kidney medulla interstitial cell](http://purl.obolibrary.org/obo/CL_1000682)
A cell that is located in the interstitial compartment of the renal medulla 
database_cross_reference
[PMID:21359760]
DOI: [10.1385/0-89603-335-X:437](https://doi.org/10.1385/0-89603-335-x:437)


[kidney inner medulla interstitial cell](http://purl.obolibrary.org/obo/CL_1000803)
A cell that is located in the interstitial compartment of the inner renal medulla
database_cross_reference
PMID: 21359760  DOI: [10.1385/0-89603-335-X:437](https://doi.org/10.1385/0-89603-335-x:437)

[kidney outer medulla interstitial cell](http://purl.obolibrary.org/obo/CL_1000804)
A cell that is located in the interstitial compartment of the outer renal medulla
database_cross_reference
PMID:21359760  DOI: [10.1385/0-89603-335-X:437](https://doi.org/10.1385/0-89603-335-x:437)
PMID:8694267  DOI: [10.1007/BF00186688](https://doi.org/10.1007/bf00186688)

[kidney nerve cell](http://purl.obolibrary.org/obo/CL_1000606)

**question** I have some doubts about this. from my understanding "kidney nerve cell" points to a nerve in the kidney, but a nerve is not a cell but a bundle of axons so one cannot define it as a cell (?). 

[kidney resident dendritic cell](http://purl.obolibrary.org/obo/CL_1000699)
A dendritic cell that is resident in the kidney
database_cross_reference
PMID: [34843404](https://pubmed.ncbi.nlm.nih.gov/34843404)

**question** : in this reference, they found that the dendritic cells in the scRNA-seq were divided into  Cd11+ dendritic cells, Cd11− dendritic cells, and plasmacytoid dendritic cell clusters. Can I add this in the definition or it is too ambiguous to say? (considering that it is just one paper on scRNA-seq that sees this)


[kidney blood vessel cell](http://purl.obolibrary.org/obo/CL_1000854)
a blood vessel cell that is part of the kidney 
PMID:34843404

[vasa recta cell](http://purl.obolibrary.org/obo/CL_1001036)
A cell that is part of the vasa recta
PMID:[24381184](https://pubmed.ncbi.nlm.nih.gov/24381184)
PMID:12529271


Are these references good enough or should I use something more specific? 
Can you use the same reference for two different cell types?
