### ISSUE TITLE
[NTR] border associated macrophage

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2285]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**

border associated macrophage

**Synonyms** (add reference(s), please)

BAM 
https://doi.org/10.1038/s41586-023-06808-9.

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

A type of macrophage with an elongated cell body with numerous processes that extend along the borders of the CNS - in the choroid plexus, meningeal and perivascular spaces This distinctive morphology allows them to interact with various components of the CNS vasculature and meninges, as well as participate in immune surveillance and regulation of the blood-brain barrier.

(Note - def partly derived from LLM content.  Please check against references!)

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10217436/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10452120/

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

macrophage

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

choroid plexus, meningeal and perivascular spaces

Please check Uberon for some suitable collective term to cover these.

**Your ORCID**

**Additional notes or concerns**

**Comment by dosumis** [comment]
@AvolaAmg - this is a term needed for mouse brain annotation.  Might be useful to follow along with fixes.

**Comment by lubianat** [comment]
@dosumis Maybe we need to create "brain border" in Uberon first. 

A subclass of [regional part of brain](http://purl.obolibrary.org/obo/UBERON_0002616), perhaps? 

It is a complex modelling, as "perivascular space" is an immaterial entity and "choroid plexus" is a material entity. Nevertheless, it is an important concept to model. General ref: 

https://www.nature.com/articles/s41586-022-05474-7

**Comment by dosumis** [comment]
> "CAMs are also known as border-associated macrophages (BAMs) and encompass perivascular macrophages (PVMs), subdural leptomeningeal macrophages (MMs), and choroid plexus macrophages ([3](https://www.annualreviews.org/doi/10.1146/annurev-immunol-093019-110159#)–[7](https://www.annualreviews.org/doi/10.1146/annurev-immunol-093019-110159#))."

Given this, it's probably worth making the subclasses at the same time.

**Comment by AvolaAmg** [comment]
I had a look at the central nervous system macrophages and this is what I think we should add/modify. Let me know what you think

new term request borderline associated macrophages
-
**Preferred term label**
Borderline Associated Macrophage

**Definition**
A macrophage that has an elongated cell body with dynamic processes. This macrophage is resident in the choroid plexus, meningeal and perivascular spaces. A borderline associated macrophage interacts with various components of the CNS vasculature and meninges, it participates in immune surveillance and in the regulation of the blood brain barrier.
databasa_cross_refence
[PMID:37232741](https://pubmed.ncbi.nlm.nih.gov/37232741)
[PMID:37626977](https://pubmed.ncbi.nlm.nih.gov/37626977)

**synonym**
BAC
**database_cross_reference**
[PMID:36945367](https://doi.org/10.1038/s41586-023-06808-9%E2%80%A8)

**synonym:**
CAM
**Database_cross_reference:**
[PMID:33556248](https://doi.org/10.1146/annurev-immunol-093019-110159)

**comment**
A border associate macrophage expresses CD45 and CD11B. This cell is also known to have the following molecular signature: CD206, CD38, LYVE1, CD163, CD169

**database_cross_reference**
[PMID:29426702](https://doi.org/10.1016/j.immuni.2018.01.011)
[PMID:37232741](https://pubmed.ncbi.nlm.nih.gov/37232741)

**parent cell term:**
central nervous system macrophage

Add synonyms for [meningeal macrophage](http://purl.obolibrary.org/obo/CL_0000879) and revise cell definition:
-

**label** 
Meningeal Macrophage

**definition:**
A central nervous system macrophage resident in the meninges. This macrophage types is highly phagocytic, expresses scavenger receptors, has dynamic protrusions and extends its processes during inflammation. The cell body of this macrophage is elongated and amoeboid spindle-shaped with limited mobility.

**database_cross_reference** <-- these need to be added to the ones that are already present in CL
[PMID:37232741](https://pubmed.ncbi.nlm.nih.gov/37232741)
[PMID:24078900](https://pubmed.ncbi.nlm.nih.gov/24078900)
[PMID:24078900](https://doi.org/10.4161%2Fintv.22823)

**synonym**
Subdural leptomeningeal macrophages

**database_cross_reference:**
[PMID:33556248](https://doi.org/10.1146/annurev-immunol-093019-110159)

**synonym**
subdural meningeal macrophages

**database_cross_reference:**
[PMID:28323268](https://doi.org/10.1038/ni.3703)

synonym
sdMΦ

**database_cross_reference:** 
[PMID:33556248](https://doi.org/10.1146/annurev-immunol-093019-110159)

**parent cell term:**
Border Associated Macrophages

 Add synonym of [choroid-plexus macrophage](http://purl.obolibrary.org/obo/CL_0000880) and modify the definition:
-

**definition**
A central nervous system macrophage found at the interface between the blood and the cerebrospinal fluid in the brain. This central nervous system macrophage expresses scavenger receptors, has a star-like shaped body.

**database_cross_reference**
[PMID:37232741(https://pubmed.ncbi.nlm.nih.gov/37232741)

**synonym **
cpepiMΦ
**database_cross_reference**
[PMID:37232741(https://pubmed.ncbi.nlm.nih.gov/37232741)

**perivascular macrophage synonym**
 A central nervous system macrophage found in small blood vessels in the brain. Markers include CD14, CD16, CD163. In homeostatic conditions, this central nervous system macrophage has a Non-motile cell body with extending and retracting projections through the blood vessel wall.

**database_cross_reference**
[PMID:37232741](https://pubmed.ncbi.nlm.nih.gov/37232741)

**synonym** 
pvMΦ
**database_cross_reference**
[PMID:37232741](https://pubmed.ncbi.nlm.nih.gov/37232741)

**parent cell term:**
Border Associated Macrophages


New Term Request Choroid epiplexus macrophage
-

**label**
choroid epiplexus macrophage

**definition**
A central nervous system macrophage that is located in the apical surface of the Choroid Plexus epithelium. This macrophage has a star-like shaped body.

**database_cross_reference**
[PMID:37232741](https://pubmed.ncbi.nlm.nih.gov/37232741)
[PMID:31061494](https://pubmed.ncbi.nlm.nih.gov/31061494/)

**synonym**
Kolmer’s cell
**database_cross_refence**
[PMID:31061494](https://pubmed.ncbi.nlm.nih.gov/31061494/)

**synonym**
cpMΦ
**database_cross_reference**
[PMID:31061494](https://pubmed.ncbi.nlm.nih.gov/31061494/)

**parent cell term:**
Border Associated Macrophages


New Term Request dural macrophages
-

**label**
dural macrophages

**definition**
A central nervous system macrophage which is part of the dura matter. This macrophage phagocytoses intruding pathogens and foreign molecules detected in the bloodstream or in the cerebrospinal fluid. This cell has an amoeboid body with dynamic protrusions in homeostasis. 

**database_cross_reference**
[PMID:31061494](https://pubmed.ncbi.nlm.nih.gov/31061494/)

**synonym**
cpMΦ
**database_cross_reference**
[PMID:31061494](https://pubmed.ncbi.nlm.nih.gov/31061494/)

**parent cell term:**
Border Associated Macrophages


I feel that the microglia should also be revised, I will have a quick read around to make sure that everything is in place
