### ISSUE TITLE
[NTR] preplasmablast 

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#2288]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
preplasmablast

**Synonyms** (add reference(s), please)
prePB (used in several published papers)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
Figure from Moreaux, Jerome. 2021. 
<img width="846" alt="Screenshot 2024-02-19 at 3 34 07 PM" src="https://github.com/obophenotype/cell-ontology/assets/47257000/97d6e6bf-9e10-4791-876a-5e1ba5473b1a">

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
After digging through the literature I believe the Moreau paper had best evidence that preplasmablasts are in the lineage of naive B cells, but activated by Interleukin 4.

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

palatine tonsil UBERON:0002373 http://purl.obolibrary.org/obo/UBERON_0002373

**literature citations**
Moreaux, Jerome. 2021. “The Origin of Preplasmablastic Cells.” Blood 137 (9): 1134–35. https://doi.org/10.1182/blood.2020009746.

**this citation provides markers of preplasmablasts and differences between plasmablasts and plasma cells** Michel Jourdan, Anouk Caraux, Gersende Caron, Nicolas Robert, Geneviève Fiol, Thierry Rème, Karine Bolloré, Jean-Pierre Vendrell, Simon Le Gallou, Frédéric Mourcin, John De Vos, Alboukadel Kassambara, Christophe Duperray, Dirk Hose, Thierry Fest, Karin Tarte, Bernard Klein; Characterization of a Transitional Preplasmablast Population in the Process of Human B Cell to Plasma Cell Differentiation. J Immunol 15 October 2011; 187 (8): 3931–3941. https://doi.org/10.4049/jimmunol.1101230
"Preplasmablasts lack documented B cell or plasma cell (CD20, CD38, and CD138) markers, express CD30 and IL-6R, and secrete Igs at a weaker level than do plasmablasts or plasma cells. These preplasmablasts further differentiate into CD20−CD38highCD138− plasmablasts and then CD20−CD38highCD138+ plasma cells. "

**Your ORCID**
Ellen M. Quardokus 0000-0001-7655-4833

**Additional notes or concerns**
Not the same as plasmablast or plasma cell. This is a distinct cell type.

**Comment by aleixpuigb** [comment]
Thank you for the request.

In [Jourdan et al., 2011](https://doi.org/10.4049/jimmunol.1101230), a counterpart of the described preplasmablast in vitro is found in lymph nodes and tonsils. We can add the relationship 'has part' preplasmablast in palatine tonsils, but I would not add 'preplasmablast SubclassOf 'part of' some 'palatine tonsil'.

The parent term can be `mature B cell`, which is already a parent term of 'naive B cell' and 'plasmablast'. I can also add `'develops into' some plasmablast` and `'develops from' some 'naive B cell'`.

Proposed definition:
> A mature B cell that serves as an intermediate stage in the differentiation of naive B cells into a plasmablast. A preplasmablast expresses CD30 and IL-6R and lacks expression of CD20, CD23, CD38 and CD138.

Additional synonyms:
pre-plasmablast [PMID:23613519](https://doi.org/10.1182/blood-2012-12-471953)
preplasmablastic cell [PMID:33661294](https://doi.org/10.1182/blood.2020009746)
