### ISSUE TITLE
[Logical def] Kidney blood vessel cell revise logical definition

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2290]
**CL term**
[Kidney blood vessel cell](http://purl.obolibrary.org/obo/CL_1000854)

**Current logical definition**
`'kidney medulla cell' and ('part of' some 'kidney blood vessel')`

**Suggested revision of logical definition**
`'cell' and ('part of' some 'kidney blood vessel')`

**Comment by AvolaAmg** [comment]
@aleixpuigb

**Comment by aleixpuigb** [comment]
I agree, the logical definition was too narrow, since there are blood vessel cells in the renal cortex, specially microvessels. https://en.wikipedia.org/wiki/Renal_cortex
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3936257/
