### ISSUE TITLE
[NTR] TAC3-positive interneuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2300]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
TAC3-positive interneuron

**Synonym** 
TAC3 interneuron 
 **database_cross_reference**
  [PMID:34727523](https://pubmed.ncbi.nlm.nih.gov/34727523/)

**Definition:**
A GABAergic interneuron that has its soma in the striatum and that has an enriched expression of the gene TAC3. 
**database_cross_reference:**:
[PMID:34727523](https://pubmed.ncbi.nlm.nih.gov/34727523/)

**Parent cell type term**
[GABAergic interneuron](http://purl.obolibrary.org/obo/CL_0011005)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[striatum](http://purl.obolibrary.org/obo/UBERON_0002435)

**Additional notes or concerns**
In Human, Rhesus Macaque, and Marmoset, TAC3-positive interneuron has its soma in the striatum.
**database_cross_reference:** 
[PMID:34727523](https://pubmed.ncbi.nlm.nih.gov/34727523/)
  [PMID:34727523](https://pubmed.ncbi.nlm.nih.gov/34727523/)

**Comment by AvolaAmg** [comment]
@aleixpuigb @dosumis

**Comment by aleixpuigb** [comment]
Looks good! There is a small typo in the notes (TC3-positive).
Remember to use `'has soma location' some striatum` instead of 'part of'. Also, you can consider adding 'has plasma membrane part' some [tachykinin-3](http://purl.obolibrary.org/obo/PR_000016004).
