### ISSUE TITLE
[NTR-cxg] nasal serous secreting cell

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2316]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

I have not found extensive information on the exact location of nasal serous secreting cells, I just decided to include "nasal cavity" only. Suggestions are welcome. 

**IMPORTANT**: This cell has been identified from a CellxGene [dataset](https://cellxgene.cziscience.com/e/066943a2-fdac-4b29-b348-40cede398e4e.cxg/) through a knowledge graph analysis. Tracker for novel cell terms identified from CxG dataset through knowledge graphs can be found [here](https://docs.google.com/spreadsheets/d/1mZWx7Wuh0yWrAMIGPqiI_6Wpu_ZoaCHtbcCV3opbEYs/edit?pli=1#gid=0).

**Preferred term label**
nasal serous secreting cell

**Synonym(s)** (add reference(s), please)
SMG serous (nasal)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A serous secreting cell that is part of the nasal cavity.

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
[serous secreting cell](http://purl.obolibrary.org/obo/CL_0000313)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[nasal cavity](http://purl.obolibrary.org/obo/UBERON_0001707)

**Your ORCID**
https://orcid.org/0000-0002-0098-8958

**Additional notes or concerns** If there are markers that uniquely identify the cell type in a particular species, they can be added here.
The CellxGene dataset found to identify this cell type is from this paper [PMID:37291214](https://pubmed.ncbi.nlm.nih.gov/37291214)

**Comment by AvolaAmg** [comment]
@aleixpuigb

**Comment by emquardokus** [comment]
SMG stands for submucosal gland which is the region of this cell type. I am getting more information from research group as this is part of lung combined HLCA

**Comment by emquardokus** [comment]
I was working up a new list of NTRs and this was on it with appropriate uberon NTRs.

**Comment by scheuerm** [comment]
Probably a silly question but what is NTR?

**Comment by emquardokus** [comment]
@scheuerm New Term Request (NTR) 😁
