### ISSUE TITLE
[NTR] Protoplasmic Astrocyte, Fibrous Astrocyte, Interlaminar Astrocyte.

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2328]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

I was having a look at this paper [PMID:37824655](https://pubmed.ncbi.nlm.nih.gov/37824655/) and I have realised some astrocytes terms are missing:

###  protoplasmic astrocyte 

**Definition**
An astrocyte cell that has highly branched protrusions, its soma is part of the neocortex and it is found between layer 2 and 6 [PMID:37139179](https://pubmed.ncbi.nlm.nih.gov/37139179/) [PMID:25904839](https://pubmed.ncbi.nlm.nih.gov/25904839/).
The protoplasmic astrocyte is involved in the formation and elimination of the synapses, in the clearance of glutamate, in the modulation of synaptic functions and in the regulation of blood flow in response to synaptic activity [PMID:25904839](https://pubmed.ncbi.nlm.nih.gov/25904839/).

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
[astrocyte of the cerebral cortex](http://purl.obolibrary.org/obo/CL_0002605)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)

**comments**
This astrocyte extends its branches to several hundred of dendrites to multiple neurons to envelope 100.000 or more synapses[PMID:20012068](https://pubmed.ncbi.nlm.nih.gov/20012068). In humans, a protoplasmic astrocyte has an average diameter of 142 µm, and its diameter ranges between 100 and 400 µm. In rodents the average diameter of a protoplasmic astrocites is 56 µm [PMID:19279265](https://pubmed.ncbi.nlm.nih.gov/19279265).

### fibrous astrocyte

**Definition**
An astrocyte cell with long fiber-like processes, the soma of this astrocyte is part of the white matter and its soma and processes are oriented along the white matter tracts [PMID:22144298](https://pubmed.ncbi.nlm.nih.gov/22144298). This astrocyte type has several contacts with the vasculature of the nervous system and is involved in metabolic support. [PMID:28280934](https://pubmed.ncbi.nlm.nih.gov/28280934/).

**Parent cell type term**
[astrocyte](http://purl.obolibrary.org/obo/CL_0000127)

**comments**
In humans, a fibrous astrocyte diameter is around 182 µm whereas in rodent a fibrous astrocyte diameter is around 85 µm [PMID:28280934](https://pubmed.ncbi.nlm.nih.gov/28280934/).

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[white matter](http://purl.obolibrary.org/obo/UBERON_0002316)

### interlaminar astrocyte

An astrocyte type that presents radial protrusions across the layers of the cortex. The soma of this astrocyte type is part of the first layer of the neocortex and this astrocytes extents its protrusions transversally to the deeper layers of the cortex [PMID:32930323](https://pubmed.ncbi.nlm.nih.gov/32930323/). The protrusion of this astrocyte type create contact with neurons, the pia matter and capillaries. This astrocyte is involved in facilitating the communication across neurons, astrocytes, capillaries, meninges and the cerebrospinal fluid [PMID:30552685](https://pubmed.ncbi.nlm.nih.gov/30552685).

Has a related synonym: 
ILA
Synonym type: 
abbreviation
[PMID:30552685](https://pubmed.ncbi.nlm.nih.gov/30552685) 

parent term: 
[astrocyte of the cerebral cortex astrocyte](http://purl.obolibrary.org/obo/CL_0002605)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)

### pial Interlaminar astrocyte

An interlaminar astrocyte type whose soma is part of the first layer of the neocortex and is in contact with the pia surface. 

parent term: Interlaminar astrocyte

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)

### subpial Interlaminar astrocyte

An interlaminar astrocyte type whose soma is part of the upper first layer of the neocortex and its processes extend to a pia surface.

parent term: Interlaminar astrocyte 

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)

**Comment by aleixpuigb** [comment]
These cell types also have individual tickets: #2320, #2321 and #2322:

Preferred term label
fibrous astrocyte

Synonym(s) (add reference(s), please)
[Astro L1-6 FGFR3 AQP1 primary motor cortex astrocyte (Hsap) (PCL:0015122)](http://purl.obolibrary.org/obo/PCL_0015122)

Definition (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
An astrocyte of the cerebral cortex that is found in white matter.
PMID: 19279265, 31435019, 34616062

Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
astrocyte (CL:0000127)

Anatomical structure where the cell type is found (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
cerebral cortex (UBERON:0000956)

Your ORCID
0000-0001-5287-0284

---

Preferred term label
interlaminar astrocyte

Synonym(s) (add reference(s), please)
[Astro L1-2 FGFR3 GFAP middle temporal gyrus astrocyte (Hsap) (PCL:0023072)](http://purl.obolibrary.org/obo/PCL_0023072)
[Astro L1 FGFR3 SERPINI2 primary motor cortex astrocyte (Hsap) (PCL:0015123)](http://purl.obolibrary.org/obo/PCL_0015123)

Definition (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
An astrocyte of the cerebral cortex that is found in layer 1 and extends long processes through layers 2-4 in humans.
PMID: 19279265, 31435019, 34616062

Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
astrocyte (CL:0000127)

Anatomical structure where the cell type is found (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
cerebral cortex (UBERON:0000956)

Your ORCID
0000-0001-5287-0284

----

Preferred term label
protoplasmic astrocyte

Synonym(s) (add reference(s), please)
[Astro L1-6 FGFR3 SLC14A1 middle temporal gyrus astrocyte (Hsap) (PCL:0023071)](http://purl.obolibrary.org/obo/PCL_0023071)
[Astro L1-6 FGFR3 PLCG1 primary motor cortex astrocyte (Hsap) (PCL:0015124)](http://purl.obolibrary.org/obo/PCL_0015124)

Definition (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
An astrocyte of the cerebral cortex that is found in all cortical layers and exhibits a highly branched morphology.
PMID: 19279265, 31435019, 34616062

Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
astrocyte (CL:0000127)

Anatomical structure where the cell type is found (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
cerebral cortex (UBERON:0000956)

Your ORCID
0000-0001-5287-0284

**Comment by aleixpuigb** [comment]
In PMID:[37139179](https://pubmed.ncbi.nlm.nih.gov/37139179) lists 4 types of astrocytes:

> Of note, four types of astrocytes have been observed in humans: interlaminar, varicose projections, protoplasmic and fibrous. With the exception of varicose projections astrocytes, all the other types were also found in the mouse brain, with several morphometric differences outlined in the section below.

I could not find varicose projection astrocyte in CL, so you might want to include it.

**Comment by AvolaAmg** [comment]
Thanks for your suggestion, I wanted to include the varicose projection astrocytes but I found other evidence that was saying that they are unsure whether it is a different type of astrocytes all together or just a different state. 

see [PMID:34533866](https://pubmed.ncbi.nlm.nih.gov/34533866/)

>Due to their location, their long tangential processes, and their irregular presence within species, we propose that VP-As are astrocytes that develop varicosities under specific conditions and that are not a distinct astrocyte type.
