### ISSUE TITLE
Change text definitionintratelencepalic-projecting glutamatergic neurons in CL. Consider including their morphological and transcriptomic characteristics and just insert the layer of origin in the "comment" section

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2339]
Change text definition for intratelencepalic-projecting glutamatergic neurons in CL. Mention transcriptomic distinction, include morphological and electrophysiological definition where possible, mention soma location where possible. Add standard transcriptomic reference data from CellxGene census.

**Comment by AvolaAmg** [comment]
I will review the text definition for the CL terms listed below and see if I can include more morphological, electrophysiological, transcriptomic informations. In the comment section, I will mention that historically these cells were defined based on their layer positioning, but this definition has changed with transcriptomic informations.
This is the list of CL terms:

[L2 intratelencephalic projecting glutametergic neuron](http://purl.obolibrary.org/obo/CL_4030060)
[L2/3 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030059)
[L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023047)
[L3 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030061)
[L4 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030063)
[L4/5 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030062)
[L4/5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023048)
[L5 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030064)
[L5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023049)
[L6 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030065)
[L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023050)
[L6 intratelencephalic projecting Car3 glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030068)
[L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](https://github.com/obophenotype/cell-ontology/issues/2339)
[L2/3 bipolar vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023007)
[L5 vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023014)
[L2/3 bipolar vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023007)
[L5/6 cck, vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023019)
[L5/6 near-projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030067)
Another point to consider:
the SST IT GABAergic cortical interneurons have in their text definition and in their cell label a specific link to Mmus (Also the VIP neurons mentioned above). Is it worth considering revising these definitions to see if there can be a universal definition encompassing also Homo sapiens and other primates?
These are the cells:

[L2/3/5 fan Martinotti sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023030)
[L4 sst Martinotti interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023031)
[L5 non-Martinotti sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023028)
[L5 sst T-Martinotti interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023027)
[L5/6 non-Martinotti sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023118)
[L6 th sst GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023075)

**Comment by AvolaAmg** [comment]
### TEXT DEFINITIONS TO CHANGE 

Main points:

- I haven't been able to find enough informations about L2 IT and L3 IT neurons, nowadays all the papers refer as L2/3 neurons expect for the hippocampal paper. I am not sure whether we should consider to define these terms as obsolete. 
- NTR -> L2 marginal neurons, L2MNs (https://www.frontiersin.org/articles/10.3389/fnana.2017.00115/full)
- For the L2/3 IT motor cortex neuron, the reference paper does not have the data on CxG. however this other paper references to the primary motor cortex L2/3 neurons, we could include this as a reference and also include their transcriptomic signature which is mentioned in the paper perhaps?
- L4 IT neurons are quite complex, require some more work for their definition 


[L2 intratelencephalic projecting glutametergic neuron](http://purl.obolibrary.org/obo/CL_4030060)

Old definition: 
A transcriptomically distinct intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 2 in the Mmus. The standard transcriptomic reference for this cell type can be found in the CellxGene census under the collection: "A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation", dataset: "Single-cell RNA-seq for all cortical & hippocampal regions (10x)", Author Categories: "subclass_label",  L2 IT ENT EN, L2 IT ENTm EN.



[L2/3 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030059)

Old definition: 
An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 2/3.

New definition:
A transcriptomically distinct intratelencephalic-projecting glutamatergic neuron with a soma found between cortical layer 2-4. This intratelencephalic-projecting glutamatergic neuron has thin-tufted apical dendrites and extends its axonal projection into L5 in the neocortex. This neuronal type has a hyperpolarised resting membrane potential. The standard transcriptomic reference data for this cell type can be found on the CellxGene census under the collection: "Transcriptomic cytoarchitecture reveals principles of human neocortex organization", dataset: "Supercluster: IT-projecting excitatory neurons", Author Categories: "CrossArea_cluster", clusters L2/3 IT_1-6. 
https://www.nature.com/articles/nn.3917#Tab2

Comment: 

Hystorically, the L2/3 intratelencephalic projectic glutametergic neuron was known to have its soma in cortical layer 2/3. MERFISH data showed that this intratelencephalic-projecting glutametergic neuron can have its soma in layer 2/3, 4B, 4C. The position of the soma in layer 4b and 4C is less frequent for this neuronal type in comparison to cortical layer 2/3.


 [L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex](http://purl.obolibrary.org/obo/CL_4023047)

Old Definition
An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 2/3 of the primary motor cortex.

New defintion: 

A transcriptomically distinct intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 2/3 of the primary motor cortex. The standard transcriptomic reference for this cell type can be found in the CellxGene census under the collection "An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types", dataset: "An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types", Author_categories: "BICCN_subclass_label", L2/3 IT.



- [L3 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030061)

Old definition: 
An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 3.

New definition: 
A transcriptomically distinct intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 3. The standard transcriptomic reference for this cell type can be found in the CellxGene census under the collection: "A taxonomy of transcriptomic cell types across the isocortex and hippocampal formation", dataset: "Single-cell RNA-seq for all cortical & hippocampal regions (10x)", Author Categories: "subclass_label",  L3 IT ENT.

[L4 intratelencephalic projecting glutamatergic neuron](L4 intratelencephalic projecting glutamatergic neuron)

Old definition:
An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 4.

New Definition:
A transcriptomically distinct intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 3-4. This neuron type can have a pyramidal, star-pyramidal or spiny stellate morphology and projects its output to L2/3 and L5A/B. The reference for this neuron type

**Comment by AvolaAmg** [comment]
@aleixpuigb @dosumis Please review when you can :)
 and I will turn this ticket into a PR.

**Comment by dosumis** [comment]
I think this is a good start.  

Some thoughts:
- For all transcriptomic references  we should generate taxonomies from datasets & use the cell set IDs from these to generate formal links to the reference cell sets in the ontology.
- For CL this should be restricted to a small set of agreed reference datasets, but we can be broader in PCL (as we already are)
- We need to discuss whether we can/should reference multiple cells sets in a definition (we don't have formal linking mechanisms to cover this right now.

**Comment by dosumis** [comment]
For CL, I think we need to concentrate on cell types defined in Jorstad for now (crossArea_subclass)

e.g. => something like

A transcriptomically distinct near-projecting glutamatergic neuron with a soma found in cortical layer 5/6. The standard transcriptomic reference data for this cell type can be found on the CellxGene census under the collection: "Transcriptomic cytoarchitecture reveals principles of human neocortex organization", dataset: "Supercluster: Deep layer (non-IT) excitatory neurons", Author Categories: "CrossArea_subclass", L5/6 NP.

(But we may also be able to add NS-Forest markers.

**Comment by AvolaAmg** [comment]
Dear David, 

Thanks for your comments!

> For all transcriptomic references we should generate taxonomies from datasets & use the cell set IDs from these to generate formal links to the reference cell sets in the ontology.

Waiting to see what Jason and Brian say 

> For CL this should be restricted to a small set of agreed reference datasets, but we can be broader in PCL (as we already are)
> We need to discuss whether we can/should reference multiple cells sets in a definition (we don't have formal linking mechanisms to cover this right now.

Agreed, I think we need to run some bioinformatics analysis and justify why we believe those cell types can be referenced by two datasets. We could consider to use one dataset as the main reference in the text definition and have additional dataset where the cell types also appears in the comment section. 
For the Analysis I suggest running an integration across the two datasets and a person correlation to see how transcriptomically related the same cell type is across the two datasets.

> For CL, I think we need to concentrate on cell types defined in Jorstad for now (crossArea_subclass)

For now, I will add on CL the new text definitions for Jorstad crossArea_subclass cell types. I will turn this into a PR.

Best, 
Alida

**Comment by scheuerm** [comment]
> > We need to discuss whether we can/should reference multiple cells sets in a definition (we don't have formal linking mechanisms to cover this right now.
> 
> Agreed, I think we need to run some bioinformatics analysis and justify why we believe those cell types can be referenced by two datasets. We could consider to use one dataset as the main reference in the text definition and have additional dataset where the cell types also appears in the comment section. For the Analysis I suggest running an integration across the two datasets and a person correlation to see how transcriptomically related the same cell type is across the two datasets.
> 

We have some experience using a computational approach call FR-Match, to link cell types together from multiple datasets.  There are a couple of other tools developed by other groups for doing this as well.  Here's a link to our paper, where we compare how they perform - https://www.nature.com/articles/s41598-022-14192-z

**Comment by dosumis** [comment]
>>  For the Analysis I suggest running an integration across the two datasets and a ~~person~~ Pearson correlation to see how transcriptomically related the same cell type is across the two datasets.

> We have some experience using a computational approach call FR-Match, to link cell types together from multiple datasets.

Let's see if we have resources. This could be a good place we could collaborate.  Scores could be very useful to add to CL-KG.
