### ISSUE TITLE
Revise cell label and definition for cortical VIP neurons in CL.

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2344]
In the light of having a complete taxonomy for cell types of the CNS, we are reviewing terms present in the Jorstad paper (see citation below). This ticket aims to discuss a definition for VIP GABAergic interneuron and their subclasses that includes also their transcriptomic signature. 

The concept is to add a CxG link to the cell definition of VIP GABAergic interneurons and indication where these cells can be found. 

Another point is to add the supercluster: CGE-derived interneurons and to group cells underneath accordingly.

Nikolas L. Jorstad et al. ,Transcriptomic cytoarchitecture reveals principles of human neocortex organization.Science382,eadf6812(2023).DOI:[10.1126/science.adf6812](https://doi.org/10.1126/science.adf6812)

**Comment by AvolaAmg** [comment]
In this ticket the following points are discussed:
- Changing the text definition of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016) to add the CxG reference. Add other synonyms and references.
- Consider whether to add 4 cell types as new CL terms downstream of  [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016) as subtypes, or whether to add the 4 cell types in the comment section of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016) 
- Grouping of CL terms downstream of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)
  
Points related to this ticket, will be discussed in other tickets.
- NTR: CGE-derived interneuron. As a parent term of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)
- NTR: spiny VIP neurons (Mmus). As a term downstream of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)
- NTR: VIP-ChAT neuron (Mmus). As a term downstream of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)

[vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)

**New Definition:**
A transcriptomically distinct GABAergic neuron located in the cerebral cortex that expresses vasoactive intestinal polypeptide. The standard transcriptomic reference data for this cell type can be found on the CellxGene census under the collection: 'Transcriptomic cytoarchitecture reveals principles of human neocortex organization', dataset: 'Supercluster: CGE-derived interneurons', Author Categories: 'CrossArea_cluster', cluster Vip. 

**database_cross_reference:**
https://cellxgene.cziscience.com/e/e4ddac12-f48f-4455-8e8d-c2a48a683437.cxg/

**has related synonym:**
VIP-Expressing GABAergic Neuron
**database_cross_reference**
[PMID:35221922](https://pubmed.ncbi.nlm.nih.gov/35221922)

**has related synonym:**
VIP type
**database_cross_reference**
[PMID:37824655](https://pubmed.ncbi.nlm.nih.gov/37824655/)

**has related synonym:**
VIP interneuron
**database_cross_reference**
[PMID:33108272](https://pubmed.ncbi.nlm.nih.gov/33108272/)

**has related synonym:**
VIP neuron
**database_cross_reference**
[PMID:33108272](https://pubmed.ncbi.nlm.nih.gov/33108272/)

**has related synonym**:
cortical VIP neuron
**database_cross_reference**
[PMID:36384143](https://pubmed.ncbi.nlm.nih.gov/36384143/)

**has related synonym:**
Vip GABAergic neuron
**database_cross_reference**
ILX:0770151

**has related synonym:**
Vip
**database_cross_reference**
ILX:0770151

**Parent term:**
CGE-derived interneuron
(term to be generated)

**Location:**
Neocortex 

**Symbol:**
VIP neuron



****
**Points of discussion**


1) Adding subtypes downstream to [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016) based on the information from this [paper](https://www.science.org/doi/10.1126/science.adf6484#abstract) or just include these subtypes in the comment section.
This [paper](https://www.science.org/doi/10.1126/science.adf6484#abstract) addresses the morphoelectric properties of cortical GABAergic interneurons in human. Some molecular markers are shown with Patch-seq.
In the context of VIP neurons, 4 different subtypes are found: VIP LBH, VIP SYT6, VIP CCD184, VIP ADAMTSL1. Their soma location, morphology, electrophysiology informations is available; however, there is no CxG reference dataset. 
![image](https://github.com/obophenotype/cell-ontology/assets/81253886/16be2bcc-109c-4a62-a090-9d3a6472f59d)


Should these cells be mentioned in the comments of [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)

i.e. 
**Comments:**
VIP neurons show heterogeneity in morphology, layer positioning and electrophysiological properties. In the Homo Sapiens cortex, 4 different subtypes of VIP neurons are identified; these neurons show different morphologies, soma location and electrophysiological properties (Lee et al., 2023). Specifically, the 4 VIP types are defined according to their transcriptomic markers: LBH-VIP (bipolar neuron, soma location L2), SY16-VIP (soma location L3), CCD184-VIP (bipolar neuron, soma location L3), ADAMTSL1-VIP (soma location L3). 

Or should I just add these as 4 different new CL terms downstream to the  [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)? 

I am a bit torn whether adding them or not as separate CL terms. I think there is no harm adding them as 4 new CL terms, for practical reasons as they would be easier to track. However, I had a look at CxG and the VIP neurons and only the LBH-VIP, and ADAMTSL1-VIP coincide with specific VIP clusters, so their markers do not fully coincide with the scRNA-seq data from Jorstad. 
Personally, I would prefer to adding them as CL terms. However I am not opposed to the idea of mentioning them just in the comments section (or completely ignore them)


2) The second point of discussion is related to the grouping of some VIP neurons found in CL:
   - [L2/3 bipolar vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023007)
   - [L5 vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023014)
   - [L5/6 cck, vip GABAergic interneuron (Mmus)](http://purl.obolibrary.org/obo/CL_4023019)
I think these neurons should have as a parent term [vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016). However the vip GABAergic cortical interneuron uses as a transcriptomic definition a Homo Sapiens CxG reference, whereas these neurons are Mmus and the CxG reference does not apply. Would it okay?

**Comment by AvolaAmg** [comment]
@dosumis please review.

**Comment by dosumis** [comment]
For lineage (CGE) - 
- this needs be inferred from develops_from relationship

**Comment by AvolaAmg** [comment]
Regarding the points of discussion:
After a call with the authors of the paper I have decided to add the 4 VIP cell types as new CL IDs.

The main point of the ticket is to re-draft the text definition of VIP interneurons as t-type. @dosumis please review the ticket, so that I can turn it into a PR.

**Comment by dosumis** [comment]
Please go ahead and make PR(s) with the new defs and terms.
