### ISSUE TITLE
[NTR] Lamp5 Lhx6 neuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2345]

**Comment by AvolaAmg** [comment]
New term label:
Lamp5 Lhx6 neuron

Parent term:
[lamp5 GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023011)

Definition:
A transcriptomically distinct lamp5 GABAergic cortical interneuron located in the cerebral cortex that expresses Lamp5 and Lhx6. The standard transcriptomic reference data for this cell type can be found on the CellxGene census under the collection: "Transcriptomic cytoarchitecture reveals principles of human neocortex organization", dataset: "Supercluster: CGE-derived interneurons", Author Categories: "CrossArea_cluster", Lamp5 Lhx6. 

database_cross_reference:
[PMID:34004146](https://pubmed.ncbi.nlm.nih.gov/34004146/)
[PMID:37824655](https://pubmed.ncbi.nlm.nih.gov/37824655/)
[PMID:37824669](https://pubmed.ncbi.nlm.nih.gov/37824669/)
[PMID:36007006](https://pubmed.ncbi.nlm.nih.gov/36007006/)

Anatomical location:
[neocortex](http://purl.obolibrary.org/obo/CL_4030060)

**Synonym** (has exact synonym)
Ivy cells
[PMID: 36007006](https://pubmed.ncbi.nlm.nih.gov/36007006/)

**Synonym** (has exact synonym)
Lamp5-Lhx6 type
[PMID:30382198](https://pubmed.ncbi.nlm.nih.gov/30382198)

@aleixpuigb @dosumis 
let me know if it is okay, I will turn it into a PR.
(p.s. in light of the discussion on this ticket, we decided to include the CellxGene collection title, as described in the text definition)

**Comment by dosumis** [comment]
Looks good.  In the absence of a more formal structure for referencing the data, I think it would also be good to add a link to the CellxGene dataset. 

We could also potentially add (perhaps at a later date)
 - NS Forest markers @scheuerm - do we have an ETA for this for CrossArea Subclass terms in Jorstad?
 -  formal link to cluster (defined by taxonomy).  Some more work needed to generate resolvable individuals for these.)

**Comment by AvolaAmg** [comment]
Should we add the CellxGene dataset link in the cell definition itself or in the comments ?
