### ISSUE TITLE
[NTR] L2 marginal neurons

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2346]

**Comment by AvolaAmg** [comment]
**New term label:**
L2 marginal neuron

**Parent term:**
[L2 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030060)

**Definition:**
An L2 intratelencephalic projecting glutamatergic neuron with a soma on the L1-L2 border. This neuron type has small apical dendrites projecting to L1. 

**database_cross_reference:**
[PMID:32108571](https://pubmed.ncbi.nlm.nih.gov/32108571/)
[PMID: 29311847](https://pubmed.ncbi.nlm.nih.gov/29311847/)

**Anatomical location:**
[neocortex](http://purl.obolibrary.org/obo/CL_4030060)

**synonym**
L2MN
[PMID:32108571](https://pubmed.ncbi.nlm.nih.gov/32108571/)
[PMID: 29311847](https://pubmed.ncbi.nlm.nih.gov/29311847/)


@aleixpuigb 
let me know if it is okay, I will turn it into a PR

**Comment by aleixpuigb** [comment]
There is an additional synonym 'layer 2 marginal neuron' in [PMID:32108571](https://pubmed.ncbi.nlm.nih.gov/32108571/)
I could not find in the references the above informations:
 - Parent term: [L2 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4030060)
 - "This neuron type has small apical dendrites projecting to L1."
Do you mind indicating me what part of the text is supporting the information?

**Comment by AvolaAmg** [comment]
Thanks for your review
for "This neuron type has small apical dendrites projecting to L1." 
The reference for "small apical dendrites" was extrapolated from this paper [PMID:32108571](https://pubmed.ncbi.nlm.nih.gov/32108571/) sentence:
"In these datasets we could furthermore distinguish L2 pyramidal cells located directly at the L1-L2 border with **a less prominent apical dendrite**"

and the information of "projecting to L1" was taken by this image in the same paper.

![image](https://github.com/obophenotype/cell-ontology/assets/81253886/977ed2f8-5785-4c96-8423-f3111367a1cd)

The parent term was a little bit trickier to assign. These cells are excitatory neurons that project into an area of the telencephalon. The telencephalon includes the cerebral cortex, subcortical white matter (commissural, association, and projection fibers), and basal nuclei. L2 marginal neurons project to the L1 layer of the cerebral cortex.

I could change their parent term to [L2/3-6 intratelencephalic projecting glutamatergic neuron](http://purl.obolibrary.org/obo/CL_4023040) instead.
