### ISSUE TITLE
Review CxG LLM driven defs & extract relevant info for CL terms

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2350]
Summary sheet here: https://docs.google.com/spreadsheets/d/1sOfT0fz_LlA2HEv8HoQk7ABBqkseAO_SFUndZW9FH_M/edit?gid=0#gid=0

(we need to check that this is up to date)

To check: Is the definition appropriate to the term? There are definitely examples where the definition applies to a different CL term, but CxG has validated. 
    - e.g. Alveolar Type 2 Fibroblast Cell [CL:4028006] has a def appropriate to AT2 (type II pneumocytes -see https://cellxgene.cziscience.com/cellguide/CL_4028006
    - Also sometimes definitions on general classes are more appropriate for their subclasses.

Extract relevant info for CL formal and textual defs. Details TBD.  For formal defs we are interested in ensuring formal links to GO terms are in place.

**Comment by anitacaron** [comment]
Done in PR #2530
