### ISSUE TITLE
Adjust Class hierarchy add synonyms to caudal ganglionic eminence derived interneuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2357]
I think this term [caudal ganglionic eminence derived GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023070) should just be a synonym of [caudal ganglionic eminence derived interneuron](http://purl.obolibrary.org/obo/CL_4023064) and not a different term. 

I had a look at a few papers, and they do not really describe CGE-derived interneurons that are not GABAergic. I can look a bit further if a discussion is needed.

**cell label:**
[caudal ganglionic eminence derived interneuron](http://purl.obolibrary.org/obo/CL_4023064)

**parent terms**
[interneuron](http://purl.obolibrary.org/obo/CL_0000099)

**downstream terms:**
[vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)
[lamp5 GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023011)
Lamp5 Lhx6 [NTR - #2345 ]
PAX6 neuron [NTR]
[sncg GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023015)
[vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)

**anatomical location**
neocortex

**Text definition (already present):**
A GABAergic cortical interneuron that develops from the caudal ganglionic eminence and has migrated to the cerebral cortex.

**database_cross_reference**
[PMID:20130169](https://pubmed.ncbi.nlm.nih.gov/20130169)
[PMID:37824663](https://pubmed.ncbi.nlm.nih.gov/37824663/)
[PMID:37824655](https://pubmed.ncbi.nlm.nih.gov/37824655/)
[PMID:20130169](https://pubmed.ncbi.nlm.nih.gov/20130169)

**has_a_related_synonym**
CGE-derived cell
CGE-derived GABAergic INs
**has_a_synonym_type**
abbreviation
**database_cross_reference**
[PMID:27034423](https://pubmed.ncbi.nlm.nih.gov/27034423/)

**has_a_related_synonym**
CGE-derived interneuron
**has_a_synonym_type**
abbreviation
**database_cross_reference**
[PMID:20130169](https://pubmed.ncbi.nlm.nih.gov/20130169)
[PMID:37824655](https://pubmed.ncbi.nlm.nih.gov/37824655/)

**has_a_related_synonym**
CGE cortical interneuron
**database_cross_reference**
[PMID:20130169](https://pubmed.ncbi.nlm.nih.gov/20130169)

**has_a_related_synonym**
 [caudal ganglionic eminence derived GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023070)
**database_cross_reference**
[PMID:20130169](https://pubmed.ncbi.nlm.nih.gov/20130169)

**has_a_related_synonym**
CGE interneuron
**has_a_synonym_type**
abbreviation
**database_cross_reference**
[PMID:37824663](https://pubmed.ncbi.nlm.nih.gov/37824663/)

**symbol**
CGE interneuron

@aleixpuigb @Caroline-99 @JABelfiore to review, once it is good to go, I will turn this into a PR

**Comment by dosumis** [comment]
Decision: 
 - Merge. 
 - Use term name from general class (as all, or almost all mammalian interneurons are GABAergic, we don't need this in the name)
 - Use EquivalentTo axiom from more specific class
