### ISSUE TITLE
[NTR] VIP-ChAT interneuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2359]
**cell label:**
VIP-ChAT interneuron

**parent term**
[vip GABAergic cortical interneuron](http://purl.obolibrary.org/obo/CL_4023016)

**Text definition:**
A vip GABAergic cortical interneuron expressing vasoactive intestinal polypeptide and choline acetyltransferase in the Mmus neocortex. This interneuron releases both γ-aminobutyric acid and acetylcholine.

**Database_cross_reference:**
[PMID:33301603](https://pubmed.ncbi.nlm.nih.gov/33301603/)
[PMID:32027647](https://pubmed.ncbi.nlm.nih.gov/32027647/)
[PMID:31754098](https://pubmed.ncbi.nlm.nih.gov/31754098/)
[PMID:30382198](https://pubmed.ncbi.nlm.nih.gov/30382198/)

**has_related_synonym:**
VIP+/ChAT+ cell
VIP+/ChAT+ interneuron
**database_cross_reference:**
[PMID:33301603](https://pubmed.ncbi.nlm.nih.gov/33301603/)

**has_related_synonym:**
VIP/ChAT interneuron
**database_cross_reference:**
[PMID:32027647](https://pubmed.ncbi.nlm.nih.gov/32027647/)

**had_related_synonym:**
VChI
**synonym type:**
abbreviation
**database_cross_reference:**
[PMID:32027647](https://pubmed.ncbi.nlm.nih.gov/32027647/)

**symbol:**
VChI

**comments:**
Work in the mouse barrel cortex and somatosensory cortex shows that a VIP-ChAT interneuron is predominantely located in L2/3 and more rarely in the deeper layers of the cortex (Dudai et al., 2021; Dudai et al., 2020). This neuronal type could be transcriptomically distinct as transcriptomic studies have identified VIP neurons expressing ChAT in a whole brain mouse transcriptomic study (Tasic et al., 2018).

**database_cross_reference:**
[PMID:33301603](https://pubmed.ncbi.nlm.nih.gov/33301603/)
[PMID:32027647](https://pubmed.ncbi.nlm.nih.gov/32027647/)
[PMID:30382198](https://pubmed.ncbi.nlm.nih.gov/30382198/)

**Comment by AvolaAmg** [comment]
@JABelfiore @Caroline-99 @aleixpuigb please review

**Comment by aleixpuigb** [comment]
Thank you for the request,

I think you can add 'capable of' some [acetylcholine secretion, neurotransmission](http://purl.obolibrary.org/obo/GO_0014055). GABA secretion is already inherited.

VIP+/ChAT+ interneuron and VIP/ChAT interneuron are exact synonyms. They are not acronyms of the label, but use the same acronyms. VIP+/ChAT+ cell is ok as related, and could also be broad.
