### ISSUE TITLE
[NTR] mural granulosa cell of ovary

### ISSUE THREAD

**Issue by emquardokus** [obophenotype/cell-ontology#2360]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

It exists in EFO but not in CL; needed for ovary ASCT+B table / HuBMAP female reproductive system

**Preferred term label**
mural granulosa cell 
EFO:0005289

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
from EFO: http://www.ebi.ac.uk/efo/EFO_0005289 EFO:0005289

The mural granulosa cells form during antral folliculogenesis, process in which a single antral cavity is formed, separating two functionally distinct granulosa cell populations. The mural granulosa cells line the wall of the follicle and are critical for steroidogenesis and ovulation.

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
granulosa cell CL:0000501 http://purl.obolibrary.org/obo/CL_0000501

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
ovary http://purl.obolibrary.org/obo/UBERON_0000992 UBERON:0000992

**Your ORCID**
Ellen M. Quardokus: https://orcid.org/0000-0001-7655-4833

**Additional notes or concerns**
**References/Citations**
https://en.wikipedia.org/wiki/Granulosa_cell
Dompe C, Kulus M, Stefańska K, Kranc W, Chermuła B, Bryl R, Pieńkowski W, Nawrocki MJ, Petitte JN, Stelmach B, Mozdziak P, Jeseta M, Pawelczyk L, Jaśkowski JM, Piotrowska-Kempisty H, Spaczyński RZ, Nowicki M, Kempisty B. Human Granulosa Cells-Stemness Properties, Molecular Cross-Talk and Follicular Angiogenesis. Cells. 2021 Jun 5;10(6):1396. doi: 10.3390/cells10061396. PMID: 34198768; PMCID: PMC8229878.

**Comment by aleixpuigb** [comment]
Thank you for submitting this term. 

I am unsure if this cell is a subclass of `granulosa cell` or if it differentiates from them. In CL, `cumulus cell` differentiates from `granulosa cell`, and [Yamochi et al., 2021](https://pubmed.ncbi.nlm.nih.gov/33970370) states that both cumulus and mural granulosa cells differentiate from `granulosa cell`. However, other sources ([Kordus and LaVoie,2021](https://rep.bioscientifica.com/view/journals/rep/153/2/R69.xml), [Eppig et al., 1997](https://pubmed.ncbi.nlm.nih.gov/9433969/) and [wikipedia](https://en.wikipedia.org/wiki/Granulosa_cell)) treat them as subtypes of granulosa cells. We might need to ask SMEs for clarification, since literature has discrepancies.

**Comment by emquardokus** [comment]
@aleixpuigb I think the difficulty is that the ovarian follicle is a developing anatomical structure which undergoes several stages of differentiation depending upon what hormones they are exposed to during the normal state of a woman's hormonal cycle.  During follicle maturation, there are distinct developmental states and most papers refer in general to a granulosa cell layer, but whether 1 layer or 2 layers exist depends on the state of follicle maturation. 
I think it's important to incorporate the follicle stage in the definitions for cumulus and mural granulosa cells and make it distinct from granulosa single layer which is present at earlier follicle stages.
Right now there is primary follicular cell of ovary CL:0002175 with terse definition: A cell within the primary follicle of the ovary. and secondary follicular cell of ovary CL:0002176 with terse definition: A cell of a secondary follicile within the ovary.
Each month in adult female ovary some of the Primordial follicles differentiate into primary follicles--> secondary follicles --> tertiary follicles (also known as Graafian follicles.) So depending on stage, depends on what the granulosa cell layer looks like.
There are 2 types of granulosa cells that can be distinguished in different layers around the oocyte: mural granulosa cell surround antrum and produce estrogen during follicle development stage and progesterone after ovulation,  and cumulus granulosa cell tightly surround oocyte.
In the [Yamochi et al., 2021](https://pubmed.ncbi.nlm.nih.gov/33970370) paper they state that there are pre-granulosa cells in primordial follicles.  Those should also be captured in CL.
In general Uberon did not have ovarian follicle development fully represented. The ASCT+B table for ovary reflected those issues. ovarian follicle UBERON:0001305--> antral follicle (not in uberon) and many other. We should meet to work this through for December 2024 8th HRA release.

**Comment by aleixpuigb** [comment]
> In the [Yamochi et al., 2021](https://pubmed.ncbi.nlm.nih.gov/33970370) paper they state that there are pre-granulosa cells in primordial follicles. Those should also be captured in CL.

**Preferred term label**
pre-granulosa cell

**Synonyms** (add reference(s), please)
pregranulosa cell ([PMID:32759216](https://doi.org/10.1073/pnas.2005570117), [PMID:17639032](https://doi.org/10.1210/en.2007-0590))
ovarian pregranulosa cell ([PMID:32759216](https://doi.org/10.1073/pnas.2005570117))
PG cell([PMID:32759216](https://doi.org/10.1073/pnas.2005570117))

**Definition** 
A supporting cell that differentiates to a granulosa cell. A pre-granulosa cell develops from an early supporting gonadal cell by repressing testis determination, and proliferates to form primordial follicles. 
[PMID:33970370](https://pubmed.ncbi.nlm.nih.gov/33970370)
[PMID:17639032](https://doi.org/10.1210/en.2007-0590)
[PMID:32759216](https://doi.org/10.1073/pnas.2005570117)
[PMID:38178246](https://pubmed.ncbi.nlm.nih.gov/38178246)

**Parent cell type term** 
[supporting cell](http://purl.obolibrary.org/obo/CL_0000630)

**Anatomical structure where the cell type is found** 
'part of' some 'ovary'

**Your ORCID**
https://orcid.org/0000-0001-6677-8489

**Additional notes or concerns**
Two types of pre-granulosa cells: bipotential PG and epithelial PG
Once CL is released, we need to add 'composed primarily of' some 'pre-granulosa cell' to [primordial ovarian follicle](http://purl.obolibrary.org/obo/UBERON_0003981)

**Comment by aleixpuigb** [comment]
@emquardokus are these two term definitions ok? I can add them today. Thank you!

**Preferred term label**  
mural granulosa cell  

**Mapping to other ontologies**
EFO:0005289

**Synonyms** (add reference(s), please)
mural GC [PMID:34198768](https://pubmed.ncbi.nlm.nih.gov/34198768)
MGC [doi:10.1530/REP-16-0500](https://doi.org/10.1530/REP-16-0500)

**Definition**
A follicular cell of ovary that differentiates from a granulosa cell during the secondary follicle stage. Mural granulosa cells line the inner surface of the follicle wall, surrounding the fluid-filled antral cavity. Mural granulosa cells produce oestrogen during the follicular phase in response to follicle-stimulating hormone (FSH), and progesterone after ovulation in response to luteinizing hormone (LH).
[PMID:34198768](https://pubmed.ncbi.nlm.nih.gov/34198768)
[PMID:27815559](https://doi.org/10.1530/rep-16-0500)
[PMID:33970370](https://doi.org/10.1007/s10815-021-02212-2)
[doi:10.1016/B978-0-12-373975-9.00013-6](https://doi.org/10.1016/B978-0-12-373975-9.00013-6 )

**Parent cell type term** 
'directly develops from' some [granulosa cell](http://purl.obolibrary.org/obo/CL_0000501)
[follicular cell of ovary](http://purl.obolibrary.org/obo/CL_0002174)

**Anatomical structure where the cell type is found** (check 
'part of' some ovary [UBERON:0000992](http://purl.obolibrary.org/obo/UBERON_0000992) (inferred)

**Your ORCID**  
Ellen M. Quardokus: [https://orcid.org/0000-0001-7655-4833](https://orcid.org/0000-0001-7655-4833)

**Additional notes or concerns**  
The maturation from granulosa cell toward the mural granulosa cell is the default differentiation process. [PMID:27160446](https://doi.org/10.1016/j.theriogenology.2016.04.019)

**Comment by aleixpuigb** [comment]
Hi @emquardokus, the terms `pre-granulosa cell` (CL:4033066) and 'mural granulosa cell' (CL:4033067) have been added to CL and will be available for the next release.
