### ISSUE TITLE
Obsoleted Go term GO:0000003 reproduction needs to be replaced

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2370]
GO:0000003 `reproduction` is obsoleted and needs to be replaced by `reproductive process` GO:0022414

**Comment by dosumis** [comment]
I don't see it used in any axioms on CL terms.

**Comment by dosumis** [comment]
It looks like it needs to be fixed in Uberon where it is used in 'reproductive organ' and 'reproductive system'.

**Comment by aleixpuigb** [comment]
Yes, I open the ticket in the wrong repo

**Comment by dosumis** [comment]
Looks like Uberon should be using 'sexual reproduction' anyway?
