### ISSUE TITLE
respiratory epithelial cell is defined as an endo-epithelial cell but 'epithelial cell' is used to define many subclasses.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2379]
The classification appears to be correct https://www.perplexity.ai/search/are-cells-of-Co5soTj9SUyCk_THNU4IkQ 

But the mix of genus => a confusing and complex hierarchy.

More research needed to decide on solution.  Should we also use endoepithelial cell in these cases?  This will remove the endothelial cells from the hierarchy but is more burden on future Editors - who will need to follow this pattern.

Alternatively we could keep this assertion on 'respiratory epithelial cell' and use that as the genus term.  Here we may need to be careful because the current partonomy does not include the nasal respiratory epithelium.

**Comment by cmungall** [comment]
simple solution: obsolete endo-eithli{al cell, um}. Unsustainable. Not used by biologists that open? people can always do a separate query over development
