### ISSUE TITLE
[Typo] Defs of CL:0011025 and CL:0011028 are mistakenly entered as exact synonyms

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#2391]
**CL term**
CL:0011025 and CL:0011028

**Description of typo, bug or error**
![Screenshot 2024-06-07 at 11 57 06](https://github.com/obophenotype/cell-ontology/assets/61156599/f909b48d-f879-4d1c-878f-b62bc653c494)
![Screenshot 2024-06-07 at 11 57 38](https://github.com/obophenotype/cell-ontology/assets/61156599/a2114556-9eb0-470f-afcd-3ad86d3b9c2d)

Thanks!
Paola

**Comment by anitacaron** [comment]
Thank you, @paola-scibite, for opening this issue. This is now fixed and will be available in the next CL release.
