### ISSUE TITLE
Revise Epithelial Cell of Proximal Tubule and Subclasses

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2395]
This ticket is in progress 

 The proximal tubule cell class and subclasses need modifications:

-  Import Uberon terms "proximal convoluted tubule segment 1" and "proximal convoluted tubule segment 2" into CL.
- Link these terms to CL terms "epithelial cell of proximal tubule segment 1" and "epithelial cell of proximal tubule segment 2" 
-  Add missing logical definitions.
-  Update textual definitions to include primary functions for "epithelial cell of proximal tubule segment 1"and "epithelial cell of proximal tubule segment 2" and "epithelial cell of proximal tubule segment 3" .
-  Link to Gene Ontology (GO) terms where appropriate.

**Comment by emquardokus** [comment]
@Caroline-99

**Comment by Caroline-99** [comment]
Thank you for providing the spreadsheet
