### ISSUE TITLE
Alveolar macrophage - location

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2404]
Alveolar macrophages are located in the lumen of the alveolus.  They should have a part_of relationship to this 
- term needs adding to Uberon?

**Comment by Caroline-99** [comment]
@dosumis I agree. I will work on adding the term "lumen of alveolus" to Uberon. For now, we can use ('part_of' some 'alveolus of lung')?

**Comment by Caroline-99** [comment]
@dosumis The term "lumen of pulmonary alveolus" has been added to Uberon. The alveolar macrophage in CL will be linked to this term after the next Uberon release.

**Comment by dosumis** [comment]
Dependent on Uberon release for [NTR: lumen of alveolus obophenotype/uberon#3302](https://github.com/obophenotype/uberon/issues/3302)
