### ISSUE TITLE
`false` deprecation value on `CL:0000662`

### ISSUE THREAD

**Issue by turbomam** [obophenotype/cell-ontology#2408]
**CL term**
`CL:0000662`

**Description of typo, bug or error**
Uses the `owl:deprecated` value  `"false"^^xsd:boolean`, which doesn't seem to violate any specs I can find, but 99.9% of the deprecations in Ubergraph have values of `"false"^^xsd:boolean`. I don't understand what the utility of a false deprecation is.

**Comment by anitacaron** [comment]
Hi @turbomam, you're right! Thank you for reporting this issue. I fixed it, and the class won't have this annotation in the next CL release.
