### ISSUE TITLE
[Class hierarchy] BEST4+ intestinal epithelial cell, human

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2410]
**CL term**

BEST4+ intestinal epithelial cell, human

**Suggested revision of class hierarchy**

This should at least be under epithelial cell - not sure why this was neglected before: See https://github.com/obophenotype/cell-ontology/issues/1695

But I believe enterocyte is more appropriate:

See https://doi.org/10.1371/journal.pone.0079693

**Comment by dosumis** [comment]
Also - add two distinct subclasses:  

small intestine BEST4 enterocyte
small intestine BEST4 colonocyte

Classification of both can be automated via partonomy.

**Comment by dosumis** [comment]
- BEST4 enterocyte: EC: enterocyte and expresses some BEST4
- small intestine BEST4 enterocyte: EC: enterocyte and expresses some BEST4 and part_of some small intestine
- BEST4 colonocyte:  EC: enterocyte and expresses some BEST4 and part_of some colon

**Comment by JABelfiore** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
#gogoeditdiff
