### ISSUE TITLE
[Class hierarchy] 'vasa recta cell' is a capillary endothelial cell and a vein endothelial cell at the same time

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2425]
**CL term**
[vasa recta cell](http://purl.obolibrary.org/obo/CL_1001036)

**Suggested revision of class hierarchy**
- [ ] This needs changes in Uberon: [#2914](https://github.com/obophenotype/uberon/issues/2914)
- [ ] Replace [kidney capillary endothelial cell](http://purl.obolibrary.org/obo/CL_1000892) for [microvascular endothelial cell](http://purl.obolibrary.org/obo/CL_2000008)

**Comment by emquardokus** [comment]
@aleixpuigb  please see related uberon ticket: https://github.com/obophenotype/uberon/issues/2914
