### ISSUE TITLE
[Class hierarchy] CGE and MGE cortical interneurons have no children

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2428]
This may have been broken.  We should add subClassOf: develops_from some MGE/CGE axioms to all relevant cortical interneurons to => automated classification. 
```[tasklist]
### Tasks
- [ ] Declare the medial ganglionic GABAergic interneuron term obsolete CL:4023069
- [ ] Revise the definition of mge derived interneurons t-types and add adjust their hierarchy
```

**Comment by AvolaAmg** [comment]
The Caudal Ganglionic Eminence interneurons seem to be fine. It has children term.
![image](https://github.com/user-attachments/assets/9ac46056-51bf-4791-be0b-85c9d9bc0106)

The Medial Ganglionic Eminence doesn't have children however to fix this I have to first declare the medial ganglionic GABAergic interneuron term obsolete [CL:4023069](http://purl.obolibrary.org/obo/CL_4023069)

Then I will work on cleaning up the hierarchy of the Medial Ganglionic evidence cell types and add their t-type definition
