### ISSUE TITLE
[NTR] Astrocyte-restricted precursor

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#2435]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl
--> not available

**Preferred term label**
astrocyte-restricted precursor

**Synonyms** (add reference(s), please)
ARP

https://singlecell.broadinstitute.org/single_cell/study/SCP263/aging-mouse-brain#study-summary

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
tentative definition: A neural precursor cell that undergoes a gliogenic switch to generate astrocytes.
https://www.frontiersin.org/journals/cell-and-developmental-biology/articles/10.3389/fcell.2023.1063843/full

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
is_a: CL:0000123 ! neuron associated cell (sensu Vertebrata)
is_a: CL:0000030 ! glioblast ??
is_a: CL:0011026 ! progenitor cell

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
UBERON:0000955 ! brain

**Your ORCID**
https://orcid.org/0000-0003-3308-6245

**Additional notes or concerns**
It exists CL:4040000 glial restricted tripotential precursor cell but the definition is restricted to oligodendrocytes and type-1 and type-2 astrocytes, while there are 3 astrocyte sub-types, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7122459/

**Comment by AvolaAmg** [comment]
@Caroline-99 please review the definition of this cell type below:

**term label:**
astrocyte-restricted precursor

**definition:**
A progenitor cell of the central nervous system that differentiates exclusively onto astrocytes. This progenitor cell expresses CD44 and S100 calcium binding protein B.
**database_cross_reference:**
PMID: [33052610](https://pubmed.ncbi.nlm.nih.gov/33052610)
PMID: **15531362**

**comment:**
*In vitro* this progenitor cell can differentiate from glial-restricted precursor cells. 
PMID: [33052610](https://pubmed.ncbi.nlm.nih.gov/33052610)

**has related synonym** 
ARP
PMID: [33052610](https://pubmed.ncbi.nlm.nih.gov/33052610)

**has related synonym**
APCs
PMID: [33052610](https://pubmed.ncbi.nlm.nih.gov/33052610)

**has related synonym** 
astrocyte precursor cells
PMID: [33052610](https://pubmed.ncbi.nlm.nih.gov/33052610)

**Logical definition**
[progenitor cell](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0011026?lang=en)
([neuron associated cell (sensu Vertebrata)](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000123?lang=en)and[part of](https://www.ebi.ac.uk/ols4/ontologies/cl/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050?lang=en) some[central nervous system](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001017?lang=en)[UBERON](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001017))
[develops from](https://www.ebi.ac.uk/ols4/ontologies/cl/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002202?lang=en)[RO](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002202)some[glioblast (sensu Vertebrata)](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000339?lang=en)
expresses [CD44](http://purl.obolibrary.org/obo/PR_000001307) and [S100 calcium binding protein B]

**Comment by Caroline-99** [comment]
Everything looks good to me. I would suggest mentioning in the textual definition that they are neuron associated cells if it is in the logical definition.

**Comment by AvolaAmg** [comment]
Thank you for your review. So technically they are both progenitor cells and neuron associated cells. i want to add both in the logical definition. As the parent term is progenitor cell.
If progenitor cell is in the logical definition would it be okay to have it in the description? (It is biologically more informative)

**Comment by Caroline-99** [comment]
Yeah it would be appropriate to include "progenitor cell" in both the logical definition and the textual description.

**Comment by AvolaAmg** [comment]
Thank you Caroline! I will do!
