### ISSUE TITLE
Atlas of the Aging Mouse Brain, 'mature neuron' and 'immature neuron' needed?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#2436]
Hello CL Team,

Atlas of the Aging Mouse Brain brings up some new concepts/terms that are currently missing in CL https://singlecell.broadinstitute.org/single_cell/study/SCP263/aging-mouse-brain#study-summary

adult neurogenesis with concept of 'mature' and 'immature' neurons sounds emerging..?

https://www.pennmedicine.org/news/news-releases/2022/july/discovery-of-molecular-signatures-of-immature-neurons-in-the-human-brain

Thank you for your help here!

Anne

**Comment by AvolaAmg** [comment]
Hi Anne, 

Thank you for your ticket, I will get back to you as soon as possible to incorporate these new concepts in CL.

Alida

**Comment by AvolaAmg** [comment]
@JABelfiore  please review:

Given the following literature research (see list of papers below), the concept of immature neurons should be included in the ontology as a cell classification as these cells remain in this state for a prolonged time in the tissue and therefore can be identified.
PMID: [31096632](https://pubmed.ncbi.nlm.nih.gov/31096632)
PMID: [37833544](https://pubmed.ncbi.nlm.nih.gov/37833544/)
PMID: [32116519](https://pubmed.ncbi.nlm.nih.gov/32116519/)
https://molecularbrain.biomedcentral.com/articles/10.1186/s13041-019-0522-8
https://pubmed.ncbi.nlm.nih.gov/21609825/



The following NTRs will be added: 

**cell label:** immature neuron
-

**cell definition:**
A neuron in a central nervous system that is not committed to a differentiated fate, that it is not been newly derived from neurogenesis, and that does not integrate within any circuit.

**database_cross_reference:**
- PMID: **37833544**
- PMID: **32116519**
- PMID: **31096632**

**comments:**
It is hypothesised that immature neurons can be utilised as a neurogenic reserve and that they can be involved in circuit plasticity. 

**database_cross_reference:**
PMID: [32116519](https://pubmed.ncbi.nlm.nih.gov/32116519)

**has related synonym:**
IN
- PMID: **32116519**

**has related synonym:**
nng-IN
PMID: **31096632**

**parent term:**
[central nervous system neuron](http://purl.obolibrary.org/obo/CL_2000029)
**uberon term:**
[central nervous system](http://purl.obolibrary.org/obo/UBERON_0001017)



**cell label:** cortical immature neuron
-

**definition:**
An immature neuron of a cerebral cortex.
**database_cross_reference:**
- PMID: **37833544**

**has related synonym:**
cIN
**database_cross_reference:**
- PMID: **37833544** 

**parent term:** immature neuron
**uberon term:** [cerebral cortex](http://purl.obolibrary.org/obo/UBERON_0000956)

**Comment by scheuerm** [comment]
I would not add a new term just because of its anatomic location, unless there is some evidence that it has a different molecular or functional property in this location.

**Comment by AvolaAmg** [comment]
Dear @scheuerm, thank you for your comment, I will have a look regarding the cortical immature neuron, but will keep the _immature neuron_ NTR
