### ISSUE TITLE
[NTR] neuronal-restricted precursor

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#2437]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl
--> not available

**Preferred term label**
neuronal-restricted precursor

**Synonyms** (add reference(s), please)
NRP

https://singlecell.broadinstitute.org/single_cell/study/SCP263/aging-mouse-brain#study-summary

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
https://link.springer.com/chapter/10.1007/978-1-59259-107-7_5
'populations of restricted progenitors isolated from the embryonic spinal cord and the neonatal forebrain anterior subventricular
zone (SVZa), which are committed to the production of neurons and are therefore called neuronal restricted progenitors (NRPs).

but also
https://www.frontiersin.org/journals/neuroanatomy/articles/10.3389/fnana.2018.00104/full
--> 'More recently, it has been shown that the adult human hypothalamus contains four distinct populations of cells that express neuronal **progenitor** markers, each of these cell types, with the exception of tanycytes, are human-specific ([Pellegrino et al., 2018](https://www.frontiersin.org/journals/neuroanatomy/articles/10.3389/fnana.2018.00104/full#B64)).

Tricky to define 'neuronal-restricted precursor', in the reference cited above (Pellegrino et al., 2018), we see:
'neural stem/progenitor cell (NPC)'

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
is_a: CL:0011026 ! progenitor cell

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
UBERON:0000955 ! brain

**Your ORCID**
https://orcid.org/0000-0003-3308-6245

**Additional notes or concerns**
This issue is related to the 'Atlas of the Aging Mouse Brain'
https://singlecell.broadinstitute.org/single_cell/study/SCP263/aging-mouse-brain#study-summary
that reports cell types, some of them not (yet?) in CL/UBERON

**Comment by AvolaAmg** [comment]
Thank you for your ticket Anne, I will review it shortly and proceed to add the term. 

Best, 
Alida

**Comment by AvolaAmg** [comment]
@Caroline-99 please review definition. 

**term label:**  
neuronal-restricted precursor

**definition:**  
A progenitor cell of the central nervous system that differentiates exclusively onto neurons. 
This progenitor cell is found in a hippocampus subventricular zone, developing cortex and spinal cord.
**database_cross_reference:**
- PMID: **10467245**
  

**comments:**
*in vitro* cultures of mice neural tubes, Neural-restricted precursors are derived by multipotent neuroepithelial cells to give rise to neurons suggesting a linear relationship between multipotent and neural-restricted differentiation (Mayer-Proschel et al., 1997). In the spinal cord of rats, neural-restricted precursor cells give rise cholinergic, GABAergic, glutametergic neurons (Cao and Howard et al., 2002)
https://www.sciencedirect.com/science/article/pii/S0014488602979811
**database_cross_reference:**  
- PMID: **9354325**
- PMID: **12429182**


**has related synonym**  
NRP  
**database_cross_reference:**
PMID: **12429182**


**Logical definition**  
[progenitor cell](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0011026?lang=en)  
([neuron associated cell (sensu Vertebrata)](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCL_0000123?lang=en)and[part of](https://www.ebi.ac.uk/ols4/ontologies/cl/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050?lang=en) some[central nervous system](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001017?lang=en)[UBERON](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001017))  



**parent term:**  
[progenitor cell](http://purl.obolibrary.org/obo/CL_0011026)  
[neuron associated cell](sensu vertebrata)[http://purl.obolibrary.org/obo/CL_0000123]
