### ISSUE TITLE
[Logical def] epithelial cell of uterus logical and textual definition 

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2441]
**Background** 

The parent of epithelial cell of uterus in CL is "endo-epithelial cell" but the epithelial cells in the uterus are meso-derm derived.

PMID: [21698266](https://pubmed.ncbi.nlm.nih.gov/21698266): "During embryogenesis, the mesoderm emerges from the primitive streak and gives rise to coelomic epithelium. The Müllerian Duct (MD) arises from invagination of coelomic epithelium during fetal development. Subsequently, the MD gives rise to the human female reproductive tract (FRT) that further differentiates to form the oviduct, uterus and upper vaginal canal." 

PMID: [11331626](https://pubmed.ncbi.nlm.nih.gov/11331626/): "The endometrium is composed of mesodermal-derived glandular and luminal epithelia that are supported by a basement membrane and connective tissue stroma." - This indicates that the epithelial cells of the endometrium, which line the uterus, are derived from the mesoderm.

 PMID: [16960017](https://pubmed.ncbi.nlm.nih.gov/16960017/): "The embryonic female reproductive tract has its origins in the intermediate mesoderm, which begins to form soon after gastrulation. As this embryonic tissue proliferates, it is thought that some cells undergo mesenchymal to epithelial transition to give rise to the coelomic epithelium that later invaginates to form the paramesonephric or Müllerian ducts (Kobayashi and Behringer, 2003). "

**CL term**
epithelial cell of uterus (CL:0002149)

**Suggested revision of logical definition**
'meso-epithelial cell' and ('part of' some uterus) 

**instead of**  
'endo-epithelial cell' and ('part of' some uterus)

**Comment by aleixpuigb** [comment]
I agree that epithelial cells of the uterus have a mesodermal origin.
EquivalenTo would be: `'epithelial cell' and ('part of' some uterus)`.
New axiom `'develops from' some 'mesodermal cell'`.
