### ISSUE TITLE
[NTR] CGRP-expressing neuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2445]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**

**Additional notes or concerns**

**Comment by AvolaAmg** [comment]
A draft for now
-

**definition:**
An interneuron neuron characterized by the expression of calcitonin gene-related peptide (CGRP), a 37-amino acid neuropeptide. This neuron type is involved in nociception and pain modulation by facilitating the transmission of nociceptive signals from peripheral sensory nerve endings to central nervous system structures. This neuron type is found in the dorsal root ganglia (DRG) and trigeminal ganglion, and the spinal cord dorsal horn.

**references:**
PMID: 34061020

**extended description:**
Pain and disorders

**references**


**synonyms:**
CGRP-positive neuron


Calcitonin gene-related peptide neuron


CGRP-expressing interneurons
PMID: 34061020

**Comment by dosumis** [comment]
Check WMB neuropeptides to see if evidence for expression in more neuron types (There may be something similar for WHB).  I think worth doing for all neurons defined by NPs.

**Comment by AvolaAmg** [comment]
From the ABC atlas WMB
![image](https://github.com/user-attachments/assets/5d4785b5-a23a-4762-a7ce-37b494a8daea)

From the ABC atlas Siletti data
![image](https://github.com/user-attachments/assets/c87ec3ec-7c9d-46ae-9b06-962e383156a0)
![image](https://github.com/user-attachments/assets/50541166-b374-4571-a510-19e930dad15d)
![image](https://github.com/user-attachments/assets/b7ce8de0-fba3-4f8b-80c5-17cc1dac84fb)
![image](https://github.com/user-attachments/assets/a8cb90ea-eec6-4dee-92bd-1d9989434487)

In the Siletti data from CxG
![image](https://github.com/user-attachments/assets/e38799ec-b6a4-4b7b-95ef-108940e47c5f)
![image](https://github.com/user-attachments/assets/8eb5b35a-cb40-4334-aa1b-8afa48701aec)

CGPR expressing neurons are found in the [spinal cord](http://purl.obolibrary.org/obo/UBERON_0002240), [DRG](http://purl.obolibrary.org/obo/UBERON_0000044), [trigeminal ganglion](http://purl.obolibrary.org/obo/UBERON_0001675). These central nervous system structures are not within the brain, so this might be why this gene is not detectable in neurons from the encephalon.
