### ISSUE TITLE
[Obsolete] glandular cell of endometrium

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2468]
**CL term**
glandular cell of endometrium
http://purl.obolibrary.org/obo/CL_0002656

**Suggested replacement**
epithelial cell of endometrial gland 
http://purl.obolibrary.org/obo/CL_0009084

**Reason for deprecation**
Both terms seems to refer to the same cell type and `"epithelial cell of endometrial gland"` has an exact synonym `"endometrial glandular epithelial cell"` which directly overlaps with the definition of` "glandular cell of endometrium"` .

**Comment by dosumis** [comment]
Are you sure these are the same.  Does glandular imply secretion?  Epithelial cells of glands often include duct cells that are not secretory.

**Comment by Caroline-99** [comment]
@dosumis @aleixpuigb Yeah glandular imply secretion in "glandular cell of endometrium". 
This is the current classification : 
![image](https://github.com/user-attachments/assets/1efb0655-2404-4e60-afc4-05df15b2f2bb)

Problems with the current classification: 

1. The term "glandular cell of endometrium" is defined as a "glandular epithelial cell," indicating it is specifically a secretory cell within the endometrial gland.
2. The term "epithelial cell of endometrial gland" includes an exact synonym "endometrial glandular epithelial cell," referring to the same cell type.
3. Currently, “epithelial cell of endometrial gland" does not have subclasses, and there is no CL term for duct cells in the endometrial gland.

**First option**
At the Reproductive System Jamboree, it was suggested to merge the two terms into "glandular cell of endometrium" and add a new term "luminal cell of endometrium" to refer to non-ciliated luminal cells. The classification would look like:
![image](https://github.com/user-attachments/assets/c98383c7-e5d5-4514-ba33-37d002981ee4)

**Second option**
If we do want to keep both terms, I would suggest refining the definitions and classification to show that these two terms are different.

**Suggested Replacement:**
1. Epithelial Cell of Endometrial Gland (CL_0009084):

Proposed Definition: Any epithelial cell that lines the endometrial glands. This term encompasses both secretory and non-secretory cell types, including secretory cells, ciliated cells, and (clear cells?).
Actions:

- Remove the exact synonym "endometrial glandular epithelial cell" to avoid overlap with "glandular cell of endometrium."
- Add "endometrial ciliated epithelial cell" and "glandular cell of endometrium" as subclasses of "epithelial cell of endometrial gland."

2. Glandular Cell of Endometrium (CL_0002656):

Proposed Definition: An epithelial cell of the endometrial gland that is primarily involved in secretion. These cells are most active during the secretory phase of the menstrual cycle and are responsible for producing substances necessary for endometrial function.
Actions:
- this term will be classified under "Epithelial Cell of Endometrial Gland "
