### ISSUE TITLE
V2, V2a, V2b, V1

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#247]
V2 cells
Cells that develop in  the V2 progenitor domain in the ventral spinal cord.  V2 cells are neuron progenitors.  
develop into:V2a, V2b cells
V1 cells
Cells that develop in  the V1 progenitor domain in the ventral spinal cord.  V1 cells are neuron progenitors.
develop into:V1 interneurons, V1 neurons   (may be species specific)  

V2a cell  
Cell that develop from the V2 cells in the ventral spinal cord.  V2a cells become excitatory neurons.
develops into: V2a interneuron (may be species specific)
V2b cell
Cell that develop from the V2 cells  in the ventral spinal cord. V2b cells become inhibitory neurons.
develops into: V2b interneuron  (may be species specific)

Discussion of if/how we want to define the interneurons and cell types needed.  Literature differentiates different cell types by genes expressed early in development (some morphology too but may not transfer between species).  
We could stop at the V2a and V2b cell level and then let each mod define species specific cell types as leaf nodes in their anatomy ontology or put the more granular cell types in the CL for groups that don't have species specific ontologies. 

Original comment by: cerivs

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia that sounds good to me! Let's close.

**Comment by cerivs** [comment]
We can just make them in the ZFA because we do still need the types.
