### ISSUE TITLE
Revise glomerular and peritubular capillary endothelial cell classification and defs 

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2474]
**glomerular endothelial cell and subsclasses** 

- [x] Link [glomerular endothelial cell](http://purl.obolibrary.org/obo/CL_0002188) to GO term glomerular endothelium fenestra (GO:0036053)
- [x] Add a textual defs for [glomerular capillary endothelial cell](http://purl.obolibrary.org/obo/CL_1001005) term 

**[peritubular capillary endothelial cell](http://purl.obolibrary.org/obo/CL_1001033)** 

- [x] Add SubclassOf **'has characteristic' some fenestrated'**
- [x] Add a textual definition

**Comment by dosumis** [comment]
Should be able to infer classification under fenestrated epithelial cell
