### ISSUE TITLE
“placental villus capillary endothelial cell” violates taxon constraints

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#2490]
[placental villus capillary endothelial cell](http://purl.obolibrary.org/obo/CL_2000062) (CL:2000062), textually defined as “any capillary endothelial cell that is part of a placenta”, is logically defined as [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005) (UBERON:0010005). It is also explicitly marked as being [present in taxon](http://purl.obolibrary.org/obo/RO_0002175) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606).

But the Uberon term for “placental labyrinth villous” (or rather, the [placenta labyrinth](http://purl.obolibrary.org/obo/UBERON_0003946) of which it is a part) is specifically marked as being [never in taxon](http://purl.obolibrary.org/obo/RO_0002161) some [Homo sapiens](http://purl.obolibrary.org/obo/NCBITaxon_9606) – the term is intended for the labyrinthine type of placenta found e.g. in rodents but _not_ in human.

If [placental villus capillary endothelial cell](http://purl.obolibrary.org/obo/CL_2000062) is intended to be applicable to many species regardless of their type of placenta (as the textual definition suggests), then its logical definition should probably make it a [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [placenta](http://purl.obolibrary.org/obo/UBERON_0001987) more generally, rather than some (taxon-restricted) [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005). (Alternatively, maybe a new generic term could be requested in Uberon, that would cover blood exchange zones of any placenta regardless of their type.)

If the term is intended to refer specifically to human cells, or at least to cells that only exists in labyrinthine-type placentas, then it should probably be a [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [chorionic villus](http://purl.obolibrary.org/obo/UBERON_0007106) (and the textual definition should be amended accordingly).

**Comment by gouttegd** [comment]
(Issue found using the Uberon check for taxon constraint violations, since CL does not have such a check internally – it should have, because it won’t be sustainable to rely on Uberon to detect such violations long after they have been introduced in the ontology.)

**Comment by aleixpuigb** [comment]
> If [placental villus capillary endothelial cell](http://purl.obolibrary.org/obo/CL_2000062) is intended to be applicable to many species regardless of their type of placenta (as the textual definition suggests), then its logical definition should probably make it a [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [placenta](http://purl.obolibrary.org/obo/UBERON_0001987) more generally, rather than some (taxon-restricted) [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005). (Alternatively, maybe a new generic term could be requested in Uberon, that would cover blood exchange zones of any placenta regardless of their type.)

I agree, as it is now, this term should not be used for a specific organism. I agree with the approach to remove the taxon constraint and substitute part_of [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005) for part_of [placenta](http://purl.obolibrary.org/obo/UBERON_0001987). If a more specific structure needs this term, either can create a new one, or can use has_part [placental villus capillary endothelial cell](http://purl.obolibrary.org/obo/CL_2000062) to the specific capillary.

**Comment by gouttegd** [comment]
> this term should not be used for a specific organism

To clarify: the `present_in_taxon 'Homo sapiens'` annotation does not mean that the term is human-specific. It just means that it exists in human, without asserting anything about its existence in other species. But since the `placental labyrinth` is explicitly said not to exist in human (`never_in_taxon 'Homo sapiens'`), that is enough to violate the taxon constraints.

> I agree with the approach to remove the taxon constraint and substitute part_of [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005) for part_of [placenta](http://purl.obolibrary.org/obo/UBERON_0001987).

If we do the latter part (substituting [placental labyrinth villous](http://purl.obolibrary.org/obo/UBERON_0010005) for part_of [placenta](http://purl.obolibrary.org/obo/UBERON_0001987)), then there would be no need to remove the `present_in_taxon`, which would still be correct and not contradict any other assertion. :)

**Comment by aleixpuigb** [comment]
> To clarify: the present_in_taxon 'Homo sapiens' annotation does not mean that the term is human-specific.

Yes, sorry, I got confused with only_in_taxon.
