### ISSUE TITLE
participates_in --> capable_of

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2521]
<img width="807" alt="image" src="https://github.com/user-attachments/assets/ef3364ff-98f8-4147-b980-66800e6beb66">

See https://obophenotype.github.io/cell-ontology/relations_guide/#recording-function

(although in this case it feels like it would be more accurate to have a relation 'participated_in' as not clear that mature syncytia always maintain a potential/capability of participating in fusion).

**Comment by Caroline-99** [comment]
@dosumis https://www.perplexity.ai/search/does-mature-syncytia-aways-mai-0vH91KqGTUG5NdR7nTUxIA

It seems that 'participate in' relation is more accurate. if so, please confirm and I will close the ticket?

**Comment by dosumis** [comment]
Having thought about it some more, it makes more sense to use output_of http://purl.obolibrary.org/obo/RO_0002353
