### ISSUE TITLE
Adding a dbxref with comment as AP does not fail QC

### ISSUE THREAD

**Issue by aleixpuigb** [obophenotype/cell-ontology#2523]
IIRC, in the past when an editor submitted a PR with the AP comment instead of database_cross_reference, the QC failed. However I have reviewed recently two PRs that passed the QC but had this bug. Of course it is the job of the creator of the PR and the reviewer to notice these things, but it might carry problems in the future. Can it be captured by the QC? Thank you!

**Comment by anitacaron** [comment]
The QC is only for when the value is PMID. I could add another QC to fail if any other annotation is used in a definition.

I searched for other annotations that are heavily used in the definition. I only found some misuse cases that need to be fixed.

| cls        | annotation        | xref                                         |
|------------|-------------------|----------------------------------------------|
| CL:0008040 | rdfs:comment      | "GOC:tfm"                                    |
| CL:0002576 | rdfs:comment      | https://orcid.org/0000-0001-7655-4833        |
| CL:4030007 | terms:contributor | https://orcid.org/0000-0002-0819-0473        |
| CL:0002301 | terms:contributor | https://orcid.org/0000-0002-0819-0473        |
| CL:4030004 | terms:contributor | https://orcid.org/0000-0002-0819-0473        |
| CL:4030012 | terms:contributor | https://orcid.org/0000-0003-2804-127X        |
| CL:0002523 | terms:contributor | https://orcid.org/0000-0002-2244-7917        |
| CL:4030028 | IAO:0000115       | "https://doi.org/10.1016/j.cell.2020.08.013" |
| CL:0000351 | rdfs:comment      | "doi:10.1007/978-3-030-84725-8"              |
| CL:4030008 | terms:contributor | https://orcid.org/0000-0002-2244-7917        |
| CL:4030006 | terms:contributor | https://orcid.org/0000-0002-0819-0473        |
| CL:4030015 | terms:contributor | https://orcid.org/0000-0003-2804-127X        |
