### ISSUE TITLE
[NTR-cxg] Add children to CL:1001596 (salivary gland glandular cell)

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#2524]
Hello, CL team,
I currently working with authors of https://doi.org/10.1177/00220345221147908 to find appropriate CL terms for salivary gland cells. Here is a diagram of the standard gland structure: https://www.nature.com/articles/s41536-020-00115-x/figures/1. 
The parent term "CL:1001596" has many cell types listed in its definition:

> Example: Serous cells, mucous cells, cuboidal epithelial cells of the intercalated ducts, simple cuboidal epithelium of the striated ducts, epithelial cells of excretory ducts.

**Preferred term label**
It's unclear if the serous and mucous cells should be salivary gland specific. But contributor mentioned that the following should have their own specific terms:
- intercalated cell of salivary gland
- striated cell of salivary gland

**Synonym(s)** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

**Parent cell type term**
CL:1001596 ([salivary gland glandular cell](http://purl.obolibrary.org/obo/CL_1001596))

**Anatomical structure where the cell type is found**
UBERON:0001044 ([saliva-secreting gland](http://purl.obolibrary.org/obo/UBERON_0001044)) or it's children

**Your ORCID**
https://orcid.org/my-orcid?orcid=0000-0003-4389-9821

**Additional notes or concerns** If there are markers that uniquely identify the cell type in a particular species, they can be added here.

**Comment by Caroline-99** [comment]
Thank you Jennifer for your ticket. I will review it and proceed to add the terms.
