### ISSUE TITLE
Remove "in blood" from textual definition of myeloid dendritic cell CD1c-positive

### ISSUE THREAD

**Issue by scheuerm** [obophenotype/cell-ontology#2538]
The current definition of myeloid dendritic cell CD1c-positive (CL:0002399) is “A myeloid dendritic cell found in the blood that is CD1c-positive.”  If we remove "found in the blood" the term can be use for tissue resident dendritic cells as well.

New definition would be “A myeloid dendritic cell that is CD1c-positive.”

**Comment by addiehl** [comment]
+1

**Comment by aleixpuigb** [comment]
Thank you Richard, I have done the changes and they will part of the next CL release.
