### ISSUE TITLE
Some taxon constraints in CL are too tight for ZFA

### ISSUE THREAD

**Issue by gouttegd** [obophenotype/cell-ontology#2542]
Two CL terms have taxon constraints that are too tight and cause issues when ZFA is merged with Uberon and CL.

# 'B cell, CD-19 positive'

'[B cell, CD-19 positive](http://purl.obolibrary.org/obo/CL_0001201)' is said to be mammal-specific ([in_taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)). It’s actually part of the logical definition.

This makes, in turn, most of the B cells in CL (e.g. '[mature B cell](http://purl.obolibrary.org/obo/CL_0000785)', '[immature B cell](http://purl.obolibrary.org/obo/CL_0000816)', '[transitional stage B cell](http://purl.obolibrary.org/obo/CL_0000818), etc.) mammal-specific.

But B cells (including mature and immature B cells, transitional stage B cell, etc.) exist beyond mammals, e.g. in zebrafish. Most ZFA terms for B cells are unsatisfiable in Uberon+CL+ZFA because of the restriction of '[B cell, CD-19 positive](http://purl.obolibrary.org/obo/CL_0001201)' to mammals.

# 'rod bipolar cell'

'[rod bipolar cell](http://purl.obolibrary.org/obo/CL_0000751) is said to be mammal-specific ([in_taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)).

But those cells apparently also exist in zebrafish, and the [ZFA term](http://purl.obolibrary.org/obo/ZFA_0009321) for them is unsatisfiable in Uberon+CL+ZFA because of that restriction to mammals.

**Comment by addiehl** [comment]
We should probably drop the ([in_taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Mammalia](http://purl.obolibrary.org/obo/NCBITaxon_40674)) for the B cell, CD19-positive.  According to [this article](https://www.frontiersin.org/journals/cell-and-developmental-biology/articles/10.3389/fcell.2021.660969/full), CD19 is found on B cells in Zebrafish, and is thus most like a marker of B cells in most or all vertebrates.

Google Gemini offers up additional articles in support of CD19 on B cells in zebrafish.  I have not had time to verify this information yet:

Scientific Articles Identifying CD19 as a B Cell Marker in Zebrafish

Here are a few scientific articles that have used CD19 as a marker for B cells in zebrafish:

1. Page et al., 2013: This study characterized the development and behavior of IgM+ B cells in zebrafish. They utilized three fluorescent transgenic lines, including one expressing CD19, to define the existence of pro-B, immature/mature, and mature B cells in the kidney marrow.   

Title: "Zebrafish B cells exhibit a distinct developmental pattern and are highly plastic."
Journal: Blood
2. Lu et al., 2016: This research explored the role of B cells in zebrafish tumor immunity. They found that CD19+ B cells can express the death ligand FasL to directly induce cytotoxicity when stimulated by IL-17A.   

Title: "CD19+ B cells contribute to anti-tumor immunity in zebrafish through FasL-mediated cytotoxicity."   
Journal: Frontiers in Immunology
3. Hu et al., 2010: This study identified IgZ as a novel B cell marker in zebrafish. They also confirmed the expression of CD19 on B cells in different tissues.   

Title: "Identification of IgZ as a novel B cell marker and its expression in zebrafish immune tissues."
Journal: Developmental and Comparative Immunology
4. Tao et al., 2017: This research investigated the regulatory role of B cells in zebrafish inflammation. They found that CD19+ B cells can be negatively regulated by IL-10.

Title: "IL-10-producing B cells regulate inflammation in zebrafish."
Journal: Journal of Immunology
These articles provide valuable insights into the use of CD19 as a B cell marker in zebrafish and its role in various immune processes.

**Comment by dosumis** [comment]
<img width="710" alt="image" src="https://github.com/user-attachments/assets/351168fc-ce97-4def-ab03-c467e1cf1ba3">

Looks like recent work supports rod-bipolar pathway as more ancient than previously thought

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/098229ec-1f05-416f-9438-bfaff4f43e5e">

So I think OK to relax taxon constraints on this to.
