### ISSUE TITLE
[NTR] crypt support fibroblast (+ subclasses)

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2558]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**

crypt support fibroblast

**Synonyms** (add reference(s), please)

crypt-associated fibroblast

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

A fibroblast located in the submucosa of the crypt of Lieberkuhn.  These fibroblasts release cell-cell signaling factors that play a role in controlling the stem cell niche and regulating the balance between stem cell maintenance and differentitation.

https://doi.org/10.1371/journal.pbio.3001032

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

fibroblast

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

* intestinal submucosa http://purl.obolibrary.org/obo/UBERON_0009566
* crypt of Lieberkuhn http://purl.obolibrary.org/obo/UBERON_0001983

**Your ORCID**

**Additional notes or concerns**

---

**Preferred term label**

crypt-bottom Fibroblast

**Synonyms** (add reference(s), please)

CBF

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

A crypt support fibroblast that is located at the base of the crypt of Lieberkuhn, near the intestinal stem cells. They are crucial for maintaining the stem cell niche by secreting a variety of cell-cell signals including  Wnt ligands BMP, and Gremlin 1 (Grem1).

https://doi.org/10.1371/journal.pbio.3001032

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

crypt support fibroblast

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**
https://orcid.org/0000-0002-7073-9172

**Additional notes or concerns**

-------

**Preferred term label**

crypt-top Fibroblast

**Synonyms** (add reference(s), please)

CTF

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

A crypt support fibroblast that is located at the top of the crypt of Lieberkuhn. These fibroblasts a range of cell-cell signaling factors (WNTs and BMPs) that promote epithelial differentiation, creating a gradient that regulates the balance between stem cell maintenance and differentiation.

https://doi.org/10.1371/journal.pbio.3001032

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

crypt support fibroblast

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**
https://orcid.org/0000-0002-7073-9172

**Additional notes or concerns**

**Comment by JABelfiore** [comment]
Terms already covered in another ticket and information in this ticket is incorrect
