### ISSUE TITLE
[NTR]Epithelial stem cell of gut

### ISSUE THREAD

**Issue by JABelfiore** [obophenotype/cell-ontology#2562]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
Epithelial stem cell of gut

**Synonyms** (add reference(s), please)
IESCs
PMID:24326621
**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A type of stem cell located at the base of intestinal crypts. This cell is capable of self-renewal and multipotent differentiation into all intestinal epithelial cell types including enterocytes, goblet cells, enteroendocrine cells, and paneth cells. Expresses markers such as LGR5, ASCL2, SMOC2. Interacts with supportive Paneth cells in the stem cell niche. Rapidly dividing to maintain intestinal epithelial homeostasis[PMID:24326621][PMID:38835047].

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
Epithelial fate stem cell 

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
 part of base of crypt of Lieberkuhn

**Your ORCID**
https://orcid.org/0009-0005-7919-4905

**Additional notes or concerns**

**Comment by dosumis** [comment]
should be part of intestinal epithelium

**Comment by dosumis** [comment]
These are commonly known as IESCs - Intestinal epithelial stem cells.  I would use this name and add the abbreviation.

"Epithelial fate stem cell" is very broad sounding - I don't think useful as synonym.  Looks like it belongs on parent class.

 Some suggested tweaks to def.

An epithelial stem cell located in a stem cell niche at the base of intestinal crypts. This cell is capable of self-renewal and multipotent differentiation into all intestinal epithelial cell types including enterocytes, goblet cells, enteroendocrine cells, and paneth cells.  These cells divide rapidly to maintain epithelial homeostatis.  A variety of adjacent cell types secrete signals that support and maintain the identity of this cell type in the niche, including Paneth Cells and specialised fibroblasts.

Expresses markers such as LGR5, ASCL2, SMOC2.  <-- Make clear in what species these apply (Do they cover both mice and humans?

[PMID:24326621][PMID:38835047].

Some more potential refs: PMID:[22610555](https://pubmed.ncbi.nlm.nih.gov/22610555), https://doi.org/10.1038/s12276-024-01179-1

**Comment by dosumis** [comment]
Probably the same cell type as intestinal crypt stem cell http://purl.obolibrary.org/obo/CL_0002250
