### ISSUE TITLE
[NTR] transit amplifying cell of gut

### ISSUE THREAD

**Issue by JABelfiore** [obophenotype/cell-ontology#2563]
**Preferred term label**
transit amplifying cell of gut

**Synonyms** (add reference(s), please)

Transit-amplifying cell (Broad) PMID: [24813615]

TA cell(Broad)PMID: [20683682]

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A transit amplifying cell of the gut is located in the intestinal crypt above the stem cell zone. This cell is part of a rapidly dividing cell population derived from intestinal stem cells. It is capable of multiple rounds of division before terminal differentiation. This cell gives rise to all differentiated intestinal epithelial cell types including absorptive enterocytes and secretory cells (goblet, enteroendocrine, and paneth cells). A transit amplifying cell of the gut expresses markers such as MCM5, TOP2A, CCNA2, PCLAF, HELLS, PCNA, and MKI67 in humans.  
PMID: [20683682] PMID: [33195268] PMID: 34497389

Extended: Plays a crucial role in intestinal epithelial homeostasis by amplifying the number of cells produced by stem cells. Controls R-spondin production to regulate intestinal stem cell proliferation. Acts as a signaling platform for controlling inflammatory cues and maintaining tissue regeneration. Susceptible to DNA damage due to rapid proliferation

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
transit amplifying cell

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
wall of crypt of Lieberkuhn

**Your ORCID**
https://orcid.org/0009-0005-7919-4905

**Additional notes or concerns**

**Comment by dosumis** [comment]
Looks good.

I think should be part of "wall of crypt of Lieberkuhn"
http://purl.obolibrary.org/obo/UBERON_0013740

Please check species specificity of markers
