### ISSUE TITLE
[NTR] Lamina propria fibroblast (S1)

### ISSUE THREAD

**Issue by JABelfiore** [obophenotype/cell-ontology#2565]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
Lamina propria fibroblast (S1)

**Synonyms** (add reference(s), please)
S1 fibroblast [PMID:30270042]

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A fibroblast is located in the lamina propria of the intestinal mucosa, particularly in the small intestine. This cell expresses PDGFRα and CD81 and is negative for α-smooth muscle actin (α-SMA). This cell is positioned adjacent to myofibroblasts surrounding colonic crypts. It is capable of synthesizing extracellular matrix components and structural proteins such as collagen and elastin[PMID:36639348][PMID:36251739].

Extended: Plays a critical role in maintaining intestinal homeostasis, supporting epithelial growth and repair, and contributing to immune responses. Derived from Gli1-expressing precursors present in embryonic day 12.5 intestine. Part of a diverse network of fibroblasts with region-specific functions in the small and large intestine. May contribute to the stem cell niche by secreting factors that influence epithelial cell behavior[PMID:36639348][PMID:36251739].

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

Fibroblast 

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

Lamina propria of intestinal mucosa

**Your ORCID**
https://orcid.org/0009-0005-7919-4905

**Additional notes or concerns**

**Comment by dosumis** [comment]
Add in links to GO via capable of. e.g. 
extracellular matrix constituent secretion
http://purl.obolibrary.org/obo/GO_0070278

**Comment by JABelfiore** [comment]
duplicate
