### ISSUE TITLE
[NTR] immune oligodendroglia BICAN Basal Ganglia term

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2575]
@JABelfiore please review

**Preferred term label**
immune oligodendroglia

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
An oligodendrocyte of the central nervous system that exhibits immune properties and it is involved in myelination. 
This cell type is immunoreactive during inflammation, neurodegenerative disorders, chronic stress and major depressive disorder. 

**database cross reference:**
PMID: [35301426](https://pubmed.ncbi.nlm.nih.gov/35301426)
PMID: [35615276](https://pubmed.ncbi.nlm.nih.gov/35615276)
PMID: [35301426](https://pubmed.ncbi.nlm.nih.gov/35301426)

**comments:**
During inflammation, immuno oligodendroglia express MHC II to interact with immune cells in mouse models (Harrington et al., 2023; Madeira et al., 2022). In a mouse model of major depressive disorder and chronic stress, immuno oligodendroglia were associated with prefrontal cortex hypomyelination (Kokkosis et al., 2022).

**database_cross_reference:**
PMID: [37057892](https://pubmed.ncbi.nlm.nih.gov/37057892)
PMID: [35615276](https://pubmed.ncbi.nlm.nih.gov/35615276)
PMID: [35301426](https://pubmed.ncbi.nlm.nih.gov/35301426)

**synonyms:**
ImOL
PMID: [35615276](https://pubmed.ncbi.nlm.nih.gov/35615276)

ImOLG
PMID: **30747918**

Immune oligodendrocyte
PMID: [35615276](https://pubmed.ncbi.nlm.nih.gov/35615276)

Im-OL
PMID: [35301426](https://pubmed.ncbi.nlm.nih.gov/35301426)

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
macroglia

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
central nervous system

**Comment by scheuerm** [comment]
This might be an example of a cell state induced by inflammatory and other "danger" signals.  Are we going to try to make a distinction between cell types and cell states in CL?

**Comment by AvolaAmg** [comment]
@scheuerm thanks for your comment.
This specific cell type is a grey area that I would like to discuss. In the literature it is often defined as a specific cell type
for instance in PMID: 35301426
> Analysis of single-nucleus transcriptomic data from MDD patients revealed oligodendroglial-lineage dysregulation and the presence of immune-oligodendrocytes (Im-OL), a novel population of cells with immune properties and myelination deficits. 
I would personally be keen to introduce the concept of cell states in cases where the cell type adopts clearly distinct properties in another state. 
@dosumis feel free to comment on the idea of including cell states in CL.

**Comment by dosumis** [comment]
Key question:  Do only a subset of oligodendrocytes have the capacity to exhibit immune functions, or is it a general property.  If the former then this strongly supports having a new cell type.

This paper suggests that immune function arises developmentally, depending on cytokine exposure of OPCs https://onlinelibrary.wiley.com/doi/full/10.1111/imm.13757

This review provides more general evidence for these being specialised oligodendrocytes developing from cytokine exposed OPCs https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9165378/

**Comment by AvolaAmg** [comment]
Thanks @dosumis I will include those in the definition.

**Comment by AvolaAmg** [comment]
Changed definition to expand on "immune function" 

An oligodendrocyte of the central nervous system that exhibits immune properties such as non-self antigen presentation to T cells, phagocytosis of debris, and cytokine and chemokine production.
This cell type is immunoreactive during inflammation, neurodegenerative disorders, chronic stress and major depressive disorder.

additional references:
PMID:30747918
PMID:35662200
PMID:35615276

for the developmental origin section, the additional information should be added to the [oligodendrocyte precursor cell](http://purl.obolibrary.org/obo/CL_0002453).

use these references and open a new ticket:
https://www.frontiersin.org/journals/immunology/articles/10.3389/fimmu.2024.1425706/full
https://onlinelibrary.wiley.com/doi/epdf/10.1111/imm.13757
