### ISSUE TITLE
[NTR] GABAergic interneuron pSNpr aSNpr for BICAN Basal Ganglia

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2577]
@JABelfiore please review

**GABAergic neuron of the anterior substantia nigra pars reticulata**

**definition:**
a GABAergic interneuron that has its soma in the anterior section of the substantia nigra pars reticulata. This GABAergic neuron is characterized by the expression of Six3 and Foxp1 and it develops from Nkx6-2 expressing neuronal progenitors in the ventrolateral midbrain-diencephalon region.

**database_cross_reference:**
PMID: 36148148

**synonyms:**
aSNpr
**database_cross_reference:**
PMID: 36148148

**parent term:**

**GABAergic neuron of the posterior substantia nigra pars reticulata**
**definition:**
A GABAergic interneuron that has its soma in the posterior section of the substnia nigra pars reticulata. This GABAergic neuron is characterised by the expression of the transcription factors Pax5, Ctip2 and Pou6f2 and it develops from the ventrolateral r1 neuroepithelium expresing NKX61.
**database_cross_reference:**
PMID: 36148148

**synonyms:**
pSNpr
**database_cross_reference:**
PMID: 36148148

**Comment by dosumis** [comment]
All look good so far.  Consider making tickets for cell types they develop from.
