### ISSUE TITLE
remove broad synonym DaN from "substantia nigra dopaminergic neuron"

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2605]
Shouldn't 'DaN' be an exact synonym on Dopaminergic neuron?  

[substantia nigra dopaminergic neuron](http://purl.obolibrary.org/obo/CL_4042024) [has_broad_synonym](http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym) "DaN"

In general I would only use broad synonym if there is no term to attach the same name to as an exact synonym to (or maybe in this case 'related' + abbreviation - following general policy on abbreviations).  Important to think from the perspective of someone searching the ontology.

(Apologies for missing this on PR.  Easier to read if you run gogoedit diff when you want a review.)

**Comment by AvolaAmg** [comment]
No worries at all I will get rid of it right now. 
Good to know for the future!

**Comment by AvolaAmg** [comment]
all done @dosumis you can see it in the new commit.
