### ISSUE TITLE
[Class hierarchy]

### ISSUE THREAD

**Issue by tnetx** [obophenotype/cell-ontology#2621]
**CL term**
Seen in https://github.com/obophenotype/cell-ontology/blob/v2024-09-26/cl.obo

````
id: CL:0000163
name: endocrine cell
def: "A cell of an endocrine gland, ductless glands that secrete substances which are released directly into the circulation and which influence metabolism and other body functions." [MESH:D055098]
subset: general_cell_types_upper_slim
subset: human_reference_atlas
synonym: "endocrinocyte" EXACT []
xref: FMA:83809
is_a: CL:0000151 ! secretory cell
is_a: CL:0000164 {gci_relation="part_of", gci_filler="UBERON:0000945"} ! enteroendocrine cell
is_a: CL:0000164 {gci_filler="UBERON:0000160", gci_relation="part_of"} ! enteroendocrine cell
is_a: CL:0000164 {gci_filler="UBERON:0001264", gci_relation="part_of"} ! enteroendocrine cell
relationship: part_of UBERON:0000949 ! endocrine system
relationship: present_in_taxon NCBITaxon:9606 ! Homo sapiens

[Term]
id: CL:0000164
name: enteroendocrine cell
def: "An endocrine cell that is located in the epithelium of the gastrointestinal tract or in the pancreas." [GOC:tfm, SANBI:mhl]
xref: BTO:0003865
xref: FMA:62930
xref: MESH:D019858
is_a: CL:0000150 ! glandular epithelial cell
is_a: CL:0000163 ! endocrine cell
````

**Suggested revision of class hierarchy**

There seems to be a circular parent-child hierarchy between ````CL:0000163```` (endocrine cell) and ````CL:0000164```` (enteroendocrine cell).  Are the is_a relationships from ````CL:0000163```` to ````CL:0000164```` autogenerated?  It seems that only ````CL:0000164```` should be "is_a" ````CL:0000163````.

**Comment by tnetx** [comment]
@dosumis I do indeed think it's misleading.  Would it be preferable to state it as relationship: part_of: UBERON:0000945 on the enteroendocrine Term instead?


````
id: CL:0000164
name: enteroendocrine cell
is_a: CL:0000163 ! endocrine cell
...
relationship: part_of: UBERON:0000945 ! stomach
```

**Comment by dosumis** [comment]
It is not true that all enteroendocrine cells are part of the stomach, some are part of the pancreas, so "relationship: part_of: UBERON:0000945 ! stomach" would be incorrect .The OWL expression allows us to assert both part relationships and use the3m to autoclassify endocrine cells as enteroendocrine. 

The issue is not with the assertions but with confusion caused by the OBO representation.  

Could you let us know what you are trying to achieve?  You may not need to use the OBO file.

**Comment by tnetx** [comment]
> Could you let us know what you are trying to achieve? You may not need to use the OBO file.

We are trying to parse the hierarchical relations between the Terms.  From the [OBO v1.2 format specification](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_2.html), we interpreted that is_a tags would describe only parent classes, not conditional subclasses.

**Comment by dosumis** [comment]
The file is OBO 1.4 spec.  The JSON serialization is much more suitable for you aim.  Not parsing needed.

https://github.com/obophenotype/cell-ontology/releases/tag/v2024-09-26

If you only want CL terms then cl-simple.json will be the best to use.

**Comment by tnetx** [comment]
> The file is OBO 1.4 spec.

I believe the [cl.obo file ](https://github.com/obophenotype/cell-ontology/blob/v2024-09-26/cl.obo) still says it's in v1.2 OBO format.  Although, from the [OBO v1.4 specifications](https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html), we also interpreted that the 'is_a' tag would only describe parent classes and that trailing modifiers {...} should only contain optional information.

> The JSON serialization is much more suitable for your aim - no parsing needed.

Thank you!  We will try parsing the JSON instead.
