### ISSUE TITLE
Revise logical definition for CL:0000863 inflammatory macrophage

### ISSUE THREAD

**Issue by raymond91125** [obophenotype/cell-ontology#2627]
CL:0000863 inflammatory macrophage LD
'elicited macrophage'
 and ('capable of' some 'interleukin-1 beta production')
 and ('capable of' some 'interleukin-6 production')
 and ('capable of' some 'tumor necrosis factor production')
 and ('capable of' some 'superoxide anion generation')
 and ('capable of' some 'defense response to bacterium')
 and ('capable of' some 'nitric-oxide synthase biosynthetic process')

Includes GO:0051767 'nitric-oxide synthase biosynthetic process' that is proposed to be obsoleted. See https://github.com/geneontology/go-ontology/issues/28860.

**Comment by addiehl** [comment]
We should just drop the ('capable of' some 'nitric-oxide synthase biosynthetic process') portion of the logical definition.

**Comment by raymond91125** [comment]
Thanks!

**Comment by aleixpuigb** [comment]
Thank you for letting us know about the obsoletion!
