### ISSUE TITLE
[Typo] Some labels contain underscores

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#2630]
**CL term**
CL0000997	immature CD8_alpha-negative CD11b-positive dendritic cell
CL0000998	CD8_alpha-negative CD11b-negative dendritic cell
CL0001000	CD8_alpha-positive CD11b-negative dendritic cell
CL0001001	immature CD8_alpha-negative CD11b-negative dendritic cell	
CL0001002	mature CD8_alpha-negative CD11b-negative dendritic cell
CL0001003	mature CD8_alpha-negative CD11b-positive dendritic cell
CL0001004	immature CD8_alpha-positive CD11b-negative dendritic cell
CL0001005	mature CD8_alpha-positive CD11b-negative dendritic cell
CL0001015	CD8_alpha-low Langerhans cell
CL0001018	immature CD8_alpha-low Langerhans cell
CL0001020	mature CD8_alpha-low Langerhans cell
CL0002454	Cd4-negative, CD8_alpha-negative, CD11b-positive dendritic cell
CL0002455	CD8_alpha-negative plasmactyoid dendritic cell
CL0002456	CD8_alpha-positive plasmactyoid dendritic cell

**Description of typo, bug or error**
The labels listed above contain underscores. You might want to replace them with hyphens, please. Thank you!

Paola

**Comment by aleixpuigb** [comment]
Thank you for your ticket, all underscores in labels and definitions have been changed to hyphens.

**Comment by paola-scibite** [comment]
> Thank you for your ticket, all underscores in labels and definitions have been changed to hyphens.

@aleixpuigb thank you!
