### ISSUE TITLE
[Text def] Revise textual and logical defs -parietal cell

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2672]
**CL term**
[parietal cell](http://purl.obolibrary.org/obo/CL_0000162)

**Suggested revision of textual definition**
An epithelial cell of the stomach that is part of the gastric gland. This cell is characterized by its pyramidal shape, abundant mitochondria, and a complex network of secretory canaliculi lined with microvilli. It secretes hydrochloric acid into the stomach lumen and produces intrinsic factor, essential for vitamin B12 absorption.

PMID: [31613538](https://pubmed.ncbi.nlm.nih.gov/31613538)
PMID: [31670611](https://pubmed.ncbi.nlm.nih.gov/31670611/)

**Comments section**
More details about the microvillus in the resting and secretory phase 

**Logical defs**
- Remove unnecessary axioms 
- links to GO - microvillus 
- Add 'part of' some 'gastric gland'

**Comment by dosumis** [comment]
update GO term to 'gastric acid secretion'
