### ISSUE TITLE
[NTR-cxg]type IIx muscle cell

### ISSUE THREAD

**Issue by jychien** [obophenotype/cell-ontology#2673]
I am currently working with the author of https://doi.org/10.1101/2024.05.15.594276. (@sebozzie)

**Preferred term label**
type IIx muscle cell

**Synonym(s)**
type 2x muscle cell, type 2x muscle fiber, type IIx muscle fiber

**Definition**
A fast type II muscle cell that utilize both the oxidative and glycolytic pathways for metabolism. These cells are distinguished by the expression of myosin heavy chain 1 (MYH1).

**Parent cell type term** 
CL:0002212: type II muscle cell

**Anatomical structure where the cell type is found**
UBERON:0001134: skeletal muscle tissue

**Additional notes or concerns**

- https://doi.org/10.1101/2024.05.15.594276:  "Within the myonuclei population type IIB, IIX and IIA myonuclei were distinguishable based on the expression of Myh4, Myh1 and Myh2, respectively"
- https://doi.org/10.1186/s13395-021-00279-0: "We provide and analyze a resource dataset based on relatively pure fibers, containing at least 80% of either MYH7 (marker of slow type 1 fibers), MYH2 (marker of fast 2A fibers), or MYH1 (marker of fast 2X fibers)."

**Comment by Caroline-99** [comment]
Hi @jychien. The new term `type IIx muscle cell (CL:4052026)` will be included in the next CL release. Thank you.
