### ISSUE TITLE
[NTR-cxg] myotendinous junction

### ISSUE THREAD

**Issue by sebozzie** [obophenotype/cell-ontology#2676]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
myotendinous junction

**Synonym(s)** (add reference(s), please)
myotendinous junction nuclei [https://doi.org/10.1038/s41467-020-20063-w](https://doi.org/10.1038/s41467-020-20063-w)
MTJ [https://doi.org/10.1038/s41467-020-18789-8](https://doi.org/10.1038/s41467-020-18789-8)
MTJ nuclei [https://doi.org/10.1038/s41467-020-20064-9](https://doi.org/10.1038/s41467-020-20064-9)

**Definition**
Myotendinous junction nuclei are specialized muscle nuclei located at the interface where muscle fibers connect to tendons. These myonuclei help regulate the structural integrity and function of the muscle-tendon connection, playing a key role in transmitting the force generated by muscle contraction to the tendon.

**Parent cell type term**
CL:0008046: extrafusal muscle fiber

**Anatomical structure where the cell type is found** 
UBERON:0001134: skeletal muscle tissue

**Your ORCID**
0009-0001-6947-615X

**Additional notes or concerns** 

[https://doi.org/10.1038/s41467-020-20063-w](https://doi.org/10.1038/s41467-020-20063-w): "Myotendinous junction (MTJ) nuclei ... were notable for expression of Col22a1 ..."

**Comment by dosumis** [comment]
GO has myotendenous junction GO:0005927

suggested label: myotendenous junction nucleus 
Suggested EC def: 'GO:nucleus and part_of some 'CL:0008046; extrafusal muscle fiber' and overlaps some ' GO:0005927; 'myotendenous junction'

**Comment by Caroline-99** [comment]
Hi @sebozzie. The new term 'myotendinous junction nucleus (CL:4052024) will be included in the next CL release.  The terms "myotendinous junction nuclei" and "MTJ nuclei" have been added as synonyms. Thank you.
