### ISSUE TITLE
[NTR-cxg] neuromuscular junction

### ISSUE THREAD

**Issue by sebozzie** [obophenotype/cell-ontology#2678]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

Preferred term label
neuromuscular junction

Synonym(s) (add reference(s), please)
neuromuscular junction nuclei https://doi.org/10.1038/s41467-020-20063-w 
NMJ https://doi.org/10.1038/s41467-020-18789-8
NMJ nuclei https://doi.org/10.1038/s41467-020-20064-9 - PMID: [33311457](https://pubmed.ncbi.nlm.nih.gov/33311457/)
NMJ myonuclei - PMID:33311464

Definition
Neuromuscular junction nuclei are specialized muscle nuclei located at the synapse where a motor neuron communicates with a muscle fiber. They regulate the production of proteins essential for maintaining the structure and function of the neuromuscular junction, supporting efficient nerve-muscle signaling for muscle contraction.

Parent cell type term
CL:0008046: extrafusal muscle fiber

Anatomical structure where the cell type is found
UBERON:0001134: skeletal muscle tissue

Your ORCID
0009-0001-6947-615X

Additional notes or concerns

https://doi.org/10.1038/s41467-020-20063-w: "NMJ nuclei were positive for known canonical markers such as Chrne, Etv5, Colq, and Musk..."

**Comment by dosumis** [comment]
Given the suggestion of  'CL:0008046; extrafusal muscle fiber' as a parent I assume that this term is intended for skeletal muscle NMJ nuclei  is that correct?

suggested label: skeletal nueuromuscular junction nucleus (?)
Suggested EC def:  'GO:nucleus and part_of some 'CL:0008046; extrafusal muscle fiber' and overlaps some ' GO:0098523; neuromuscular junction of myotube'

**Comment by sebozzie** [comment]
@dosumis Indeed, it is intended for skeletal muscle NMJ nuclei. In that case I would suggest the label "neuromuscular junction nuclei" or "NMJ nuclei".

**Comment by Caroline-99** [comment]
Hi @sebozzie. The new term 'neuromuscular junction nucleus (CL:4052025)' will be included in the next CL release.  The terms "neuromuscular junction nuclei" and "NMJ nuclei" have been added as synonyms. Thank you.
