### ISSUE TITLE
 Re-label glandular cell of endometrium & improve classifications 

### ISSUE THREAD

**Issue by Caroline-99** [obophenotype/cell-ontology#2695]
Related #1760 #2468 
- [x] Re-label glandular cell of endometrium to `glandular endometrial unciliated epithelial cell` to remain consistent with the luminal endometrial unciliated epithelial cell - Related #1760
- [x] Add glandular cell of endometrium as a broad synonym

Related #2468  
- [x] Add` part of some endometrial gland` instead of `part of some endometrial glandular epithelium` to classify glandular endometrial ciliated epithelial cell under epithelial cell of endometrial gland.

**Comment by aleixpuigb** [comment]
I would suggest another option, a new ET for [epithelial cell of endometrial gland](http://purl.obolibrary.org/obo/CL_0009084):
`'epithelial cell' and ('part of' some 'endometrial glandular epithelium')`

![image](https://github.com/user-attachments/assets/ef82a054-6ca9-45f7-a377-ddf41050283f)
