### ISSUE TITLE
toxoplasma life cycle stages

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#270]
see attached file

Original comment by: jmm13

**Comment by nicolevasilevsky** [comment]
Do these definitions make sense:
- **tachyzoite**: The rapidly growing life stage of T. gondii, which replicates within a parasitophorous vacuole within the host cell. Synonyms: endozoite, trophozoite. Source: https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/tachyzoite
- **bradyzoite**: The life stage found in the tissue cyst which replicates slowly within a parasitophorous vacuole within the host cell. Synonym: cystozoite. Source: https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/tachyzoite
- **sporozoite**: A usually motile infective form of some sporozoans that is a product of sporogony and initiates an asexual cycle in the new host. Source: https://www.merriam-webster.com/dictionary/sporozoite

**Comment by cmungall** [comment]
wow, this ticket is from 10 years ago!

Since then we have OPL can you coordinate with them?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky following up on this ticket, OPL ( the Ontology for Parasite Lifecycle) has

- [OPL:0000057 trophozoite stage](https://www.ebi.ac.uk/ols/ontologies/opl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOPL_0000057) (you listed "trophozoite" as a synonym of tachyzoite)
- [OPL:0000152 sporozoite stage](https://www.ebi.ac.uk/ols/ontologies/opl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOPL_0000152)

so only 'bradyzoite' seems missing. I can put in a quick request if you'd like.

**Comment by nicolevasilevsky** [comment]
that would be great, thanks @paolaroncaglia!
And thanks for clarifying about OPL, I didn't know what that is. :)

**Comment by paolaroncaglia** [comment]
Done: https://github.com/OPL-ontology/OPL/issues/19. Closing now.
