### ISSUE TITLE
CL to AO part_of links

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#271]
attached: 110 proposed all-some part_of links to Uberon, derived from ZFA (ZFA IDs shown for comparison). Not vetted - it's possible some of these are ZFA specific.

For latest version see http://github.com/cmungall/uberon
cell-to-uberon-via-ZFA.txt

Original comment by: cmungall

**Comment by paolaroncaglia** [comment]
There is no longer a cell-to-uberon-via-ZFA.txt in http://github.com/cmungall/uberon (now obophenotype/uberon), or at least I can't spot it. I suspect this may be out of date.

**Comment by bvarner-ebi** [comment]
Hi, @cmungall. Are you expecting any other work on this ticket? As noted in the comment above, this ticket may be out of date, and I plan to close it unless additional feedback is provided within the next week.

CC: @dosumis, @matentzn

**Comment by matentzn** [comment]
100% close this.
