### ISSUE TITLE
Switch CL build to use the Whelk reasoner

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2717]
This is required for reasoning to take advantage of property chains added for https://github.com/oborel/obo-relations/issues/787

ROBOT supports Whelk

CC @balhoff  - I assume no down-sides.  Please yell if I'm wrong.  Thanks!

**Comment by gouttegd** [comment]
Note that while Whelk has just been updated to version 1.2.1 in ROBOT (two days ago), the version available in the ODK as of now is still 1.0.4.

**Comment by balhoff** [comment]
@dosumis @gouttegd Whelk is slower and uses more memory, but supports these additional axiom types. It's possible you won't notice for CL. Whelk 1.0.4 does not use property ranges, but 1.2.1 does.

**Comment by gouttegd** [comment]
From a quick test:

* With ELK: `make test` runs in ~2min and consumes ~6.5 GB of RAM
* With WHELK: `make test` runs in ~3.30min and consumes ~7.6GB of RAN

Strictly speaking it’s almost a doubling of the running time, but that seems sustainable to me.
