### ISSUE TITLE
Add cellmark CL release artefact to CL components

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2725]
This contains marker content approved for CL:

https://github.com/Cellular-Semantics/CellMark/blob/main/clm-cl.owl

I think it makes most sense to incorporate as a component as we need the whole thing rather than just a module.

- [ ] Add step to makefile to pull content into components folder
- [ ] Add import statement to cl-edit.owl

I think that's it/

**Comment by scheuerm** [comment]
Very excited to see this!!  Thanks!!!

**Comment by Caroline-99** [comment]
This ticket was fixed by this PR https://github.com/obophenotype/cell-ontology/pull/2772
