### ISSUE TITLE
[NTR] post-arteriole capillary cell

### ISSUE THREAD

**Issue by JABelfiore** [obophenotype/cell-ontology#2726]
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
post-arteriole capillary cell

**Synonyms** (add reference(s), please)
blood vascular endothelial cells (broad) PMID: 35406678 

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

An endothelial cell forming the walls of capillaries immediately downstream from arterioles, facilitating the exchange of substances between blood and interstitial fluid. This cell is characterized by a small diameter and may be continuous, fenestrated, or sinusoidal, depending on their location and function. This cell plays a crucial role in tissue oxygenation, nutrient delivery, and maintaining homeostasis within the microvascular network.

PMID: 35406678 PMID: 17893694 

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
Capillary endothelial cell

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**
https://orcid.org/0009-0005-7919-4905

**Additional notes or concerns**

**Comment by dosumis** [comment]
Curious about the motivation for this term.  Presumably it is a subtype of capillary endothelial cell.

**Comment by JABelfiore** [comment]
> Curious about the motivation for this term. Presumably it is a subtype of capillary endothelial cell.

This is from the GCA hierarchy, this cell type has characteristics from both arteriole and capillary cells and expresses both marker types.
