### ISSUE TITLE
Link deuterosomal cell to centriole replication

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#2774]
Based on text of def this is valid:

An epithelial cell part of respiratory tract epithelium that is a precursor of a multi-ciliated cell. This cell actively amplifies centrioles, a required step for multiciliogenesis.

\+
SubClassOf capable_of some centriole replication (GO:0007099)

**Comment by Caroline-99** [comment]
@dosumis Would this term be more specific [de novo centriole assembly involved in multi-ciliated epithelial cell differentiation](http://purl.obolibrary.org/obo/GO_0098535)?
