### ISSUE TITLE
adjust definition of thalamic excitatory neuron

### ISSUE THREAD

**Issue by AvolaAmg** [obophenotype/cell-ontology#2795]

**Comment by AvolaAmg** [comment]
Some references for this ticket:
- https://www.ncbi.nlm.nih.gov/books/NBK549908/#:~:text=The%20thalamus%20is%20a%20paired,and%20an%20anterior%20nuclear%20group.
- https://pubmed.ncbi.nlm.nih.gov/25616182/
- [Paraventricular Thalamus Projection Neurons Integrate Cortical and Hypothalamic Signals for Cue- Reward Processing](https://www.cell.com/neuron/pdf/S0896-6273(19)30443-X.pdf)
- https://www.nature.com/articles/s41531-018-0060-6#:~:text=These%20thalamic%20glutamatergic%20neurons%20provide,PD%20and%20other%20neurological%20disorders.
- https://link.springer.com/article/10.1007/s12264-024-01207-0
- Glutamatergic neurons in paraventricular nucleus of the thalamus regulate the recovery from isoflurane anesthesia
- Anterior thalamic glutamatergic neurons modulate prefrontal cortical firing and regularity
- https://www.sciencedirect.com/science/article/pii/S0006322323013045#:~:text=Background,has%20not%20yet%20been%20assessed.

**Comment by scheuerm** [comment]
I believe it should be spelled "glutamatergic"

**Comment by AvolaAmg** [comment]
A Draft
- 
**label:**
glutametergic neuron of the thalamus

**definition:**
A glutamatergic neuron with soma located in a thalamus. This neuron type can be involved in a series of circuits related to sensory integration, motor integration, pain processing, circadian rhythm and reward response.

**comments:**
Glutamatergic neurons of the thalamus are part of a diverse series of circuits [Add the circuits and potential function here] 
[Add pathologies here]
