### ISSUE TITLE
Waltham Data Science ID numbers?

### ISSUE THREAD

**Issue by stevewds** [obophenotype/cell-ontology#2858]
Hi - 

At the November Uberon / CL meeting we discussed Waltham Data Science getting some identifiers to add to the ontology. Could we please have some?

@gouttegd @rays22 

Thanks!
Steve

**Comment by gouttegd** [comment]
Done. You got the range 4,070,001--4,071,999.

**Comment by stevewds** [comment]
Thank you @gouttegd
