### ISSUE TITLE
LTi-lymphoid tissue–inducer

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#299]
Looking at the .obo file from 11/4, this time,  I do not see lymphoid tissue–inducer cells which are discussed in J:164687. They state "Key to the development of lymph nodes and Peyer’s patches is a distinct subset of cells called lymphoid tissue–inducer (LTi) cells, which have been identified in both mice and humans." They then reference PMID: 19029905 and 9354470.

Original comment by: jbubier

**Comment by nicolevasilevsky** [comment]
I think this can be closed, this term is in CL:
CL_0011018
