### ISSUE TITLE
Align thymocyte / DN T Cell with MP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#31]
```
See: 
https://sourceforge.net/tracker/?func=detail&atid=1109502&aid=3610968&group_id=7
6834


```

Original issue reported on code.google.com by `cmung...@gmail.com` on 20 Apr 2013 at 8:07

**Comment by addiehl** [comment]
Closing.  Will reopen if a better description of the problem is provided.  I suspect MP is the problem, not CL in any case.
