### ISSUE TITLE
NTR H90

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#336]
Following on from my request about the heterothallic H- and H+ S. pombe \(https://sourceforge.net/tracker/?func=detail&aid=3392537&group\_id=76834&atid=925065\)....

Could I please request a new term that refer to homothallic S. pombe.

The reason for this is that pombe switch between the H+ and H- genotype every ~3 generations, and therefore it would be useful to have a term describing this cell-type

This cell-type is known as H90 in the pombe community \(http://www-bcf.usc.edu/~forsburg/diploids.html\).

Cheers
Antonia

Original comment by: antonialock

**Comment by cmungall** [comment]
@Antonialock do you still need this?

**Comment by Antonialock** [comment]
no it is ok
