### ISSUE TITLE
CL:0000372 ! tormogen cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#342]
Consider adding a taxon constraint to insecta

Original comment by: cmungall

**Comment by bvarner-ebi** [comment]
Hi, @gouttegd, checking in to see if this is still an active issue. If not, can we close the ticket? If more discussion is needed, can we add to CL meeting agenda and invite parties who can provide input?

**Comment by gouttegd** [comment]
Still active, yes. I’ll add the taxon restriction, but I think it should go to the parental term `epidermal cell (sensu arthropoda)` (CL:0000463) instead. This is consistent with the name of that cell type and will automatically cover both `tormogen cell` (CL:0000372) and `trichogen cell` (CL:0000374).
