### ISSUE TITLE
NTR: cardiovascular progenitor cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#349]
PMID:17519333

"give rise to cardiomyocyte, endothelial, and smooth muscle lineages"

Original comment by: cmungall

**Comment by bonitalam** [comment]
Hello, the ENCODE project is interested in this term for annotating some biosamples we have. Any updates would be much appreciated!

**Comment by nicolevasilevsky** [comment]
Hi @bonitalam I'll try to add this asap

**Comment by nicolevasilevsky** [comment]
note to self:
parent: CL_0000048 'multi fate stem cell'

**Comment by nicolevasilevsky** [comment]
@bonitalam I think this is a synonym of cardioblast:
A stem cell that can give rise to multiple cell types (i.e. smooth muscle, endothelial) in the developing heart.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2796444/

**Comment by bonitalam** [comment]
@nicolevasilevsky thank you for adding the synonym to cardioblast!
