### ISSUE TITLE
cardiac neural crest cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#350]
We have several 'cardiac neural crest cell' process terms in GO:

E.g:
cardiac neural crest cell development involved in heart development ; GO:0061308
cardiac neural crest cell development involved in outflow tract morphogenesis ; GO:0061309
cardiac neural crest cell differentiation involved in heart development ; GO:0061307
cardiac neural crest cell migration involved in outflow tract morphogenesis ; GO:0003253

Could a corresponding 'cardiac neural crest cell' term be added to the cell ontology, please?
is_a: neural crest cell ; CL:0000333

presumably with the following child (derived_from)
cardiac mesenchymal cell ; CL:0000569

PMID: 16054405
PMID: 20890117
PMID: 12490557

Thanks,
Becky

Original comment by: nobody

**Comment by nicolevasilevsky** [comment]
to do:
- [ ] cardiac mesenchymal cell; CL:0000569 should be a child of cardiac neural crest cell
- [ ] add vagal neural crest cell PMID:22016183
- [ ] add text def to CL:0000008 migratory cranial neural crest cell
- [ ] CL:0000011 migratory trunk neural crest cell

@mellybelly do you know the answer to @cmungall's question above:
the following three terms already exist; are these the same thing? Are these neural crest cell types always 'migratory'?

**Comment by bvarner-ebi** [comment]
Hi, @nicolevasilevsky, is this still an active issue? If not, can we close the ticket? If it requires more discussion, feel free to add to the next CL meeting agenda and invite parties who can provide input.

**Comment by nicolevasilevsky** [comment]
From a quick google search, it looks like 'migratory cardiac neural crest cell' is the same as cardiac neural crest cell:
https://journals.biologists.com/dev/article/147/20/dev188706/225875/The-heart-of-the-neural-crest-cardiac-neural-crest

I'll add a synonym.

@bvarner-ebi could I assign you as a reviewer?
