### ISSUE TITLE
CL:0000746 ! A myocyte located in the heart. The contractile

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#351]
def: "A myocyte located in the heart. The contractile fiber resembles those of skeletal muscle but are only one third as large in diameter, are richer in sarcoplasm, and contain centrally located instead of peripheral nuclei"

This is too specific. The term should work for all metazoans, including
FBbt:00007319 ! cardial cell [SYNONYM: "cardiomyocyte" (exact)]

GO has
GO:0055007 ! cardiac muscle cell differentiation [DEF: "The process in which a cardiac muscle precursor cell acquires specialized features of a cardiac muscle cell. Cardiac muscle cells are striated muscle cells that are responsible for heart contraction."]

Original comment by: cmungall

**Comment by addiehl** [comment]
I believe all issues here are fixed.
