### ISSUE TITLE
upper level cell type coordination

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#356]
Attached is a proposal for reorganizing and defining some of the upper level cell types in order to coordinate across ontologies such as OBI, ReO, CLO, CARO etc. Note that the axioms are simply a starting place and should be used as examples of the sort of logical definitions that we should create.

Thanks much,
Melissa and Matt

Original comment by: mellybelly

**Comment by nicolevasilevsky** [comment]
@mellybelly @mbrush @cmungall 
It looks like the attached document was not migrated to GitHub.

Is this still needed? If yes, is there any way you could dig up the original attachment? :)

**Comment by cmungall** [comment]
close
