### ISSUE TITLE
NTRs: olfactory bulb cell types

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#357]
~ CL:new ! olfactory bulb cell
~~ CL:new ! mitral cell
~~ CL:new ! olfactory interneuron
~~~ CL:0000626 ! olfactory granule cell [add syn for olf. bulb]
~~~ CL:new ! olfactory bulb periglomerular cell

needed to define terms below:

[Term]
id: MP:0009941
name: abnormal olfactory bulb interneuron morphology
namespace: MPheno.ontology
def: "any structural anomaly of the group of neurons residing in the olfactory bulb that serve to process and refine signals arising from olfactory sensory neurons" [PMID:18603310]
is_a: MP:0000819  ! abnormal olfactory bulb morphology
is_a: MP:0000965  ! abnormal sensory neuron morphology

[Term]
id: MP:0009942
name: abnormal olfactory bulb granule cell morphology
namespace: MPheno.ontology
def: "any structural anomaly of the main intrinsic GABAergic neuron in the granule cell layer of the main olfactory bulb; dendrites of these cells receive synaptic input from mitral and tufted cell lateral dendrites in the external plexiform layer, and have synaptic outputs on those dendrites through reciprocal dendrodendritic synapses" [NLX:nifext_123]
synonym: "abnormal olfactory granule neuron morphology" EXACT []
xref: CL:0000626
xref: NLX:nifext_123
is_a: MP:0009941  ! abnormal olfactory bulb interneuron morphology
is_a: MP:0009949  ! abnormal olfactory bulb granule cell layer morphology

[Term]
id: MP:0009943
name: abnormal olfactory bulb periglomerular cell morphology
namespace: MPheno.ontology
def: "any structural anomaly of the small neuron in the glomerular layer of the olfactory bulb whose dendrites arborize within a glomerulus, where it receives synaptic input from olfactory receptor cell axon terminals, and also engages in dendrodendritic interactions with mitral and tufted cell dendrites; uses both GABA and dopamine as a neurotransmitter" [NLX:nlx_cell_091202]
synonym: "abnormal olfactory bulb periglomerular neuron morphology" EXACT []
xref: NLX:nlx_cell_091202
is_a: MP:0009941  ! abnormal olfactory bulb interneuron morphology
is_a: MP:0009948  ! abnormal olfactory bulb glomerular layer morphology

Original comment by: cmungall

**Comment by nicolevasilevsky** [comment]
We have:
CL_1001502 'mitral cell'
CL_1001434 'olfactory bulb interneuron'

I'll look into adding 'olfactory bulb cell'

**Comment by nicolevasilevsky** [comment]
@cmungall is 'olfactory bulb cell' still needed?
We have CL_1001434 'olfactory bulb interneuron'

**Comment by cmungall** [comment]
olfactory bulb cell' is a weird grouping - should probably be olfactory
bulb neuron. Assume there are other neuron types there

**Comment by shawntanzk** [comment]
Just took a look at this - probably need to do more reading that I have done so far, but it seems to me that most olfactory cells are interneurons (including the two classes under it). Probably needs relooking later on in terms of making it more complete, and will hopefully get to this if the brain data standards map gets to this area/if it gets funded enough to reach this area (if not before when I can spend a bit more time reading more on this) 
Putting this comment here and assigning myself to it so it doesnt go stale.

**Comment by cmungall** [comment]
Makes sense

Maybe we can close the ticket before it reaches it's tenth birthday :-)

Nicole, in the interim, we should make sure we have a pattern for "X cell" where X is an anatomical structure. Don't see here
https://github.com/obophenotype/cell-ontology/tree/master/src/patterns/dosdp-patterns

I am not a fan of these terms. We have a lot from KUPO. They just shadow the AO. First task is properly cataloging them via DPs

**Comment by cmungall** [comment]
We do have https://github.com/obophenotype/cell-ontology/blob/master/src/patterns/dosdp-patterns/cellPartOfAnatomicalEntity.yaml

However, it's not clear from the name of this pattern that here cell is a variable. We want another pattern where cell is fixed at 'cell'. We need better naming conventions for DPs!

https://github.com/INCATools/dead_simple_owl_design_patterns/issues/67
