### ISSUE TITLE
Remove leading uppercase from FMA-derived syns

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#360]
Example:

[Term]
id: CL:0002072
name: nodal myocyte
namespace: cell
def: "A specialized cardiac myocyte in the sinuatrial and atrioventricular nodes. The cell is slender and fusiform confined to the nodal center, circumferentially arranged around the nodal artery." [FMA:67101, GOC:tfm, http://63.198.234.228/OpenFMA/Nodal%20myocyte.html\]
***synonym: "Myocytus nodalis" EXACT []
synonym: "P cell" EXACT []
***synonym: "Pacemaker cell" EXACT []
xref: BTO:0004190
xref: FMA:67101
is_a: CL:0002086 ! specialized cardiac myocyte
created_by: tmeehan
creation_date: 2010-06-29T11:41:37Z

obviously P cell remains the same

Original comment by: cmungall

**Comment by paolaroncaglia** [comment]
Capitalization in the example has been fixed since. I presume other cases were addressed as part of #438 , so I'll close.
