### ISSUE TITLE
T cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#371]
Hi, In the current CL file (March 22nd 2012) T cell is defined as "A type of lymphocyte whose defining characteristic is the expression of a T cell receptor complex." However I couldn't see any restriction to that effect, nor a class "T cell receptor complex" 

Use case: I am trying to query the file to get something along the lines of "what type of cells is CD3 positive" which I would expect to return T cells. CD3 is part of the T cell receptor complex, so that would require that the restrictions/class above are explicitly added to the file.

Thanks,
Melanie

Original comment by: mcourtot

**Comment by nicolevasilevsky** [comment]
Looks like the def of T cell has been updated. Closing this.
