### ISSUE TITLE
obsoletion request: CL:0000122 ! stellate cell issues

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#375]
CL has this as a CNS cell:

[Term]
id: CL:0000122
name: stellate cell
namespace: cell
xref: BTO:0002316
is_a: CL:0000117 ! CNS neuron (sensu Vertebrata)

There is no def. The def in BTO is:
def: "Any cell having a star-shaped appearance produced by numerous processes that extend in different directions, such as the Kupffer cells in the liver, astrocytes, and granule cells in the granular layers of the cerebral and cerebellar cortices." [BTO:0002316]

i.e. this is a very generic morphological definition. Although it has no children in BTO.

Which definition does CL intend? The graph says CNS. A generic fuzzy morphological term like BTO seems useless.

Note we have no children of this in CL. Neither of the two are asserted to be subtypes:

stellate interneuron
hepatic stellate cell

(which would be subtypes of a fuzzy grouping class, but only the former would be a subtype of the CNS type)

I think the safest thing is just to obsolete this term.

I will obsolete this if no one has objections within ~1wk

Original comment by: cmungall

**Comment by shawntanzk** [comment]
It now has a def and is currently being used
