### ISSUE TITLE
skeletal muscle satellite cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#384]
this is classified as a muscle precursor, but Al says this is not the case:

[Term]
id: CL:0000594
name: skeletal muscle satellite cell
namespace: cell
def: "An elongated, spindle-shaped, quiescent myoblast that are located between the basal lamina and the plasmalemma of the muscle fibres. They are thought to play a role in muscle repair and regeneration." [GOC:tfm, MESH:A.11.635.500.700]
is_a: CL:0000035 ! single fate stem cell
is_a: CL:0000188 ! skeletal muscle cell
is_a: CL:0000680 ! muscle precursor cell  *****

Note also the text def says that this is a (quiescent) myoblast, but the relationships say that it develops_from myoblast.

Original comment by: cmungall

**Comment by amyleerobinson** [comment]
What does it mean that "this is classified as a muscle precursor, but Al says this is not the case" ? Literally someone is running ML on cell classifications and it's learning how to improve ontologies?

**Comment by cmungall** [comment]
@amyleerobinson sorry only just noticed your comment now. In fact "Al" refers to a bloke called "Alistair", not an Artificial Intelligence!

We do use reasoners to classify ontologies, but these never learn (unfortunately), they just make inferences based on what you tell them and the logic of OWL.

In fact there are various approaches to automating and learning ontologies from data, text, etc. I think we are a long way from replacing human editors but if you're interested look up the work on Elyssa Chessler (ODE) and Trey Ideker (Nexo) for bioinformatics approaches, NELL for text-based and the work of Jens Lehmann's group on generalized class learning. I'm missing off a ton but that should get you started.

**Comment by paolaroncaglia** [comment]
Looks like @dosumis already edited as needed (https://github.com/obophenotype/cell-ontology/issues/384#issuecomment-112630091), so I'll close.
