### ISSUE TITLE
Innate Lymphoid Cells Terms

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#404]
Alex,
I have created terms for innate lymphoid cells, which is a relatively new term of which NK cells are now a child of (included in update; see attachment). Sorry for going old school and using obo-edit format instead of Protege.
Enjoy.
Dave

Original comment by: ddougall

**Comment by addiehl** [comment]
See note on #456 about the upper level terms.  I will add additional mouse and human specific terms later.

**Comment by nicolevasilevsky** [comment]
I think this can be closed. Please reopen if not.

**Comment by addiehl** [comment]
It's okay to close this, but I am currently developing a bunch of new terms for human ILC cell types for the HIPC project, for which I will create a new tracker entry.
