### ISSUE TITLE
follicular helper cell  populations

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#411]
While going through some of the cell population/marker names used by several HIPC centers, we came across the following ones which are not present in Cell Ontology. 

Cell Population                        Modifiers/Markers
T follicular helper 1 cell             CD3+, CD4+, CD8-, CXCR5+, CD45RA-, CXCR3+, CCR6-
T follicular helper 2 cell             CD3+, CD4+, CD8-, CXCR5+, CD45RA-, CXCR3-, CCR6-
T follicular helper 17 cell        CD3+, CD4+, CD8-, CXCR5+, CD45RA-, CXCR3-, CCR6+

We propose those cell populations to be added in Cell Ontology.

Original comment by: dsarantis

**Comment by nicolevasilevsky** [comment]
@addiehl do these terms still need to be added?
I can add them

**Comment by addiehl** [comment]
See my recent comments to #175.  I am going to add these in the coming week as part of a bunch of HIPC related term revisions.
