### ISSUE TITLE
NTR: midbrain dopaminergic neuron

### ISSUE THREAD

**Issue by rebeccafoulger** [obophenotype/cell-ontology#415]
Please could you create a new term:

midbrain dopaminergic neuron ; CL:NEW1
dopaminergic neuron (CL_0000700) and part_of some midbrain (UBERON_0001891)

And to match similar grouping terms, also:
neuron of the midbrain ; CL:NEW2
CNS neuron (sensu Vertebrata) (CL_0000117) and part_of some midbrain (UBERON_0001891)
child term: neuron of the substantia nigra ; CL_0002614

Thank you. I need them to create GO process terms in: https://github.com/geneontology/go-ontology/issues/12039

Thanks,
Rebecca

**Comment by cmungall** [comment]
Added via http://cl.termgenie.org/

ID: CL:2000097 Label: midbrain dopaminergic neuron

**Comment by rebeccafoulger** [comment]
Hi Chris- is there a release date for this term to be live in CL?
Thanks!
