### ISSUE TITLE
NTR:  Early & Late cortical thymocyte

### ISSUE THREAD

**Issue by avikdatta** [obophenotype/cell-ontology#416]
Label:  CD3-negative, CD4-positive, CD8-positive, double positive thymocyte
Synonyms: Early cortical thymocyte
is_a: CL:0000809 ! double-positive, alpha-beta thymocyte
Text definition: A double positive thymocyte with the phenotype CD3-negative, CD4-positive, CD8-positive
Definition source: PMID:    12086890 (http://www.ncbi.nlm.nih.gov/pubmed/12086890)

Label: CD3-positive, CD4-positive, CD8-positive, double positive thymocyte
Synonyms: Late cortical thymocyte
is_a: CL:0000809 ! double-positive, alpha-beta thymocyte
Text definition:  A double positive thymocyte with the phenotype CD3-positive, CD4-positive, CD8-positive
Definition source: PMID:    12086890 (http://www.ncbi.nlm.nih.gov/pubmed/12086890)

**Comment by avikdatta** [comment]
Hi, 

Please let me know if any further details are required for adding these ontology terms.

thanks
Avik

**Comment by addiehl** [comment]
Hi Avik,

Thank you for your term request, and sorry for the delay.

It seems you are basing your request on the schematic in Figure 3 of PMID:12086890.  This figure is a representation of thymocyte development based presumably on multiple sources, though poorly referenced.  None of the primary data for this figure is from this paper, and I suspect much of the understanding of thymocyte differentiation depicted in the figure is based on mouse data, although the paper itself is about human T cell acute lymphoblastic leukemia.

In looking at the first term you propose, I cannot use Figure 3 as evidence for this term, "CD3-negative, CD4-positive, CD8-positive, double positive thymocyte."  Figure 3 shows a "CD3 -/low, CD4+, CD8+ early cortical thymocyte.  A cell type cannot be both CD3-negative and CD3-low, which suggests that either more than one stage is being represented in the figure or that the authors are using CD3 -/low to indicate very low expression of CD3 in flow cytometry. This figure is not sufficient evidence that a CD3-negative (i.e. TCR negative) double positive thymocyte population exists.  If you can find a primary source with evidence for a CD3-negative, double positive cell type, please let me know.  The challenge is that CD3 is a component of the pre-TCR receptor containing a successfully recombined beta-chain and the invariant pre-TCR alpha chain, which is already present in the DN3/DN4 stage, and replaced by the alpha-beta TCR in the initial DP stage.  So I am dubious that a CD3-negative DP-thymocyte actually exists.

Furthermore, the proposed cell type cannot be placed as a child of CL:0000809 ! double-positive, alpha-beta thymocyte.  CL:0000809 ! double-positive, alpha-beta thymocyte is logically defined as having an 'alpha-beta T cell receptor complex', and  'alpha-beta T cell receptor complex' is a type of  'T cell receptor complex', and 'T cell receptor complex' is logically defined with has_part some 'CD3 episilon'.  CD3 (CD3 epsilon) is used by immunologists as a proxy for the TCR, typically interpreted as the abTCR in most experimental contexts, so the CL:0000809 ! double-positive, alpha-beta thymocyte cell type necessarily bears CD3, as would any subtype.

In looking at your second term, CD3-positive, CD4-positive, CD8-positive, double positive thymocyte, in fact this term is already logically equivalent to its proposed parent term, CL:0000809 ! double-positive, alpha-beta thymocyte, per the logic in the previous paragraph, i.e. CL:0000809 already has_part CD3 epsilon, which a DL query in Protege verifies.

My solution for this second term is to add the broad synonym 'late cortical thymocyte' to CL:0000809.  I will also add 'early cortical thymocyte' as a broad synonym to the CL terms for DN3 and DN4 (CL:0000807 and CL:0000808).

Sorry to be so negative,
Alex

**Comment by addiehl** [comment]
Synonyms 'early cortical thymocyte' and 'late cortical thymocyte' added as described above.

**Comment by avikdatta** [comment]
Dear Alex,

Thanks for assigning these two cell types to the correct ontology terms.

regards
Avik
