### ISSUE TITLE
NTR: fibroblast of breast

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#422]
label: fibroblast of breast
definition: A fibroblast that is part of the breast.
part_of: UBERON_0000310 (breast)
is_a: CL_0000057 (fibroblast)

**Comment by bonitalam** [comment]
Could we get an update on this term? 

We would also like to request something else similarly:

label: fibroblast of skin of scalp
definition: A fibroblast that is part of the skin of scalp.
part_of: UBERON_8300000 (skin of scalp)
is_a: CL_0000057

Thanks for your help!

**Comment by bonitalam** [comment]
Created a PR https://github.com/obophenotype/cell-ontology/pull/773
