### ISSUE TITLE
NTR: cortex-derived neurosphere

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#424]
label: cortex-derived neurosphere
definition: Neurosphere culture cells derived from stem cells from the cerebral cortex.
is_a: neurosphere (CL term pending ticket #423)
develops_from: UBERON_0001851 (cortex)
reference: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2821778/

**Comment by addiehl** [comment]
Closed.  See comment to #423.
