### ISSUE TITLE
NTR: ganglionic eminence-derived neurosphere

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#425]
label: ganglionic eminence-derived neurosphere
definition: Neurosphere culture cells derived from stem cells from the medial ganglionic eminence.
is_a: neurosphere (CL term pending ticket #423)
develops_from: UBERON_0004023 (ganglionic eminence)
reference: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2933789/

**Comment by addiehl** [comment]
Closed.  See comment to #423.
