### ISSUE TITLE
no def for: acid secreting cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#427]
http://purl.obolibrary.org/obo/CL_0000161

has logical but no natural language def

This is an old class. I'm wondering if it was intended originally in the sense of gastric acids. Is the grouping according to current logic useful?

**Comment by bvarner-ebi** [comment]
Unless there are concerns, I propose the following:

- [ ] post a message on #cl-editors and #cl slack channels with intent to obsolete 'acid secreting cell'. If no objections after a week, obsolete the term.

- [ ] add SubClass Of `'secretory cell'`
 and SubClass Of `'capable of' some 'acid secretion'` to 'parietal cell'

**Comment by dosumis** [comment]
see also https://github.com/obophenotype/cell-ontology/issues/2095

**Comment by dosumis** [comment]
Given the  usage of CellXGene I would suggest adding replaced_by axiom to link this to parietal cell.
