### ISSUE TITLE
monocyte is_a mononuclear cell

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#428]
mononuclear cell: "A leukocyte with a single non-segmented nucleus in the mature form."

monocyte:  "Myeloid mononuclear recirculating leukocyte that can act as a precursor of tissue macrophages, osteoclasts and some populations of tissue dendritic cells."^^xsd:string

https://en.wikipedia.org/wiki/Monocyte has:
"Monocytes have unilobar nuclei, which makes them one of the types of mononuclear leukocytes."

* should mononuclear cell have synonym (or perhaps label) 'mononuclear leukocyte'?
* should monocyte be a subclass of mononuclear leukocyte?

If the answer to either of these questions is no, then presumably 'mononuclear cell' needs a better, more extensive definition.

geneontology/go-ontology#10840

**Comment by addiehl** [comment]
Fixed.

Added axiom to monocyte so inferred to be type of mononuclear cell.
Added synonym mononuclear leukocyte to mononuclear cell.

-- Alex
