### ISSUE TITLE
New Term: Neural Crest Cell

### ISSUE THREAD

**Issue by ybradford** [obophenotype/cell-ontology#431]
New term:
Neural crest cell
Def: A cell of the neural crest. Neural crest cells are multipotent and develop from cells found at the neural plate boarder. Premigratory neural crest cells are found at the neural plate boarder and will undergo ectomesynchymal transition and delamination to form migratory neural crest cells.
Is_a embryonic cell CL_0002321
is_a multipotent cell CL_0000048
Part of some neural crest UBERON_0002342
Has parts: migratory neural crest cell CL_0000333; premigratory neural crest cell CL_0007004

**Comment by ybradford** [comment]
edit def to: 
A cell of the neural crest. Neural crest cells are multipotent. Premigratory neural crest cells are found at the neural plate boarder and will undergo ectomesynchymal transition and delamination to form migratory neural crest cells.
@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
added new term CL_0011012
