### ISSUE TITLE
CL:0000598 pyramidal cell, part_of relationship

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#435]
CL:0000598
pyramidal cell
Pyramidal neurons have a pyramid-shaped soma with the apex and an apical dendrite pointed toward the pial surface and other dendrites and an axon emerging from the base. The axons may have local collaterals but also project outside their region. Pyramidal neurons are found in the cerebral cortex, the hippocampus, and the amygdala. [database_cross_reference: GOC:tfm][database_cross_reference: MESH:A08.186.211.577.405.700]

This term is missing part_of relationships
-part_of some cerebral cortex (UBERON:0000956)
-part_of some Ammon's horn (UBERON:0001954)
-part_of some amygdala (UBERON:0001876)

**Comment by ybradford** [comment]
The part of relationships have to be true for all instances of that cell type. To deal with the various locations, a new term 'cerebral cortex pyramidal neuron' can be created with child sister classes: 'hippocampal pyramidal neuron', 'Meynert cell' (with an updated term def.), 'primary motor cortex pyramidal cell', and new term ' amygdala pyramidal cell'.

**Comment by jahilton** [comment]
That sounds like a great plan. Thank you

**Comment by bonitalam** [comment]
Hello, would it be possible to add a part_of relationship to brain (UBERON:0000955)?

**Comment by shawntanzk** [comment]
made a mistake and accidentally commit to master instead of a branch >.< reopening
