### ISSUE TITLE
Please revise CL:0000019 ‘sperm’

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#437]
Currently, CL:0000019 ‘sperm’ is_a ‘ciliated cell’ and a descendant of ‘animal cell’. This works well to represent typical mammalian sperm. However, there may be a need for broader coverage. For instance, the worm C. elegans has amoeboid sperm (and some crustaceans may also have non-flagellated sperm); and some gymnosperm plants have flagellated and motile sperm cells (http://www.ncbi.nlm.nih.gov/pubmed/16736257). As CL:0000019 ‘sperm’ seems to be the only occurrence of mature male germ cell in CL, some GO editors and curators suggest that more terms are added, removing the assumptions that all sperms are ciliated AND belong to animals. 

Here’s a suggestion from @krchristie:

“…it might be good if we could use a CL term that is less restrictive to Metazoa, but not because of crustaceans that have sperm without flagella, but because of gymnosperms that do have flagellated sperm. If it is possible to use a more general term that would allow for any flagellated/ciliated cell, I think that would be better. Basically, I think that the CL term xref for "flagellated sperm motility" [the GO term we’re discussing in this ticket https://github.com/geneontology/go-ontology/issues/10905] should be to a term with as broad a taxonomic range as possible since the presence of cilia/flagella seems to be very ancient. However, if the CL doesn't go to a level that makes that possible, I am OK with a less general term, though at some point in the future if GO expands its mandate for organismal coverage, we might need to use a more general term.”

Thanks,

Paola

**Comment by krchristie** [comment]
Perhaps also worth knowing that angiosperms have (non-flagellated) non-motile sperm. [Dresselhaus et al. 2016. Fertilization Mechanisms in Flowering Plants (PMID:26859271)]

**Comment by cmungall** [comment]
Choices are:

 * name classes (e.g. sperm, ciliated sperm, amoeboid sperm)
 * taxon GCIs - see https://github.com/obophenotype/uberon/wiki/Evolutionary-variability-GCIs

**Comment by paolaroncaglia** [comment]
Note for self: if and when CL revises their ‘sperm’ branch, GO may adjust/add cross-references to ‘sperm motility’ terms, see https://github.com/geneontology/go-ontology/issues/10905#issuecomment-228016749.

**Comment by dosumis** [comment]
This was fixed:

![image](https://user-images.githubusercontent.com/112839/94294665-10115e00-ff58-11ea-8580-3fd341e662c7.png)

#655 
#587
