### ISSUE TITLE
Fix capitalization

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#438]
https://github.com/cmungall/capital-offence/issues/1
# To be capitalized
## lieberkuhn
- [CL:0002250](http://purl.obolibrary.org/obo/CL_0002250) ! intestinal crypt stem cell [SYNONYM: "stem cell of intestinal crypt of  **lieberkuhn** " (exact)]
- [CL:1000338](http://purl.obolibrary.org/obo/CL_1000338) ! enterocyte of epithelium of crypt of  **lieberkuhn**  of small intestine
- [CL:1000345](http://purl.obolibrary.org/obo/CL_1000345) ! paneth cell of epithelium of crypt of  **lieberkuhn**  of small intestine
- [UBERON:0001241](http://purl.obolibrary.org/obo/UBERON_0001241) ! crypt of Lieberkuhn of small intestine [SYNONYM: "crypt of  **lieberkuhn**  of small bowel" (exact)] [SYNONYM: "crypt of  **lieberkuhn**  of small intestine" (exact)] [SYNONYM: "intestinal gland of small bowel" (exact)] [SYNONYM: "intestinal gland of small intestine" (exact)] [SYNONYM: " **lieberkuhn**  crypt of small bowel" (exact)] [SYNONYM: " **lieberkuhn**  crypt of small intestine" (exact)] [SYNONYM: "small bowel crypt of  **lieberkuhn** " (exact)] [SYNONYM: "small bowel intestinal gland" (exact)] [SYNONYM: "small bowel  **lieberkuhn**  crypt" (exact)] [SYNONYM: "small intestinal crypt of Lieberkuhn" (exact)] [SYNONYM: "small intestine crypt of Lieberkuhn" (exact)] [SYNONYM: "small intestine crypt of  **lieberkuhn** " (exact)] [SYNONYM: "small intestine intestinal gland" (exact)] [SYNONYM: "small intestine  **lieberkuhn**  crypt" (exact)]
- [UBERON:0001983](http://purl.obolibrary.org/obo/UBERON_0001983) ! crypt of Lieberkuhn [SYNONYM: "crypt of  **lieberkuhn** " (exact)] [SYNONYM: "crypt of LieberkC<hn" (exact)] [SYNONYM: "crypts of LieberkC<hn" (exact)] [SYNONYM: "follicles of  **lieberkuhn** " (exact)] [SYNONYM: "intestinal crypt" (exact)] [SYNONYM: "intestinal crypts" (exact)] [SYNONYM: "intestinal gland" (broad)] [SYNONYM: "intestinal gland of Lieberkuhn" (related)] [SYNONYM: "Lieberkuhn crypt" (exact)] [SYNONYM: " **lieberkuhn**  crypt" (exact)] [SYNONYM: "Lieberkuhn gland" (exact)] [SYNONYM: "Lieberkuhn's gland" (exact)] [SYNONYM: "Lieberkuhn's glands" (exact)]
- [UBERON:0001984](http://purl.obolibrary.org/obo/UBERON_0001984) ! crypt of Lieberkuhn of large intestine [SYNONYM: "intestinal gland of large intestine" (exact)] [SYNONYM: "large intestinal crypt of  **lieberkuhn** " (exact)] [SYNONYM: "large intestine crypt of  **lieberkuhn** " (exact)] [SYNONYM: "large intestine intestinal gland" (exact)] [SYNONYM: "large intestine  **lieberkuhn**  crypt" (exact)] [SYNONYM: " **lieberkuhn**  crypt of large intestine" (exact)]
- [UBERON:0013485](http://purl.obolibrary.org/obo/UBERON_0013485) ! crypt of Lieberkuhn of colon [SYNONYM: "colonic crypt" (exact)] [SYNONYM: "colonic crypt of  **lieberkuhn** " (exact)]
- [UBERON:0013486](http://purl.obolibrary.org/obo/UBERON_0013486) ! crypt of Lieberkuhn of appendix [SYNONYM: "appendiceal crypt" (exact)] [SYNONYM: "appendiceal crypt of  **lieberkuhn** " (exact)]
## henle
- [CL:1000909](http://purl.obolibrary.org/obo/CL_1000909) ! kidney loop of  **henle**  epithelial cell
- [CL:1001016](http://purl.obolibrary.org/obo/CL_1001016) ! kidney loop of  **henle**  ascending limb epithelial cell
- [CL:1001021](http://purl.obolibrary.org/obo/CL_1001021) ! kidney loop of  **henle**  descending limb epithelial cell
- [CL:1001106](http://purl.obolibrary.org/obo/CL_1001106) ! kidney loop of  **henle**  thick ascending limb epithelial cell
- [CL:1001107](http://purl.obolibrary.org/obo/CL_1001107) ! kidney loop of  **henle**  thin ascending limb epithelial cell
- [CL:1001108](http://purl.obolibrary.org/obo/CL_1001108) ! kidney loop of  **henle**  medullary thick ascending limb epithelial cell
- [CL:1001109](http://purl.obolibrary.org/obo/CL_1001109) ! kidney loop of  **henle**  cortical thick ascending limb epithelial cell
- [CL:1001111](http://purl.obolibrary.org/obo/CL_1001111) ! kidney loop of  **henle**  thin descending limb epithelial cell
- [UBERON:0001288](http://purl.obolibrary.org/obo/UBERON_0001288) ! loop of Henle [SYNONYM: "ansa nephroni" (exact)] [SYNONYM: "Henle loop" (exact)] [SYNONYM: " **henle** 's loop" (exact)]
- [UBERON:0003455](http://purl.obolibrary.org/obo/UBERON_0003455) ! inner renal medulla loop of  **henle**  [SYNONYM: "Henle loop of inner medulla of kidney" (exact)] [SYNONYM: "Henle loop of inner renal medulla" (exact)] [SYNONYM: "Henle loop of inner zone of medulla of kidney" (exact)] [SYNONYM: "Henle loop of inner zone of renal medulla" (exact)] [SYNONYM: " **henle** 's loop of inner medulla of kidney" (exact)] [SYNONYM: " **henle** 's loop of inner renal medulla" (exact)] [SYNONYM: " **henle** 's loop of inner zone of medulla of kidney" (exact)] [SYNONYM: " **henle** 's loop of inner zone of renal medulla" (exact)] [SYNONYM: "inner medulla of kidney Henle loop" (exact)] [SYNONYM: "inner medulla of kidney  **henle** 's loop" (exact)] [SYNONYM: "inner medulla of kidney loop of Henle" (exact)] [SYNONYM: "inner renal medulla Henle loop" (exact)] [SYNONYM: "inner renal medulla  **henle** 's loop" (exact)] [SYNONYM: "inner renal medulla loop of Henle" (exact)] [SYNONYM: "inner zone of medulla of kidney Henle loop" (exact)] [SYNONYM: "inner zone of medulla of kidney  **henle** 's loop" (exact)] [SYNONYM: "inner zone of medulla of kidney loop of Henle" (exact)] [SYNONYM: "inner zone of renal medulla Henle loop" (exact)] [SYNONYM: "inner zone of renal medulla  **henle** 's loop" (exact)] [SYNONYM: "inner zone of renal medulla loop of Henle" (exact)] [SYNONYM: "kidney inner medulla loop of  **henle** " (exact)] [SYNONYM: "loop of Henle of inner medulla of kidney" (exact)] [SYNONYM: "loop of Henle of inner renal medulla" (exact)] [SYNONYM: "loop of Henle of inner zone of medulla of kidney" (exact)] [SYNONYM: "loop of Henle of inner zone of renal medulla" (exact)]
- [UBERON:0005096](http://purl.obolibrary.org/obo/UBERON_0005096) ! descending thin limb [SYNONYM: "descending limb of  **henle** %27s loop" (related)] [SYNONYM: "descending limb of loop of  **henle** " (related)] [SYNONYM: "descending thin limb of loop of Henle" (exact)] [SYNONYM: "loop of Henle descending thin limb" (exact)] [SYNONYM: "loop of  **henle**  thin descending limb" (exact)] [SYNONYM: "pars descendens (tubulus attenuatus)" (exact)] [SYNONYM: "thin descending limb" (exact)] [SYNONYM: "thin descending limb of loop of  **henle** " (related)] [SYNONYM: "thin descending limb of the loop of  **henle** " (related)] [SYNONYM: "thin descending loop of  **henle** " (related)]
- [UBERON:0006541](http://purl.obolibrary.org/obo/UBERON_0006541) ! outer medulla inner stripe loop of  **henle** 
- [UBERON:0006542](http://purl.obolibrary.org/obo/UBERON_0006542) ! outer medulla outer stripe loop of  **henle** 
- [UBERON:0034996](http://purl.obolibrary.org/obo/UBERON_0034996) ! outer renal medulla loop of  **henle**  [SYNONYM: "loop of Henle, outer medullary portion" (exact)]
- [UBERON:0034997](http://purl.obolibrary.org/obo/UBERON_0034997) ! renal medulla loop of  **henle**  [SYNONYM: "loop of Henle of renal medulla" (exact)] [SYNONYM: "loop of Henle, medullary portion" (exact)]
## Lugaro
- [CL:0011006](http://purl.obolibrary.org/obo/CL_0011006) !  **lugaro**  cell [SYNONYM: "Lugaro cell" (exact)]
## Purkinje
- [CL:1000376](http://purl.obolibrary.org/obo/CL_1000376) !  **purkinje**  myocyte of interventricular septum
  - [CL:1000479](http://purl.obolibrary.org/obo/CL_1000479) !  **purkinje**  myocyte of atrioventricular node
  - [CL:1000483](http://purl.obolibrary.org/obo/CL_1000483) !  **purkinje**  myocyte of internodal tract
  - [CL:1000484](http://purl.obolibrary.org/obo/CL_1000484) !  **purkinje**  myocyte of atrioventricular bundle
## Peyer
- [CL:1000411](http://purl.obolibrary.org/obo/CL_1000411) ! endothelial cell of  **peyer** 's patch
- [UBERON:0004693](http://purl.obolibrary.org/obo/UBERON_0004693) ! Peyer's patch epithelium [SYNONYM: " **peyer** 's patch epithelium" (exact)]
- [UBERON:0010386](http://purl.obolibrary.org/obo/UBERON_0010386) ! Peyer's patch follicle [SYNONYM: " **peyer** 's patch follicle" (exact)]

**Comment by nicolevasilevsky** [comment]
I can fix these manually, does that work?

**Comment by cmungall** [comment]
Go for it - I assume you will just do in a text editor?

obv. the uberon ones will be fixed at src

**Comment by nicolevasilevsky** [comment]
Do you just want the labels to have proper capitalization? So the synonym in the first example would be 'stem cell of intestinal crypt of Lieberkuhn' 

I would just do this in Protege, right?

**Comment by cmungall** [comment]
On 6 Sep 2016, at 14:10, nicolevasilevsky wrote:

> Do you just want the labels to have proper capitalization? So the 
> synonym in the first example would be 'stem cell of intestinal crypt 
> of Lieberkuhn'

labels and synonyms, and yes that's the correct capitalization for the 
synonym

> I would just do this in Protege, right?

if that's the way you really want to do it. I mean this is designed so 
that we can just run the script to do it but I won't have time to do it

**Comment by nicolevasilevsky** [comment]
Ah, I see. I can just fix it via Protege, it shouldn't take me too long.

**Comment by nicolevasilevsky** [comment]
I fixed all the CL terms except 
CL:0011006 ! lugaro cell [SYNONYM: "Lugaro cell" (exact)]

If I change the label to Lugaro cell, it will then match the synonym. Should I do that and remove the synonym?

**Comment by cmungall** [comment]
Yes, remove it

**Comment by paolaroncaglia** [comment]
A handful of cases of capitalization still need to be fixed, I'll address. Findable by searching the following in Protege with "Case sensitive" checkbox:
lieberkuhn
peyer
