### ISSUE TITLE
Update definition for CL:0000038

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#44]
```

Update definition for term CL:0000038, “erythroid progenitor cell” to 
remove mention of ter119 marker. Ter119 marker is too specific at this level 
and children can either be Ter119+ or Ter119-
```

Original issue reported on code.google.com by `vmall...@stanford.edu` on 15 May 2013 at 10:01

**Comment by paolaroncaglia** [comment]
> Update definition for term CL:0000038, “erythroid progenitor cell” to 
> remove mention of ter119 marker. Ter119 marker is too specific at this level 
> and children can either be Ter119+ or Ter119-
> 
> Original issue reported on code.google.com by `vmall...@stanford.edu` on 15 May 2013 at 10:01

CL:0000038 “erythroid progenitor cell” is currently defined as "A progenitor cell committed to the erythroid lineage." and there's no mention of Ter119 in any of its annotations or axioms, so I'll close.
