### ISSUE TITLE
Adrenal medulla chromaffin cell infered hierachy

### ISSUE THREAD

**Issue by cerivs** [obophenotype/cell-ontology#442]
The reasoner should make this an is_a  child of endocrine cell it doesn't.  Need to investigate why this is happening.
 This is a problem that was found when we fixed issue #439

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/18680100/235319ec-7f17-11e6-91c8-d47f4554cec8.png)

**Comment by cerivs** [comment]
Not really a problem.

**Comment by cmungall** [comment]
<img width="1211" alt="screen shot 2016-09-20 at 9 45 44 am" src="https://cloud.githubusercontent.com/assets/50745/18680115/35759e6a-7f17-11e6-9c6d-f4894062cc76.png">

**Comment by cmungall** [comment]
We would like this to be inferred based on properties of the cells, but this is a universal issue across CL...
