### ISSUE TITLE
NTR: innate lymphoid cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#449]
Spits, H., Artis, D., Colonna, M., Diefenbach, A., Di Santo, J. P., Eberl, G., … Vivier, E. (2013). Innate lymphoid cells--a proposal for uniform nomenclature. Nature Reviews. Immunology, 13(2), 145–9. doi:10.1038/nri3365

Definition adapted from paper:

An immune cell characterized by the absence of recombination activating gene (RAG)-dependent rearranged antigen receptors; a lack of myeloid cell and dendritic cell phenotypical markers; and their lymphoid morphology

They propose as subclasses NK cells (currently directly under lymphocyte), and LTi cells (not yet in CL)

They also propose ILC1, ILC2 and ILC3 cell types (defined by cytokine production), as well as an ILC precursor/progenitor cell

table 1 has phenotypic markers for the mouse subset

**Comment by cmungall** [comment]
progenitor cells (ILCP) purported to be identified here:
http://www.nature.com/doifinder/10.1038/nature20105

**Comment by simondharding** [comment]
Has there been any progress on adding innate lymphoid cells to the ontology? We are currently using the ontology as part of an extension to the Guide to PHARMACOLOGY (www.guidetopharmacology.org) called the Guide to IMMUNOPHARMACOLOGY. As such we are annotating target proteins with cell types they function in, which includes innate lymphoid cells. Can we be of any support in get these terms defined and incorporated?

**Comment by addiehl** [comment]
I added group 1, 2, and 3 ILC to the CL-edit file on January 30 and 31, 2017.  They will be present in the next public release of the CL.  See #456 and #404.  I am planning still to add species-specific subtypes, but the upper level ILC terms are good to go.

-- Alex

**Comment by cmungall** [comment]
Thanks @addiehl - btw you can close tickets or reference them in your commit message by preceding the number with a hash symbol
