### ISSUE TITLE
Update label for CL:0002000

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#45]
```

Update label for CL:0002000 to be “c- Kit-positive erythroid progenitor 
cell” which is how it is seen in literature. 
```

Original issue reported on code.google.com by `vmall...@stanford.edu` on 15 May 2013 at 10:02

**Comment by addiehl** [comment]
'c- Kit-positive erythroid progenitor cell' exists as an exact synonym.  Won't fix.
