### ISSUE TITLE
cycle between band form neutrophil relationship and mature neutrophil

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#453]
Cycle:

 * [mature neutrophil](http://purl.obolibrary.org/obo/CL_0000096) develops_from: "band form neutrophil"
 * [band form neutrophil](http://purl.obolibrary.org/obo/CL_0000560) subClassOf: "mature neutrophil"

This is not coherent, unless develops_from is reflexive, or band form neutrophils have existed for all of time...

This is preventing the uberon release, as we can't make a basic ontology (basic ontologies have no cycles in the graph).

**Comment by cmungall** [comment]
Protege seems to hang when trying to open cl-edit -- I wonder if this is the reason?

**Comment by addiehl** [comment]
Thanks Chris.
