### ISSUE TITLE
innate lymphoid cell

### ISSUE THREAD

**Issue by nnouspikel** [obophenotype/cell-ontology#456]
Dear CL biocurators,

I am annotating the innate immune response and would need new CL terms for innate lymphoid cells as following:

- Parent term: innate lymphoid cells as a child of lymphocyte CL_0000542
Definition:
Innate lymphocytes that are relatively rare in comparison to adaptive lymphocytes in lymphoid tissues, but they are enriched at barrier surfaces of the mammalian body, such as the skin, lung and intestine, as well as in adipose and some mucosal-associated lymphoid tissues; can be identified by expression of the common gamma chain (γc, CD132), IL-7Rα (CD127), IL-2Rα (CD25), and Thy1 (CD90) markers; respond to cytokine and microbial signals and are potent innate cellular sources of multiple pro-inflammatory and immunoregulatory cytokines
develops from: common lymphoid progenitors; development of ILCs from common lymphoid progenitors occurs independently of somatic recombination

- Children terms:
Child term 1: Group 1 innate lymphoid cell (NK cell is a child of Group 1 innate lymphoid cell)
Child term 2: Group 2 innate lymphoid cell
Child term 3: Group 3 innate lymphoid cell
Definition: Group 1 ILCs (ILC1s) respond to IL-12, constitutively express T-bet, and produce effector cytokines including interferon (IFN)-γ and tumor necrosis factor (TNF); conventional NK cells are a subset of ILC1
Definition: Group 2 ILCs (ILC2s) respond to the cytokines IL-25, IL-33 and TSLP; constitutively express high levels of GATA3; and produce the effector cytokines IL-4, IL-5, IL-9, IL-13 and amphiregulin2
Definition: Group 3 ILCs (ILC3s) respond to IL-1β, IL-6 and IL-23; constitutively express RORγt; and produce the effector cytokines IL-17 and/or IL-22

These names and definitions are based on review PMID:26121198. If you have other suggestions, please feel free to let me know.

Many thanks for your help,
Nevila Hyka-Nouspikel

**Comment by nnouspikel** [comment]
Hello,

Did you have a chance to review these new terms? Please let me know if I can help to speed up the process.

All the best for 2017! 
Nevila Hyka-Nouspikel

**Comment by addiehl** [comment]
I have added the following terms, based on the work of David S. Dougall, from issue #404, with additional information taken from your help above and my own additional research:

innate lymphoid cell = http://purl.obolibrary.org/obo/CL_0001065
group 1 innate lymphoid cell = http://purl.obolibrary.org/obo/CL_0001067
ILC1 = http://purl.obolibrary.org/obo/CL_0001068
group 2 innate lymphoid cell = http://purl.obolibrary.org/obo/CL_0001069
group 3 innate lymphoid cell = http://purl.obolibrary.org/obo/CL_0001071

Note that I will add your initials (Nevila) to the new terms, assuming they should be noted as GOC:nhn.  Please let me know if this is correct.

I also moved 'natural killer cell' under 'group 1 innate lymphoid cell' and moved and renamed the former 'nuocyte' term (CL_0002089) to 'group 2 innate lymphoid cell, mouse' based on the markers used in the logical definition and the literature cited, which was a mouse paper.

These additions and changes will appear in the next public version of the Cell Ontology.

I intend to add more terms for mouse and human subtypes of these terms, with appropriate marker lists, when I get more time.

-- Alex

**Comment by nnouspikel** [comment]
Thank you so much Alex!

I noticed that there are two new terms for Group 1 ILC:
group 1 innate lymphoid cell = http://purl.obolibrary.org/obo/CL_0001067 
= ILC1 = http://purl.obolibrary.org/obo/CL_0001068
We need to keep only one of them, don't you think?

It's ok to put my initials.

All the best,

Nevila

**Comment by addiehl** [comment]
Hi Nevila,

Per PMID:23348417, which proposed the now accepted nomenclature for ILCs, Group 1 ILC is a class composed of NK cells (T-bet+, EOMES+, generally cytotoxic) and ILC1 cells (T-bet+, EOMES-, non-cytotoxic).  Both these subtypes of Group 1 ILCs can release type I cytokines (IFN-gamma, IL-12, IL-18), but differ in their potential for cytoxicity.
--Alex

**Comment by nnouspikel** [comment]
Hi Alex,

You're right. Fig 1 clearly shows that ILC1 is part of group 1 ILCs.

Thank you very much,

Nevila
