### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by markwoon** [obophenotype/cell-ontology#462]
Any chance of a new release soon?

I could roll my own from the repo, but the build is broken...

**Comment by addiehl** [comment]
Hi Chris, can we make a new release of CL soon? @cmungall 
Thanks

**Comment by cmungall** [comment]
travis build is failing, need to fix that first. at a meeting. will try and look later

@addiehl I also not there are lots of rdfs:comment on axiom annotations - we use xref otherwise we get

```
+def: "An innate lymphoid cell that is capable of producing T-helper 2-cell associated cytokines upon stimulation." [] {comment="PMID:23292121", comment="PMID:23562755", comment
```

in the .obo

**Comment by cmungall** [comment]
https://github.com/obophenotype/cell-ontology/releases/tag/v2017-04-14
