### ISSUE TITLE
NTR: cardiac muscle progenitor cell

### ISSUE THREAD

**Issue by rachhuntley** [obophenotype/cell-ontology#475]
Hi,

Is it possible to have a new term "cardiac muscle progenitor cell" (synonym "cardiomyocyte progenitor cell")?
It seems this is not the same as "fetal cardiomyocyte", since these progenitor cells are also found in adults (https://www.ncbi.nlm.nih.gov/pubmed/12387899).

I'd like this term so I can request a GO term for cardiac muscle progenitor cell proliferation for annotation of this article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4632798/

(Note, there is an existing GO term  GO:0003261 cardiac muscle progenitor cell migration to the midline involved in heart field formation.)

Thanks,
Rachael.

**Comment by rachhuntley** [comment]
OK, I think the cell type I need is "cardiac muscle myoblast", which already exists. I was running into problems finding this due to lack of synonyms "cardiac muscle progenitor cell" or "cardiomyocyte progenitor cell".
Could these please be added?

**Comment by nicolevasilevsky** [comment]
I added these synonyms
