### ISSUE TITLE
NTR: IMR-90 cell

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#476]
The ENCODE project is requesting a new term for IMR-90 cells...

label: IMR-90 cell
synonyms: IMR-90, IMR90, IMR90 cell
text definition: Normal lung fibroblast cell line from a human female. The human diploid fibroblast strain IMR-90 was derived by W.W. Nichols and associates from the lungs of a 16-week female fetus.
part_of: lung [UBERON:0002048]
is_a: lung fibroblast [CL:0002553]
reference: https://www.atcc.org/Products/All/CCL-186.aspx

Thank you!

**Comment by addiehl** [comment]
Cell lines are handled by the Cell Ontology Ontology, where a class for this cell already exists:
http://purl.obolibrary.org/obo/CLO_0006951

I recommend you use the CLO class for your purposes.
Thanks,
Alex
