### ISSUE TITLE
NTR: HFF-Myc

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#477]
For the ENCODE project...

label: HFF-Myc
synonyms: HFF-cMyc
text definition: A foreskin fibroblast cell expressing canine cMyc.
part_of: prepuce of penis [UBERON:0001332]
is_a: foreskin fibroblast [CL:1001608]
reference: https://www.encodeproject.org/documents/265c52a9-abeb-49f6-9aeb-ecd8e190f4eb/@@download/attachment/HFFMyc_Stam_protocol.pdf

Thank you!

**Comment by paolaroncaglia** [comment]
The term HFF-Myc is in EFO as EFO:0005710, and I suspect it was added there because genetically modified cells would be out of scope for CL, but this ticket was never updated (and I can't find any reference to this term request in the EFO tracker - possibly too old). I'll close.
