### ISSUE TITLE
NTR: annulus fibrosus cell

### ISSUE THREAD

**Issue by jahilton** [obophenotype/cell-ontology#478]
For the ENCODE project...

label: annulus fibrosus cell
text definition: A cell isolated from the annulus fibrosus of human intervertebral disc.
part_of: annulus fibrosus [UBERON:0006444]
is_a: connective tissue cell [CL:0002320]
reference: https://www.sciencellonline.com/products-services/primary-cells/human-annulus-fibrosus-cells.html

Thank you!

**Comment by paolaroncaglia** [comment]
CL:0002602 'annulus pulposus cell' exists and is equivalent to
'connective tissue cell' and ('part of' some 'annulus fibrosus disci intervertebralis')
which fits with this request based on the proposed definition. I'll close.
