### ISSUE TITLE
CI Job for CL?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#485]
Is there a CI job for CL? On the [ReadMe](https://github.com/obophenotype/cell-ontology/blob/master/src/ontology/README-editors.txt) it says to check the build here:  http://build.berkeleybop.org/job/build-cl/ but it looks like this has been disabled.

**Comment by cmungall** [comment]
Travis

**Comment by nicolevasilevsky** [comment]
Thanks!
