### ISSUE TITLE
Two term stanza do not have a name tag in the obo file

### ISSUE THREAD

**Issue by cmpich** [obophenotype/cell-ontology#497]
The following two term stanzas do not have a name tag but need one:

[Term]
id: UBERON:0005186
is_obsolete: true
replaced_by: UBERON:0004204

[Term]
id: UBERON:0005187
is_obsolete: true
replaced_by: UBERON:0004205

**Comment by addiehl** [comment]
I don't think this is an issue anymore.  These are obsolete terms and are not in the current CL obo files.
