### ISSUE TITLE
peripheral blood

### ISSUE THREAD

**Issue by tuli** [obophenotype/cell-ontology#499]
Please can you tell me which term I would use for 'peripheral blood'

**Comment by nicolevasilevsky** [comment]
Hi, can you give more context? There is:
CL_2000001 peripheral blood mononuclear cell
CL_0002246 peripheral blood stem cell

**Comment by tuli** [comment]
Hello,
Sorry, I thought this was the uberon git repo. My original question was to
uberon, but maybe I should curate blood as cell type rather than tissue
type.

Mary Ann

*Mary Ann Tuli*

Data Editor, GigaDB
GigaScience Journal, BGI-Hong Kong
Email: maryann@gigasciencejournal.com
ORCID: 0000-0002-4667-9528 <http://orcid.org/0000-0002-4667-9528>
Website: www.gigadb.org <http://gigadb.org/>

On Tue, Feb 27, 2018 at 4:15 PM, Nicole Vasilevsky <notifications@github.com

**Comment by addiehl** [comment]
Blood is not a cell type per se, but does contain a number of cell types in addition its not cellular components such as a variety of proteins, small molecules, and water.

The class 'blood' in Uberon is probably appropriate for your use, http://purl.obolibrary.org/obo/UBERON_0000178, although it has a surprisingly bad definition, mentioning only erythrocytes as a cell type component.

**Comment by addiehl** [comment]
Closing as I think this is resolved.
