### ISSUE TITLE
Fibro/adipogenic progenitors

### ISSUE THREAD

**Issue by Alessandro-Palma** [obophenotype/cell-ontology#500]
Hi,
I would like to request a new term for "fibro/adipogenic progenitors". 
These are tissue-resident mesenchymal cells, important for skeletal muscle regeneration, being able to differentiate into both adipocytes or fibroblasts.
Here are some references:

- _Roles of nonmyogenic mesenchymal progenitors in pathogenesis and regeneration of skeletal muscle [PMC3932482](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3932482/)_
- _Fibrosis and adipogenesis originate from a common mesenchymal progenitor in skeletal muscle. [PMID:22045730](https://www.ncbi.nlm.nih.gov/pubmed/22045730)_
- Muscle injury activates resident fibro/adipogenic progenitors that facilitate myogenesis. [PMID:20081841](https://www.ncbi.nlm.nih.gov/pubmed/20081841)

Thanks.

**Comment by paolaroncaglia** [comment]
@Alessandro-Palma 
The term you requested is CL_0009099 (fibro/adipogenic progenitor cell); it will be available at the next CL release. Thank you for your patience.
