### ISSUE TITLE
KCD renal intercalated cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#513]
![image](https://user-images.githubusercontent.com/50745/43229637-5658f1d4-901a-11e8-95eb-0fb21bc87412.png)

This is a "bad smell" - we have one subtype of renal intercalated cell differentiated by region. 

An additional comment for KPMP folks it's also not useful to subtype renal intercalated cell by region at all

**Comment by bvarner-ebi** [comment]
> An additional comment for KPMP folks it's also not useful to subtype renal intercalated cell by region at all

With HuBMAP, several location-specific cell types have been requested and created.

<img width="423" alt="Screenshot 2022-08-09 at 12 14 48" src="https://user-images.githubusercontent.com/95643797/183634642-eb6e96bf-c44d-4d4a-950f-b820ce3a98cd.png">

@emquardokus, as the main liaison, do you have any comments on this?
If there is no comment on this ticket within the next few days, I plan to close this ticket.

**Comment by emquardokus** [comment]
@bvarner-ebi I was working directly with Sanjay Jain who is both HuBMAP and KPMP so I'm not sure where/who this newest comment came from? Sanjay added the cell types and KPMP usually rigorously discusses every new item.

**Comment by bvarner-ebi** [comment]
Thank you for the feedback, @emquardokus. Given your comment and since this ticket was opened in 2018 with no other activity, I will close it.
