### ISSUE TITLE
glomerular mesangial cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#515]
http://purl.obolibrary.org/obo/CL_1000742

"Intraglomerular mesangial cells are specialized pericytes located among the glomerular capillaries within a renal corpuscle of a kidney"

Change to "glomerular mesangial ..." to be consistent with label.

Add intraglom as syn

**Comment by bvarner-ebi** [comment]
[ ] Update text definition and add dbxref:

Current:
Intraglomerular mesangial cells are specialized pericytes located among the glomerular capillaries within a renal corpuscle of a kidney.

Proposed:
A specialized pericyte located among the glomerular capillaries in a renal corpuscle.
https://doi.org/10.1152/physrev.1998.78.3.723

[ ] Remove logical definition. All elements are already parent classes and parent cell type currently lacks text definition.

[x] "intraglomerular mesangial cell" is already an exact synonym
