### ISSUE TITLE
kidney interstitial cell subtypes

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#516]
![image](https://user-images.githubusercontent.com/50745/43230944-120b7f74-901f-11e8-9afa-61ba51c1d0e1.png)

 - we don't believe mesangial cell should be here
 - we think resident would be a goos grouping class

**Comment by bvarner-ebi** [comment]
Of note, here is the current modelling:

<img width="425" alt="Screenshot 2022-08-02 at 17 08 46" src="https://user-images.githubusercontent.com/95643797/182421641-b93a167d-d82a-4e0a-841c-f06a10172bea.png">

<img width="424" alt="Screenshot 2022-08-02 at 17 09 48" src="https://user-images.githubusercontent.com/95643797/182421858-0f50d143-2724-402f-ba50-1101f20ab871.png">

@cmungall, do you still see an issue with how the mesangial cell types are inferred? They are no longer asserted as 'kidney interstitial cell' subclasses.

**Comment by cmungall** [comment]
sorry, I don't have anything to add here, I made the issue when working with an expert at a KPMP meeting. If you are satisfied the biology is correct then you can close

**Comment by shawntanzk** [comment]
@bvarner-ebi - any follow up with this? thanks

**Comment by bvarner-ebi** [comment]
1. From [Kidney International, Vol. 39 (1991), pp. 370—381](https://doi.org/10.1038/ki.1991.49):
"The glomerular and the extraglomerular mesangium may be
considered to be special interstitia inasmuch as their cells are
embedded in abundant extracellular matrices, which communi-
cate with each other and (the latter) with the cortical interstitial
spaces."

mesangium is also asserted to be 'part of' some 'kidney interstitium' in CL.

2. If a new resident kidney cell class is warranted, kindly provide justification or reference(s) to support a new term request.

This ticket can be reopened or another ticket made if follow up is required for these points.
