### ISSUE TITLE
fibrocyte

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#517]
http://purl.obolibrary.org/obo/CL_0000135

Is this term still used? We think it should be obsoleted

**Comment by addiehl** [comment]
This class has multiple descendants.  Probably a more thorough review is called for.

**Comment by bvarner-ebi** [comment]
Checking in on this ticket from 2018. 
Unsure of context.

@cmungall, @addiehl- is there still reason to consider term obsoletion and further investigation?
If not, this ticket can be closed.

**Comment by bvarner-ebi** [comment]
Closing this ticket due to lack of activity.
If evidence is available to support obsoletion of CL:0000135 fibrocyte, please add and reopen the ticket.
