### ISSUE TITLE
Add taxon contraints on cell types 

### ISSUE THREAD

**Issue by pgaudet** [obophenotype/cell-ontology#524]
Hello, 

For the Gene ontology ticket: 
https://github.com/geneontology/go-ontology/issues/16108

We need taxon constraints for the following cell lines: 
* epithelial cell
* cardiac muscle cell 
* stem cell
*  leukocyte cell
*  erythrocyte 
*  leukocyte
* vascular smooth muscle cell
* bone marrow cell

Only in: metazoa, or more precise if you can. 

Thanks, Pascale and @valwood

**Comment by cmungall** [comment]
You should have constraints to metazoa already

 * epithelial cell part-of epithelium only_in Eumetazoa (@pfey03 disagrees with this)
 * cardiac muscle cell part-of primary circulatory organ only_in Bilateria
 * stem cell - https://en.wikipedia.org/wiki/Plant_stem_cell
 * vascular smooth muscle cell  - part of vasculature, inherit Bilateria from circulator system


## TODO

 * leukocyte - should have direct TC in CL
