### ISSUE TITLE
NTR: gonadal somatic cell

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/cell-ontology#525]
gonadal somatic cell, here a tentative definition:

def: "A somatic cell that is present in the gonad and enters into close association with the primordial germ cells to commit as germ cells."
synonym: "gonad somatic cell" EXACT []
synonym: "somatic stem cell of gonad" EXACT []
is_a: CL:0000034 ! stem cell
is_a: CL:0002371 ! somatic cell
is_a: CL:0000630 ! supportive cell
xref: FBbt:00006010

Three major somatic cell types (Sertoli cells, Leydig cells, and peritubular myoid cells) are identified in male gonad. Granulosa and theca cells are the female gonadal somatic cells
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2902374/

https://www.ncbi.nlm.nih.gov/pubmed/27300183

needed for scRNA-seq expression data annotation, see
https://www.ncbi.nlm.nih.gov//pubmed/26046443

**Comment by paolaroncaglia** [comment]
@ANiknejad (cc @gouttegd and @dosumis )
Is this term still needed, please? If so, perhaps one of my colleagues who are more experts on insects than me could add it, with a taxon constraint I guess. Thanks.

**Comment by bvarner-ebi** [comment]
@ANiknejad, following up on this ticket. Is this cell type still needed?

If so, can you clarify whether you are requesting a gonadal stem cell class or a class that would have the children 'Sertoli cell', 'Leydig cell', etc? I do not think these are considered stem cells.

**Comment by bvarner-ebi** [comment]
@ANiknejad, since there has been no reply on this ticket for 6 months, I will close it. Feel free to reopen if still needed.
