### ISSUE TITLE
Add edges from CL:0001035 and CL:0000066  to CL:0002371

### ISSUE THREAD

**Issue by mbernste** [obophenotype/cell-ontology#530]
I believe the following cell type terms should have CL:0002371 (somatic cell) in their ancestral terms:
CL:0001035 (bone cell)
CL:0000066 (epithelial cell)

**Comment by paolaroncaglia** [comment]
I will close this ticket as a duplicate because 'somatic cell' and its incomplete classification are under discussion in [this other ticket](https://github.com/obophenotype/cell-ontology/issues/1150). Thanks.
