### ISSUE TITLE
Refactor cell ontology build pipeline to use ODK

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#533]

**Comment by matentzn** [comment]
This is on my wider agenda, but not a super high priority. Note that currently the pattern pipeline is broken in the ODK, that needs to be fixed first before we roll out ODKs with pattern support!

**Comment by paolaroncaglia** [comment]
@matentzn tagging you due to your previous comment, please.

**Comment by matentzn** [comment]
Hu, this has been done more than a year ago; am I missing something? I think this can be closed.

**Comment by paolaroncaglia** [comment]
Thought so. Thanks. I'll close.
