### ISSUE TITLE
Migrate pCL over to CL

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#536]
We will put these in explicitly as human for now; may generalize to include mouse later

 https://bioportal.bioontology.org/ontologies/PCL

**Comment by dosumis** [comment]
A new (currently experimental) repo with a version of PCL built using robot templates is here:
https://github.com/obophenotype/provisional_cell_ontology

There a more issues discussed before merging in - in particular new nested classifications having EC defs that are not sufficient for auto-classification within the ontology.
