### ISSUE TITLE
issue with Protege and CL

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#537]
Does anyone else have issues with using Protege with the CL? This is just an issue for me with CL, not any other ontology, and it seems to be an issue with different versions of Protege, I am currently using v5.5.0 beta.

When I search for a class, and click on it in the search box, it will bring up the annotations, but it won't pull up the class in the Class hierarchy pane. 

I should submit a ticket on the Protege tracker, but I was wondering if anyone else had this problem specifically with CL or had any ideas.

Thanks!

Here is a screenshot, you can see that native cell is not displayed in the Class Hierarchy pane:
![image](https://user-images.githubusercontent.com/6722114/52244302-e6db2000-2891-11e9-96f2-a605f7b4ecbe.png)

**Comment by addiehl** [comment]
This is the way CL has behaved for me in Protege for years.  The way to see the full class hierarchy is to run the reasoner and then view the inferred hierarchy.

I've never understood why this is, but that has been my experience.

**Comment by nicolevasilevsky** [comment]
It is so weird! I only have this issue with the CL and no other ontology. I'll submit a ticket to Protege, but thanks for the tip, @addiehl.

**Comment by nicolevasilevsky** [comment]
I submitted a ticket to Protege: https://github.com/protegeproject/protege/issues/847

**Comment by nicolevasilevsky** [comment]
update - this will be fixed in the next release of Protege.
