### ISSUE TITLE
A few missing parents/synonyms and typos

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#557]
Hi,
I’ve noticed a few issues, listing them here by type:
 
Missing parents:

- [x] Based on the definition of CL:1001603 ‘lung macrophage’ (“Circulating macrophages and tissue macrophages (alveolar macrophages) of lung”), CL:0000583 ‘alveolar macrophage’ should be given the additional parent ‘lung macrophage’; at present it is only a subclass of ‘tissue-resident macrophage’ (at least it is in OLS; for some reason http://purl.obolibrary.org/obo/CL_0000583 won’t load in Ontobee and returns an error “Error loading stylesheet: A network error occurred loading an XSLT stylesheet:http://www.ontobee.org/ontology/view/CL?iri=http://purl.obolibrary.org/obo/CL_0000583”).
- [x] CL:0000691 ‘stellate interneuron’ should be given the additional parent CL:0000122 ‘stellate neuron’ (they also both lack a definition, see e.g. https://en.wikipedia.org/wiki/Stellate_cell).
- [x] CL:0009005 ‘salivary gland cell’ should be given a part_of axiom to UBERON:0001044 ‘saliva-secreting gland’. There are missing links between ‘salivary gland cell’ and CL terms that are part_of children or descendants of ‘saliva-secreting gland’; adding the axiom above should fix that. 

Synonyms:

- [x] CL:0000815 ‘regulatory T cell’ doesn’t have the synonym “Treg”, commonly used in the literature. “Treg” is in CL as a broad synonym, or as part of synonyms, of subtypes of regulatory T cells. I’d suggest adding “Treg” as a synonym to CL:0000815 ‘regulatory T cell’.

Typos:

- [x] The labels of CL:0002147 ‘clear chief cell of parathyroid cell’ and CL:0002143 ‘dark chief cell of parathyroid cell’ should both probably be corrected to ‘...gland’.
- [x] For consistency with other types of brush cells, the label of CL:0002203 ‘Brush cell of epithelium proper of large intestine’ should probably be ‘brush…’.
- [x] CL:0002265 ‘type D cell of colon’ has a synonym “colonc delta cell”, this is probably a typo for “colonic…”. 
- [x] The label of CL:1000323 ‘pylroric gastric gland goblet cell’ should be corrected to “pyloric…”.
- [x] The definition of CL:0002051 ‘CD38-high pre-BCR positive cell’ reads “A pre-BCR positive T cell that is CD38-high.” but should probably read “...positive B cell…” based on its parentage.
- [x] CL:0000171 ‘pancreatic A cell’ has a synonym “alpha cell of iselt of Langerhans”, where “iselt” should be corrected to “islet”.
- [x] CL:0005019 ‘pancreatic epsilon cell’ has definition “Ghrelin secreting cells found in the found in the exocrine pancreas.”, where “found in the” is duplicated.

Thanks!

**Comment by nicolevasilevsky** [comment]
good catch on all these issues @paolaroncaglia!
