### ISSUE TITLE
Add CL:0000235 is_a CL:0000842

### ISSUE THREAD

**Issue by mbernste** [obophenotype/cell-ontology#561]
I think CL:0000235 (macrophage) should have an edge to CL:0000842 (mononuclear cell)

**Comment by addiehl** [comment]
Nuclear number should be captured via logical definitions, but we need to evaluate whether we should apply this across the CL or just to provide support for these phenotypically defined classes (mononuclear cell) that relate more to how the cells are prepared than some true ontological class

**Comment by mbernste** [comment]
That makes sense. To provide some motivation for adding missing edges such as this, I am currently developing a cell type classifier using public RNA-seq data (https://www.biorxiv.org/content/10.1101/634097v1). We are using the graph structure of the Cell Ontology to improve classification performance and it benefits the classifier when these edges are included.

**Comment by paolaroncaglia** [comment]
The issue of capturing nuclear number (or not) was raised in 2 other tickets, so I'll link this one there for recording purposes, and close it as duplicate. Please feel free to comment on the more recent tickets if desired. Thanks.
