### ISSUE TITLE
Add edges from children of 'professional antigen presenting cell' (CL:0000145)

### ISSUE THREAD

**Issue by mbernste** [obophenotype/cell-ontology#562]
According to https://www.nature.com/articles/nri3754 , the professional antigen presenting cells at least encompass dendritic cells (CL:0000451), macrophages (CL:0000235), and B cells (CL:0000236). I proposing adding is_a edges from these terms to CL:0000145

**Comment by addiehl** [comment]
It would be better to add logical axioms that specify a functional criteria for antigen presentation such as 'capable of' some 'antigen processing and presentation of peptide or polysaccharide antigen via MHC class II' to the proposed parent and child classes and let the reasoner deduce the relationship.

BTW, professional antigen presenting cells = any cell that can perform class II antigen presentation

I can add this to my HIPC work

**Comment by mbernste** [comment]
Thank you!

**Comment by addiehl** [comment]
'professional antigen presenting cell'
leukocyte and 'capable of' some 'antigen processing and presentation of peptide or polysaccharide antigen via MHC class II'

The axiom 'capable of' some 'antigen processing and presentation of peptide or polysaccharide antigen via MHC class II' was added to 'dendritic cell', 'macrophage', and 'mature B cell', and reasoning infers these are subclasses of 'professional antigen presenting cell'.

Note that per an existing axiom, 'mature eosinophil' is also inferred to be a subclass of 'professional antigen presenting cell'.  A review of the literature offers mixed evidence and viewpoints on this issue, so the following editor's note was added:
"The status of eosinophils as true professional antigen presenting cells is unclear, despite their ability to present exogenous peptides and peptides processed from exogenous proteins (in certain studies) via MHC Class II and activate T cells. Per the equivalence axioms, 'eosinophil' is reasoned to be a subclass of 'professional antigen presenting cell', though the role of eosinophils as such in the body may be limited."
