### ISSUE TITLE
Format problem in live data?

### ISSUE THREAD

**Issue by jlparmley** [obophenotype/cell-ontology#563]
We are trying to parse the current owl data file for cl and run into problems with new line characters in the section pasted below. 
Is this valid owl format? Our current owl parsers cannot handle this. 
In fact trying to paste it in this ticket as code does not work for the entire string. 

If this is correct please let us know and we will try to solve the issue we have at our end  Otherwise, please can you let me know when it is debugged. 
Many thanks

Quote: 

```
    <!-- http://purl.obolibrary.org/obo/RO_0002007 -->

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002007">
        <rdfs:subPropertyOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
        <rdfs:domain>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000040"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0000053"/>
                        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/PATO_0002124"/>
                    </owl:Restriction>
                </owl:intersectionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://purl.obolibrary.org/obo/BFO_0000040"/>
        <obo:IAO_0000115>X outer_layer_of Y iff:
. X :continuant that bearer_of some PATO:laminar
. X part_of Y
. exists Z :surface
. X has_boundary Z
. Z boundary_of Y

has_boundary: http://purl.obolibrary.org/obo/RO_0002002
boundary_of: http://purl.obolibrary.org/obo/RO_0002000</obo:IAO_0000115>
        <obo:IAO_0000117>David Osumi-Sutherland</obo:IAO_0000117>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">RO:0002007</oboInOwl:hasDbXref>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">uberon</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">bounding_layer_of</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/ro/subsets#ro-eco"/>
        <oboInOwl:shorthand rdf:datatype="http://www.w3.org/2001/XMLSchema#string">bounding_layer_of</oboInOwl:shorthand>
        <rdfs:comment>A relationship that applies between a continuant and its outer, bounding layer.  Examples include the relationship between a multicellular organism and its integument, between an animal cell and its plasma membrane, and between a membrane bound organelle and its outer/bounding membrane.</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A relationship that applies between a continuant and its outer, bounding layer. Examples include the relationship between a multicellular organism and its integument, between an animal cell and its plasma membrane, and between a membrane bound organelle and its outer/bounding membrane.</rdfs:comment>
        <rdfs:label xml:lang="en">bounding layer of</rdfs:label>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">bounding layer of</rdfs:label>
    </owl:ObjectProperty>
```

**Comment by jlparmley** [comment]
I have noticed exactly the same issue with the hp.owl file (the original one was in cl.owl.

`    

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/RO_0002007">
        <rdfs:subPropertyOf rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
        <rdfs:domain>
            <owl:Class>
                <owl:intersectionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000040"/>
                    <owl:Restriction>
                        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0000053"/>
                        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/PATO_0002124"/>
                    </owl:Restriction>
                </owl:intersectionOf>
            </owl:Class>
        </rdfs:domain>
        <rdfs:range rdf:resource="http://purl.obolibrary.org/obo/BFO_0000040"/>
        <obo:IAO_0000115>X outer_layer_of Y iff:
. X :continuant that bearer_of some PATO:laminar
. X part_of Y
. exists Z :surface
. X has_boundary Z
. Z boundary_of Y

has_boundary: http://purl.obolibrary.org/obo/RO_0002002
boundary_of: http://purl.obolibrary.org/obo/RO_0002000</obo:IAO_0000115>
        <obo:IAO_0000117>David Osumi-Sutherland</obo:IAO_0000117>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">RO:0002007</oboInOwl:hasDbXref>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">uberon</oboInOwl:hasOBONamespace>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">bounding_layer_of</oboInOwl:id>
        <oboInOwl:inSubset rdf:resource="http://purl.obolibrary.org/obo/ro/subsets#ro-eco"/>
        <oboInOwl:shorthand rdf:datatype="http://www.w3.org/2001/XMLSchema#string">bounding_layer_of</oboInOwl:shorthand>
        <rdfs:comment>A relationship that applies between a continuant and its outer, bounding layer.  Examples include the relationship between a multicellular organism and its integument, between an animal cell and its plasma membrane, and between a membrane bound organelle and its outer/bounding membrane.</rdfs:comment>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A relationship that applies between a continuant and its outer, bounding layer. Examples include the relationship between a multicellular organism and its integument, between an animal cell and its plasma membrane, and between a membrane bound organelle and its outer/bounding membrane.</rdfs:comment>
        <rdfs:label xml:lang="en">bounding layer of</rdfs:label>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">bounding layer of</rdfs:label>
    </owl:ObjectProperty>
`

**Comment by matentzn** [comment]
Which parsers are you using? OWL API based? Can you paste the parser error message so I can see exactly where the error occurs? Thanks!

**Comment by paolaroncaglia** [comment]
The submitter hasn't replied in nearly 3 years, so I'll assume that the issue is no longer an issue and I'll close. If not, please feel free to open a new ticket with updated details. Thanks.

**Comment by matentzn** [comment]
Definitely not a problem for the standard parsers!
