### ISSUE TITLE
Review what's been lost in moving to ODK

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#568]
Pre ODK Makefile here:

@cmungall  - looks like quite a lot going on with Bridge files etc.  Is any of this still relevant?  Could you  review and  post tickets if anything needs to be recovered?

https://github.com/obophenotype/cell-ontology/blob/a7ea8362d3a1000534f72bdc34f7f78dd81d7b33/src/ontology/Makefile

**Comment by paolaroncaglia** [comment]
I'll assume that there are no pending issues by now, so I'll close.
