### ISSUE TITLE
cerebral cortex GABAergic interneuron relationship to cerebral cortex is inconsistent in definitions

### ISSUE THREAD

**Issue by ukemi** [obophenotype/cell-ontology#570]
As part of a new import pipeline @balhoff designed for GO imports, we can now visualize changes in imported ontologies and their impact on GO. The relationships between cerebral cortex GABAergic interneuron development terms and forebrain development terms were changed. I suspect this is due to the relation in the ontology that specifies that a cerebral cortex GABAergic interneuron has_soma_location some cerebral cortex and there are projections of these neurons that extend beyond. However, the definition of the neurons is still 'A GABAergic interneuron that is part_of a cerebral cortex'. Should the definition be modified to be consistent with the equivalence axiom?

**Comment by dosumis** [comment]
> Should the definition be modified to be consistent with the equivalence axiom?

It should.  CL neuron defs should change.
