### ISSUE TITLE
Obsolete use of CP_ iris and replace by CL_ instead to avoid future clashes?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#572]
There are a bunch of classes in CL that dont have the normal CL namespace, like this:

https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCP_0000028

Maybe it make sense in the long term to obsolete those and instead use CL_000 iris. Just to avoid bad things happening when the Core Process Ontology (CP) will be registered at OBO :P

**Comment by addiehl** [comment]
These 'CP' terms were created years ago to capture cellular phenotypes.  The CP prefix has never been registered with OBO foundry, nor is there an actual CP ontology, though we once thought of doing one.  In retrospect, this is just an ugly hack, and I agree we should obsolete these terms and replace with terms from a more appropriate source, perhaps PATO.

**Comment by matentzn** [comment]
If they are cellular phenotypes, maybe we should align them with uPheno phenotypes as well? Here three options:

1. Obsolete all CP terms and replace by fresh CL ids. Apply uPheno patterns instead of the now incompatible bearer-of pattern.
2. Move CP terms as they are to a new ontology called cellular phenotype ontology. Use uPheno patterns. There are likely to emerge more cellular phenotypes! 
3. Extent [CMPO](https://www.ebi.ac.uk/ols/ontologies/cmpo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fcmpo%2FCMPO_0000303). I am not exactly sure, about worldview and biology issues, but wouldnt this be a more suitable home?

@addiehl @dosumis @simonjupp @cmungall

**Comment by dosumis** [comment]
I'd be happy to split these terms into a separate, imported file - but I don't think this would be a phenotype ontology.

All these terms are GO cell components, subclassed by their qualities, so they might better be considered as extensions to GO CC than phenotypes.  If they were made into phenotypes following uPheno, then they couldn't fullfill their current role in defining cell types  (at least not without a change in axiomatization). The one potentially problematic case is 'increased nucleus size'. - as this appears to be  comparative (and so more phenotype-y?).  However, looking at the definition, I think the chosen quality is wrong:

"A nucleus size quality which is relatively high compared to the amount of cytoplasm present in the same cell."

From this, it sounds like we need a new (categorical) PATO term, something like:

"A quality inhering in a cell whose nuclear volume is relatively high compared to the amount of cytoplasm present in the same cell." 

We could then use this to define the CP term, renames as something like 'oversized nucleus'.

@addiehl  - would that make sense to you?

Longer term - maybe they should just be requested as GO terms?

**Comment by addiehl** [comment]
I believe these terms would be most appropriately moved to CMPO, since they all describe cellular phenotypes that are observed via microscopy.

Does anyone actively maintain CMPO?

**Comment by cmungall** [comment]
CMPO isn't in OBO. @matentzn @dosumis do you know if there is interest at EBI in maintaining it?

https://www.ebi.ac.uk/cmpo/

or is this subsumed by upheno? we could just put in as class expressions, no? original constraints due to obof

**Comment by matentzn** [comment]
I think this is up to us. https://github.com/EBISPOT/CMPO has not been updated in a while, we could take it over, or do something else. Whatever works to maintain the concept of "cellular phenotypes" I guess!

**Comment by matentzn** [comment]
Its not been subsumed by uPheno!

**Comment by cmungall** [comment]
we should think about modularization. is CMPO species neutral? what are its
boundaries with uPheno? Does it automatically subsume e.g. the majority of
FYPO (which is species specific, and inherently all "cellular phenotypes"
by nature of the organism)

**Comment by simonjupp** [comment]
My intention was always to submit CMPO to OBO as an uber cellular phenotypes. I tried to keep the modelling as close as possible to uPheno using the SUBQ pattern. We were working with a bunch of phenotype observation from a number of different microscopy datasets that all needed to be annotated with pre-composed terms.  This meant we ended up with some strange terms like this http://www.ebi.ac.uk/cmpo/CMPO_0000378, that isn't a cellular phenotype, but an observation about a bunch of phenotypes in a population of cells. The curators wanted these terms, but I was never really sure about how best to handle these in a pre-composed way. 

I once did a little experiment to see how much of FYPO I could classify beneath CMPO - with a bit of axiom rewriting this kind of worked. It would be great to see some or all of CMPO integrated into OBO and properly aligned with uPheno.

**Comment by dosumis** [comment]
I don't think that a phenotype ontology is the right home for these classes.  Some relevant discussion on a closed ticket from late last year: https://github.com/obophenotype/cell-ontology/issues/734#issuecomment-694964148

These terms are used to define various cell types  - they typically refer to entities rather than their qualities, e.g. see basophilic cytoplasm here:

```
'basophilic erythroblast' EquivalentTo erythroblast 
  and ('has part' some 'basophilic cytoplasm')
  and ('has part' some heterochromatin) 
  and ('has plasma membrane part' some 'transferrin receptor protein 1')
```

I think a lot of this can be fixed by having the relevant qualities in PATO.  I already made a ticket for these
`'has part' some 'basophilic cytoplasm'`
->
`'has part' some ('cytoplasm  and 'bearer of' some basophilic`) # We could suggest these as types of cytoplasm in GO but a doubt they'd take them.

I already made a ticket for histological qualities in PATO:  https://github.com/pato-ontology/pato/issues/342

Here's the complete list of CP terms:

'acidophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000027
'banded nucleus' http://purl.obolibrary.org/obo/CP_0000039
'basophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000028
'cartwheel heterochromatin' http://purl.obolibrary.org/obo/CP_0000043
'increased nucleus size' http://purl.obolibrary.org/obo/CP_0000037
'lobed nucleus' http://purl.obolibrary.org/obo/CP_0000025
'neutrophillic cytoplasm' http://purl.obolibrary.org/obo/CP_0000000
'polychromatophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000035
'reniform nucleus' http://purl.obolibrary.org/obo/CP_0000040

The only one that sounds like a QE phenotype is 'increased nucleus size', but having looked into what this is used for, I this is better expressed in terms of nuclear/cytoplasmic ratio.  PATO ticket here:

https://github.com/pato-ontology/pato/issues/343. (Nicole has already made a start at adding).

**Comment by dosumis** [comment]
There are clearly phenotypes in CMPO which look like they could be useful here - e.g. https://www.ebi.ac.uk/ols/ontologies/cmpo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fcmpo%2FCMPO_0000117&viewMode=All&siblings=false

But it is not clear to me how we can use terms defined using QE to fill slots in CL defs - whereas the EQ versions clearly do.

**Comment by dosumis** [comment]
All agreed that we should fix following EQ (not QE) formalism as compound entity - ask described above.

  - [ ] Add all relevant terms to PATO
  - [ ] Retofit.

**Comment by matentzn** [comment]
This issue is not solved, but for future reference, i propose to just get rid of the CP namespace for now by incorporating the terms #1311 and you can deal with the issue curation wise as you see fit when you get to it. I just want to move the ID cleanup forward. 

So, whoever takes this issue on: the terms, in case #1311 gets merged, now have regular CL ids.

**Comment by dosumis** [comment]
I think we're close to solving it.   Needs:

1. This PATO issue fixing: https://github.com/pato-ontology/pato/issues/342
(These PATO terms have already been added) https://github.com/pato-ontology/pato/commit/0ac2938138d4c8faeccf245d09bc78e14520844e)

2. Updates to CL terms that reference CP terms to change to compound entity reference.

**Comment by dosumis** [comment]
Actually - we might have most of the PATO terms already (I think they need to be moved, but that's a secondary issue)

![image](https://user-images.githubusercontent.com/112839/141984447-55035bb8-46bc-4212-a8b6-563edf3c704f.png)

**Comment by matentzn** [comment]
So all 10 CP terms will be obsoleted?

**Comment by dosumis** [comment]
@shawntanzk  - can you have a go at quickly cleaning this up.

Example: 
[acidophilic cytoplasm](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCP_0000027)
is used to defined these terms:

![image](https://user-images.githubusercontent.com/112839/141984910-1eb257df-cc38-4f30-b9c1-5b648d8523d0.png)

Each should be changed to:
has_part some (cytoplasm and 'bearer of'* some PATO:acidophilc) ...

**Comment by dosumis** [comment]
Added to agenda for tomorrow's CL call

**Comment by shawntanzk** [comment]
I'll hold off making changes on this till after tomorrow's CL call discussing this - don't want to break OBO products before discussing how to handle it

**Comment by shawntanzk** [comment]
might also need a PATO release after new terms gets passed to fully complete this
