### ISSUE TITLE
possible taxon constraint needed on 'leucocyte'

### ISSUE THREAD

**Issue by krchristie** [obophenotype/cell-ontology#576]
In https://github.com/geneontology/go-ontology/issues/17613, @hattrill made this request:

> Could you put a taxon constrain on:
> 
> GO:0002443 | leukocyte mediated immunity
> GO:0045321 | leukocyte activation
> GO:0050900 | leukocyte migration
> 
> I think that the appropriate taxid is Protostomia NCBI:txid33317
> 
> (From the CL:
> hemocyte (sensu Nematoda and Protostomia) CL:0000387 are the immune cells of inverts (rather than leukocyte CL:0000738 which is a vertebrate thing))
> 
> (I haven't exhaustively gone through the GO to look for leukocyte terms, just these nodes looked like good bets for what I was looking at.)

As there are quite a number of leucocyte terms in GO, the more parsimonious solution would be for the taxon constraint to come from CL.

Thanks,

Karen

**Comment by krchristie** [comment]
Hi @nicolevasilevsky - I just wanted to check if you might be able to get to this soon. Thanks :)

**Comment by nicolevasilevsky** [comment]
@krchristie this is pending a pull request, I asked @cmungall and @dosumis to review. (I know Chris is out of town at the moment, so hopefully @dosumis can look at it.) Or maybe @matentzn, could you help?
Thanks!

**Comment by nicolevasilevsky** [comment]
I just merged the PR @krchristie. You should see this change in the next release.
