### ISSUE TITLE
CL:0000158 term name = CL:0007021 exact synonym

### ISSUE THREAD

**Issue by ukemi** [obophenotype/cell-ontology#583]
I have opened a ticket in GO to change our primary label on GO:0060486 to club cell differentiation. However, I notice that 'club cell' is also an exact synonym of CL:0007021. Is this allowed in CL? If so, I will change the GO term label, but I thought I'd check with you first.

**Comment by cerivs** [comment]
The zebrafish community calls the cells "club cells" probably due to morphology.    They are secretory epidermal cells.

**Comment by addiehl** [comment]
I think we will have to relax the exact synonym on CL:0007021 to related synonym, or alternately rephrase it as "club cell (zebrafish)".
