### ISSUE TITLE
Current incompatibilities between CL, Uberon, and GO

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#584]
The following ontology, which combines CL, Uberon, GO, RO, and NCBITaxon, has 18
 unsatisfiable classes. 

```turtle
Ontology(<http://example.org/ontologies/2019/9/4/untitled-ontology-1328>
Import(<http://purl.obolibrary.org/obo/cl/releases/2019-08-12/cl-base.owl>)
Import(<http://purl.obolibrary.org/obo/go/releases/2019-07-01/go-base.owl>)
Import(<http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim-disjoint-over-in-taxon.owl>)
Import(<http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl>)
Import(<http://purl.obolibrary.org/obo/ro/releases/2019-09-25/ro.owl>)
Import(<http://purl.obolibrary.org/obo/uberon/releases/2019-06-27/uberon-base.owl>)
)
```

I opened the issue here because it seem like the most suspicious culprit axioms are `capable of` relations asserted by CL. Here is an example for `arthropod fat body`:

## [arthropod fat body](http://purl.obolibrary.org/obo/UBERON_0003917) EquivalentTo [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [arthropod fat body](http://purl.obolibrary.org/obo/UBERON_0003917) SubClassOf [adipose tissue](http://purl.obolibrary.org/obo/UBERON_0001013)
    - [adipose tissue](http://purl.obolibrary.org/obo/UBERON_0001013) EquivalentTo [connective tissue](http://purl.obolibrary.org/obo/UBERON_0002384) and ([composed primarily of](http://purl.obolibrary.org/obo/RO_0002473) some [fat cell](http://purl.obolibrary.org/obo/CL_0000136))
      - [composed primarily of](http://purl.obolibrary.org/obo/RO_0002473) SubPropertyOf: [has part](http://purl.obolibrary.org/obo/BFO_0000051)
      - [fat cell](http://purl.obolibrary.org/obo/CL_0000136) SubClassOf [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [mesenchymal stem cell](http://purl.obolibrary.org/obo/CL_0000134)
        - [develops from](http://purl.obolibrary.org/obo/RO_0002202) SubPropertyOf: [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254)
        - [mesenchymal stem cell](http://purl.obolibrary.org/obo/CL_0000134) EquivalentTo [connective tissue cell](http://purl.obolibrary.org/obo/CL_0002320) and ([has plasma membrane part](http://purl.obolibrary.org/obo/RO_0002104) some [PR_000001345](http://purl.obolibrary.org/obo/PR_000001345)) and ([has plasma membrane part](http://purl.obolibrary.org/obo/RO_0002104) some [PR_000001800](http://purl.obolibrary.org/obo/PR_000001800)) and ([has plasma membrane part](http://purl.obolibrary.org/obo/RO_0002104) some [PR_000001843](http://purl.obolibrary.org/obo/PR_000001843)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [osteoblast differentiation](http://purl.obolibrary.org/obo/GO_0001649)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [cell migration](http://purl.obolibrary.org/obo/GO_0016477)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [neuron differentiation](http://purl.obolibrary.org/obo/GO_0030182)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [epithelial cell differentiation](http://purl.obolibrary.org/obo/GO_0030855)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [fat cell differentiation](http://purl.obolibrary.org/obo/GO_0045444)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [cardiac muscle cell differentiation](http://purl.obolibrary.org/obo/GO_0055007)) and ([capable of](http://purl.obolibrary.org/obo/RO_0002215) some [chondroblast differentiation](http://purl.obolibrary.org/obo/GO_0060591)) and ([lacks_plasma_membrane_part](http://purl.obolibrary.org/obo/cl#lacks_plasma_membrane_part) some [MHC class II protein complex](http://purl.obolibrary.org/obo/GO_0042613)) and ([lacks_plasma_membrane_part](http://purl.obolibrary.org/obo/cl#lacks_plasma_membrane_part) some [PR_000001003](http://purl.obolibrary.org/obo/PR_000001003)) and ([lacks_plasma_membrane_part](http://purl.obolibrary.org/obo/cl#lacks_plasma_membrane_part) some [PR_000001006](http://purl.obolibrary.org/obo/PR_000001006))
          - [cardiac muscle cell differentiation](http://purl.obolibrary.org/obo/GO_0055007) EquivalentTo [cell differentiation](http://purl.obolibrary.org/obo/GO_0030154) and ([results in acquisition of features of](http://purl.obolibrary.org/obo/RO_0002315) some [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746))
            - [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746) SubClassOf [develops from](http://purl.obolibrary.org/obo/RO_0002202) some [cardiac muscle myoblast](http://purl.obolibrary.org/obo/CL_0000513)
              - [cardiac muscle myoblast](http://purl.obolibrary.org/obo/CL_0000513) EquivalentTo [myoblast](http://purl.obolibrary.org/obo/CL_0000056) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133)) and ([develops into](http://purl.obolibrary.org/obo/RO_0002203) some [cardiac muscle cell](http://purl.obolibrary.org/obo/CL_0000746))
                - [cardiac muscle tissue](http://purl.obolibrary.org/obo/UBERON_0001133) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [heart](http://purl.obolibrary.org/obo/UBERON_0000948)
                  - [heart](http://purl.obolibrary.org/obo/UBERON_0000948) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Vertebrata <vertebrates>](http://purl.obolibrary.org/obo/NCBITaxon_7742)
                    - [Vertebrata <vertebrates>](http://purl.obolibrary.org/obo/NCBITaxon_7742) SubClassOf [Craniata <chordates>](http://purl.obolibrary.org/obo/NCBITaxon_89593)
                      - [Craniata <chordates>](http://purl.obolibrary.org/obo/NCBITaxon_89593) SubClassOf [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711)
                        - [Chordata](http://purl.obolibrary.org/obo/NCBITaxon_7711) SubClassOf [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511)
                    - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
            - [results in acquisition of features of](http://purl.obolibrary.org/obo/RO_0002315) SubPropertyOf: [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295)
  - [arthropod fat body](http://purl.obolibrary.org/obo/UBERON_0003917) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656)
    - [Arthropoda](http://purl.obolibrary.org/obo/NCBITaxon_6656) SubClassOf [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770)
      - [Panarthropoda](http://purl.obolibrary.org/obo/NCBITaxon_88770) SubClassOf [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794)
        - [Ecdysozoa](http://purl.obolibrary.org/obo/NCBITaxon_1206794) SubClassOf [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Protostomia](http://purl.obolibrary.org/obo/NCBITaxon_33317) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Deuterostomia](http://purl.obolibrary.org/obo/NCBITaxon_33511)
  - [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [capable of](http://purl.obolibrary.org/obo/RO_0002215) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [has part](http://purl.obolibrary.org/obo/BFO_0000051) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [develops from](http://purl.obolibrary.org/obo/RO_0002202) o [part of](http://purl.obolibrary.org/obo/BFO_0000050) SubPropertyOf: [develops from](http://purl.obolibrary.org/obo/RO_0002202)
  - [has developmental contribution from](http://purl.obolibrary.org/obo/RO_0002254) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

**Comment by balhoff** [comment]
cc @ukemi @cmungall

**Comment by matentzn** [comment]
@dosumis

**Comment by dosumis** [comment]
Delete axiom 'arthropod fat body' subClassOf 'adipose tissue' from Uberon.  It's really not justified by definition adipose tissue.  If we need a general class for both maybe make 'fat storage tissue' in Uberon.

**Comment by balhoff** [comment]
Thanks for checking this @dosumis!

**Comment by paolaroncaglia** [comment]
This seems done, so I'll close.
