### ISSUE TITLE
sperm are not always ciliated

### ISSUE THREAD

**Issue by ukemi** [obophenotype/cell-ontology#587]
To make a logical definition for sperm motility in GO, we need to be able to include sperm from organisms such as C. elegans. However, CL has this:
male gamete and (capable of some  flagellated sperm motility) and (capable of some sperm capacitation)
and  it is a subclass of ciliated cell (CL:0000064). 
I'm also not certain that worm sperm undergo capacitation. 

See PMID:29879100

**Comment by cmungall** [comment]
Thank you for identifying this issue in CL

It's actually worse as CL asserts it's an animal cell:

![image](https://user-images.githubusercontent.com/50745/67039696-b1502d00-f0d6-11e9-8e89-21989d4fb8bf.png)

While the focus of CL is metazoa, there is a need for an ontology to hold general groupings that span wider groups.

Also CL should strive to use language that does not cause confusion. Calling something "sperm" that is more specific than the label suggests is an anti-pattern. (note that we can always have taxon-specific synonyms for a more mammalian centric subclass if we like)

I propose 

 1. that we remove the linkage between GLC and animal cell (and review what is currently under animal cell). In fact I question the utility of animal cell and eukaryotic cell. These predate TCs.
 2. we remove the logical definition from CL sperm cell (this is a bad definition in any case by the criteria I laid down in https://douroucouli.wordpress.com/2019/07/29/ontotip-dont-over-specify-owl-definitions/ and https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/). We could make them taxon GCIs but I question the utility
 3. We add subclasses provided by Karen

Can @obophenotype/cell-ontology editors indicate agreement/disagreement

**Comment by dosumis** [comment]
So how do cilia and nematode sperm fit in to this picture?

**Comment by ukemi** [comment]
Nematode sperm do not have a flagellum. They are ameboid. There is also an issue here if we want to include plants. If I recall correctly from my days as a developmental biologist, plants do not segregate their germ line (see the graph above). Comments from @tberardini  or @vanaukenk might be helpful here.

**Comment by dosumis** [comment]
- Does movement by pseudopod count as ameboid? In which case C.elegans sperm classified as ameboid sperm (from PMID:29879100).  Peraps worth ading motile and non-motile sibling classes.

**Comment by ukemi** [comment]
See this paper PMID:19295707

**Comment by krchristie** [comment]
> Peraps worth ading motile and non-motile sibling classes.

I think that's a good idea. It seems to me that in order to make an equivalence axiom for the GO term 'sperm cell motility', it would be better to use a CL term 'motile sperm cell' rather than just 'sperm cell' since the latter isn't necessarily motile. So that would modify my earlier suggestion to this:

-- sperm cell
--- motile sperm cell
---- amoeboid sperm cell
---- flagellated sperm cell
--- non-motile sperm cell

**Comment by nicolevasilevsky** [comment]
is there action needed on this ticket?

**Comment by ukemi** [comment]
We need a release so we can import the new terms.

**Comment by nicolevasilevsky** [comment]
I think this can be closed, please reopen if needed.
