### ISSUE TITLE
CL:0000334 query

### ISSUE THREAD

**Issue by mah11** [obophenotype/cell-ontology#598]
For work we're doing on FYPO, @matentzn and I have a question about CL:0000334  ! vegetative cell (sensu Fungi): 

Is it, or should it be, defined as a fungal cell as it exists during the part of the life cycle represented by GO:0072690 ! single-celled organism vegetative growth phase?

#447 is probably also relevant

**Comment by mah11** [comment]
ping! Any word on this one?

**Comment by paolaroncaglia** [comment]
@mah11 hi! CL:0000334 ! vegetative cell (sensu Fungi) is currently a subclass of 'fungal cell'. And the plan to cede fungal cell types to the FAO is still standing. Editorial resources in CL at the moment tend to focus on mammalian terms, but if you'd need any urgent edit on CL:0000334 in the interim, please list your suggested changes and I'll be happy to commit them. Thanks.

**Comment by bvarner-ebi** [comment]
Hi, @mah11, checking in on this ticket.
As noted above, CL:0000334 'vegetative cell (sensu Fungi)' is currently a subClass of 'fungal cell'.
It currently lacks a text definition, which should be addressed in https://github.com/obophenotype/cell-ontology/issues/1823.

Do you have any specific requests for this term? If so, please do reopen this ticket and add your requests.
