### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#606]
I just wanted to note that GO is waiting for some new terms, so if anyone has time to make a release in the near future, that would be great!

**Comment by matentzn** [comment]
I have no problem to generally do this (right now!), but I am unclear what to do with open PRs. I have asked this question on the UBERON tracker before: "Question: Should me merge pull request after a period of time without review?", and @cmungall  says he prefers to take a look, but I am not sure this is the best way to move forward. The business saying is: "Its better to ask for forgiveness than for permission" - in the same sense I think we should consider an SOP that simply says that after a period of X days, PRs can be merged. Else we need someone that volunteers to own the ontology and takes care of the merging in a timely manner. In any case: I can offer to run releases etc in a regular manner, I can do it fast, incorporate it into my wider workflows; but I cant review the biology of the PRs, and I also love to be able to avoid to chase biologists for review :P Let me know! Always happy to do this! @dosumis @cmungall

**Comment by dosumis** [comment]
Reviewing outstanding PRs right now.  Will attempt a release later.  Are there any particular tickets that should be priority for GO?

**Comment by balhoff** [comment]
I think the changes GO needed have already been merged. Right @ukemi?

**Comment by ukemi** [comment]
The sperm subclasses are still not available in our import. #587

**Comment by dosumis** [comment]
Hi @ukemi  - Edits for that ticket have been merged down, so will be in next release.

**Comment by dosumis** [comment]
![image](https://user-images.githubusercontent.com/112839/71731943-e8b0b900-2e3d-11ea-9edb-fab55522d2c7.png)

**Comment by ukemi** [comment]
Thanks @dosumis. What's the release cycle?

**Comment by dosumis** [comment]
Trying to release now but failing due to issues with Makefile: #608.  I'll make sure these are fixed and a new release generated in the next couple of days.

> Thanks @dosumis. What's the release cycle?

There isn't one.  Uncoordinated voluntary effort.   I think past time to start up some CL meetings again and get some basic organization for a monthly release cycle with a rotor for running releases + some basic training on editing and running releases.    Could we get a volunteer from GO to be involved? I'd like to keep the focus on practical organisation & implementation.

**Comment by nicolevasilevsky** [comment]
@dosumis I am happy to participate in regular CL meetings too.

**Comment by addiehl** [comment]
I would also like to participation in regular CL meetings as well.

**Comment by aopisco** [comment]
+1: would like to join regular CL meetings

**Comment by dosumis** [comment]
Hi Angela,

I've  sent an  invitation by email.

Nicole:  Maybe we could post an open invitation on the GitHub readme?

**Comment by addiehl** [comment]
Closing this as a new release of CL was made on Monday, March 2 by @dosumis and we have a new standing meeting for CL set up:
https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit?ts=5e4687d7
