### ISSUE TITLE
CL build fail 

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#608]
```
robot query --use-graphs true -f csv -i cl-edit.owl --query ../sparql/cl_terms.sparql tmp/cl_terms.txt
tmp/cl_terms.txt (No such file or directory)
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [cl.Makefile:60: tmp/cl_terms.txt] Error 1
```

**Comment by dosumis** [comment]
I notice the release is passing https://travis-ci.org/obophenotype/cell-ontology, so perhaps just a local issue for me?  Don't see why though:  Use a newly checked out repo + freshly pulled container.

**Comment by addiehl** [comment]
The most recent CL release was March 2, 2020, and I believe it was successful, so I am closing this issue.
