### ISSUE TITLE
NTR: Pulmonary Ionocyte

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#613]
Hello, 

New in ontologies, a fan of the project, want to really get involved.  

Some high-profile articles recently brought the discovery of the pulmonary ionocyte into light, and I did not find it in the current ontology version, so here it is a suggestion of possible new term:

label: pulmonary ionocyte
definition: A CFTR-rich ionocyte that is part of the lung epithelium
part_of: some lung ( UBERON:0002048 )
is_a: epithelial cell of the lung (CL:0000082)
ionocyte (CL:0005006)

refs:
https://www.nature.com/articles/s41586-018-0393-7
https://www.nature.com/articles/s41586-018-0394-6

Thanks!

**Comment by matentzn** [comment]
Hey @lubianat 

Awesome! Thanks for chiming in! I can see you are generally good with git and so on, would you like us to try and set you up so you can make such additions yourself? Drop me an [email](https://www.ebi.ac.uk/about/people/nicolas-matentzoglu), or if you prefer, ping me on gitter.  It may be a bit of getting used to, but I believe its worth it - especially if you are interested in ontologies in general.  If you are interested in CL in particular, we are restarting regular calls every 2 weeks from 16:00 to 17:00 on Wednesday from Wed 19 Feb to Wed 19 Aug (GMT). I can send you an invite if you like!
