### ISSUE TITLE
Questions about stem cells and blast/progenitor cells

### ISSUE THREAD

**Issue by vanaukenk** [obophenotype/cell-ontology#617]
We recently made some revisions to cell division terms in the BP branch of GO and came across some inference issues wrt neuroblasts and somatic stem cells that need clarification.

Currently, neuroblast ( http://purl.obolibrary.org/obo/CL_0000031) is defined as:
A cell that will develop into a neuron often after a migration phase.

neuroblast is an is_a child of neuronal stem cell (http://purl.obolibrary.org/obo/CL_0000047) defined as:
Neural stem cell is characterized as an undifferentiated cell that originates from the neuroectoderm and has the capacity both to perpetually self-renew without differentiating and to generate multiple types of lineage-restricted progenitors.

Since the definition of neuroblast implies that the cell is already committed to a fate, it is inconsistent with being a child of 'neuronal stem cell' and it seems more appropriate as a child, or synonym, of 'neural progenitor cell', recently created and defined as:
An undifferentiated cell that originates from a neural stem cell and has the capacity to generate multiple types of lineage-restricted progenitors but not to self-renew.")

See: https://github.com/obophenotype/cell-ontology/pull/616

However, neuroblast currently has two children, sensu Vertebrata and sensu Nematoda and Protostomia.  The definition of the Vertebrata term seems to describe a progenitor cell:
An embryonic cell that develops into a nerve cell or neuron.

while the Nematoda and Protostomia has no definition, but seems to refer to stem cells (see the Introduction of: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0195855).

Can you please take a look and let us know what you think?

Thanks -
@ukemi @vanaukenk

**Comment by dosumis** [comment]
I think the biology is clear and there's a terminology clash between invertebrate and vertebrate uses of the term neuroblast.  We should not have a single neuroblast term that unites them based on name.

Arthropod neuroblasts are stem cells.  They retain their identify while neural progenitors (ganglion mother cells) bud from them in repeated rounds of division.  The neural progenitors then divide by fission to form specific neurons, glial cells and (occasionally) epithelial cells.   I think this fits well with:

> Neural stem cell is characterized as an undifferentiated cell that originates from the neuroectoderm and has the capacity both to perpetually self-renew without differentiating and to generate multiple types of lineage-restricted progenitors.

It doesn't fit with: 

> "A cell that will develop into a neuron often after a migration phase."

That sounds more like immature descendants of ganglion mother cells.

I'm not as familiar with the vertebrate terminology.  But here it seems to be used to refer to a : postmitotic cell that does not divide further, and which will develop into a neuron after a migration phase." https://en.wikipedia.org/wiki/Neuroblast

Proposal:

obsolete neuroblast 

Then: 

precursor cell (CL_0011115)
.   neural precusor cell
.   .     neuroblast (sensu vertebrata)
.   .     neuroblast (sensu Vertebrata and sensu Nematoda

stem cell
.       neural stem cell
.       .       neuroblast (sensu Vertebrata and sensu Nematoda

**Comment by vanaukenk** [comment]
Thanks @dosumis 
@ukemi and I will take a look at the pull request.

**Comment by vanaukenk** [comment]
Thanks @dosumis and apologies for the delay.

I think the above changes look okay, and agree that there seems to be a terminology clash here.

In looking at the diff, though, I have a question about the 'neuroglioblast (sensu Nematoda and Protostomia)' term (and also about the existing 'neuroglioblast (sensu Nematoda)' term).

This isn't my area of expertise, but I see that we don't have a corresponding 'neuroglioblast' term in the C. elegans cell and anatomy ontology, nor do any Textpresso or PubMed searches pull up relevant C. elegans or nematode papers.  

The existing CL term doesn't have a paper reference.  Do you know how this term is used in the nematode community?

Thx.

**Comment by dosumis** [comment]
Hi Kimberly,

'neuroglioblast' is occasionally used in flies, although not much recently. Many neuroblasts have some glia progeny - we'll probably find more of these as more complete maps of lineage are made.  I've no idea where the 'sensu Nematoda' term comes from - perhaps over-enthusiastic term addition by Michael Ashburner 15-20 years ago?  Happy to obsolete.

**Comment by vanaukenk** [comment]
Thanks @dosumis 
I think we can go ahead and obsolete the 'neuroglioblast (sensu Nematoda)' term.
