### ISSUE TITLE
Please clarify what happened to the following terms:

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#631]
CL_0000139
CL_0000184
CL_0000201
CL_0000403
CL_0000450
CL_0000804
CL_0000812

**Comment by matentzn** [comment]
If i do a grep -r for one of those I get this:

```
./ontology/cl-refactored.owl:AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasAlternativeId> <http://purl.obolibrary.org/obo/CL_0000136> "CL:0000450"^^xsd:string)
grep: ./ontology/CHANGES: No such file or directory
./ontology/imports/clo_import.owl:        <oboInOwl:hasAlternativeId rdf:datatype="http://www.w3.org/2001/XMLSchema#string">CL:0000450</oboInOwl:hasAlternativeId>
./ontology/imports/clo_import.obo:alt_id: CL:0000450
./ontology/imports/clo_import.json:          "val" : "CL:0000450"
./ontology/cl-edit.owl:AnnotationAssertion(oboInOwl:hasAlternativeId obo:CL_0000136 "CL:0000450"^^xsd:string)
./ontology/cl-edit_neg_exp.o
```

**Comment by matentzn** [comment]
(the terms are used by ZFA)

**Comment by dosumis** [comment]
[Ameloblast](https://www.ebi.ac.uk/ols/ontologies/CL/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000059)
has alternative id: CL:0000053, CL:0000139

OBO alt_IDs should automatically be converted to obsolete OWL classes with replaced_by.  This might not  have happened  in the move to OWL.

**Comment by dosumis** [comment]
Consistent with: 
./ontology/cl-edit.owl:AnnotationAssertion(oboInOwl:hasAlternativeId obo:CL_0000136 "CL:0000450"^^xsd:string)

I think there's a general job retrieve obsolete classes from alt_ids.

**Comment by matentzn** [comment]
Thank you I did not know that! :)

**Comment by dosumis** [comment]
OBO2OWL conversion does this automatically - so OK for ontologies maintained in OBO.  This functionality in OBO2OWL conversion may not have been in place when  CL moved to OWL.

**Comment by paolaroncaglia** [comment]
Hi @matentzn ,
Can this be closed now? Cheers.

**Comment by matentzn** [comment]
I dont think so - only if these terms are - in fact - back in CL! Thanks for checking in!

**Comment by bvarner-ebi** [comment]
All CURIEs noted above currently appear in CL as obsoleted classes with 'term replaced by' annotations.
If necessary, kindly reopen and provide pending action item(s).
