### ISSUE TITLE
NTR: mesothelial cell of epicardium

### ISSUE THREAD

**Issue by bonitalam** [obophenotype/cell-ontology#643]
We would like to request this NTR to annotate some biosamples.

label: mesothelial cell of epicardium
definition: A mesothelial cell that is part of the epicardium
part_of: UBERON_0002348 (epicardium)
is_a: CL_0000077 (mesothelial cell)

Thank you for your help!

**Comment by dosumis** [comment]
Should be easy to add this.  Should have  logical def:

intersection_of: CL_0000077 (mesothelial cell)
intersection_of: part_of UBERON_0002348 (epicardium)
