### ISSUE TITLE
CL terms with missing definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#649]
Here is a [spreadsheet](https://docs.google.com/spreadsheets/d/1Bcu6O5hgqAxTMcha_pDv4yZCQ8kTlMiLlb8o4b_2He0/edit#gid=1116044123) with terms that are missing definitions in CL.

(I don't know how to bring in the labels- can anyone do that?)

Hopefully we can all work through this list and add definitions.

**Comment by nicolevasilevsky** [comment]
related to #632

**Comment by nicolevasilevsky** [comment]
Kent added the labels [here](https://docs.google.com/spreadsheets/d/1Bcu6O5hgqAxTMcha_pDv4yZCQ8kTlMiLlb8o4b_2He0/edit#gid=308594775)

**Comment by paolaroncaglia** [comment]
Closing as a duplicate of https://github.com/obophenotype/cell-ontology/issues/1262.
