### ISSUE TITLE
NTR: progenitor cell 

### ISSUE THREAD

**Issue by bonitalam** [obophenotype/cell-ontology#653]
Hello, we would like to request a term for "progenitor cell". Right now a lot of progenitor cells (e.g. CL_0000038, https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000038) can be traced back up to "precursor cell" (CL_0011115) which we feel is too broad of a description and lacks the connection to a "progenitor cell" term. The "progenitor cell" term can be a subclass of "precursor cell" (CL_0011115)  like "stem cell" (CL_0000034) is currently.

From our understanding: "A progenitor cell is a biological cell that, like a stem cell, has a tendency to differentiate into a specific type of cell, but is already more specific than a stem cell and is pushed to differentiate into its "target" cell," (Lawrence, B.E.; Horton, P.M. (2013). Progenitor Cells : Biology, Characterization and Potential Clinical Applications. Nova Science Publishers, Inc. p. 26.). "Progenitors are typically the descendants of stem cells, only they are more constrained in their differentiation potential or capacity for self-renewal, and are often more limited in both senses" (https://doi.org/10.1016/B978-0-12-409503-8.00002-0).

Thank you for your help and consideration.

**Comment by nicolevasilevsky** [comment]
To clarify - are you proposing the hierarchy:
precursor cell
-stem cell
--progenitor cell (develops from stem cell)

Does this look correct?

**Comment by bonitalam** [comment]
Hi @nicolevasilevsky, yes that looks correct to me. However, I don't know if there are exceptions or cases where progenitor cells do not develop from stem cells that we should be wary of.

**Comment by addiehl** [comment]
In my understanding, a progenitor cell is a type of 'precursor cell' that has a develops_from relationship with 'stem cell'

'precursor cell'
- 'stem cell'
- 'progenitor cell'

logical definition of 'progenitor cell'
  'precursor cell' and 'develops from' some 'stem cell'

Alex

**Comment by nicolevasilevsky** [comment]
@addiehl - I added this term, would you mind reviewing the PR?
Thanks!
