### ISSUE TITLE
NTRs based on SARS-CoV-2 entry factors paper

### ISSUE THREAD

**Issue by paola-scibite** [obophenotype/cell-ontology#654]
Hi,
Based on a recent SARS-CoV-2 entry factors paper (https://www.nature.com/articles/s41591-020-0868-6):

- [x] Should a new term be created for ‘transit amplifying progenitor cell’ (synonym ‘transit amplifying cell’, acronym ‘TAC’)? It’s related to stem cells which I’m not an expert on, so can’t suggest much, except see also https://www.ncbi.nlm.nih.gov/pubmed/31399601, https://www.ncbi.nlm.nih.gov/pubmed/30827895 and https://www.ncbi.nlm.nih.gov/pubmed/24813615.

- [x] Should a new term be created for ‘limbal stem cell’ (synonym ‘limbus stem cell’)? See also https://www.ncbi.nlm.nih.gov/pubmed/29172876. (Update: no need to, can be captured compositionally.)

- [x] Should a new term be created for ‘vesicular smooth muscle cell’ as subclass (or descendant?) of CL:0000192 ‘smooth muscle cell’, acronym VSMC? It’s unclear to me what these really are. (Update: no ref provided, so can't check easily; also, VSMC is currently an exact synonym of 'vascular associated smooth muscle cell', so maybe the previous request was a mistake.)

Thanks,
Paola (Roncaglia)

**Comment by paolaroncaglia** [comment]
These NTRs stem from an HCA paper, so they'd be in scope for my work, I'll take this ticket. Also, 'transit amplifying cell' was created in the meantime, I'll check if ‘transit amplifying progenitor cell’ would be an appropriate synonym, and I'll add dbxrefs.
