### ISSUE TITLE
not all sperm are ciliated

### ISSUE THREAD

**Issue by ukemi** [obophenotype/cell-ontology#655]
I still see sperm (CL:0000019) asserted as a subclass of ciliated cell (CL:0000064). Not all sperm are ciliated. For example C. elegans sperm are ameboid and are not ciliated.

**Comment by dosumis** [comment]
Hmm - sorry.  I was sure this was fixed.

**Comment by dosumis** [comment]
For ref: https://github.com/obophenotype/cell-ontology/pull/592

Looks like sperm still has the axiom SUBCLASSOF: has_part some cilium!   

Will remove.

**Comment by ukemi** [comment]
Thanks!
