### ISSUE TITLE
NTR - tracheobronchial goblet cell

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#656]
Grouping term for goblet cells of the trachea on bronchi .  These are frequently discussed/treated together in anatomy/pathology texts.

This  would  group  existing terms for 'bronchial goblet cell' and 'tracheal goblet cell'.  Note, lung goblet cell is a (less useful?) sibling term - with only some overlapping members covering goblet cells in the more terminal bronchi the are part of the lungs.

Note, respiratory goblet cell is probably too broad as it covers nasal muscosa goblet cells.

**Comment by mkeays** [comment]
Tracheobrochial goblet cell?
