### ISSUE TITLE
tracheobronchial serous cell

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#658]
'serous cell' that part_of some 'trachenobronchial tree'

**Comment by mkeays** [comment]
Would existing terms 'serous cell of epithelium of brochus' and 'serous cell of epithelium of trachea' go under this one?

**Comment by dosumis** [comment]
with the right EquivalentClass definition, they will automatically be classified under.

Partnomy:

![image](https://user-images.githubusercontent.com/112839/81299921-e91cc300-906e-11ea-8295-0f17ac5903f9.png)



respirar

rte

**Comment by dosumis** [comment]
Note - pathologist spreadsheets use a set of terms for many cell type: trachea, main bronchi, lobar bronchi, segmental bronchi

I think this = tracheobronchial tree

'

trachea,   main bronchi, lobar bronchi, segmental bronchi
--



trachea,   main bronchi, lobar bronchi, segmental bronchi
--
