### ISSUE TITLE
NTR: CD25+ Mast cell

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#662]
Needed for HP_0031408 'Increased proportion of CD25+ mast cells'
Related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/5697

NTR: CD25+ mast cell
Parent: CL_0000097 'mast cell'
Def: A mast cell that is CD25+.
Comment: Mast cells do not normally express CD25, but neoplastic mast cells may be CD25-positive.

**Comment by addiehl** [comment]
If this is a neoplastic cell, it should not be placed under 'native cell'.

We have in the CL 'neoplastic cell' (http://purl.obolibrary.org/obo/CL_0001063); perhaps this should be the is_a parent:

'neoplastic cell'
and 'derives from' some 'mast cell'
and 'has plasma membrane part' some 'interleukin-2 receptor subunit alpha'

interleukin-2 receptor subunit alpha = CD25

Alex

**Comment by nicolevasilevsky** [comment]
Thank you Alex! I will add this as such. :)

**Comment by addiehl** [comment]
Perhaps we should have an exact synonym 'CD25+ neoplastic mast cell' just to make it even more obvious that this is not a normal cell type.
