### ISSUE TITLE
[NTR] CD3+ T cell

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#666]
**Preferred term label:**
'CD3-positive, alpha-beta T cell'

**Synonyms**
CD3-positive, alpha-beta T lymphocyte
CD3-positive, alpha-beta T-cell
CD3-positive, alpha-beta T-lymphocyte
CD3+ T cell

**Definition (free text, please give PubMed ID)**
A T cell expressing an alpha-beta T cell receptor and the CD3 coreceptor.

'mature alpha-beta T cell'
 and ('has plasma membrane part' some 'CD3 subunit with immunoglobulin domain')

**Parent term**
'mature alpha-beta T cell'

related ticket: https://github.com/obophenotype/human-phenotype-ontology/issues/5701

@addiehl does this look okay to you?

**Comment by addiehl** [comment]
We do not need this term.  The alpha-beta T cell receptor contains the CD3 chains by default -- they are part of the TCR protein complex.

**Comment by addiehl** [comment]
Beyond which, all mature T cells are CD3+, because CD3 is a component of the gamma-delta TCR complex as well.  Also, when people say CD3+, they really mean CD3e positive, because that is the CD3 chain that is almost always targeted in a flow cytometry assay.

**Comment by nicolevasilevsky** [comment]
Thanks, Alex and thanks for your comment on the HPO ticket. We can close this.
