### ISSUE TITLE
[NTR] tracheobronchial smooth muscle cell

### ISSUE THREAD

**Issue by mkeays** [obophenotype/cell-ontology#669]
**Preferred term label:**
tracheobronchial smooth muscle cell

**Synonyms**
smooth muscle cell of tracheobronchial tree

**Definition (free text, please give PubMed ID)**
Any smooth muscle cell that is part of the tracheobronchial tree. Based on pathologist annotations.

**Parent term**
smooth muscle cell

**Your nano-attribution (ORCID)**

**Comment by addiehl** [comment]
How is this related to 'bronchial smooth muscle cell' CL:0002598?

**Comment by dosumis** [comment]
It would be a parent (part of tracheobronchial tree).  I think there are a number of cases where the most justifiable class may be tracheobronchial rather than bronchial.

**Comment by dosumis** [comment]
Happy for this to be added as simple grouping term.

**Comment by mkeays** [comment]
This is done (commit df99a52b1c123a0964a827f4123594da64cc0d77).
