### ISSUE TITLE
[NTR] blood vessel smooth muscle cell

### ISSUE THREAD

**Issue by mkeays** [obophenotype/cell-ontology#670]
**Preferred term label:**
blood vessel smooth muscle cell

**Synonyms**
smooth muscle cell of blood vessel

**Definition (free text, please give PubMed ID)**
Any smooth muscle cell that is part of any blood vessel

**Parent term**
vascular associated smooth muscle cell

**Notes**
Blood vessels as distinct from other vasculature.

**Comment by dosumis** [comment]
We have [vascular associated smooth muscle cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000359)  - probably sufficient?

**Comment by mkeays** [comment]
@dosumis yeah, I thought that may include lymphatic vessels as well though

**Comment by dosumis** [comment]
Good point.  I just checked -  'lymphatic vessel' is part of vasculature in Uberon + there is associated smooth muscle, even though we don't have the cell types yet: https://en.wikipedia.org/wiki/Lymphatic_vessel

So - I think good to add - and perhaps add lymph vessel sibling term too.

**Comment by mkeays** [comment]
Ok, sounds good 👍
