### ISSUE TITLE
[NTR] interalveolar septum eosinophil

### ISSUE THREAD

**Issue by mkeays** [obophenotype/cell-ontology#677]
**Preferred term label:**
interalveolar septum eosinophil

**Synonyms**
eosinophil of interalveolar septum
eosinophil of interalveolar septa
interalveolar septa eosinophil

**Definition (free text, please give PubMed ID)**
Any eosinophil that is found in the interalveolar septa

**Parent term**
eosinophil

**Comment by mkeays** [comment]
Investigating whether these cells are tissue-resident or not. There seems to be recent evidence for a lung-resident population of eosinophils ([Mesnil et al, 2016](https://pubmed.ncbi.nlm.nih.gov/27548519/)). Checking whether these are lung-wide or specific to substructure(s) e.g. interalveolar septa.

**Comment by mkeays** [comment]
[Mesnil et al (2016)](https://pubmed.ncbi.nlm.nih.gov/27548519/) say resident eosinophils are found in lung parenchyma ([alveoli, alveolar ducts and respiratory bronchioles](https://radiopaedia.org/articles/lung-parenchyma)) in human and mouse. They are distinct from inflammatory eosinophils in the following ways:

- resident eosinophils have a ring-shaped nucleus, while inflammatory eosinophils have a segmented nucleus.
- resident eosinophils are present in normal, healthy lung tissue.
- resident eosinophils from nonasthmatic human lungs are Siglec8<sup>+</sup> CD62L<sup>+</sup> IL-3R<sup>lo</sup>, inflammatory eosinophils from sputa from asthmatic patients are Siglec8<sup>+</sup> CD62L<sup>lo</sup> IL-3R<sup>hi</sup>. In mice, resident eosinophils are SiglecF<sup>int</sup> CD62L<sup>+</sup> CD101<sup>lo</sup>; during induced airway allergy, resident eosinophils remain unchanged and are accompanied by recruited inflammatory eosinophils (SiglecF<sup>hi</sup> CD62L<sup>-</sup> CD101<sup>hi</sup>).

They postulate a regulatory/homeostatic role for resident eosinophils, noting that mice lacking resident eosinophils showed increased Th2 cell responses to inhaled allergens.

A later review ([Ardain et al, 2020](https://onlinelibrary.wiley.com/doi/full/10.1111/imm.13143)) prefers not to classify them as "tissue resident", because they are relatively short-lived (1-2 days) and need to be continually replenished from blood.

**Comment by addiehl** [comment]
The discussion of resident versus inflammatory eosinophils raises several points:
1) The difference in marker levels, and particularly CD62L, suggests that both these subtypes of eosinophils should be represented in CL.  Per Mesnil (2016) both subtypes stain histologically with eosin dye, and thus can be defined as eosinophils via this classical method.

2)  CL currently defines 'mature eosinophil' as having a 'lobed nucleus', also known as a segmented nucleus.  This distinctive nucleus morphology is seen in all mature granulocytes (neutrophils, basophils, and eosinophils; [PMID:21073711](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3224570/) among many references and textbooks). The ring-shaped nucleus described in Mesnil (2016) for the resident eosiniophils suggests they are immature form per references 66 and 67 in that paper.  Potentially, the resident eosinophils are a subclass of 'band form eosinophil' defined in CL as "A late eosinophilic metamyelocyte in which the nucleus is in the form of a curved or coiled band, not having acquired the typical multilobar shape of the mature basophil [sic]."  Some support for this can be found [here](https://books.google.com/books?id=x1CxsHla5EoC&pg=PA53&lpg=PA53&dq=ringed+nucleus+eosinophil&source=bl&ots=6tAozAs4uj&sig=ACfU3U2LxN4mL5swvIC1_M8wsYlMJ-uX7A&hl=en&sa=X&ved=2ahUKEwiZ79OM0sXpAhXihXIEHcJrB1IQ6AEwDnoECAkQAQ#v=onepage&q=ringed%20nucleus%20eosinophil&f=false).

3) The discussion in Ardain (2019) regarding tissue resident status is very brief.  Arguably, if these cells home to the lung and simply live a brief life there, they could be considered tissue resident, particularly if they play a unique functional role there, as suggested by the mice that lack them.

4) At this time I would propose to define the 'resident eosinophil'/'interalveolar septum eosinophil' via its markers as a subclass of 'band form eosinophil' and that is 'part of' some 'lung parenchyma'.

I am open to further discussion on this proposal.

Alex

**Comment by mkeays** [comment]
Thanks @addiehl -- I will create a 'lung parenchyma resident eosinophil' and include the markers in the definition. The 'interalveolar septum' information comes from annotations from a pathologist we are also working with who explained that the eosinophils in interalveolar septum she refers to are circulating ones in the blood vessels. I think these are distinct from the resident eosinophils characterized by Mesnil et al.

**Comment by dosumis** [comment]
To  follow-up: We need to look at parenchyma terms in Uberon  and see if it is viable to come up with a strategy to wire them up to the rest of the partonomy.

**Comment by mkeays** [comment]
@dosumis OK, sounds good. Also, @addiehl mentioned the definition of [band form eosinophil](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000774) which refers to basophil at the end -- shall I fix that to say 'eosinophil' instead?

**Comment by addiehl** [comment]
Yes, it would be great to fix that error -- probably a copy and paste error years ago.

**Comment by mkeays** [comment]
OK great, I will fix that as part of this work. I'm thinking about how to add the inflammatory eosinophils mentioned above -- I'm not currently sure if they are general inflammatory eosinophils that are found in tissues other than lung or if they are lung-specific.

**Comment by dosumis** [comment]
Hi Maria,  
 - looks like this is done now commit merged.  OK to close?

**Comment by mkeays** [comment]
Yup, closing 👍
