### ISSUE TITLE
Resources for new users

### ISSUE THREAD

**Issue by krcurtis** [obophenotype/cell-ontology#685]
Are there any resources available for getting a new user up to speed with best practices for using the Cell Ontology?

I would like to use the Cell Ontology with markers in flow cytometry and CyTOF to identify cells. I've had some confusing results when exploring markers to identify B-cells.  For example CL_0000236 is the node name for B-cells, but it didn't seem to have any direct link to plasma membrane components (such as via a blind node and a has_plasma_membrane_part property). I did find another B-cell-type node, CL_0001200, lymphocyte of B lineage, CD19-positive, which had a link to CD19.

I saw that OWL supports some inference mechanisms, and I was using rdflib, which perhaps does not support them.  Are there any inference mechanisms used in the Cell Ontology that users should be aware of?

Thanks!

**Comment by krcurtis** [comment]
Thank you for pointing me to FlowCL, I've previous looked at that, and that lead me to the Cell Ontology.

Regarding the logical definition, that raises a couple questions that I had. With the CL in OWL format, the SPARQL queries seem a little bit more verbose than I expected from some earilier papers (Meehan et al. 2011). Below is an example SPARQL query for cells that have a CD19 plasma membrane component (ignoring any issues for the moment with properties like has_high_plasma_membrane_amount). Is that level of verbosity expected? Or is there an easier way?

```
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  PREFIX owl:<http://www.w3.org/2002/07/owl#>
  PREFIX oboinowl:<http://www.geneontology.org/formats/oboInOwl#>
  PREFIX has_pmp: <http://purl.obolibrary.org/obo/RO_0002104>
  SELECT DISTINCT ?x ?celllabel
  WHERE {
    ?marker1 oboinowl:hasExactSynonym "CD19"^^xsd:string .
    ?y owl:someValuesFrom ?marker1 .
    ?y owl:onProperty has_pmp: .
    ?y rdf:type owl:Restriction .
    ?x rdfs:subClassOf ?y .
    ?x rdfs:label ?celllabel .
    ?x a owl:Class .
  }
```

Also is it ever valid to derive cell markers from an ancestor in a cell's lineage?

**Comment by balhoff** [comment]
@krcurtis the RDF rendering of OWL axioms is not very SPARQL-friendly, when the axioms involve complex logical expressions. Also, there are frequently inferences that you would miss when taking this route. One way to deal with this is to use an OWL reasoner to precompute some simpler RDF triples for the purpose of SPARQL queries. I created something like this for CL and some other OBO ontologies, available in a triplestore, but it doesn't have much in the way of documentation (this is making me realize I should work on that). However @dosumis has been using it and I think he has some examples—@dosumis can you point us to anything you've made for working with Ubergraph (if I'm mistaken, no worries)?

Alternatively you can load CL into the Protégé desktop app, and use the ELK reasoner available there. But that requires getting into OWL, and while you can do logical queries you can't really tailor the output as flexibly as with SPARQL.

**Comment by krcurtis** [comment]
Ok, thanks
