### ISSUE TITLE
Revise definitions for CP_0000000 and CP_0000027

### ISSUE THREAD

**Issue by matentzn** [obophenotype/cell-ontology#691]
**CL term**
CP_0000000 (neutrophillic cytoplasm)
CP_0000027 (acidophilic cytoplasm)

**Suggested revision of textual definition**

Currently: `Cytoplasm that exhibits molecular interaction for acidic dyes under specific pH conditions.` (same for both classes)

**Comment by matentzn** [comment]
One of them should be fixed because they are the same.

**Comment by addiehl** [comment]
I think the definitions should both be revised per something like
https://biosci.mcdb.ucsb.edu/immunology/Cells-Organs/blood-cell-morphology.htm
https://www.histology.leeds.ac.uk/what-is-histology/H_and_E.php

CP_0000000 (neutrophillic cytoplasm)
Cytoplasm that exhibits a characteristic staining and color, pale-pink, with Wright-Giemsa stain.

CP_0000027 (acidophilic cytoplasm)
Cytoplasm that exhibits a characteristic staining and color, red or pink, with Eosin stain

**Comment by matentzn** [comment]
That would be great! I will just use those definitions now (to get rid of ROBOT report errors) but I will leave the ticket open for @dosumis to complain.

**Comment by matentzn** [comment]
@addiehl  is your GOC short hand `GOC:add`?

**Comment by addiehl** [comment]
Yes, GOC:add is my GOC initials.
Also, https://orcid.org/0000-0001-9990-8331

**Comment by addiehl** [comment]
Thanks, BTW

**Comment by matentzn** [comment]
Yeah gladly!

**Comment by nicolevasilevsky** [comment]
can this be closed?

**Comment by matentzn** [comment]
Yep was solved long ago.
