### ISSUE TITLE
R1 photoreceptor cell is connected to generic eye, should b part of ommatidium

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#696]
See https://github.com/obophenotype/uberon/issues/1635 for more context

We need more taxon constraints in CL, and/or more specific part-of assignments such that the more comprehensive TCs from Uberon are inheritedd

**Comment by nicolevasilevsky** [comment]
are all of the R receptors part of the ommatidium?
(R2 - R8 photoreceptor cell)

**Comment by cmungall** [comment]
yes all 8

**Comment by nicolevasilevsky** [comment]
did you have a chance to look at the PR? Just want to make sure my approach was correct. :)

**Comment by nicolevasilevsky** [comment]
Just saw your comment on the PR - thanks!
