### ISSUE TITLE
[NTR] CD56-high natural killer cells

### ISSUE THREAD

**Issue by pnejad** [obophenotype/cell-ontology#698]
**Preferred term label:**

CD56-high natural killer cell

**Synonyms**

CD56High NK cell, CD56Bright NK cell,

**Definition (free text, please give PubMed ID)**
"These cells are numerically in the minority in peripheral blood but constitute the majority of NK cells in secondary lymphoid tissues. They are abundant cytokine producers but are only weakly cytotoxic before activation." 

Definition taken from [PMID:19278419](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2673358/)

**Parent term**

natural killer cell?
CL:0000623

**Your nano-attribution (ORCID)**

0000-0002-3163-0115

**Comment by dosumis** [comment]
@addiehl - looks like this one is your area of expertise.  Do you have time to review? (@pnejad works on wrangling HCA data.  We are likely to get many more cell types from her and her colleagues.)

**Comment by addiehl** [comment]
The cell type you are interested in is already in the Cell Ontology:
CD16-negative, CD56-bright natural killer cell
[http://purl.obolibrary.org/obo/CL_0000938](http://purl.obolibrary.org/obo/CL_0000938)
Definition:  NK cell that has the phenotype CD56-bright, CD16-negative, and CD84-positive with the function to secrete interferon-gamma but is not cytotoxic.

-- Alex
