### ISSUE TITLE
Reference CL in Wikidata items about cell types

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#700]
Hello, 

I am interested in better representing knowledge about cell types on Wikidata. There is a Wikidata property for [Cell Ontology ID](https://www.wikidata.org/wiki/Property:P7963) and I would like to link Wikidata articles to their CL IDs. 

However, many of these concepts are not on Wikidata yet. 

I am aware that, as CL is not "CC0", I could not merge all the content. However, its CC-BY release would allow the connection to Wikidata with proper references. 

I would do the following: 

- Create an article for every cell type on CL using only the name (but not the definition, as it does not apply to Wikidata)
- Add an "[instance of](https://www.wikidata.org/wiki/Property:P31) " "[cell type](Q189118)"
- Add an "[subclass of](https://www.wikidata.org/wiki/Q21514624)" linking cell types to their parent classes
- Link the concept to CL using [Cell Ontology ID](https://www.wikidata.org/wiki/Property:P7963)

Using as reference for those statements the property "[reference URL](https://www.wikidata.org/wiki/Property:P854)" pointing to the URI of the concept in the cell ontology. 

It would enrich Wikidata a lot, and allow connections to CL via the Linked Open Data on Wikidata. As a side benefit, this linking may increase the visibility of CL on "spread the word". 

I wanted to open this issue and see your opinions on the subject. Would that be okay, on your perspective? 

Thanks!

**Comment by addiehl** [comment]
I would be in favor of this, but would like other CL editors to weigh in.  I trust that you understand the license issues better than me.

Alex

**Comment by lubianat** [comment]
Hello, @addiehl , 

Do you who else could weigh in on that?

**Comment by addiehl** [comment]
@cmungall @dosumis @alanruttenberg

**Comment by lubianat** [comment]
Hello, @addiehl , while we do not have a position on that, I think I'll start to manually add the [Cell Ontology ID](https://www.wikidata.org/wiki/Property:P7963) cross-reference to cell types that are already present on Wikidata. I guess that would be okay, but if there is any objection please let me know.

**Comment by bvarner-ebi** [comment]
Hi @lubianat, is this ticket still active? If yes, can you assign it to yourself and comment if you need more input. Otherwise, can you close the ticket?

**Comment by lubianat** [comment]
@bvarner-ebi  I did start the manual cross-references; 

I do not know, however, if I could batch-create items on Wikidata for the missing CL cell types. I'll assign to myself and keep it open
