### ISSUE TITLE
[Obsolete] apoptosis fated cell, scaffold cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#708]
No def, no metadata, nothing. Single child, bad smell. wth is a scaffold cell? is this to do with tissue engineering?

![image](https://user-images.githubusercontent.com/50745/93169225-8224b000-f6d9-11ea-8ce5-3252285249dd.png)

**Comment by nicolevasilevsky** [comment]
+1 for obsoleting.

The only thing I can find in a google search about scaffold cells has to do with tissue engineering:
https://www.wikilectures.eu/w/Scaffolds_in_tissue_engineering
