### ISSUE TITLE
neuronal stem cell logical definition is wrong

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#714]
text: Neural stem cell is characterized as an undifferentiated cell that originates from the neuroectoderm and has the capacity both to perpetually self-renew without differentiating and to generate multiple types of lineage-restricted progenitors.

'multi fate stem cell'
 and ('part of' some 'central nervous system')

BAD SMELL: text def massively differing from logical def. See S11 in https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

The logical def is clearly wrong. Consider glial cells, or even resident immune cells, or blood vessel cells.

**Comment by cmungall** [comment]
multi-potent skeletal muscle stem cell also dodgy

**Comment by nicolevasilevsky** [comment]
suggested revisions:
- rename to 'neural stem cell', this seems to the more commonly used name
- proposed revision to the definition: An undifferentiated neural cell that originates from the neuroectoderm and has the capacity both to perpetually self-renew without differentiating and to generate multiple central nervous system neuronal and glial cell types. (source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6710163/)
- remove logical def
- remove asserted superclass 'multi fate stem cell'
- add superclass 'neural cell'

@dosumis @cmungall let me know your thoughts

**Comment by bvarner-ebi** [comment]
@nicolevasilevsky, since there has been no comment on this issue for quite a while, are you comfortable moving forward with your plan outlined above? If not, feel free to add to CL agenda and invite parties who can offer input.

**Comment by nicolevasilevsky** [comment]
sure, I'm fine with moving forward. I can make these changes.
