### ISSUE TITLE
obsolete glial cell sensu X

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#715]
spot the obvious problem:

![image](https://user-images.githubusercontent.com/50745/93172803-67096e80-f6e0-11ea-9630-333fde1518e9.png)

this will be fixed by the axiomatization I am doing (#707) and by fixing the pipeline (#709) which will place the hippocampal ones under veterbrate..

yet the idea of making groupings under glial cell for "Vertebrates" and "Protostomes + Nematodes" is arbitrary and weird and hard to maintain and goes back to CL 2005. We should just obsolete these groupings

**Comment by dosumis** [comment]
Might be interesting to view in the light of evolutionary evidence.  Lower down the hierarchy we probably do need the split.  There are sometimes identical names for very different cells based on rough analogy.

**Comment by nicolevasilevsky** [comment]
I can obsolete terms, if needed - let me know what terms should be obsoleted.

**Comment by cmungall** [comment]
> Might be interesting to view in the light of evolutionary evidence. Lower down the hierarchy we probably do need the split. There are sometimes identical names for very different cells based on rough analogy.

Agreed - I think the current V vs N+protostome split may somewhat approximate this but IMO better to obsolete these now and reinstate groupings as evidence becomes available and/or if we need specific axioms.

@nicolevasilevsky I suggest go ahead and make the obsoletion PRs, we can vote on any controversial ones
