### ISSUE TITLE
obsolete grouping class: metabolising cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#720]
_A cell whose primary function is intermediary metabolism._

![image](https://user-images.githubusercontent.com/50745/93267671-e048a600-f760-11ea-9e74-1bbdf706c8ad.png)

 - 'metabolising cell'
    - 'fat body cell'
    - hepatocyte

Currently this groups two classes: hepatocyte (vertebrates) and fat body cell (note this is presumably intended to represent cells in insect fat bodies, not fat pads in mammals... see #710 ). 

Surely there is more than one metabolising cell per phylum?

If we are going to keep this, then we need a commitment to completeness and clarity. Make a logical def

This will give us:

![image](https://user-images.githubusercontent.com/50745/93268005-5d741b00-f761-11ea-95d5-b1673fa7e647.png)

But is this even complete?  How do we determine 'primary function' anyway?

I think it's simpler just to obsolete the grouping

**Comment by dosumis** [comment]
Happy to obsolete, but thought worth adding some notes:

capable_of some 'metabolic process' is obviously silly (what cell isn't?) as, I think, is the name.  The def is not too bad though: "A cell whose primary function is intermediary metabolism."  Maybe a better way to do this would be to define in terms of specialized metabolic function - with some reference to whole body physiology/metabolic functions.   Human adipocytes would certainly count under this def, e.g. see https://themedicalbiochemistrypage.org/adipose-tissue-not-just-fat/#:~:text=Specific%20metabolic%20processes%20regulated%20by,coagulation)%2C%20and%20blood%20pressure.&text=BAT%20specializes%20in%20the%20production,adaptive%20thermogenesis)%20and%20lipid%20oxidation.

Perhaps more useful than a general grouping, would be to have some cross-species grouping wrt specialized metabolic functions.  Maybe worth a mini-project with GO to ensure we have the terms?
