### ISSUE TITLE
[Logical def] neural cell

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#721]
**CL term**
CL_0002319 'neural cell'

**Suggested revision of logical definition**
Currently the logical def is:
'animal cell' and ('part of' some 'nervous system')

From @cmungall:
This would classify endothelial cells in brain blood vessels as neurons.

This should be revised.

Here is the current inferred hierarchy:
![image](https://user-images.githubusercontent.com/6722114/93269178-5cdc8400-f763-11ea-989a-0e02d103c41b.png)

**Comment by nicolevasilevsky** [comment]
Should we just add the subclass Of axiom:
'part of' some 'nervous system'
?

**Comment by dosumis** [comment]
This points to a general unresolved standards question about the relationship between the brain and its blood supply.   I'd prefer to use located_in or contained_in.   Then 'neural cell', as currently defined, does not cover 'endothelial cell'.  Worth thinking about status of immune cells too.  Don't know if any are truly resident in brain.

**Comment by dosumis** [comment]
Do we really need this grouping term?

**Comment by bvarner-ebi** [comment]
Checking in on this ticket from 2+ years ago.
Any additional thoughts?
I propose to close the ticket if no action item can be defined.

**Comment by nicolevasilevsky** [comment]
I am fine with closing this ticket, I am unsure of how to proceed.

**Comment by bvarner-ebi** [comment]
Closing per requester's approval above. 
Further edits to this class can be tracked in #2064.
