### ISSUE TITLE
Rename and define 'receptor cell'

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#724]
![image](https://user-images.githubusercontent.com/50745/93269740-7af6b400-f764-11ea-8d72-0709e162e866.png)

currently no text def or logical def

I think the intent is such that this should be called 'sensory receptor cell'

TBD:

 - make part of uberon sensory system (thus inheriting TCs)
 - link to GO sensory perception / detection of stiumlus (capable of part of?) (@dosumis ?)

**Comment by cmungall** [comment]
Also: many subclasses should follow a DP, neuronal receptor cell and involves in GO detection of X stimulus involved in perception of Y

**Comment by nicolevasilevsky** [comment]
I took a pass at this, not sure if it is correct, see PR: #729
