### ISSUE TITLE
Review: valve cell

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#726]
![image](https://user-images.githubusercontent.com/50745/93270395-e9884180-f765-11ea-84f7-61897687b75a.png)

 - 'valve cell'
   - 'closable valve cell'
   - 'heart valve cell'
   - 'permanently open valve cell'

none of the terms have text definitions. heart valve cell has a trivial logical definition. None of the 3 children have children

So much wrong here. Seems a weird very general grouping (is it the function of the cell? or the function of the structure the cell is part of)

'heart valve cell' is quite general. Is this 'heart' in the general sense encompassing insect hearts?

In mammals heart valve cells comprise two types: VICs, VECs, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4485434/

Surely it is more useful to include these specific types rather than the grouping?

Does anyone know what the two subtypes based on closability are? Presumably these are exhaustive so why is heart cell not under one of these? I don't see any reference to these in the literature. No defs, no axioms, no children.

I think it can be OK to have functional groupings, but these should at least have children, and the functional groupings in CL should be on the function of the cell not the structure the cell is part of.

IMO cleanest to obselete all of these. More conservatively: obsolete all except HVC, and add two subtypes VIC and VEC

**Comment by nicolevasilevsky** [comment]
seems like these classes may be used in other sources:
http://bioportal.bioontology.org/ontologies/CL/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000664&jump_to_nav=true#mappings

**Comment by cmungall** [comment]
Nope...

 1. the BP mappings are automated
 2. you'll see all of these come from MIREOT (some from very old CLs when we have the purl.org PURLs!)

**Comment by nicolevasilevsky** [comment]
Ah, got it!

**Comment by bvarner-ebi** [comment]
I propose we move forward with the following:

>More conservatively: obsolete all except HVC, and add two subtypes VIC and VEC

'heart valve interstitial cell' is requested in https://github.com/obophenotype/cell-ontology/issues/1736.
I'll plan to add a NTR for 'heart valve endothelial cell' (PMID:[25311230](https://pubmed.ncbi.nlm.nih.gov/25311230)).

**Comment by bvarner-ebi** [comment]
The following classes have been obsoleted:

CL:0000663 'valve cell'
CL:0000664 'closable valve cell'
CL:0000665 'permanently open valve cell'

The obsoleted classes have been replaced by:
CL_1000147 'cardiac valve cell'
