### ISSUE TITLE
obsolete 'lobed nucleus'

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#734]
I'm trying to update GO to use cl-base (see https://github.com/geneontology/go-ontology/issues/19984). Unsatisfiabilities are fixed by the new Uberon release, but now I am running into an inferred equivalence between two 'lobed nucleus' classes.

CL [lobed nucleus](http://purl.obolibrary.org/obo/CP_0000025) and GO [lobed nucleus](http://purl.obolibrary.org/obo/GO_0098537) have identical logical definitions. Could CL obsolete CP:0000025 in favor of the GO term? As a side note, CP is not a registered OBO prefix (there are some [GO problems like this](https://github.com/geneontology/go-ontology/issues/19535) as well); it seems like that should be addressed.

**Comment by dosumis** [comment]
> Could CL obsolete CP:0000025 in favor of the GO term?

That's exactly what we should do.

There are only a handful of CP classes. Most belong in GO.  We should find some other way to retire or move what's left.

**Comment by addiehl** [comment]
I agree with shifting the CP classes to GO where possible, though I thought their phenotypic nature did not support that:
'acidophilic cytoplasm' <http://purl.obolibrary.org/obo/CP_0000027>
'banded nucleus' <http://purl.obolibrary.org/obo/CP_0000039>
'basophilic cytoplasm' <http://purl.obolibrary.org/obo/CP_0000028>
'cartwheel heterochromatin' <http://purl.obolibrary.org/obo/CP_0000043>
'increased nucleus size' <http://purl.obolibrary.org/obo/CP_0000037>
'lobed nucleus' <http://purl.obolibrary.org/obo/CP_0000025>
'neutrophillic cytoplasm' <http://purl.obolibrary.org/obo/CP_0000000>
'polychromatophilic cytoplasm' <http://purl.obolibrary.org/obo/CP_0000035>
'reniform nucleus' <http://purl.obolibrary.org/obo/CP_0000040>

**Comment by dosumis** [comment]
They are certainly types of cellular component.  I think we should just request their addition & see what GO editors say.

The only one that definitely doesn't belong is 'increased nucleus size'  The definition  suggests it should be a PATO term.  "A nucleus size quality which is relatively high compared to the amount of cytoplasm present in the same cell."

Something ilke:

high nuclear/cytoplasmic volume ratio:  A quality inhering in a cell by virtue of the cell having a high nucleus volume to cytoplasmic volume ratio.  [https://en.wikipedia.org/wiki/NC_ratio]

@addiehl would it be possible to add some guidance in a comment about what counts as high?

**Comment by dosumis** [comment]
Looking some more - the x-phillic terms are likely problematic for GO.  They clearly correlate with physical differences between cells, but are also tied to assays.

Perhaps we could find a way to accommodate them as cellular qualities in GO; 

cellular quality
.   -  cellular histological quality: A quality inhering in a cell by virtue of its capacity to be stained by specific histological dyes.
.   .    - cellular acidophilic* histological quality:  A cellular quality inhering in a cell by virtue of its capacity to be stained by acidic dyes.  Comment: in histopathology this is commonly indicated by pale-pink staining with Wright-Giemsa stain.

@addiehl  - does that sound OK to you?  


\* acidophilic should not be used on its own here, as it would be confused with the term used for acid loving microbes

- [ ] Request alternative terms from PATO:
 - 'acidophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000027
 - 'basophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000028
 - 'increased nucleus size' http://purl.obolibrary.org/obo/CP_0000037
 - 'neutrophillic cytoplasm' http://purl.obolibrary.org/obo/CP_0000000
 - 'polychromatophilic cytoplasm' http://purl.obolibrary.org/obo/CP_0000035


- [ ] Request terms from GO:
   - 'banded nucleus' http://purl.obolibrary.org/obo/CP_0000039
   - 'cartwheel heterochromatin' http://purl.obolibrary.org/obo/CP_0000043
   - 'lobed nucleus' http://purl.obolibrary.org/obo/CP_0000025
   - 'reniform nucleus' http://purl.obolibrary.org/obo/CP_0000040

**Comment by addiehl** [comment]
Based on http://lymerick.net/blood-cells.pdf, I would say an N:C ratio expressed as a percentage of the cytoplasm occupied by the nucleus of 50% or higher represents a 'high nuclear/cytoplasmic volume ratio', an "increased nucleus size."  It is difficult to find a great answer as to what constitutes a high ratio, but since lymphocytes have a 50-80% N:C ratio, and are considered to have a 'high nuclear/cytoplasmic volume ratio' per our CL definition ('increased nucleus size') we can take 50% as the low end to be considered to have a high N:C ratio.

**Comment by addiehl** [comment]
I assume you mean cellular qualities in PATO, not GO.  I think your suggested subclasses for 'cellular quality' make sense. And   I agree with your division of these potential term requests from PATO and from GO.
