### ISSUE TITLE
Need reticulospinal neurons added to CL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#74]
```
Need definition. 

Information known so far: reticulospinal neuron is_a neuron, some part of the 
neuron is part_of reticular formations(brain) and Mauthner cell is_a 
reticulospinal neuron (http://neurolex.org/wiki/Nlx_151908).  

NIF doesn't have particular information on the general class of reticulospinal 
neurons.
```

Original issue reported on code.google.com by `cer...@gmail.com` on 20 Jun 2013 at 7:31

**Comment by shawntanzk** [comment]
[NTR]

Term: reticulospinal neurons

def: a neuron with soma location in the reticular formation with axons that extend into the spinal cord such. Reticulospinal neuron activity can lead to a variety of motor behaviors. [PMID:29720934]

synonyms: RSN 

parent term: neuron

Axioms: (might be equiv class - will check if there is any issues with this) 
subclass some neuron
has_soma_location some 'reticular formation' 
'has synaptic IO in region' some 'spinal cord'
