### ISSUE TITLE
NTR extrafusal muscle fiber

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#743]
**Preferred term label:**

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
the skeletal standard muscle fibers that are innervated by alpha motor neurons and generate tension by contracting, thereby allowing for skeletal movement. They make up the large mass of skeletal muscle tissue and are attached to bone by fibrous tissue extensions .' [DOI:10.1016/B978-0-443-10321-6.00004-7,Wikipedia:Extrafusal_muscle_fiber&oldid=978415293]

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

skeletal muscle cell

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

skeletal muscle

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

https://en.wikipedia.org/wiki/Extrafusal_muscle_fiber
Use in definition of alpha nauron

**Comment by paolaroncaglia** [comment]
'extrafusal muscle fiber' was added at the time as CL:0008046, so I'll close.
