### ISSUE TITLE
[NTR] lower motor neuron

### ISSUE THREAD

**Issue by cebriggs7135** [obophenotype/cell-ontology#744]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)
https://en.wikipedia.org/wiki/Lower_motor_neuron
#741 

**Preferred term label:**
lower motor neuron

**Synonyms**
LMN

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Lower motor neurons (LMNs) are motor neurons located in either the anterior grey column, anterior nerve roots (spinal lower motor neurons) or the cranial nerve nuclei of the brainstem and cranial nerves with motor function (cranial nerve lower motor neurons).

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
motor neuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

**Comment by cebriggs7135** [comment]
@dosumis commenting here.

**Comment by lubianat** [comment]
@cebriggs7135 
Wikipedia pages have Wikidata links: https://www.wikidata.org/wiki/Q3916640
From Wikidata, I found a Foundational Model of Anatomy entry for "lower motor neuron": 
https://bioportal.bioontology.org/ontologies/FMA/?p=classes&conceptid=http%3A%2F%2Fpurl.org%2Fsig%2Font%2Ffma%2Ffma84632&jump_to_nav=true 

They might be useful too.

**Comment by dosumis** [comment]
Various OBO foundry ontologies end up on Wikidata.  Unfortunately FMA doesn't have a definition or reference.

**Comment by dosumis** [comment]
Closing as duplicate with #744 which was closed by PR #740
