### ISSUE TITLE
Extrahepatic Bile Duct Epithelial Cell

### ISSUE THREAD

**Issue by rich-brennan** [obophenotype/cell-ontology#755]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Extrahepatic cholangiocyte

**Synonyms**
Extrahepatic Bile Duct Epithelial Cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
An epithelial cell of the extrahepatic portion of the bile duct. Cholangiocytes are the epithelial cells of the bile duct. They are cuboidal epithelium in the small interlobular bile ducts, but become columnar and mucus secreting in larger bile ducts approaching the porta hepatis and the extrahepatic ducts. (PMID:16550043)

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
Cholangiocyte (CL:1000488)

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
extrahepatic bile duct epithelium (UBERON:0004822)

**Your nano-attribution (ORCID)**
0000-0002-0449-2730

**Any additional notes or concerns**
Also consider investigating the relationship between "intrahepatic bile duct epithelial cell" (CL:0002538) and Cholangiocyte (CL:1000488) for which bile duct epithelial cell is a synonym. Perhaps subclassify Cholangiocyte (CL:1000488) with “extrahepatic cholangiocyte” and “intrahepatic cholangiocyte” (which is reasonable since there are morphological and functional differences) and rename  intrahepatic bile duct epithelial cell (CL:0002538) to “intrahepatic cholangiocyte” including “intrahepatic bile duct epithelial cell” as a synonym.

**Comment by mkeays** [comment]
Hi @rich-brennan , I'm actually working on this at the moment :) I've got a related ticket here, almost ready for review: https://github.com/obophenotype/cell-ontology/issues/697

**Comment by rich-brennan** [comment]
Hi Maria,

This ticket (#697<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_obophenotype_cell-2Dontology_issues_697&d=DwMCaQ&c=Dbf9zoswcQ-CRvvI7VX5j3HvibIuT3ZiarcKl5qtMPo&r=R371wBvy7Uz1CadKCOlU0dujKN0lJldd3-jwK0A1nfk&m=82kudcpCBXrB179lK4cxOdwCJVSXFvCNgGurHPYC8dE&s=J6ggUaYxkRyu4ws2k1vY6vlif2pZSnoto_0J16-1EI4&e=>) covers the same topic and seems to have the same recommended resolution. Thanks for picking up on this.

BTW (I’m newby on GitHub) when I submitted the issue a group of 3 other people somehow were assigned to the request – did that happen automatically or did I do something inadvertently to link random, unsuspecting people to the issue? The same thing didn’t happen to my UBERON submissions.

Best,

Richard

Richard Brennan, PhD DABT
Scientific Advisor, Preclinical Safety

richard.brennan@sanofi.com<mailto:richard.brennan@sanofi.com>

Office:  +1 (781) 434 3561
Mobile: +1 (408) 881 3242

153 2nd Avenue, Waltham, MA 02451, USA

[cid:image002.jpg@01D6970D.C28BA8F0]

Please consider the environment before printing this email!

**Comment by nicolevasilevsky** [comment]
> BTW (I’m newby on GitHub) when I submitted the issue a group of 3 other people somehow were assigned to the request – did that happen automatically or did I do something inadvertently to link random, unsuspecting people to the issue? The same thing didn’t happen to my UBERON submissions.

It happened automatically, we created templates in this repo, so certain people are automatically assigned to certain types of tickets.

We have templates in Uberon too, but don't have the automatic assignments set up.

@rich-brennan when you reply to a github ticket via email, it posts your email signature on this public page. I am going to delete it above.

**Comment by mkeays** [comment]
@rich-brennan great, I think I will close this one as #697 seems to cover it. Can update you when the terms are released.
