### ISSUE TITLE
neuron develops-from some vertebrate neuroblast leads to incoherency

### ISSUE THREAD

**Issue by cmungall** [obophenotype/cell-ontology#757]
![image](https://user-images.githubusercontent.com/50745/94725898-5593a980-0311-11eb-999d-b264f8ea344e.png)

**Comment by cmungall** [comment]
the multi-unit eye TC is clearly wrong, presumably intent was to make -ve, likely my error.

Note this unsat only arises on my branch where I am bringing in uberon TCs (for #709)

**Comment by cmungall** [comment]
Side issue for @balhoff 

this makes the TC plugin do weird stuff

![image](https://user-images.githubusercontent.com/50745/94726235-cb981080-0311-11eb-9b52-eb742432035e.png)


branch issue-709-uberon-base to replicate

**Comment by cmungall** [comment]
@dosumis you know most about difference in usage of 'neuroblast' across metazoa, can you recommend action?

We could simply have a GCI, neuron and in some Vert Sub dev-from some Vert neuroblast. But I'd like to pick more at the modeling here:

currently the "nematode and protostome" neuroblast (is this even a meaningful grouping?) has no texture definition. It is a neuronal stem cell (correct)

![image](https://user-images.githubusercontent.com/50745/94733785-1d926380-031d-11eb-8d59-867b37aa1ca5.png)

(suspiciously, the only subclasses of neuronal stem cell are nemo-proto)

in verts it has a definition, but not a stem cell (correct), it's non-terminally differentiated (correct), but is incomplete - no develops-from asserted or inferred:

![image](https://user-images.githubusercontent.com/50745/94735128-19674580-031f-11eb-848f-dbd29dbfdf5d.png)

I don't think any of this is wrong, it just seems suboptimal modeling

in fbbt the genus is neural stem cell though this is not a distinct concept:

![image](https://user-images.githubusercontent.com/50745/94734507-30f1fe80-031e-11eb-97b9-966829ddb05b.png)

in wbbt it's a blast cell. Not sure enough of c elegans development to say if this inconsistent with calling it 

![image](https://user-images.githubusercontent.com/50745/94734672-67c81480-031e-11eb-8a4f-0c5bb984c0d9.png)

None of this is actually wrong, but it seems confusing and incomplete

in verts we presumably want to trace a lineage neuron back to neural stem cells, e.g. via RG cells

**Comment by cmungall** [comment]
going with a GCI, which is not wrong:

![Uploading image.png…]()

**Comment by dosumis** [comment]
GCI is fine.  Discussion of why we need separate sensu terms for vertebrate and invertebrate neuroblasts is here: https://github.com/obophenotype/cell-ontology/issues/617#issuecomment-580862253

> in fbbt the genus is neural stem cell though this is not a distinct concept:

Not needed as neuroblasts are the only neural stem cells in flies (probably true in all arthropods).  I have no idea about nematodes.

Looks to me like radial glia should go under neural stem cell:

"During the late stages of neurogenesis, radial glial cells divide asymmetrically in the ventricular zone, generating a new radial glial cell, as well as a postmitotic neuron or an intermediate progenitor (IPC) daughter cell" https://en.wikipedia.org/wiki/Radial_glial_cell#Progenitors

Don't know whether all vertebrate neuroblasts develop from radial glia though.

**Comment by balhoff** [comment]
This issue is preventing import of `cl-base` into GO.

**Comment by matentzn** [comment]
If someone fixes it I can immediately run a new release.

**Comment by cmungall** [comment]
@matentzn - as soon as the PR check completes successfully, merge and make a new release, thanks!
