### ISSUE TITLE
[NTR] testing123

### ISSUE THREAD

**Issue by cebriggs7135** [obophenotype/cell-ontology#761]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

**Comment by nicolevasilevsky** [comment]
Closing - test from training
