### ISSUE TITLE
[Typo/Bug] Broken link in OBO Foundry Cell Ontology page

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#772]
Hi,

In the [OBO Foundry Cell Ontology page](http://obofoundry.org/ontology/cl.html), in the list on the right, the link next to "Domain" (pointing to "cells") seems broken.

Thanks,
Paola

**Comment by addiehl** [comment]
I went to multiple different info pages for various ontologies, GO, PATO, etc., and the vast majority of the domain links go to 404 file not found pages.  This is not a CL issue, but an OBO Foundry issue.

@cmungall

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky [reported](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1317) this issue in the OBOF tracker, and assigned to @matentzn , so I guess this CL ticket could be closed. What's the CL tracker policy on closing tickets that don't involve edits please: can submitters close if they believe the issue has been addressed (or moved elsewhere)? Or would you rather have tickets left open, for editors to close when they meet/review/make a new release? 
Thanks.

**Comment by matentzn** [comment]
Generally, be confident with closing tickets, no matter who made them - its better to have them re-open the ticket then to spent too much time pondering on whether to close and issue or not. Just make a quick statement why you think the issue should be closed, then say: "Please re-open the ticket if you disagree with my assessment", and that's enough.. :)

**Comment by paolaroncaglia** [comment]
Exactly, thanks @matentzn ;-)
