### ISSUE TITLE
[Typo/Bug] Insane GCI

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#782]
This is bad:

![image](https://user-images.githubusercontent.com/112839/96559369-de6c8800-12b4-11eb-9bfe-290bf8bff449.png)

It needs to go ASAP.

**Comment by nicolevasilevsky** [comment]
what is a GCI?

**Comment by balhoff** [comment]
> what is a GCI?

Loosely, a subclass axiom where there is an anonymous expression (not a named class) on both sides.

**Comment by dosumis** [comment]
Or anonymous class expression on left, named on right

**Comment by dosumis** [comment]
In this case anonymous class expression on left is 'in taxon' some 'Homo Sapiens'.

So all things that are 'in taxon' some 'Homo Sapiens' (where things might include 'anatomical structures', 'biological processes'. ...) have all of the properties on the right - - plasma membrane part endoglin; are capable_of 'neuron differentiation'. etc.

I'm rather surprised it didn't break a whole load of builds.  Might have got through because we don't use 'in taxon' some 'Homo sapiens' much outside of CL.

**Comment by addiehl** [comment]
I don't know anything about the origin of this CGI.  I have never used CGIs in my ontology work.

**Comment by dosumis** [comment]
@addiehl  - wasn't suggesting you added it.  Can you look at the right hand side to see if it looks familiar?  I suspect the left hand side should have been some class you worked on.

(BTW  - you may not be aware of it, but you've added many GCIs to CL: mixing subClassOf and equivalence axioms on a single class produces hidden GCIs.  e.g. if you made a term equivalentTo: 'in Taxon' some 'Homo Sapiens' and added the subClassOf restriction on the right, you would have added a hidden GCI equivalent to the above)
