### ISSUE TITLE
[Synonym] multiciliated cell

### ISSUE THREAD

**Issue by lubianat** [obophenotype/cell-ontology#785]
**CL term**
[multi-ciliated epithelial cell](http://purl.obolibrary.org/obo/CL_0005012
)

**Synonym to be added**
multiciliated epithelial cell
multiciliated cell
multi-ciliated cell
MCC

**broad/exact/narrow/related ?**
broad/exact (not sure if there are non-epithelial multiciliated cells)

**Source**
[Regulation of cilia abundance in multiciliated cells](https://doi.org/10.7554/eLife.44039.001)

**Comment by cmungall** [comment]
I think these should be broad syns, there are many non-metazoan multiciliate eukaryotes
