### ISSUE TITLE
[NTR] zygote

### ISSUE THREAD

**Issue by balhoff** [obophenotype/cell-ontology#786]
**Preferred term label:**

zygote

CL seems to have [animal zygote](http://purl.obolibrary.org/obo/CL_0000365), but not a more general zygote. PO has [plant zygote](http://purl.obolibrary.org/obo/PO_0000423). Should CL provide a superclass for these two?

This request stems from an issue in GO which came to light once I tried to bring in taxon restrictions from CL (revealing that we're using animal zygote in connection with a plant fertilization process): https://github.com/geneontology/go-ontology/issues/20176

**Comment by cmungall** [comment]
Trying to craft best defs for animal and generic

@cooperl09 @ramonawalls I note the PO def of plant zygote is circular:

zygote: A native plant cell (PO:0025606) which is a whole plant (PO:0000003) in the plant zygote stage (PO:0001097).
zygote stage: A sporophyte development stage (PO:0007134) that occurs during the interval between fertilization and the first cell division of the plant zygote (PO:0000423)

**Comment by ramonawalls** [comment]
I think the circularity could be fixed by modify the second definition to get rid of the reference to plant zygote:

zygote stage: A sporophyte development stage (PO:0007134) that occurs during the interval between fertilization and the first cell division.
