### ISSUE TITLE
[NTR]: paneth cell of epithelium of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#787]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
paneth-like cell

**Synonyms**
paneth cell of epithelium of large intestine; paneth-like cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A paneth-like cell that is located in the epithelium of the large intestine PMID: 31753849

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
paneth cell http://purl.obolibrary.org/obo/CL_0000510

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
epithelium of large intestine http://purl.obolibrary.org/obo/UBERON_0001278/

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,
Your requested new term
CL_0009009 'paneth cell of epithelium of large intestine' 
is now in CL and will be visible at the next CL release, scheduled for this week. Thanks.

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'paneth cell of colon' and make it a child term of colon - UBERON:0001155 colon
Sorry we didn't catch this before release

**Comment by paolaroncaglia** [comment]
@sfexova 
CL_0009009 (paneth cell of epithelium of large intestine) is now 
CL_0009009 (paneth cell of colon)
Note, different label but same ID. I kept "paneth cell of epithelium of large intestine" as a broad synonym. Ontobee doesn't record any external use of the term (it was released in January, so that was expected, but I checked just in case).
