### ISSUE TITLE
[NTR]: transit amplifying cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#788]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
transit amplifying cell

**Synonyms**
transient amplifying cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Transit-amplifying cells (TACs) are an undifferentiated population in transition between SCs and differentiated cells. PMID: 24813615

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
stem cell: http://purl.obolibrary.org/obo/CL_0000048

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**
/0000-0003-4183-8865

**Any additional notes or concerns**
transit amplifying stem cells can be derived from stem cell populations in multiple tissues such as intestine and retina so would keep this under stem cell and will request tissue specific flavours  in addition requests as child term of both CL term and specific tissue

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 

Transit-amplifying cells derive from stem cells (see https://pubmed.ncbi.nlm.nih.gov/28835754/: "...During development, stem cells may change first to a pluripotent and highly proliferative state, known as transit-amplifying cells..."). So I wouldn't make TACs a subclass of SCs, but rather a subclass of 'native cell' that derives from SC. @dosumis @addiehl would that be the correct axiomatisation please?

**Comment by ngeorgeebi** [comment]
@paolaroncaglia sounds good

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
The new term CL_0009010 (transit amplifying cell) will be in this week's CL release.
