### ISSUE TITLE
[NTR]: transit amplifying cell of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#789]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
transit amplifying cell of large intestine

**Synonyms**
transit amplifying cell of large intestine; large intestine transit amplifying cell; transient amplifying cell of large intestine; transient amplifying cell of crypt of Lieberkuhn of large intestine

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A rapidly proliferating population of cells that differentiate from stem cells of the intestinal crypt of the large intestine. Stem cells located in the crypts of Lieberkühn give rise to proliferating progenitor or transit amplifying cells that differentiate into the four major epithelial cell types. These include columnar absorptive cells or enterocytes, mucous secreting goblet cells, enteroendocrine cells and Paneth cells. PMID: PMID: 20801415

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
transit amplifying cell - not yet created
intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
crypt of Lieberkuhn of large intestine: http://purl.obolibrary.org/obo/UBERON_0001984

**Your nano-attribution (ORCID)**
/0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
@dosumis 
The proposed definitions for TAC of large/small intestine are the same (see https://github.com/obophenotype/cell-ontology/issues/790). Unless Nancy has suggestions to differentiate the two terms in any way, it looks like these would be more in scope for EFO than CL based on current knowledge. Any objection?
Thanks.
Paola

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
The new term CL_0009011 (transit amplifying cell of large intestine) will be in this week's CL release.

**Comment by sfexova** [comment]
hi @paolaroncaglia, can we please change this term to 'transit amplifying cell of colon' and make it a child term of colon - UBERON:0001155 colon
Sorry we didn't catch this before release
Also, I have my doubts about this being placed under intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250 - I do not think this is the correct parent cell type, transit amplifying cells to my knowledge _differentiate from_ crypt stem cells and are considered commited cells (not stem): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2965634/

**Comment by paolaroncaglia** [comment]
- [ ] 'transit amplifying cell of appendix' should not reason under 'transit amplifying cell of colon'

**Comment by paolaroncaglia** [comment]
Morning @sfexova ,

> Also, I have my doubts about this being placed under intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250 - I do not think this is the correct parent cell type, transit amplifying cells to my knowledge _differentiate from_ crypt stem cells and are considered commited cells (not stem): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2965634/

I agree and this was already axiomatized, see the Term relations side panel in the OLS entry [here](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0009011).

**Comment by paolaroncaglia** [comment]
@sfexova 

> can we please change this term to 'transit amplifying cell of colon' and make it a child term of colon - UBERON:0001155 colon

CL_0009011 (transit amplifying cell of large intestine) is now 'transit amplifying cell of colon'.
