### ISSUE TITLE
NTR: intestinal stem cell

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#79]
```
required to define:

[Term]
id: GO:0036335
name: intestinal stem cell homeostasis
namespace: biological_process
def: "Any biological process involved in the maintenance of the steady-state 
number of intestinal stem cells within a population of cells." [GOC:nhn, 
PMID:22042863]
is_a: GO:0048872  ! homeostasis of number of cells
nformation.


```

Original issue reported on code.google.com by `cmung...@gmail.com` on 28 Jun 2013 at 12:19

**Comment by addiehl** [comment]
I think the CL class 'intestinal crypt stem cell' ([CL:0002250](http://purl.obolibrary.org/obo/CL_0002250)) is the appropriate choice for the required logical definition of GO:0036335, based on a [simple Google search](https://www.google.com/search?client=safari&rls=en&q=intestinal+stem+cell&ie=UTF-8&oe=UTF-8) for "intestinal stem cell" and reading what I found.  Arguably GO:0036335 should be renamed "intestinal crypt stem cell homeostasis," but I will leave that to GO to ponder. 

@cmungall for further review.

**Comment by bvarner-ebi** [comment]
Per @addiehl's comment above, closing this ticket and created this ticket in GO: https://github.com/geneontology/go-ontology/issues/24180.
