### ISSUE TITLE
[NTR]: transit amplifying cell of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#790]
Preferred term label:
transit amplifying cell of crypt of Lieberkuhn of large intestine

Synonyms
transient amplifying cell of small intestine; small intestine transit amplifying cell; small intestine transient amplifying cell; transient amplifying cell of crypt of Lieberkuhn of small intestine

Definition (free text, please give PubMed ID in format PMID:XXXXXX)
A rapidly proliferating population of cells that differentiate from stem cells of the intestinal crypt of the large intestine. Stem cells located in the crypts of Lieberkühn give rise to proliferating progenitor or transit amplifying cells that differentiate into the four major epithelial cell types. These include columnar absorptive cells or enterocytes, mucous secreting goblet cells, enteroendocrine cells and Paneth cells. PMID: PMID: 20801415

Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):
transit amplifying cell - not yet created
intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250

What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon
crypt of Lieberkuhn of small intestine: http://purl.obolibrary.org/obo/UBERON_0001241

Your nano-attribution (ORCID)
/0000-0003-4183-8865

Any additional notes or concerns

**Comment by paolaroncaglia** [comment]
Note for self, see https://github.com/obophenotype/cell-ontology/issues/789#issuecomment-728222082

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
The new term CL_0009012 (transit amplifying cell of small intestine) will be in this week's CL release.
