### ISSUE TITLE
[NTR]: tuft cell of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#791]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
tuft cell of small intestine

**Synonyms**
brush cell of small intestine; tuft cell of epithelium of small intestine; brush cell of epithelium of small intestine; brush cell of epithelium proper of small intestine

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Intestinal tuft cells are a morphologically unique cell type, best characterized by striking microvilli that form an apical tuft. These cells represent approximately 0.5% of gut epithelial cells depending on location. PMID: 29714721

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
brush cell: http://purl.obolibrary.org/obo/CL_0002204
intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
small intestine: http://purl.obolibrary.org/obo/UBERON_0002108

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**
Small intestine version of large intestine brush cell here: http://purl.obolibrary.org/obo/CL_0002203

**Comment by paolaroncaglia** [comment]
Closing this ticket as discussion has moved to https://github.com/obophenotype/cell-ontology/issues/792.

**Comment by paolaroncaglia** [comment]
Hi @sfexova and @ngeorgeebi ,
The new term is CL_0009080 (tuft cell of small intestine).
Thanks,
Paola
