### ISSUE TITLE
[NTR]: stromal cell of lamina propria of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#793]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
stromal cell of lamina propria of large intestine

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A connective tissue cell of an organ found in the loose connective tissue. This cell is found in the lamina propria of the large intestine.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
stromal cell: http://purl.obolibrary.org/obo/CL_0000499

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lamina propria of large intestine: http://purl.obolibrary.org/obo/UBERON_0011189

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
stromal cell of lamina propria of large intestine EFO_0010894
will be in the EFO release scheduled for Nov 16th. 
I'll add the EFO IDs for your other terms in your CL tickets, as your GitHub handle doesn't seem to work in the EFO repo.
Thanks,
Paola
