### ISSUE TITLE
[NTR]: mesothelial cell of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#798]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
mesothelial cell of small intestine

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A mesothelial cell that is part of the small intestine.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
mesothelial cell http://purl.obolibrary.org/obo/CL_0000077

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
small intestine http://purl.obolibrary.org/obo/UBERON_0002108

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
mesothelial cell of small intestine EFO_0010897
