### ISSUE TITLE
[NTR]: mesothelial cell of large intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#799]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
mesothelial cell of large intestine

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Mesothelial cell that resides in the large intestine

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
mesothelial cell http://purl.obolibrary.org/obo/CL_0000077

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
large intestine http://purl.obolibrary.org/obo/UBERON_0000059

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by dosumis** [comment]
This type of generic + location term might be better in EFO (with the same logical definition).  CC @zoependlington 

@ngeorgeebi - if it goes into EFO the term will still end up in the scAtlas application ontology.

**Comment by ngeorgeebi** [comment]
Hi David and Maria ( and the cell ontology team),

I have a large number of cell terms like this. Should I request that they go directly to EFO instead of making new term requests for CL?

Please see the following:

endocrine cell of large interstine
mesothelial cell of large intestine
gastrointestinal tract (lamina propria) macrophage of large intestine
stromal cell of large intestine lamina propria
lymphocyte of large intestine lamina propria
intestinal crypt stem cell of large intestine
Mesothelial cell of small intestine
endocrine cell of small intestine
Peyer's patch T cell
Peyer's patch lymphocyte
Peyer's patch follicular dendritic cell
mesothelial cell of small intestine
lamina propria stromal cell of small intestine
gastrointestinal tract (lamina propria) macrophage of small intestine

Would you be able to let me know of any terms that you would feel fit into this criteria and therefore should be requested directly via EFO instead? 

Very grateful for all your help.
Best
Nancy



> On 29 Oct 2020, at 15:56, David Osumi-Sutherland <notifications@github.com> wrote:
> 
> 
> This type of generic + location term might be better in EFO (with the same logical definition). CC @zoependlington
> 
> @ngeorgeebi - if it goes into EFO the term will still end up in the scAtlas application ontology.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Dr. Nancy George
Bioinformatician
Functional Genomics Group
EMBL - European Bioinformatics Institute
Wellcome Trust Genome Campus, Cambridge UK

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
mesothelial cell of large intestine EFO_0010898

**Comment by sfexova** [comment]
@paolaroncaglia and/or @zoependlington can we please change this term to 'mesothelial cell of colon' and make it a child term of colon - UBERON:0001155 colon

**Comment by paolaroncaglia** [comment]
Note for self: create 'mesothelial cell of colon' (part_of UBERON:0001155 colon) in CL, with a tag for location_grouping subset, and obsolete mesothelial cell of large intestine EFO_0010898? Ask SCA if that would work for them (the EFO term was created before we started adding location grouping terms in CL).

**Comment by sfexova** [comment]
I think that would work fine, we won't need 'mesothelial cell of large intestine' for the anatomograms

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
Looking at this again, if there's definitely no need for 'mesothelial cell of large intestine' for the anatomograms, then I should
- [ ] modify the existing term CL:0009025 'mesothelial cell of large intestine' to become 'mesothelial cell of colon' instead;
- [ ] obsolete EFO_0010898 'mesothelial cell of large intestine' (replace with CL:0009025 'mesothelial cell of colon').

Please let me know if you have any concerns re. SCA pipelines. Thanks.
Paola

**Comment by sfexova** [comment]
I don't see any issues with this plan - thanks!

**Comment by paolaroncaglia** [comment]
Hi @sfexova 
(cc @ngeorgeebi )
CL_0009025 is now 'mesothelial cell of colon' (instead of 'mesothelial cell of large intestine'. The change will be visible with the next CL release. I'll leave this ticket open while I take care of the other action item.
