### ISSUE TITLE
Review: hepatoblast and hepatic stem cell terms

### ISSUE THREAD

**Issue by mshadbolt** [obophenotype/cell-ontology#800]
**CL term (ID and Label)**
CL:0005026 hepatoblast 
CL:0002195 hepatic stem cell

**Reason for deprecation**
I feel like these are the same or similar thing, though I could be wrong. The `hepatoblast` term has a good definition and links to the cells that derive from it while the `hepatic stem cell` seems to be an import from FMA with no references and very generic definition. Not sure if they should be completely merged or just better organised/defined in their hierarchy to reflect that they are very similar/related terms. May need input from a liver expert.

**Term to be merged with (ID and Label)**
Not really sure which term should be retained

**Comment by paolaroncaglia** [comment]
@mshadbolt 
cc @dosumis 

I agree that it’s unclear if the two CL terms for 'hepatoblast' and 'hepatic stem cell' mean the same or not based on their current annotations alone. However, looking at the summary [here](https://www.sciencedirect.com/science/article/pii/S0091679X08000083?via%3Dihub), I suspect that the two don’t fully overlap. I haven’t tried to access the full text, but Google search shows that it contains the following: “Pluripotent cells in liver comprise two populations: hepatic stem cells (HpSCs) and possibly also hepatoblasts (HBs).”

Perhaps we could enlist someone among @emquardokus ' colleagues to help, please?

**Comment by dosumis** [comment]
Looks to me like hepatoblast is used for fetal precursors of hepatocytes; 'hepatic stem cell' is used for self renewing pool of hepatocyte precursors in the adult.  If we need to group we should  add parent class 'hepatocyte precursor'.

**Comment by paolaroncaglia** [comment]
Update: at the CL meeting today, @addiehl suggested (based on PMID:26798363) that hepatoblast is a fetal cell type, while hepatic stem cells exist in the adult liver (there's a subtype in the CL already, 'hepatic oval stem cell'). So we shouldn't merge the two terms. Ideally, we should add some annotations to these terms to clarify the distinction. 
- [ ]

**Comment by mshadbolt** [comment]
ok cool thanks for the clarification, would it be best to close this ticket and start a new one with the change that should be made instead of merging?

**Comment by paolaroncaglia** [comment]
@mshadbolt 

> ok cool thanks for the clarification, would it be best to close this ticket and start a new one with the change that should be made instead of merging?

For brevity and to keep track of the background discussion, I changed this ticket title. It is now assigned to @addiehl , but he warned that the issue is complex and it might take some time to work out the best way to address it (possibly in other branches too). Hopefully that won't prevent HCA curators from using those terms in the meantime, but if you feel otherwise, please let him know. Thanks!

**Comment by mshadbolt** [comment]
ok cool, no it isn't blocking us or anything, I try to make tickets when I notice something weird or confusing so it is recorded but there isn't a rush to fix it from us.

**Comment by emquardokus** [comment]
@paolaroncaglia @mshadbolt A good person to have review would be Anna-Maria Masci (GitHuB: masciam) who is working on our anatomical structures, cell types and biomarkers table for HuBMAP.

**Comment by paolaroncaglia** [comment]
Thanks @emquardokus ,

> A good person to have review would be Anna-Maria Masci (GitHuB: masciam) who is working on our anatomical structures, cell types and biomarkers table for HuBMAP.

@masciam, 
Would you please have a chance to advice on the best way to address this ticket?
Many thanks in advance.
Paola Roncaglia

**Comment by masciam** [comment]
@paolaroncaglia I would say that those are two different type of cells. The hepatoblast derived from the  hepatic stem cell (HpSC) both are fetal and endogenous. The hepatoblast could differentiate into cholangiocyte or hepatocyte. In the liver there some bone marrow derived stem cell  that arrived from the blood exogenous source . So I would keep the two cell types separated.

**Comment by paolaroncaglia** [comment]
@masciam 

> @paolaroncaglia I would say that those are two different type of cells. The hepatoblast derived from the hepatic stem cell (HpSC) both are fetal and endogenous. The hepatoblast could differentiate into cholangiocyte or hepatocyte. In the liver there some bone marrow derived stem cell that arrived from the blood exogenous source . So I would keep the two cell types separated.

Thank you for your helpful feedback! I'll incorporate the information in those CL terms. I'll also add your ORCID as a reference (I found https://orcid.org/0000-0003-1940-6740 - if incorrect please let me know).
Best,
Paola
