### ISSUE TITLE
NTR: Peyer's patch lymphocyte

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#809]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Peyer's patch lymphocyte

**Synonyms**
Peyer's patch resident lymphocyte; small intestine Peyer's patch lymphocyte

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Lymphocytes in Peyer's patches have a major role in driving the immune response to antigens sampled from the intestinal lumen.  PMID: 23525039
These cells also play a role in regulating the formation of follicle-associated epithelium and M cells in Peyer's patches by converting intestitial enterocytes into M cells. PMID: 9252325

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
Lymphocyte: http://purl.obolibrary.org/obo/CL_0000542

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
Peyer's patch: http://purl.obolibrary.org/obo/UBERON_0001211

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Any additional notes or concerns**
Have Peyer's patch B cell and small intestine Peyer's patch T cell as child terms

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
Lastly, the new term CL_0009014 (Peyer's patch lymphocyte) will also be in this week's CL release. Thank you.
