### ISSUE TITLE
Add syns and xrefs for subtypes of glomerular visceral epithelial cell

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#81]
```
{meso,pro} nephric podocyte

and add xref to ZFA

 ZFA:0001673 ! pronephric podocyte
 ZFA:0001674 ! mesonephric podocyte

```

Original issue reported on code.google.com by `cmung...@gmail.com` on 3 Jul 2013 at 9:32

**Comment by paolaroncaglia** [comment]
@bvarner-ebi this is an old ticket about renal cell types with references to non-human vertebrates (ZFA = zebrafish anatomy). As you're going to look into the kidney domain for ASCT+B, it'd be helpful if you could address this ticket too please, to ensure consistency/avoid duplication. If you're ok with that please unassigned me. Thank you!

**Comment by bvarner-ebi** [comment]
Hi, @cerivs, checking in to see if you find the plan above acceptable. Upon approval, I will proceed.

cc @paolaroncaglia, in case you are OK with approving

**Comment by paolaroncaglia** [comment]
@bvarner-ebi your proposal sounds good to me. Thank you.

**Comment by bvarner-ebi** [comment]
@paolaroncaglia, I also see several GO terms that use the original nomenclature, e.g., GO:0061257 'mesonephric glomerular visceral epithelial cell development'.

Should these terms be updated as well? E.g., the above term label would be updated to 'mesonephric podocyte development' and the original label would be added as an exact synonym. Once edited in GO, would those term label changes be reflected in CL after an import refresh?
Should I submit a ticket for a GO editor to make those edits?

**Comment by dosumis** [comment]
I think worth submitting a GO ticket to see if they want to update their term names.

**Comment by bvarner-ebi** [comment]
> I think worth submitting a GO ticket to see if they want to update their term names.

https://github.com/geneontology/go-ontology/issues/23000

**Comment by raymond91125** [comment]
Shouldn't CL:0002525 metanephric glomerular visceral epithelial cell -> metanephric podocyte?

**Comment by bvarner-ebi** [comment]
> Shouldn't CL:0002525 metanephric glomerular visceral epithelial cell -> metanephric podocyte?

Thanks for catching that, @raymond91125. I will update the commit.
