### ISSUE TITLE
NTR: Peyer's patch follicular dendritic cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#810]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Peyer's patch follicular dendritic cell

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Follicular dendritic cell located in the Peyer's patch. These cells from a meshwork in which Peyer's patch B cells reside. PMID: 24437401

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
Follicular dendritic cell: http://purl.obolibrary.org/obo/CL_0000442

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
Peyer's patch: http://purl.obolibrary.org/obo/UBERON_0001211

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
CL_0009015 (Peyer's patch follicular dendritic cell) will be available in the next CL release.
