### ISSUE TITLE
NTR: gastrointestinal tract (lamina propria) macrophage of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#811]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
small intestine lamina propria resident macrophage

**Synonyms**
macrophage of small intestine

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A macrophage which is resident in the lamina propria of the small intestine

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
gastrointestinal tract (lamina propria) macrophage:
http://purl.obolibrary.org/obo/CL_0000865

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

lamina propria of small intestine: http://purl.obolibrary.org/obo/UBERON_0001238

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
You requested 'gastrointestinal tract (lamina propria) macrophage of small intestine'

This already exists in fact:

CL:0000865 'gastrointestinal tract (lamina propria) macrophage'
equivalent to
'gut-associated lymphoid tissue macrophage'
 and ('part of' some 'lamina propria of small intestine')

@dosumis @addiehl 
CL:0000865 has no PMID dbxref or additional info, but the equivalence axiom clearly states small intestine. Should we add an exact synonym "gastrointestinal tract (lamina propria) macrophage of small intestine" and a gloss to the definition "A gut-associated lymphoid tissue macrophage found in the lamina propria of _small intestine_."?

Thanks,
Paola

**Comment by dosumis** [comment]
@addiehl - any preference?
Might be safer to make new term and move restriction to small intestine to logical def of that?

**Comment by paolaroncaglia** [comment]
Resolution from today's HCA/SCA curators call: Paola to convert existing term into a broader parent, and add specific children

**Comment by addiehl** [comment]
1) So the broader parent will be 'gut-associated lymphoid tissue macrophage' without the 'part of' some 'lamina propria of small intestine' axiom?  Will you propose a more general axiom for anatomical localization?

2) What child classes do you foresee:
gastrointestinal tract (lamina propria) macrophage of small intestine?
gastrointestinal tract (lamina propria) macrophage of large intestine?  (assuming this exists)
any others?

Thanks, Alex

**Comment by paolaroncaglia** [comment]
Hi @addiehl ,

>     1. So the broader parent will be 'gut-associated lymphoid tissue macrophage' without the 'part of' some 'lamina propria of small intestine' axiom?  Will you propose a more general axiom for anatomical localization?
> 
>     2. What child classes do you foresee:
>        gastrointestinal tract (lamina propria) macrophage of small intestine?
>        gastrointestinal tract (lamina propria) macrophage of large intestine?  (assuming this exists)
>        any others?

My plan is the following:

- [ ] Edit the existing term CL:0000865 'gastrointestinal tract (lamina propria) macrophage' to make it broader, but only as little broader as necessary, i.e.
from equivalent to 'gut-associated lymphoid tissue macrophage' and ('part of' some 'lamina propria of small intestine')
to equivalent to 'gut-associated lymphoid tissue macrophage' and ('part of' some 'gastrointestinal system lamina propria’)
I’d also add the exact synonyms 
gastrointestinal system (lamina propria) macrophage
macrophage of gastrointestinal system (lamina propria)
The definition doesn’t need changing (it is “A gut-associated lymphoid tissue macrophage found in lamina propria of the gut.”).

- [ ] Create child CL:NEW gastrointestinal tract (lamina propria) macrophage of small intestine (as requested by Nancy)

As for potential additional children, based on Uberon they could be 
‘gastrointestinal tract (lamina propria) macrophage of large intestine’
’gastrointestinal tract (lamina propria) macrophage of funds of stomach’
@ngeorgeebi do you foresee that any of these might be needed? If unlikely or not known, I won’t create them.

Thanks,
Paola

**Comment by ngeorgeebi** [comment]
thanks @paolaroncaglia for pinging me! I know that we will also need this term: gastrointestinal tract (lamina propria) macrophage of large intestine’ but I don't think for now we need the stomach macrophage term.

**Comment by addiehl** [comment]
Sounds good to me

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
@addiehl 
Thank you both for your prompt feedback. I'll update this ticket when the edits are done.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
I've implemented the strategy I described in https://github.com/obophenotype/cell-ontology/issues/811#issuecomment-762979542. Summing up, the terms you need are:

CL_0009007 (gastrointestinal tract (lamina propria) macrophage of small intestine)
CL_0009008 (gastrointestinal tract (lamina propria) macrophage of large intestine)

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
P.S. The new terms will be in the next CL release.
