### ISSUE TITLE
NTR: crypt stem cell of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#813]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
intestinal crypt stem cell of small intestine

**Synonyms**
stem cell of small intestine crypt of Lieberkuhn

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
An intestinal stem cell that is located in the small intestine crypt of Liberkuhn. These stem cells reside at the bottom of crypts in the large intestine and are highly proliferative. They either differentiate eto transit amplifying cells or self-renew to form new stem cells.  PMID: 20683682

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal crypt stem cell: http://purl.obolibrary.org/obo/CL_0002250

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
small intestine: http://purl.obolibrary.org/obo/UBERON_0002108

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi
I added the new term CL_0009017 (intestinal crypt stem cell of small intestine).
It will be in the CL release planned for this week.
Thanks.
