### ISSUE TITLE
NTR: lymphocyte of large intestine lamina propria 

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#814]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
lamina propria lymphocyte of large intestine

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A lymphocyte that resides in the lamina propria of the large intestine

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
lymphocyte : http://purl.obolibrary.org/obo/CL_0000542

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
large intestine: http://purl.obolibrary.org/obo/UBERON_0000059

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
There's this new term too: CL_0009018 (lymphocyte of large intestine lamina propria), will be in this week's CL release.
