### ISSUE TITLE
[NTR] Import BTO term BTO_0002771 "olfactory ensheathing cell"

### ISSUE THREAD

**Issue by anjaf** [obophenotype/cell-ontology#817]
I would like to request the term "olfactory ensheathing cell" to be imported from the The BRENDA Tissue Ontology:
http://purl.obolibrary.org/obo/BTO_0002771

**Preferred term label:**
olfactory ensheathing cell

**Synonyms**
OEC

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
These cells are a specialized type of glial cells found in association with olfactory receptor neurons. They show features of astrocytes and Schwann cells. These cells support the growth of primary olfactory axons from the neuroepithelium in the nasal cavity to the brain.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
http://purl.obolibrary.org/obo/UBERON_0002264

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
http://purl.obolibrary.org/obo/UBERON_0002264

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
This is for Single Cell Expression Atlas work

Thank you!

**Comment by paolaroncaglia** [comment]
@anjaf 
Thanks, this cell type indeed seems to be absent form CL. However, I'm not sure if CL would be keen on importing from BTO, and the BTO term you suggest is ~10 years old. I'd rather create a new CL term and xref BTO. @dosumis any objection please?
Notes for self: could use https://en.wikipedia.org/wiki/Olfactory_ensheathing_cell, but may also need clarification directly from the literature (the Wikipedia entry seems to imply equivalence between macroglia and radial glia, not sure about that). The original paper on OECs is likely https://pubmed.ncbi.nlm.nih.gov/23862023/.

**Comment by addiehl** [comment]
I agree that creating a new term in CL is probably a better choice, with an xref to BTO.  The term should have better references than wikipedia and COPE (which is now behind a paywall), and may benefit from an improved definition.

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky Thank you for adding that term! Is the plan still to try and aim for a CL release around the 10th of each month, please? 

@anjaf the term you requested is CL_0011028 'olfactory ensheathing cell', not released yet. 

@anjaf @dosumis (cc @zoependlington ) A general question: Zoe and I would like to make sure if any action item is required from us, once requested CL (or Uberon, or EFO) terms have been created, to ensure that they make their way to the application ontology for the Single Cell Expression Atlas. Thanks.

**Comment by dosumis** [comment]
If the term is in the scatlas seed (zooma file) and the current CL release, it will be integrated into the scAtlas ontology build. No additional steps needed.
