### ISSUE TITLE
EPIC: Add Patch-seq and connectivity type grouping cell types for mouse motor cortex

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#828]
Transcriptomic clustering reference: 
Yao, Z., Liu, H., Xie, F., Fischer, S., Booeshaghi, A. S., Adkins, R. S., Aldridge, A. I., Ament, S. A., Pinto-Duarte, A., Bartlett, A., Behrens, M. M., Van den Berge, K., Bertagnolli, D., Biancalani, T., Corrada Bravo, H., Casper, T., Colantuoni, C., Creasy, H., Crichton, K., … Mukamel, E. A. (2020). An integrated transcriptomic and epigenomic atlas of mouse primary motor cortex cell types. BioRxiv, 2020.02.29.970558. https://doi.org/10.1101/2020.02.29.970558

Figure below is adapted from fig 2 in this ref showing patch-seq and connectivity type groupings we need to add.
![image](https://user-images.githubusercontent.com/112839/102205131-a8b5db00-3ec2-11eb-9bbb-c70666499fc0.png)

For Patch-Seq data and discussion see: 

Scala, F., Kobak, D., Bernabucci, M., Bernaerts, Y., Cadwell, C. R., Castro, J. R., Hartmanis, L., Jiang, X., Laturnus, S., Miranda, E., Mulherkar, S., Tan, Z. H., Yao, Z., Zeng, H., Sandberg, R., Berens, P., & Tolias, A. S. (2020). Phenotypic variation of transcriptomic cell types in mouse motor cortex. Nature, February. https://doi.org/10.1038/s41586-020-2907-3

This ticket is for general discussion. Individual subtickets should be generated for each term.

Where morphology is referenced, we will also need the relevant morphology terms in PATO: https://github.com/pato-ontology/pato/issues/344

**Comment by dosumis** [comment]
Potentially relevant:

Gouwens, N. W., Sorensen, S. A., Baftizadeh, F., Budzillo, A., Lee, B. R., Jarsky, T., Alfiler, L., Baker, K., Barkan, E., Berry, K., Bertagnolli, D., Bickley, K., Bomben, J., Braun, T., Brouner, K., Casper, T., Crichton, K., Daigle, T. L., Dalley, R., … Zeng, H. (2020). Integrated Morphoelectric and Transcriptomic Classification of Cortical GABAergic Cells. Cell, 183(4), 935-953.e19. https://doi.org/10.1016/j.cell.2020.09.057

Hodge, R. D., Bakken, T. E., Miller, J. A., Smith, K. A., Barkan, E. R., Graybuck, L. T., Close, J. L., Long, B., Johansen, N., Penn, O., Yao, Z., Eggermont, J., Höllt, T., Levi, B. P., Shehata, S. I., Aevermann, B., Beller, A., Bertagnolli, D., Brouner, K., … Lein, E. S. (2019). Conserved cell types with divergent features in human versus mouse cortex. Nature, 573(7772), 61–68. https://doi.org/10.1038/s41586-019-1506-7


CC @jeremymiller - tagging in case you have additional info/refs to add for this.
CC @tgbugs: do you already have NPO term for these?

**Comment by jeremymiller** [comment]
This is the overview publication for everything that has come out about motor cortex and all the related modalities: https://www.biorxiv.org/content/10.1101/2020.10.19.343129v1.  In particular, Figure 10 is an extended version of the figure from the slide in this thread.  Otherwise, you've covered the relevant papers, I think.

**Comment by dosumis** [comment]
CC @shawntanzk

**Comment by dosumis** [comment]
See also https://github.com/patrick-lloyd-ray/cell_set_aligned_alias/blob/main/aligned_aliases.csv

**Comment by dosumis** [comment]
Summary from Shawn here: https://docs.google.com/document/d/112UnWf-SufdlmAOmUz5eNUdgiknYrr0-aGXhupVyUOA/edit

**Comment by dosumis** [comment]
Following discussion with @patrick-lloyd-ray (e.g. [here](https://github.com/obophenotype/cell-ontology/pull/861) and in the above doc +  on our weekly sprint call, we now have reasonable guidelines for textual defintions. @shawntanzk will implement for or priority cell types and make pull requests.

**Comment by shawntanzk** [comment]
Generally done, anything else should have its own ticket
