### ISSUE TITLE
analogous cell types in human and mouse

### ISSUE THREAD

**Issue by amadeusX** [obophenotype/cell-ontology#832]
Hi,
Could you please help me with a list (or some way to generate that list) of analogous human and mouse cell types? Such pairs include K652 and MEL, GM12878 and CH12.LX, and h1-hESC and CJ7, although the latter is somewhat debated.
The evolutionary comparison of human and murine cells is important for several reasons. We are interested in the evolutionary remodeling of transcription factor binding sites between diverse human and mouse primary cell pairs and immortalized cell type pairs. For the latter, matching human and murine cell types is particularly challenging.  
The Encyclopaedia of DNA Elements (ENCODE) Project has compiled such a list long time ago but I could not find that and the ENCODE Help desk is closed for the year. An up-to-date list would be highly appreciated!
Thank you so much!
Steve Ladunga

**Comment by cmungall** [comment]
Hi @amadeusX, I directed you here, but in fact I think you are interested in querying cell *lines*, whereas this ontology is for in-vivo cell *types*. (even though the IDs for this ontology are "CL:..." - confusing!)

I would like to direct you to a place where your question can be answered but a challenge here is there are different ontological representations of cell lines:

 - CLO http://obofoundry.org/ontology/clo (last updated 2 years ago)
 - cellosaurus https://web.expasy.org/cellosaurus/

I note that CLO doesn't seem to have K652, but this is in cellosaurus
https://web.expasy.org/cellosaurus/CVCL_0004

I confess I am not sure how best to determine homology/analogy for cell lines, I suppose you first determine homology of the source in-vivo cells and then look to see if analogous transformations, as well as the sources having some kind of analysis condition (e.g mutation in same gene).

Others here may have ideas!

**Comment by addiehl** [comment]
K652 is probably a typo for [K562 cells](https://en.wikipedia.org/wiki/K562_cells), a fairly widely used erythroleukemia cell line.

I agree that this is a question for the Cell Line Ontology, the Cell Ontology.

One way to relate cell lines that is partly used by CLO is the use of 'derives from' some CL:XXXXXXX logical axiom, to identify putative progenitor cell types that a cell line cell may be derived from.  This may provide some of the information you are interested in mining.

Oliver He, @yongqunh, may be able to provide additional help.

**Comment by amadeusX** [comment]
Hi Alex,

Thank you so much for your suggestions! Indeed, it's K562, sorry for my typo!
The origins of the immortalized cell lines are well documented, both ontologically and traditionally. Unfortunately, even if a human and a mouse cell line were derived from comparable primary cells, that does not necessarily mean that the two derivatives are also comparable. For example, HeLa cells have degenerated wildly during almost the seven decades passed.


Steve

Istvan (Steve) Ladunga


________________________________

**Comment by addiehl** [comment]
Hi Steve,

In the past I (and probably others) have suggested using relations like 'model for' or 'phenotypically similar to' as a way of linking cell line cells to cell types that they are considered experimental models for, but this has not be implemented in CLO or elsewhere as far as I know.  This may represent an opportunity to enrich CLO with this type of information.

Even more interesting would be an ontology of transcriptional program signatures which could be associated with cell line cells in CLO or cell type classes in CL, which could include sets of genes that are co-transcribed, patterns of methylation, or other feature sets that are shared between different cell lines and particular cell types and could serve as a way of demonstrating similarity between and used for matching cell line cells with their in vivo cognates.

Alex

**Comment by amadeusX** [comment]
Hi Alex,
You may have already read these articles: Published: 21 August 2019
Conserved cell types with divergent features in human versus mouse cortex
Rebecca D. Hodge, Trygve E. Bakken, […]Ed S. Lein 
Nature volume 573, pages61–68(2019)  https://www.nature.com/articles/s41586-019-1506-7 and 
![image](https://user-images.githubusercontent.com/15035271/102820951-6a468180-43d6-11eb-850f-5bbf6910b8da.png)
Apart from some trivial primary cells, this is a Herculean task for a large team. However, its is absolutely necessary from both theoretical and practical standpoints.

 Steve

**Comment by addiehl** [comment]
Those are both very interesting papers.  It is unfortunate that we don't have the resources to capture this level of information in CL at this time, but the "provisional cell ontology" presented in Hodge et al. is at least tied into parent classes in CL, so we will hopefully be able to enrich the CL with some new cell type information in the coming year.  I think there's a project at the Allen Institute that will contribute to the CL soon, though I don't think this will help with your original inquiry.

**Comment by amadeusX** [comment]
Thank you very much for your valuable help! I think at this time we can close the issue!

**Comment by yongqunh** [comment]
Thanks for including me. Sorry for my late reply (somehow I got time to read the thread). Yes. The discussion involve CLO. Let me take a look carefully and provide feedback soon.
