### ISSUE TITLE
[NTR] fetal hepatobiliary progenitor cell

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#840]
Cc @pnejad 
Stemming from a request from a Human Cell Atlas curator (https://github.com/HumanCellAtlas/ontology/issues/72):

**Preferred term label:**
fetal hepatobiliary progenitor cell

**Synonyms**
exact synonym: fetal hepatobiliary hybrid progenitor cell
related or narrow synonym (as it’s an abbreviation): HHyP cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A progenitor cell with hepatic and biliary lineage potential, identified in mouse and human, and anatomically restricted to the ductal plate of fetal liver.
PMID:31350390

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
subclass of progenitor cell

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
part of UBERON:0004820 bile duct epithelium
part of UBERON:0000323 late embryo

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-3163-0115

**Any additional notes or concerns**
subset tag: added_for_HCA

I’m unsure about axiomatising any of the markers listed in the [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6659636/). If we did add any, it should be as (‘has plasma membrane part' some [appropriate PRO ID]), but probably avoiding equivalences? @dosumis @addiehl please.

**Comment by paolaroncaglia** [comment]
Note for self and FYI @pnejad: 
I'll add 'fetal hepatobiliary progenitor cell' as soon as the CL editors resolve an issue with merging CL files.
I added the question about markers for discussion at the next CL meeting. Depending on resolution, I might add axioms to the new term, but I'll aim to create the new term first and add details later if I can't do both at once.

**Comment by dosumis** [comment]
Are markers required to distinguish from other, similar cell types?

We probably don't have sufficient logic available for an equivalentClass definition if we need to define wrt developmental potential.

**Comment by paolaroncaglia** [comment]
@dosumis 

> Are markers required to distinguish from other, similar cell types?

Not in this case, no. I noticed some mentions of (potentially not even unique) markers in the paper, hence my question. I'll add the term without markers - better anyway as they could be of limited use in this case. Thanks!

> 
> We probably don't have sufficient logic available for an equivalentClass definition if we need to define wrt developmental potential.

**Comment by paolaroncaglia** [comment]
- [ ] Paola to look for a better anatomy term

**Comment by paolaroncaglia** [comment]
Note for self: do not close this ticket untill all items in https://github.com/obophenotype/cell-ontology/pull/964#issuecomment-791452632 have been addressed.

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,
The new term is CL_0009013 (fetal hepatobiliary progenitor cell).
It will be available at the next CL release (not sure when that'll be, but I'll push for a release soon).
It will then be automatically brought into HCAO via its subset tag.

Quick notes for self:
- [ ] When Uberon is next released, replace CL_0009013 (fetal hepatobiliary progenitor cell) part of bile duct with part of ductal plate
- [ ] Fix synonym HHyP cell (abbreviation/acronym)
- [ ] Add taxon note as appropriate (found/present in Mammalia)

**Comment by paolaroncaglia** [comment]
Note to self - waiting for Uberon release

**Comment by paolaroncaglia** [comment]
Depends on #1255 .
