### ISSUE TITLE
[NTR] Alpha 7 Cell (mus MOp)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#859]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**

Alpha 7 Lamp5 GABAergic interneurons of the primary motor cortex (Mus musculus)

**Synonyms**
ɑ7 Lamp5 MOp (mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**

A GABAergic interneuron of Lamp5 subclass that is strongly labelled for α7 nAChRs. that are located in L1 of the primary motor cortex and have multipolar dendrites with vertically descending axonal collaterals that go deep into the column, usually branching in L5A, but often terminating there. Unlike typical Lamp5 electrophysiology,  alpha7 cells have Vip- and Sst-like firing, with active depolarizing hump at near-threshold membrane potentials, and show larger hyperpolarization sag, stronger burst, and rebound firing

*may have too much details in description 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic interneuron 

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

http://purl.obolibrary.org/obo/UBERON_0001384 - Primary Motor Cortex
*has some soma location, can specify layer

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
Add Lamp5 GABAergic Interneuron as parent

**Comment by patrick-lloyd-ray** [comment]
> that are located in L1 of the primary motor cortex and have multipolar dendrites with vertically descending axonal collaterals that go deep into the column, usually branching in L5A, but often terminating there. 

Suggest: "These cells are located in L1..." rather than "that are located in L1."
