### ISSUE TITLE
[NTR] L2/3 PV-like cell (Mus MOp)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#874]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**

L2/3 Pvalb like Sst GABAergic interneuron of the primary motor cortex (Mus musculus)

**Synonyms**
L2/3 PV-like SST MOp (Mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A Sst GABAergic cortical interneuron transcriptomically between the Sst and the Pvalb families and found in L2/3 of the primary motor cortex. Some L2/3 PV-like SST cells have Martinotti morphology while some have basket cell morphology. L2/3 PV-like SST cells have lower AP width and higher firing rate than typical Sst subclass cells. L2/3 PV-like SST cells have high maximum firing rate variability, with many classified as belonging to the Pvalb subclass on the basis of electrophysiology. 
PMID:33184512

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic interneuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
http://purl.obolibrary.org/obo/UBERON_0001384 - Primary Motor Cortex
*has some soma location, can specify layer

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
subclass of sst interneurons #867

**Comment by shawntanzk** [comment]
@dosumis - should I add expresses some Pvalb in this too? That would make it be both sst and Pvalb interneuron

**Comment by dosumis** [comment]
>  should I add expresses some Pvalb in this too? That would make it be both sst and Pvalb interneuron

Not unless we have direct evidence for expression (across the type). Looks like not on basis of this def. The label (pvalb-like) is good as doesn't imply pvalb expressin. I think this is any example of where property-based classification might start to clash with to clash with transcriptomics-based.   We need to keep an eye on this when we start mixing the two.

**Comment by dosumis** [comment]
Looks like we could make subclasses by morphology.  Please make a ticket for this.
