### ISSUE TITLE
[NTR] Upper FS Basket cell (Mus MOp)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#876]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Upper fast-spiking basket Pvalb GABAergic interneuron of the primary motor cortex (Mus musculus)

**Synonyms**
Upper FS BC PV MOp (Mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A Pvalb GABAergic cortical interneuron in upper L5 and L2/3 of the primary motor cortex that have strong layer-adapting morphology, classical L2/3 basket morphology in L2/3, and mostly large basket cell morphology in upper L5. They are Fast spiking with some showing delayed firing with large latency.
PMID:26612957
PMID:18568015

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic interneuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
http://purl.obolibrary.org/obo/UBERON_0001384 - Primary Motor Cortex
*has some soma location, can specify layer

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
subclass of Pvalb interneurons #868

**Comment by dosumis** [comment]
Add to PCL for now.

**Comment by shawntanzk** [comment]
migrated issue to https://github.com/obophenotype/brain_data_standards_ontologies/issues/225
