### ISSUE TITLE
[NTR]L4 IT (Mus MOp)

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#884]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
L4 intratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)

**Synonyms**
L4 IT MOp (Mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
An intratelencephalic-projecting glutamatergic neuron that is located in the boundary between L2/3 and L5 of the primary motor cortex. These cells have diverse morphologies with some pyramidal and some stellate cells.
PMID:33184512

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
glutamatergic neuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
http://purl.obolibrary.org/obo/UBERON_0001384 - Primary Motor Cortex
*has some soma location, can specify layer

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
xref:(ILX:0770172)
Subclass of L2/3-6 IT projecting neuron #878

**Comment by shawntanzk** [comment]
Not sure if I should include the following information: 

Likely corresponded to the quasi-L4 neurons described previously in the motor cortex. [PMID:25525751](https://pubmed.ncbi.nlm.nih.gov/25525751/). 

The paper quoted also writes: (1) input of primary thalamocortical (TC) axons from VL and PO; (2) output to excitatory neurons in other layers, especially L2/3; (3) largely unidirectional L4→2/3 projections (i.e., little input in return from L2/3), and often, although not as a strict rule, (4) a paucity of long-range corticocortical inputs and outputs.

**Comment by dosumis** [comment]
PCL for now

**Comment by shawntanzk** [comment]
migrated to https://github.com/obophenotype/brain_data_standards_ontologies/issues/226
