### ISSUE TITLE
Corrections on release v2020-01-20

### ISSUE THREAD

**Issue by dosumis** [obophenotype/cell-ontology#892]
Errors to fix in italics

[Term]
id: CL:0019022
name: endothelial cell of pericentral hepatic sinusoid
*synonym: "pericentral LSEC" EXACT [] {comment="PMID:28287163"}*
*property_value: http://purl.org/dc/elements/1.1/creator http://orcid.org/0000-0003-2034-601X*
*property_value: http://purl.org/dc/elements/1.1/date 2020-09-10T12:38:29Z xsd:dateTime*

creator and date need to be fixed more generally - check editors have correct settings.

Wikipedia version dbxrefs e.g. Wikipedia:Alpha_motor_neuron&oldid=957148643

**Comment by bvarner-ebi** [comment]
Closing this issue as it is from Jan 2021, it is unassigned, and there has been no follow up.
