### ISSUE TITLE
[Typo/Bug] CL:4023011 has malformed xref tag

### ISSUE THREAD

**Issue by bkmartinjr** [obophenotype/cell-ontology#930]
CL:4023011, `Lamp5 GABAergic cortical interneuron` has a typo in the xref tag causing parsing failure in some applications.

using OBO from http://purl.obolibrary.org/obo/cl.obo

format-version: 1.2
data-version: releases/2021-02-01

Excerpt of first four tags shows the malformed xref:

```
[Term]
id: CL:4023011
name: Lamp5 GABAergic cortical interneuron
def: "A GABAergic neuron located in the cerebral cortex that expresses Lamp5" [PMID:30382198]
xref: xref (ILX:0770149)
```

I believe the xref should read:  `xref: xref:(ILX\:0770149)`

CC @aopisco

**Comment by tgbugs** [comment]
I think the correct xref is `xref: ILX:0770149`.

**Comment by shawntanzk** [comment]
whoops, will fix all the xrefs of all stuff with ILX I've added

**Comment by bkmartinjr** [comment]
I may have been slightly unclear above.  The actual typo that causes parsing failure was the missing colon in the link.

**Comment by shawntanzk** [comment]
I've just checked and it is already fixed in cl-edit.owl file where the ILX is not prefixed with a "xref:" 
(I'll be honest, I'm not sure if I did that, cause I don't remember doing it, but also I've got horrid memory) 
Not sure how you would want me to handle this, 
should I make edits for main cl file now (kind of scared to touch that file)? or can we just push a release with the current cl-edit? Do let me know. 
Thanks

**Comment by dosumis** [comment]
We can fix it in the next release.  We should do another one soon, as wee need term available for BDS ontology build.

**Comment by dosumis** [comment]
@matentzn  - We should also look into tightening up syntactic tests for xrefs.  I think we already have a soft warning for these.

@bkmartinjr  - It looks like you are parsing the OBO file.  This is a legacy format.  The easiest way to consume the ontology without any need for custom parsing is to use the JSON version: http://purl.obolibrary.org/obo/cl/cl.json. CL terms and relationships between them are in graph[0].

**Comment by matentzn** [comment]
@dosumis What about http://robot.obolibrary.org/report_queries/invalid_xref 
Isnt that sufficient? We should clear the robot report errors and set CI to fail on error...

**Comment by shawntanzk** [comment]
Closing this ticket as I think everything that is working fine now. Please reopen or create new tickets if there is any issues with this still. Thanks
