### ISSUE TITLE
[NTR] several cell type terms to replace EFO terms

### ISSUE THREAD

**Issue by paolaroncaglia** [obophenotype/cell-ontology#932]
Stemming from https://github.com/EBISPOT/efo/issues/880. 
These new CL terms are needed to replace EFO terms in Single Cell Expression Atlas anatomograms:

'central venous hepatic sinusoidal endothelial cell' http://www.ebi.ac.uk/efo/EFO_0010706
=> DONE, use CL:0019022 'endothelial cell of pericentral hepatic sinusoid'

'endometrial glandular epithelial cell' http://www.ebi.ac.uk/efo/EFO_0010710
=> DONE, use CL:0009084 'epithelial cell of endometrial gland' 

'endothelial cell of respiratory system lymphatic vessel' http://www.ebi.ac.uk/efo/EFO_0010667
=> DONE, use CL:0009086 'endothelial cell of respiratory system lymphatic vessel' 

'fused extravillous trophoblast' http://www.ebi.ac.uk/efo/EFO_0010712
=> DONE, use CL:0009087 'fused extravillous trophoblast' 

'lung capillary endothelial cell' http://www.ebi.ac.uk/efo/EFO_0010668
=> DONE, use CL:4028001 'pulmonary capillary endothelial cell' 
CL:4028001 was created very recently by Joshua Fortriede; I added an exact synonym of "lung capillary endothelial cell" to it.

'lung pericyte cell' http://www.ebi.ac.uk/efo/EFO_0010669
=> DONE, use CL:0009089 'lung pericyte' 

'periportal hepatic sinusoidal endothelial cell' http://www.ebi.ac.uk/efo/EFO_0010705
=> DONE, use CL:0019021 'endothelial cell of periportal hepatic sinusoid'

'placental endothelial cell' http://www.ebi.ac.uk/efo/EFO_0010708
=> DONE, use CL:0009092 'endothelial cell of placenta'

'placental smooth muscle cell' http://www.ebi.ac.uk/efo/EFO_0010709
=> DONE, use CL:0009093 'smooth muscle cell of placenta' 

'portal endothelial cell' http://www.ebi.ac.uk/efo/EFO_0010704
=> DONE, use CL:0009094 'endothelial cell of hepatic portal vein'

'uterine endothelial cell' http://www.ebi.ac.uk/efo/EFO_0010711
=> DONE, use CL:0009095 'endothelial cell of uterus' 

(As of Feb 10th 2021, all CL IDs above are released live in CL)

- [x] I'll check if any of these terms have been created in CL since then
- [x] I'll add the location grouping tag where appropriate 
- [x] I'll copy any relevant annotation from the EFO terms
- [x] I'll ask the SCA curators to provide references if needed (none were provided, so I'll go with ORCIDs)
- [x] I'll add the SCA curators ORCIDs (Nancy's is https://orcid.org/0000-0003-4183-8865; Silvie's is https://orcid.org/0000-0003-3440-1876)
- [x] I'll add the EFO IDs as xrefs to the new CL terms, as resolved (see https://github.com/obophenotype/cell-ontology/issues/932#issuecomment-795732369)
- [ ] Warn SCA of pending obsoletion (some months)
- [ ] Obsolete in EFO and add replaced_by tag pointing to Uberon/CL term
- [ ] Remove CL xrefs to EFO terms when these are made obsolete?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi
@sfexova 
Could you please provide references for the terms above? PMID, DOI, ISBN, Wikipedia... 
Also your ORCID please,
Thanks
Paola

**Comment by paolaroncaglia** [comment]
@dosumis 
The label "extravillous trophoblast" is used in both CL and Uberon. I believe that the Uberon term was created first but I can't be sure - it doesn't have annotations, and there's no trace of label or ID in the Uberon GitHub tracker. The CL term was [created by you last year for HCA](https://github.com/obophenotype/cell-ontology/issues/630), should it be labelled "extravillous trophoblast _cell_" and have an equivalence axiom pointing to the Uberon term? If so I'd also add the location_grouping subset tag. Thanks. I will then need to ask the SCEA curators what differentiates a 'fused extravillous trophoblast' from the CL term, because it doesn't have any annotation (http://www.ebi.ac.uk/efo/EFO_0010712).

**Comment by dosumis** [comment]
I think trophoblast is sometimes used to refer to tissue e.g. see https://en.wikipedia.org/wiki/Intermediate_trophoblast.  I wonder whether we should just obsolete Uberon term though and add a replaced_by tag to the CL term.  I think that depends on whether the Uberon grouping does useful work, e.g. by including ECM.

**Comment by paolaroncaglia** [comment]
Thanks @dosumis ,

> Trophoblast is sometimes used to refer to tissue e.g. see https://en.wikipedia.org/wiki/Intermediate_trophoblast. I wonder whether we should just obsolete Uberon term though and add a replaced_by tag to the CL term. I think that depends on whether the Uberon grouping does useful work, e.g. by including ECM.

I'm not sure on the best course of action here, I'd need to do some reading. Unless we can ask for others' opinions?
 
@ngeorgeebi , would you have any reference please for your 'fused extravillous trophoblast'? (It's now http://www.ebi.ac.uk/efo/EFO_0010712)

Thanks,
Paola

**Comment by ngeorgeebi** [comment]
tagging @sfexova for comment

**Comment by paolaroncaglia** [comment]
A procedural note: at the curators call today we agreed on a provisional plan:  
Phase 1: Add to Uberon/CL and link via xrefs to EFO
Warn SCA of pending obsoletion (some months)
Phase2: Obsolete in EFO and add replaced_by tag pointing to Uberon/CL term.

**Comment by paolaroncaglia** [comment]
@sfexova 
Following up on the thread here about 'fused extravillous trophoblast' (http://www.ebi.ac.uk/efo/EFO_0010712), could you please confirm if this term is used in/needed for the placenta anatomogram? I tried looking for it in EA and SCEA, but I suspect that the search by experimental factor function may be broken. Looking for a placenta anatomogram, I could only find [this one](https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-6678/results/anatomogram) linked from an [ExpressionAtlas Twitter post](https://twitter.com/ExpressionAtlas/status/1360191081732845568); it has 'extravillous trophoblast' but not 'fused extravillous trophoblast'. 
No definition or references were provided for EFO_0010712 'fused extravillous trophoblast', there's only a note "Made as a placeholder for AE anatomagrams, term should be requested in UBERON.". So if we are to create a Uberon or CL term to represent this and replace the EFO term, we need more info please (see discussion with David above too).
If no info is available and 'fused extravillous trophoblast' is not needed for anatomograms, I wouldn't create a new term in Uberon or CL, and I'd tag the EFO term for obsoletion.
Thank you,
Paola

**Comment by paolaroncaglia** [comment]
Thanks @sfexova .

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,

Following up on CL term requests for
'central venous hepatic sinusoidal endothelial cell' 
'periportal hepatic sinusoidal endothelial cell' 
'portal endothelial cell' 

based on the reference you provided (https://www.nature.com/articles/s41467-018-06318-7 = PMID:30348985):
“We observed three endothelial cell populations… 
The most abundant endothelial cell cluster … we propose that these endothelial cells are likely periportal LSECs (Zone 1). 
The second most abundant endothelial cell population … we propose that this is an LSEC cluster that is central venous in origin (Zone 2/3).
where LSEC = liver sinusoidal endothelial cell.
Some terms were added by Maria Keays in Sept 2020 which I think fit the descriptions:
periportal LSECs (in paper) = 'periportal hepatic sinusoidal endothelial cell' (in your request) = CL:0019021 'endothelial cell of periportal hepatic sinusoid'
LSEC cluster that is central venous in origin = 'central venous hepatic sinusoidal endothelial cell' = CL:0019022 'endothelial cell of pericentral hepatic sinusoid' (has equivalence axiom “’endothelial cell of hepatic sinusoid' and ('adjacent to' some 'central vein of liver’)”) 
As for 'portal endothelial cell’, do you mean “’endothelial cell' and ('part of' some ‘portal triad’)”? or “’part of' some ‘portal vein’”? The paper doesn’t help.

Please confirm that you can use the 2 existing CL terms, and the anatomical location that 'portal endothelial cell’ should refer to. Thanks.

**Comment by dosumis** [comment]
> On second thought, by 'portal endothelial cell’ you probably mean
’endothelial cell' and ('adjacent to' some 'hepatic portal vein')
but if that's the case, the term wouldn't be part of the liver in the SCA anatomogram. So perhaps
’endothelial cell' and ('part of' some liver) and ('adjacent to' some 'hepatic portal vein').

Unless you are defining a very broad grouping term (e.g. endothelial cell of liver) I think any endothelial cell needs to be part of some vein/vessel/sinusoid (or part of some endothelium of one of these) rather than directly part of the liver.  In this case I think that means either part of the sinusoid adjacent to the 'hepatic portal vein' (but isn't this =  'endothelial cell of periportal hepatic sinusoid' (added by Maria) AKA 'periportal hepatic sinusoidal endothelial cell' ?) or part of the vein itself.

**Comment by paolaroncaglia** [comment]
Hi @dosumis ,

> > On second thought, by 'portal endothelial cell’ you probably mean
> > ’endothelial cell' and ('adjacent to' some 'hepatic portal vein')
> > but if that's the case, the term wouldn't be part of the liver in the SCA anatomogram. So perhaps
> > ’endothelial cell' and ('part of' some liver) and ('adjacent to' some 'hepatic portal vein').
> 
> Unless you are defining a very broad grouping term (e.g. endothelial cell of liver) I think any endothelial cell needs to be part of some vein/vessel/sinusoid (or part of some endothelium of one of these) rather than directly part of the liver. In this case I think that means either part of the sinusoid adjacent to the 'hepatic portal vein' (but isn't this = 'endothelial cell of periportal hepatic sinusoid' (added by Maria) AKA 'periportal hepatic sinusoidal endothelial cell' ?) or part of the vein itself.

Yep, thanks. The existing term 'endothelial cell of periportal hepatic sinusoid' is Equivalent To
'endothelial cell of hepatic sinusoid' and ('adjacent to' some 'portal triad').
So I think the term @sfexova needs for 'portal endothelial cell’ should be Equivalent To
’endothelial cell' and (’part of' some ‘hepatic portal vein’)
and should in fact be labelled, for consistency and completeness, 'endothelial cell of hepatic portal vein', with 'portal endothelial cell’ as a broad synonym. Let me know if you have any objection.

**Comment by paolaroncaglia** [comment]
Added CL_0009084 (epithelial cell of endometrial gland) 
More soon(ish).

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
I hope all's well. FYI, I finished adding CL terms for SCA to replace the previous EFO terms. The new CL IDs are in https://github.com/obophenotype/cell-ontology/issues/932#issue-803754398.

**Comment by paolaroncaglia** [comment]
Note to self: I'm not closing this ticket yet, due to the last 3 checkpoints in https://github.com/obophenotype/cell-ontology/issues/932#issue-803754398.

**Comment by paolaroncaglia** [comment]
Note to self: the CL side of the work is complete; the EFO side is reported [elsewhere](https://github.com/EBISPOT/efo/issues/880#issuecomment-795737707). So I'll close.
