### ISSUE TITLE
B cell has two definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#935]
I'm surprised Protege didn't throw up an error when saving, I've never seen this before.

![image](https://user-images.githubusercontent.com/6722114/107318215-17419000-6a51-11eb-9d7f-e6fdb9aaf2c6.png)

cc @dosumis @addiehl @cmungall @matentzn

**Comment by nicolevasilevsky** [comment]
OLS:
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000236

**Comment by cmungall** [comment]
Protege itself is fine with it. But if we are running standard robot report
we would catch it

**Comment by dosumis** [comment]
I thought we had an OBO cardinality check, but not obvious here:
https://github.com/obophenotype/cell-ontology/tree/master/src/sparql

@matentzn - am i misremembering?

We should probably review the checks that we have and tighten up.

**Comment by matentzn** [comment]
I have
1) Updated to latest ODK
2) Switched CL to fail on ERROR in robot report - duplicate definitions will be caught by ci
https://github.com/obophenotype/cell-ontology/pull/938

**Comment by nicolevasilevsky** [comment]
OOoooh, I see what is happening here. One of these definitions is brought in from PR (it has two labels too).

I don't know how to address this.

**Comment by addiehl** [comment]
The correct current definition is "A lymphocyte of B lineage that is capable of B cell mediated immunity."  The other definition is an earlier definition that was revised to remove the references to markers.  The change was made with PR #622 on February 7, 2020, so not sure how the old definition came back to life, probably due to a merge with a fork created before that date or something.

**Comment by addiehl** [comment]
I will fix this, though we should figure out the underlying cause.

**Comment by addiehl** [comment]
Well, that didn't work.  I now understand Nicole's comment.

**Comment by dosumis** [comment]
What didn't work?

**Comment by addiehl** [comment]
Actually, my changes did stick after the merge, so I appear to have removed the duplicate label and extra definition.

**Comment by dosumis** [comment]
The  offending axioms were in the PR import.  Hope they just got in there from a manual edit in Protege gone wrong.
