### ISSUE TITLE
rename 'skeletal muscle cell' to 'cell of skeletal muscle' ??

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#95]
```
From this commit: https://code.google.com/p/cell-ontology/source/detail?r=270

2. 'skeletal muscle cell' had formal def: EquivalentTo 'muscle cell' that 
part_of some 'skeletal muscle'

But textual def: "Any somatic cell that is part of a skeletal muscle"
Consistent with the textual definition, but not the formal defintion, 'skeletal
muscle satellite cell', which is not a 'muscle cell', was classified underneath
GO textual defs are also consistent with the CL textual definition.

Therefore decided to change formal def to match textual def:

'somatic cell' that part_of some muscle'.

Question: Perhaps name should be changed to 'cell of skeletal muscle', as
'skeletal muscle cell' sounds intuitively like it should be a type of muscle
cell.

```

Original issue reported on code.google.com by `dosu...@gmail.com` on 20 Sep 2013 at 4:33

**Comment by jahilton** [comment]
We (ENCODE project) understand the change in term. However, we also believe the former term 'skeletal muscle cell' should be added as a synonym.
It is common use to refer to these as 'skeletal muscle cell' (example: http://www.sigmaaldrich.com/technical-documents/protocols/biology/human-skeletal-muscle-cells.html)

**Comment by jahilton** [comment]
It seems that CL:0000188 has been changed back to 'skeletal muscle cell', again without adding the alternate term as a synonym.
Is this a permanent change?

**Comment by addiehl** [comment]
(see also #72) CL:0000188 in 2021 has the label 'cell of skeletal muscle' and has 'skeletal muscle cell' as an exact synonym.  I believe this is resolved, so closing.
