### ISSUE TITLE
[NTR] Meis2 cortical GABAergic 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/cell-ontology#966]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Meis2 expressing GABAergic cortical neuron (Mus musculus) 

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A GABAergic type(? - using terminology from reference) located in the cerebral cortex that expresses the gene Meis2 in mouse
PMID:33372656

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic Interneuron? (see below)

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
Cerebral Cortex

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
Not 100% sure about neuronal nature of this given that in Fig 10 of https://www.biorxiv.org/content/10.1101/2020.10.19.343129v1 it is in the "other" box. However, [PMID:33372656 states it as a GABAergic
](https://elifesciences.org/download/aHR0cHM6Ly9jZG4uZWxpZmVzY2llbmNlcy5vcmcvYXJ0aWNsZXMvNTk5MjgvZWxpZmUtNTk5Mjgtc3VwcDItdjIueGxzeA--/elife-59928-supp2-v2.xlsx?_hash=FiWSXqPj3SGTXyKbv%2B4i012DkRMUAtra6Bc99Zn8oN8%3D)

**Comment by shawntanzk** [comment]
@dosumis I can't seem to get what cell type this node should really be. 
There seems to be [Meis2 GABA](https://bioportal.bioontology.org/ontologies/PCL/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0000&jump_to_nav=true) and [Meis2 Glut](https://bioportal.bioontology.org/ontologies/PCL/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0000364&jump_to_nav=true) 
While [PMID:33372656 ](https://pubmed.ncbi.nlm.nih.gov/33372656/) states it is a GABAergic type, the [transcriptomic paper ](https://doi.org/10.1101/2020.02.29.970558)we are basing on seems to suggest non-neuronal/other.

Given how it doesn't seem to be a major cluster (see the clipped image from Fig 2 of the [biorxiv paper](https://doi.org/10.1101/2020.02.29.970558)), perhaps we can consider a full transcriptomics definition to individual leaf nodes on BDS instead (ie the automated definition for BDS)? 
![Screenshot 2021-03-08 at 08 35 36](https://user-images.githubusercontent.com/76212760/110297456-685e8880-7feb-11eb-95a9-1e28162d8b6c.png)

**Comment by dosumis** [comment]
@jeremymiller - we're a bit stuck on this one.  Could you help clarify?

**Comment by jeremymiller** [comment]
Meis2 is a highlight distinct GABAergic type.  It is so distinct that it often (as in this case) shows up in the dendrogram outside the scope of the rest of the neurons.
