### ISSUE TITLE
[NTR]: enteroendocrine cell of small intestine 

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#972]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enteroendocrine cell of small intestine 

**Synonyms**
small intestine enteroendocrine cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enteroendocrine cell located in the epithelium of the small intestine. Enteroendocrine cells are specialized epithelial cells dispersed among mucosal cells of the gastrointestinal tract that represent less than 1% of the entire gut epithelial population. They constitute the largest endocrine organ of the human body, which produces and secretes a variety of hormones or signaling molecules, including gastrin (G cells), ghrelin (P or X cells), somatostatin (D cells), cholecystokinin (CCK) (I cells), serotonin (enterochromaffin cells), glucose-dependent insulinotropic peptide (GIP) (K cells), glucagon-like peptides (GLPs) and peptide YY (PYY) (L cells). PMID: 18185066

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal enteroendocrine cell: http://purl.obolibrary.org/obo/CL_1001516

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
small intestine: http://purl.obolibrary.org/obo/UBERON_0002108

**Your nano-attribution (ORCID)**
ORCID: 0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA thank you! 
@dosumis do @sfexova and I (@ngeorgeebi) need permissions here to assign and tag as well?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
CL:0009006 'enteroendocrine cell of small intestine'
