### ISSUE TITLE
[NTR]: gastrointestinal tract (lamina propria) lymphocyte of small intestine

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#973]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
gastrointestinal tract (lamina propria) lymphocyte of small intestine

**Synonyms**
small intestine lamina propria lymphocyte; small intestine lamina propria leukocyte (LPL); small intestine lamina propria leukocyte; gastrointestinal tract small intestine (lamina propria) leukocyte

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A lymphocyte that resides in the lamina propria of the small intestine. Lamina propria leukocytes  and intraepithelial lymphocytes  are the effector compartments of the gut mucosal immune system. Lymphocytes circulate through gut associated lymphoid tissues until recruitment by intestinal antigens. They are involved in the gut immune response. PMID: 26551552

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
lymphocyte:  http://purl.obolibrary.org/obo/CL_0000542  Copy

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lamina propria of small intestine: http://purl.obolibrary.org/obo/UBERON_0001238

**Your nano-attribution (ORCID)**
orcid.org/0000-0003-4183-8865/

**Any additional notes or concerns**

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA - thanks!

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
I added this as CL_0009044 (lymphocyte of small intestine lamina propria) for consistency with the label of a similar term.
