### ISSUE TITLE
[NTR]: smooth muscle cell of high endothelial venule

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#974]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
smooth muscle cell of high endothelial venule

**Synonyms**
high endothelial venule smooth muscle cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A layer of smooth muscle cells that forms the outer layer of the high endothelial venule and pumps to allow flow of lymph fluid carrying lymphocytes.  PMID: 27881983

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
smooth muscle cell: http://purl.obolibrary.org/obo/CL_0000192

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
high endothelial venule of lymph node: https://github.com/obophenotype/uberon/issues/1754

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**

**Comment by ngeorgeebi** [comment]
@paolaroncaglia please tag with SCA - thanks!

**Comment by paolaroncaglia** [comment]
Waiting for Uberon release.

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi (cc @sfexova ),

The new term is CL_0009049 (smooth muscle cell of high endothelial venule).
Please note: this term has been created as 'smooth muscle cell' and 'part of' some 'high endothelial venule', i.e. _not_ specifically part of 'high endothelial venule of lymph node', as originally requested. Based on the discussion in https://github.com/obophenotype/uberon/issues/1754#issuecomment-853689449, I hope that CL_0009049 (smooth muscle cell of high endothelial venule) can address your needs, but if not please let me know. 

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Update: Nancy needs 'smooth muscle cell of high endothelial venule of lymph node'.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi @sfexova 
CL:0009049 is now 'smooth muscle cell of high endothelial venule of lymph node'.
Shawn is planning a CL release today, so the term should be available to you very soon.
