### ISSUE TITLE
[NTR] embryonic skeletal muscle fiber and neonatal skeletal muscle fiber

### ISSUE THREAD

**Issue by mkeays** [obophenotype/cell-ontology#979]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term labels:**
embryonic skeletal muscle fiber
neonatal skeletal muscle fiber

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
- embryonic: A skeletal muscle fiber found in an embryo. In mammalian embryos, skeletal muscle expresses myosin heavy chain-embryonic (MyHC-emb, encoded by the MYH3), which regulates skeletal muscle development. PMID:7196501|PMID:32094117.
- neonatal: A skeletal muscle fiber found at the fetal and neonatal stages. In mammalian fetuses and neonates, skeletal muscle expresses myosin heavy chain-neonatal (MyHC-neo, encoded by the MYH8 gene). This expression disappears shortly after birth and is replaced by expression of adult heavy chain myosins. PMID:7196501|PMID:26180627.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
- both: [skeletal muscle fiber](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0008002)
- _develops from_ [skeletal muscle myoblast](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000515)

- embryonic: [embryonic cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002321)

How to relate stages?
- embryonic: [embryo stage](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000068)
- neonatal: [neonate stage](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0007221)

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
- [skeletal muscle tissue](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001134)

**Your nano-attribution (ORCID)**
0000-0003-2034-601X

**Any additional notes or concerns**
Not sure how to relate developmental stage.

**Comment by paolaroncaglia** [comment]
@mkeays and CL/UBeron editors
I presume that 'existence starts during' and/or 'existence ends during' would be appropriate relationships to link to embryo/neonate stages, based on the class usage for 'embryo stage' in Uberon. However, it seems that (most) existing embryonic cell types in CL do not use the same relationship nor are linked to 'embryo', so I'm not sure and would welcome your feedback. Thanks.

**Comment by mkeays** [comment]
Thanks @paolaroncaglia . Yes, I had looked at some other embryonic cell types for inspiration and noticed they didn't have any relationship to the stage so I'm not sure what's right.

For now I will add the below, and maybe we can discuss with the others in the call on Wednesday:

- embryonic skeletal muscle fiber: `SubClassOf 'skeletal muscle fiber' and ('existence starts and ends during' some 'embryonic stage'_`
- fetal and neonatal skeletal muscle fiber: `SubClassOf 'skeletal muscle fiber' and ('existence starts during' some 'post-embryonic stage') and ('existence ends during' some 'neonate stage')`

**Comment by paolaroncaglia** [comment]
Note to self:
- [ ] I'll add the terms as per https://github.com/obophenotype/cell-ontology/pull/985 (that PR is old and has risky conflicts).
