### ISSUE TITLE
CL:0000645 pituitcyte - issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#98]
```

def: "A cell with long processes running parallel to adjacent axons in the 
proximal infundibulum of the neurohypophysis. These processes form a 
three-dimensional network among the axons of the hypothalamic neurosecretory 
cells and are connected by gap junctions which provide for their metabolic 
coupling. This cell type constitutes most of the nonexcitable tissue in the 
neurohypophsis; function may include possibly acting as an intermediate in the 
modulation of oxytocin and vasopressin release. This cell type is highly 
variable in size and shape and commonly contain lipid droplets and deposits of 
lipochrome pigment." [ISBN:0412046911, ISBN:0517223651, 
http://en.wikipedia.org/wiki/Pituicyte]
xref: BTO:0003793
xref: FMA:83503
is_a: CL:0000127  ! astrocyte


Is this really an astrocyte? WP says they are similar to astrocyte/glial cells. 
Similar != subclassof.

Also: add part_of link to UBERON:0002198 ! neurohypophysis
```

Original issue reported on code.google.com by `cmung...@gmail.com` on 27 Sep 2013 at 5:30

**Comment by paolaroncaglia** [comment]
Following up on this, [a recent study on "Single-Cell Molecular and Cellular Architecture of the Mouse Neurohypophysis"](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6984808/) (PMID:31915267) supports "the notion that tanycytes and pituicytes are of a common astrocytic lineage" (and the frequent denomination of pituicyte as the main astroglia in the neurohypophysis).
This suggests that the current placement of CL:0000645 'pituicyte' as subclass of 'astrocyte' (and near-sibling of 'tanycyte') is correct. Hence, I will
- [ ] Modify the definition slightly to read "A glial cell of astrocytic lineage with long processes..."
- [ ] Add PMID:31915267 as def dbxref
- [ ] add part_of UBERON:0002198 ! neurohypophysis
