### ISSUE TITLE
[NTR]: germinal center T cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#987]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
germinal center T cell

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A specialized type of CD4 positive T cell, the follicular helper T cell (TFH cell), that upregulates CXCR5 expression to enable its follicular localization. These specialised T cells reside in the germinal center of the lymph node. PMID: 21739669

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
T follicular helper cell: http://purl.obolibrary.org/obo/CL_0002038

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node: http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**
if the T follicular helper cell already in CL refers to a 'resident' TFH cell in the germinal center of lymph node - can make a synonym maybe? i'm under the impression they are two seperate cell types thanks @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Waiting for Uberon release due to work on germinal center terms etc.

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi (cc @sfexova ),

Based on the info you provide in your request above, this new term should be equivalent to
'T follicular helper cell' and 'part of' some 'lymph node germinal center'
(the latter already exists as UBERON:0009039).
As per your question "if the T follicular helper cell already in CL refers to a 'resident' TFH cell in the germinal center of lymph node - can make a synonym maybe? i'm under the impression they are two seperate cell types", 'T follicular helper cell' is textually defined as "located in follicles of secondary lymph nodes that expresses is BCL6-high, ICOS-high and PD1-high", but is not specific to the lymph node germinal center, so we could still create a new, child term for grouping purposes, if needed for the anatomograms. Could you confirm that this is what you'd need, please?

Notes for self:
- [ ] Fix typo in def above ("...expresses is...")
- [ ] Look into this equivalence axiom pointing to an obsolete term (and note that obsolete term appears as live in the axiom list in OLS):
'CD4-positive helper T cell' and ('capable of' some GO_0051024)
There may be others, is there a way to automatically replace obsolete terms with their replaced-by when available? And/or flag them?

**Comment by paolaroncaglia** [comment]
@addiehl 
Hi again. CL:0002038 'T follicular helper cell' is textually defined as "located in follicles of secondary lymph nodes that expresses is BCL6-high, ICOS-high and PD1-high". Should we add a subclass
'part of' some UBERON:0010753 'lymph node secondary follicle'?
I'll remove the redundant "expresses" from the def.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@ngeorgeebi @sfexova 
The new term is CL:0009062 'germinal center T cell' (with exact synonym "lymph node germinal center T follicular helper cell", plus 2 similar ones).
