### ISSUE TITLE
[NTR]: paracortex T cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#988]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
paracortex T cell

**Synonyms**
T cell of lymph node paracortex; paracortical T cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Naïve T cells which arrive into the lymph node via the high endothelial venules enter into the paracortex. Here cortical macrophages and dendritic cells present antigenic peptides to these naïve T cells stimulating them to become activated helper T cells or cytotoxic T lymphocytes. British society for immunology: https://www.immunology.org/public-information/bitesized-immunology/organs-and-tissues/lymph-node#:~:text=The%20outer%20layer%20(Cortex)%20contains,T%20cells%20enter%20the%20node.  

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
T cell: http://purl.obolibrary.org/obo/CL_0000084

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node: http://purl.obolibrary.org/obo/UBERON_0000029

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**
Maybe subset of naive T cell instead? Also couldn't find a generic enough paper. Sources are the ref'd website and the Encyclopaedia Brittanica - not sure how to cite those! sorry!

**Comment by paolaroncaglia** [comment]
Waiting for Uberon release with paracortex term.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] UBERON:8410066 lymph node paracortex is live in Uberon, but not imported into CL yet

**Comment by paolaroncaglia** [comment]
@ngeorgeebi @sfexova 
The new term is CL:0009064 'lymph node paracortex T cell' (with broad synonym 'paracortex T cell').
