### ISSUE TITLE
[Class hierarchy]: lymph node tingible body macrophage

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#989]
**CL term**
lymph node tingible body macrophage: http://purl.obolibrary.org/obo/CL_0000888

**Suggested revision and reasons**
Could we have part of lymph node instead of part of lymph node cortex? This is for the SCA project - thanks!

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi (and @sfexova ),

> lymph node tingible body macrophage: http://purl.obolibrary.org/obo/CL_0000888
> Could we have part of lymph node instead of part of lymph node cortex? This is for the SCA project - thanks!

'lymph node tingible body macrophage' is 'part of' some 'cortex of lymph node'
and
'cortex of lymph node' is 'part of' some 'lymph node'
so from an ontology point of view it'd be redundant to state that 'lymph node tingible body macrophage' is 'part of' some 'lymph node'. I've seen this type of request in other SCA tickets, are the anatomograms somehow unable to display or imply the ancestry of a term other than its direct is_a and part_of parents? Or are there reasons that I'm missing?
If this is an issue that requires discussion, please add to the agenda for our next curators meeting on July 14th.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Discussed at curators meeting today, Silvie confirmed that redundant part_of links are not needed for anatomograms.
