### ISSUE TITLE
[NTR]: medullary plasma cell

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#992]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
medullary plasma cell

**Synonyms**
plasma cell of medullary sinus; medullary sinus plasma cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A plasma cell that is located in the medullary sinus of the lymph node.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
plasma cell: http://purl.obolibrary.org/obo/CL_0000786

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
lymph node: http://purl.obolibrary.org/obo/CL_0000786

**Your nano-attribution (ORCID)**
0000-0003-4183-8865

**Any additional notes or concerns**
Part of anatomograms project with SCA - @paolaroncaglia. Sorry for the definition - i couldln't find a specific location-related role for these cells but we have them as a cell shape in the anatomogram. Maybe for EFO?

**Comment by paolaroncaglia** [comment]
@ngeorgeebi and @sfexova 
This request is for "A plasma cell that is located in the _medullary sinus of the lymph node_.", so the correct part_of parent would be Uberon 'lymph node medullary sinus', not the broader 'lymph node' as you suggested. 'lymph node medullary sinus'is part of 'medulla of lymph node' which is part of 'lymph node'. May I go ahead and create the term as part of 'lymph node medullary sinus', or is there an issue similar to https://github.com/obophenotype/cell-ontology/issues/989#issuecomment-874624066?

Thanks in advance for your feedback.
Paola

**Comment by paolaroncaglia** [comment]
Also, re. new term label(s), we should keep in mind Alex's comment [here](https://github.com/obophenotype/cell-ontology/issues/1001#issuecomment-804327087).

**Comment by paolaroncaglia** [comment]
Re. part_of parents: discussed at curators meeting today, Silvie confirmed that redundant part_of links are not needed for anatomograms.

**Comment by paolaroncaglia** [comment]
@ngeorgeebi (cc @sfexova )
The new term is CL_0009059 (plasma cell of medullary sinus of lymph node).
