### ISSUE TITLE
[Class hierarchy]: lymphocyte

### ISSUE THREAD

**Issue by ngeorgeebi** [obophenotype/cell-ontology#993]
**CL term**
lymphocyte: http://purl.obolibrary.org/obo/CL_0000542

**Suggested revision and reasons**
Can this have part of lymph node relationship added please? This is part of the SCA project anatomograms

**Comment by addiehl** [comment]
It is not appropriate at all for 'lymphocyte' to have a part of 'lymph node' relationship.  Lymphocytes include B cells, T cells, and innate lymphoid cells and are found in in the blood and in various tissues and organs throughout the body.

Alex

**Comment by ngeorgeebi** [comment]
@addiehl thanks for the feedback - I agree that this is a generic term for a whole class of cell. However, I was considering whether it would be a good workaround to have lymphocyte as lymph node as a term to fit our anatomograms project better. Thanks!

**Comment by addiehl** [comment]
Some generic cell types simply should not be localized on an anatomogram.

**Comment by dosumis** [comment]
> Some generic cell types simply should not be localized on an anatomogram.

Agree, but we did discuss on call adding subclasses by location, so would you consider 'lymphocyte of lymph gland'?  Agree this example might seem like a step too far, but also worried that we are dealing difficult to define lines for these grouping terms.  e.g. would 'lymphocyte of lymph gland' be worse than 'T cell of Peyer's patch'?

**Comment by addiehl** [comment]
I'm not going to stop 'lymphocyte of lymph node' but it is a term that is too generic to be useful to most uses of the Cell Ontology, similar to something like neuron of 'hippocampal formation'.  Even worse perhaps as there are many lymph nodes across the body and they are not perfectly identical in their cell content or function (though fairly similar).
