### ISSUE TITLE
[NTR]tuft cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#994]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
tuft cell of appendix

**Synonyms**
tuft cell of appendix vermiformis
tuft cell of vermiform appendix

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Tuft cell that is a part of a vermiform appendix. Intestinal tuft cells are a morphologically unique cell type, best characterized by striking microvilli that form an apical tuft. They are known to express express chemosensory receptors. Tuft cells form lateral projections from the basolateral membrane which associate with neighboring cell nuclei. PMID:29714721

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal tuft cell http://purl.obolibrary.org/obo/CL_0019032

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**
this is a part of series of appendix vermiformis cells, some of these cell types already exist in CL - e.g. 'appendix goblet cell'. It would be good to keep the term label style as consistent as possible across the whole batch so I used just 'appendix' rather than the full 'vermiform appendix' but do not mind either.

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,

I added CL_0009020 (tuft cell of appendix). It will be available with the next CL release. There isn't a set date yet, but I'll push for a release soon (ideally after I've added a few more cell types for you and @ngeorgeebi ).
On a general note, the definitions you provided for each “x cell of appendix” term describe what x cells and appendix are, but we don’t need to repeat those descriptions as they can be looked via the parent terms. So I didn’t include those descriptions, and kept only the generic pattern definition “An x cell that is part of a vermiform appendix” (except where a specific description was included). Similarly, most of the PMIDs you provided refer to the x cells, and are not specific to x cells in the context of appendix, so I didn’t include them unless they were in fact specific and informative for the new term.

Thanks,
Paola
