### ISSUE TITLE
[NTR]enterocyte of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#995]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
enterocyte of appendix

**Synonyms**
enterocyte of appendix vermiformis
enterocyte of vermiform appendix

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Enterocyte that is a part of vermiform appendix. Enterocytes are columnar cells with ditinctive microvilli in the apical surface and they form most of the epithelium of the gut intestine. The main function of enterocytes is absorbing molecules from the gut lumen and transport them to inner connective tissue and blood vessels. PMID: 15925533

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
enterocyte http://purl.obolibrary.org/obo/CL_0000584

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
Hi @sfexova ,
This will be CL_0009026 (enterocyte of appendix).
