### ISSUE TITLE
[NTR]transit amplifying cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#996]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
transit amplifying cell of appendix

**Synonyms**
transit amplifying cell of vermiform appendix
transit amplifying cell of appendix vermiformis

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Rapidly proliferating population of cells that differentiate from stem cells of the intestinal crypt of the appendix vermiformis. Stem cells located in the crypts of Lieberkühn give rise to proliferating progenitor or transit amplifying cells that differentiate into the four major epithelial cell types. These include columnar absorptive cells or enterocytes, mucous secreting goblet cells, enteroendocrine cells and paneth cells. [ http://www.ncbi.nlm.nih.gov/pubmed/20801415 http://orcid.org/0000-0003-4183-8865 ] 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
transit amplifying cell http://purl.obolibrary.org/obo/CL_0009010

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
crypt of Lieberkuhn of appendix http://purl.obolibrary.org/obo/UBERON_0013486

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
This will be CL_0009027 (transit amplifying cell of appendix).
