### ISSUE TITLE
[NTR]intestinal crypt stem cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#998]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
intestinal crypt stem cell of appendix

**Synonyms**
intestinal crypt stem cell of vermiform appendix
intestinal crypt stem cell of appendix vermiformis
stem cell of intestinal crypt of Lieberkuhn of appendix vermiformis
stem cell of intestinal crypt of Lieberkuhn of appendix

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Intestinal crypt stem cell that is located in the vermiform appendix. These stem cells reside at the bottom of crypts in the appendix and are highly proliferative. They either differentiate into transit amplifying cells or self-renew to form new stem cells. PMID:20683682 

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
intestinal crypt stem cell http://purl.obolibrary.org/obo/CL_0002250

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
crypt of Lieberkuhn of appendix http://purl.obolibrary.org/obo/UBERON_0013486

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 
Last one for today: CL_0009028 (intestinal crypt stem cell of appendix). Thanks,
Paola
