### ISSUE TITLE
[NTR]mesothelial cell of appendix

### ISSUE THREAD

**Issue by sfexova** [obophenotype/cell-ontology#999]
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
mesothelial cell of appendix

**Synonyms**
mesothelial cell of vermiform appendix
mesothelial cell of appendix vermiformis

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Mesothelial cell that is located in the vermiform appendix. Mesothelial cells form a monolayer of specialised pavement-like cells that line the body's serous cavities and internal organs. The primary function of this layer, termed the mesothelium, is to provide a slippery, non-adhesive and protective surface. PMID: 14592528

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
mesothelial cell http://purl.obolibrary.org/obo/CL_0000077

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
vermiform appendix http://purl.obolibrary.org/obo/UBERON_0001154

**Your nano-attribution (ORCID)**
0000-0003-3440-1876

**Any additional notes or concerns**

**Comment by paolaroncaglia** [comment]
@sfexova 

CL_0009029 (mesothelial cell of appendix)
will be in the next CL release, which might be as soon as tomorrow.

BTW, in case you don't subscribe to all notifications from the CL repo, which I'd understand: if helpful, you and @ngeorgeebi may still be notified of CL releases if you set your CL repo "watch" option to custom and then choose "releases". Same for the Uberon GitHub repo.

Best,
Paola
